### ISSUE TITLE
clean up multilabel code

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1005]
1) some multilabel measures sport "for-loops". Pls remove them

2) all multilabel wrappers basically have the same copy-paste example! please try to spot this. it is also on a dontrun block. lets have one example and reference this one from the other places. and the example should be without dontrun if possible.

@giuseppec 
@PhilippPro 

can you please resolve this asap?

**Comment by giuseppec** [comment]
I started a branch https://github.com/mlr-org/mlr/tree/cleanup_multilabel and will do the first iteration, @PhilippPro I'll give you a sign when you can do the second iteration, hope this is okay.

**Comment by PhilippPro** [comment]
yes

**Comment by giuseppec** [comment]
@PhilippPro I did some changes regarding 1) in https://github.com/mlr-org/mlr/pull/1019. Could you do 2) and remove the examaples as bernd mentioned?

**Comment by PhilippPro** [comment]
Done.

**Comment by berndbischl** [comment]
i think the PRs for this are still not merged?
