### ISSUE TITLE
clean up measure brier.sc code

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1006]
see my comments in this PR #861

**Comment by berndbischl** [comment]
```

the measure does NOT contain docs for what it actually does
there is NO REAL unit tests. a real unit test would actually compare a handcalculated result on a mini-data situation with the result of the measure.

```

**Comment by berndbischl** [comment]
also I do agree that brier.scaled is really a better name

**Comment by berndbischl** [comment]
@larskotthoff 
would you please clean this up so we can close this quickly

**Comment by larskotthoff** [comment]
Well, both documentation and test are exactly like for the other measures. I asked about the name 2 months ago and never got a reply.

I'm not sure what you're looking for here. Renaming is easily done, but if we start documenting measures and/or testing them differently, this should be done consistently.

**Comment by berndbischl** [comment]
> Well, both documentation and test are exactly like for the other measures. I asked about the name 2 months ago and never got a reply.

simply ask again then. sometimes we overlook stuff..... too many issues.

> I'm not sure what you're looking for here. Renaming is easily done, but if we start documenting measures and/or testing them differently, this should be done consistentl

we kinda do this consistently. 
a) check measures.R. all non-standard measures contain a little note that gives a hint to the user what happens.
b) check test_base_measures
test_that("check measure calculations"
this contains at least one handcrafted check per measure
(note that we had bugs here for some esoteric measures, and this is something thats REALLY bad for users)

**Comment by berndbischl** [comment]
regarding the docs: 
if its called "accuracy" everbody in ML knows what we compute here. if its called brier.sc, nobody knows what it is. and you also have no chance of figuring this out (except for reading sources). which makes the object pretty useless....

**Comment by berndbischl** [comment]
(and with the last comment i am not referring mainly to the name of the measure. if its called brier.scaled, a better name, i still dont know what it is)

**Comment by larskotthoff** [comment]
Regarding docs: The note for the existing Brier score says "Brier score" -- based on that, "Brier scaled" seems acceptable (although I guess it could say what it's scaled to).

Regarding the tests: Same thing there. Brier.sc uses the same test as Brier.

Like I said, this is probably something that can be improved in general.
