### ISSUE TITLE
Transductive learning in MLR?

### ISSUE THREAD

**Issue by mansarin** [mlr-org/mlr#1011]
Hi,

Are there any transductive learning methods implemented already in the MLR learners? I did a quick search and couldn't find anything. By transductive, I mean that they would be able to use both the test and training data sets to "train" the learner (both labels and features from training, and only features from testing set). One example of a transductive learner is support vector machines, but they seem to be implemented inductively here. [Here's a transductive learning example from another R package](http://r.gmum.net/getting_started.html).

I am pretty new to machine learning in general, so I expect that there is a lot I am missing. Please help me out if this is the case.

**Comment by mansarin** [comment]
Lars,

Thanks. Does that mean that I'd also be unable to integrate such an algorithm as a new learner, within MLR?

**Comment by larskotthoff** [comment]
Not necessarily, but it won't be entirely straightforward. In particular things like performance measures may not work unmodified.

**Comment by berndbischl** [comment]
hi.

transductive learning is not really supported at the moment in mlr, although it may or may not be possible to a "hack" a learner into mlr which somehow does this. the proper solution would be to first create a new TaskClass. 

A few further questions:

Transductive learning would, at least from a usage standpoint, the same as semisupervised?
So I pass a bunch of data in, but some y = NA, as those are not labeled. 

Semisupervised is then just different, as the model should be "inductive", the training be hopefully improved by the unlabeled data, and I would ask for predictions on any potential x-points.

For transductive, the model training works differently and as a user i would only ask for predictions at the unlabeled data points that i passed in during training.

just thinking about whether one could kill 2 birds with 1 stone, so semisupervised and transductive could be represented in the same fashion...?

**Comment by mansarin** [comment]
Bernd,

Thanks for your response. Transductive learning is indeed a form of semi-supervised learning, along with inductive learning. In TL, you're interested in just finding the labels for the unlabeled data. In IL, you're not only interested in labeling the unlabeled instances, but also finding a generalization (= a model) that can be applied to new instances (i.e. instances apart from the training and testing set that you have already) when they arrive. I think I just restated what you have already written.

Semi-supervised and transductive should have different task classes, but that's my guess: since one wants a generalized model, and the other wants to avoid it. Perhaps "semi-supervised" tasks could be the semi-supervised inductive learning approach, and "transductive" tasks could be the SS TL approach?
