### ISSUE TITLE
trafo argument ignored

### ISSUE THREAD

**Issue by MasonGallo** [mlr-org/mlr#1015]
`tuneGrid` by default ignores trafo without presenting the choice to the user. This may result in different than expected grids! Perhaps we should check if trafo exists rather than assuming False?

**Comment by jakob-r** [comment]
I will have a look at it tomorrow.

**Comment by berndbischl** [comment]
@MasonGallo 

can you please post for stuff like these mini examples? otherwise we cannot discuss this.

**Comment by MasonGallo** [comment]
@berndbischl Sure:

```
ps1 = makeParamSet(makeNumericParam(id = "C", lower = -1, upper = 1))
generateGridDesign(ps1, resolution = 10L)

            C
1  -1.0000000
2  -0.7777778
3  -0.5555556
4  -0.3333333
5  -0.1111111
6   0.1111111
7   0.3333333
8   0.5555556
9   0.7777778
10  1.0000000

ps2 = makeParamSet(makeNumericParam(id = "C", lower = -1, upper = 1, 
                                    trafo = function(x) 2^x))
generateGridDesign(ps2, resolution = 10L)
```
This returns the same:

 ```   
            C
1  -1.0000000
2  -0.7777778
3  -0.5555556
4  -0.3333333
5  -0.1111111
6   0.1111111
7   0.3333333
8   0.5555556
9   0.7777778
10  1.0000000
```

However, this is probably not what the user expected since if we did
```
seq(2^-1, 2^1, length.out = 10L)
[1] 0.5000000 0.6666667 0.8333333 1.0000000 1.1666667 1.3333333 1.5000000 1.6666667 1.8333333
[10] 2.0000000
```

This means we might search different hyperparameter space than we expected (or at least it's not 100% clear to me). `tuneGrid` does not consider trafo therefore `generateGridDesign` always defaults to False.

**Comment by berndbischl** [comment]
you have posted an example for generateGridDesign. That is a function from PH and that has a documented argument "trafo"....?

**Comment by MasonGallo** [comment]
https://github.com/mlr-org/mlr/blob/be30fcd9c6e408e96364dd3a0a6ee2691942e80d/R/tuneGrid.R

`tuneGrid` calls `generateGridDesign` with trafo always set to False

**Comment by MasonGallo** [comment]
But either way, the behavior is a bit confusing to me, even if I manually set trafo to True as indicated above

**Comment by berndbischl** [comment]
yes. and now look into evalOptimizationStates.R. there you find in line 21 ...?

can we please discuss with by looking at a CONRETE and COMPLETE example where something either wrong or confusing happens, please?

**Comment by berndbischl** [comment]
the grid search produces a grid on the untransformed scale. then in evalOptimizationStates the generic trafo happens, as for all other tuners. 

so from my perspective everything is correct. which is why i directly need to see the usecase where you apparently have a problem....

**Comment by MasonGallo** [comment]
When I generate a grid using trafo, it still makes the same grid which is confusing. For example, I would expect `ps2` to make a grid with 10 steps from 2^-1 to 2^1 but instead it makes the grid from -1:1 then raises. Ex:

```
generateGridDesign(ps2, resolution = 10L, trafo = T)
           C
1  0.5000000
2  0.5832645
3  0.6803950
4  0.7937005
5  0.9258747
6  1.0800597
7  1.2599210
8  1.4697345
9  1.7144880
10 2.0000000
```

But then:

```
seq(2^-1, 2^1, length.out = 10L)
[1] 0.5000000 0.6666667 0.8333333 1.0000000 1.1666667 1.3333333 1.5000000 1.6666667 1.8333333
[10] 2.0000000
```

I find this confusing. I saw the trafo arg for `generateGridDesign` is never actually called, so I wondered if that was intentional? Sounds like this is intended, so maybe it's a documentation issue? I am also not sure if this is more of a issue for PH or mlr now that you mention it.

**Comment by MasonGallo** [comment]
@berndbischl and I discussed improving documentation

**Comment by berndbischl** [comment]
@MasonGallo 

here s what i added to docs

https://github.com/berndbischl/ParamHelpers/commit/43c312e0de56f183ad17ef596f8511447c810883

regarding further doc improvements or the making the tuning part of the tutorial better:
very happy if you help out there!
