### ISSUE TITLE
measures PPV, TPR, FPR corner cases

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#1016]
For PPV, TPR and FPR the value NaN is returned when the denominator is zero. 
For Multilabel PPV return 1 when denominator is zero, see:

```
measurePPV(c(1,1,1), rep(0, 3), positive = 1)
# [1] NaN
measureMultilabelPPV(cbind(c(1,1,1), c(1,1,1)), cbind(rep(0, 3), rep(0, 3)))
# [1] 1
```

should we keep this as it is or should we unify this and when the denominator is zero return NaN in case of the multilabel PPV (or return 1 in case of the PPV)? Maybe this discussion helps http://stats.stackexchange.com/questions/1773/what-are-correct-values-for-precision-and-recall-in-edge-cases

same question holds for tpr, fpr...

**Comment by berndbischl** [comment]
code for better checks, needs to be finished

```

load_all()

getData = function(true1 = 0.5, pred1 = 0.5, n = 10L) {
  list(
    y = rbinom(n, prob = true1, size = 1L), levels = c("0", "1"),
    yhat = rbinom(n, prob = pred1, size = 1L), levels = c("0", "1")
  )
}

doSeq = function(arg, measfun, s, ...) {
  vnapply(s, function(r) {
    args = namedList(arg, r)
    d = do.call(getData, args)
    measfun(d$y, d$yhat, ...)
  })
}

checkMeasure = function(measfun, lower = 0, upper = 1, n = 10L, ...) {
  s = seq(0, 1, length.out = n)
  print("true1")
  z = doSeq("true1", measfun, s, ...)
  print(z)
  # expect_numeric(z, lower = lower, upper = upper, finite = TRUE, any.missing = FALSE)
  print("pred1")
  z = doSeq("pred1", measfun, s, ...)
  print(z)
  # expect_numeric(z, lower = lower, upper = upper, finite = TRUE, any.missing = FALSE)
}


n = 10L
# checkMeasure(measureTP, upper = n, positive = "0")
# checkMeasure(measureFP, upper = n, positive = "0")

# checkMeasure(measureTPR, positive = "1")
# checkMeasure(measureFPR, positive = "1", negative = "0")

checkMeasure(measurePPV, positive = "1")

# checkMeasure(measureTP)
# checkMeasure(measureTP)
# checkMeasure(measureFP)
# checkMeasure(measurePPV)
# checkMeasure(measurePPV)

```

**Comment by smilesun** [comment]
1. For TPR and FPR, in the edge case, I would suggest output NA, since TPR=TP/(TP+FN), if the denominator is zero, it means there is no positive sample in the test, you don't have a measure for this case, the measure if undefined.
2. For PPV=TP/(TP+FP), in the edge case, it depend on the last ranked sample, if it is P, then PPV=1, otherwise PPV=0, THIS is true holding for all cases

**Comment by berndbischl** [comment]
> For TPR and FPR, in the edge case, I would suggest output NA, since TPR=TP/(TP+FN), if the denominator is zero, it means there is no positive sample in the test, you don't have a measure for this case, the measure if undefined.
> For PPV=TP/(TP+FP), in the edge case, it depend on the last ranked sample, if it is P, then PPV=1, otherwise PPV=0, THIS is true holding for all cases

i think i agree. document this and test it.
