### ISSUE TITLE
Quantile regression

### ISSUE THREAD

**Issue by bhvieira** [mlr-org/mlr#1022]
Basic questions, I'm adding Quantile Regression Forests (`quantregForest` from package of same name).  Working on my fork for now (https://github.com/catastrophic-failure/mlr/tree/quantregForest)
It's functionally the same as `randomForest` regression, but offers quantile estimation at prediction.

Now, two questions regarding the implementation:
- What should I actually predict? The default of the packages are `c(0.1, 0.5, 0.9)` quantiles. For now I set it at the median, like in `caret`. This question is also pertinent to further quantile regression methods we add.
- Should I add all those other functionalities `mlr` supports for `randomForest`?

**Comment by PhilippPro** [comment]
Hi,
my first impression is, that that would be a complete new class of learners, cause maybe the user wants several quantiles at once and not only the median. In any case the user should be able to set the quantile to the value he wants. Do you know other quantile regression methods in R? (I've got a quantregRanger repo, but not actualised)

**Comment by catastrophic-failure** [comment]
Linear Quantile Regression and Nonlinear Quantile Regression (`rq` and `nlrq` in `quantreg`).

There are also Kernel Quantile Regression (`kqr` in `kernlab`) and Quantile Regression Neural Network (`qrnn.fit` in `qrnn`, you ).

In all these you set the desired quantile `tau` during training.

**Comment by PhilippPro** [comment]
I just discovered the robust lqr package
