### ISSUE TITLE
Accessing Regression Parameters

### ISSUE THREAD

**Issue by larry77** [mlr-org/mlr#1024]
Dear All,
I must be missing the obvious.
Please consider the following 2 lines of code

`lrn = makeLearner("regr.glmnet")`
`mm4 = train(lrn, bh.task)`

It is a simple regression (without tuning). It is vital for me to access not only the values of the hyperparameters, but also those of the beta coefficients.
Where are they stored and how can I retrieve them?
Many thanks

**Comment by schiffner** [comment]
Hi,

`getLearnerModel(mm4)` gives you the object returned by `glmnet` which contains the betas.

Cheers,
Julia

**Comment by larry77** [comment]
Thanks, but the betas are not yet that easy to extract.
See the following

`dd<-getLearnerModel(mm4)`
`betas<-dd$beta`

`str(betas)
Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  ..@ i       : int [1:657] 11 4 11 4 11 4 11 4 11 4 ...
  ..@ p       : int [1:77] 0 0 1 3 5 7 9 11 13 15 ...
  ..@ Dim     : int [1:2] 14 76
  ..@ Dimnames:List of 2
  .. ..$ : chr [1:14] "crim" "zn" "indus" "nox" ...
  .. ..$ : chr [1:76] "s0" "s1" "s2" "s3" ...
  ..@ x       : num [1:657] -0.0844 0.1278 -0.1536 0.5694 -0.197 ...
  ..@ factors : list()`

and I have a rather complicated object (for me who am not familiar with the dgCMatrix class) containing a list of betas in every "row" (I suppose it is the history of the evolution of the betas until the final choice made by the algorithm).
How can I quickly extract the final values of the betas?

**Comment by larry77** [comment]
OK, I see now that

`betas<-as.matrix(betas)`
`betas<-betas[ , ncol(betas)` 


gets the job done.
Cheers

**Comment by schiffner** [comment]
Hi,

there seems to be a misunderstanding regarding glmnet's output:
glmnet gives you the whole regularization path from an empty model (first column) to a (nearly) saturated model (last column).
The final column is not necessarily the best solution w.r.t. generalization performance.
In order to find this you need to tune the regularization parameter `lambda`.

Cheers

**Comment by larry77** [comment]
Indeed. This post was just about how to extract the betas. In my script, I tune the lambda and alpha hyperparameters, but it is still interesting in the end of the day to know the betas (in my case to see which features have been retained) of the trained model.

**Comment by schiffner** [comment]
Sure. Glad it's working now.
