### ISSUE TITLE
pvalue and randomsplits is not a parameter of cforest

### ISSUE THREAD

**Issue by MariaErdmann** [mlr-org/mlr#1025]
Hi,

implementing a multilabel.cforest I stumbled over the parameter pvalue in the paramset of our classification, regression and survival learners. I searched for this parameter in conjunction with cforest on the net but did not find it. Indeed, it does not work (creating the learner does work, but training not):

````
clrn = makeLearner("classif.cforest", par.vals = list(pvalue = TRUE))
mod = train(clrn, binaryclass.task)

rlrn = makeLearner("regr.cforest", par.vals = list(pvalue = FALSE))
mod2 = train(rlrn, regr.task)

slrn = makeLearner("surv.cforest", par.vals = list(pvalue = TRUE))
mod3 = train(slrn, surv.task)
````
Do I miss something or can I remove the parameter from the learners?

Cheers, Maria

**Comment by MariaErdmann** [comment]
Same with parameter 'randomsplits':

````
clrn = makeLearner("classif.cforest", par.vals = list(randomsplits = TRUE))
mod = train(clrn, binaryclass.task)

rlrn = makeLearner("regr.cforest", par.vals = list(randomsplits = FALSE))
mod2 = train(rlrn, regr.task)

slrn = makeLearner("surv.cforest", par.vals = list(randomsplits = TRUE))
mod3 = train(slrn, surv.task)
````

**Comment by MariaErdmann** [comment]
Parameter 'replace': default is set to FALSE, in the manual the default is: TRUE
Parameter 'testtype': in the manual in cforest_control() default is 'Teststatistic'
Parameter 'mincriterion': There are several places where defaults are given for this parameter. In cforest_control() it is qnorm(0.9), in varimp() it is 0 and in ctree_control() it is 0.95.

**Comment by schiffner** [comment]
Hi,

I agree about the unnecessary parameters `pvalue` etc., couldn't find them either.

About the defaults:
I think they are correct.
We had this problem here: https://github.com/mlr-org/mlr/issues/556
As solution for this we decided:
* use `ctree_control` instead of the default `ctree_unbiased` for `controls`
* to make sure that e.g. `classic.cforest` behaves the same as using `cforest` directly, we use the defaults in `forest_unbiased`:
```
party::cforest_unbiased
function (...) 
cforest_control(teststat = "quad", testtype = "Univ", mincriterion = 0, 
    replace = FALSE, fraction = 0.632, ...)
<environment: namespace:party>
```

**Comment by MariaErdmann** [comment]
Thank you for the explanation and the link to the issue! Makes it clear now! Should we probably add a small note telling the user or other developers to come, which defaults are used?

> to make sure that e.g. classic.cforest behaves the same as using cforest directly, we use the defaults in forest_unbiased:

Isn it also used for `regr.cforest`?

**Comment by schiffner** [comment]
> Thank you for the explanation and the link to the issue! Makes it clear now! Should we probably add a small note telling the user or other developers to come, which defaults are used?

Mhh, good question.

I think users won't have a problem with the defaults directly. Although we do puzzling things inside outwardly nothing was changed, and the defaults given in the parameter set are correct.
But we don't tell them that they don't need to use any of the control functions but can pass the parameters directly. So I think we could add something like this to the `note`:
"Control parameters have to be passed directly and not by using any of the control functions (like `cforest_control`) in `cforest`."

What would also certainly be helpful for all developers is adding a comment to the R code which references the issue.

> Isn it also used for regr.cforest?
Yup. And for surv.cforest, too.

**Comment by MariaErdmann** [comment]
Dipping a little bit deeper into cforest with respect to the multilabel.cforest I figured out that the control parameters (randomsplits, pvalue, minprob) do exist. See: `cforest_control()` and also that we need these parameters to ensure that the tests work properly. However, I can't set these control paramters myself in cforest (and this is also the reason why they are not working in mlr) . See code snippet below. Any ideas? 

````
library(party)

data(iris)
iris

# Look at Slot "varctrl": There you can find i.e. pvalue
party::cforest_control()

cforest(Species ~., data = iris, control = cforest_control(mtry = 1, pvalue = FALSE))
# throws error
````

**Comment by jakobbossek** [comment]
You can change these S4 slots directly:
```splus
library(party)

data(iris)
ctrl = party::cforest_control()
ctrl@gtctrl@mtry = 1L
ctrl@varctrl@pvalue = TRUE
print(ctrl)

cforest(Species ~., data = iris, control = ctrl)
```

**Comment by jakobbossek** [comment]
Talked about that with @berndbischl 
We are going to remove these three parameters.

**Comment by jakobbossek** [comment]
Adressed in #1087
