### ISSUE TITLE
How to quote MLR in a publication?

### ISSUE THREAD

**Issue by larry77** [mlr-org/mlr#1029]
Dear All,
I suppose the title of the post says it all.
How should I cite MLR?
Regards

**Comment by jakob-r** [comment]
As it should be the case for all for all R-Packages
```
citation("mlr")
```
If your publication will be published in the future come back it would be appreciated if you came back to check if this is still up to date, as we have a paper in the pipeline.

**Comment by jakobbossek** [comment]
Since not all users are familiar we should maybe add some lines on this in the README and/or tutorial.

**Comment by berndbischl** [comment]
there should be a PROMINENT section on the main page how to cite mlr. we now have various papers. and the citation("mlr") should also be improved. 

i marked this as "severe" and will do this on tuesday.

**Comment by berndbischl** [comment]
i updated the README
