### ISSUE TITLE
getMultilabelBinaryPerformances must be proof read

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1031]

**Comment by MasonGallo** [comment]
Is this related to warnings I'm getting below when attempting to build mlr?

```
Updating mlr documentation
Loading mlr
Warning messages:
1: In FUN(X[[i]], ...) :
  incomplete final line found on '/home/mason/work/mlr/inst/examples/MultilabelWrapper.R'
2: In FUN(X[[i]], ...) :
  incomplete final line found on '/home/mason/work/mlr/inst/examples/MultilabelWrapper.R'
3: In FUN(X[[i]], ...) :
  incomplete final line found on '/home/mason/work/mlr/inst/examples/MultilabelWrapper.R'
4: In FUN(X[[i]], ...) :
  incomplete final line found on '/home/mason/work/mlr/inst/examples/MultilabelWrapper.R'
5: In FUN(X[[i]], ...) :
  incomplete final line found on '/home/mason/work/mlr/inst/examples/MultilabelWrapper.R'
Documentation completed
```

**Comment by larskotthoff** [comment]
No, this sounds like it's a Mac issue where files are created without a newline character at the end. Although we have other files like that as well, so not sure why you're seeing this warning here.

**Comment by MasonGallo** [comment]
This was actually on Ubuntu. 

Adding a blank line fixes the warning, but I'm not sure why it's only triggered for this particular file.

**Comment by berndbischl** [comment]
@MasonGallo 
yeah, i have seen this before. just add the final white line to fix this for you.

but with this issue i referred to reviewing the code in that file as a whole. like proof-reading it and the API here.

**Comment by PhilippPro** [comment]
example has to be replaced by 

`#' @example inst/examples/MultilabelWrapper.R`
