### ISSUE TITLE
Add unit tests to check for wrong default values

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#1034]
In mlr we maybe have wrong default values, for example in the `?mboost::boost_control` documentation it says that `center = TRUE`  is the default. In our mlr param set, the default is `FALSE`, see:

``` r
getParamSet(lrn)$pars[["center"]]
#     Type len   Def Constr Req Tunable Trafo
#1 logical   - FALSE      -   -    TRUE     -
# Used: train.
```

This is the issue that is caused:

``` r
lrn = makeLearner("regr.glmboost")
set.seed(1);(bench <- benchmark(lrn, bh.task))
#                task.id    learner.id mse.test.mean
#1 BostonHousing-example regr.glmboost      25.95779

lrn2 = setHyperPars2(lrn, getDefaults(lrn$par.set))
set.seed(1);(bench2 <- benchmark(lrn2, bh.task))
#                 task.id    learner.id mse.test.mean
#1 BostonHousing-example regr.glmboost      42.50329
```

Maybe we should add a test for all learners such as:

```
testthat::expect_equal(as.data.frame(bench), as.data.frame(bench2))
```

Or maybe something like this is sufficient:

```
testThatLearnerHasCorrectDefaults = function(lrn, task) {
  lrn2 = setHyperPars2(lrn, getDefaults(lrn$par.set))

  rin = makeResampleInstance("Holdout", task = task)
  set.seed(1);m1 = train(lrn, task, subset = rin$train.inds[[1]])
  lrn2 = setHyperPars2(lrn, getDefaults(lrn$par.set))
  set.seed(1);m2 = train(lrn2, task, subset = rin$train.inds[[1]])

  p1 = predict(m1, task, subset = rin$test.inds[[1]])
  p2 = predict(m2, task, subset = rin$test.inds[[1]])
  expect_equal(performance(p1), performance(p2))
}
```

**Comment by giuseppec** [comment]
In general, making sure that our defaults are always correct is very important for reproducibility in openml because we decided not to upload default hyperparameter values to openml. Applying a learner `lrn = makeLearner("regr.glmboost")` and `lrn2 = setHyperPars2(lrn, getDefaults(lrn$par.set))` on the same task with the same seed should therefore always return the same result, shouldn't it?

**Comment by larskotthoff** [comment]
Agreed. We probably should also have tests that compare the default mlr learner with the unwrapped learner.

**Comment by jakob-r** [comment]
Related to handling #1032
