### ISSUE TITLE
plotLearnerPrediction with ranger results does strange things

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1039]
```
set.seed(12)
data = convertMLBenchObjToTask("mlbench.circle", 1000L)
lrn = makeLearner("classif.ranger")

plotLearnerPrediction(lrn, task = data)
```

So the resulting plot has a mmce of 0.963. I would guess that the classes get switched somewhere

**Comment by PhilippPro** [comment]
Maybe this is related to that: https://github.com/imbs-hl/ranger/issues/95

**Comment by mnwright** [comment]
Fixed in ranger (wrong class labels in probability estimation in some cases).

**Comment by ja-thomas** [comment]
ok cool

**Comment by berndbischl** [comment]
> Fixed in ranger (wrong class labels in probability estimation in some cases).

thx. 
and also glad to be of service here at the ML unit testing service station for other packages ;-)
