### ISSUE TITLE
ranger and the write.forest default

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#1040]
This issue is maybe a bit related to https://github.com/mlr-org/mlr/issues/1034 . Some default values for paramaters do not make sense for mlr, such as the default for `write.forest` is `FALSE`, which yields:

``` r
lrn = makeLearner("classif.ranger")
lrn2 = setHyperPars2(lrn, getDefaults(lrn$par.set))
bench = benchmark(lrn2, iris.task)
#[Resample] cross-validation iter: 1
#Error in predict.ranger(object = .model$learner.model, data = .newdata,  : 
#  Error: No saved forest in ranger object. Please set write.forest to TRUE when calling ranger.
```

Apparently the code above worked in mlr 2.8 but does not work anymore because we allow the user to set the `write.forest`, shouldn't we fix `write.forest = TRUE`?

**Comment by jakob-r** [comment]
We should discuss this at the workshop together with PR #1032

**Comment by jakob-r** [comment]
If the default in the orignal learner is NULL I would not set it as the default in mlr except those few special cases. Otherwise to be consequent we would have change a lot.

**Comment by MariaErdmann** [comment]
Yes, I agree, thanks!

**Comment by giuseppec** [comment]
Can we then close this issue?

**Comment by MariaErdmann** [comment]
I think so, yes.
