### ISSUE TITLE
Add support for displaying train performance when comparing models/sets

### ISSUE THREAD

**Issue by MasonGallo** [mlr-org/mlr#1044]
IMO Most of our methods that we use to compare multiple learners or multiple hyperparameter sets would benefit from displaying train error out of the box, rather than just validation error, in order to see if a model/set is under/overfitting.

For example, I would expect [learning curve](http://mlr-org.github.io/mlr-tutorial/devel/html/learning_curve/index.html) to at least have an option to also draw a line for the training performance. Same goes for my GSoC work on hyperparameter tuning.

Thoughts?

**Comment by berndbischl** [comment]
you do know that we can do that with resample, don't you?

```
load_all()

lrn = makeLearner("classif.rpart")
m1 = mmce
m2 = setAggregation(mmce, train.mean)
m2$id = "trainerr"

rdesc = makeResampleDesc("CV", predict = "both", iters = 2)

r = resample(lrn, iris.task, rdesc, measures = list(m1, m2))

print(r)
print(r$measures.test)
print(r$measures.train)

d = generateLearningCurveData(list(lrn), iris.task, measures = list(m1, m2), resampling = rdesc)
print(plotLearningCurve(d))
```

is this somehow underdocumented?

@schiffner

**Comment by MasonGallo** [comment]
Definitely - I would argue that it's at least under documented in either the documentation or I suppose the tutorial - I have to guess that the example you listed above will work or read the source code. To be fair, this also holds true for my GSoC work. My opinion is that all "out of the box" examples we show in the docs/tutorial demonstrate this.

**Comment by MasonGallo** [comment]
@berndbischl 

Unless I'm missing something, getting train performance doesn't work with `tuneParams` - I think it's due to how evalOptimizationState calls `resample` object [here](https://github.com/mlr-org/mlr/blob/3d7499b8743b41731c5ef7f2d3462cdc0c9a4e2e/R/evalOptimizationState.R#L57).

Reproducible example:

```
ps = makeParamSet(
  makeNumericParam("C", lower = -5, upper = 5, trafo = function(x) 2^x),
  makeNumericParam("sigma", lower = -5, upper = 5, trafo = function(x) 2^x))
ctrl = makeTuneControlRandom(maxit = 100L)
rdesc = makeResampleDesc("CV", predict = "both", iters = 2L)
learn = makeLearner("classif.ksvm", par.vals = list(kernel = "rbfdot"))
res = tuneParams(learn, task = pid.task, control = ctrl, measures = acc,
                 resampling = rdesc, par.set = ps, show.info = F)
generateHyperParsEffectData(res)
```

**Comment by schiffner** [comment]
> is this somehow underdocumented?

I agree with Mason. If I remember correctly there is one example in the tutorial on the resampling page, but that's about it...

**Comment by berndbischl** [comment]
mason already open this here for the tutorial

https://github.com/mlr-org/mlr-tutorial/issues/44

where could we improve R docs to show how this works? 
resample and tune for now?

**Comment by MasonGallo** [comment]
> resample and tune for now?
Agreed. What about a link or something in Notes for other methods like benchmark?

```
load_all()

lrn = makeLearner("classif.rpart")
m1 = mmce
m2 = setAggregation(mmce, train.mean)
m2$id = "trainerr"

rdesc = makeResampleDesc("CV", predict = "both", iters = 2)

r = resample(lrn, iris.task, rdesc, measures = list(m1, m2))

print(r)
print(r$measures.test)
print(r$measures.train)

d = generateLearningCurveData(list(lrn), iris.task, measures = list(m1, m2), resampling = rdesc)
print(plotLearningCurve(d))
```

IMHO most users probably want despite the concerns from #1047 
```
print(plotLearningCurve(d, facet = "learner"))
```
I added to tutorial and will look for other examples like it

**Comment by berndbischl** [comment]
@MasonGallo 
can you pls do a PR for the doc improvement? 
and i have to admit i cannot understand most of the rest of your post, where you starting at the large chunk of code. what are you saying here?

**Comment by MasonGallo** [comment]
@berndbischl 
basically, I think most users of `plotLearningCurve` with train & test curves prob want to use this facet argument to get the curves on same scale/plot, which kinda goes against our discussion around faceting in #1047 but I still think it's important to have in this case

**Comment by berndbischl** [comment]
> basically, I think most users of plotLearningCurve with train & test curves prob want to use this facet argument to get the curves on same scale/plot, which kinda goes against our discussion around faceting in #1047 but I still think it's important to have in this case

sure. but in #1047 we did not a) really come to a decision, its mor like a discussion point b) i didnt suggest to get rid of facetting. i suggested to do a default facetting , but use only ggplot2 operators later for the user, and not our function signatures, to later change that facetting?

**Comment by berndbischl** [comment]
i guess we need to discuss this orally, also with @zmjones 

can you please do a PR to improve the docs here so we can close?

**Comment by MasonGallo** [comment]
Yes the PR is on my todo list
