### ISSUE TITLE
better facetting for plots

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1047]
i asked to make faceting better in this 
https://github.com/mlr-org/mlr/issues/898

i now kinda disagree that this was such a good idea. it just bloats the API with more and more ggplot options.

we should figure out whether we can get away without having this in the signature.
and let a user simply change the faceting by applying standard ggplot plus ops. 

what i didnt know before is that ggplot apparently allows you to overwrite the faceting.
so this works, also for all intermediate p-plots:

```
library(ggplot2)
d = iris
p = ggplot(d, aes(x = Sepal.Length, y = Sepal.Width)) + geom_point()
p = p + facet_wrap(~ Species, nrow = 3)
p = p + facet_wrap(~ Species, ncol = 3)
p = p + facet_grid(~ Species, scales = "free")
p = p + facet_wrap(~ Species, ncol = 3, scales = "free")
print(p)
```

we could simply create a default faceting in our plot functions and then let the user change this later by applying a plus op.

**Comment by zmjones** [comment]
this doesn't work with the plus operation 

i agree that this is api bloating though

not sure what to do

**Comment by jakobbossek** [comment]
> this doesn't work with the plus operation
Why? It should work. Modifying the ggplot object is possible.

**Comment by berndbischl** [comment]
i havent looked at every detail. but if you set a certain default faceting you can overwrite this with the +.

check my example above?

**Comment by jakobbossek** [comment]
In my opinion we should revert #950. No need for more arguments since a modification with + is definitely possible.

**Comment by zmjones** [comment]
I agree

**Comment by jakobbossek** [comment]
@berndbischl What do you think? Should I undo #950?

**Comment by jakobbossek** [comment]
ping

**Comment by berndbischl** [comment]
i think this should be undone. problem is:
we need to carefully check this....

**Comment by jakobbossek** [comment]
Ok. I will assign myself for that.
