### ISSUE TITLE
for gbm and other ensemble learners: predict args

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1051]
is it possible to predict on a smaller subset of trees, after the model was fitted?

so we need to pass down the "n.trees" from mlr's predict function. we have ... varargs in mlr::predict.
this could be used.

**Comment by zmjones** [comment]
this is possible with randomForest by using the `predict.all` argument (which returns the tree prediction matrix) and then subsetting this. with `cforest` it is not possible (since torsten didn't want to merge my patch). how would this be useful with boosting though?

**Comment by smilesun** [comment]
pull request #1114
