### ISSUE TITLE
make sure that mlr does not need the most recent version of R

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1059]
we need some kind of a check for this, so that we only use the the R version we require in the DESC

it is possible that we currently have this problem, due to changes on listLearner.

we probably need to fix this, so this might be 2 issues:

a) fix listLearners
b) create a test that mlr can run with eg R 3.0

https://github.com/rstudio/shiny/issues/849

**Comment by berndbischl** [comment]
@larskotthoff 
we have to solve a) NOW. but we can do that. 

please give a response whether you think b) could be solved soon.

**Comment by berndbischl** [comment]
@mllg can you please fix a) ?
that blocks the upload of 2.10.

**Comment by berndbischl** [comment]
whether we can really have a formal test on jenkins, maybe lars has to look at this

**Comment by schiffner** [comment]
> that blocks the upload of 2.10.

When are you going to upload, Bernd?

**Comment by berndbischl** [comment]
when we are done, preferably during the next 7 days. why?

**Comment by schiffner** [comment]
Because I'm not yet done with the tutorial stuff and wanted to know how much time I have left. :wink:

**Comment by mllg** [comment]
> @mllg can you please fix a) ?

Everything is fine with `listLearners`.

**Comment by larskotthoff** [comment]
I've tried more R versions in #1171, but we fail for everything older than release because of other packages.

**Comment by larskotthoff** [comment]
So Travis installs all packages in DESCRIPTION (including suggests) automatically and there's no way to change that. So we can't easily have builds on older versions of R that only do the basic checks (and install only the packages required for this).

**Comment by berndbischl** [comment]
> So Travis installs all packages in DESCRIPTION (including suggests) automatically and there's no way to change that. So we can't easily have builds on older versions of R that only do the basic checks (and install only the packages required for this).

ok, travis seems out then. i dont think we can ever install all suggested packages with older versions, reliably. 

can we do that on jenkins?

**Comment by larskotthoff** [comment]
Well, we would need to manually set up and maintain virtual machines with various R versions. Doable, but quite a bit of effort. Hiwi task?

**Comment by berndbischl** [comment]
> Well, we would need to manually set up and maintain virtual machines with various R versions. Doable, but quite a bit of effort. Hiwi task?

i domt have a hiwi who can do this. 

IMHO we need exactly 1! extra R version. with lowest version nr we claim that we support.

**Comment by larskotthoff** [comment]
I think you're underestimating your hiwis (again).

So what should that version number be?

**Comment by berndbischl** [comment]
> I think you're underestimating your hiwis (again).

they might be reading here, too, so just for the record: i think they are great. but i dont think they can setup basically a linux system, on jenkins....

> So what should that version number be?

simple answer. thats what we claim in the DESCRIPTION
    R (>= 3.0.2),

of course, i am totally ok if you change that nr a bit, depending on your results.
lower is alway better, but i dont think we can go below a major 3

**Comment by larskotthoff** [comment]
I can't get Rcpp to compile on 3.0.2. Does anybody know which minimum version it needs?

**Comment by berndbischl** [comment]
The required r version Nr by rcpp should be visible on the cran rcpp site.

But you should NOT have rcpp as a dEpendency?  What do you need it for?

**Comment by larskotthoff** [comment]
Well according to CRAN it only needs 3.0.0. I think it's pulled in by ggplot.

**Comment by berndbischl** [comment]
> Well according to CRAN it only needs 3.0.0. I think it's pulled in by ggplot.

why not simply check the ggplot2 cran site?
a) ggplot2 already states that it needs >= R 3.1
b) it does not (directly) need rcpp.

**Comment by berndbischl** [comment]
ggplot2 needs plyr and that needs RCPP. 

we also import shiny now, which is in itself a dependency hell.

can we somehow clean this up?

@mllg @zmjones 

we need some help here....

**Comment by berndbischl** [comment]
can we try to move some of the stuff to suggests?

**Comment by mllg** [comment]
Alternatively, we set the minimum required version to R-3.1.0 (released April 2014) and all problems are gone ;)

**Comment by mllg** [comment]
In principle we already have such a dependency because Lars is obviously struggling to get all packages compiled, so there is nothing to lose. 

Regarding the other packages: putting `shiny` into Suggests is a no-brainer (we already selectively import functions from shiny, not the complete namespace). `ggplot2` might be a bit tricky.

**Comment by zmjones** [comment]
yea agreed about shiny being in suggests. none of the ggvis stuff is required. 

i am not opposed to moving ggplot2 to imports either. there are probably a lot of people that don't use the plotting functionality, and this would allow us to completely eliminate the plyr dependency right?

**Comment by zmjones** [comment]
it would bloat the plotting code a decent bit though. is there some way to avoid explicit referencing of the package for things in suggests?

**Comment by mllg** [comment]
> it would bloat the plotting code a decent bit though. is there some way to avoid explicit referencing of the package for things in suggests?

No, that's the downside. Best would be an extra package `mlrPlots` which imports `ggplot2` :wink:

**Comment by larskotthoff** [comment]
I'm trying 3.1.2 now and all dependencies compile, but mlr doesn't load:

```
Error : object ‘.S3methods’ is not exported by 'namespace:utils'
ERROR: lazy loading failed for package ‘mlr’
```

**Comment by larskotthoff** [comment]
I've removed that, but stuck now running the examples -- they require `caret`, which requires `car`, which requires at least R version 3.2.

**Comment by berndbischl** [comment]
Ok, lets wrap it up, so we dont muddle issues here, and Lars does not get blocked with this.

1) we set the mlr R dependency to 3.1.0 or 3.1.2, depending on what works for Lars

2) we create a NEW issue to move shiny and ggvis to SUGGESTS and dynamically load those.

3) we think about doing the same for ggplot2, but not now. i can see the point about having an extra package for this, but am also not that thrilled about this.... :(
would rather avoid if possible.

4) Lars, caret should really not be called in the examples. The only thing I could imagine is getCaretParamSet. If you need to delete the example here: fine.
If the same problem occurs for the unit tests for this function , move them from "base" to group "tune", where the latter is not called in your tests.

OK?

**Comment by larskotthoff** [comment]
I don't know if there's anything else that requires 3.2 and I don't really want to sink any more time into this. I'll give it one last try on 3.2, but I don't want to start moving code/examples around.

**Comment by larskotthoff** [comment]
The clustering tests need the clusterSim package, which requires rgl, which requires R 3.2.

**Comment by eddelbuettel** [comment]
(Coming a little late to this)

It is indeed a noble goal to not needlessly depend on new-ish versions.  My heros for that are Matt and Arun whose data.table still builds with R 2.15.  But they have no Depends themselves.

For a package such as mlr with that many Depends/Recommends/Suggests I would think it is near-impossible to go back several years.  Surely one of the many packages pulled in will have break the chain...

(Rcpp has a >= on 3.0.0 but even we got bitten when a external PR had an implicit depends on `#define` available only in R 3.2.0, and we failed to test on 3.1.0 and 3.0.0.  I don't keep old versions.)

Lastly, and to finally get to the point of why I wrote the note ;-) -- I see two options for you:
- Gabor has some infrastructure around r-hub [here](https://github.com/metacran/r-builder) which makes several R versions available to Travis. I have not used this myself.
- You could just hack your own Travis drivers. I use my fork of the (older, initial) scheme as I like it better (and as it allows me to get .deb packages from external repos such as PPAs on launchpad)

**Comment by larskotthoff** [comment]
Thanks @eddelbuettel. We've used other versions of R on Travis and our own test infrastructure (Jenkins) allows arbitrary setups.

That said, it looks like in practice we need a very recent version of R because of the deps anyway, so there's probably no point in having a separate test job.

**Comment by eddelbuettel** [comment]
We are in full agreement here.

**Comment by larskotthoff** [comment]
@berndbischl Close here?

**Comment by jakob-r** [comment]
@berndbischl ping

**Comment by pat-s** [comment]
It is very hard to ensure that all packages/important deps of {mlr] will work on all R versions that we officially support based on the DESCRIPTION entry.

As long as we are not using a blocking feature of an R version within the package ourselves, I see no need why we should need to check all R versions ourselves.

In the end this is like a package dep: It can theoretically work with an older version since we are not relying on a blocking feature of a later version but its up to the user to get everything working in the end.

Raising the R version now also does not make sense since it will break backward compatibility.
