### ISSUE TITLE
Why is cv.glmnet used instead of glmnet?

### ISSUE THREAD

**Issue by dominikkirchhoff** [mlr-org/mlr#106]
cv.glmnet seems to do some optimization by an integrated CV. Is that what we want the learner to do?

Also, when applying cv.glmnet to the Iris data set, I get a whole lot of zeros, which seems quite weird to me (see test_surv_glmnet for a reproducible example).

**Comment by krishxx** [comment]
For me it worked, when I used like:
glmnet::cv.glmnet()
