### ISSUE TITLE
plotThreshVsPerf: why cant i subset the displayed the measures

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1061]
assume you have resampled with 5 measures and only want to display 2.

**Comment by berndbischl** [comment]
@zmjones 
this seems pretty simple. could you please solve this?

**Comment by zmjones** [comment]
yep

**Comment by zmjones** [comment]
this was fixed in the referenced commits.

**Comment by zmjones** [comment]
which i apparently never issued a pr for. will fix them up and pr.
