### ISSUE TITLE
makeLearner: do the same string/name suggestion as we do for hyperpars soon 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1070]
see here #1060

**Comment by jakobbossek** [comment]
Since `makeLearner` delegates hyperparameter setting to `setHyperPars` there is nothing to do 😉 
```splus
lrn = makeLearner("classif.randomForest", ntr = 1000)
% > classif.randomForest: couldn't find hyperparameter 'ntr'
% > Did you mean one of these hyperparameters instead: ntree mtry strata
```

**Comment by larskotthoff** [comment]
What we're looking for is

    lrn = makeLearner("classif.randomFrest")
    > classif.randomFrest not found, did you mean "classif.randomForest"

**Comment by jakobbossek** [comment]
Ah, ok. Thanks for the explanation.

**Comment by jakobbossek** [comment]
See PR #1106
