### ISSUE TITLE
we need a better way to document specific things for learners, filters and measures, etc

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1072]
currently we have the "note" mechanism for this.

the notes document stuff like this
- minimal  API changes from mlr on the learner
- changed defaults
- extra hints for users to avoid problems

this is actually good. but some notes are getting longer and longer. 
problems are 
- we use a string, but this is more like a doc page
- long notes are bad for console display when learner is printed
- long notes are bad for the appendix table in the tutorial

we need to create something like doc pages for each learner?

**Comment by zmjones** [comment]
i very much agree that we need to do something about this. i think the doc page would be fine as long as it didn't entail us being required to write docs for each learner. we could just link to the package page in all cases where we don't modify the default package behavior.
