### ISSUE TITLE
create seperate mlr-learners package?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1088]
which would contain all RLearner files.

Here are some pros and cons from the workshop discussion.
must be closed soon.

Vorschlag: mlrLearners paket machen

+ schneller Testen auf Travis
+ wir bleiben nur bei einem extra Paket
+ logisch besser aufgebaut
+ Verwaltbarkeit wird einfacher (log history)

o mini: 1 Learner pro Type (eher Top 10)
o List Learners sollte unabhängig funktionieren
o ideales Testsystem bräuchte 

- grundstruktur änderungen müssten umständlich synchronisiert werden
- höhere maintanance
- PRs könnten über beide Pakete gehen

**Comment by larskotthoff** [comment]
I'm not in favour of this (and don't remember hearing a convincing argument for it).

**Comment by berndbischl** [comment]
we certainly cannot do this now. and nobody will do it in the next couple of weeks. 

the topic can be discussed again during future devel meetings if this is seen as helpful
