### ISSUE TITLE
rf importance filter methods

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1093]
we have some problems here:

1) please rename. we want 
randomforest.importance
randomForestSRC.importance

2) specific versions should be selected by a "method" arg, with better names then type = 1.

3) for the normal randomforest imp with node impurity you dont need importance = TRUE in the call.
makes it faster.

**Comment by berndbischl** [comment]
4) deprecate the "rf.importance" then which was already there

5) at least for these new methods that you now touch, add docs.

**Comment by berndbischl** [comment]
6) consider also rf.min.depth here. see merged PR #1082 
same comments as above apply.

and lars wanted you to add a unit test

**Comment by schiffner** [comment]
Also random forest supports ordered factor features. (That's missing for some of the other methods, too.)

**Comment by jakobbossek** [comment]
Not finished yet. I opened a new issue for the docs (see #1099).
I renamed `rf.importance` to `randomForestSRC.rfsrc` following the schema `pkg.method`.

**Comment by jakobbossek** [comment]
See PR #1101

**Comment by jakobbossek** [comment]
Done via b8c46bc
