### ISSUE TITLE
better tests for learners param

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1095]
1) we could systematically try out all values of all discrete params

2) we could do random testing with quicktest

**Comment by larskotthoff** [comment]
1) would take far too long in practice I think. 2) sounds good.

**Comment by berndbischl** [comment]
> 1) we could systematically try out all values of all discrete params

not necessarily, i am not speaking about a full crossprod, but changing one  factor at a time.
for 1) AND 2) am more worried about all of the peculiarities that could occur.
