### ISSUE TITLE
show.info in learner creation

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#1098]
Does the following have any effect?

```
makeLearner("classif.ksvm", config = list(show.info = TRUE))
```

can we just forbid to set `show.info` here if it does not have any effect at all? We need this for https://github.com/mlr-org/mlr/pull/1089

**Comment by larskotthoff** [comment]
Is this still relevant?

**Comment by berndbischl** [comment]
the show.info arg needs to removed from setHyperPars. it just clutters up the interface. and the message from the fuzzy arg suggesttion needs to be merged with the "could not find hyperpar" message.

wrt what giusseppe writes: yes this is relevant. i have no idea whether that option has any effect at all.

**Comment by schiffner** [comment]
> wrt what giusseppe writes: yes this is relevant. i have no idea whether that option has any effect at all.

Doesn't seem so, neither via `config` nor via `...`. Putting it in `par.vals` of course causes an error:
```
lrn = makeLearner("classif.ksvm", config = list(show.info = TRUE))
r = resample(lrn, iris.task, makeResampleDesc("CV", iters = 2))
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] Result: mmce.test.mean=0.0333

lrn = makeLearner("classif.ksvm", config = list(show.info = FALSE))
r = resample(lrn, iris.task, makeResampleDesc("CV", iters = 2))
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] Result: mmce.test.mean=0.08

lrn = makeLearner("classif.ksvm", show.info = FALSE)
r = resample(lrn, iris.task, makeResampleDesc("CV", iters = 2))
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] Result: mmce.test.mean=0.0533

lrn = makeLearner("classif.ksvm", par.vals = list(show.info = FALSE))
classif.ksvm: couldn't find hyperparameter 'show.info'
Did you mean one of these hyperparameters instead: shrinking sigma scaled
Error in setHyperPars2.Learner(learner, insert(par.vals, args), show.info = show.info) : 
  classif.ksvm: Setting parameter show.info without available description object!
You can switch off this check by using configureMlr!
```

**Comment by berndbischl** [comment]
> can we just forbid to set show.info here if it does not have any effect at all?

yes, we should forbid this. now.
