### ISSUE TITLE
Database backends

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#1108]
I've started on data sources in the datasource branch. I suggest the following road map:
- [x] Remove every direct access to "[task]$env$data" and replace it with a call to `getTaskData`.
- [x] Rewrite `subsetData` for new data sources
- [x] Use `getData`in `getTaskData` and other Task-ops.
- [ ] Re-work task descriptions
- [ ] Implement checkData
- [ ] Export a helper equivalent of `fixup.data`
- [ ] Implement `changeData` (stop if read-only source for now)
- [ ] Write down a real-world scenario (e.g., subsampling on a big data base)
- [ ] Implement more sources (sparse, mmap-ed files, ...)
- [ ] Benchmark and optimize

**Comment by berndbischl** [comment]
comment so i dont forget this:
i would be good if a data source could simply point to a file on disk. even a regular one that alone fits in mem. this is extremely trvial, but already a nice feature. think about bechmark with 100 data sets.
you dont want to expand those all to mem. 1 exp just needs 1 data set

**Comment by mllg** [comment]
> i would be good if a data source could simply point to a file on disk. even a regular one that alone fits in mem. this is extremely trvial, but already a nice feature. think about bechmark with 100 data sets.
> you dont want to expand those all to mem. 1 exp just needs 1 data set

So support for Feather (https://blog.rstudio.org/2016/03/29/feather/)?

**Comment by berndbischl** [comment]
> So support for Feather (https://blog.rstudio.org/2016/03/29/feather/)?

probably, if this is stable. 
possibly also ARFF and rdata at some point, so you dont have to convert too much for already existing data files?
