### ISSUE TITLE
add learners from mxnet

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1120]
deeplearning toolbox. see here

https://github.com/dmlc/mxnet/tree/master/R-package

**Comment by rwarnung** [comment]
I start using `mxnet`. `caret` implements mxnet using a 3 layer setup similar to the `deepenet` learner. I will play a bit more with `mxnet `(and the `caret `interface to it) and then I could try to help to get into `mlr`.

https://github.com/topepo/caret/blob/master/models/files/mxnet.R

should work with `mlr `too ..

**Comment by berndbischl** [comment]
cool thx

**Comment by enricoferrero** [comment]
+1, it'd be great to have the money models available.

**Comment by ja-thomas** [comment]
We have a master student working on implementing mxnet into mlr as part of his thesis. PR should be open soon

**Comment by rwarnung** [comment]
Great. I didn't find the time to get really started. But I would contribute in testing the learner. I am very much looking forward to this!

**Comment by jakob-r** [comment]
> `caret` implements mxnet using a 3 layer setup similar to the `deepenet` learner.

If you look closely it seems that layer 2 and 3 stay unused per default.

**Comment by rwarnung** [comment]
This is a question of the design of the learner -right? One could use the function `mx.mlp` with less flexiblity or `mx.model.FeedForward.create` with full flexibility (e.g. different activation functions for each layer except the last one).
