### ISSUE TITLE
We should not use try(..., silent=TRUE) anywhere in the code

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1131]
```
makeLearner.R
61:  constructor = try(getS3method("makeRLearner", class = cl), silent = TRUE)

evalOptimizationState.R
24:    learner2 = try(setHyperPars(learner, par.vals = state2), silent = TRUE)

RLearner_regr_nodeHarvest.R
14:      makeLogicalLearnerParam(id = "silent", default = FALSE, tunable = FALSE),

Task.R
67:#'   \dQuote{quiet} = Do it but keep silent.

RLearner_classif_xgboost.R
10:      makeIntegerLearnerParam(id = "silent", default = 0),

RLearner_classif_nodeHarvest.R
14:      makeLogicalLearnerParam(id = "silent", default = FALSE, tunable = FALSE),

train.R
79:    fun2 = if (opts$on.learner.error == "stop") identity else function(x) try(x, silent = TRUE)

predict.R
105:    fun2 = if (opts$on.learner.error == "stop") identity else function(x) try(x, silent = TRUE)

RLearner_regr_xgboost.R
10:      makeIntegerLearnerParam(id = "silent", default = 0),

```

**Comment by mllg** [comment]
As far as I can see all suppressed errors are handled correctly in the respective following lines.

**Comment by ja-thomas** [comment]
@berndbischl what are your thoughts? If it's ok we can close this

**Comment by jakobbossek** [comment]
To be honest I used `try(..., silent = TRUE)` in PR #1106 😉 
I do not see the problem if catched errors are handled afterwards.

**Comment by berndbischl** [comment]
> As far as I can see all suppressed errors are handled correctly in the respective following lines.

well. i also suspected that try-silent call might simply point us to bad code.
this is the first piece of code i looked. 

```
  constructor = try(getS3method("makeRLearner", class = cl), silent = TRUE)
  if (inherits(constructor, "try-error")) {
    possibles = getNameProposals(cl, possible.inputs = suppressWarnings(listLearners()$class))
    stopf("Couldn't find learner '%s'\nDid you mean one of these learners instead: %s",
      cl, stri_flatten(possibles, collapse = " "))
  }
```

i dont like it. the first line should be isLearnerAvailable(cl). Maybe this encapsulates the try then.

and this is should also be better:
suppressWarnings(listLearners()$class))

suppressWarnings should be an option. and listing the learner names, just the strings, should be a direct function call. like getSupportedLearners.
