### ISSUE TITLE
show how to do normal cost-sens classification with mlr 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#114]
show an example application with#

a) binary classes
b) multi-classes

then extend later

**Comment by schiffner** [comment]
One could also mention cost curves (via plotROCRCurves, ViperCharts)

**Comment by larskotthoff** [comment]
Is this still relevant? If so, we should close here and open in the new tutorial repo.

**Comment by berndbischl** [comment]
Yes, it would be best to transfer the relvant infos here to the tutorial tracker

**Comment by larskotthoff** [comment]
See mlr-org/mlr-tutorial#15.
