### ISSUE TITLE
Metrics R package

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#1140]
There is the Metrics package https://github.com/benhamner/Metrics which we might include into mlr?

**Comment by catastrophic-failure** [comment]
Ben is lacking many metrics there for R (several which mlr supports already). Also I do have working code for normalizedGini and relative errors for regression (will work these into PRs soon).

**Comment by berndbischl** [comment]
just looked into the package. there is no reason we need to depend on it.
we can browse it for some measures we are missing. this will not be very many.

and possibly use it to unit-test against it.

**Comment by ja-thomas** [comment]
Just had a look at the package,

some stuff that he does have that we currently don't support ist
`MeanQuadraticWeightedKappa`
`ScoreQuadraticWeightedKappa`


I think we have everything else (maybe I overlooked something). Not sure how important these two are. 

@catastrophic-failure Do you know these measures and how "important" they are?

**Comment by berndbischl** [comment]
> some stuff that he does have that we currently don't support ist
> MeanQuadraticWeightedKappa
> ScoreQuadraticWeightedKappa

these measure are indeed sometimes used. 
we should include them, simply unit test a bit against the Metrics package, and then be done here.

**Comment by berndbischl** [comment]
> simply unit test a bit against the Metrics package, and then be done here.

maybe even this is bad idea. if Metrics changes, be break. lets simply include the new measures.
and somebody could do mini comparison, manually, to spot any differences that we could learn from.

**Comment by ja-thomas** [comment]
while we're on it: https://github.com/yanyachen/MLmetrics

**Comment by berndbischl** [comment]
@florianfendt 
can you pls compile a list what measures are in these other packages and whether it is easy to include them in mlr? then for the simple ones pls do that

**Comment by florianfendt** [comment]
| Measure                                                     | in mlr |
|-----------------------------------------|-------|
| Absolute Error (AE)                                    | ✔️        |
Average Precision at K (APK, AP@K)          | ❓ 
Area Under the ROC (AUC)                         | ✔️ 
Classification Error (CE)                              | ✔️ 
F1 Score (F1)	                                            | ✔️ 
Levenshtein                                            |  ❓ 
Log Loss (LL)	                                        | ❓ 
Mean Log Loss (LogLoss)                   |  ✔️ 
Mean Absolute Error (MAE)              |  ✔️ 
Mean Average Precision at K (MAPK, MAP@K) | ❓ 
Mean Quadratic Weighted Kappa                     | no
Mean Squared Error (MSE)                     | ✔️ 
Mean Squared Log Error (MSLE)  |	no
Quadratic Weighted Kappa	| no
Relative Absolute Error (RAE)  | ✔️ 
Root Mean Squared Error (RMSE) | ✔️ 
Relative Squared Error (RSE) | ✔️ 
Root Relative Squared Error (RRSE) | ✔️ 
Root Mean Squared Log Error (RMSLE) | no
Squared Error (SE) | ✔️ 
Squared Log Error (SLE) | no
Normalized Gini    | no
