### ISSUE TITLE
add a layer "TaskWrapper" to MLR

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1142]
Currently we have the preprocessing wrapper which wrap the preprocessing together with the learner, which is a great feature that allow us to tune the preprocessing wrapper together with the learner.  Shall we also have Wrapper just for task?  So the feature engineering on this task is regardless of the cascade/pipeline?    This is light weight compared to our current Wrapper which result to a learner. If we have this new"TaskWrapper",  we could let the user define their own function to do feature processing which could add domain knowledge into the training.

**Comment by berndbischl** [comment]
we will probably rewrite the task preprocressing anyway at some point in time. 
what you are saying is  very important. but for now:

either

a) do the feature generation manually before you use mlr
b) use the PreprocWrapper
