### ISSUE TITLE
Better documentation for measures

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#1144]
We need to improve the measures doc page.
Similar as for learners (see #1072) some notes get longer and longer.

**Comment by MasonGallo** [comment]
What if we linked to the "notes" within the tutorial site for each measure / learner? That way, we would create a page for each measure to list the info.

**Comment by berndbischl** [comment]
> What if we linked to the "notes" within the tutorial site for each measure / learner? That way, we would create a page for each measure to list the info.

how to do this should not be discussed here, but here: #1072 

this issue is just for adding details about the measures

**Comment by berndbischl** [comment]
@florianfendt 
some measures already contain nice formulas and so on in the notes. 
can you please make that equally could for all measures? 
so eg assume i have no idea what "mmce" means. can you fix that with 1-2 simple sentences in the note?

do you understand what i mean?
