### ISSUE TITLE
Automatically convert ordered factor features if the learner does not support that

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1145]
Should be offer a mlr option, that if some task contains ordered factors and the learner does not support these we just give a warning and convert them to unordered factors?

Could be useful for benchmarks with a large number of datasets.

Or do we already have something like that and I just don't know about it? (It seems kind of obvious)

**Comment by schiffner** [comment]
At the moment we have `fixDataForLearner` which has an option to convert ordered factors to integers. We discussed in #926 that this is not ideal and at the moment are leaning towards a wrapper doing these conversions.
With regard to learner properties: If the user says he wants ordered factors converted to factors we could just add property `"ordered"` to the wrapped learner.

**Comment by berndbischl** [comment]
> At the moment we have fixDataForLearner which has an option to convert ordered factors to integers. We discussed in #926 that this is not ideal and at the moment are leaning towards a wrapper doing these conversions.

yes. and the more i here about this i think we should not do much here anyhow. but completely refactor the whole preprocessing thing some point in the future.
