### ISSUE TITLE
write short blog post on mlr palermo workshop

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1155]

**Comment by ja-thomas** [comment]
I wrote a short text and added some pictures, feel free to iterate over that, my pictures aren't that great unfortunately.

**Comment by jakob-r** [comment]
I read it and I think it's fine to be published. We can add better pictures later (if available).

**Comment by ja-thomas** [comment]
published

**Comment by berndbischl** [comment]
thank you! but can we at least add a list of people who was there?
