### ISSUE TITLE
jenkins shows NullPointer exception

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1158]
directly on the first page if you click on the link

**Comment by ja-thomas** [comment]
Don't want to start diskussing label usage, but is that really severe (e.g. "blocking" us) ?

We still have travis and also a longer period of time with jenkins completely down.

**Comment by berndbischl** [comment]
@ja-thomas you are kinda right. but either we see jenkins as ingetral for testing or not.
problems here, both on travis and on jenkins, have hurt us too much in the past.
so i am labeling any of these things as severe now.
they must be solved with utmost priority.

**Comment by larskotthoff** [comment]
Caused by using a direct link to a page that you're not allowed to see when you're not logged in, apparently.

**Comment by berndbischl** [comment]
it actually was the main page...

**Comment by larskotthoff** [comment]
That definitely shouldn't happen (and I haven't seen this before). How were you able to log in then?

**Comment by berndbischl** [comment]
the top bar was ok. the null pointer exception was in the main window, where normally the builds can be seen. 
at some point i noticed that the top bar said "log in" (i.e. that i was logged out).
so i guessed that logging in.....
