### ISSUE TITLE
mini fixes for PR #1157

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1164]
see my last post in the PR thread

**Comment by berndbischl** [comment]
https://github.com/mlr-org/mlr/pull/1162

**Comment by berndbischl** [comment]
EDIT: I linked the wrong PR number. fixed.

**Comment by larskotthoff** [comment]
@zmjones Could you make a new PR for this please?

**Comment by zmjones** [comment]
yes. i am a bit confused by bernd's review though.

i am trying to handle the case of extracting measure ids when you pass a list of measures or only one. the if statement isn't to check that the arg has the right class, but to just distinguish between these two cases so i can extract the id using `extractSubList`. What is wrong with this?

**Comment by larskotthoff** [comment]
Bernd's point is that you already have a list after calling `checkMeasures`, so the check after that is not necessary (no, of course that's not documented).

**Comment by zmjones** [comment]
ah ok. thanks.
