### ISSUE TITLE
Problem in  `plotThreshVsPerf` if `pretty.names = FALSE`

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#1167]
Dear plot master @zmjones 

I have a problem with `plotThreshVsPerf` if `pretty.names = FALSE`:
```
lrn = makeLearner("classif.lda", predict.type = "prob")
mod = train(lrn, task = sonar.task)
pred = predict(mod, task = sonar.task)
d = generateThreshVsPerfData(pred, measures = list(fpr, fnr, mmce))
plotThreshVsPerf(d, pretty.names = FALSE)
# Error in melt.data.table(as.data.table(obj$data), measure.vars = mnames,  : 
#   object 'mnames' not found
```
My guess is that in [your latest commit](https://github.com/mlr-org/mlr/commit/1525ff0504fc11bf810de3ffa0d10d13616aef4c) the else case corresponding to
https://github.com/mlr-org/mlr/blob/master/R/generateThreshVsPerf.R#L155
vanished accidentally, but am not sure if I'm missing something.

**Comment by zmjones** [comment]
yep that looks correct. PR incoming

**Comment by schiffner** [comment]
Thx!
