### ISSUE TITLE
master is currently broken

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1169]
seems to have happened in the last merge by zach / lars
only happens in R oldrelease

@larskotthoff @zmjones

**Comment by zmjones** [comment]
I just looked at it. Looks unrelated to the commit. A package version
mismatch in the container I think.

**Comment by berndbischl** [comment]
shall we disable oldreslease again? 
because now we have a broken travis badge on the front page

**Comment by larskotthoff** [comment]
This occurs in other PRs as well. I don't see a solution other than disabling oldrelease.
