### ISSUE TITLE
Custom functions do not work in parallel

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#117]
I cannot run custom functions in parallel. Here's an example that only runs in unparallelized mode:

``` r
library(mlr)
library(parallelMap)
parallelStartSocket(4)
library("mlbench")
data(Sonar)
makeRLearner.classif.glmnet = function() {
  makeRLearnerClassif(cl = "classif.glmnet", package = "glmnet",
                      par.set = makeParamSet(makeNumericLearnerParam(id = "alpha", default = 1, lower = 0, upper = 1),
                                             makeNumericLearnerParam("lambda", lower = 0.000001, upper = 1, default = 0.001)),
                      properties = c('numerics', 'prob', 'twoclass', 'factors'))
}
trainLearner.classif.glmnet = function(.learner, .task, .subset, .weights, ...) {
  d = getTaskData(.task, .subset, target.extra = TRUE)
  glmnet(as.matrix(d$data), d$target, family = "binomial", ...)
}
predictLearner.classif.glmnet = function(.learner, .model, .newdata, ...) {
  if(.learner$predict.type == 'prob'){
    x <- predict(.model$learner.model, newx = as.matrix(.newdata), type = 'response')
    x <- cbind(1 - x, x)
    colnames(x) <- .model$task.desc$class.levels
  } else {
    x <- factor(predict(.model$learner.model, newx = as.matrix(.newdata), type = 'class')[,1])
  }
  x
}

task = makeClassifTask(data = Sonar, target = "Class", positive = "M")
lrn = makeLearner("classif.glmnet")
rdesc = makeResampleDesc("CV", iters = 3)
r = resample(lrn, task, rdesc)
```

**Comment by berndbischl** [comment]
I have explained this in the tutorial under "parallel"

I guess we wont do much more now

**Comment by rpinsler** [comment]
It seems that once you provide a level argument within parallelStart* you *must* provide the same level argument for parallelExport/parallelLibrary/parallelSource. I found this a little bit confusing because I assumed that by default the latter three functions make the objects available for all levels (and the argument is simply to restrict the exporting to a particular level). Maybe it is worth adding a note about this.

**Comment by berndbischl** [comment]
Ah. that is a good point. Let me think about this for a moment.

**Comment by larskotthoff** [comment]
Should this issue be moved to the tutorial tracker?

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
