### ISSUE TITLE
mlr dev docker image

### ISSUE THREAD

**Issue by MasonGallo** [mlr-org/mlr#1173]
Note: I don't have much experience / expertise on this, so just ideating at this point...

Would it be possible for us to create a "dev" docker image for mlr? Maybe something similar to the travis build for local dev work? 

Happy to help make this happen if anyone has thoughts/ideas

**Comment by larskotthoff** [comment]
Yes, absolutely. Here's a Dockerfile that may work:

```
FROM ubuntu:latest
RUN apt-get update -q
RUN apt-get install -yqq --no-install-recommends software-properties-common python-software-properties wget unzip git libcurl4-openssl-dev libxml2-dev openssl libgmp-dev texlive texinfo texlive-fonts-extra gsettings-desktop-schemas 
RUN add-apt-repository -y ppa:marutter/rrutter
RUN apt-get update -q
RUN apt-get install -yqq --no-install-recommends r-cran-rjava
RUN apt-get build-dep -yqq r-cran-rjava
RUN apt-get build-dep -yqq r-cran-rgl
RUN R CMD javareconf
RUN echo 'options(repos = "http://cran.rstudio.com/"); install.packages(c("mlr", "devtools"), dependencies = c("Depends", "Imports", "Suggests"))' | R --no-save --quiet
RUN echo 'library("devtools"); install_github("berndbischl/ParamHelpers")' | R --no-save --quiet
RUN echo 'library("devtools"); install_github("mlr-org/mlr", dependencies = c("Depends", "Imports", "Suggests"))' | R --no-save --quiet
RUN locale-gen en_US.utf8
RUN update-locale LANG="en_US.UTF-8"
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV TRAVIS true
```

**Comment by jakob-r** [comment]
Can this be closed or do we want to add a Dockerfile to the Docker Hub?

**Comment by MasonGallo** [comment]
I would like to test what @larskotthoff shared and possibly add a link to the coding guidelines wiki just haven't had a chance yet

**Comment by MasonGallo** [comment]
Discussed with @larskotthoff. I am going to investigate how feasible this is and how much work it will require to maintain. Gonna close for now. Anyone who has thoughts/ideas welcome to reopen.
