### ISSUE TITLE
generatePartialDependenceDate: can we allow obj also to be a learner

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1177]
and then internally train on "input"?
might be a nice shortcut.

or is this bad design? (i dont really see a downside here?)

**Comment by zmjones** [comment]
idk i am not a big fan of this idea. the reason i don't particularly like it is because i can't imagine a research scenario in which you'd want to do this. so if it is only for teaching purposes then i think that could mislead students. i mean it already only takes two lines. that is pretty short.

**Comment by pat-s** [comment]
I don't think that we want to make such changes in _mlr_ right now.
