### ISSUE TITLE
getLearnerID: function seems missing?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1178]
we have getTaskId, but not this one?

**Comment by larskotthoff** [comment]
Well, there are lots of things for which we currently don't have getters. Hiwi task?

**Comment by schiffner** [comment]
For naming consistency we should then also rename setId -> setLearnerId

**Comment by berndbischl** [comment]
> Well, there are lots of things for which we currently don't have getters. Hiwi task?

i am noting these issues down when i work with mlr and see these problems.

**Comment by berndbischl** [comment]
PR is here #1185
