### ISSUE TITLE
mlr families man page: not acessible and more issues

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1183]
1) if you install the package, then do library(mlr), then ?mlrFamilies, the page is not found.
your man page is probably wrong

2) mlr-families would be a better name in R-style

3) the whole man page seems to have many NULL entries. please filter them out.

**Comment by larskotthoff** [comment]
1) Fixed.
2) That would be inconsistent with the rest of mlr though. We don't have any pages with hyphens.
3) Seems to occur only on Travis -- I think I fixed this, but can only test with a master commit.

**Comment by larskotthoff** [comment]
1 and 3 are fixed; how important is 2 to you?

**Comment by berndbischl** [comment]
>  how important is 2 to you?

its ok, you can leave it. please to to finish this.

**Comment by larskotthoff** [comment]
Ok, in that case everything is done.
