### ISSUE TITLE
plotLearnerPrediction should work on a trained model

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1190]
Either
A) make use of _S3_ to call it either on a model or a learner, or
B) fully replace old functionality because it is strange. Why is there resampling code in the plot function just to add a number (i.e. miss classification rate) to the title?

**Comment by berndbischl** [comment]
> S3 it or fully replace old functionality because it is strange.

nobody understands what you mean if you post such short sentences. 
the first part i can guess, the 2nd: not so much.

**Comment by jakob-r** [comment]
I edited it

**Comment by berndbischl** [comment]
> fully replace old functionality because it is strange.

then pls make a positive suggestion, how?

the CV nr in the title is there, because the plot only shows the fit. i thought that it would be informative and you can turn it oft.

in general, we could try to strive for the genData, plotStuff API that we use elsewhere?
but before we get it wrong a 2nd time we have to write it down here.
paging plotmaster @zmjones to the thread as well

**Comment by zmjones** [comment]
I think we talked about this before.

plotLearnerPrediction is a teaching tool only as far as I understand it and so it is not so concerning to me that we don't have a generate/plot setup. after all the generate function would just be a wrapper to train on 2-3 features.

**Comment by jakob-r** [comment]
I write because for *mlrMBO* we store away models and it would be totally nice just to have look at them without writing all the stuff over and over again.
So what we would need is
```r
# Define the X Space of the given data as a par.set
# obj: data.frame only containing X or task
generateParSetFromData = function(obj, stretch) {...}

# plot (1) ,2 or 3d depending on the par.set
# model: trained model
# par.set: ParSet of Length 1 to 3 
# task: optionally pass a task so that observation points can be added to the plot including miss classifications.
plotLearnerModel = function(model, par.set, task = NULL) {...}
```

Question: What happens when we have more then 3 Features? 
Suggestion: To count the length of the ParSet we only look at continuous values. Everything else will be dealt with `facet.grid`.

**Comment by berndbischl** [comment]
ok, some comments:

1) so, basically you want plotMBOResult, a function that the we already have, but looks not so good?
or another plot helper, but in mbo. that means that the issue should also be opened there. we can discuss changes to plotLearnerModel here, but guess we will always need special code that goes in mbo for this.

2) How do you suppose this will ever work if you have a opt problem with more than 2 or 3  features?
plotLearnerModel was only created for this task, plotting low dimensional models. is this realistic for your use case?

3) isnt what @MasonGallo has done more relevant to us here? the plots for hyper par optimization. imho they might possibly be generalized to what we want. have you looked at those? they cover many special cases already.

**Comment by jakob-r** [comment]
1) I am not talking about the mbo result but intermediate models mainly. I want to see how the surface of the surrogate looks. I can imagine that also others want to plot the predictions. So why not have the most general functionality in mlr?

2) We pretty often work with lower dimensional models in the try out phase - and this is where we want to be able to plot. 
It can partly work by keeping some other features fixed (i am thinking of a shiny slider here)

3) mbo is not always hyperparameter optimzation

**Comment by berndbischl** [comment]
we talked on hangout.

we agreed: 

* lets open a clean issue here, that outlines API changes to plotLearnerPrediction

* @jakob-r looks at masons stuff and what we have in MBO. then we open a clean issue in mbo there, to plan what we want to plot a single iteration from an MBO result.
