### ISSUE TITLE
Different first result when setting seed

### ISSUE THREAD

**Issue by MasonGallo** [mlr-org/mlr#1192]
Is this working as intended?

```
library(mlr)
options(mlr.debug.seed = 1L)
rdesc = makeResampleDesc("CV", iters = 3)
resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.255
```

But then if I call resample again, I get a different result:

```
resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.23
```

**Comment by larskotthoff** [comment]
To get the same result, you would need to set the seed again before calling `resample`.

**Comment by berndbischl** [comment]
> To get the same result, you would need to set the seed again before calling resample.

not really. the mlr.debug.seed is something completely internal. it is not exposed at all for a user.
it is ONLY used in unit testing. and ONLY effects learner training and prediction.

**Comment by berndbischl** [comment]
before a learner is trained in mlr, or predicted, we set the debug.seed, if it exists.
to ensure reproducible outputs of those

**Comment by MasonGallo** [comment]
So if I'm following, that means we throw out the seed after train/predict? What if the user wants the predictions etc to be reproducible?

**Comment by berndbischl** [comment]
now i dont get what you mean. have you looked at the codebase in R/ where the debug.seed is used?

**Comment by MasonGallo** [comment]
@larskotthoff my results are the same after the 2nd result tho ex:

```
options(mlr.debug.seed = 7L)
resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.24
```

```
resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.245
```

```
resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.245
```

**Comment by schiffner** [comment]
You need to use `set.seed`. The options call does not do this.

```
set.seed(123)
> resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.242
Resample Result
Task: PimaIndiansDiabetes-example
Learner: classif.ksvm
mmce.aggr: 0.24
mmce.mean: 0.24
mmce.sd: 0.06
Runtime: 0.183741
> set.seed(123)
> resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.242
Resample Result
Task: PimaIndiansDiabetes-example
Learner: classif.ksvm
mmce.aggr: 0.24
mmce.mean: 0.24
mmce.sd: 0.06
Runtime: 0.185906
```

**Comment by berndbischl** [comment]
of course they are. i am trying to explain it here.

a) please look in R/ how the debug.seed is used. i also wrote it down above.

b) in terms of normal package use: mlr does not offer you anything special here. if you want seeding, use set.seed, the general R mechanism.

c) ONLY for the unit tests i need this:
if i train the randomForest "manually" and with mlr, i want to compare the results. and they should be the same. now, for the former call, i have to set a seed. for the latter, with mlr, i can save some typing, by always setting the debug.seed internally. that is the ONLY reason the mlr.debug.seed exists. maybe it has a bad name, and maybe it is underdocumented, but that is what it is.

**Comment by MasonGallo** [comment]
@schiffner @berndbischl  `set.seed` reproduces the same behavior in my comment above to @larskotthoff where the 1st run is different from the subsequent runs:

```
> set.seed(123)
> resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.237
Resample Result
Task: PimaIndiansDiabetes-example
Learner: classif.ksvm
mmce.aggr: 0.24
mmce.mean: 0.24
mmce.sd: 0.05
Runtime: 0.090121
> resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.245
Resample Result
Task: PimaIndiansDiabetes-example
Learner: classif.ksvm
mmce.aggr: 0.24
mmce.mean: 0.24
mmce.sd: 0.03
Runtime: 0.0896211
> resample("classif.ksvm", pid.task, rdesc)
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
[Resample] Result: mmce.test.mean=0.245
Resample Result
Task: PimaIndiansDiabetes-example
Learner: classif.ksvm
mmce.aggr: 0.24
mmce.mean: 0.24
mmce.sd: 0.03
Runtime: 0.085978
```

**Comment by berndbischl** [comment]
i have now really no idea what you are talking about.

**Comment by larskotthoff** [comment]
Yes, sorry, I missed the debug part :)

@MasonGallo You still have the debug seed set, that's why you're getting the same result in subsequent runs.

**Comment by MasonGallo** [comment]
D'oh! Thanks all!

Long story short: don't use the debug seed except in unit testing otherwise you're gonna have a bad time
