### ISSUE TITLE
Measures that fail on single/all identical samples

### ISSUE THREAD

**Issue by catastrophic-failure** [mlr-org/mlr#1195]
Per #1172 now measures that don't work on  single/all identical samples may include a warning. I'm willing to add the warnings and the tests if there's a consensus on which measures should have them.

For starters, `expvar` fails just like `rrse`.

---

There might be overlap with #1154, so an unified approach needs to be defined.

**Comment by larskotthoff** [comment]
I think you've just said which measures should have them -- those that fail on single/all identical truth/prediction values :)

We can expand this definition later, but it would be very helpful if you could do a PR for those.

**Comment by catastrophic-failure** [comment]
@larskotthoff Sorry, I meant some kind of list. Inspecting the functions reveal some problematic ones, but I'm not used to all of them, so I'm probably going to miss some.

**Comment by larskotthoff** [comment]
Start with the ones you can easily identify.

**Comment by berndbischl** [comment]
> There might be overlap with #1154, so an unified approach needs to be defined.

that PR is about something else, there will be no overlap here is guess (hope?)
at least what the topic concerns. if you touch measures like TPR and so on (ROC) there might be (hopefully fixable) conflicts.

and dont forget to write one unit test then where you test all measures on a single instance.

**Comment by catastrophic-failure** [comment]
@berndbischl @larskotthoff I just started working on this in #1211 . I see `ber` also handles special cases, and returns an `NA_real_` in case of missing predictions.

**Comment by catastrophic-failure** [comment]
There's a possible issue we should solve. I'm adding warnings to the `measureX` functions, but I think it should be better located at the `x` objects. The reason is simple: if, for any reason, we add a measure that uses the same `measureX` the warning won't make sense to the user. What do you think?

**Comment by larskotthoff** [comment]
I would make the error message suitable for all calling measures.

**Comment by catastrophic-failure** [comment]
Hey, long time no see. I'm finishing my Master's Dissertation, going to defend near the end of February, so I revisited the repository to see what's changed.

I'm closing this issue as the commit has been merged already, but if any measure is missing tests and warnings (and tests for warnings), ping me here and I'll add those in new PRs, so I continue to contribute to the repo.
