### ISSUE TITLE
mlr blog mini issues: the blog contains no backlink to mlr and the about page is crappy

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1196]
1) can we have a backlink in the top row to go to mlr? i think the logo should link to the main mlr  README

2) the about page is not so good.

a) the intro text is crappy
rewrite it.

b) the personal details are now redundant with what we have in the wiki
we should just list names with a mini sentence and link to the mlr persons wiki page

**Comment by berndbischl** [comment]
we should also backlink to rbloggers, tal asked about this in his email

**Comment by jakob-r** [comment]
This issue should be here: https://github.com/mlr-org/mlr-org.github.io/issues

**Comment by jakob-r** [comment]
:heavy_check_mark:  Backlink to rbloggers in the footer

**Comment by berndbischl** [comment]
> This issue should be here: https://github.com/mlr-org/mlr-org.github.io/issues

will do next time, it solving it takes too long ls copy it

> b) Question: mlr-bloggers = mlr-authors? Target group might not be the same so I think different texts are legit.

i do agree that they might different. thats why i said this:
>> we should just list names with a mini sentence and link to the mlr persons wiki page
names = blog authors, then 1 mini sentence, then at least for all mlr devel a link to the mlr devel wiki (and maybe the home page of the guy)

**Comment by berndbischl** [comment]
Tal also emailed me that our feed is broken. We should repair that ASAP.

```
BTW, I noticed your feed has an error:
https://mlr-org.github.io/feed.xml
Inline image 1

```

**Comment by jakob-r** [comment]
[![[Valid RSS]](https://validator.w3.org/feed/images/valid-rss-rogers.png)](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmlr-org.github.io%2Ffeed.xml)

**Comment by jakob-r** [comment]
If something is still wrong open an issue [here](https://github.com/mlr-org/mlr-org.github.io/).

**Comment by berndbischl** [comment]
@jakob-r 
how is the "about page" fixed now? it seems point 2) seems to be not handled at all?

**Comment by pat-s** [comment]
Since we have a completely new blog site now, this issue is outdated.
