### ISSUE TITLE
documentation of the package: find functions in files

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#1197]
It would be cool to have a file that for each function gives you the file where you can find the function. 
@smilesun are you working on something like this?

**Comment by smilesun** [comment]
What do you mean exactly ? I don't quite understand

**Comment by PhilippPro** [comment]
Something like a table:

Function                                        file
predict.WrappedModel                 predict.R
makePrediction                             Prediction.R
makePrediction.TaskDescRegr   Prediction.R
... (and so on)

So when you search a function you just have to look at this table. I would do this with a search algorithm, that searches "function" in each file and looks the name before the "=" sign.

**Comment by berndbischl** [comment]
use a search tool over multiple files. noboby wants to maintain a file like this.

and we are discussing this in slack now
