### ISSUE TITLE
listLearners: give output a s3 class and have printer

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1201]
everytime i call listLearner, the (table) output looks really crappy on the console. 
expecially as the not is included. 

shall we simply give the output an s3 class, which we simply add to the data.frame, so it looks better?

returning data.table would (of course) already mitigate the problem a lot. but the "note" column is still bad.

we could also have an option not to include this by default?

or: my last sentences are bad design and we really should handle this in a printer?

@mllg  @larskotthoff what do you think?

**Comment by berndbischl** [comment]
@zmjones  @jakob-r

**Comment by larskotthoff** [comment]
I would do this with a printer.

**Comment by mllg** [comment]
:+1: for S3 printer to generate something more compact if this bugs you.
