### ISSUE TITLE
vignette vs. mkdocs online tutorial 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1208]
@zmjones  started this discussion with @larskotthoff here: #1207 
he basically seems to want a large tutorial vignette either in addition to or instead of the online tutorial

@zmjones pls discuss this here, and outline a summary of what you want again

my answer to you now:

but i have some arguments against this
- i hate pdfs (for such a thing), and i don't want a PDF exclusively for the tutorial
- our large tutorial does not "fit" good to a vignette, interlinking chapters is much harder, etc. we specifically selected mkdocs for this reason. @mllg checked this a bit IIRC when we created the current mlr tutorial and we explored whether we could simply convert it to vignette
- i don't see how adding the tutorial as it is to the package as a vignette, would not severely slow down the master build (for maybe an hour?) 
- the mlr tutorial PDF will be quite large. you now make the package a few MB larger, for something that not everybody wants on their local machine (ok, somehow minor point in the list)

but lets think about what relevant points your suggestion adresses:
- the current mlr mini vignette seems rather stupid and none of us really cares about this. i would much rather substitute this with a pure link to the online tutorial. ()
- it is really bad that we cannot check whether PRs (for mlr) break the tutorial, and we figure this out after having merged

IMHO: 
- we could MAYBE live with a longer travis build. this might be better than having a broken tutorial or bad PR merged. we just merge a bit slower then. the only requirement than is that people dont use travis to "debug" and test their code. they HAVE to know how to test and check efficiently on their local machine.
  this would mean we clone the tutorial also in the mlr travis file and build it to check it.
- we figure out whether we can substitute the mlr vignette with a link to the online tutorial.

**Comment by pat-s** [comment]
Everything has been reorganized in the tutorial and we now only have one HTML version.
