### ISSUE TITLE
multilabel tests are not standard

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1217]
<s>I don't know if it's a problem but I wanted to ask if there is any specific reason, why the tests in test_base_multilabel.R are not all using the `test_that` enviroment.

https://github.com/mlr-org/mlr/blame/master/tests/testthat/test_base_multilabel.R#L151</s>

Okay. The function internally calls `test_that`. Looks a bit weird but is probably okay?

**Comment by jakob-r** [comment]
Well, it makes debugging a bit harder.

**Comment by larskotthoff** [comment]
So what's the issue here? What do you want to do instead?

**Comment by jakob-r** [comment]
It should be fine like this.
