### ISSUE TITLE
racing paper in citation()

### ISSUE THREAD

**Issue by HeidiSeibold** [mlr-org/mlr#1218]
Cite paper mentioned in readme in package:

Lang, Michel, Helena Kotthaus, Peter Marwedel, Claus Weihs, Jörg Rahnenführer, and Bernd Bischl. "Automatic model selection for high-dimensional survival analysis." Journal of Statistical Computation and Simulation 85, no. 1 (2015): 62-76.

also the readme is inconsistent (Lang, Michel versus Helena Kotthaus)

**Comment by ja-thomas** [comment]
We'll do that as soon as the paper is accepted

**Comment by mllg** [comment]
I've changed the README and just linked to the journal page.
