### ISSUE TITLE
line plot for benchmarking

### ISSUE THREAD

**Issue by HeidiSeibold** [mlr-org/mlr#1219]
```
ggplot(runs.list, aes(x = factor(name, levels = unique(runs.list$name)), y = predictive.accuracy)) +
  geom_point() +
  geom_line(aes(group = task.id), alpha = 0.6) +
  ylab("Predictive Accuracy") + xlab("")
  theme(panel.grid.major.x = element_blank())
```

or including boxplots

```

ggplot(runs.list, aes(x = factor(name, levels = unique(runs.list$name)), y = predictive.accuracy)) +
  geom_boxplot() +
  geom_line(aes(group = task.id), alpha = 0.6) +
  ylab("Predictive Accuracy") + xlab("")
  theme(panel.grid.major.x = element_blank())
```

see OpenML paper
[unnamed-chunk-8-2.pdf](https://github.com/mlr-org/mlr/files/457495/unnamed-chunk-8-2.pdf)

**Comment by jakob-r** [comment]
That is a feature request? Well we already have all [this fancy stuff](http://mlr-org.github.io/mlr-tutorial/devel/html/benchmark_experiments/index.html#benchmark-analysis-and-visualization) but I am sure we could add lines to it.

**Comment by HeidiSeibold** [comment]
@berndbischl asked me to write the issue. I think he liked to plot :)

**Comment by pat-s** [comment]
This should go into _mlr3viz_.
