### ISSUE TITLE
Tuning with Out of Bag Predictions

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#1221]
Advantage: Much faster tuning than with other resampling technique (e.g. 5 times faster than 5-fold-CV).

I just made a quick (1 hour) and dirty solution creating a new learner, but this is of course not the general solution. 

We need a new resampling technique "OOB", so we can use it in makeTuneWrapper.
So we need to change something in doResampleIteration, as we do not need any prediction anymore. 
Something like:

```
if (pp == "oob") {
    pred.oob = getOOBPreds(m, task)
    ms.train = vnapply(measures, function(pm) performance(task = task, model = m, pred = pred.oob, measures = pm))
}
```

Any comments on this?

**Comment by larskotthoff** [comment]
Hmm, this wouldn't work for all learners though. The current resample methods do work for everything -- how do you see this working? Throw an error if the learner doesn't support it? Or fall back to something else?

**Comment by ja-thomas** [comment]
But we have a tag for oobag of the learner, so we could do a quick check and give and informative error message when a learner that does not support oobag is called with `resampling = oob`.

I think it can be useful in some cases, especially since we have a convinient way to extract oob errors.

**Comment by pat-s** [comment]
This should go into _mlr3_.
