### ISSUE TITLE
Version 2.10 released via CRAN or GitHub?

### ISSUE THREAD

**Issue by srp33** [mlr-org/mlr#1222]
Dear Colleagues,

I'm anxious to use version 2.10, which has some bug fixes that I need. But CRAN is still on version 2.9, and the latest GitHub release is version 2.8. Any idea on when 2.10 might be released via one or both of these channels?

Thanks,
-Steve

**Comment by PhilippPro** [comment]
Dear Steve,

you can install the latest github version, which is already version 2.10 via 
`devtools::install_github("mlr-org/mlr")`

What do you mean with version 2.8?

**Comment by srp33** [comment]
Dear Philipp,

I understand that I can install the development version, but I want to the release version (2.10). This makes it so I can install a specific version and don't have to worry that I am installing code that is under active development.

On your GitHub release page (https://github.com/mlr-org/mlr/releases), it shows that releases have been made up to v2.8, but perhaps you are no longer releasing via this mechanism. It is easiest for me to install via CRAN anyway.

Thanks!

**Comment by berndbischl** [comment]
@srp33 
hi.

1) we try to release every 4-5 weeks to CRAN now. so 2.10 should be pushed now.

2) i saw your first post about this and wanted to reply earlier. sorry. also i understand that you wait for the fix.

3) i am on the open machine learning workshop now, and currently working 24/7 on openml for this week. i will try to get 2.10 done this week. maybe earlier, but i dont want to promise this now.

ok? best

bernd

**Comment by berndbischl** [comment]
PS:
we really dont use the github releases. i dont want to maintain that, just an extra burden. i will remove those files and make that clear in the README. releases are on CRAN and only there.

**Comment by srp33** [comment]
Bernd,

Thanks for your reply. That sounds good. I'll keep my eye open for the next release on CRAN.

Regards,
-Steve

**Comment by berndbischl** [comment]
we have begun to clean mini things up an hour ago. keep your fingers crossed that we find nothing serious :)

**Comment by srp33** [comment]
Hi Bernd,

Just wanted to see if you could provide an update on this?

Many thanks!

**Comment by berndbischl** [comment]
upload will be tonite. sorry for the slowness

**Comment by jakob-r** [comment]
The mlr upload on cran is a bit delayed. Anyhow I think we can close here.

**Comment by srp33** [comment]
Any idea how long it takes to be update on CRAN? It's been a week now.
