### ISSUE TITLE
Reactivate test for tuning does not break with small discrete values

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1227]
We should reactivate the test as soon as the fix in ParamHelpers (version 1.9) is on CRAN.

For now it is deactivated so that we can release.

See PR #1226

**Comment by larskotthoff** [comment]
Is there a need for an issue in addition to the pull request? Can you please describe the problem?

**Comment by ja-thomas** [comment]
This is a reminder that we reactivate the test. The PR can be closed and then we may forget.

But since we will most likely not use the PR we can close this (after the release)

**Comment by ja-thomas** [comment]
obsolete since we updated PH first
