### ISSUE TITLE
xgboost mini issue: some params should not be defined as "tunable"

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1240]
print.every.n
verbose

and so on. needs to be checked.

classif.xgboost and regr.xgbosst

**Comment by mllg** [comment]
Also, check the default for `maximize` and fix it or drop a comment why `TRUE` or `FALSE` is correct for the respective learner.

**Comment by larskotthoff** [comment]
This should be fixed; please reopen if there's anything else.
