### ISSUE TITLE
mlbench pkg should be escaped in examples, eventually also in tests

### ISSUE THREAD

**Issue by jangorecki** [mlr-org/mlr#1246]
Hi,
Just came to inform that suggested packages used in examples should be escaped, so not mandatory to run examples. Best way is to use `if (requireNamespace(.)) {_actual_code_}` function. Otherwise you should move `mlbench` (and potentially others, `mlbench` was first to fail) to imports.

```
* checking examples ... ERROR
Running examples in ‘mlr-Ex.R’ failed
The error most likely occurred in:

> ### Name: makeClassifTask
> ### Title: Create a classification, regression, survival, cluster,
> ###   cost-sensitive classification or multilabel task.
> ### Aliases: ClassifTask ClusterTask CostSensTask MultilabelTask RegrTask
> ###   SurvTask Task makeClassifTask makeClusterTask makeCostSensTask
> ###   makeMultilabelTask makeRegrTask makeSurvTask
> 
> ### ** Examples
> 
> library(mlbench)
Error in library(mlbench) : there is no package called ‘mlbench’
Execution halted
```

The best way to check is remove all suggested deps and try R CMD check. More details in [R-exts](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Package-Dependencies).

**Comment by berndbischl** [comment]
Hi Jan,

1) As this is simply a recommendation, and not required by checks with "--as-cran", and would create considerable work on our side: 
Could you please provide some context why you want us to change this?

2) Please note that nothing what you have suggested, as a "workflow solution", really does work so nicely. We need to ensure this then for all future versions of mlr. 

a) Importing such packages (needed in examples) is inappropriate. I am not enlarging the dependency chain of the package for *everybody* so some persons can run some examples in an slightly easier fashion.

b) > the best way to check is remove all suggested deps and try R CMD check

Sure. To do this once. Which is still annoying. In order to do this properly, and to ensure that this does not happen again in the future, we basically have to create a custom Jenkins job now, just for this thing.

3) I will not be able (whatever the result of this discussion) change this for the upcoming release. So the first possible potential fix for this would be in 4-6 weeks.

@larskotthoff  @mllg

**Comment by jangorecki** [comment]
1.
Any workflow that builds and tests mlr package will require to handle this exception, using `--no-examples` or installing extra suggested dependency (which is not always possible). Submissions to CRAN also perform package check without the need to install all suggested dependencies, they are optional, but most of the available. It may eventually end up in error during CRAN submission if for some reason optional package won't be available, which is happening from time to time. (you probably know) Only depends, imports and linking to are verified to be present during CRAN check.

2.
> Importing such packages (needed in examples) is inappropriate.

agree, but official recommendation (`if(requireNamespace(.))`) is a win-win here.

> Sure. To do this once. Which is still annoying. In order to do this properly, and to ensure that this does not happen again in the future, we basically have to create a custom Jenkins job now, just for this thing.

Yes, this is a software quality control matter. You can either include that in CI workflow, or ask developers to look into this issue when adding new suggested dependencies. Dependencies aren't moving that fast so this still can be reasonable way to handle that. The way I'm doing it is exactly as you suggest, an extra CI job (gitlab in my case) which runs on clean R environment without extra packages pre-installed. This job reveals few other issues that couldn't be spotted if checking package would always have all optional dependencies. I have also CI job that ensure all suggested deps are present (using `_R_CHECK_FORCE_SUGGESTS_` env var) so no tests are being skipped.

I've found R-way of managing dependencies really outstanding comparing to other languages and I like to cultivate it, and since this hit me during testing `mlr` I decided to report :)

3.
No rush, just informing.

**Comment by larskotthoff** [comment]
Thanks for your report. We haven't been very careful with this, and mlr uses a lot of packages. You're absolutely right that we could and should be better about this. We already have various jobs that test combinations of CRAN and development packages, with various other things changed. We'll add another job to test this.

**Comment by berndbischl** [comment]
@jangorecki 
Thank you for your longer clarification. We will look into this, to make this easier and more robust.

**Comment by berndbischl** [comment]
@larskotthoff 
if you can set this up on jenkins this would be cool. I can try to clean up mlr then locally, once.

Basically that should happen in the new job.
- clone mlr. 
- only install depends and imports packages
- run R CMD check
- the unit tests should only run the "base" group (which is what we run on CRAN)

**Comment by larskotthoff** [comment]
So run `R CMD check --as-cran`?

**Comment by berndbischl** [comment]
> So run R CMD check --as-cran

sure, yes.

**Comment by berndbischl** [comment]
@larskotthoff 
is it possible to build an extra jenkins job to check that we got rid of this problem now completely?

**Comment by larskotthoff** [comment]
We already have a job that runs with --as-cran, or do you mean something else?

**Comment by berndbischl** [comment]
i mean with minimal packages installed, so the same problem is triggered that the OP reported

**Comment by larskotthoff** [comment]
AFAIK I tried this but figuring out the minimal number of packages wasn't trivial. Running it without the suggests didn't work as caret was required for something.

**Comment by berndbischl** [comment]
the minimal nr of packages is simply depends + imports + (maybe) random forest and rpart for testing
mlr should be installed from GH
one should "R CMD check" and run only the unit tests in group "base"
if that does not pass, it is likely a problem on our side

**Comment by rezwanulhaquerezwan** [comment]
I am getting following errors . How can I solve it ?

```
> install.packages("mlbench")
trying URL 'https://cran.rstudio.com/src/contrib/mlbench_2.1-1.tar.gz'
Content type 'application/x-gzip' length 920768 bytes (899 KB)
==================================================
downloaded 899 KB

* installing *source* package ‘mlbench’ ...
** package ‘mlbench’ successfully unpacked and MD5 sums checked
** libs
/home/rezwan/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -I/home/rezwan/anaconda3/lib/R/include -DNDEBUG   -D_FORTIFY_SOURCE=2 -O2 -I/home/rezwan/anaconda3/include   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/rezwan/anaconda3/include  -c waveform.c -o waveform.o
make: /home/rezwan/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc: Command not found
/home/rezwan/anaconda3/lib/R/etc/Makeconf:160: recipe for target 'waveform.o' failed
make: *** [waveform.o] Error 127
ERROR: compilation failed for package ‘mlbench’
* removing ‘/home/rezwan/anaconda3/lib/R/library/mlbench’
Warning in install.packages :
  installation of package ‘mlbench’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpoIHfXL/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
```

```
> library(mlbench)
Error in library(mlbench) : there is no package called ‘mlbench’
```

**Comment by larskotthoff** [comment]
It looks like your environment got messed up and it can't find the compiler.
