### ISSUE TITLE
Getting error during train function

### ISSUE THREAD

**Issue by nitsourish** [mlr-org/mlr#1248]
I encountered following error when I tried to train xgboost learner  using following code:

> tr <- train(lrn, train_data_task)

Error in unique.default(x, nmax = nmax) :
unique() applies only to vectors

Please help me solve this. Thank you very much!

**Comment by larskotthoff** [comment]
Could you provide a complete example please? What are the parameters for `xgboost`, what's the data?

**Comment by berndbischl** [comment]
please reopen with reproducible example
