### ISSUE TITLE
for all learners: make sure that we check the manually used learner against the mlr implementatin with EMPTY param sets

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1251]
so we check default behavior.

for this one has to go through the unit tests for the base learners and check that we have 
list()
in there for the par.vals when we check

**Comment by berndbischl** [comment]
see this bug here #1244

**Comment by jakob-r** [comment]
Can you explain in short (but not too short) what is going on?
Some learners need some arguments to be called, right!? So the `list()` won't work.

**Comment by larskotthoff** [comment]
But mlr has defaults that are taken in this case. So in principle giving no arguments should always work.

**Comment by jakob-r** [comment]
Ah my bad. I thought we want to initialize the original learner always with empty par set.
For the future it might be interesting to do that for mlr learners that do not have specific defaults.

**Comment by larskotthoff** [comment]
This was fixed in #1253.
