### ISSUE TITLE
Add paper to costSensWeightedPairs

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1252]
Might help to understand the stuff,

http://www.jmlr.org/proceedings/papers/v39/lin14.pdf

**Comment by larskotthoff** [comment]
What's the issue? Just add the link to the paper to the R file?

**Comment by berndbischl** [comment]
we need also maybe 1-2 explaining sentences. 
and pls note: sometimes we create these issues when other stuff happens....
(in this case it was during a bachelor defense....)

**Comment by MariaErdmann** [comment]
Solved in #1339. What did you mean with 

> we need also maybe 1-2 explaining sentences. 

?
