### ISSUE TITLE
b632plus estimates of performance measures in classification tasks

### ISSUE THREAD

**Issue by wiesenfa** [mlr-org/mlr#1255]
b632plus estimates of measures depending on predicted probabilities (auc, brier score) in classification tasks seem to not work (while b632 estimates work) in the 2.9 release.
The problem arises when estimating the no-information measure (i.e. gamma) in b632plus().
The noinformation AUC is always 0.5, thus in this case the step 

```
grid = expand.grid(y1, y2, KEEP.OUT.ATTRS = FALSE)
pred2 = mlr:::makePrediction(task.desc = pred$task.desc, row.names = rownames(grid),
                                  id = NULL, truth = grid[, 1L], predict.type = "response", y = grid[, 2L],
                                  time = NA_real_)
gamma = performance(pred2, measures = measure)  

```

in b632plus() could essentially be omitted. The following function seems to work for AUC (although it needs to be tested):

```
b632plusAUC = makeAggregation(
  id = "my_b632plus",
  name = ".632 Bootstrap plus",
  fun = function(task, perf.test, perf.train, measure, group, pred) {
  #        df = as.data.frame(pred)
    a = numeric(length(perf.test))
    for (i in seq_along(a)) {
  #          df2 = df[df$iter == i,, drop = FALSE]
  #          y1 = df2$truth
  #          y2 = df2$response
  #          grid = expand.grid(y1, y2, KEEP.OUT.ATTRS = FALSE)
  #           pred2 = mlr:::makePrediction(task.desc = pred$task.desc, row.names = rownames(grid),
  #                                  id = NULL, truth = grid[, 1L], predict.type = "response", y = grid[, 2L],
  #                                  time = NA_real_)
     #noinformation AUC 
      gamma = 0.5 #performance(pred2, measures = measure)  

    # relative overfit
      R = (perf.test[i] - perf.train[i]) / (gamma - perf.train[i])

    # rule out R=0/0 (==NaN)
      if (perf.test[i] == perf.train[i] & perf.train[i]  ==gamma) R=0 #a[i] will be ==0.5 anyway independent of w
    # force R to be in [0,1]  
      if (R>=1) R=1
      if (R<=0) R=0
    # weight
      w = 0.632 / (1 - 0.368*R)

    # assure that estimate of AUC will not be larger (i.e. better) than apparent AUC even if bootstrap AUC is better than apparent AUC (compaere ModelGood:::MgFormule632)
      if (perf.train[i] <=perf.test[i]) w=0

      a[i] = (1-w) * perf.train[i] + w*perf.test[i]
    }
    return(mean(a))
  }
)
```

This function is only valid for AUC and essentially mimics what package ModelGood does, of course it would be better to have something more general, such that also brier scores etc could be estimated.

One might want to change the last line a[i] = (1-w) \* perf.train[i] + w*perf.test[i] to (though I'm not sure whether I am completely convinced of this):

```
if (perf.test[i]>=gamma) a[i] = (1-w) * perf.train[i] + w*perf.test[i]
if (perf.test[i]<gamma) a[i] = (1-w) * perf.train[i] + w*gamma

```

which assures that a[i] is at least gamma==0.5 (i.e. the no-information AUC), see 

Sahiner, B., Chan, H. P., & Hadjiiski, L. (2008). Classifier performance estimation under the constraint of a finite sample size: Resampling schemes applied to neural network classifiers. Neural Networks, 21(2), 476-483. 

Package ModelGood doesn't do this, but package peperr seems to include this (for all performance measures in general) if I follow the code correctly. 

The line

```
# rule out R=0/0 (==NaN)
   if (perf.test[i] == perf.train[i] & perf.train[i]  ==gamma) R=0 #a[i] will be ==gamma anyway independent of w

```

might also be helpful in the usual b632plus() function, i.e. when esimating mean misclassification errors, for example. Otherwise, if in a bootstrap sample the predictors do not have any explanatory power the aggregated measures will be NaN since in this case R=0/0==NaN and thus w==NaN such that a[i] is NaN. In this case I think it would make sense to have a[i]==gamma which results anyway independent of w if perf.test[i] == perf.train[i]  ==gamma.

Thanks a lot for your work and effort!

**Comment by larskotthoff** [comment]
Thanks for your report. If I understand you correctly, there are two issues -- first, the unnecessary computation (and possible inaccuracy) for AUC, and the issue that sometimes the score will be `NaN` because of a division by 0.

Regarding the first point, an option would be to implement no-information scores for all the measures that can just be retrieved in functions like this. In principle, that's possible, but will be quite a bit of effort (patches welcome!).

Regarding the second point, it looks indeed like a good addition to check for 0/0 here and handle that case appropriately (although the other checks are AUC-specific). Could you open a pull request with that change please? We'll be happy to have a look and merge it.

**Comment by berndbischl** [comment]
i currently dont worry too much, if we are maybe computing something a bit inefficiently. correctness should come first. 

@wiesenfa 
have i overread that or have you posted a reproducible example that demonstrates the problem?

**Comment by wiesenfa** [comment]
Sorry for being imprecise and not giving an example.
The problem I encountered was not computational inefficiency but an error meassage 

> Error in FUN(X[[i]], ...) : 
>   Measure auc requires predict type to be: 'prob'!

 when using b632plus (despite specifying predict.type = "prob" in makeLearner()) .
I adjust the "Quick Start" example in the following to obtain a two class example for demonstration:

```
library(mlr)

#attempt to replace b632plus()
b632plusAUC = makeAggregation(
  id = "my_b632plus",
  name = ".632 Bootstrap plus",
  fun = function(task, perf.test, perf.train, measure, group, pred) {
    #        df = as.data.frame(pred)
    a = numeric(length(perf.test))
    for (i in seq_along(a)) {
      #          df2 = df[df$iter == i,, drop = FALSE]
      #          y1 = df2$truth
      #          y2 = df2$response
      #          grid = expand.grid(y1, y2, KEEP.OUT.ATTRS = FALSE)
      #           pred2 = mlr:::makePrediction(task.desc = pred$task.desc, row.names = rownames(grid),
      #                                  id = NULL, truth = grid[, 1L], predict.type = "response", y = grid[, 2L],
      #                                  time = NA_real_)
      #noinformation AUC 
      gamma = 0.5 #performance(pred2, measures = measure)  
      
      # relative overfit
      R = (perf.test[i] - perf.train[i]) / (gamma - perf.train[i])
      
      # rule out R=0/0 (==NaN)
      if (perf.test[i] == perf.train[i] & perf.train[i]  ==gamma) R=0 #a[i] will be ==0.5 anyway independent of w
      # force R to be in [0,1]
      if (R>=1) R=1
      if (R<=0) R=0
      # weight
      w = 0.632 / (1 - 0.368*R)
      
      # assure that estimate of AUC will not be larger (i.e. better) than apparent AUC even if bootstrap AUC is better than apparent AUC (compaere ModelGood:::MgFormule632)
      if (perf.train[i] <=perf.test[i]) w=0
      
      a[i] = (1-w) * perf.train[i] + w*perf.test[i]
    }
    return(mean(a))
  }
)


data(iris)
# make iris a two class toy example
  iris2=iris
  iris2$Species=as.factor(ifelse(iris$Species=="setosa","setosa","v"))

task = makeClassifTask(id = "tutorial", data = iris2, target ="Species" )
lrn = makeLearner("classif.lda", predict.type = "prob") 


m1=setAggregation(mlr::auc,aggr = b632plus)
m2=setAggregation(mlr::auc,aggr = b632plusAUC)
m3=setAggregation(mlr::auc,aggr = b632)


outer = makeResampleDesc("Bootstrap", iters = 10,predict="both",stratify=T)
set.seed(1)
resamp.inds = makeResampleInstance(outer, task = task)

# gives error: "Measure auc requires predict type to be: 'prob'!"
r = resample(lrn, task, resampling = resamp.inds, show.info = F,models = TRUE,measures=m1)

# using above replacement of b632plus (and for comparison b632), it seems to works (although the results are obviously uninformative with 10 bootstrap samples and AUCs of 1) :
r = resample(lrn, task, resampling = resamp.inds, show.info = F,models = TRUE,measures=list(m2,m3))
r$aggr
```
The problem is that makePrediction() in b632plus() for estimating the noinformation measure specifies predict.type = "response" instead of predict.type = "prob" (see out commented part in b632plusAUC() above). Note that simply changing the predict type in the original code of b632plus() without further adjustments as an easy fix doesn't work. 

I am a new user of mlr with only quite limited experience with it so far, so I'm not really familiar with its architecture and an easier and more general fix might be possible (as well as I might have done something wrong). I'm not familiar with the many functions mlr provides and the structure of mlr so its kind of difficult for me to get to a more general solution.

**Comment by larskotthoff** [comment]
Ah, so there's another bug there? So there's two issues:
- `predict.type` is response and should be prob
- 0/0 returns `NaN` when it's possible to return a more sensible value

Is that everything?

**Comment by wiesenfa** [comment]
Mostly yes, but it is necessary to change the strategy to estimate the noinformation measure, it will not work to just change the predict.type.
The simplest preliminary fix might be to add something like
```
if (measure=="auc") {     
    gamma=0.5
} else { #the original strategy to compute gamma
                 df2 = df[df$iter == i,, drop = FALSE]
                  y1 = df2$truth
                  y2 = df2$response
                  grid = expand.grid(y1, y2, KEEP.OUT.ATTRS = FALSE)
                   pred2 = mlr:::makePrediction(task.desc = pred$task.desc, row.names = rownames(grid),
                                          id = NULL, truth = grid[, 1L], predict.type = "response", y = grid[, 2L],
                                          time = NA_real_)
        gamma = performance(pred2, measures = measure)  
}

```

In addition, package ModelGood and the paper I cited seem to take care that the relative overfit R is forced to be in [0,1]. I'm not sure whether this step would be always useful or only relevant for AUC.


The disadvantage of the above is that anything else depending on predicted probabilities as the brier score would still not work.

**Comment by larskotthoff** [comment]
So the measure would need to specify whether it needs probabilities?

Regarding the restriction to [0,1], the original definition doesn't afford that, so I'm a bit hesitant. It seems to make sense that in some cases e.g. you can have negative overfitting, i.e. "underfitting".

**Comment by wiesenfa** [comment]
yes, differentiating between measures which need probabilities or predicted classes would be a goood strategy.

With respect to your second comment, I agree that it could be a good idea to stick to the original definition although I feel that strange things might happen if R is outside that range (which might occur only theoretically anyway).

**Comment by larskotthoff** [comment]
Ok, so it sounds to me this would be a change to the measures, adding metadata that says whether probabilities are needed and what the no information value is. Then this just needs to be retrieved. Does that sound reasonable?

Do you want to have a go at implementing this yourself? Happy to help with the details!

**Comment by larskotthoff** [comment]
@wiesenfa ping

**Comment by wiesenfa** [comment]
Sorry for the delay Lars. I will have a look at it, but I'm sorry that I probably won't be able to spend time on it before end of November.

**Comment by larskotthoff** [comment]
No rush, I just want to make sure that this isn't abandoned.
