### ISSUE TITLE
Tunable Parameters in C50

### ISSUE THREAD

**Issue by larry77** [mlr-org/mlr#1265]
Dear All, 
Once again, a question more than an issue.
Please have a look at the short example at the end of the post.
Everything seem to be fine, what I do not understand is that if I type

   > getParamSet(lrn)

Then "rules" does not appear to be a tunable parameter (or am I misunderstanding the meaning of the "tunable" label?).
Can anyone please clarify this to me?

############################################################## 
 
    rm(list=ls())

    library(C50)
    library(mlr)
    lrn = makeLearner("classif.C50") 
    ps = makeParamSet(
    makeDiscreteParam("trials", values = seq(10)),
    makeLogicalParam("rules"),
    makeLogicalParam("winnow")
       )

    ctrl = makeTuneControlGrid()
    rdesc = makeResampleDesc("RepCV", folds =3, reps = 3, predict="test")
   
    res = tuneParams(lrn, task = iris.task, resampling = rdesc, par.set = ps,
     control = ctrl)

     lrn = setHyperPars(makeLearner("classif.C50"), par.vals = res$x)
     ## Now I can finally train the learner on the whole train dataset
     mm = train(lrn, task=iris.task)

**Comment by larskotthoff** [comment]
The `rules` parameter does the following, according to the C5.0 help:

> A logical: should the tree be decomposed into a rule-based model?

It doesn't make sense to tune that. I won't affect performance and it depends on what the user is looking for whether they want a tree or a set of rules.
