### ISSUE TITLE
add number of (tunable) hyperpars to listLearners?

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#1273]
This should be possible and I think this will help users to select learners with e.g. low number of hyperpars, what do others think about this?

**Comment by PhilippPro** [comment]
I think this is problematic, because:
- some parameters are "tunable" in mlr, but in fact they usually do not require tuning 
- some algorithms could have many tuning parameters but e.g. could provide very good results in the default mode

So the information could be a missleading/senseless.

**Comment by larskotthoff** [comment]
There's also a difference between a tunable binary and numeric parameter. I agree that just the number is misleading, and you can get the information easy enough.

**Comment by giuseppec** [comment]
I think that showing the number of discrete, numeric, integer, logical, vector and untyped hyperparameters is still a property of a learner that we could at least also show in `listLearners` as an overview. However, I can live without this feature if everybody else is against this.

**Comment by jakob-r** [comment]
Theoretically I like this idea but on the other side this number can be heavily misleading because of the mentioned reasons. A discussion that leads to a well defined number would take up to many *resources* we need for other things.

**Comment by PhilippPro** [comment]
And/or for a specific hyperparameter.

**Comment by larskotthoff** [comment]
Just to clarify: I'm totally ok with having this information in listLearners (maybe as an option), I would just be careful about how we describe/advertise this.

@giuseppec If you want to, please go ahead with this.

**Comment by berndbischl** [comment]
i dont really see this as high prio. i am ok with having this info in there, if it is properly documented what it means. 
at the moment the only info we can provide is of technical nature: how many param (of a type?), how many technically tunable and so on
