### ISSUE TITLE
Add flexible discriminant analysis as classifier

### ISSUE THREAD

**Issue by rwarnung** [mlr-org/mlr#1276]
Flexible discriminant analysis (FDA) is a classification approach that is comparable to MARS (as implemented in the packages earth and mda).

In the mlr package we have a learner for earth  **regr.earth** - but at the moment we don't have the classifier analog. Wouldn't it be great to have is a standard-learner? Later this month I will try to imlement a learner myself.

**Comment by schiffner** [comment]
Hi,

+1. Do I understand correctly that you would be willing to try implementing the interface to FDA yourself?
If yes, please use the manual in the devel version of the tutorial (the release version is outdated):
https://mlr-org.github.io/mlr-tutorial/devel/html/create_learner/index.html

Cheers,
Julia

**Comment by rwarnung** [comment]
Hi @schiffner : correct. I will try to write the learner following the instructions. I really like the classificatio approach as it is halfway between logistic regression and more complicated models.

**Comment by rwarnung** [comment]
@schiffner I try to implement the fda learner. However I face some problems (as I am not used to developping for a package). Is there any sample code that I could look at (besides the lda code in the mlr-tutorial)? Can I see the code for the following learners: classif.gbm or classif.glmnet ? I expect to see code parts that match my problem. Thank you!

**Comment by schiffner** [comment]
Hi, the interfaces to classification learners are all in files named RLearner_classif_<learner_name>.R, for example glmnet can be found here:
https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_glmnet.R
(I will add this info also to the tutorial. Thanks for making me aware that this is missing.)

**Comment by rwarnung** [comment]
@schiffner Thanks for providing the code for glmnet - this is indeed really helpful. I have the release version of mlr installed. It does not find the function getTrainingInfo as well as getFixDataInfo. Do I have to install the devel version to use these functions and see their description? Thank you!

**Comment by schiffner** [comment]
Hi,
sorry, should have mentioned this. You don't need the devel version. The functions you mention are internal helper functions and therefore not exported.
You can find all helper functions here: https://github.com/mlr-org/mlr/blob/master/R/helpers.R

**Comment by rwarnung** [comment]
@schiffner thank you for this useful link! I think the last thing missing are the functions fixDataForLearner and getFixDataInfo ... Out differently: how could I approach this? Just trying to fight my way through using my own appreach or rather follow the path using all these helper functions? In case the learner could enter the group of built-in learners maybe it would be best to have it very similar to the learners that already exist ... right? thank you!

**Comment by rwarnung** [comment]
@schiffner No neeed to comment on the functions anymore.  I found other code as a example that does not use any helper functions. I will play a bit with the learner and later "present" it ;)

**Comment by rwarnung** [comment]
@schiffner  I have written a first version of the learner. I also tried it out (paremter tuning anf so forth) and I think it is ready as a first develop version. How can I submit it (sorry that I ask such basic questions)?

**Comment by schiffner** [comment]
@rwarnung: No need to apologize. These questions are very useful to improve our documentation.

> How can I submit it?

Normally by sending us a pull request.
Have you found the coding guidelines in the Wiki (https://github.com/mlr-org/mlr/wiki/mlr-Coding-Guidelines)? They contain some information on how this works.

How did you try out your learner? Are you familiar with unit testing and package testthat? Or are you willing to give it a try?

We would need a unit test for the new learner.
I have started to write down more info about testing here (I should have done this a long time ago, sorry):
https://github.com/mlr-org/mlr-tutorial/pull/68/commits/cb7b53ca3f0619f30fae3d4c7a267fabad1e58b7

**Comment by rwarnung** [comment]
@schiffner I tested it on the sonar task and compared it to the direct call of earth. I will follow the guidlines and do the tests that you propose.

**Comment by rwarnung** [comment]
@schiffner I am still struggeling with the unit testing. I am reading what you have posted. I will try to adapt the lda tests. Is it correct that I only have to adapt one file (https://github.com/mlr-org/mlr/blob/master/tests/testthat/test_classif_lda.R)? I can not attacht the learner here to show you and ask whether this is useful at all? Thank you!

**Comment by schiffner** [comment]
@rwarnung : If you could point me to the correct branch in your fork of mlr I could certainly have a look. Or more conveniently, you could open a pull request, which would make it easier to give feedback.

**Comment by rwarnung** [comment]
@schiffner thanks for your help. I am new to all this but I try to catch up. First I have forked mlr and then I have uploaded my learner. You should find it here: 
https://github.com/rwarnung/mlr/tree/master/R/RLearner_classif.earth.R 

I think I did too much documentation (copied from the original documentation). I started looking at tests but I need to get familiar with the helper functions there I guess. What would be the next step? Thank you!

**Comment by schiffner** [comment]
Thanks very much for the PR!

Regarding the tests:
Writing the test file is mostly copy-paste. I usually look at tests for learners with similar properties and adapt them.
In your case there is already the regression analogue regr.earth and your learner has properties "twoclass" and "prob". Therefore:
* You could take the first part (`requirePackagesOrSkip` and the `parset.list`) from the tests for the regr.earth learner (https://github.com/mlr-org/mlr/blob/master/tests/testthat/test_regr_earth.R).
* Another learner with properties "twoclass" and "prob" is classif.ada.
You can pretty much copy the second half of `test_that("classif_ada",` starting with line 11
https://github.com/mlr-org/mlr/blob/master/tests/testthat/test_classif_ada.R#L11

We have many different helper functions and objects, but luckily for your test you just need `testSimpleParsets` (which checks if the predicted class labels are correct) and `testProbParsets` (which checks if the predicted probabilities are correct) and some data like `binaryclass.task` etc. for binary classification problems.

I hope that helps!
