### ISSUE TITLE
Faster filter functions

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#1279]
I just discovered the `Rfast` package and saw that it has some very fast implementions of various univariate tests. I was thinking that we could use them for making faster filter functions. It seems that we could improve the speed of the correlation as well as ANOVA filters at least ten fold. See the following benchmarks:

```
dat <- data.frame(matrix(rnorm(50000), ncol = 500))
regr.task <- makeRegrTask(dat = dat, target = 'X1')
class.task <- makeClassifTask(dat = data.frame(y = factor(rbinom(nrow(dat), 1, 0.5)), dat), target = 'y')

rank1 = function(task) {
    y = FSelector::rank.correlation(getTaskFormula(task), data = getTaskData(task))
    setNames(y[["attr_importance"]], getTaskFeatureNames(task))
}

rank2 = function(task) {
    d = getTaskData(task, target.extra = TRUE)
    setNames(abs(Rfast::correls(d$target, d$data, type = 'spearman')[,1]), getTaskFeatureNames(task))
}

lincor1 = function(task) {
    y = FSelector::linear.correlation(getTaskFormula(task), data = getTaskData(task))
    setNames(y[["attr_importance"]], getTaskFeatureNames(task))
}

lincor2 = function(task) {
    d = getTaskData(task, target.extra = TRUE)
    setNames(abs(Rfast::correls(d$target, d$data, type = 'pearson')[,1]), getTaskFeatureNames(task))
}

anov1 = function(task) {
    data = getTaskData(task)
    sapply(getTaskFeatureNames(task), function(feat.name) {
      f = as.formula(stringi::stri_paste(feat.name,"~",getTaskTargetNames(task)))
      aov.t = aov(f, data = data)
      summary(aov.t)[[1]][1,'F value']
    })
}
anov2 = function(task) {
    d = getTaskData(task, target.extra = TRUE)
    setNames(Rfast::ftests(as.matrix(d$data), as.numeric(d$target))[,1], getTaskFeatureNames(task))
}


rbenchmark::benchmark(rank1(regr.task), rank2(regr.task), replications = 10)
all.equal(rank1(regr.task), rank2(regr.task))
rbenchmark::benchmark(lincor1(regr.task), lincor2(regr.task), replications = 10)
all.equal(lincor1(regr.task), lincor2(regr.task))
rbenchmark::benchmark(anov1(class.task), anov2(class.task), replications = 10)
all.equal(anov1(class.task), anov2(class.task))
cor(anov1(class.task), anov2(class.task))
```
The anova results are not exactly equal,probably because the Rfast implentation of the F-test assumes unequal variances.

**Comment by larskotthoff** [comment]
Sounds good. Could you make a pull request please?

**Comment by studerus** [comment]
I guess I could simply replace the pearson and spearman correlation filters with the Rfast versions since the results should be exactly the same but how about the ANOVA? Should I include a separate filter, since the original ANOVA filter seems to assume equal variance whereas the Rfast version does not.

**Comment by larskotthoff** [comment]
It sounds like the Rfast version is more general, so I would just replace it. As a sanity check I would see if you get the same result for some test cases though.

**Comment by statlink** [comment]
Good morning, indeed the F-tests in the Rfast package assume unequal variances. In some future update we will include the equal variances case (ANOVA) as well. Note that we have made a mistake in the rowMins/rowMaxs functions, but this is going to be fixed in November. The rest of the functions have been thoroughly checked for speed and accuracy. 

Stay tuned, more is coming.

**Comment by larskotthoff** [comment]
Thanks for the heads-up @statlink!
