### ISSUE TITLE
Cost-sensitive classification with mlr

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#129]
It was asked how cost sensitive classification can be performed with mlr. 

Assumptions: We have matrix C, where C_ij is the cost when we predict class j for class example of class i.

Goal: Produce a learner that minimizes these costs in expectation.

Question: What can be don in mlr already to achieve this?

@SchroederFabian

Correct?

**Comment by rniehkust** [comment]
Dear Sir,

I have a question. I need to use metacost to do some calculation. Dose your project use metacost to do Cost sensitive analysis(minimize the expected cost)?

If so, how can I do it?

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
