### ISSUE TITLE
mlr: new gbm release

### ISSUE THREAD

**Issue by pdmetcalfe** [mlr-org/mlr#1290]
We're coming up to a new release of gbm which considerably tidies the code and introduces a much stricter NAMESPACE.  As part of this we have unfortunately had to change the API, and it looks like it's going to break your package.

The new gbm is at

https://github.com/gbm-developers/gbm

Would it be possible for you to take a look?

[00check.log.txt](https://github.com/mlr-org/mlr/files/529036/00check.log.txt)

**Comment by schiffner** [comment]
Thanks vey much for notifying us. We will take a look.

**Comment by mllg** [comment]
The changes are mostly ready for merge, but not compatible with gbm < 2.2.0. Whoever uploads first breaks the other package.

@pdmetcalfe Do you have an ETA for your update?

**Comment by schiffner** [comment]
> The changes are mostly ready for merge ...

Sorry, not done yet. Function `gbm::gbm` will be deprecated and I still need to change a few things so that we can use the new `gbm::gbmt`.

@pdmetcalfe I read that you are maybe planning an extra package for the multinomial distribution / multi-class case. Do you have any further information on this?

**Comment by pdmetcalfe** [comment]
gbm::gbm will be around for a while yet!

Planning on "next few weeks" for release; there's a few other packages need
updating.

I'm hoping that multinomial can be reproduced as a sequence of Bernoulli
problems, but that won't be instant.

I think the way it works is we upload to CRAN, telling them that the other
package is coming soon.

Cheers,

pdm

**Comment by berndbischl** [comment]
@schiffner @pdmetcalfe 
what is the status here?
