### ISSUE TITLE
debugging a model/task that fails in parallel

### ISSUE THREAD

**Issue by HarlanH** [mlr-org/mlr#1294]
Hi -- I've got a survival model that I'm trying to get to run (benchmark) in parallel. I'm having trouble, and can't figure out how to track it down.

The behavior I'm seeing is this:

```
Mapping in parallel: mode = multicore; cpus = 2; elements = 2.
Error in split.default(results, unlist(grid$task)) : first argument must be a vector
3. split.default(results, unlist(grid$task))
2. split(results, unlist(grid$task))
1. benchmark(e2_lrns, task, qq, measures = cindex, keep.pred = FALSE, show.info = TRUE)
```

Debugging shows that `results` is NULL, so something in the parallel processes is failing without an error.

If I switch out my task for `lung.task`, keeping everything else idendical, it works. If I disable parallel mode, it works. Despite the fact that `logging=TRUE`, there's nothing in the log files on disk. I'm using typical bundled learners and measures for survival models. 

How would you advise I attempt to track down the issue?

I cannot share my data, but here's the summary of the task, with a couple of things obscured:

```
Supervised task: ttt
Type: surv
Target: aaa,bbb
Observations: 3204
Features:
numerics  factors  ordered 
      51        4        0 
Missings: FALSE
Has weights: FALSE
Has blocking: FALSE
```

And a bit about my machine:

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)
mlr_2.9 parallel_3.3.0 parallelMap_1.3 ...
```

**Comment by larskotthoff** [comment]
`parallelStart()` (which you can use to explicitly start the parallelization) has a couple of options to get more information on what's going on, in particular with respect to logging (see `?parallelStart`).

**Comment by HarlanH** [comment]
Yes -- I had previously found those options, but the output to those files
is entirely blank. Do you have any idea what aspect of a Task might cause a
failure like this?

**Comment by larskotthoff** [comment]
Hmm, not really. @berndbischl

**Comment by HarlanH** [comment]
I'm still pretty much stalled here. For reference, I can do something like this:

```
lrns <- list(makeLearner("surv.coxph"), 
             makeLearner("surv.coxphInts"))
bmr = benchmark(lrns[[1]], 
                   tmptask, rdesc, 
                measures=myMeasures,
                keep.pred=FALSE, show.info=TRUE)
```

and the same thing with `lrns[[2]]`, but if I say `lrns`, it fails with this:

```
Mapping in parallel: mode = multicore; cpus = 2; elements = 2.
 Show Traceback
Error in split.default(results, unlist(grid$task)) : first argument must be a vector
```

and nothing in the log files. 

I could really use a way to get this to work. I've ruled out custom measures as being the issue, and it does seem to have something to do with the task -- if I swap in `lung.task`, it works -- but there's no missing data or anything, so I'm unsure what's going on...

cc @berndbischl

**Comment by HarlanH** [comment]
If I switch to `level="mlr.resample"`, I get this error instead:

```
Mapping in parallel: mode = multicore; cpus = 2; elements = 15.
 Show Traceback
Error in mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule, : attempt to select more than one element in integerOneIndex
```

**Comment by HarlanH** [comment]
Can I buy someone a beer or a book or something to get help on this? cc @berndbischl

**Comment by larskotthoff** [comment]
Could you post a complete minimal example that allows to reproduce the problem please?

**Comment by HarlanH** [comment]
My data and aspects of the task are proprietary, so I'm struggling to do
so, but will certainly share one if I can construct one. I've tried to step
through the code before and after the parallelMap, and that hasn't shed any
light. If someone's available for a quick screenshare, perhaps that could
help?

**Comment by larskotthoff** [comment]
My feeling is that a screenshare won't be sufficient. Parallelization is notoriously difficult to debug. Could you construct a small example that isn't proprietary?

**Comment by HarlanH** [comment]
I haven't been able to construct a reproducible example yet, but I can confirm that the code works as expected on this AMI: http://www.louisaslett.com/RStudio_AMI/ So, it may be OS X specific, or something else specific to my Mac setup.

**Comment by larskotthoff** [comment]
Have you tried the latest version of R on your mac?
