### ISSUE TITLE
How to do Time Series Cross Validation in mlr?

### ISSUE THREAD

**Issue by jeonghyunwoo** [mlr-org/mlr#1302]
I'm trying machine learning task with time based target.
for example, predictors are 6 months lagged values and 
target is current value.
'caret' package provides 'createTimeSlice' function or 'timeslice' method in trainControl 
for this problem.
I want to use 'classif.h2o.deeplearning' in mlr with method like 'timeslice' in 'caret'
How can I treat this problem? 
Thanks in advance for your helps.

Below is manual for time series cross validation using caret.
rpubs.com/crossxwill/time-series-cv

**Comment by PhilippPro** [comment]
@Stevo15025 is currently working on it for his master thesis, I think.

**Comment by Stevo15025** [comment]
@jeonghyunwoo yes if you pull my fork you should be able to use `GrowingCV` and `FixedCV` cross validation.

https://github.com/Stevo15025/mlr

Please note that my current version does not pass `R CMD CHECK`, but will hopefully be fixed by Wednesday.

**Comment by jeonghyunwoo** [comment]
I wish the work early finished successfully.
Thank you.

2016. 10. 24. 오후 8:28에 "Philipp Probst" <notifications@github.com>님이 작성:

**Comment by MasonGallo** [comment]
Any updates on this?

**Comment by Stevo15025** [comment]
So far it is in a branch [here](https://github.com/mlr-org/mlr/tree/forecasting) and I am waiting for a code review. See `GrowingCV` and `FixedCV` in the resampling portion of the tutorial below. We are having some problems with `MAX_NUM_DLLs` that I am fixing now, but that doesn't effect the forecasting extension besides being unable to pass the tests on all classification learners in jenkins and travis.

See tutorial [here](https://rawgit.com/Stevo15025/mlrForcastingTutorial/gh-pages/forcasting_in_mlr.html)

**Comment by MasonGallo** [comment]
cool ty I'll check it out
