### ISSUE TITLE
predict fails when using a data.table instead of a data.frame

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1306]
This should work imo

```
library(mlr)
library(data.table)
irisdt = data.table(iris)
mod = train("classif.qda", iris.task)
predict(mod, newdata = irisdt)

> Error in predict(mod, newdata = irisdt) : 
  Assertion on '.newdata' failed: Must be of type 'data.frame', not 'integer'.
```

**Comment by larskotthoff** [comment]
Is this only a problem with the check? Could you have a look if it works when you change it accordingly please?

**Comment by ja-thomas** [comment]
I'm not sure I understand what you mean?

**Comment by larskotthoff** [comment]
The example fails because of the check. If you remove the check, does it work or does something further down the line break? I.e. do we even need coercion to data frame for data tables?

**Comment by ja-thomas** [comment]
ah, yes we need, since the data.table is converted to an integer because column selection by number as we do here does not work for data.tables:

`truth = newdata[, t.col, drop = TRUE]`

**Comment by larskotthoff** [comment]
Ok, fair enough. I'll merge your PR then to close this, but we should probably revisit this later.
