### ISSUE TITLE
Add models from tuning to opt.path

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1313]
There [seems to be some demand](http://stackoverflow.com/questions/40250815/r-mlr-package-is-it-possible-to-save-all-models-from-parameter-tuning/40265902) to store models during tuning.
Thanks to the dotted extras we could easily store them in the opt.path.

**Comment by berndbischl** [comment]
yes, i can see the need (sometimes)
happy to accept a PR here which adds that option
