### ISSUE TITLE
What's the status of survival and probability prediction?

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#1321]
I just wanted to ask if this is likely to be (re)enabled at some time?

At the moment it is documented here and there that prob is a valid predict.type for survival (e.g. in the docs of makeLearner, LearnerProperties and in some places in the tutorial). If the answer is no I would tend to remove this to not confuse people.

See also #966

**Comment by mllg** [comment]
I was looking into supporting [pec](https://cran.r-project.org/package=pec) to calculate brier scores from prediction probabilities. Unfortunately, the interface is rather subpar for mlr and only few learners are supported. 
Some help from someone actively working with survival models would be appreciated.
