### ISSUE TITLE
Travis is broken ... again

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#1326]
`devtools` does not update survival (probably because it is installed in the system lib), but `Hmisc` needs a recent version. We already had this issue once (with lme IIRC), but I can't recall how to solve this at the moment.

Any suggestions @larskotthoff @berndbischl ?

**Comment by berndbischl** [comment]
1) what do we need hmisc for? disable that test?

2) cant we simply overinstall the version by writing script code in the travis yml?

**Comment by mllg** [comment]
1) We cannot install. All Suggests must be installable for Travis.
2) Yes, we need something like this.

**Comment by berndbischl** [comment]
https://github.com/mlr-org/mlr/pull/1328
