### ISSUE TITLE
Broken tests generateThreshVsPerf

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#1327]
Tests are broken on winbuilder and locally on OSX. Cannot fix it, I don't understand the tests.

```
1. Failure: generateThreshVsPerfData (@test_base_generateThreshVsPerf.R#43) ----
length(XML::getNodeSet(doc, black.line.xpath, ns.svg)) not equal to length(unique(pvs$data$iter)).
1/1 mismatches
[1] 0 - 2 == -2
```

Additional warning:
```{r}
the XPath query has no namespace, but the target document has a default namespace.
This is often an error and may explain why you obtained no results
```

**Comment by berndbischl** [comment]
confirmed also on my (ubuntu) laptop
we need to fix this now, this means master tests are broken
@larskotthoff @zmjones

**Comment by berndbischl** [comment]
how is it possible that travis runs then?

**Comment by mllg** [comment]
Tests are failing. Probably a third party package (ggplot2, XML, ...?) has introduced this one. The last successful test was several days ago.
