### ISSUE TITLE
refactor resample / tuning message and number output a bit

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1332]
Current example

[Resample] cross-validation iter 1: mmce.test.mean=0.04,ber.test.mean=0.0366
[Resample] cross-validation iter 2: mmce.test.mean=0.0533,ber.test.mean=0.0586
[Resample] Aggr. Result: mmce.test.mean=0.0467,ber.test.mean=0.0476

some (minor) issues

1) numbers could be better aligned, for readability

2) measure names could be shorter

3) the internal code could be better
we have these functions
perfsToString
measureAggrPrettyName 
measureAggrName       

perfsToString should probably be more configurable and get the measures objects, so it formats the name itself

**Comment by ja-thomas** [comment]
1. number alignment:

zeros or spaces. We would suggest zeros

2. measure names:

drop `.mean`, and `.test` when it's the default, e.g. if it is not changed by the user. Not sure if thats a smart idea, other suggestions?

**Comment by jakob-r** [comment]
The best would be some table style to prevent reoccurring information in every line. Would take some effort  to get it beautiful probably.

**Comment by berndbischl** [comment]
> number alignment:
> zeros or spaces. We would suggest zeros

ok

> measure names:
> drop .mean, and .test when it's the default, e.g. if it is not changed by the user. Not sure if thats a smart idea, other suggestions?

just always drop the aggregation (test.mean) i would suggest. this is just a simple log.


> The best would be some table style to prevent reoccurring information in every line.

also good idea. just log the x / measure names once in a starting line
(or is that less readable?)

**Comment by florianfendt** [comment]
@berndbischl 
> The best would be some table style to prevent reoccurring information in every line.

> also good idea. just log the x / measure names once in a starting line
> (or is that less readable?)

I'll play around a bit with that this week and we can have a look together Monday
