### ISSUE TITLE
Add tag "weights" to classif.randomForestSRCSyn again

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#1333]
Currently weights are not supported due to a bug in randomForestSRC. Bug reported via mail and property removed. The test which triggered the bug (in `test_learners_classif_all`) will be active again as soon as we add the property again.

**Comment by berndbischl** [comment]
relevant for classif and regr learner

**Comment by berndbischl** [comment]
both learners are in todofiles now and removed from the package
the new release broke travis in various ways
