### ISSUE TITLE
Problem in partial dependence plot for regression task

### ISSUE THREAD

**Issue by roolio** [mlr-org/mlr#1341]
Hello, while playing with the (great) generatePartialDependenceData/plotPartialDependence couple of functions, on a regression task, I think I found a problem : 

I'm using one of the example of your [blog post](https://mlr-org.github.io/exploring-learner-predictions-with-partial-dependence/) : 

```{R}
library(mlr)
lrn.regr = makeLearner("regr.ksvm")
fit.regr = train(lrn.regr, bh.task)
pd.ci = generatePartialDependenceData(fit.regr, bh.task, "lstat",
  fun = function(x) quantile(x, c(.25, .5, .75)))
pd.ci
```

Results are  : 

> PartialDependenceData
Task: BostonHousing-example
Features: lstat
Target: medv
Derivative: FALSE
Interaction: FALSE
Individual: FALSE
        medv     lstat      lower      upper
1 0.04926083  1.730000 0.04217945 0.05842859
2 0.04696305  5.756667 0.04105306 0.05410397
3 0.04421699  9.783333 0.03924252 0.04942763
4 0.04091042 13.810000 0.03697014 0.04671165
5 0.03867111 17.836667 0.03270961 0.04551396
6 0.03745035 21.863333 0.02924507 0.04406066

Where it seems that medv values should be higher (as indicated in your blog post).
Median of medv is at 21.4 : 

```{R}
median(bh.task$env$data$medv)
````

> [1] 21.2

It seems that values are already divided by the number of raws : 

```{R}
pd.ci = generatePartialDependenceData(fit.regr, bh.task, "lstat",
  fun = sum)
```

give more realistic results.

I'm using mlr 2.10

Kind regards

Julien

**Comment by larskotthoff** [comment]
I've tried with the latest github version and I'm getting results that look ok:

```
> pd.ci
PartialDependenceData
Task: BostonHousing-example
Features: lstat
Target: medv
Derivative: FALSE
Interaction: FALSE
Individual: FALSE
      medv     lstat    lower    upper
1 24.80835  1.730000 21.38244 29.56052
2 23.73625  5.756667 20.81227 27.57550
3 22.34014  9.783333 19.97346 25.12216
4 20.69059 13.810000 18.71324 23.61991
5 19.58093 17.836667 16.52309 22.89049
6 19.08066 21.863333 15.01318 22.12068
... (10 rows, 4 cols)
```

Could you please try with the latest development version and see if you're still getting the bug?

**Comment by roolio** [comment]
Hello, 
Sorry, I was indeed using an old version of 2.10 : I've installed the latest and results are good. 

Thanks a lot for your feedback
