### ISSUE TITLE
xgboost multiclass weighted classification problem

### ISSUE THREAD

**Issue by jukiewiczm** [mlr-org/mlr#1342]
Hello,
There is a tiny code error which makes weighed multiclass classification fail with xgboost.
I would do the change myself, but the mlr's pull request guide seemed a little too overwhelming to get familliar with to make such a small change :).

https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_xgboost.R#L79
Here, the `data = data` has to be replaced with `data = xgb.dmat`.

Thanks!

**Comment by larskotthoff** [comment]
Thanks for the report. I've opened a PR to fix this.
