### ISSUE TITLE
Include quickcheck again

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1350]
We temporary disabled quickcheck since we otherwise will always get a NOTE on CRAN.

As soon as quickcheck is on CRAN we can include quickcheck again.

See PR #1349

**Comment by berndbischl** [comment]
the problem is basically this.
quickcheck is only available on github. this will result in NOTES and problems on winbuilder.


```
Suggests or Enhances not in mainstream repositories:
  quickcheck

URL: https://cran.r-project.org/package=quickcheck
    From: inst/doc/mlr.html
    Status: 404
    Message: Not Found
```

I have tried to fix this with "Remotes"  in DESCRIPTION but this seems not to be recognized

**Comment by berndbischl** [comment]
@mllg @larskotthoff 
do you know how to handle this?

**Comment by berndbischl** [comment]
michel says: we could remove it from suggests and do a skip_if_notinstalled

**Comment by larskotthoff** [comment]
That sounds good to me. Any disadvantages if we do this?

**Comment by berndbischl** [comment]
> That sounds good to me. Any disadvantages if we do this?

not sure if it works completely, we need to check this on winbuilder. if it does we can simply do it

**Comment by larskotthoff** [comment]
Ok, let's have a look at this after the release.
