### ISSUE TITLE
remove checkLearnerClassif soon

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1351]
Giuseppe used this in RBPCurve, I added a deprecated version. Needs to be removed soon when Giuseppe has pushed a new version to CRAN

**Comment by ja-thomas** [comment]
@giuseppec please say when your package is on CRAN

**Comment by giuseppec** [comment]
On CRAN now.

**Comment by giuseppec** [comment]
@berndbischl I think the function can be removed now, at least from my side.
