### ISSUE TITLE
(Tests for) classif.gamboost fail on Windows machine

### ISSUE THREAD

**Issue by MariaErdmann** [mlr-org/mlr#1365]
`test_learners_all_classif` and `test_classif_gamboost` fail on my windows machine with following error message:
 `Error in chol.default(A) : LAPACK routines cannot be loaded`
Does anybody else with a windows machine experience this problem?
You can also simply reproduce the error with the following code snippet?
````
lrn = makeLearner("classif.gamboost")
mod = train(lrn, binaryclass.task)
````

**Comment by larskotthoff** [comment]
Works for me -- you need to install the lapack libraries. See http://icl.cs.utk.edu/lapack-for-windows/

**Comment by MariaErdmann** [comment]
Hi, thanks for checking. I have the lapack libraries installed. My lapack problem did only occur in RStudio, not when using R from the command line. Therfore, I installed the new stable R Studio version, updated all my packages and now it seems to work.
