### ISSUE TITLE
Question on the 'requires' argument in paramSet

### ISSUE THREAD

**Issue by MariaErdmann** [mlr-org/mlr#1369]
Training i.e. a `regr.svm` with parameter `degree = 4L`, actually requires a polynomial kernel, but I can easily train a `regr.svm` with `degree = 4L` and `kernel = "radial"`. I am not sure, but previous, I think, an error was thrown, when I tried this. Was there a change I missed? 

````
lrn = makeLearner("regr.svm")
# regr.svm' parameter degree requires the kernel to be "polynomial"
extractSubList(getParamSet(lrn)$pars, "requires")$degree
# but it is no problem to do that:
lrn2 = makeLearner("regr.svm", par.vals = list(kernel = "radial", degree = 4L))
# I think previously an error was thrown at this point
lrn2
mod = train(lrn2, regr.task)
pred = predict(mod, regr.task)
````

**Comment by jakob-r** [comment]
This is a known issue and it is already dealt with in #240, #1032 and probably many more. Until now the requirements are still not properly checked.

Close, because duplicate.

**Comment by MariaErdmann** [comment]
Oh, ok, sorry! Thanks, for clarification.
