### ISSUE TITLE
Learner bug list: Test learners with defaults against no params

### ISSUE THREAD

**Issue by MariaErdmann** [mlr-org/mlr#1370]
Wrt to #1034 and #711 I implemented the following test and looked at all the errors. Since the test throws quite a lot of errors I will use this issue to make a list with all the errors that I get and which need to be fixed in order to get the test run through. We thought it would be better to fix the problems in seperate PRs.  What do you think?

The test is not finished yet since I do not know yet how to handle default parameters that have a require statement. But I considered this case when starting debugging the first errors.

````
testThatLearnerHasCorrectDefaults = function(lrn, task) {
  
  rin = makeResampleInstance("Holdout", task = task)
  set.seed(1); m1 = train(lrn, task, subset = rin$train.inds[[1]])
  lrn2 = setHyperPars2(lrn, getDefaults(lrn$par.set))
  set.seed(1); m2 = train(lrn2, task, subset = rin$train.inds[[1]])
  
  p1 = predict(m1, task, subset = rin$test.inds[[1]])
  p2 = predict(m2, task, subset = rin$test.inds[[1]])
  expect_equal(performance(p1), performance(p2))
}
````

**Comment by MariaErdmann** [comment]
Classification learners
- [ ] classif.avNNet: 

````
lrn = makeLearner("classif.avNNet", par.vals = list(repeats = 5))
mod = train(lrn, binaryclass.task)
lrn = makeLearner("classif.avNNet", par.vals = list(bag = FALSE))
mod = train(lrn, binaryclass.task)

# Problem is this part in the learner's file line 36 - 40
# ind = stri_detect_regex(nms, "repeats") --> produces a vector with one TRUE and rest is FALSE
# if (sum(ind)>0) --> is TRUE
# repeats = .learner$par.vals[[ind]] --> one [] is sufficient
# ind = stri_detect_regex(nms, "bag")
# if (sum(ind)>0)
#  bag = .learner$par.vals[[ind]]
```` 

- [ ] classif.glm

````
lrn = makeLearner("classif.binomial")
lrn2 = setHyperPars2(lrn, getDefaults(lrn$par.set))
mod2 = train(lrn2, binaryclass.task)

# Problem is here: we need to add model into the signature of the train function
````

- [ ] classif.blackboost

````
lrn = makeLearner("classif.blackboost")
mod = train(lrn, binaryclass.task)
lrn2 = setHyperPars2(lrn, getDefaults(lrn$par.set))
mod2 = train(lrn2, task)

# There are 2 problems here 
# 1) the dots passed to 
# tc =  learnerArgsToControl(party::ctree_control, teststat, testtype, mincriterion, maxdepth, 
# savesplitstats, ...) in line 51 of the learner
# 2) are some parameters in the learner that cannot be passed to blackboost, including minsplit,
# minbucket, stump, nresample, maxusrrogate, mtry
````

- [ ] classif.bst

````
lrn = makeLearner("classif.bst")
lrn2 = setHyperPars2(lrn, getDefaults(lrn$par.set))
mod = train(lrn2, binaryclass.task)

# maxcompete is missing in train function's singature and in the control.tree list
# Moreover, I am not sure if all these rpart tree control parameters are passed
# The bst code does not indicate to do so
````

.... to be continued

**Comment by larskotthoff** [comment]
Sounds good, thanks for doing this!

**Comment by MariaErdmann** [comment]
Finished the list!
Now, I and whoever feels like it can fix a learner in a PR. I tried to check all params whenever I encountered a bug,but please, check all the parameters once more. Four eyes see more than two :-) And please, just set a check mark when you fix a learner, such that only one person works on a learner.
According to our monday meetup the following should be applied for parameters which have a default that is `NULL` in the algorithms help page and whenever we don't have a default for that parameter or we have another default than `NULL` for feasability in the past: Then set the param to `NULL` and use `special.vals = list( NULL)`.

**Comment by Coorsaa** [comment]
I'm working now on the (cv)glmnet learners
