### ISSUE TITLE
makeNumericLearnerParam default=Inf

### ISSUE THREAD

**Issue by HeidiSeibold** [mlr-org/mlr#1373]
I am trying to integrate a function in mlr. The problem I am facing right now is that I am not allowed to have `default = Inf`, i.e.

`makeIntegerLearnerParam(id = "mtry", default = Inf, lower = 1)`

I get

```
> classif.lrn = makeLearner("classif.newctree", predict.type = "prob", fix.factors.prediction = TRUE)
 Error in makeParam(id = id, type = "integer", len = 1L, lower = lower,  : 
  mtry : 'default' must be a feasible parameter setting. 
```

The help page says about mtry:
number of input variables randomly sampled as candidates at each node for random forest like algorithms. The default mtry = Inf means that no random selection takes place.

**Comment by larskotthoff** [comment]
The problem is that ParamHelpers doesn't support infinity as a value.

@berndbischl  @mllg @ja-thomas  Issue in PH?

**Comment by berndbischl** [comment]
we have introduced "special.val" exactly for this purpose in PH?

**Comment by HeidiSeibold** [comment]
Can you explain, what this means?

Maybe a side note: I saw that for `makeNumericLearnerParam` you have an option `allow.inf = TRUE`. Why not for `makeIntegerLearnerParam`?

**Comment by HeidiSeibold** [comment]
There is a related problem with NULL
```
makeFunctionParam("applyfun", default = NULL)
```

**Comment by larskotthoff** [comment]
@HeidiSeibold You can see examples of how this is used in RLearner_classif_xgboost.R. You declare all the special values separately.

**Comment by HeidiSeibold** [comment]
Thanks, works now!
