### ISSUE TITLE
digits in resample result message should be configurable

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#1380]
We use `messagef("[Resample] Result: %s", perfsToString(aggr))` to print the resample results.
However, we force the number of digits to 3:

```r
perfsToString = function (y) {
    stri_paste(stri_paste(names(y), "=", formatC(y, digits = 3L), 
        sep = ""), collapse = ",", sep = " ")
}
```

This is sometimes annoying because, e.g. the value `1135.55` will be shown as `1.14e+03`. can we use something like `formatC(y, digits = options()$digits)` which can be set by the user instead of fixing the value to 3? Or add a new option to `configureMlr`.

**Comment by ja-thomas** [comment]
Connected to #1332

**Comment by ja-thomas** [comment]
@berndbischl @mllg @larskotthoff 

What option would you prefer? We are not sure

- use `options()$digits`

- use a new variable in `configureMlr`

Maybe the second option is better, as one want to have different behavior for these printers.

**Comment by berndbischl** [comment]
we seem to have that problem in a few places

```
R/calculateROCMeasures.R
87:#' @param digits [\code{integer(1)}]\cr
88:#'   Number of digits the measures are rounded to.
92:print.ROCMeasures = function(x, abbreviations = TRUE, digits = 2, ...) {

R/calculateConfusionMatrix.R
109:#' @param digits [\code{integer(1)}]\cr
113:print.ConfusionMatrix = function(x, both = TRUE, digits = 2, ...) {

R/helpers.R
22:  stri_paste(stri_paste(names(y), "=", formatC(y, digits = 3L), sep = ""),
bischl@bischl-x1:~/cos/mlr (master) $ 

```

how about this:
- always use formatC
- each function where you really want to influence this (here print.ObjectClass) have an arg,
  that arg is the "format" string
- the default of that arg is taken from a new mlr option from configureMlr

?
