### ISSUE TITLE
error message in regr.glm

### ISSUE THREAD

**Issue by andreashandel** [mlr-org/mlr#1381]
I'm trying to fit some data with glm through mlr assuming gamma distribution (btw, thanks for implementing glm support a while back)!

Here is a SEMI-reproducible example:

```
library(mlr) 
myseed=111
set.seed(myseed) 
mydata=data.frame(outcome = rexp(10), pred1 = rexp(10), pred2=as.factor(rbinom(10,1,prob=0.5)), pred3 = rexp(20) )
mytask = makeRegrTask(id='analysis', data = mydata, target = 'outcome')
learner_name = "regr.glm"
mylearner = makeLearner(learner_name, family = 'Gamma')
sampling_choice = makeResampleDesc("RepCV", reps = 10, folds = 10)
fullmodel = resample(mylearner, task = mytask, resampling = sampling_choice, show.info = FALSE )
```

Error I get is:

Error: no valid set of coefficients has been found: please supply starting values
In addition: Warning message:
In log(ifelse(y == 0, 1, y/mu)) : NaNs produced

I'm saying my example is SEMI-reproducible because if I set the random seed to something else, it sometimes works. (Unfortunately for my real dataset, no choice of random seed works).

Is this a bug with mlr, or does this error message tell me I'm doing something I shouldn't be doing? Could someone help me figure out what this error message means and who I could go about getting this to work (no problem if I do family = 'gaussian' in glm).

Thanks!

**Comment by larskotthoff** [comment]
This is a bug in `glm`, I'm getting the same error with

```
glm(outcome~., mydata, family = 'Gamma')
```

I would open an issue upstream.
