### ISSUE TITLE
Get the standard deviation of the inner folds in nested CV

### ISSUE THREAD

**Issue by danielhomola** [mlr-org/mlr#1384]
Dear mlr people,

first of all massive thanks to you all for your amazing package! 

I'm trying to get a feeling of the variance across the inner folds in nested CV, and the 
https://www.rdocumentation.org/packages/mlr/versions/2.9/topics/getNestedTuneResultsOptPathDf?

only returns the mean. I tried looking at
https://github.com/mlr-org/mlr/blob/master/R/getNestedTuneResults.R#L44
but I couldn't work out how can I actually get the results of each inner fold and calculate the std across the inner folds.

This would be a really useful metric I think. Is there a way to get this info somehow and I'm missing something, or is this a new feature that I'd need to implement?

Many thanks,
d

**Comment by larskotthoff** [comment]
You can set a measure with a different aggregation with `setAggregation`. See `?aggregations` for available aggregations. For sd:

```
ps = makeParamSet(
  makeDiscreteParam("C", values = 2^(-2:2)),
  makeDiscreteParam("sigma", values = 2^(-2:2))
)
ctrl = makeTuneControlGrid()
inner = makeResampleDesc("Subsample", iters = 2)
lrn = makeTuneWrapper("classif.ksvm", resampling = inner, par.set = ps, control = ctrl, show.info = FALSE)

outer = makeResampleDesc("CV", iters = 3)
r = resample(lrn, iris.task, resampling = outer, extract = getTuneResult, show.info = FALSE,
  measures = list(setAggregation(mmce, test.sd)))

r$measures.test
  iter mmce
1    1 0.06
2    2 0.02
3    3 0.04
```

**Comment by danielhomola** [comment]
Thanks so much for the quick reply. Just for future reference, for those who might be interested. If you want aggregated metrics from the inner folds you'll need to add measures = list(setAggregation(mmce, test.sd)) to makeTuneWrapper. 

Here's my full example with parallel grid search with Gradient Boosted Regression trees. 

`library(mlr)
library("parallelMap")
# make a parallel environment for gridsearch
parallelStartSocket(8, level = "mlr.resample")
data(BostonHousing, package = "mlbench")
regr.task = makeRegrTask(id = "bh", data = BostonHousing, target = "medv")

ps = makeParamSet(
  makeDiscreteParam("n.trees", values = seq(400,501, by=100)),
  makeDiscreteParam("interaction.depth", values = (2:3))
)
ctrl = makeTuneControlGrid()
inner = makeResampleDesc("Subsample", iters = 10)
lrn = makeTuneWrapper("regr.gbm", resampling = inner, par.set = ps, control = ctrl, show.info = FALSE, measures = list(m1, m2))

## Outer resampling loop
m1 = mse
m2 = setAggregation(mse, test.sd)
outer = makeResampleDesc("CV", iters = 3)
r = resample(lrn, regr.task, resampling = outer, extract = getTuneResult, show.info = FALSE)

r$extract
opt.paths = getNestedTuneResultsOptPathDf(r)
opt.paths
parallelStop()`
