### ISSUE TITLE
Using nested CV with predefined indices

### ISSUE THREAD

**Issue by danielhomola** [mlr-org/mlr#1385]
Is it possible to do nested CV using predefined indices? If I have two columns, one that holds the membership of a sample in the outer fold, and another one that holds the membership of a sample in the inner fold. Can I pass this onto makeTuneWrapper?

Many thanks,
d

**Comment by larskotthoff** [comment]
You can specify the columns as `stratify.cols` in `makeResampleDesc`. This is independent of any wrapper you use with it.

**Comment by danielhomola** [comment]
Thanks a lot for the answer. 

I would need the CV to use the indexing I provide in those two column **exactly**. So for instance:


```
id match outer_fold inner_fold
1   1     1          1          1
2   2     2          1          1
3   3     3          1          2
4   4     4          1          2
5   5     5          2          1
6   6     6          2          1
7   7     7          2          2
8   8     8          2          2
9   9     1          1          1
10 10     2          1          1
11 11     3          1          2
12 12     4          1          2
13 13     5          2          1
14 14     6          2          1
15 15     7          2          2
16 16     8          2          2
```

**Comment by berndbischl** [comment]
stratification is *not* what you are looking for
@larskotthoff that really is someting different

it is not hard to prespecify the outer splits. simply create a resampling instance, then overwrite the train.splits and test.splits in the instance object.

but for the inner folds you cannot do that, that is not supported.

**Comment by danielhomola** [comment]
Thanks a lot for clarifying. Could I extend the package somehow to make this possible?

**Comment by berndbischl** [comment]
yes, of course you can help. we are always very happy about such offers and try to support as much as possible.
(not sure how hard this is in general for you, as the project has become quite large and complex, but let me not scare you away in the first post :) )

so i would suggest the following:
- open a 1 or 2 clean issues about this, which should describe the API FIRST! 
(so you dont waste time)

- i would really start with a clean constructor / setter for indices for normal / outer resampling. thats also needed very often. 

- then we can see how to deal with internal resampling

what do you think?

**Comment by danielhomola** [comment]
Thanks for your response and hints. I realized, that I can simply use my predefined nested indexing, to run 3  cross-validation rounds, then concatenate the results to get something similar to ```getNestedTuneResultsOptPathDf(r)```. 

This is a bit hacky, but I might stick with it, as I'm really pressed for time, and contributing to mlR properly (as you hinted) would take a quite a bit of time. 

Thanks again!

**Comment by danielhomola** [comment]
Sorry for reopening this issue, but wouldn't it be possible to achieve this with blocking? 

To reiterate, all I want is to ensure that certain samples always end up in the same fold, i.e. they cannot be split between test and train.. In my original question I defined this in a much more rigid way, saying that I'd actually want to define for each sample the exact outer and inner fold number it goes to. But now I realise this is overly restrictive and it seems what I want to achieve is easily doable with `blocking`.

An example: let's say we have a classification dataset with 1000 samples. For every positive sample we have 49 negatives which are "matched" with a single positive. Therefore all I want to achieve is to ensure that when I do hyperparameter tuning using nested-cv, these blocks of 50 samples are never separated.

Couldn't this be easily achieved with the `blocking` parameter of `makeClassifTask`?

Many thanks,
d

**Comment by berndbischl** [comment]
1) 
> To reiterate, all I want is to ensure that certain samples always end up in the same fold,

thats what we created "blocking" for. if samples have the same level in "blocking" they will not be put in different folds.

```
#' @param blocking [\code{factor}]\cr
#'   An optional factor of the same length as the number of observations.
#'   Observations with the same blocking level \dQuote{belong together}.
#'   Specifically, they are either put all in the training or the test set
#'   during a resampling iteration.
#'   Default is \code{NULL} which means no blocking.
```

is that text improvable?

2) 

> An example:
i think you simply need to put these 50 guys n a block with the same level

3)
nevertheless, i think your initial request to directly define index sets should be supported.

**Comment by berndbischl** [comment]
i opened this. #1498 

if you respond to 1-2 we can close

**Comment by danielhomola** [comment]
Thanks a lot for clarifying this is great news actually!

**Comment by ajing** [comment]
I have a different problem also associated with a customized split. I want 50 samples aways be in the training set for both outer and inner CV. In makeTuneWrapper, is that possible to do that for inner CV?
