### ISSUE TITLE
Can not integrate the multiclass classifier of earth

### ISSUE THREAD

**Issue by rwarnung** [mlr-org/mlr#1387]
As we have discussed [here](https://github.com/mlr-org/mlr/pull/1320) we can not integrate a multiclass classifier using earth as long as there `contr.earth.response` is not exported in the earth package.

I quote from the pr. if you write the learner in the multiclass setting earth tries to call  `contr.earth.response` and throws and error:

```

lrn = makeLearner("classif.earth")
m = train(lrn, iris.task)
Error in get(ctr, mode = "function", envir = parent.frame()) : 
  object 'contr.earth.response' of mode 'function' was not found
```

**Comment by berndbischl** [comment]
have you tried saying package = "!earth" in the constructor?
@schiffner @larskotthoff 

quoting from BBmisc::requirePackages

packs [character]
Names of packages. If a package name is prefixed with “!”, it will be attached using require. If a package name is prefixed with “_”, its namespace will be loaded using requireNamespace. If there is no prefix, argument default.method determines how to deal with package loading.

(I have seen problems of this type before, basically it means the the client package has a faulty NAMESAPCE, really attaching the package was our way around this, and  this "trick" must still be used for some other learners in mlr for similar reasons IIRC)

**Comment by rwarnung** [comment]
Thanks for the comment. Then I will try this and possibly revive the multiclass learner.

**Comment by rwarnung** [comment]
@berndbischl thanks, I tried this and it works as far as I see. I am posting a new pull request these minutes ... thanks!
