### ISSUE TITLE
Output of Cubist

### ISSUE THREAD

**Issue by larry77** [mlr-org/mlr#1390]
Apologies, I have just realized that 

writeLines(mm4_bef$learner.model$output)

is the solution to my issue. I leave the post only in case it can be of any use to someone else.

##############################################
Dear All,
A minor, but annoying issue.
I am trying my hands at Cubist+R. Cubist, roughly speaking, generates a tree whose terminal leaf is a regression model.
Please consider the example at the end of the post. The only trouble is that when I interrogate the model by 

mm4_bef$learner.model$output

The output is kind of messy. It should be a matter of simply parsing the "\n" in order to have something human readable (which is one of the added values of Cubist).
Any suggestion is welcome.
##################################################

    library(Cubist)
    library(mlr)
    library(parallelMap)

    n_cores <- 6

    data(BostonHousing, package = "mlbench")
    task = makeRegrTask(id = "bh", data = BostonHousing, target = "medv")

    lrn = makeLearner("regr.cubist") 

    ps = makeParamSet(
    makeDiscreteParam("rules", values = seq(5))
     )

    ctrl = makeTuneControlGrid()
    rdesc = makeResampleDesc("RepCV", folds =5, reps = 5, predict="test")
    parallelStart("multicore", n_cores)

    set.seed(1234)
    res = tuneParams(lrn, task = task, resampling = rdesc, par.set = ps,
     control = ctrl)

    ## at this point I update the learner by setting the values of the parameters determined before

    lrn = setHyperPars(makeLearner("regr.cubist"), par.vals = res$x)

    ## Now I can finally train the learner on the whole train dataset

    mm4_bef = train(lrn, task)

**Comment by larskotthoff** [comment]
For reference: mlr doesn't process the learner model in any way; this is just what the model does itself.

In this particular case, just `cat` the output: `cat(getLearnerModel(mm4_bef)$output)`.
