### ISSUE TITLE
Unable to install / load mlr package in R

### ISSUE THREAD

**Issue by saraswatmks** [mlr-org/mlr#1404]
Hi ! 

I am not able to install mlr package in R Studio. Following is the error I am getting:

**Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘mlr’
  These will not be installed**

Please help!

**Comment by larskotthoff** [comment]
See https://stackoverflow.com/questions/31249980/error-in-r-package-which-is-only-available-in-source-form-and-may-need-compil
