### ISSUE TITLE
Difficulties with mboost, party versions

### ISSUE THREAD

**Issue by catastrophic-failure** [mlr-org/mlr#1411]
Hey all, been away for a while. Today I tried to build a binary classification model with `"classif.blackboost"`. As I wanted to use `family = "AUC"`, I updated my `mlr` to the current github version.

Now I can't run this example
```splus
lrn = makeLearner("classif.blackboost", predict.type = "prob")
fit = train(learner = lrn, task = pid.task)
#Error in .Call("R_remove_weights", tree, remove, package = "party") : 
# "R_remove_weights" not resolved from current namespace (party)
```

I'm sure this is due to version incompatibility between `mboost`, `mlr`, and/or `party`, but I can't pinpoint exactly which version should I be using right now.

Hmm, also, this might be due to the fact I'm using Microsoft R Open in my Windows machine, which means by default I access a frozen version of CRAN at MRAN.

**Comment by larskotthoff** [comment]
Did you try updating all of the packages to the latest version?

**Comment by catastrophic-failure** [comment]
Yep, that did it. In case anyone's using MRO, I reinstalled `mlr` from github and also `mboost` from CRAN.

```splus
install.packages('mboost', repos = 'http://cran.us.r-project.org')
devtools::install_github("mlr-org/mlr")
```
