### ISSUE TITLE
Add a chapter on clustering to the mlr tutorial

### ISSUE THREAD

**Issue by rwarnung** [mlr-org/mlr#1414]
We have cluster learners implemented and listed but as far as I found it no clear documentation on how to use them. Can we add a chapter about clustering to the tutorial?

**Comment by PhilippPro** [comment]
+ 1
If you look with detail into some sections you can find it out (e.g. tasks and performance section) but this is hard to find out for newbies. Recently I tried to explain somebody how to do clustering via the tutorial, but this was really not easy. In fact we miss also some graphical interpretations (like e.g. dendrograms) but this is probably beyond the scope of mlr.

**Comment by jakob-r** [comment]
I opened an issue in the github page for the tutorial.
