### ISSUE TITLE
default SE estimation in regr.randomForest is set wrong

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1416]
in the function documentation in the parameter definition we state that the default is `jackknife` but we set `se.method = "bootstrap"` in par.vals.

This is quite confusing as everybody (including myself) would assume that when `regr.randomForest` is run in default settings, that jackknife is used...

**Comment by jakob-r** [comment]
should be set to jackknife then - or what is the consensus?

**Comment by ja-thomas** [comment]
imo yes, but we also have to change the default for `keep.inbag`. 

Or we just use `sd` as it is the simplest. I'm not sure, but I would suggest we use something else than bootstrap

**Comment by berndbischl** [comment]
just use sd in mlr, doc it properly and in mbo we have our own defaults anyway

i dont want "keep.inbag" on as a default

**Comment by riebetob** [comment]
working on this
