### ISSUE TITLE
performance NA when measure not applicable

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1417]
assume the following:

you are benchmarking a number of learner on a number of tasks, and measuring different measures.
now, for some learners it might happen that a certain measure is not applicable, eg there is one learner that cannot predict probs, but you also have AUC in your measures. 

what happens now is that we exit with a hard error and you get nothing.

example:

```
load_all()

tasks = list(sonar.task)

lrn1 = makeLearner("classif.rpart", predict.type = "prob")
lrn2 = makeLearner("classif.logreg")
lrns = list(lrn1, lrn2)
ms = list(mmce, auc)

b = benchmark(lrns, tasks, resampling = hout, measures = ms)
print(b)
```

results in  (assume lrn2 cannot predict probs, i was too lazy)
```
Error in FUN(X[[i]], ...) : 
  Measure auc requires predict type to be: 'prob'!
```

that seems too conservative. eg. if lrn2 would crash one can also get a full benchmark object but with NAs.
I think best would be if "performance" could also return an NA here? with an option for this?
maybe with a warning?

**Comment by larskotthoff** [comment]
Sounds good to me. I would make it an additional on.failure (or something like that) parameter.

**Comment by MasonGallo** [comment]
Looks like this comes from the call to `doPerformanceIteration`. We would want this on.failure arg to be avail only to `benchmark` right?

**Comment by larskotthoff** [comment]
Yep.

**Comment by berndbischl** [comment]
i am not sure i get why it is an on.failure arg we want here? no "failure" really happens?

**Comment by berndbischl** [comment]
maybe it is just the naming? is that options "on.measure.not.applicable"?
