### ISSUE TITLE
Should we write something like getBagPredictions?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1423]
We decided to have `getOOBPredictions(model, task)` which is nice for performance evaluations without resampling.
Similar to that something like `getBagedPredictions(pred)` or `predictBags(model, task, newdata)` could come in handy to have a unified method to access the single bagged predictions. 
For every bag we need the information if an observation is contained (e.g `keep.inbag = TRUE`).

This would enable us to write general functions to calculate the jackknife estimate and the se estimate for example.

**Comment by berndbischl** [comment]
thats indeed useful

**Comment by berndbischl** [comment]
well, maybe even easier to add columns to the normal prediction object? and extend its class?

**Comment by berndbischl** [comment]
we could do the following:

extend predict.type in makeLearner from
response,prob / response, se
-->
response,prob,bagall / response, se, bagall

bagall always containts (in the pred object) the columns for 
response, prob or se, and the "all" cols from the bag

for classif, the "all" cols only contains class labels to make it simpler?

**Comment by jakob-r** [comment]
That's indeed a more straightforward idea.

> for classif, the "all" cols only contains class labels to make it simpler?

Just in a really few cases we would even have the possibility to generate `prob.bagall`, so I think restriction on class labels is totally fine.

But keep in mind, that we would have to extend the prediction object to also contain information for every bag which items it includes if we want to have the option to use jackknife.
