### ISSUE TITLE
Problem using generatePartialDependenceData: "Please set write.forest to TRUE when calling ranger"

### ISSUE THREAD

**Issue by denominator1** [mlr-org/mlr#1425]
While trying to generate partial dependence plots I am getting the following error message:

regr.task <- makeRegrTask(data=result, target="diff") # Define regression task
regr.lrn = makeLearner("regr.ranger", num.trees=1000, seed=4543) # Define regression learner

parallelStartSocket(10)
fit.regr = train(regr.lrn, regr.task) # Train regression learner
parallelStop()

pd.regr.ind = generatePartialDependenceData(fit.regr, regr.task,individual = TRUE)
Error in predict.ranger(object = .model$learner.model, data = .newdata,  : 
  Error: No saved forest in ranger object. Please set write.forest to TRUE when calling ranger.

As we know, "write.forest" is part of ranger() which, according to the manual, does not need to be called when trying to generate those plots via generatePartialDependenceData() (and generatePartialDependencePlots in the next setp, of course). So, is there a way to use generatePartialDependenceData without calling ranger() first? You help is much appreciated!

**Comment by larskotthoff** [comment]
Sounds like this should work -- could you post a complete, reproducible example please?

**Comment by denominator1** [comment]
Quite a difficult task because my data file is huge (2.14 GB). I hope the following code and output might nevertheless help. Thanks for your help! Much appreciated!:

> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: SUSE Linux Enterprise Server 11 SP4

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.0 ranger_0.5.0      dplyr_0.5.0       parallelMap_1.3  
[5] mlr_2.10          ParamHelpers_1.10

loaded via a namespace (and not attached):
 [1] assertthat_0.1   backports_1.0.4  BBmisc_1.10      checkmate_1.8.2 
 [5] colorspace_1.3-2 DBI_0.5-1        ggplot2_2.2.1    grid_3.1.3      
 [9] gtable_0.2.0     lattice_0.20-34  lazyeval_0.2.0   magrittr_1.5    
[13] Matrix_1.2-7.1   munsell_0.4.3    parallel_3.1.3   plyr_1.8.4      
[17] R6_2.2.0         Rcpp_0.12.8      scales_0.4.1     splines_3.1.3   
[21] stringi_1.1.2    survival_2.39-5  tibble_1.2       tools_3.1.3 



# Example

library(mlr)
library(parallelMap)
library(dplyr)
library(ranger)
library(data.table)

result <- data.frame(fread('multilocus.results.csv'))
result$check_sigma_2_env <- result$sigma_2_env > 0

result[result$check_sigma_2_env, "falconer"] <- 2*((result[result$check_sigma_2_env, "sigma_zz_mz_t"]/result[result$check_sigma_2_env, "sigma_2_z"])-(result[result$check_sigma_2_env, "sigma_zz_dz_t"]/result[result$check_sigma_2_env, "sigma_2_z"]))

result$falconer_diff <- result$falconer - result$h2 # Differences/Bias

result <- dplyr::select(result,falconer_diff, a_A, k_A, p_A, a_B, k_B, p_B, a_C, k_C, p_C, rho_gen_env, rho_dom_env, rho_ep_env, h2) # Select all variables needed for the analysis
result <- result[!is.na(result$falconer_diff),] # Omit missing values


#######################################
# Generating partial prediction plots #
#######################################

regr.task <- makeRegrTask(data=result, target="falconer_diff") # Define regression task
regr.lrn = makeLearner("regr.ranger", num.trees=1000, seed=4543) # Define regression learner

parallelStartSocket(10)
fit.regr = train(regr.lrn, regr.task) # Train regression learner
parallelStop()
fit.regr # Check

pd.regr = generatePartialDependenceData(fit.regr, regr.task)

> pd.regr = generatePartialDependenceData(fit.regr, regr.task)
Error in predict.ranger(object = .model$learner.model, data = .newdata,  : 
  Error: No saved forest in ranger object. Please set write.forest to TRUE when calling ranger. 
  Error: Status code 502 returned

**Comment by larskotthoff** [comment]
Hmm, here's an example that works for me:

```
regr.lrn = makeLearner("regr.ranger", num.trees=1000, seed=4543)
fit.regr = train(regr.lrn, bh.task)
pd.regr = generatePartialDependenceData(fit.regr, bh.task)
```

This also works if I do it with parallelMap. It's possible that ranger simply refuses to store the models because they are too large, given that you have this much data. You could always try one of the other random forest models in mlr.

**Comment by denominator1** [comment]
OK, the strange thing, though, is that the analysis did run before I updated my R packages, including ranger and mlr. I have no idea what went wrong. *If* you are interested in running the analysis on a random subset of my data, here it is: https://dl.dropboxusercontent.com/u/3670118/result.csv .

**Comment by larskotthoff** [comment]
Your data works for me as well, all packages updated (some of the preprocessing you're doing doesn't work though).

**Comment by denominator1** [comment]
OK, that's a bit strange. I will check the server configuration, perhaps that's an issue, don't know. The preprocessing (omitting missing cases etc.) didn't cause any problems here. Anyway, thanks for your help, I will check my code again.

**Comment by berndbischl** [comment]
Pls reopen if you can post a complete example for us to debug.
