### ISSUE TITLE
Some fundamental/architectural considerations about curve_data2 branch 

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1436]
For those who are not involved , the curve_data2 branch is for the time series data classification/regression rather than the classical smoothing/prediction using ARIMA,etc. 

I do not expect the following problems to be solved immediately, maybe we should discuss this during the mlr workshop 2017

To fit the need for this new feature of mlr, we have the following new classes

0. inst.R   add FDA dataset
1. **TimeSeriesClassifTask**
File name:  TimeSeriesClassifTask.R
Function name: makeTimeSeriesClassifTask

Keypoint:
type = "tsclassif"
task$task.desc = addClasses(task$task.desc, "TaskDescTimeSeriesClassif")
addClasses(task, "TimeSeriesClassifTask")  [Class - subclass]

Since we have class type check in mlr, currently we have hacked in the following way

- R/checkLearnerBeforeTrain.R 
```
-  if (td$type != learner$type) {
+  # FIXME: this seems a bit bad style, but the other option would be to somehow create
+  # a wrapper for normal classif and regr learners? more code for user and and a bit unintuitive...?
+  if (td$type != learner$type && !(td$type == "tsclassif" && learner$type == "classif")) {
     stopf("Task '%s' is '%s', but learner '%s' is for '%s'!", td$id, td$type, learner$id, learner$type)
   }
```

- measures.R

```
mmce = makeMeasure(id = "mmce", minimize = TRUE, best = 0, worst = 1,
  properties = c("classif", "classif.multi", "fdaclassif", "req.pred", "req.truth"),
  name = "Mean misclassification error",
  note = "Defined as: mean(response != truth)",
  fun = function(task, model, pred, feats, extra.args) {
    measureMMCE(pred$data$truth, pred$data$response)
  }
)

tpr = makeMeasure(id = "tpr", minimize = FALSE, best = 1, worst = 0,
  properties = c("classif", "fdaclassif", "req.pred", "req.truth"),
  name = "True positive rate",
  note = "Percentage of correctly classified observations in the positive class. Also called hit rate or recall.",
  fun = function(task, model, pred, feats, extra.args) {
    measureTPR(pred$data$truth, pred$data$response, pred$task.desc$positive)
  }
)
```
acc
multilable acc

- R/Task_operators.R

```
changeData = function(task, data, costs, weights) {
     "classif" = makeTaskDesc(task, td$id, td$target, td$positive),
     "surv" = makeTaskDesc(task, td$id, td$target, td$censoring),
     "cluster" = makeTaskDesc(task, td$id),
-    "tsclassif" = makeTaskDesc(task, td$id, td$target, td$positive),
     makeTaskDesc(task, td$id, td$target))
   return(task)
 }

```
    "fdaclassif" = makeTaskDesc(task, td$id, td$target, td$positive),
    "fdaregr" = makeTaskDesc(task, td$id, td$target, td$positive),

**Question: Are we going to stick with these hacking or is there better way to do this?**

2. Specific TimeSeries learner, for example

FIle name: RLearner_tsclassif_shapelet.R
Function name: makeRLearner.tsclassif.shapelet
Function name: trainLearner.tsclassif.shapelet
Function name: predictLearner.tsclassif.shapelet

3. Make non time-series learner (ie. all the current classification learners in mlr which do not consider the ordering or time dependencies of features) applicable to our new **TimeSeriesClassifTask**.  

3.1 To achieve this, we have the functionality that transforms a **TimeSeriesClassifTask** to a normal **ClassifTask**, which is in fact a feature extraction technique from time series data. 

File name: TSfeature.R
Function name: makeTSFeaturesClassifTask

The function above is basically choosing from an argument which is a String that lets the user select the following two options to extract the features and transform them into a normal task
File name: TSfeatures_fourier.R
File name: TSfeatures_wavelets.R

**Question: Are we sure we want to do this in a way that each method takes one file and we let the user to pass a string to select which method do we use?** 

3.2 We also have a timeseries preprocess wrapper which is a normal learner
File name: TSPreprocWrapper.R
Function name: makeTSPreprocWrapper

The problem is that I am currently just copying and modifying from our existing wrappers but don't really understand the mechanism, for example

` require('stringi')
  lrn2 = makePreprocWrapper(lrn, train = trainfun, predict = predictfun, par.vals = list(positive = "1"))
  lrn2$id = stri_replace(lrn$id, replacement = ".fourier", regex = "\\.preproc$")
  lrn2 = addClasses(lrn2, "FourierFeaturesWrapper")
  return(lrn2)`

**Again, if we have 100 feature extraction techniques, we are going to have 100 such wrappers?**

**Comment by berndbischl** [comment]
if this is more documentation, move this from here someplace else. maybe the wiki?

**Comment by smilesun** [comment]
out of data
