### ISSUE TITLE
renaming a function name is mlr curvedata 

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1437]
shouldn't we change the name of   "makeTSFeaturesClassifTask " in R/TSfeature.R into "trafoTSTask2ClassifTask" which states clearly what this function does?  If we use the current naming, it is really confusing as we have this "makeTimeSeriesClassifTask" function in "TimeSeriesClassifTask.R" and we only have one subclass called "TimeSeriesClassifTask" defined in function "makeTimeSeriesClassifTask". 

All in all,  in R/TSfeature.R,  we are just transforming a task, but not making a new task.

@berndbischl

**Comment by berndbischl** [comment]
agreed, but rather use
convertTSTaskToNormalTask

(and whether thats regr or classif you can decide dynamically)

**Comment by smilesun** [comment]
finished.
