### ISSUE TITLE
tuneControlDesign is depends on ParSet whereas all other tuneControl* don't

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1438]
This is kind of inconsistent. IMHO it should be the similar as for `tuneControlGrid` so we can use it like this:
```r
tune.ctrl = makeTuneControlDesign(..., budget = 10, design.fun =  maximinLHS)
```
but I don't want to abandon the old style as I still see the use for it
```r
tune.ctrl = makeTuneControlDesign(..., design = specific.design.df)
```

Opinions?

**Comment by berndbischl** [comment]
I can see your point. Just add 2 further args to pass in 
- the PH::generateDesignBla function
- its control arguments as a list

PS:

You are aware aware of the fact that you argue here and wish for EXACTLY the opposite as in 
https://github.com/mlr-org/mlrMBO/issues/305

(and I still see why this is useful.... just saying)

@jakobbossek

**Comment by jakob-r** [comment]
You cought me :wink: But I think *"EXACTLY the opposite" is an overstatement.
In both cases I favor the more general approach. But It is complicated and depends on the use cases we have in mind.

**Comment by berndbischl** [comment]
> But I think *"EXACTLY the opposite" is an overstatement.

overstatement: well possibly. but i think the points still stands ;-)

**Comment by berndbischl** [comment]
but lets be constructive: 

what do you think about 



> Just add 2 further args to pass in
> 
> the PH::generateDesignBla function
> its control arguments as a list

**Comment by jakob-r** [comment]
So we insert the argument `par.set` later inside of tuneDesign when we actually know it?
```r
tune.ctrl = makeTuneControlDesign(...,
  design.fun =  generateDesign, design.fun.args = list(n = 10, par.set = ???))
```
Sounds reasonable. `makeTuneControlRandom` would then just be a wrapper for `makeTuneControlDesign(design.fun =  generateRandomDesign())` and we could remove tuneRandom() internally.

**Comment by berndbischl** [comment]
> So we insert the argument par.set later inside of tuneDesign when we actually know it?

sure

> and we could remove tuneRandom() internally.

that just fucks up existing code. leave it. you would need to deprecate it, but i dont really see the benefit now
