### ISSUE TITLE
Bug in resample.R runtime

### ISSUE THREAD

**Issue by danielhomola** [mlr-org/mlr#1441]
I think https://github.com/mlr-org/mlr/blob/master/R/resample.R#L111
should be:
`runtime = as.numeric(difftime(time2, time1, units="secs"))`

`"sec"` is not a recognised option in `difftime` so it will just default to `auto`, which means, that if something runs for longer than 60 secs, let's say for 84 secs, it will use 1.4 instead. 1.4 is of course in minutes.

**Comment by jakob-r** [comment]
Thanks for spotting the mistake.

**Comment by berndbischl** [comment]
huh? i thought i saw this before? this is still unfixed?

**Comment by danielhomola** [comment]
Thanks for the quick fix!

**Comment by berndbischl** [comment]
lets only close if the PR is merged pls

**Comment by danielhomola** [comment]
oops, sorry

**Comment by berndbischl** [comment]
fixed in #1442

**Comment by berndbischl** [comment]
@danielhomola thx!
