### ISSUE TITLE
learnerArgsToControl: function is not unit tested

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1448]
write tests now

**Comment by berndbischl** [comment]
and possibly make the docs of the helper a bit better

**Comment by berndbischl** [comment]
this actually seems not to work?

```

f = function(x1, x2, ...) {
  xs = learnerArgsToControl(list, x1, x2, ...)
  # print(str(xs))
}

f(1, x2 = 2, x3 = 77)
```

**Comment by MariaErdmann** [comment]
@berndbischl: can you push your change to the function, please? ;-)

**Comment by berndbischl** [comment]
https://github.com/mlr-org/mlr/tree/fix_learnerargstocontrol

**Comment by MariaErdmann** [comment]
Thanks:-)

**Comment by berndbischl** [comment]
@mllg 
possibly also read this. i am not sure if this was your code, mine or olafs. 
but what happens here is pretty bad. (see my example with current master)

comments?

**Comment by mllg** [comment]
Does `BBmisc::argsAsNamedList()` work properly or has the same problems? No additional  comments, we just need some more tests for this "feature" of R.

**Comment by berndbischl** [comment]
with BBmisc and mlr master i get:

```
load_all("~/cos/mlr")
load_all("~/cos/BBmisc/")

f = function(x1, x2, ...) {
    xs = learnerArgsToControl(list, x1, x2, ...)
  print(str(xs))
}

f(1, x2 = 2, x3 = 77)

xs = argsAsNamedList(1, x2 = 2, x3 = 77)
print(str(xs))
```

and only the former seems broken:

```
List of 3
 $ x1: num 1
 $ x2: num 2
 $ 77: num 77
NULL
List of 3
 $ 1 : num 1
 $ x2: num 2
 $ x3: num 77
NULL
```

can you potentially check /  reiterate over my solution that i linked in the branch here?

**Comment by mllg** [comment]
I was originally hinting to  re-writing `learnerArgsToControl` to something like this:
```r
function(f, ...) {
  do.call(f, argsAsNamedList(...))
}
```
But you solution looks also good to me. However, we really need tests, looking up missings is complicated and error-prone.
