### ISSUE TITLE
Use glmnet::glmnet.control(factory = TRUE) in train function

### ISSUE THREAD

**Issue by MariaErdmann** [mlr-org/mlr#1450]
All the glmnet-learners have this code snippet in their train-function:
```
saved.ctrl = glmnet::glmnet.control()
  is.ctrl.arg = names(args) %in% names(saved.ctrl)
  if (any(is.ctrl.arg)) {
    on.exit(do.call(glmnet::glmnet.control, saved.ctrl))
    do.call(glmnet::glmnet.control, args[is.ctrl.arg])
    args = args[!is.ctrl.arg]
  }
```

If there are control parameters set in the learner, the defaults in the `glment::glmnet.control` object are overwritten by the desired parameter settings **permanently**. Therefore, we need to set back the `glment::glmnet.control` object to its default after leaving the train function. 
But we should also do this **before**! (It might be that the user used glmnet  before (without mlr) changed the control parameters (permanently) and then he/she uses mlr and does not work with a default `glment::glmnet.control` object any more.) 
Furthermore, it would be better to use `glmnet`'s 
````
glmnet.control(factory=TRUE) # reset all the parameters to their default
#see
?glmnet::glmnet.control
````

**Comment by larskotthoff** [comment]
Ok, so this is simply a call to `glmnet.control(factory=TRUE)` before and after training?

**Comment by MariaErdmann** [comment]
Yes, and adaption of tests. See PR #1453 1453.
