### ISSUE TITLE
create a data structure that could handle multi channel time series regression/classification

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1451]
For time series classification/regression, very frequently, the task is a multi-modal signal processing, which means data from different sensors which we call "channel" here need to be fused, some of these channels are even not time series, which could be only a factor or so.

These cases are not rare, for example, FDboost which use spline boosting to solve the Functional regression works better in a multi-channel situation, for each channel, a p-spline is fitted.

I discussed with Janek and it seems that we dont' have a field in task which could put meta information to the columns? In fact , the whole data is still a data frame, but we need some meta information to indicate which columns sector are one channel, which are another, and so on.

```
#FIXME: currently the following will not work, since mlr does not support put meta information on the column, which could be a solution to seperate each channel or modal
makeTimeSeriesMultiChannelClassifTask = function(id = deparse(substitute(data)), data, target, weights = NULL, blocking = NULL, positive = NA_character_, fixup.data = "warn", check.data = TRUE, channel.list) {
  checkmate::assert_list(channel.list)
  task = makeSupervisedTask("classif", data, target, weights, blocking, fixup.data = fixup.data, check.data = check.data)
  task = makeClassifTask(id, data, target, weights, blocking, positive, fixup.data, check.data)
  task = makeTimeSeriesClassifTask(id, data, target, weights, blocking, positive, fixup.data , check.data)
  type = "ts_mc_classif" #multi channel
  task$type = type
  task$task.desc$type = type
  task$task.desc = addClasses(task$task.desc, "TaskDescTimeSeriesMultiChannelClassif")
  addClasses(task, "TimeSeriesMultiChannelClassifTask")
}

```

**Comment by Stevo15025** [comment]
Can you provide an example of what the data looks like? If the sensor data all comes in at the same time (periodic) you can just store the time index in the row names of the data.frame.

**Comment by smilesun** [comment]
Ok, first let us make a clear boundary between time series forecasting and classification(which means you want to infer a scalar quantity out of a time series instead of predicting what is the next value for the time series) suppose now I have several sensors about a patient, one is EEG, and another one is blood pressure(continuous measurement and this is already possible due to the technical advances), if this guy has heart disease, it seems that doing a classification on top of the blood pressure time series makes more sense than doing a classification on top of the EEG curve, isn't it? (If my biology knowledge is right) so now, EEG and blood pressure becomes two channel. We definitely need to have some annotation for these two column blocks. What's more, there is another column said this patient is a smoker or not, which is a scalar input instead of a functional input.

All these could not be solved inside mlr if we only have the column name, since this could not be programmed generically?  

What do you think?

xudong

**Comment by smilesun** [comment]
@berndbischl , maybe we could do this by forcing the user to name the column in a pattern that we defined? so we don't need to change anything in mlr?

**Comment by berndbischl** [comment]
@smilesun and i discussed a possible API for this

**Comment by smilesun** [comment]
Yes, Thanks for providing the solution, let me write down our discussion to make it clearer and possibly a little bit more about how to extend that into non-equal-length time series, for example, the churning data.

```
makeTimeSeriesMultiChannelClassifTask = function(id = deparse(substitute(data)), data, target, weights = NULL, blocking = NULL, positive = NA_character_, fixup.data = "warn", check.data = TRUE, channel.list) {
  checkmate::assert_list(channel.list)
  task = makeSupervisedTask("classif", data, target, weights, blocking, fixup.data = fixup.data, check.data = check.data)
  task = makeClassifTask(id, data, target, weights, blocking, positive, fixup.data, check.data)
  type = "ts_mc_classif" #multi channel
  task$type = type
  task$task.desc$type = type
  task$task.desc = addClasses(task$task.desc, "TaskDescTimeSeriesMultiChannelClassif")
  **task$channel.list = channel.list**
  addClasses(task, "TimeSeriesMultiChannelClassifTask")
}
```

The major concern is about how this $channel.list should look like

My suggestion is for the parameter $channel.list, which is to annotate the column , we use

$channel.list = c("ch1","ch1", "ch1",....,"ch1", "s","s", "ch2","ch2","ch2".."ch2", "s","s")
The disadvantage is that we have to define a global variable "s" as a factor which indicate the corresponding column is a scalar.

A nicer proposal by Bernd is $channel.list = list(ch1 = 1:100, ch2 = 150:180) while for the other columns by default is scalar. 

Not sure if we need to consider this design for non-equal length time series.

**Comment by smilesun** [comment]
@berndbischl , I have wrote a little example using the API i have wrote on multiChannel regression task, are you sure you like it? I can't make it shorter to create a task 
```
  data("fuelSubset", package = "FDboost")
  ############################
  dim1 = dim(fuelSubset$UVVIS)
  LEN1 = length(fuelSubset$uvvis.lambda)
  dim2 = dim(fuelSubset$NIR)
  length(fuelSubset$heatan) 
  length(fuelSubset$h2o)
  LEN2 = length(fuelSubset$nir.lambda)
  data = as.data.frame(Reduce(cbind, list(fuelSubset$UVVIS, fuelSubset$NIR, fuelSubset$h2o, fuelSubset$heatan)))
  colnames(data)[length(colnames(data))] = "heat"
  channel.list = list(UVVIS = 1:LEN1, NIR = (LEN1 + 1):(LEN1 + LEN2 + 1))
  index.list = list(UVVIS = fuelSubset$uvvis.lambda, NIR = fuelSubset$nir.lambda)
  reg.task = makeTimeSeriesRegrTask(data = data, target = "heat", channel.list = channel.list, formula.list = NULL, index.list = index.list)  
```

**Comment by sbrockhaus** [comment]
One general thing: you have to decide whether you care for the case that the functional variable is not observed on equally spaced points.

**Comment by sbrockhaus** [comment]
Thus, you decided agaist matrix-valued entries in the data.frame, as done in FDboost, c.f. 
```
data("fuelSubset", package = "FDboost")
str(fuelSubset)
lapply(fuelSubset, class)
```

**Comment by smilesun** [comment]
1. I think we definitely need to include the non-equal distance index 
2. Well, the code could be simplified like below, not sure if there is any way to make this even shorter?
```

  data("fuelSubset", package = "FDboost")
  str(fuelSubset)
  data = as.data.frame(Reduce(cbind, list(fuelSubset$UVVIS, fuelSubset$NIR, fuelSubset$h2o, fuelSubset$heatan)))
  colnames(data)[length(colnames(data))] = "heat"
  channel.list = list(UVVIS = 1:LEN1, NIR = (LEN1 + 1):(LEN1 + LEN2 + 1))
  index.list = list(UVVIS = fuelSubset$uvvis.lambda, NIR = fuelSubset$nir.lambda)
  reg.task = makeTimeSeriesRegrTask(data = data, target = "heat", channel.list = channel.list, formula.list = NULL, index.list = index.list)  
```

**Comment by berndbischl** [comment]
> One general thing: you have to decide whether you care for the case that the functional variable is not observed on equally spaced points.
> Maybe for the moment, it is better to stick to functional data with equally spaced observations - or ignore it if this is not the case...

i would suggest to ignore this for now, to keep it simple

**Comment by sbrockhaus** [comment]
when the index is ignored, I suppose it is enough to specify the indices of the channels like 
`reg.task = makeTimeSeriesRegrTask(data = data, target = "heat", channel.list = channel.list)`

**Comment by smilesun** [comment]
@berndbischl , @sbrockhaus, @fabian-s (can't echo fabian here)
Are we sure that we want the current structure, since most FDA research use list(mat1 = mat1, mat2 = mat2,target = target) structure. The current situation is that we have to transform this into a task and inside the implementation, we have to convert this back to a list matrix again, is this really what we want to repeat those tedious thing? What advantage data we gain if we continue with this.
