### ISSUE TITLE
simplify construction of tuning parameter sets

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr#1452]
Right now we have to build tuning parameter sets from scratch which are similar to learner param sets. It would be nicer to adapt the existing learner param set by only passing the tuning values to it, e.g.  if we want to specify a range for a numeric param, we only add values for min and max to the learner paramset for this param. Technically, we then simply filter the paramset for the params we want to tune. We already have filterParams() where we can filter by param ids.

**Comment by larskotthoff** [comment]
Does `updateParVals` do what you want?

**Comment by berndbischl** [comment]
> Does updateParVals do what you want?

huh? no.

what he / we want is something like this, before you call tuneParams

```
ps = 
list(
list("C", c(-10, 10), scale = "log2")
list("sigma", c(-10, 10), scale = "log2")
)
tuneParams("classif.ksvm", par.set = par.set)
```

(the specific format i just made up, maybe can be improved)


basically a shortcut to define feasibility spaces for tuning. the current way is very verbose, and mlr learner already have the ParamSet object included. It just needs to be "changed" a little bit.

**Comment by larskotthoff** [comment]
Well that's what I was wondering. You could just get the parameter space from the learner and then modify that instead of creating a new one. Maybe have a shortcut function for this.

**Comment by berndbischl** [comment]
I think that would help, we simply need to "perfect format" for that shortcut way of writing it. 
Implementing it is rather trivial I guess.
