### ISSUE TITLE
OOB Curves with any mlr measure

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#1458]
I wrote a little package (it is not completely ready, but the main function works) for calculating the Out-of-bag Curve (number of trees vs. measure calculated over the OOB-Predictions) for any measure that is available in mlr: 
[OOBCurve](https://github.com/PhilippPro/OOBCurve)

In the standard random forest packages only the error-rate-curve is available. 

This corresponds to a paper about the number of trees and the evaluation via error-rate and other measures, that I want to publish, where I critizise the use of the error-rate for this purpose. 

Currently the main function only works for randomForest, but I want to expand it to other packages like ranger and randomForestSRC. Should this be included in mlr anyhow? Any comments on this?

Another idea I have in mind is to use this to make it possible to calculate the variable importance (VIMP) for any measure of mlr in a similar way. I think this would be quite good, as at the moment only in the party package one can calculate the AUC-VIMP as far as I know. 

This is related to #1423

**Comment by jakob-r** [comment]
I think it is completely fine if we have packages building on mlr without having to integrate every method. 
But what i personally find a bit strange with your code is that you mix `mlr` with the regular Learner interface. That kind of defeats the purpose.

I would change it to something like this

```r
mod = train("classif.randomForest", sonar.task)
results = OOBCurve(mod, measures = list(mmce, auc, brier), task = sonar.task)
```

and then just call `getLearnerModel(mod)` inside of `OOBCurve` and run the learner specific code after
```r
if (randomForest %in% class(getLearnerModel(mod))) {
   ...
}
```

Afterwards we can see if we should have more `getOOB` methods in mlr for specific bagged learners and rearrange the code.

**Comment by PhilippPro** [comment]
Thanks for the suggestion. I will try to change it like that. 

I will have to use the keep.inbag parameter and set it to TRUE, but this should be possible.

**Comment by jakob-r** [comment]
Okay. Forgot that. In OOBCurve you can easily query if the parameter was set. To prevent the user from using a wrongly configured learner you could make a wrapper like `makeOOBLearner`.

**Comment by PhilippPro** [comment]
Okay. I changed it, now it supports models of `ranger`, `randomForest` and models of these two packages trained with `train`, so it is quite flexible.
