### ISSUE TITLE
it is very weird that we call listLearners in getDefaultMeasure

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1459]
that can even produce warnings, when some packages are not installed

```
getDefaultMeasure = function(x) {
  type = if (inherits(x, "TaskDesc"))
    x$type
  else if (inherits(x, "Task"))
    x$task.desc$type
  else if (inherits(x, "Learner"))
    x$type
  else if (x %in% listLearners()$class)
    stri_split_fixed(x, ".", simplify = TRUE)[1]
  else
    x
  switch(type,
    classif = mmce,
    cluster = db,
    regr = mse,
    surv = cindex,
    costsens = mcp,
    multilabel = multilabel.hamloss
  )
}
```

**Comment by berndbischl** [comment]
we should simply remove the learner-string case here, or cut up the the string without any listLearners call.
we probably also want a function
listTaskTypes

**Comment by jakob-r** [comment]
That is indeed strange code, but I don't like your suggestion so much. Why don't we call - like usually when the learner can be a string - `checkLearner`? 
Also: Why don't we S3 that whole thing?

**Comment by berndbischl** [comment]
we should really make this function s3, you are 100% correct. 

i still think we should have a function listTaskTypes, maybe independently
