### ISSUE TITLE
we should store the class label distribution in the TaskDesc

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1460]
that info is useful.
currently we only store the label names, but counts for features types.

we should change to a named int vec for the class labels

**Comment by Stevo15025** [comment]
This would also be useful with #1398

**Comment by giuseppec** [comment]
Also the `mlr:::print.ClassifTask` should be updated so that it does not compute the distribution again. Instead it should print the distribution which is stored in the TaskDesc then.

**Comment by juliafried** [comment]
working on this
