### ISSUE TITLE
Learner note: what should be in the note and what not

### ISSUE THREAD

**Issue by MariaErdmann** [mlr-org/mlr#1462]
We talked already about the learner note in #1453 and I will quote what was said:

> what should be in the note:
a) if we change stuff from the "default behavior" of the learner
b) if mlr adds new options to the learner
c) if we know of really severe problems

> what should not be in the learner:

> normal, lengthy explaining documentation. an example is regr.randomForest. for that we have our own se-estimators. the note should possible say that, very briefly, but then should refer to ?regr.randomForest, which documents all the background on this separate page.

**Comment by larskotthoff** [comment]
Sounds good to me.

**Comment by giuseppec** [comment]
Is this here something we should write into the wiki @jakob-r ?

**Comment by berndbischl** [comment]
> Is this here something we should write into the wiki @jakob-r ?

thats mainly relevant for the "create custom learner" page in the tutorial.
talk to @schiffner

**Comment by jakob-r** [comment]
Question: Should this info be in the mlr tutorial or in the dev guidelines?

**Comment by schiffner** [comment]
Bernd is right, this should be in the tutorial.

**Comment by jakob-r** [comment]
Even though some information would be straight for developers?

**Comment by berndbischl** [comment]
> Even though some information would be straight for developers?

you do know that the "create custom learners" page is our developers docs for the mlr learner API at the moment?
