### ISSUE TITLE
have small function listTaskTypes

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1465]
should return simply a char vector of all valid task types

unit test this against the types of all available tasks, possibly the tasks of all objects where we have examples in data?

**Comment by jakob-r** [comment]
I suppose you are talking about `getSupportedTaskTypes()` that we already have.

**Comment by berndbischl** [comment]
thank you.

we have 
getSupportedTaskTypes
getSupportedLearnerProperties

(both unexpoerted)

shall we call them 
listTaskTypes
listLearnerProperties

seems to more consitent for the names. and then export them.

possibly test a little bit

**Comment by jakob-r** [comment]
i am okay with that

**Comment by berndbischl** [comment]
not really done. 

- the functions should be in their own files now
- titles should end with a "dot" .
- the rox docs have too many whitespace lines
- after @description their should be no indentation

**Comment by MasonGallo** [comment]
Do we really want to add 2 more files to essentially contain 1 small function each?

Maybe we could have a single place where these "types" of list/get methods could live.

**Comment by berndbischl** [comment]
> Do we really want to add 2 more files to essentially contain 1 small function each?

well, currently they are in very bad generic files like "helpers.R". and we are more and more moving away from case-by-case exceptions. and at least some very lengthy list* methods are (rightfully) in their own files.
so i dont even know how to handle it better here, and would suggest to have one file each, following our generic rule.

but tell me if you have a better idea.

**Comment by MasonGallo** [comment]
I agree that "helpers.R" is probably too generic.

From reading a few other issues discussing get/set/list methods, I'm thinking this is something we might want to discuss in munich if we have time.
