### ISSUE TITLE
Error in if ((forward && better) || (!forward && (better || (!is.na(control$max.features) &&  :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by vrgaliano** [mlr-org/mlr#1466]
I get this error when using forward sequential search for feature selection:

Error in if ((forward && better) || (!forward && (better || (!is.na(control$max.features) &&  : 
  missing value where TRUE/FALSE needed

**Comment by berndbischl** [comment]
pls provide a full and reproducible example so we have a chance to debug and help

**Comment by github-gs** [comment]
I got the same error, this is my code. Hope you give me some advice. when i used the selectFeatures function, the error came out:'Error in if ((forward && better) || (!forward && (better |(!is.na(control$max.features) &&  : 
  missing value where TRUE/FALSE needed'. 
Is it a bug or my code is wrong? pls help me! 
    

Classify_learner <- makeLearner('classif.nnTrain', predict.type = "prob")
Train_dataset=normalizeFeatures(obj=Train_dataset,target='Condition',method='standardize')
Test_dataset=normalizeFeatures(obj=Test_dataset,target='Condition',method='standardize')
    
Train.task <- makeClassifTask(data = Train_dataset, target = "Condition")
Test.task <- makeClassifTask(data = Test_dataset, target = "Condition")
    
ctrl = makeFeatSelControlSequential(method = "sfs", maxit = NA)
fsr=selectFeatures(learner=Classify_learner,task=Train.task, resampling=folds,measures=list(auc, tpr, fpr),control=ctrl)

**Comment by pat-s** [comment]
Please edit your post and format your code.

**Comment by github-gs** [comment]
> Please edit your post and format your code.

The code has been formatted. Thank you very much for helping me.

**Comment by pat-s** [comment]
Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.
