### ISSUE TITLE
getTaskFormula should check if x is actually a task object

### ISSUE THREAD

**Issue by HeidiSeibold** [mlr-org/mlr#1467]
Otherwise you get funny errors

```
> getTaskFormula(convertOMLTaskToMlr(tsk))
Error in if (type == "surv") { : argument is of length zero
```

This is just a small detail, but could improve user experience ;)

Just FYI: I figured out now that it should be
`getTaskFormula(convertOMLTaskToMlr(tsk)$mlr.task)`
instead :lollipop:

**Comment by jakob-r** [comment]
Always a good idea to assert for classes.

Regarding OpenML: I guess the function is not called `convertOMLTaskToMlrTask` for a reason :wink: .
The confusing name difference is not optimal but `?convertOMLTaskToMlr` is pretty accurate at least.

**Comment by HeidiSeibold** [comment]
> Regarding OpenML: I guess the function is not called convertOMLTaskToMlrTask for a reason :wink: .
> The confusing name difference is not optimal but ?convertOMLTaskToMlr is pretty accurate at least.
Very true :rofl:

**Comment by berndbischl** [comment]
fixing this now

**Comment by berndbischl** [comment]
PR is #1474
