### ISSUE TITLE
we are running Rfast feature filter unit tests in base

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1473]
that package is not very simply to install. we should run a much simpler filter here "as default"

**Comment by berndbischl** [comment]
one with very lightweight dependencies, so RWeka is out too

**Comment by larskotthoff** [comment]
What's so difficult about it? You need an additional system library, is that so bad?

**Comment by berndbischl** [comment]
you can convince me to close this here, but i would rather have simpler tests with less baggage in "base" as a general rule. 

we have the variance filter. why not use this? needs zero packs

**Comment by larskotthoff** [comment]
Fine with me, I just don't see where this is causing an issue that we need to address.

**Comment by berndbischl** [comment]
we had quite a few similar problems before. lets simply do this, takes 10 min

**Comment by berndbischl** [comment]
@florianfendt 

please do this
