### ISSUE TITLE
TSPreprocWrapper

### ISSUE THREAD

**Issue by lbeggel** [mlr-org/mlr#1475]
I've changed the learner id in lrn2 to include the TSpreproc name, i.e.

``
 lrn2$id = stri_replace(**lrn2**$id, replacement = ".fourier", regex = "\\.preproc$")
``
Moreover: the current PreprocWrapper is only usable for fourier trafo. Should we specify another for e.g. wavelets, or should we generalize this one?

**Comment by lbeggel** [comment]
@smilesun @berndbischl

**Comment by berndbischl** [comment]
>  require('stringi')

you cannot simply put "require" statements in your code. 
mlr imports stringi anyway, so it is available

>  lrn2$id = stri_replace(lrn2$id, replacement = ".fourier", regex = "\\.preproc$")

you cannot do this, the user could have set any potential id, it might not even include "preproc"
remove this, open an issue that you dont like the current id. we can deal with it later



> should we specify another for e.g. wavelets, or should we generalize this one?

this is much more important. do this now. and yes, generalize this, we dont want 10 functions for this i think.

**Comment by smilesun** [comment]
As we discussed today, the "fourier " should be passed as an argument to this preprocess wrapper. 
method = "fourier"
`lrn2$id = stri_replace(**lrn2**$id, replacement = method, regex = "\\preproc$")`

not sure if this works.

**Comment by lbeggel** [comment]
Things to do (maybe the previous issues become irrelevant due to this):
-change name (=lrn$id) to ... .tspreproc
-rename function to makeFDAFeatExtractWrapper
-useful example: FilterWrapper

**Comment by smilesun** [comment]
Look at the new preprocesWrapper2.R first

**Comment by lbeggel** [comment]
@smilesun Is this still open? Or should we close it? When we come back to preprocessing, i think we need to start all over again anyway.

**Comment by smilesun** [comment]
I think we could close it now.
