### ISSUE TITLE
Gradually renaming TS to FDA

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1476]
Hi, I have just renamed every file we have currently from "*TS*" pattern to "*FDA*" pattern, but I just changed the file name, please change the function names accordingly.

**Comment by lbeggel** [comment]
Renamed the functions/documentation, expect multiResNaive. 
@smilesun Could you please do this for the multiResNaive?

**Comment by lbeggel** [comment]
Updated also the ts-parts in the more basic mlr structure, i.e.  measures.R and checkLearnerBeforeTrain.R

**Comment by smilesun** [comment]
done.
