### ISSUE TITLE
it should be really simple to request dummy encoding for learners that support factors

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1477]
currently it is a bit tedious, i guess one needs the DummyWrapper

**Comment by berndbischl** [comment]
but please note that we might want to overhaul the whole data preprocessing / cleaning business anyhow.
so this might not be a simple issue and is connected to other questions and should be solved in a consistent manner

**Comment by giuseppec** [comment]
You could close this issue after merging https://github.com/mlr-org/mlr/pull/1139. Changing the prerpocessing stuff is still something which we have to do separately anyway.
