### ISSUE TITLE
Include (missing) learners from package fda.usc for fda

### ISSUE THREAD

**Issue by lbeggel** [mlr-org/mlr#1483]
Useful learners: 
-classif.np / .knn /.kernel:  Nonparametric classifcation with bandwidth / knn / kernel 

DONE. LB

-classif.glm: functional classification using functional (and non functional) explanatory variables by 
-basis representation; fitting GLM

DONE. LB

-classif.gsam: -”- ; fitting Generalized Additive Models

-classif.gkam: -”- : fitting Generalized kernel Additive Models

-classif.DD: classification based on DD-plot (Depth vs Depth)

-classif.depth: classification using maximum depth

**Comment by lbeggel** [comment]
@smilesun For coordination: before starting with a learner, we should add our name/shorthand symbol to the learners and after finishing, add DONE. Are you OK with this?

**Comment by smilesun** [comment]
I will finish the FDboost learner first before I get into these
