### ISSUE TITLE
Tests for learners for FDA

### ISSUE THREAD

**Issue by lbeggel** [mlr-org/mlr#1487]
I've created the new FDA learners "fdaclassif. ..." (e.g. RLearner_FDAclassif_shapelets.R)
@giuseppec Could you please point to a "most representative" example of a classif. ... - learner where I can see how the test structure for learners should look like?

**Comment by berndbischl** [comment]
it really does not matter which one you take. lda. rpart.
they are all very similar

**Comment by berndbischl** [comment]
@lbeggel 
can you please respond if you need further info? or close?
