### ISSUE TITLE
makeLearner: problem with config 

### ISSUE THREAD

**Issue by HeidiSeibold** [mlr-org/mlr#1491]
I am trying to use the config argument in makeLearner (thanks @berndbischl for the hint), but it doesn't seem to do anything.
A little example:

```
> lrn <- makeLearner("regr.glm", par.vals = list(bla = "bla"),
+ config = list(on.par.without.desc = "quiet"))
Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  regr.glm: Setting parameter bla without available description object!
You can switch off this check by using configureMlr!
```

Am I doing something wrong?

```
> getMlrOptions()
$on.learner.error
[1] "stop"

$on.learner.warning
[1] "warn"

$on.par.out.of.bounds
[1] "stop"

$on.par.without.desc
[1] "stop"

$show.info
[1] TRUE

$show.learner.output
[1] TRUE
```

**Comment by Coorsaa** [comment]
@HeidiSeibold try the following:
````
configureMlr(on.par.without.desc = "quiet")
lrn = makeLearner("regr.glm", bla = "bla")
````

**Comment by jakob-r** [comment]
Works flawlessly for me. Which mlr version are you on?

**Comment by HeidiSeibold** [comment]
@Coorsaa that works but I don't want that

@jakob-r mlr 2.9
Let me try updating

**Comment by HeidiSeibold** [comment]
Ah great, the development version solved this issue already. Will use that now, thanks :cake:

**Comment by berndbischl** [comment]
@HeidiSeibold 2.10 is also on cran now

**Comment by berndbischl** [comment]
note to myself:
and we have already a unit test for what heidi is doing here in test_base_hyperpars.
so all is good
