### ISSUE TITLE
we CLEARLY need to document what "default" means in a learner param set

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1494]
see the problems here #1479

**Comment by berndbischl** [comment]
```
what is the default in the ParamSet: it DOCUMENTS what is the default in the UNDERLYING function.
in this case, that is model = TRUE. it is not used in ANY way in code. so if you change it, it has no effect.
what is in there, does not refer to mlr in any way. just for glm.

if you want to change default behavior in a learner, you have to set par.vals.
(we should really not do this very often)

if you change par.vals, say in the note why.
```

**Comment by berndbischl** [comment]
we should also think about whether we want to place that info somewhere in the r docs

**Comment by berndbischl** [comment]
yes, this is kinda a tutorial issue, i created this here, so we solve this soon

**Comment by berndbischl** [comment]
actually we have to document what ALL things in the paramset mean.
constraints and requires settings.
and also how defaults should be specified when mlr introduces new parameters, like in regr.randomForest, the se.estimation stuff

**Comment by larskotthoff** [comment]
![](https://cdn.meme.am/cache/instances/folder739/500x/75511739.jpg)

**Comment by schiffner** [comment]
I have written a lot of stuff, but not pushed yet. Give me a few more days!

**Comment by berndbischl** [comment]
@schiffner 
cool. please push soon.

**Comment by schiffner** [comment]
Ok. Sorry. Was hit critically by SUDDEN RELEASE...

**Comment by berndbischl** [comment]
now, if you start complaining about TOO FREQUENT  releases ..... :)

**Comment by larskotthoff** [comment]
I think the surprise of releases will decrease as they become more frequent.

**Comment by schiffner** [comment]
What Lars said. :)
