### ISSUE TITLE
set model = FALSE for regr.glm like for classif.binomial?

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr#1495]
Should we set model to FALSE for regr.glm analogous to classif.binomial in order to save some memory here aswell?

**Comment by berndbischl** [comment]
thx! 
yes, it should be consistent

``
bischl@bischl-x1:~/cos/mlr (master) $ ack "stats::glm" R

R/RLearner_classif_logreg.R
17:  stats::glm(f, data = getTaskData(.task, .subset), model = FALSE, family = "binomial", weights = .weights, ...)

R/RLearner_classif_probit.R
17:  stats::glm(f, data = getTaskData(.task, .subset), model = FALSE,

R/RLearner_regr_glm.R
46:  ctrl = learnerArgsToControl(stats::glm.control, epsilon, maxit, trace)
57:    m = stats::glm(f, data = d, control = ctrl, family = family, ... )
59:    m = stats::glm(f, data = d, control = ctrl, weights = .weights, family = family, ... )

R/RLearner_classif_binomial.R
21:  stats::glm(f, data = getTaskData(.task, .subset), family = binomial(link = link), weights = .weights, ...)
```
