### ISSUE TITLE
Allow userdefined resampling splits

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1498]
- either through a setter in in the constructor

- we possibly have to check constraints on the splits, so better in the constructor i guess, eg, CV need disjunct folds.

- even better would be a function that magically know from split id structure what type of resampling this is.

- we already have makeFixedHoldout an could deprecate this

**Comment by ajing** [comment]
I have a different problem also associated with a customized split. I have about 300 samples. There are 50 samples I aways want them to be in the training set for both outer and inner CV. In makeTuneWrapper, is that possible to do that for inner CV?

The reason I want those 50 samples always in the training set is that the labels for those samples do not have high quality. So, I want to use other high-quality samples to do parameter selection. Do you think this is a good way to deal with it?

**Comment by berndbischl** [comment]
> I have a different problem also associated with a customized split. I have about 300 samples. There are 50 samples I aways want them to be in the training set for both outer and inner CV. In makeTuneWrapper, is that possible to do that for inner CV?

it is not (easily) possible for the inner resampling iteration. for the outer, you can simply overwrite the index lists, in the ResampleInstance (slot train.inds and test.inds).

For the inner, you could MAYBE establish your own ResampleInstance, by deriving from the base class.
But thats quite hard, I suppose.


> The reason I want those 50 samples always in the training set is that the labels for those samples do not have high quality. So, I want to use other high-quality samples to do parameter selection. Do you think this is a good way to deal with it?

whether that's a good idea, i cannot really tell from here. that really depends on your specific data set and data analysis scenario.

**Comment by ajing** [comment]
Another drawback for using ResampleInstance and setting train.inds and test.inds is that we cannot use the fancy makeTuneControl* (i.e. TuneControlCMAES).
