### ISSUE TITLE
Check that prediction task makes sense

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1499]
We should have a more verbose check, that the data given to train actually makes sense.

```r
> m = train("classif.svm", task = iris.task)
> predict(m, sonar.task)
Error in eval(expr, envir, enclos) : object 'Sepal.Length' not found
```

You would say, that no sane person would do that but actually in the great mlr_shiny app it can easily happen that you accidentally supply a wrong predict data set. But instead of fixing it there I think it makes more sense to do that check inside of mlr.

**Comment by berndbischl** [comment]
I agree that this is helpful, but depending what you do exactly this can become quite costly in each predict step. 

we could as a first step check whether the names of the used features in the model coincide with what is in the predict data frame. 
we also need to watch out that we are too conservative here and break stuff that should work

**Comment by jakob-r** [comment]
I think checking the names is totally fine already. If the new data is a task then comparing the description should also not be so expensive.

**Comment by berndbischl** [comment]
> . If the new data is a task then comparing the description should also not be so expensive.

would be good, but:
a) some stuff will not be the same in the 2 descs (number of obs, some other stuff)
b) this check should also work if "newdata" is simply a dataframe. so we should probably just implement on this level. which means i have not much more than col names. (every other info from the df itself costs some, too much?, time to extract it in every predict...)
