### ISSUE TITLE
clustering in nested cv

### ISSUE THREAD

**Issue by danielhomola** [mlr-org/mlr#1503]
Dear mlr people!

Is there any simple way of incorporating additional modelling steps in the middle of the nested cv? 

For example let's say I have an imbalanced dataset, with 10 times more negative samples than positives. Furthermore let's say I want to assess, whether downsampling the negatives by clustering them and replacing each cluster with their centroid improves performance. Can I somehow plug the clustering process into the nested cv so that it's done on the outer_train, before the hyper-parameter search is done on the inner folds? Or do I need to open up resampling.R and add it in there?

Many thanks,
d

**Comment by berndbischl** [comment]
errm, well, that is what mlr was made for.

we call this "wrapping" the learner to extend its functionality. 
(pipelining might be a more modern name nowadays....)

eg you can add the [DownsampleWrapper](https://github.com/mlr-org/mlr/blob/master/R/DownsampleWrapper.R) to any learner

that do simple downsampling before each training.

when you resample that "extended" learner, that "preprocessing" is naturally embedded in the outer CV

**Comment by berndbischl** [comment]
more comments 1:

now you seem to want more complex downsampling, that does this based on clustering the data.
- for that a convenience method does not exists
- but we have the (PreprocWrapper)[https://github.com/mlr-org/mlr/blob/master/R/DownsampleWrapper.R] to allow exactly extending learners with custom code
- if you find what you are doing of general use and importance you might considering a PR to help other guys (open source collaboration idea...)

**Comment by berndbischl** [comment]
more comments 2:

I think you want to read this. Did you already. And is something badly explained or missing?

https://mlr-org.github.io/mlr-tutorial/devel/html/wrapper/index.html
https://mlr-org.github.io/mlr-tutorial/devel/html/preproc/index.html
https://mlr-org.github.io/mlr-tutorial/devel/html/over_and_undersampling/index.html

**Comment by danielhomola** [comment]
Thanks a lot for your prompt reply (as always)! The info at 
https://mlr-org.github.io/mlr-tutorial/devel/html/preproc/index.html
was new to me.. sorry for not reading the docs more thoroughly. The level of modularity in mlr is pretty amazing. You've done a fantastic job with this package!

I know about the downsampling routines, but I haven't seen this sort of downsampling with clustering implemented. I think it is actually a very nice idea, so I'll write it in the coming days and report back on how it performs. If you then deem it worthy for inclusion, I'm happy to do a PR.

Thanks again!
d

**Comment by berndbischl** [comment]
cool. reopen if you have more questions.

maybe also take a note of this gsoc proposal
yes, we think
> The level of modularity in mlr is pretty amazing
but still we see room for making it even cooler ;-)

https://github.com/rstats-gsoc/gsoc2017/wiki/Operator-Based-Machine-Learning-Pipeline-Construction

**Comment by danielhomola** [comment]
Seems like makePreprocWrapper expects a data.frame not a dataset. So if I were to downsample the data how can I accordingly downsample the blocking variable of the dataset as well? Looks like I cannot do that right?
