### ISSUE TITLE
removeConstantFeatures should not change the seed

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1505]
we had some (pretty obscure) problems here

https://github.com/mlr-org/mlr/issues/1490

problem is that removeConstantFeatures calls computeMode, and that does random tie breaking.
and that changes the seed.

1) removeConstantFeatures should probably never really do something stochastic

2) and I am sure it does not do this now. it does not matter how we compute the mode. so we can simply change to a deterministic tie breaker option.

**Comment by giuseppec** [comment]
+1 to fix this. I think a stochastic behavior is even worse for stuff like `removeConstantFeatureWrapper`, isn't it?

However, we still have to keep in mind that the root of this "problem" is the default in `computeMode`. Therefore, we should also check if it is okay for [other functions]( https://github.com/mlr-org/mlr/search?utf8=%E2%9C%93&q=computeMode) to still use `computeMode`  with the random ties method.

**Comment by berndbischl** [comment]
> +1 to fix this. I think a stochastic behavior is even worse for stuff like removeConstantFeatureWrapper, isn't it?

well like i said the result itself is not stochastic, its simply that we trigger the RNG

> However, we still have to keep in mind that the root of this "problem" is the default in computeMode. Therefore, we should also check if it is okay for other functions to still use computeMode with the random ties method.

i dont know. why is it problematic if a function does something stochastic internally, in general. 
think about integration. or optimization. or other stuff. do you now "worry" to use that because it somehow uses the RNG internally?

**Comment by berndbischl** [comment]
well, maybe it would have been better to choose a different default computeMode. but i cannot change that anymore. and i really dont see a "big" problem in what @heidiseibold reported. 
in mean what is the bad thing that happened? her debugging got a tiny bit harder?
(like a said, removeConstantFeatures will remove every time exactly the same set, even with random tie breaking)

**Comment by berndbischl** [comment]
but tell me if you spot other problems

**Comment by giuseppec** [comment]
> i dont know. why is it problematic if a function does something stochastic internally, in general.
think about integration. or optimization. or other stuff. do you now "worry" to use that because it somehow uses the RNG internally?

I think the bad thing is not knowing/expecting that a function affects the RNG. When I write a script, I think I always know which function does something stochastic and that this will affect the seed in my subsequent code. What I find at least confusing is something like this (I would never expect a different value for `rnorm(1)` just by switching lines) :

```r 
set.seed(1)
rnorm(1)
# [1] -0.6264538
summarizeColumns(iris.task) # you could also do removeConstantFeatures here
#           name    type na     mean      disp median     mad  min  max nlevs
# 1 Sepal.Length numeric  0 5.843333 0.8280661   5.80 1.03782  4.3  7.9     0
# 2  Sepal.Width numeric  0 3.057333 0.4358663   3.00 0.44478  2.0  4.4     0
# 3 Petal.Length numeric  0 3.758000 1.7652982   4.35 1.85325  1.0  6.9     0
# 4  Petal.Width numeric  0 1.199333 0.7622377   1.30 1.03782  0.1  2.5     0
# 5      Species  factor  0       NA 0.6666667     NA      NA 50.0 50.0     3
```

just switch lines in the code gives me:

```r
set.seed(1)
summarizeColumns(iris.task) # you could also do removeConstantFeatures here
#          name    type na     mean      disp median     mad  min  max nlevs
# 1 Sepal.Length numeric  0 5.843333 0.8280661   5.80 1.03782  4.3  7.9     0
# 2  Sepal.Width numeric  0 3.057333 0.4358663   3.00 0.44478  2.0  4.4     0
# 3 Petal.Length numeric  0 3.758000 1.7652982   4.35 1.85325  1.0  6.9     0
# 4  Petal.Width numeric  0 1.199333 0.7622377   1.30 1.03782  0.1  2.5     0
# 5      Species  factor  0       NA 0.6666667     NA      NA 50.0 50.0     3
rnorm(1)
# [1] -0.3262334
```` 

Maybe I am just thinking too far, I just wanted to mention that.

**Comment by MasonGallo** [comment]
Why do we need to select the mode randomly? Can we just remove this entirely and set the default to "first"?

**Comment by MasonGallo** [comment]
I think it makes most sense to change this default in `BBmisc` rather than find/replace a bunch of times in `mlr`

**Comment by berndbischl** [comment]
@MasonGallo I have no idea what is affected if we change this in BBmisc. But for removeConstantFeatures it really makes no difference how the mode is selected. "random" and "first" should be completely equivalent mathematically. 
So i would suggest to simply make the change here
