### ISSUE TITLE
Automatic detection of K using Gaussian-means clustering

### ISSUE THREAD

**Issue by abhinavchdhry** [mlr-org/mlr#1510]
Gaussian-means or G-means, as presented in this paper (https://papers.nips.cc/paper/2526-learning-the-k-in-k-means.pdf) works significantly well for autmatically detecting the right number of clusters in K-means when the clusters are approximately Gaussian. The X-means algorithm which does the same job is already present as `RLearner_cluster_XMeans`

I am currently working on an efficient implementation of G-Means and was wondering if it makes sense to include a learning for this as well?

**Comment by larskotthoff** [comment]
Yes, absolutely. In general, you'd implement the actual learner as a separate package and then have an interface to it in mlr. We'd welcome your pull request for this and I'd be happy to help.

**Comment by berndbischl** [comment]
yes. we will simply create this issue, as this seems to be mainly on your side. 

when you are somewhat done simply open a PR please. that can also contain problem, where  you then ask questions. 
we are happy to help you then.

thx!
