### ISSUE TITLE
difficulties in implementing FDboost in mlr

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1516]
I tried several ways to have FDboost implemented, but I decide to give up this morning before getting further help, the point is I am not aware of a valid way to write the formula in FDboost API through mlr. My implementation is here:
https://github.com/mlr-org/mlr/pull/1500/commits/464509dfb49ee7a0b7b104345f38dd98ee7750fd

The major concern might be how to pass a variable to a formula(I figure that out using eval but combined with bsignal, that does not work.)

**Comment by sbrockhaus** [comment]
Assuming that you need to solve the FIXME in 

https://github.com/mlr-org/mlr/blob/464509dfb49ee7a0b7b104345f38dd98ee7750fd/R/RLearner_FDAregr_FDboost.R#L44

have you tried something like

```
library(FDboost)
tn = "heatan"
fs =  formula(paste0(tn, "~ bsignal(UVVIS, uvvis.lambda, knots = 40, df = 4, check.ident = FALSE)+
                        bsignal(NIR, nir.lambda, knots = 40, df = 4, check.ident = FALSE)"))

mod2f <- FDboost(fs, timeformula = ~bols(1), data = fuelSubset, control = boost_control(mstop = 200))

mod2g <- mboost(fs, data = fuelSubset, control = boost_control(mstop = 200))
```

Does that do the trick? We can also look at it together on Thursday .

**Comment by smilesun** [comment]
hi, this does not work. As you could see from the commented out blocks of the code

**Comment by fabian-s** [comment]
don't know enough context, but the problem seems to be related to metaprogramming in R, `deparse(paste ` etc is usually not the best solution... 
Might something like this help:
```r
library(FDboost)

target = "heatan"
funcyCovariate = "UVVIS"
funcyIndex = "uvvis.lambda"
bsignalArgs = list(knots = 40, df = 4)

#define placeholder formula
fs = formula(target ~ terms)
#overwrite lefthand side
fs[[2]] = as.name(target)
# construct the call to bsignal from the list of arguments ....
rightHandSide = as.call(c(as.name("bsignal"), x = as.name(funcyCovariate), 
    s = as.name(funcyIndex), bsignalArgs))
# .... and write into righthand side
fs[[3]] <- rightHandSide
fs
## heatan ~ bsignal(x = UVVIS, s = uvvis.lambda, knots = 40, df = 4)
```

if you have multiple terms on the right hand side on the formula you can loop over them and concatenate them as repeated calls to  `+`

**Comment by berndbischl** [comment]
just helped @smilesun a little bit to generically construct the formula here.

**Comment by smilesun** [comment]
training now works generically, but I met problem with test 
@berndbischl 

https://github.com/mlr-org/mlr/pull/1517/commits/5ae81ef460f5d8ae92f2fc3913d6e7e797323a86
