### ISSUE TITLE
Using random forest for missing data imputation

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#152]
I made a prepocessing wrapper for imputing missing values with random forests. It can be used for classification, regression and survival tasks and predictors can be both numeric and factors. Since the imputation model is passed to the predict function, missing values in test cases can be imputed without learning from test cases and thereby without biasing performance. More information about how this works is available in [this paper](http://projecteuclid.org/download/pdfview_1/euclid.aoas/1223908043). Could you please review this code and tell me if you agree to incorporate in mlr?

```
#'@export
makeRandomForestImputeWrapper <- function(learner, ...) {
  learner <- addProperties(learner, 'missings')

  trainfun = function(data, target, args) {
    library(randomForestSRC)
    if (length(target) == 2) {
      target = paste0("Surv(", target[1], ",", target[2], ")")
    }
    args = c(list(as.formula(paste(target, '~ .')), data = data, na.action = 'na.impute',
             importance = "none", proximity = FALSE), list(...), args)
    rf.fit = do.call(rfsrc, args)
    i = match(target, colnames(data))
    if (any(is.na(data))) {
      if (!is.null(rf.fit$imputed.data)) {
        data[rf.fit$imputed.ind, - i] = rf.fit$imputed.data[, -i] 
      } else {
        p = predict(rf.fit, data, na.action = 'na.impute', importance = "none", proximity = FALSE)
        data[p$imputed.ind, - i] = p$imputed.data[, -i] 
      }
    }
    return(list(data = data, control = rf.fit))
  }

  predictfun = function(data, target, args, control) {
    if (any(is.na(data))) {
      args = c(list(object = control, newdata = data, na.action = 'na.impute', importance = "none"), args)
      p = do.call(predict.rfsrc, args)
      data[p$imputed.ind, ] = p$imputed.data
    }
    return(data)
  }

  ps = makeParamSet(
    makeIntegerLearnerParam('nimpute', default = 1L, lower = 1L),
    makeIntegerLearnerParam(id = "ntree", default = 1000L, lower = 1L),
    makeDiscreteLearnerParam(id = "bootstrap", values = c("by.root", "by.node", "none"), default = "by.root"),
    makeIntegerLearnerParam(id = "mtry", lower = 1L),
    makeIntegerLearnerParam(id = "nodesize", lower = 1L),
    makeNumericVectorLearnerParam(id = "xwar.wt", lower = 0)
  )
  #Set number of trees to 1 for speed purposes
  pv = list(ntree = 1)

  makePreprocWrapper(learner, trainfun, predictfun, ps, pv)
}
```

**Comment by ForestCoelln** [comment]
i support the proposed randomForestImputeWrapper . I have the feeling the arguments from studerus are still valid.  I have no idea how to impute with randomforestSRC using mlr. Maybe its because i just started using mlr.

**Comment by SteveBronder** [comment]
I like the wrapper, though EOD I believe randomForestSRC does make a random forest model for each predictor no? I'll have to reread the paper.

**Comment by ForestCoelln** [comment]
randomForestSRC::impute performs a multivariate prediction on more than on several target variables at once.  And I don't see how the imputed values for a single predictor can be returned easily as -in my understanding- is required by the mlr-wrapper.   Well maybe i'am wrong. In this case it would be good  -at least for the more inexperienced - to have an more sophisticated imputation wrapper example in the mlr documetation.

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
