### ISSUE TITLE
Tests can fail if viper api is down

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1521]
For `test_base_plotViperCharts.R` we should check if there API is reachable and skip if it's not the case

**Comment by berndbischl** [comment]
shall we remove vipercharts? it is extremely useful and important? 
it also seems to be down quite often....

**Comment by larskotthoff** [comment]
Anybody actually using it?

**Comment by berndbischl** [comment]
really hard to say.

 it is also pretty "external" to mlr, plots are in a different style, etc.

maybe at some point we want to have the most useful stuff like cost curves + lift charts (?) reimplemented in ggplot2.

**Comment by jakob-r** [comment]
Let's put it in the mlrExtras package :wink:

**Comment by berndbischl** [comment]
remove viperchars, put files into "todo-files"

**Comment by ja-thomas** [comment]
And write a blog post with the code so that people can still find it

**Comment by schiffner** [comment]
* ViperCharts also need to be removed from the tutorial (maybe one can scavenge stuff for the blog post).
* One can easily make lift charts (and also precision/recall plots, sensitivity/specificity plots and the like) with `plotROCCurves`, so no need for an extra-implementation.
The only thing we would loose by removing ViperCharts are cost curves.
* There are examples for precision/recall plots and sensitivity/specificity plots in the tutorial. One could add one for lift charts.

**Comment by berndbischl** [comment]
> One can easily make lift charts (and also precision/recall plots, sensitivity/specificity plots and the like) with plotROCCurves, so no need for an extra-implementation.

create an issue to show that please
