### ISSUE TITLE
DLL Error when calling classification tests in forecasting branch

### ISSUE THREAD

**Issue by Stevo15025** [mlr-org/mlr#1535]
In the forecasting branch, the code below will cause a maximum number of DLLs loaded error. The code is a simplified version of the beginning of [`test_learners_classif.R`](https://github.com/mlr-org/mlr/blob/master/tests/testthat/test_learners_all_classif.R)

```r
data(Sonar, package = "mlbench", envir = environment())
binaryclass.df = Sonar
binaryclass.target = "Class"
binaryclass.task = makeClassifTask("binary", data = binaryclass.df, target = binaryclass.target)
task = subsetTask(binaryclass.task, subset = c(10:20, 180:190),
                  features = getTaskFeatureNames(binaryclass.task)[12:15])
lrns = mylist(task, create = TRUE)
#  Error in dyn.load(file, DLLpath = DLLpath, ...) : 
#  unable to load shared object '/home/steve/R/x86_64-pc-linux-gnu-library/3.3/mclust/libs/mclust.so':
#  maximal number of DLLs reached...
#  Failed with error:  ‘package ‘mvoutlier’ could not be loaded’
#   Show Traceback
# 
# Rerun with Debug
# Error in requirePackages(package, why = stri_paste("learner", id, sep = " "),  : 
#  For learner classif.rrlda please install the following packages: rrlda 
```

In (R 3.4)[http://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.html] this won't be an issue as I requested that they allow for users to increase the maximum number of DLLs that R is able to load. 

> The maximum number of DLLs that can be loaded into R e.g. via dyn.load() can now be increased by setting the environment variable R_MAX_NUM_DLLS before starting R.)

But that be out until April and I was wondering if anyone has ideas on how to tackle this now. I plan to submit my masters thesis (the forecasting branch) to the R in Finance conference to present this April. While R 3.4 also is scheduled to come out in April, I think that is a little too close for comfort time-wise.

So,

1. This error only occurs in the tests for classifiers. For the purposes of my branch am I allowed to cut out those tests for now?

2. The error happens on the execution of `mylist()`, is there a way to limit the number of packages `mylist()` will load?

**Comment by larskotthoff** [comment]
1. Yes, although you can also just split up the tests further.
2. `mylist` will load the packages necessary for the learners if you pass `create = TRUE`. You could restrict that number by restricting the number of eligible learners, but again the better solution here is to split up the tests further.

**Comment by Stevo15025** [comment]
Thanks for the feedback lars.

On 2, what should I split the tests by? When I try to split by properties I still receive the error for numerics

```r
data(Sonar, package = "mlbench", envir = environment())
binaryclass.df = Sonar
binaryclass.target = "Class"
binaryclass.task = makeClassifTask("binary", data = binaryclass.df, target = binaryclass.target)
task = subsetTask(binaryclass.task, subset = c(10:20, 180:190),
                  features = getTaskFeatureNames(binaryclass.task)[12:15])
# Same example but only getting numeric learners for binary task
lrns = mylist(task, create = TRUE, properties = "numerics")
# ...
# Loading required package: glasso
# Error in dyn.load(file, DLLpath = DLLpath, ...) : 
#   unable to load shared object '/home/steve/R/x86_64-pc-linux-gnu-library/3.3/glasso/libs/glasso.so':
#   `maximal number of DLLs reached...
# Failed with error:  ‘package ‘glasso’ could not be loaded’
# Error in requirePackages(package, why = stri_paste("learner", id, sep = " "),  : 
#   For learner classif.rrlda please install the following packages: rrlda
```

**Comment by larskotthoff** [comment]
If by property doesn't work, you could try splitting by name, i.e. a-l first and then m-z or something like that.

**Comment by Stevo15025** [comment]
Okay then, I am going to add an argument to `filterLearnerTable()` that takes in a character vector of letters and only takes the packages that start with those letters. Then we can pass that through the dots in `mylist()`. The tests will be broken up such as `test_that(learners work: A-L Numeric classif)` etc.
