### ISSUE TITLE
should we have another check if fd.features cover the whole feature column names

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1537]
Laura and I discussed this, should we have another check for fd.features

e.g.

if ncol(df) = 20
is it allowed to have 
fd.features = list(ch1 = 1:10, ch2 = 11:18)? 

```
  fd.features = lapply(fd.features, function(f) {
    if (is.character(f)) {
      rest = setdiff(f, fnames)
      if (length(rest) > 0L)
        stopf("Functional features must use only data column names, not: '%s'",
          clipString(collapse(rest), 30L))
      return(f)
    }
    if (is.integer(f)) {
      if (!all(f >= 1L & f <= length(cns)))
        stop("Functional features indices must be between 1 and ncols(data)!")
      return(cns[f])
    }
  })
```

**Comment by smilesun** [comment]
@lbeggel , I think in this case, we are assuming that the rest 2 columns are scalar covariates?

**Comment by berndbischl** [comment]
> if ncol(df) = 20
> is it allowed to have
> fd.features = list(ch1 = 1:10, ch2 = 11:18)?

> @lbeggel , I think in this case, we are assuming that the rest 2 columns are scalar covariates?

exactly, what is not mentioned in fd.features is by defintion "scalar". that should also already be in the documentation?
