### ISSUE TITLE
Using data.table in mlr

### ISSUE THREAD

**Issue by Stevo15025** [mlr-org/mlr#1538]
Is it okay to convert data to a data.table, do what you need to do, and then convert it back? I do not see a relevant issue or anything in the coding guidelines so I though I would post here. 

I ask because I am working with making lags in the forecast extension. The code in `createLagDiffFeatures()` is pretty gross at the moment. But I can make the code about half the size and much more readable by using `shift()` in data.table

**Comment by jakob-r** [comment]
I think as data.table is in our IMPORTS it should be okay? I don"t know where it is used though.
