### ISSUE TITLE
how should subsetTask behave for FDA task

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1540]
I have added the S3 method for FDARegrTask as below in this commit 
https://github.com/mlr-org/mlr/pull/1517/commits/ec66973bcc40a3e1da9fdd27b4a62672a1cab85f
```
makeTaskDesc.FDARegrTask = function(task, id, target, td) {
  badtd = makeTaskDesc.RegrTask(task = task , id = id, target = target)
  badtd$type = "fdaregr"
  badtd$fd.features = td$fd.features
  badtd$fd.grids = td$fd.grids
  addClasses(badtd, "FDARegrTaskDesc")
}
```

in changeData in taskOperator. R

```
 task$task.desc = switch(td$type,
    "classif" = makeTaskDesc(task, td$id, td$target, td$positive),
    "surv" = makeTaskDesc(task, td$id, td$target, td$censoring),
    "cluster" = makeTaskDesc(task, td$id),
    "fdaclassif" = makeTaskDesc(task, td$id, td$target, td$positive),
    "fdaregr" = {makeTaskDesc(task, td$id, td$target, td)},
     makeTaskDesc(task, td$id, td$target))
  return(task)
}
```

After making those changes, `subtask = subsetTask(task, features = getTaskFeatureNames(td)[1:10])` will return a FDARegrTask instead of a RegrTask
and `dim(getTaskData(subtask))=11`

but the problem is , the taskDescription for subtask here is still the same with task, which is not right, my question is should the user call subsetTask(task, features = getTaskFeatureNames(td)[1:10])

**Comment by smilesun** [comment]
A full reproducible example for this would be 

```
library(FDboost)
data("fuelSubset")
dim1 = dim(fuelSubset$UVVIS)
LEN1 = length(fuelSubset$uvvis.lambda)
dim2 = dim(fuelSubset$NIR)
length(fuelSubset$heatan)
length(fuelSubset$h2o)
LEN2 = length(fuelSubset$nir.lambda)
mdata = as.data.frame(Reduce(cbind, list(fuelSubset$UVVIS, fuelSubset$NIR, fuelSubset$h2o, fuelSubset$heatan)))
colnames(mdata)[length(colnames(mdata))] = "heatan"
channel.list = list(UVVIS = 1:LEN1, NIR = (LEN1 + 1):(LEN1 + LEN2))
index.list = list(UVVIS = fuelSubset$uvvis.lambda, NIR = fuelSubset$nir.lambda)
fdboost.task = makeFDARegrTask(data = mdata, target = "heatan", fd.features = channel.list, fd.grids = index.list)

subtask1 = subsetTask(fdboost.task)
print(subtask1)
subtask2 = subsetTask(fdboost.task, features = getTaskFeatureNames(fdboost.task)[1:10])
print(subtask2)
dim(getTaskData(subtask2))
```

@berndbischl , could you please add some comments on this

**Comment by berndbischl** [comment]
ok, lets do this:
arg "features" in subset and  train only refers to "basic" non-fd-feature column names. 
during subsetting, the desc-info fd.features needs then to be adapted. 
(and this needs to be unit tested)

later on, the user likely wants to subset whole fd.feature groups. but then in "train", "subset" and mlr in general, we probably want to support feature groups, under such a name. and not now introduce a special arg called "fd.features" in basic functions like "train" and "subset".

**Comment by smilesun** [comment]
according to the current FDA data structure, we decide not to support the feature subset of a single functional covariate.
