### ISSUE TITLE
some limitations about our current data structure for Functional data

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1543]
if we have a video as input which is also time series, our current structure for multi-fda-covariate does not really work . Need to think for a better data structure.

**Comment by smilesun** [comment]
Another problem is to handle the non-equal length  and non identical fd.grids across different observations, (k,v) long format might be a good data structure.

**Comment by berndbischl** [comment]
i would like to keep this simple here, and later possibly extend mlr in general for more complex data structures
