### ISSUE TITLE
classif.plsdaCaret sometimes does not terminate

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1544]
... because it uses the `"oscorespls"` algorithm, which is prone to numerical instability. The [pls package paper](https://www.jstatsoft.org/article/view/v018i02/v18i02.pdf) mentions that the `"kernelpls"` algorithm gives the same result and is usually faster. I suggest changing it [here](https://github.com/mlr-org/mlr/blob/e8801bcb5ad1ac7c5fdfc7b862df7eb4c37a698a/R/RLearner_classif_plsdaCaret.R#L18).

```R
library(fastICA)
> dm <- fastICA(matrix(runif(6000), ncol=6), 6, method="C")$S
> mkt <- makeClassifTask("orthotask", data.frame(t=sample(factor(c('a', 'b')), 1000, replace=TRUE), dm), target='t')
> train(makeLearner('classif.plsdaCaret'), mkt)  # runs forever
```

**Comment by berndbischl** [comment]
well, i kinda see your point, but i really would not like to change the defaults of every learner in mlr.
(in a manual way)

does this break always or just sometimes?

**Comment by berndbischl** [comment]
ok, expand a little bit on your argument, then possibly do a PR with a cleanly documented "note" in the learner why this is changed in mlr

**Comment by mb706** [comment]
`"kernelpls"` is the default behaviour (see 'plsralg' in [pls.options](http://finzi.psych.upenn.edu/R/library/pls/html/pls.options.html)), the [`method = "oscorepls"`](https://github.com/mlr-org/mlr/blob/e8801bcb5ad1ac7c5fdfc7b862df7eb4c37a698a/R/RLearner_classif_plsdaCaret.R#L18) in `trainLearner.classif.plsdaCaret` overrides this.

**Comment by berndbischl** [comment]
ok, so someone HARDCODED a method in the mlr learner, which is NOT even the DEFAULT in the underlying package? 

  caret::plsda(d$data, d$target, method = "oscorespls", ...)

then by  any means please change and correct this!

also there is no "method" apparrantly oin parset
