### ISSUE TITLE
fda: @title should end with a dot

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1546]
pls do now

**Comment by jakob-r** [comment]
That should be in the according PR #1517.
Closing here.

**Comment by berndbischl** [comment]
well, the PR is pretty large so we would like to use issues at least a liitle bit for that.

but hopefully merge the PR in 10 days. 

but ok, that smaller stuff can be discussed in the PR: but do not cliose every fda issue now pls

**Comment by jakob-r** [comment]
Vielleicht wäre das damm mal was, damit ihr nicht hier alles zuspammen müsst :wink: 
https://github.com/mlr-org/mlr/projects
