### ISSUE TITLE
fda: whitelines in rox docs

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1547]
whitelines like this

@title

@description 
sdsadasdsadasdsadasdsa sdasdasd
asdasdasasdasd asdasdasdasd dsasdas

@param <from here on now extra white lines>
@param
...
@return
@export
@example

**Comment by berndbischl** [comment]
also note that there is a linebreak after @description, and no identation for the text block

**Comment by lbeggel** [comment]
DONE
