### ISSUE TITLE
Tuning: Give user the option to specify his own resampling method

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1553]
This would greatly enhance flexibility with respect to things like imputation or fallback learners. It also would allow the user to cache some intermediate results (e.g. filter values for feature selection--unless there already exists an option for that?).

I suggest a `resample.fun` argument that is expected to have the same interface as `resample` and also to return a `ResampleResult`.

**Comment by berndbischl** [comment]
hi,
1) please, especially for "base" changes to the core system let us please discuss this first.

2) I am not sure I understand completely what the advantage is of this. Can you explain, possibly with some examples, what the advantage of this is?

**Comment by mb706** [comment]
I assume being able to write a different `resample` method would generally increase flexibility for those who need it, while not getting in the way of anyone else.

This might, for example, be useful when a user wants to perform more sophisticated imputation in case a learner returns an error (e.g. depending on the proportion of resampling iterations that failed), or for multilevel parallelization of the tuning process, or if someone has a time consuming data-dependent pre-processing step that gives the same result for a given train/test split and could be cached (which was my particular use case).

In my case, I am trying to tune a learner inside a filterWrapper, but it turned out that the filtering step takes way longer than the train/predict steps (since I end up filtering a large proportion of the present features). This is a waste of effort when an optimization method uses a fixed resampling instance, because for a given resampling iteration, the features being filtered are constant. My own '`resample`' method now uses pre-computed `FilterValues`.

I think in the very long run a caching mechanism for these kind of cases would be nice, e.g. have each resampling instance save the seed for all train/test splits, then filterWrappers could cache their `FilterValues`. (If someone gets redis to work on the lrz cluster...)
