### ISSUE TITLE
Predefined fold indices for tuning parameters

### ISSUE THREAD

**Issue by AlejandroCatalina** [mlr-org/mlr#1556]
Hi there,

I am trying out the tuning functionality and I am stuck defining a resampling strategy according to my needs. I find the current strategies very rigid and I would like to specify myself the indices for the train and test folds in a custom CV scheme. The reason why I need this is because my data is a time series, so a usual CV scheme with random folds would not make sense.

To solve this I am trying to define a ResampleInstance and then overwrite the train.inds and test.inds attributes manually, but the tuneParams function throws the following error when passed the modified ResampleInstance

```
[Tune-x] 1: lambda=0.00416
Error: from glmnet Fortran code (error code 7777); All used predictors have zero variance
```

I am trying to tune a Lasso glmnet model with a single "lambda" parameter. Of course, if I don't overwrite the train and test indices in the ResampleInstance it doesn't throw any errors. I don't really get the error, I made sure the indices don't overlap and cover the whole sample space.

Is there any way to achieve what I want? Maybe defining a custom resampling strategy or something?

Thank you for your attention

**Comment by mb706** [comment]
Please make sure that `$train.inds` and `$test.ins` are each a _list of vectors_, not a matrix or just a vector. Even if you are using resampling with only one fold (i.e. if `rdesc$desc$iters == 1`) they each must be a list containing a single vector.

**Comment by AlejandroCatalina** [comment]
Thank you, that seems to solve the issue.
