### ISSUE TITLE
randomForest hangs when nodesize >= sampsize

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1557]
If the `nodesize` parameter (either given, or default 5 for regression and 1 for classification) exceeds (edit: or equals) the `sampsize` parameter (either given, or defaulting to `if (replace) nrow(x) else ceiling(0.632 * nrow(x))`), `classif.randomForest` and `regr.randomForest` hang and can no longer be interrupted with Ctrl-C.

```R
> resample(makeLearner("regr.randomForest", sampsize=2, nodesize=3), pid.task, hout)
[Resample] holdout iter 1:    
```

I don't know if this should be mlr's responsibility; in principle, the `trainLearner` code could check for this and throw an error. Please tell me if these kind of bugs don't belong here.

**Comment by larskotthoff** [comment]
Hmm, we should be able to do this when #1126 is merged I think. And yes, certainly a good thing to raise here.

**Comment by berndbischl** [comment]
> . Please tell me if these kind of bugs don't belong here.

i really do not think that we want to maintain all of these special cases in mlr?
and if the learner hangs that seems like a really bad bug in the package - which you should take up with the original package author

**Comment by larskotthoff** [comment]
But in this case it makes sense to check this in mlr. I agree that the learner hanging is a bug, but even if it didn't it wouldn't make sense.

**Comment by jakob-r** [comment]
But then still - in the very end randomForest should throw a useful error message.
