### ISSUE TITLE
strange behavior of pfr from refund package

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1559]
```
library('refund')
data(DTI)
DTI1 <- DTI[DTI$visit==1 & complete.cases(DTI),]
# Fit model with additive functional term for CCA, using tensor product basis
fit.af <- refund::pfr(pasat ~ af(cca, Qtransform=TRUE, k=c(7,7)), data=DTI1)
```
With error message
```
Error in get(fun, mode = "function", envir = parent.frame()) : 
  object 'refund::pfr' of mode 'function' was not found
```

but  this one works
```
library('refund')
data(DTI)
DTI1 <- DTI[DTI$visit==1 & complete.cases(DTI),]
# Fit model with additive functional term for CCA, using tensor product basis
fit.af <- pfr(pasat ~ af(cca, Qtransform=TRUE, k=c(7,7)), data=DTI1)
```

**Comment by berndbischl** [comment]
for fabian: note that the error is thrown INDSIDE of refund, you seem to be doing some strange stuff with getting from namespace there, which apparently fails when we right valid R code like xudong posted above

**Comment by fabian-s** [comment]
should be fixed now, see https://github.com/refunders/refund/commit/b158e410d9b02401e7fde32a5bc7d81221b8a8ec

I'd argue that it's an **R** bug, though, not a `refund` bug :wink:   
`get("pfr")`   
works but   
`get("refund::pfr")`
doesn't. That's just stupid...

**Comment by smilesun** [comment]
Danke! Such agile fix.

**Comment by berndbischl** [comment]
> I'd argue that it's an R bug, though, not a refund bu

i have seen this problem a couple of times now, and probably would agree i guess....
thx a lot!

**Comment by berndbischl** [comment]
@smilesun why did you reopen without a comment?

**Comment by smilesun** [comment]
@berndbischl @fabian-s , because I found something strange on my computer
First, I run
`devtools::install_github("refunders/refund")`

The following passed. But now it does not work again. even i use  `devtools::install_github("refunders/refund", ref="devel").`
```
library('refund')
data(DTI)
DTI1 <- DTI[DTI$visit==1 & complete.cases(DTI),]
# Fit model with additive functional term for CCA, using tensor product basis
fit.af <- refund::pfr(pasat ~ af(cca, Qtransform=TRUE, k=c(7,7)), data=DTI1)
```

**Comment by smilesun** [comment]
only` library('refundDevel') `works

**Comment by fabian-s** [comment]
@smilesun, sorry for the terrible messiness of `refund` -- if you install the `devel` branch, the package is called `refundDevel`. If you install `master`, it's `refund`. For `mlr` please use the latter as it should be stable and work more reliably.

**Comment by smilesun** [comment]
@fabian-s  hi, thanks, but the master ,the refund::pfr(pasat ~ af(cca, Qtransform=TRUE, k=c(7,7)), data=DTI1) will generate an error, but currently if I don't use the scope operator, mlr will only generate a note, I can still use it.

**Comment by fabian-s** [comment]
@smilesun: sorry, I'm an idiot. https://github.com/refunders/refund/commit/5a9b74b737359fc84428f5f43ed1c302a7208cac actually really fixes it, I promise. You can use `master` now.

**Comment by smilesun** [comment]
Thanks, it works now :+1: , thanks for the quick work :)
