### ISSUE TITLE
User expectations for factors may not match up with using data.matrix() in xgboost

### ISSUE THREAD

**Issue by Stevo15025** [mlr-org/mlr#1561]
So for xgboost on [line 54](https://github.com/mlr-org/mlr/blob/master/R/RLearner_regr_xgboost.R#L54) the learner converts the data.frame to a matrix. If the user has all numeric data that is fine. However, from the [docs](https://stat.ethz.ch/R-manual/R-devel/library/base/html/data.matrix.html) for data.matrix() we see 

> Factors and ordered factors are replaced by their internal codes.

So where a user may expect these to be treated as factors (ie dummy vars) they are instead converted to integers.

I would recommend throwing an error in the xgboost train function if we detect a factor. This leaves the user with the decision to convert factors to dummies or integers.

**Comment by Stevo15025** [comment]
Should I write a branch to check and throw an error?

**Comment by mb706** [comment]
Why not just remove `"factors"` from the learner's `properties`?

**Comment by Stevo15025** [comment]
Oh yes or this

**Comment by Stevo15025** [comment]
Made a pr #1570

**Comment by giuseppec** [comment]
Has been merged https://github.com/mlr-org/mlr/pull/1570
