### ISSUE TITLE
rewrite the feature extraction functions for FDA 

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1562]
I think the API for feature extraction need a lot of refactoring,  for example, the following code has risk that user input some arguments inconsistent.  variable y might not exist at all for the last line. Also, we have copied a lot of code for each feature extraction method to test the parameters, but it would be nice to do them in one wrapper and assume the input is right for each specific method. Also, it does not make sense to include the target at all, including target should be also set in the wrapper instead of each individual function. 

@lbeggel , should I rewrite everything if I need that in a hurry? 

 ```
cns = colnames(data)
  if (target %in% cns) {
    y = data[, target]
    data[, target] = NULL
  }
.....
  # potentially include target again
  if (include.target)
    fftPA[, target] = y
```

**Comment by lbeggel** [comment]
If you need it in a hurry, rewrite it. But i think for the finalized version we need to discuss/formalizes this in a better way and discuss this .

**Comment by lbeggel** [comment]
DONE. No target included
