### ISSUE TITLE
*Tasks should have their separate help pages

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1565]
currently we document everything in Task.R 
lets spread that out to the correct files, like RegrTask.R.
We can and should of course use "inheritParams"

**Comment by florianfendt** [comment]
@berndbischl 
What should happen to all the additional info we currently provide in the description section of the help page (e.g: useful operators and object members). Should it be copied to all the help pages (possibly with inheritSection)?

**Comment by berndbischl** [comment]
use inheritSection and inheritParams, that should remove nearly all copy-paste

**Comment by berndbischl** [comment]
of course one could also still have a general ?Task page and link to that

**Comment by florianfendt** [comment]
ok. I'm doing this now
