### ISSUE TITLE
"Bagging light" with average probabilities

### ISSUE THREAD

**Issue by rwarnung** [mlr-org/mlr#1566]
In my application I would simply like to ensemble a bunch of logistic regressions (say 3 or 4) trained on random subsets of the data. My aim is get a more stable probability estimator. Something like

    makeBaggingWrapper(makeLearner("classif.logreg"), bw.iters = 4, bw.feats = 0.9, bw.size = 0.75)

Using the bagging-wrapper as explained in the tutorial I have to set the base learner to
`predicttype = "response"`. 
If I set the bagged learner to `predicttype = "probability"` then the probability is estimated by the relative proportions of the class lables. So I have to apply a large parameter for `bw.iters` - otherwise my probabilies will be very crude.
The problem could be solved if I can have  `predicttype = "probability"`  on the base learners and then the average of the probabilities is taken.

Can I train a small number of learners on random subsets?
This issue is also a question on [stackoverflow](http://stackoverflow.com/questions/42535668/bagging-in-the-r-package-mlr) but they usually close my questions quickly :) I already have one vote ...

A pedestrian way to do it would be the following. But wouldn't this be they same as bagging the probabilities of two logistic regressions trained on random subsets?
```
library(mlr)
lrn1 = makeLearner("classif.logreg", predict.type ="prob")

N = getTaskSize(sonar.task)
set.seed(100)
sampl1 = sample.int(N, 0.75*N)
sampl2 = sample.int(N, 0.75*N)
mod1 = train(lrn1, sonar.task, subset = sampl1)
mod2 = train(lrn1, sonar.task, subset = sampl2)

final.prediction = 0.5*( predict(mod1, task = sonar.task)$data$prob.M + predict(mod2, task = sonar.task)$data$prob.M)
```

**Comment by berndbischl** [comment]
> The problem could be solved if I can have predicttype = "probability" on the base learners and then the average of the probabilities is taken.

that is indeed currently not supported. not sure why we didnt do it, but i remember the discussion.
maybe multiclass was a little bit harder?

it should be an easy extension though. want to help with a PR? the bagging code itself is pretty smallish and unserstandable.

**Comment by rwarnung** [comment]
Alright, I will try!

**Comment by rwarnung** [comment]
@berndbischl I had a look at the code. The bagged learner is in fact based on `makeHomogeneousEnsemble  `and if I look there, then I see

```
##############################               helpers                      ##############################

# internal mini helper: return a matrix of predictions, either numeric for regr or character for classif
# rows = newdata points, cols = ensembles members
# does only work for responses, not probs, se, etc
predictHomogeneousEnsemble = function(.learner, .model, .newdata, ...) {
```
so I would have to change the character to something numeric for the probabilities. I wonder if changes to the HomogeneousEnsemble affect other parts of the package as well.
If I search for `HomogeneousEnsemble ` then it pops up with quite many learners .. 
What do you think?
