### ISSUE TITLE
tasks should support "ignore" features

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1567]
it is quite often useful to have some cols in the task data.frame, that are not used for modelling.

like IDs, or stuff you only use for stratification, etc.

it would be great if you can simply mark them as like this
makeClassifTask(data = d, target = "y", ignore.cols = c("id", "foo"))

getData then should then get an option whether to return those, which should probably be FALSE by default to ensure backwards compatability

does anyone have a better name than "ignore.cols"?

@jakob-r @mllg @larskotthoff

**Comment by mllg** [comment]
No better name. Maybe differentiate between "active" and "inactive"? Hm.

Be aware that you have to be super careful for ops like `getTaskNFeats()` and `getTaskDesciption()`. Should be a good test if we use the getters everywhere ;)

**Comment by mb706** [comment]
Could then also think of functions to change a task's active/inactive cols, to change a task's task, and to change a task's type.

**Comment by MasonGallo** [comment]
I would find this very useful as long as the implementation doesn't increase memory usage

**Comment by larskotthoff** [comment]
What's the argument against simply removing those columns before making a task?

**Comment by berndbischl** [comment]
> No better name. Maybe differentiate between "active" and "inactive"? Hm.

not sure what you mean here exactly. can you explain pls?

> Be aware that you have to be super careful for ops like getTaskNFeats() and getTaskDesciption(). Should be a good test if we use the getters everywhere ;)

sure. it's not a very trivial change. but needs to be carefully unit tested.

**Comment by berndbischl** [comment]
> What's the argument against simply removing those columns before making a task?

well. i *was* of your opinion, that it is simple preprocessing, and that burden should be "shifted to the user", instead of making mlr more complicated. but here are 2 scenarios, where you can see how it quickly becomes inconvenient:

a) you have and "ID" col in your data. currently, need to remove it before task creation. now, maybe the ids are "meaningful" that they tell you something about certain subgroups in your data, or which observation is what individual. and you would like to know: on which IDs do i observe the largest errors after modeling? you now need to keep track of the id-col outside of the task, and later match it vs. your predictions. while the alternative would be: it is simply in your task.

b) this happened to @smilesun: you have some cols you wanna stratify on. but they are also not allowed to be used in training. xudong had to do this: include them in the task, create the resampling instance, where he stratified on them, then remove the again, so they are not used for the model

**Comment by larskotthoff** [comment]
Ok, sounds good to me. For consistency with the other argument names I would propose `ignore` instead of `ignore.cols`.

**Comment by berndbischl** [comment]
> For consistency with the other argument names I would propose ignore instead of ignore.cols.

i wanted to be more specific, but i think you are correct. it is also not "target.col" but "target". thx

**Comment by nismmech1984** [comment]
Has this option, i.e. 'ignore.cols', been implemented in any way in the latest version?

**Comment by pat-s** [comment]
No, but thanks for bringing it up again. :+1:

**Comment by pat-s** [comment]
Won't fix in {mlr}, please request this in {mlr3} (if still missing).
