### ISSUE TITLE
what is a good way to pass parameters for pfr and other functions

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1568]
Hi, I saw that in  refund package  for one function like pfr, there some so many parameters (less than one milliion )that come from different functions and even different packages(mgcv for example) and should we have a hierachy of parameters for the mlr learner?  something like the user should specify a list    
`pfr.pars = list(af = list(k = vector(), Qtransform = TRUE), peer = list(argvals = vector(), pentype = "RIDGE"), fpc = list(argvals = NULL, method ="svd") )`

An example for DTI datasets
```
data(DTI)
DTI1 <- DTI[DTI$visit==1 & complete.cases(DTI),]
# Fit model with additive functional term for CCA, using tensor product basis
fit.af <- refund::pfr(pasat ~ af(cca, Qtransform=TRUE, k=c(7,7)), data=DTI1)
```
but af here could also be replaced by peer, fpc, etc
```
peer(X, argvals = NULL, pentype = "RIDGE", Q = NULL, phia = 10^3,
  L = NULL, ...)
```
```
fpc(X, argvals = NULL, method = c("svd", "fpca.sc", "fpca.face",
  "fpca.ssvd"), ncomp = NULL, pve = 0.99, penalize = (method == "svd"),
  bs = "ps", k = 40, ...)
```

`re(x, ...)`

**Comment by smilesun** [comment]
what I mean here is maybe something like list(mgcv.s = list(k =3, fac = TRUE), mgcv.af = list(par1 = , par2 = ))

**Comment by smilesun** [comment]
The problem of having a parameter `pfr.pars = list(af = list(k = vector(), Qtransform = TRUE), peer = list(argvals = vector(), pentype = "RIDGE"), fpc = list(argvals = NULL, method ="svd") )` is that how are we going to tune it in the future? but if we flatten out all the parameters, I have to write 60 lines.

**Comment by pat-s** [comment]
I do not understand what this issue is about.
