### ISSUE TITLE
Finish tutorial

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#157]
Currently unfinished:
- Bagging: BB, Julia
  Compare contents with section Wrapped Learners.
  Maybe call this section "Multiclassifier Systems" or "Ensemble Methods" instead and mention/show superlearner, stacked learner.  
  (See https://github.com/mlr-org/mlr-tutorial/issues/11)
- mention `predict.threshold` argument of `makeLearner` (Julia): It's mentioned in the section about cost-sensitive learning, mention maybe in learner.Rmd
- section about setting/tuning threshold in combination with hyper parameter tuning / feature selection (Julia)  
  (See https://github.com/mlr-org/mlr-tutorial/issues/12)

Needs improvement:
- Benchmark experiments with wrappers (i.e. tuning, feature selection etc.):
  Where should this be explained? In Benchmark or in Tuning, Feature Selection etc.?
  Also use other examples than classification.  
  (This is fixed. We have a page about nested resampling now. It shows classification and regression examples. See https://github.com/mlr-org/mlr-tutorial/blob/gh-pages/src/nested_resampling.Rmd)
- Create Custom Learners:
  Should be proofread and enhanced with regard to survival and cluster analysis.
  For example information regarding the prediction type seems incomplete.
  getLearnerData, getFormula and learnerArgsToControl should be explained.
  Maybe explain which learner properties are available and what they mean (e.g. an na.action argument does not necessarily qualify for property missing)  
  (This is mostly fixed. Just need to commit a paragraph about `learnerArgsToControl`.)

Currently broken:

Nice to have:
- automatic link checking:
  try http://wummel.github.io/linkchecker/
  (See https://github.com/mlr-org/mlr-tutorial/issues/25)
- some sort of index, needs further discussion

README to build tutorial:
https://github.com/berndbischl/mlr/tree/gh-pages/tutorial

**Comment by schiffner** [comment]
I have a question regarding the "build" file:

Some packages (including glmnet) have been removed from the list of packages to load first, i.e. before mlr (see 35b6e074b2f0ee30ad680d01c76574dabb89b7f9).

Today I tried to build the tutorial with the latest mlr version and got the following error because mlr::auc is masked by glmnet::auc:

```
Knitting file 'performance.Rmd' ...
Quitting from lines 102-107 () 
Error in lapply(list.files(src, pattern = "\\.Rmd$"), knitIt) : 
  Assertion on 'measures' failed: Must be a list
Calls: lapply ... checkMeasures -> assertList -> makeAssertion -> mstop
Execution halted
```

Is it ok to add glmnet again to the "build" file or is there a different solution I am not aware of?

**Comment by berndbischl** [comment]
We tried to reduce the number of packages, as we use requiereNamespace in requirePackages as the default option now. Sadly, many R packages have a "broken" Namespace file, so we need to "require" them normally. 

Just add anything you need for now to the build file. It is MUCH more important that our content is good and finished.

**Comment by schiffner** [comment]
Thanks Bernd, done.

Another question: I updated the measures tables in the tutorial
(http://berndbischl.github.io/mlr/tutorial/html/measures/index.html).
At least for my settings some of them are too wide to be displayed properly. Could someone with css-experience please have a look?

**Comment by Autodidact24** [comment]
@schiffner @larskotthoff,

Regarding the measures tables display issue:
We can reduce the "padding" to 5px to have tables displayed properly.
![image](https://cloud.githubusercontent.com/assets/5631503/6199761/ec97edca-b47d-11e4-91c0-10577763af06.png)

**Comment by Autodidact24** [comment]
or we can reduce the font-size: 12px; but I guess we want to keep it consistent with rest of the documentation.

**Comment by Autodidact24** [comment]
@larskotthoff,
Regarding automatic link checking:
We can use https://github.com/endymion/link-checker. Its a Ruby gem, and works well with Octopress, Jekyll and other static site generators (MkDocs in our case).

**Comment by larskotthoff** [comment]
@Autodidact24 My preferred solution would be to reduce the size of the left column -- there's lots of whitespace there.

**Comment by Autodidact24** [comment]
@larskotthoff,
I think you mean the spaces around the sidebar and not the column of the table itself. Yes, we can shift the sidebar slightly to the left. 

Regarding the automatic link checking:
Please take a look at this : https://github.com/endymion/link-checker
Its a Ruby gem and works well static HTML pages.

Regarding proof-reading "Create custom learners":
I can take this up. I've been trying to write a custom Learner. So, reading the documentation (and making improvements) may help me understand that better.

**Comment by larskotthoff** [comment]
@Autodidact24 Patches for link checking welcome :)

**Comment by berndbischl** [comment]
I would of course in general prefer the same font size in the tables as in the rest of the tutorial.

But if the font size is a little bit reduced simply for the tables to make them more readable, that is OK for me.

**Comment by berndbischl** [comment]
> Patches for link checking welcome :)
+1

**Comment by berndbischl** [comment]
> Imbalanced Classification Problems

Tobias did that. And @schiffner proof read it. Have you pushed it?

**Comment by Autodidact24** [comment]
@berndbischl @larskotthoff 
I'm trying to integrate link checking. I just wanted to verify how this will work. This may sound too elementary.
So, we use Travis CI for testing the project. If we decide to use http://wummel.github.io/linkchecker/, which is a Python framework, we'll just put something like this in .travis.yml:

```python
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
script: python tests/link_checker.py
branches:
  only:
    - gh-pages
```
Am I right ?

@berndbischl 
Regarding tables display issue:
I think it would be better to reduce "padding" than font.

**Comment by larskotthoff** [comment]
@Autodidact24 Looks ok to me.

**Comment by berndbischl** [comment]
@schiffner 
Can you please port all remaining relevant infos here to the tutorial tracker?
Then close?
