### ISSUE TITLE
little exported helper to cut down the measure names?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1571]
simplifyMeasureNames(xs) 

mmce.test.mean --> mmce

would probably nice if it simply ignore other strings in xs which are not measure names

we dont have do to this, but it is pretty always required when you present mlr tables in reports

**Comment by MasonGallo** [comment]
Would this be replacing the `pretty.names` args?

**Comment by berndbischl** [comment]
not sure. maybe. because we call it on container objects?
you would still need to write a couple of lines of code for that. 
not sure how convenient this is.

and i guess we should not discuss this here, then
