### ISSUE TITLE
Has theme_bw() in plotPartialDependence been depreciated?

### ISSUE THREAD

**Issue by denominator1** [mlr-org/mlr#1578]
Hi,

I updated "mlr" to the most recent version and got a new error message:

> plotPartialDependence(pd.regr.falconer.raised.ind) + theme_bw() + geom_path(size=.000001, alpha=.01) + ylab("Predicted Bias")
Error: could not find function "theme_bw"

The error didn not occur in the previous version and my syntax ran without any problems. ggplot2 was also properly loaded. I therefore wonder whether "theme_bw()" has been depreciated?

**Comment by larskotthoff** [comment]
Have you loaded `ggthemes`?

**Comment by berndbischl** [comment]
how is that related to mlr? 
theme_bw is a ggplot2 function. (or at least it was?)

**Comment by berndbischl** [comment]
the corrrect answer is tat ggplot2 is now in "imports" so we dont pollute the namespace of persons who dont perform mlr plots.

just do library(ggplot2) to attach ggplot functions (like theme_bw)
