### ISSUE TITLE
subset Task before trainLearner.* is called

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1588]
atm we call `getTaskData(.task, .subset, ...)` in all `trainLearner.*` functions. This is error-prone and not intuitive.

The initial motivation behind that seems to be unknown, maybe performance reasons (I talked to @berndbischl about that)

**Comment by berndbischl** [comment]
this is a prettly large change, that i would rather avoid, but i still think we need to make it.

reasons:
* errorprone-ness that @jakob-r mentioned
* it creates problems in expression handling (n gets changed later)
* it just seems bad design

**Comment by jakob-r** [comment]
problem are the Wrappers

**Comment by berndbischl** [comment]
> problem are the Wrappers,

why?

**Comment by jakob-r** [comment]
Maybe not only. We save the subset used drugin `train` in `makeWrappedModel.Learner`. There are several methods that need that information.

* getOOBPreds
* doResampleIteration in certain cases (?)

**Comment by berndbischl** [comment]
well, i did not understand your first comment. now you are referencing further problems without being very specific.... can you maybe explain a bit better what would go wrong if we remove .subset from the signature?

**Comment by jakob-r** [comment]
I have to look further down the call stack to see where the subset is finally used. The comment was more meant to be a memory hook for myself.

**Comment by jakob-r** [comment]
### getOOBPreds
we want to have the prediction exactly for the subset the bag was trained on - here `makePrediction` needs an `id`-vector that was formerly the subset

**Comment by jakob-r** [comment]
For makeWrappedModel we need the `subset` unfortunately we call that function not only from `train()` but also from `trainLearner.ConstantClassWrapper()` and `trainLearner.CostSensClassifWrapper()`

**Comment by mb706** [comment]
Was done in #2100
