### ISSUE TITLE
listLearners, with create=F, seems still to list only installed learners?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1593]
thats a bit strange? i guess we dont want that?

**Comment by berndbischl** [comment]
it is quite simple to fix (i hope), but maybe not for a complete newbie

**Comment by berndbischl** [comment]
had a look at. check.packages = FALSE does what I want.

maybe the default should be changed? if create = F, we probably also want check.packages = F? not sure.

@mllg @larskotthoff 
comments?

**Comment by larskotthoff** [comment]
No opinion on this. Either seems fine to me.

**Comment by ja-thomas** [comment]
> maybe the default should be changed? if create = F, we probably also want check.packages = F? not sure.

+1
