### ISSUE TITLE
Test for Style Guide Adherence

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1599]
If compliance with the style rules in new PRs is a problem it might pay off to test for the most common issues with a test script during package test. This might be as simple as a few greps, or involve static code analysis (there seems to be something like R lint). Don't know how easy it would be to make it run on Windows in the former case.
It would be neat if the test script could also be easily involved from command line (`checkstyle.sh [mlr-dir]`), and if the package internal test (that gets run on travis) could mention this possibility in its error output, so people don't get frustrated when some black box they don't know about keeps rejecting their perfectly well working code.

**Comment by larskotthoff** [comment]
That sounds very good. Could you make such a script to check for common things and integrate that into the build process?

**Comment by mb706** [comment]
Status so far:

Guidelines: [https://github.com/rdatsci/PackagesInfo/wiki/R-Style-Guide](https://github.com/rdatsci/PackagesInfo/wiki/R-Style-Guide).

[lintr](https://github.com/jimhester/lintr/tree/master/R) offers a few hooks that check for specific issues. Unfortunately, the predefined ones are not very flexible in themselves. It is possible to create new "linters", but these custom linters will (1) probably not work with emacs, rstudio etc and (2) need to call `lintr:::`-functions, so idk what CRAN says about that happening in the tests?.

It follows the list of (abridged) code guidelines, with the related linter that could be used.

1. English
  not likely
2. file names
  possible, but not through lintr
3. line length
  `line_length_linter`, though mlr doesn't adhere to this anyways.
4. tabs as 2 spaces
  `no_tab_linter`
5. indentation: 2 spaces per paren
  should be possible
6. double quotes
  create new linter, based on `single_quote_linter`
7. no `T`, `F` but `TRUE`, `FALSE`
  create new linter
8. integers with `L`
  unlikely
9. no `c(1:3)`
  create new linter
10. `=` instead of `<-`
  create new linter based on `assignment_linter`
11. space between operators & assignment; space after comma
  `commas_linter`
  `infix_spaces_linter`
12. curly braces: open: 1 space before, on same line; closing: own line except after `else`
  `open_curly_linter`
  `close_curly_linter`
13. space after if, for, while; no `== TRUE`
  `spaces_left_parentheses_linter`
14. no space before function call paren
  `spaces_left_parentheses_linter`
15. use `return`; return `invisible(NULL)` if nothing else
  sounds hard
16. no semicolon, one cmd per line
  maybe possible with linter
17. use whitespace lines for structure
  d/k
18. one `#` for comment, followed by space. indentation same as code
  d/k
19. function names: camel case
  maybe a variation of `camel_case_linter`
20. vars: lowercase dot separated
  `snake_case_linter`
  maybe a variation of `camel_case_linter`
21. roxygen doc
  not likely
22. one major fn per file
  not likely
23. function length: 1-3 screens
  not likely
24. including: `library`, then `source`, no abs paths
  `absolute_paths_linter`
25. avoid longer, local help functions
  not likely
26. no global vars
  d/k
27. no TODO, only FIXME in comments
  d/k
28. use S3, not S4
  unlikely
29. don't repeat code
  unlikely
30. apply exceptions
  unlikely
31. respect existing code base
  see above

Other linters that could be used for things not mentioned in the style guide:
* `commented_code_linter`: check for commented code
* `object_usage_linter`: "checks that closures have the proper usage"
* `object_length_linter`: max length of objects
* `spaces_inside_linter`: spaces inside parentheses, square brackets
* `trailing_blank_lines_linter`: blank lines at the end of files
* `trailing_whitespace_linter`: whitespace at the end of lines

**Comment by larskotthoff** [comment]
Other things:

Don't use `sapply`, use `v*apply`.

**Comment by berndbischl** [comment]
> , but these custom linters will (1) probably not work with emacs, rstudio etc and (2) need to call lintr:::-functions, so idk what CRAN says about that happening in the tests?.

a) CRAN is not relevant. we only run this on travis, and the code will not be in the mlr package

b) bonus points if you can lint locally or somehow make make rstudio, and other editors support this. but this is REALLY of MINOR importance now. what is important is that this is centrally supported by travis / github and PR pushers get feedback on GH

**Comment by mb706** [comment]
Note: creating new linters is [documented in the lintr github](https://github.com/jimhester/lintr/blob/master/vignettes/creating_linters.Rmd).

**Comment by mb706** [comment]
Closed by #1612
