### ISSUE TITLE
Scalar features in Functional data analysis

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1610]
todo: we need to add scalar features to functional data analysis task, at the moment , the scalar features are ignored

**Comment by berndbischl** [comment]
learners need a property whether they support scalar features.

*if* they support scalar features, learners should of course get and handle them

if they dont, you have 2 options:

a) throw an error, if scalar features are in the task, before training

b) drop them, but warn about it

**Comment by berndbischl** [comment]
maybe b) is more convenient now.

but *document* that well

**Comment by pat-s** [comment]
Eventually fixed in #1880? Either way, not adding more detailed support for FDA to {mlr}.
