### ISSUE TITLE
update NEWS file for 2.11

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1617]
mention also workshop

**Comment by ja-thomas** [comment]
"Thing like master is broken, basic functionality of mlr is wrong, blocks other high prio PRs."

https://github.com/mlr-org/mlr/wiki/github-workflow

**Comment by berndbischl** [comment]
> "Thing like master is broken, basic functionality of mlr is wrong, blocks other high prio PRs."

???

**Comment by berndbischl** [comment]
@ja-thomas

**Comment by ja-thomas** [comment]
That's from the Github workflow. You added this is a blocking issue

**Comment by berndbischl** [comment]
ok thingS. the sentence didnt even pass for me

**Comment by berndbischl** [comment]
done
