### ISSUE TITLE
Inconsistency in dealing with "changing the behavior of API defaults"

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1619]
@larskotthoff , @berndbischl 
We find something strange, if we want to change the default value for  a parameter of an API, we should set par.vals and add a note when we create a custom learner, but we find out that this is not consistent throughout mlr!
e.g. 
In classif.ada
```
    makeIntegerLearnerParam(id = "xval", default = 10L, lower = 0L, tunable = FALSE)
    ),
    par.vals = list(xval = 0L),
```

but in classif. bartmachine

```
  par.vals = list("use_missing_data" = TRUE),
   makeLogicalLearnerParam(id = "use_missing_data", default = TRUE),
```

**Comment by larskotthoff** [comment]
If you find something that's not the way it should be, please fix and make a PR.

**Comment by smilesun** [comment]
But, which  way is right? classif.ada. or classif.bartmachine ?

**Comment by jakob-r** [comment]
bart machines par set is wrong.

defaults in the par set always state what is the default in the underlying function from the original package

par.vals are overriding settings
