### ISSUE TITLE
how to add new properties to FDA learner

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1624]
For functional data analysis task,  we would like to have a property

1. indicating whether this learner could handle scalar variables or not, for example, FDboost and pfr allow for scalar covariate while other learners don't support this. 
2. indicating whether this learner could handle multi-covariate

But when one call `listTaskTypes()`, the FDATask does not exist at all, so could someone explain how to change everything to successfully add two extrac properties for FDATask ? 
```
listLearnerProperties = function(type = "any") {
  allProps = c(listTaskTypes(), "any")
  assertSubset(type, allProps)
  mlr$learner.properties[[type]]
}
```

**Comment by pfistfl** [comment]
Maybe we would want to be able to subset ```listLearners()``` so it only shows fda___ learners, such as **fdaregr**.  As @smilesun noticed, simply applying non-fda learners to functionals works quite well, so this should not be restricted.

**Comment by pat-s** [comment]
We won't add new FDA features to {mlr} anymore, so I'll close here.
