### ISSUE TITLE
randomForest se prediction is NaN if ntrees is small

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1628]
This didn't use to be the case, so I'm wondering if this is supposed to happen.

```R
> lrn <- makeLearner("regr.randomForest", ntree=10, predict.type="se")
> m <- train(lrn, bh.task)
> predict(m, bh.task)
Prediction: 506 observations
predict.type: se
threshold: 
time: 0.09
  id truth response  se
1  1  24.0 25.71350 NaN
2  2  21.6 22.41767 NaN
3  3  34.7 37.22150 NaN
4  4  33.4 34.14950 NaN
5  5  36.2 34.59817 NaN
6  6  28.7 25.82333 NaN
... (506 rows, 4 cols)
```

**Comment by ja-thomas** [comment]
We changed the se estimation of the RF recently, so this might happend there.

**Comment by berndbischl** [comment]
@zmjones 

this happens in the jackknife if an observation is never out-of-bag for any of the 10 trees you used.

  oob = model$inbag == 0
  jack.n = apply(oob, 1, function(x) rowMeans(pred$individual[, x, drop = FALSE]))

in my example it was obs 30. so row 30 in oob contains only F, and rowMeans is applied to an emptyvec.

we should at least document this. a "simple user fix" is to increase number of trees. maybe the best option would be to throw an error here? not sure how one could repair this, and the se estimation is pretty meaningless in this case?

**Comment by mb706** [comment]
There will always be a chance (approx 1 - (1-(1-e^-1)^t)^n ?) that for n observations and t trees at least one observation is not out of bag for any of the trees.

**Comment by mb706** [comment]
To elaborate the above comment -- the `se` prediction fails probabilistically:
```R
> res = sapply(10:20, function(x)
    mean(replicate(100,
        any(is.na(
            predict(train(
                makeLearner("regr.randomForest", ntree=x, predict.type="se"),
                bh.task), bh.task)$data$se)
        ))
    ))
> res
 [1] 1.00 0.98 0.86 0.73 0.51 0.50 0.30 0.19 0.16 0.09 0.07
> plot(10:20, res)
> lines(10:20, 1 - (1-(1-exp(-1))^(10:20) )^getTaskSize(bh.task))
```

![treesuccess](https://cloud.githubusercontent.com/assets/15801081/23795505/4ef4605a-0596-11e7-9157-924a5c5af7ef.png)

I'll go on record and say that I think that learners randomly failing (even if with small probability) is not very nice. How bad would it be to have
```R
model$inbag = model$inbag[rowSums(model$inbag) > 0, , drop = FALSE]
```
at the beginning of `jackknifeStandardError`?

**Comment by berndbischl** [comment]
(hint: if you feel unsure about the formula, simulate it)

assume n = 10K
then that probability is for t
2: 50%
10: 1e-3
20: 1e-6
30: 0 (says my simulation :) )

for n = 50K, t = 30: 

point in case: it does never matter, whether the prob is non-zero. what matters is whether it is likely that this happens more than once in a year.  because if not, you dont have to act on that.

**Comment by berndbischl** [comment]
1) that was an older of mine i apparently not finished. just for completeness sake, you can simulate this with the RF, just simulate a random binary matrix. but whatever

2) i think your fix is very nice. @zmjones should still comment
