### ISSUE TITLE
getModelCoefficients

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1632]
It might be useful to extract model coefficient from all learners that actually have coefficient

e.g. `{classif | regression}.{binomial, cvglmnet, gamboost, glmboost, h2o.glm, logreg, multinom, penalized.lasso}`

We can also add a function for effect plots.

Should be quite simple and similar to `getOOBprediction` and `getFeatureImportance`

**Comment by MasonGallo** [comment]
What do you mean by effect plots?

**Comment by ja-thomas** [comment]
I would use something similar to the `effects` package: https://cran.r-project.org/web/packages/effects/effects.pdf
