### ISSUE TITLE
simplifyMeasureNames: meta review with lars, flo and others

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1633]
the new function violates style guide in multiple places and has also little implementation problems.

should also be in its own file

**Comment by berndbischl** [comment]
@larskotthoff @florianfendt @jakob-r

**Comment by berndbischl** [comment]
- exported function should be in its own file
- dot after title
- no indent in description block
- dont use MANUAL cr's in description block
- no whiteline between @param and  @return
- param xs: no cr after data type

- assertCharacter(xs, min.len = 1L): 
requiring length 1 is suboptimal i guess. in programming you often would like to be able to apply this to empty vecs as well

**Comment by florianfendt** [comment]
on it. I'll open new PR

**Comment by berndbischl** [comment]
> on it. I'll open new PR

thx. it is most important that @larskotthoff and @jakob-r read this, as they review (here: lars)
