### ISSUE TITLE
Using NAs as default for parameter in learner

### ISSUE THREAD

**Issue by Stevo15025** [mlr-org/mlr#1648]
What do we use when the default for a learner is NA? For instance you may have something in a learners set up like

```r
makeIntegerLearnerParam(id = "d", default = NA_integer_, special.vals = list(NA_integer_)),
````

This is used in `auto.arima` in forecasting. When this learner is constructed the warning arises

```r
lrn <- makeLearner("fcregr.auto.arima")
Warning in makeParam(id = id, type = "integer", learner.param = TRUE, lower = lower,  :
  NA used as a default value for learner parameter d.
ParamHelpers uses NA as a special value for dependent parameters.
```

What is proper procedure here?

**Comment by larskotthoff** [comment]
That's the proper procedure. Looking at the documentation, it sounds like NULL should be a suitable default as well though.
