### ISSUE TITLE
The right way to construct a data frame from a list of matrix and vectors

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1656]
@fabian-s,  I think last time we talk about the cons and pros of constructing the data frame from a list of matrix and a list of vectors, you mentioned something that might affect the final behavior,  but I forgot what is that, look at the following code (using branch  "fda_pull1_task" ), 
```
data(fuelSubset, package = "FDboost")
# mdata = data.frame(fuelSubset[c("UVVIS", "NIR", "h2o", "heatan")])  # option 1, the cleaner way   
mdata = as.data.frame(Reduce(cbind, list(fuelSubset$UVVIS, fuelSubset$NIR, fuelSubset$h2o, fuelSubset$heatan)))  # our current method
len1 = length(fuelSubset$uvvis.lambda)
len2 = length(fuelSubset$nir.lambda)
colnames(mdata)[length(colnames(mdata))] = "heatan"
fdf = list(UVVIS = 1:len1, NIR = (len1 + 1):(len1 + len2))
fdg = list(UVVIS = fuelSubset$uvvis.lambda, NIR = fuelSubset$nir.lambda)
fuelSubset.task = makeFDARegrTask(data = mdata, target = "heatan", fd.features = fdf, fd.grids = fdg)
```

Do you think there is a difference between 
`mdata = data.frame(fuelSubset[c("UVVIS", "NIR", "h2o", "heatan")])  # option 1, the cleaner way   `
and 
`mdata = as.data.frame(Reduce(cbind, list(fuelSubset$UVVIS, fuelSubset$NIR, fuelSubset$h2o, fuelSubset$heatan)))  # our current method`

I think the first one has the advantage that it preserves the column names of the original matrix, which is good, and also it is cleaner, 
but I forget what you told last time, there will be a problem if you want to append a column or so to the data frame ? 

 
@giuseppec

**Comment by giuseppec** [comment]
You can simply answer the question yourself by doing a "microbenchmark", e.g.

```

bench = microbenchmark::microbenchmark(
  mdata1 = as.data.frame(iris[, c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width")]),
  mdata2 = as.data.frame(Reduce(cbind, list(iris$Sepal.Length, iris$Sepal.Width, iris$Petal.Length, iris$Petal.Width)))  
)
bench
 
# Unit: microseconds
# expr    min      lq      mean  median       uq     max neval cld
# mdata1 26.941 28.4385  33.65122 31.6455  32.9285  71.843   100  a 
# mdata2 93.225 96.0045 104.95527 97.5020 110.5445 223.654   100   b
```

**Comment by fabian-s** [comment]
hmm, sorry, @smilesun , not sure which conversation you mean,  but as @giuseppec said method 2 is much more expensive because of all the data copying it triggers...
