### ISSUE TITLE
calcConfusionMatrix: more unit tests

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1680]
from test_base_calculateConfusionMatrix

```
check values itself
 +  task = subsetTask(sonar.task, 1:15)
 +  pred = holdout(makeLearner("classif.rpart"), task)$pred
 +  truth = factor(rep("R", 5), levels = c("M", "R"))
 +  predicted = factor(c("R", "R", "M", "M", "M")) # two correct three wrong
 +  err.abs = 3
 +  err.rel = 3/5
 +  pred$data$truth = truth
 +  pred$data$response = predicted
 +  cm = calculateConfusionMatrix(pred, relative = TRUE)
 +  expect_equal(cm$relative.error, err.rel)
 +  expect_equal(cm$result[3,3], err.abs)
```

this only tests the errrate, but the matrices (abs and rel) contain more entries. add a few lines to the test.

**Comment by akasher** [comment]
I wish to solve this issue.  I ran the above test on my local system. And it gave the following error message:-
```

expect_equal(cm$relative.error, err.rel)
Error: cm$relative.error not equal to `err.rel`.
1/1 mismatches
[1] 0.4 - 0.6 == -0.2

```
This test checks the cm$relative.error, and cm$result[3,3] , but does not check cm$relative.row and cm$relative.col. 

So should I add some lines to check those?

**Comment by larskotthoff** [comment]
If you're getting errors with the existing tests, try updating all of your packages to the latest version. And yes, the idea is to have more checks.

**Comment by berndbischl** [comment]
@akasher 
if you find a real problem with the codebase, we always need a fully reproducible example

**Comment by giuseppec** [comment]
Confusion matrix also shows values such as the positive predicted value (ppv), see https://en.wikipedia.org/wiki/Confusion_matrix#Table_of_confusion which we should also unit test.
E.g. we should check if the corresponding entry in the confusion matrix equals to `performance(pred, ppv)`. We need to do this for some other measures (see `listMeasures()`) that can be derived from the confusion matrix.
