### ISSUE TITLE
Vote on new mlr logo!

### ISSUE THREAD

**Issue by MasonGallo** [mlr-org/mlr#1684]
Please vote on your favorite logo by "reacting" to it with a +1 below. Thanks @hannahatkin for creating the logos!

**Comment by MasonGallo** [comment]
![bluedots](https://cloud.githubusercontent.com/assets/4913951/23921391/de509dfe-08d4-11e7-952c-14e67e4c014d.png)

**Comment by MasonGallo** [comment]
![bluerabbitsquare](https://cloud.githubusercontent.com/assets/4913951/23921523/50dd2158-08d5-11e7-8dcd-b7c14a12564c.png)

**Comment by MasonGallo** [comment]
![bluerabbittext](https://cloud.githubusercontent.com/assets/4913951/23921565/78180ff8-08d5-11e7-9d53-5d7b1cf80781.png)

**Comment by MasonGallo** [comment]
![orangestarbig](https://cloud.githubusercontent.com/assets/4913951/23921613/a3fd939a-08d5-11e7-8919-bb08fc03d70d.png)

**Comment by MasonGallo** [comment]
![orangestarsmall](https://cloud.githubusercontent.com/assets/4913951/23921639/ba507a5e-08d5-11e7-93e2-f39537aa8cba.png)

**Comment by schiffner** [comment]
All look great!
Just a quick question: I get the rabbit. Do the star and the squares also have a special meaning that I'm missing? :grimacing:

**Comment by berndbischl** [comment]
i really really dont know :)

i like the microsoft logo, and the 2 rabitts, the 1st one possibly the least......
argh

**Comment by berndbischl** [comment]
@MasonGallo do you also want to publish a mini post on the blog? (so it gets on rbloggers)

**Comment by hannahatkin** [comment]
@schiffner The block one is the most abstract -- this is playing on the idea of ease and simplification. MLR makes tedious tasks easier, like the last block just needs one more simple nudge to complete the pattern.

The star logos are made of oval shapes, playing on the shape that is found behind the R logo. I took the oval and made it into a cohesive pattern as if building off from R itself.

**Comment by jakob-r** [comment]
Actually i like the first one the most. It has a "retro" touch. :smile: 
Unfortunately caret seems to have gotten note of our actions and they completely removed the carot from all their visible sites. This kind of makes it harder to get the joke.

@hannahatkin: Can you provide favicon versions of the logos so we can see how they would look in the browser?

**Comment by schiffner** [comment]
@hannahatkin Very cool! Thanks for the info.

**Comment by hannahatkin** [comment]
@jakob-r Favicons actually need to be hand designed in order to scale properly so I was only planning on creating that once we finalized on a design. Unfortunately, I don't have the time to create all of them right now. I will say, that the for the one you liked, I'd likely just use the "mark" (the orange squares) as the favicon if that helps visualize it a bit.

**Comment by mb706** [comment]
So everyone gets up to 6 votes?

**Comment by larskotthoff** [comment]
I think you get as many votes as you like :)

**Comment by PhilippPro** [comment]
I like the third one most. The first one is hard to read, although I really like the description below, maybe should be included into the others too. And it seems like network graphs which is not the main thing of mlr...
The last two ones remind me of physics and molecules.

**Comment by MasonGallo** [comment]
> @MasonGallo do you also want to publish a mini post on the blog? (so it gets on rbloggers)

@berndbischl yes I'll put up a short blog post linking to this issue by tmw

**Comment by saraswatmks** [comment]
Great work @hannahatkin 
I liked the second one. 
It's great to see such enthusiasm and support for mlr package. I learned it last december even [wrote a tutorial](https://www.analyticsvidhya.com/blog/2016/08/practicing-machine-learning-techniques-in-r-with-mlr-package/) but then I stopped myself to learn further, being afraid that it might be just another R package which came and got lost on CRAN. Now, I'm pretty cheered up! :)

**Comment by berndbischl** [comment]
> learned it last december even wrote a tutorial 

i saw your tutorial back then and was pretty happy. good job! 

> but then I stopped myself to learn further, being afraid that it might be just another R package which came and got lost on CRAN

believe me, i / we have invested too much to give up now ;-)

**Comment by MasonGallo** [comment]
Looks like we have a winner @ 50 votes!
