### ISSUE TITLE
New Learners From Existing R Package table is broken in wiki

### ISSUE THREAD

**Issue by Stevo15025** [mlr-org/mlr#1685]
https://github.com/mlr-org/mlr/wiki/List-of-Possible-Enhancements-to-mlr

**Comment by ja-thomas** [comment]
I really really hate Markdown tables....

I tried to fix It for 15 minutes, now I'm mad and it still doesn't work....

If someone else is motivated to try it, feel free...

**Comment by Stevo15025** [comment]
Seems like everything is fine now
