### ISSUE TITLE
kknn wrong package name

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#1689]
kknn causes problems when uploading a run on OpenML. The reason is, that the package name is `!kknn` instead of `kknn` in makeLearner:

 ```
 makeRLearnerClassif(
    cl = "classif.kknn",
    # FIXME: kknn set its own contr.dummy function, if we requireNamespace,
    # this is not found, see issue  226
    package = "!kknn",
```
Is this still necessary?

This is related to #226.

**Comment by ja-thomas** [comment]
Wasn't that fixed in https://github.com/openml/openml-r/pull/319 ?

have you tried updating you openML package?

**Comment by berndbischl** [comment]
please read the (fucking) docs

?requirePackages


packs	
[character]
Names of packages. If a package name is prefixed with “!”, it will be attached using require. If a package name is prefixed with “_”, its namespace will be loaded using requireNamespace. If there is no prefix, argument default.method determines how to deal with package loading.
