### ISSUE TITLE
regr.rvm parameter "tau" doesn't do anything?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1707]
regr.rvm only calls `kernlab::rvm`, which doesn't seem to use a "`tau`" parameter. `tau` is neither mentioned in the help, nor in the [source](https://github.com/cran/kernlab/blob/master/R/rvm.R).

**Comment by catastrophic-failure** [comment]
Good catch, probably a leftover from `classif.lssvm`.

**Comment by berndbischl** [comment]
> Good catch, probably a leftover from classif.lssvm.

seems so
