### ISSUE TITLE
Random selection of rows for generatePartialDependenceData(): Silly problem or feature suggestion

### ISSUE THREAD

**Issue by denominator1** [mlr-org/mlr#1708]
This is perhaps an entirely idiotic question or a feature suggestion at best: I wonder whether it is possible to define a random selection of rows from an already trained learner in "input" from

	generatePartialDependenceData(obj, input,…)

Here comes a description of the problem using an example:

	regr.task <- makeRegrTask(data=result, target="diffs") # Define regression task
	regr.lrn = makeLearner("regr.ranger", num.trees=1000, seed=4543) # Define regression learner

	parallelStartSocket(60)
	fit.regr = train(regr.lrn, regr.task) # Train regression learner
	parallelStop()

Here comes the actual problem: We use

	pd.regr = generatePartialDependenceData(fit.regr, regr.task) 

to generate partial dependence data, which uses the *entire* trained data from "regr.task". However, when the original data are huge one might actually be interested in just using a random selection of the data for generatePartialDependenceData() and plot these results using plotPartialDependence(). I wonder whether it is possible to define the random selection *within* generatePartialDependenceData().

**Comment by denominator1** [comment]
OK, sorry, I found the solution. Example:
          pd.regr = generatePartialDependenceData(fit.regr, getTaskData(regr.task)[sample(nrow(getTaskData(regr.task)), size = 500),])

**Comment by larskotthoff** [comment]
So this is solved and can be closed?

**Comment by denominator1** [comment]
Yes, please.
