### ISSUE TITLE
Reference for FeatureImportanceData

### ISSUE THREAD

**Issue by stellasophia** [mlr-org/mlr#1712]
Hi,
I have seen that with the mlr-function "FeatureImportanceDate" it is also possible to compute an importance for interactions by using the interaction=TRUE argument. 

The manual says that all features are permuted together and then the performance is contrasted with the performance without the features being permuted. This approach seems very interesting to me. Unfortunately, I could not find a documentation or a reference where its functioning is described more in detail i.e. a proof is given of how this works. 

Is there any reference anyone could help me with?
Any source would be appreciated very much. 

@berndbischl

**Comment by ja-thomas** [comment]
@zmjones I think you are the specialist for that :)

**Comment by berndbischl** [comment]
@zmjones are you there?

**Comment by zmjones** [comment]
yep! there are a bunch of references for this, but the original is friedman's 2001 boosting paper. i'll add that today.

**Comment by zmjones** [comment]
there isn't any theoretical analysis of this general method, the closest thing is [this nips paper](https://papers.nips.cc/paper/4928-understanding-variable-importances-in-forests-of-randomized-trees.pdf) by giles louppe

**Comment by stellasophia** [comment]
Thanks a lot. I will look into that

**Comment by berndbischl** [comment]
@zmjones 
did you add the refs? then we could soon close

**Comment by berndbischl** [comment]
@zmjones 
shall we not maybe also add the giles loupe paper in refs? if it helps people to understand what happens

sorry

**Comment by zmjones** [comment]
i am not so sure it does. this is one of those methods where the theory is pretty far disconnected from practice. the method analyzed in louppe's paper is much more closely related to the gini gain importance measures that some of the rf learners compute internally.

**Comment by zmjones** [comment]
anyways after i thought about it some i think the friedman paper is probably the best reference. i don't know of any paper that considers this method specifically, everything else mentions either some very specific alternative or related method or only discusses it in passing.

**Comment by berndbischl** [comment]
ok thx
