### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1721]
The release tags stopped being made at version 2.8, FYI

**Comment by berndbischl** [comment]
i know. @larskotthoff @mllg 
i guess we never needed them and it was just another thing on the todolist.

get rid of them? is that a bad idea? i mean the old targz get collected on cran.

**Comment by larskotthoff** [comment]
I'm in favour of resurrecting them. It makes it easier to go back and see what exactly was included in a release.
