### ISSUE TITLE
unit test for learners with missing prop

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1724]
in this PR #1690 @mllg assigned to the prop missing wrongly to h2o glm.

yes, this can happen. but our unit tests should catch this. 
why dont they?

**Comment by mllg** [comment]
Tests are working because h2o glm can handle missing values in its default configuration.

**Comment by berndbischl** [comment]
then i dont get what @kdpsingh said here:

quote start
Thanks for merging. However, as per my original note, only h2o GBM and h2o randomForest support missings. The other h2o models (including GLM) currently don't support missing values -- there is an interface to perform mean imputation via h2o but I wouldn't count that as supporting missing values.
quote end


so h2o glm imputes missing with the mean? always, per default? 
then i see this as technical support for missings. and we should possibly add the property again?

**Comment by berndbischl** [comment]
> then i see this as technical support for missings. and we should possibly add the property again?

ok, i read the docs. i dont know, maybe as we are at the moment, we are good. glm does not support missings (in mlr), as the handling is very "naive" and mlr supports this in a more general way trough its impute oprrators,

we also have

testThatLearnerHandlesMissings = function(lrn, task, hyperpars) {

so i guess we are good

**Comment by kdpsingh** [comment]
It wasn't clear to me on the h2o website but I just looked more closely at the h2o R package documentation.
Both h2o.glm and h2o.deeplearning functions have a "missing_values_handling" property that defaults to "MeanImputation." This is probably why the unit tests worked. (On website it wasn't clear that this was the default behavior.)
If mean imputation by the package constitutes missing value support (which would be reasonable), then I would consider adding the "missings" property back to h2o.glm and to h2o.deeplearning and would add a note regarding mean imputation in the notes section on the tutorial webpage.
If you decided not to consider this as missing value support, would also understand if this is consistent with approach to other packages.




On Wed, Mar 22, 2017 at 7:41 AM -0400, "Bernd Bischl" <notifications@github.com> wrote:













then i see this as technical support for missings. and we should possibly add the property again?



ok, i read the docs. i dont know, maybe as we are at the moment, we are good. glm does not support missings (in mlr), as the handling is very "naive" and mlr supports this in a more general way trough its impute oprrators,


we also have


testThatLearnerHandlesMissings = function(lrn, task, hyperpars) {


so i guess we are good

**Comment by berndbischl** [comment]
@larskotthoff @mllg @jakob-r 

what to do about the glm learners, do we gibe them "missing" or not? 
i REALLY am unsure. this is kinda in between.

if a learner simply has na.handling = na.omit i see this not as "proper" and we dont mark with "missing".
(as this is too simple and just drops data)

OTOH i also dont want to argue back and forth whether learners implement a "good" missing value handling technique. we dont mark quality, we mark technical capabilities. 

one could argue that the learner ITSELF does not handle missings, but then again many learners dont handle factors, and do some dummy encoding.

please help ? :)

**Comment by larskotthoff** [comment]
We can only test the technical aspect in the unit tests. I think that's what we should go for -- we also don't judge learners or parameter settings in this way.

**Comment by kdpsingh** [comment]
In that case I would suggest adding the missings property back for h2o glm and also for h2o deeplearning. I would consider adding a note to the mlr tutorial saying for h2o glm and deeplearning that the model defaults to doing mean imputation. That should resolve this from coming up again.
Apologies for creating confusion. Thanks so much for your hard work on this package.






On Wed, Mar 22, 2017 at 12:51 PM -0400, "Lars Kotthoff" <notifications@github.com> wrote:












We can only test the technical aspect in the unit tests. I think that's what we should go for -- we also don't judge learners or parameter settings in this way.

**Comment by berndbischl** [comment]
> We can only test the technical aspect in the unit tests

thats clear, it is about semantics, what the props mean. 
the point is that many learners already drop observations that have missing values in them.
this would pass our formal tests.

so you now propose that we all give the "missing" property?

**Comment by kdpsingh** [comment]
Just to be clear, h2o glm and deeplearning don't drop observations. They mean impute by default.






On Wed, Mar 22, 2017 at 1:45 PM -0400, "Bernd Bischl" <notifications@github.com> wrote:













We can only test the technical aspect in the unit tests



thats clear, it is about semantics, what the props mean.

the point is that many learners already drop observations that have missing values in them.

this would pass our formal tests.


so you now propose that we all give the "missing" property?

**Comment by larskotthoff** [comment]
@berndbischl Yes, I think that would make sense.

**Comment by berndbischl** [comment]
> yes, I think that would make sense.

i really do not....

**Comment by berndbischl** [comment]
> Just to be clear, h2o glm and deeplearning don't drop observations. They mean impute by default.

sure, i have read the docs. just a general argument about what "missing" means. to contrast.

**Comment by larskotthoff** [comment]
Ok, but then we need a clear definition of what's "sensible". And we should think about this for the other properties.

**Comment by berndbischl** [comment]
> Ok, but then we need a clear definition of what's "sensible".

yes. exactly. my personal understanding:

- surrogate splits of trees and the like: reasonable. a very special mechanism to handle NAs
- just dropping any row with an NA: not reasonable. you dont learn anything, it is just a naive cop out. and you could do this for any learner. then "missing" becomes meaningless.

---> so we should give the property for anything that is vaguely reasonable. that might include the mean.imputation of h2o here as well....

**Comment by ledell** [comment]
@berndbischl I think this has been resolved via my PR: https://github.com/mlr-org/mlr/pull/2028 So this issue can be closed.
