### ISSUE TITLE
Restructure learners_all tests

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#1725]
## Problem
If I touch a a single learner or implement a new learner, I have to run the `learners_all` tests to confirm that the learner really supports missings, handles weights, ... This is takes a long time, you frequently get DLL errors and unrelated warnings. Summarized, this is just unnecessarily tedious.

## Proposal
Implement a single function `testLearner(lrn, task = NULL, pars = list())`. This function proceeds as follows:

* Construct learner using `makeLearner(lrn, pars)`.
* If `task` is `NULL`, construct a small sample task depending on the class of the learner as well as properties of the learner: `numeric`, `factors`, `ordered`, `missings`. For the future, you might also want to introduce the arguments `n` and `p` to control the size of the generated task.
* Test additional properties of the learner like `weights`, `prob`, `se` and so on. These tests are mostly already implemented in `helper_helpers.R`.
* If anything goes wrong, stop with an error. This way, you can use `traceback()`, `browser()` etc.
* If all tests pass, return `TRUE`. Unit tests should just call the function like `expect_true(testLearner("classif.lda"))`.

I also propose to put this function in the package and export it. This way, you can easily test your custom learners. You could also write some unit tests for it, e.g. test that an error is thrown if a learner has the  `missings` property but does not a fit on a task with missings.

**Comment by berndbischl** [comment]
> If I touch a a single learner or implement a new learner, I have to run the learners_all tests to confirm that the learner really supports missings, handles weights, ... This is takes a long time, you frequently get DLL errors and unrelated warnings. Summarized, this is just unnecessarily tedious.

correct + agree

> Proposal

probably a good idea and better than what we currently have.

what about the handcrafted tests we have? where we compare the manual training vs the mlr training. i would really like to get rid of them but this is probably a bad idea?

**Comment by mllg** [comment]
> what about the handcrafted tests we have? where we compare the manual training vs the mlr training. i would really like to get rid of them but this is probably a bad idea?

I think they can co-exist. A unit test for a learner should still contain hand-crafted tests, but should also contain call(s) to `testLearner()`. This way, one can filter tests for a specific learner efficiently.

**Comment by berndbischl** [comment]
> I think they can co-exist.

this is what i also thought. a bit annoying, but we still need them.

OK so this is going to be "effort" what is outlined here. i guess a person should structure the general tests first, then we can ask the hiwis to put them into the individual learner files. 

but we PRECISELY need to define first what should happen.

**Comment by larskotthoff** [comment]
Proposal looks good to me.
