### ISSUE TITLE
Create learner for survival analysis with discrete hazard modelling

### ISSUE THREAD

**Issue by jyk** [mlr-org/mlr#1726]
Please add learner for survival analysis with discrete hazard modelling using discSurv package. I can help You if needed. Jüri Kuusik

**Comment by berndbischl** [comment]
> I can help You if needed

sure, we are happy to look at a PR. docs are here.
https://mlr-org.github.io/mlr-tutorial/devel/html/create_learner/index.html

**Comment by jyk** [comment]
OK, I will start to code it. However it will take some time... Jüri
