### ISSUE TITLE
Ideas for extending the linters

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1727]
In the `lintr` PR I mentioned some things that are part of the style guide, but that are not currently checked by the linter. Also there are some other things that are good style, not mentioned in the style guide, that could be enforced. Most of these either take some effort to implement, given the current capabilities of lintr, or are violated so much that making the mlr code conform would take some work.
 
Some of my thoughts on possible extensions:
- [ ] Maximum line length:
`line_length_linter` exists and could easily be added to the currently active linters, but there are quite a few lines that are quite long. Some of the long lines are long string constants (e.g. `notes` of some learners).
- [ ] Prevent too many blank lines
mlr could agree on a maximum of consecutive blank lines it wants to allow, or if it wants to forbid trailing blank lines in a file. For the latter, there is `trailing_blank_lines_linter`.
- [ ] Two spaces indentation per parenthesis / braces level:
Would be an interesting project to write a linter that does this.
- [ ] Check indentation of comments
Would probably be a corollary of the above.
- [ ] Check that `#` is followed by a space or a single quote
Quite easy, have a look at `todo_comment_linter` on how to handle comment content.
- [ ] Disallow things like `c(1:3)`:
Currently the `unneeded_concatenation_linter` checks for constants of the form `c(1)`; it can probably be extended to also check for `c(1:3)`.
- [ ] Disallow `for (i in 1:n)`
This can be a bug when `n` is ever `0`, but it is a question of whether it is desirable to ban this. It could furthermore be debated if all `1:n` should be disallowed, or only the ones in `for` loops, not the ones in other places, e.g. indexing arrays. If so, one would need to write a linter that ideally still allows expressions involving only constants (as e.g. `1:10`).
- [ ] test for, and forbid, `== TRUE`:
Unfortunately, `== TRUE` is needed for [paramset requires arguments](https://github.com/berndbischl/ParamHelpers/issues/62), so if someone creates a linter for this, they have to make exceptions for these.
- [ ] test for `v*apply` instead of `sapply`
There is an easy to use `undesirable_function_linter` that could just forbid `sapply`, but there are many `sapply`s in the code that would need to be replaced first.
- [ ] (Edit:) `curly_braces_inter`
This one can check for curly braces formatting (e.g. `}` being always on a line of its own etc.). It should probably be modified, however, to tolerate `fun({x = expr()}) kind of situations. Also make sure spaces before curly braces are enforced.
- [ ] (Edit:) Spaces before closing parentheses seems to be a problem sometimes.

**Comment by larskotthoff** [comment]
I would do the easy and important things first, in particular indentation and `sapply`. We should probably wait a bit to see how this works out in practice though.
