### ISSUE TITLE
createDummyFeatures applied to train and test data separately

### ISSUE THREAD

**Issue by SixiangHu** [mlr-org/mlr#1728]
There may have an issue on `createDummyFeatures` function when it applies to train and test data.

Say, I have a factor column "factor1" in both train and test data, but level "x" only existed in train data.
After applied `createDummyFeatures` function to both data, new train data has `factor1.x` and it becomes a feature in the learner.  But when use the model to predict test data, it will have error as there is no `factor1.x`.

Example like:
```
factor1 <- sample(LETTERS,100,replace=TRUE)
num1 <- sample(1:10,100,replace=TRUE)

# create an extreme case that all levels in train cannot be found in test
all <- data.frame(factor1,num1)
train <- subset(all,factor1 %in% LETTERS[1:13])
test <- subset(all,!factor1 %in% LETTERS[1:13])

trtask <- makeRegrTask(data=train,target="num1")
tstask <- makeRegrTask(data=test ,target="num1")

trtask <- createDummyFeatures(trtask)
tstask <- createDummyFeatures(tstask)

mod  <- train("regr.gbm",trtask)
pred <- predict(mod,tstask)
```

And the code above gives error:
```
Error in eval(expr, envir, enclos) : object 'factor1.A' not found
```

Probably there is already a function / method to solve this issue in `mlr`, but cannot find it.

What I have tried:
1.  `Resampling` section of the tutorial doesn't metion useful info on index control that I can `createDummyFeatures` combined data then split.

2. `fixup.data = "no" ` doesn't work in `makeRegrTask`.  Run:
`trtask <- makeRegrTask(data=train,target="num1",fixup.data="no")`
has an error:
`Error in eval(expr, envir, enclos) : object 'factor1.A' not found`
looks like `checkTaskData` function in `tark.R` file ignore the `fixup.data` option?

**Comment by larskotthoff** [comment]
You could use stratified resampling, or you could manually make sure that all factor levels are present after splitting:

```
test$num1 = factor(test$num1, levels = levels(train$num1))
```

**Comment by SixiangHu** [comment]
@larskotthoff, thanks for the quick reply. Realised that the example I provided is misleading to training / holdout sample split, which can be solved by stratified resampling provided by `mlr`. 

However, the actual problem here is after you trained your model on a dataset (train data here) and applied to system for coming (new) data (test data here), if there is no obs on those new data (test), the prediction failed straight away as show in the example above.  This data split is quite common on Kaggle competitions that test data is used for submit predictions.

The solution provided may not solve the question because:
1. after split the data, all levels are still existed in both train and test, however, it is after calling `createDummyFeatures` that all `factor1` levels with no obs are dropped (from `factor1`, not `num1`), hence the prediction error.  In this case the factor code provided won't work.

2. Stratified resampling doesn't work here as I cannot combine train and test together and then sampling to train / holdout as test here is not for model training purpose.

A revised example provided to make the problem clearer:
```
# dependent variable
factor1 <- sample(LETTERS,100,replace=TRUE)

# response variable
num1 <- sample(1:10,100,replace=TRUE)

# create an extreme case that all levels in train cannot be found in test
all <- data.frame(factor1,num1)
train <- subset(all,factor1 %in% LETTERS[1:13])
test <- subset(all,!factor1 %in% LETTERS[1:13])

# set the response in test to 0 given that this is the data to be predicted.
test$num1 <- 0

trtask <- makeRegrTask(data=train,target="num1")
tstask <- makeRegrTask(data=test ,target="num1")

trtask <- createDummyFeatures(trtask)
tstask <- createDummyFeatures(tstask)

mod  <- train("regr.gbm",trtask)
pred <- predict(mod,tstask)
```

**Comment by larskotthoff** [comment]
It sounds like creating dummy features is the wrong approach then :)

I guess you could manually add the missing features after running `createDummyFeatures`.

**Comment by SixiangHu** [comment]
I figured it out that I need to set both `fixup.data="no"` and `check.data=FALSE` in `makeRegrTask` to keep those 0 obs factor levels:

```
trtask <- makeRegrTask(data=train,target="num1",fixup.data ="no",check.data = FALSE)
tstask <- makeRegrTask(data=test ,target="num1",fixup.data ="no",check.data = FALSE)
```

This may cause some ML method throwing warnings (gbm: "factor1.N has no variation"), but better than nothing.

As there is a solution, I will close this issue.  Thanks for your help @larskotthoff .
