### ISSUE TITLE
Is that possible to do pipeline with multiple operation within each CV loop?

### ISSUE THREAD

**Issue by ajing** [mlr-org/mlr#1729]
For example, if I want to filter by information gain first, add 30 PCA features, then build a SVM model. How to do that in mlr?

**Comment by larskotthoff** [comment]
Use [wrappers](https://mlr-org.github.io/mlr-tutorial/devel/html/wrapper/index.html), in particular a [feature selection wrapper](https://mlr-org.github.io/mlr-tutorial/devel/html/feature_selection/index.html) and a [preprocessing wrapper](https://mlr-org.github.io/mlr-tutorial/devel/html/preproc/index.html).

**Comment by ajing** [comment]
Thanks! Does mlr support "one standard error rule" for parameter selection?

**Comment by larskotthoff** [comment]
Not out of the box, but you can implement this yourself quite easily.

**Comment by larskotthoff** [comment]
Not out of the box, but you can implement this yourself quite easily.

**Comment by ajing** [comment]
Another question..

For makeResampleDesc function:

```
makeResampleDesc(method, predict = "test", ..., stratify = FALSE,
  stratify.cols = NULL)
```

What if stratify.cols is not part of the 'data'? My understanding is that data argument in makeClassifTask() can only contain x and y. What if the column I want to stratify is not part of y or x? Should I use multi-label classification?

**Comment by Stevo15025** [comment]
> What if the column I want to stratify is not part of y or x?

This is something that was discussed in #1567 ,creating an `ignore.cols` argument for a task. It has not been implemented yet. 

>  Should I use multi-label classification?

I'm not familiar enough with multi-label to say whether this would help, I don't see directly how it would do this.

**Comment by ajing** [comment]
@larskotthoff Could you provide a little bit hint about implement "one standard error rule" for parameter selection in mlr? Using makeTuneControl?

Thanks!

**Comment by larskotthoff** [comment]
We've implemented a custom search in another package here: https://github.com/coseal/aslib-r/blob/master/server_scripts/searchSequential.R. Note how you can specify a threshold in the `compare.diff` function.
