### ISSUE TITLE
MCC returning NaN when tuning fairly imbalanced dataset. Denominator is zero.

### ISSUE THREAD

**Issue by Rodrigo61** [mlr-org/mlr#1736]
Hello folks,

I don't know if my issue report is correct, but MCC's function returns NaN if the formula's denominator  is zero. Since you are using the same formula described in this [link](https://en.wikipedia.org/wiki/Matthews_correlation_coefficient)  I thought that would be nice if you include this part:

> In this equation, TP is the number of true positives, TN the number of true negatives, FP the number of  false positives and FN the number of false negatives. If any of the four sums in the denominator is zero, the denominator can be arbitrarily set to one;

current function:
```
measureMCC = function(truth, response, negative, positive) {
  tn = as.numeric(measureTN(truth, response, negative))
  tp = as.numeric(measureTP(truth, response, positive))
  fn = as.numeric(measureFN(truth, response, negative))
  fp = as.numeric(measureFP(truth, response, positive))
  (tp * tn - fp * fn) /
    sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
```

my suggestion:
```
measureMCC = function(truth, response, negative, positive) {
  tn = as.numeric(measureTN(truth, response, negative))
  tp = as.numeric(measureTP(truth, response, positive))
  fn = as.numeric(measureFN(truth, response, negative))
  fp = as.numeric(measureFP(truth, response, positive))
  
  denominator = as.numeric(sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)))
  if(denominator == 0){
    denominator = 1
  }
  
  (tp * tn - fp * fn) / denominator
}
```

Thank you ;D

**Comment by larskotthoff** [comment]
Hmm, so the only case in which this occurs is if a lot of things are 0, e.g. there are 0 observations. Did you actually encounter this in practice? This edge case seems very unlikely to me.

**Comment by Rodrigo61** [comment]
It happens when you have a fairly imbalanced dataset. My study uses imbalanced datasets with 5%, 3%, 1% and 0.1% of relative rarity. So, I had to modified the function like above to use MCC. Perhaps I shouldn't use MCC for so imbalanced datasets.

**Comment by larskotthoff** [comment]
It sounds like another measure would be more appropriate -- especially with the correction you propose you may get misleading results. For example, with tp = 100, tn = 1, fp = 0, fn = 0 the value would be 100.

**Comment by Rodrigo61** [comment]
Actually in your example the value would be 1. I think that the denominator can be arbitrarily set to any value, because whenever you get a zero value for denominator you'll also get a zero for numerator.

We can prove this with a truth table:

proposition: [**(TP ^ FP) v (TP ^ FN) v (TN ^ FP) v (TN ^ FN )] --> zero for denominator**.
where TP, FP, FN and TN are equal to 1 when they are zero. (i.e TP = 1 when we have 0 True Positives. Little confusing, sorry :P)

This expression is equal to 1 when:

TP = 0 ^ FP = 0 ^ TN = 1 ^ FN = 1 --> numerator = 0 (without negative observations)
TP = 0 ^ FP = 1 ^ TN = 1 ^ FN = 0 --> numerator = 0 (predict all positive)
TP = 0 ^ FP = 1 ^ TN = 1 ^ FN = 1 --> numerator = 0 (without negative observations)
TP = 1 ^ FP = 0 ^ TN = 0 ^ FN = 1 --> numerator = 0 (predict all negative)
TP = 1 ^ FP = 0 ^ TN = 1 ^ FN = 1 --> numerator = 0 (without negative observations)
TP = 1 ^ FP = 1 ^ TN = 0 ^ FN = 0 --> numerator = 0 (without positive observations)
TP = 1 ^ FP = 1 ^ TN = 0 ^ FN = 1 --> numerator = 0 (without positive observations)
TP = 1 ^ FP = 1 ^ TN = 1 ^ FN = 0 --> numerator = 0 (without positive observations)
TP = 1 ^ FP = 1 ^ TN = 1 ^ FN = 1 --> numerator = 0 (no observations)

So, in all that cases we have numerator = denominator = 0 and makes sense to me return MCC's value = 0. Because our model isn't better than a random predict.

**Comment by larskotthoff** [comment]
Ah sorry, yes, I missed the "rate" part. Still, a value of 1 in this case would be misleading, wouldn't it? Especially if you're tuning and want to maximise the value.

It sounds like you're proposing to set the value for MCC to 0 if the denominator is 0? That would probably make more sense.

**Comment by Rodrigo61** [comment]
I don't see why it would be misleading. In your example you predict right all the examples, so make sense to me make MCC's value =  1 (Perfect predict model).

> It sounds like you're proposing to set the value for MCC to 0 if the denominator is 0? That would probably make more sense.

Yes, that is what I suggest with my truth table explanation. Sorry if it's confusing.

**Comment by larskotthoff** [comment]
My point is that the "perfect" model may be perfect by virtue of the data, not by virtue of the model.

So what do you propose we implement?

**Comment by Rodrigo61** [comment]
I agree, that's why imbalancing training is so hard to study. We don't have perfect measures to evaluate. But I think that is out of scope. Your example is a common case of MCC (i.e. denominator != 0), so if it would be a misleading is problem of MCC's formula.

I still suggest this code, because it's works as I explained and it's easier for understand since uses this [link](https://en.wikipedia.org/wiki/Matthews_correlation_coefficient) as reference.
```
measureMCC = function(truth, response, negative, positive) {
  tn = as.numeric(measureTN(truth, response, negative))
  tp = as.numeric(measureTP(truth, response, positive))
  fn = as.numeric(measureFN(truth, response, negative))
  fp = as.numeric(measureFP(truth, response, positive))
  
  denominator = as.numeric(sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)))
  if(denominator == 0){
    denominator = 1
  }
  
  (tp * tn - fp * fn) / denominator
}
```
But if you think that is more clear you can just return 0, like this:
```
measureMCC = function(truth, response, negative, positive) {
  tn = as.numeric(measureTN(truth, response, negative))
  tp = as.numeric(measureTP(truth, response, positive))
  fn = as.numeric(measureFN(truth, response, negative))
  fp = as.numeric(measureFP(truth, response, positive))
  
  denominator = as.numeric(sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)))
  if(denominator == 0){
    result = 0
  }else{
    result = (tp * tn - fp * fn) / denominator
  }

  result
}
```

Both codes should work :D

**Comment by larskotthoff** [comment]
Ok, I've made a PR for that in #1739.
