### ISSUE TITLE
Cannot load mlr since lintr commit

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#1737]
This is the error I get:
```r
> library(devtools)
> load_all()
Loading mlr
Loading required package: ParamHelpers

Attaching package: ‘lintr’

The following object is masked from ‘package:devtools’:

    lint

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
  object 'T_and_F_symbol_linter' not found
```

**Comment by mb706** [comment]
This is because mlr uses the github version of lintr, which has some 
useful additions beyond the CRAN version, and handles commas correctly. 
Install it with `devtools::install_github("jimhester/lintr")`.

Maybe the test could contain a version check and throw a more meaningful 
error message. Setting 'suggests' to the lintr version on github 
unfortunately doesn't help.

**Comment by mllg** [comment]
I'd suggest to move all stuff in `helper_linters.R` into functions so that we do not get errors during loading the package (yes, for some reasons all files matching `tests/testthat/helper*` are sourced in `devtools::load_all()`). 
The test should be skipped if the version requirements are not met and the namespace of `lintr' should not be attached (if possible).

**Comment by mb706** [comment]
> for some reasons all files matching `tests/testthat/helper*` are sourced in `devtools::load_all()`
no words

> The test should be skipped if the version requirements are not met and the namespace of `lintr' should not be attached (if possible).
should make sure that Travis still gives an error (and doesnt silently stop linting) if for some reason it failed to load lintr

**Comment by berndbischl** [comment]
> for some reasons all files matching `tests/testthat/helper*` are sourced in `devtools::load_all()`
> no words

yes, this is a problem. you should ALL be aware of this. they changed this in devtools about a year ago. IIRC i also complained in their tracker about this, or at least asked. @larskotthoff @mllg @jakob-r @ja-thomas @giuseppec

**Comment by berndbischl** [comment]
@mllg @mb706 @larskotthoff 
can we please fix thix NOW? this kinda completely breaks the master branch. please never do that.

**Comment by mb706** [comment]
PR #1741 doesn't help?

**Comment by mb706** [comment]
Apparently it solved only half the problem, but now it should work.
