### ISSUE TITLE
add reference for MCC change

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1746]
@larskotthoff 
if you merge stuff like in PR #1736, please add the reference, preferably in the docs. 
if you dont do this, nobody will later understand WHY we did that

**Comment by berndbischl** [comment]
https://github.com/mlr-org/mlr/pull/1739

**Comment by larskotthoff** [comment]
Well, the reference is Wikipedia, which says that it can be set arbitrarily :P What exactly do you want me to add there?

There is a reference to the issue in the test.

**Comment by berndbischl** [comment]
> Well, the reference is Wikipedia, which says that it can be set arbitrarily :P

then add exactly that. at least as a comment in the code
maybe with a sentence about the justification

**Comment by berndbischl** [comment]
if somebody reads that code in 12 months one has zero change to distinguish between

a) an inexperienced guy wrote a pretty arbitrary code line here - which is dubious and weird
b) somebody put some good and proper thought into this (and if so, one usually likes to read the result of that thought, or a link to the explanation)

**Comment by berndbischl** [comment]
thx
