### ISSUE TITLE
getFeatureImportance should return a data.frame in long table format

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#1755]
```r
lrn = makeLearner("classif.xgboost")
mod = train(lrn, iris.task)
imp.xgb = getFeatureImportance(mod)
imp.xgb$data
```
Data is a data.frame with one row. You cannot sort conveniently over columns, and cannot plot it with ggplot. Is there a reason why this is not in the long table format with columns "column" and "importance" ?

**Comment by jakob-r** [comment]
You mean `$res` right?

**Comment by mllg** [comment]
Whoops. Yep.

**Comment by berndbischl** [comment]
well this is also wrong

#' @return [\code{FeatureImportance}] An object containing a \code{data.frame} of the variable importances and further information.

it should be 
a) code-link
b) the s3 class should be documented. with ALL slots not "some further info"

regarding the question


> Data is a data.frame with one row. You cannot sort conveniently over columns, and cannot plot it with ggplot. Is there a reason why this is not in the long table format with columns "column" and "importance" ?

this should be a numerical vector? that seems to be the most natural format
why convert it to a df?

also why is this implicitly done?
  #convert named vector to data.frame with columns and set NA to 0

this is not even documented?

**Comment by jakob-r** [comment]
It is documented in `generateFeatureImportance.R`:

```r
#' @return [\code{FeatureImportance}]. A named list which contains the computed feature importance and the input arguments.
#'
#' Object members:
#' \item{res}{[\code{numeric}]\cr
#'   Has columns for each feature or combination of features (colon separated) for which the importance is computed.
#'   A row coresponds to importance of the feature specified in the column for the target.
#' }
```

But to be honest I have problems understanding the meaning of the last sentence. Is it about multitask problems?

**Comment by pat-s** [comment]
I just came across this.

Adding a `tidyr::gather(imp.xgb$res, "column", "importance")` would solve @mllg issue here. Should we implement this within the function?

> this should be a numerical vector? that seems to be the most natural format
> why convert it to a df?

because there needs to be a relation between the feat.imp and the feature. Or did I get you wrong here?
