### ISSUE TITLE
How to obtain cross-validated predictions from tuneParams()?

### ISSUE THREAD

**Issue by suraggupta** [mlr-org/mlr#1757]
Whenever we do hyper-parameter tuning for a learner, is there a method to obtain the predictions for each of the folds? This could come in handy for making custom stacked models. Please let me know if I'm missing something here.

**Comment by larskotthoff** [comment]
Yes, you can use `getRRPredictions()`. See [the tutorial](https://mlr-org.github.io/mlr-tutorial/devel/html/resample/index.html).
