### ISSUE TITLE
Reference for sffs

### ISSUE THREAD

**Issue by kerschke** [mlr-org/mlr#1759]
Within the documentation of the feature selection strategies, the sequential floating forward/backward search strategies are described as follows:

- `sffs` Sequential Floating Forward Search: Starting from an empty model, in each step the algorithm chooses the best model from all models with one additional feature and from all models with one feature less.
- `sfbs` Sequential Floating Backward Search: Similar to sffs but starting with a full model.

As far as I can tell, this is exactly what the implemented approaches do. However, when looking for a reference of sffs and/or sfbs, most of the papers I found (if not all) basically refer to _"Pudil, P., Novovicova, J., and Kittler, J. (1994). Floating search methods in feature selection.
Pattern recognition letters, 15(11):1119–1125"_ and unfortunately, they describe these two strategies slightly different. For instance, in case of the sffs, they do not just try to remove one feature per iteration, but instead keep trying to remove features from the current set as long as the model improves - and then go to the next iteration.

Does anybody of you have a reference for the approach implemented in `mlr`? Unfortunately, the reference given in `?makeFeatSelControlSequential`, i.e. _"Kohavi, R., and John, G.H. (1997). Wrappers for feature subset selection. Artificial Intelligence Volume 97:273-324. [http://ai.stanford.edu/~ronnyk/wrappersPrint.pdf](http://ai.stanford.edu/~ronnyk/wrappersPrint.pdf)"_ does not refer to the floating approach at all.

**Comment by berndbischl** [comment]
hi, it seems that docs can be improved here.

1) the pudil ref is the correct ref for the floating type of search algos

2) maybe the mlr doc is even a bit imprecise. the method first does the normal step, (so f or b), and then that either succeeds, or fails. in both cases an "opposite" step is tried, so for sffs we now try to remove one feature again.
