### ISSUE TITLE
Is that possible to get the prediction score for each sample in tuneParam?

### ISSUE THREAD

**Issue by ajing** [mlr-org/mlr#1760]
TuneResult only returns the evaluation metrics for the hyperparameter set.

Is that possible to get a more detailed profile for the sample level prediction for each hyperparameter?

**Comment by berndbischl** [comment]
i am not sure i understand exactly what you want?

**Comment by berndbischl** [comment]
the predictions object for the best hyperparam config?

the prediction object for each hyperparam config? 

something else?

**Comment by ajing** [comment]
Like the "pred" attribute in "ResampleResult"

```R
> head(pred_res)
   id truth    prob.B      prob.M response iter  set
1  19     B 0.9801872 0.019812824        B    1 test
2  28     B 0.9989415 0.001058538        B    1 test
3 156     B 0.9688464 0.031153619        B    1 test
4 183     B 0.9984488 0.001551157        B    1 test
5 204     B 0.9988995 0.001100477        B    1 test
6 230     B 0.9673841 0.032615868        B    1 test
```

**Comment by berndbischl** [comment]
just for the best config? or for all? 

the answer is in both cases: "no, not automatically". but not hard to obtain yourself.

also do you run tuneParams or the TuneWrapper?

**Comment by ajing** [comment]
The way I currently do is getting the best parameter by "tuneParams" then do "resample" to get the prediction for each sample. But, I feel it may be a little bit overfitting. I think it's better to do TuneWrapper.

**Comment by berndbischl** [comment]
well, yes, you should do nested reampling. bit now you are dodging the question.

its like this:

if you run tuneParams and want the Prediction object of the best config, just take the "x" slot of the TuneResult, call setHyperPars, and resample

if you want the Prediction object from the *outer* loop of nested resampling, the TuneWrapper will simply produce that if you resample it

If you want something else please tell me *precisely* what you want, with more than a short oneliner

**Comment by ajing** [comment]
Thanks!

**Comment by berndbischl** [comment]
i also opened this #1764
