### ISSUE TITLE
How to avoid parameter name conflict for multiple makeFilterWrapper?

### ISSUE THREAD

**Issue by ajing** [mlr-org/mlr#1762]
If I do more than one filter wrapper, I will get a name clash error. Is there any way to avoid that?

```R
  model_prob <- makeLearner("classif.svm", predict.type = "prob")
  model_fltr1 <- makeFilterWrapper(model_prob, fw.method = "kruskal.test")
  model_fltr2 <- makeFilterWrapper(model_fltr1, fw.method = "anova.test", fw.abs = 3)
```

**Comment by berndbischl** [comment]
No not really. May I ask why you are trying to do that?

**Comment by ajing** [comment]
I have a classification problem with less than 500 samples and more than 2K features. Features are highly correlated and I wrote a preprocess wrapper to remove redundant features based on the correlation matrix. But, my redundant-removing wrapper is slow for a large feature set, so the goal of my first wrapper is filtering features with little information. The goal for the second filter is to control the number of features feeding to the core learner (e.g. SVM).

I think I can write another preprocess wrapper to accommodate.

**Comment by berndbischl** [comment]
Is your goal to obtain a feature set which simultanously

a) has a low redundancy, so low correlation in the set
b) a high "correlation" with y, so features contain information about y?

because that is MRMR and mlr supports that as a single filter.....

https://en.wikipedia.org/wiki/Feature_selection#Minimum-redundancy-maximum-relevance_.28mRMR.29_feature_selection

https://mlr-org.github.io/mlr-tutorial/devel/html/filter_methods/index.html

**Comment by ajing** [comment]
Thanks, Bernd! I tried MRMR, but it doesn't support classification.

**Comment by berndbischl** [comment]
> Thanks, Bernd! I tried MRMR, but it doesn't support classification.

but it is still what you want, concept-wise, if it would work?

**Comment by ajing** [comment]
> but it is still what you want, concept-wise, if it would work?

Yes, that's what I want.

**Comment by berndbischl** [comment]
the think is that package mrme CLAIMS that they can handle classification as well. 

I know we tried that and saw some problems. which is why we removed the property from the filter. we could check again to reenable this?

**Comment by ajing** [comment]
Yes, that would be great! I'd be happy to help in anyway I can.

**Comment by berndbischl** [comment]
ok, first read this. this issue was the reason we removed classification. read it properly

https://github.com/mlr-org/mlr/issues/940

**Comment by berndbischl** [comment]
the docs of mrmre still say this

```
The correlate function could be used to measure correlation between any types of variables:
numeric vs. numeric Pearson, Spearman, Kendall or concordance index
numeric vs. ordered factor concordance index (Somers’ Dxy)
numeric vs. survival data concordance index (Somers’ Dxy)
ordered factor vs. ordered factor Carmer’s V
ordered factor vs. survival data concordance index (Somers’ Dxy)
survival data vs. survival data concordance index (Somers’ Dxy)
Part of the code underlying correlate is also used in mim method of the mRMRe.Data object because
correlations are used to build the mutual information matrix in order for feature selection to take
place. This is why these two functions have many argiuments in common
```

for me this stills reads as if they dont support (unordered) categorical features, neither in x or y.

**Comment by berndbischl** [comment]
@smilesun would you be willing to help with this?

**Comment by ajing** [comment]
> ok, first read this. this issue was the reason we removed classification. read it properly
> #940

It sounds like that mrmr is not suitable for classification.

**Comment by berndbischl** [comment]
> It sounds like that mrmr is not suitable for classification.

thats untrue, it is just that they implemented it that way in mrmre that ways (which seems weird?)

i started to look at feast, and that supports classification

**Comment by ajing** [comment]
> thats untrue, it is just that they implemented it that way in mrmre that ways (which seems weird?)

Yes, I mean the package mRMRe doesn't support classification. I am also looking at feast.

There is an R package interface:
https://github.com/mbq/praznik

**Comment by berndbischl** [comment]
@ajing hmm i never googled those two! thanks! i asked about the status of the projects in their trackers. but both stopped in aug 2016?

**Comment by ajing** [comment]
> @ajing hmm i never googled those two! thanks! i asked about the status of the projects in their trackers. but both stopped in aug 2016?

Yes, no update after. Probably, we can adapt it.

**Comment by berndbischl** [comment]
> Yes, no update after. Probably, we can adapt it.

would you help with that?

**Comment by ajing** [comment]
> would you help with that?

Sure. But, I don't have much experience on R’s C interface. And, I may also need some guidance on the expected API.

**Comment by pat-s** [comment]
Praznik filter are integrated since v2.14.0, closing.
