### ISSUE TITLE
survival predict at new time with surv.ranger

### ISSUE THREAD

**Issue by katsumiyokota** [mlr-org/mlr#1768]
I'm not very familiar with mlr's version of surv.ranger. Is it possible to predict out the response by time similar to the following?

```
predictSurvProb.ranger <- function(object, newdata, times, ...) {
  pred <- predict(object, newdata)
  pos <- sapply(times, function(x) {
    max(c(0, which(x >= pred$unique.death.times)))
  })    
  p <- cbind(1, predictions(pred))[, pos+1, drop = FALSE]
  return(p)
}
```

**Comment by PhilippPro** [comment]
Can you please post a reproducible example of what you want to predict?
I think it is not possible with the current implementation. 

A usual workflow for survival tasks in mlr is like that:
```
library(mlr)
wpbc.task
lrn = makeLearner("surv.ranger")
mod = train(lrn, wpbc.task, subset = 1:150)
pred = predict(mod, newdata = getTaskData(wpbc.task, subset = 151:190))
pred
pred$data$response
```
This gives you the mean of the estimated cumulative hazard function.
