### ISSUE TITLE
Use a LICENCE File that reflects the licence in the DESCRIPTION

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1771]
This way the licence will also be directly visible to git like in this example:

![licence indicator](https://help.github.com/assets/images/help/repository/repo-license-indicator.png)

**Comment by berndbischl** [comment]
i have no idea what i should do here?

**Comment by giuseppec** [comment]
Are you sure that copy and pasting the content from https://opensource.org/licenses/BSD-2-Clause to the LICENSE file is allowed on CRAN? 
I did this for [OpenML](https://github.com/openml/openml-r/blob/master/LICENSE) with the BSD-3-Clause and got an email from CRAN that the LICENSE should contain only the fields `YEAR`, `COPYRIGHT HOLDER` and `ORGANIZATION` as described in https://cran.r-project.org/web/licenses/ (the licenses there do not 100% match with the ones listed in https://opensource.org/licenses).
From the CRAN link above, you can see that the LICENSE file should contain only the fields `YEAR` and `COPYRIGHT HOLDER`  in case of BSD-2-Clause.

**Comment by berndbischl** [comment]
@jakob-r

**Comment by jakob-r** [comment]
Yeah. I was not aware of that when I opened the issue but run into the same problem for `mlrMBO`. I am okay to revert to CRAN standards but for `mlrMBO` I added an option in [rt](https://github.com/rdatsci/rt) and can now call `rbuild --cran.license`.

**Comment by berndbischl** [comment]
and i would suggest to do the same in other projects. we already have a very complex build process. 
and I mean: the LIC is mainly for cran. what the advantage to have something nonstandard in here, then convert it before release?

**Comment by berndbischl** [comment]
thx @jakob-r
