### ISSUE TITLE
predict() returning probabilities > 1

### ISSUE THREAD

**Issue by efh0888** [mlr-org/mlr#1773]
I'm using caret to build a random forest model (with method = "ranger") and to make predictions.  Strangely, I am getting some predictions that print as 0/1 but in fact are greater than 1.  I used ranger() directly (using the training data and tuned mtry value from caret) and get the same results, so the issue must be in ranger.

I'm working with highly sensitive data, and frankly don't have any clue how I can create another random forest model with the same issue on different data.  If you have any suggestions I'll gladly give it a shot.  But the best I can do at this point is describe what I did (fairly straightforward and probably won't help at all) and attach the portion of the affected predictions as a zipped RDS object.

```
set.seed(456)
rfModel <- ranger(TARGET ~ ., data = train, probability = TRUE, mtry = 2)
probs <- data.frame(predict(rfModel, test)$predictions)
sum(probs[,2] > 1)  # 161
```

[probs_greater_than_1.zip](https://github.com/mlr-org/mlr/files/914227/probs_greater_than_1.zip)

**Comment by giuseppec** [comment]
Hi,

> I used ranger() directly (using the training data and tuned mtry value from caret) and get the same results, so the issue must be in ranger.

You should then post this issue here https://github.com/imbs-hl/ranger/issues or on stackoverflow https://stackoverflow.com/questions/tagged/ranger.
I will close this here as I don't see any `mlr` related issue/question.

An alternative would be to use the `randomForest` package instead of `ranger`.

**Comment by berndbischl** [comment]
@giuseppec is correct

but: the related mlr issue is to try to unit test against this as much as possible.
we are already working on that, but we basically now do bug detection for other packages / authors....

see here eg  #1017

**Comment by giuseppec** [comment]
@efh0888 if you could reproduce the same bug with different (e.g. simulated) data and post a fully reproducible minimal example (+ the simulated data), this would help. Otherwise, we basically can't really help (unfortunately).

**Comment by efh0888** [comment]
Sorry guys, not sure what the heck happened, could have sworn I was on the ranger github repo, so don't know how I ended up here haha... @giuseppec I'll post in the correct repo and see what they say...
