### ISSUE TITLE
Not able to find appropriate method of predict of class "xgb.booster"

### ISSUE THREAD

**Issue by Ishant1589** [mlr-org/mlr#1780]
Hi,

I am using MLR to tune XGB parameters. I am able to run XGboost directly on the data after converting the data into the required format, but using xgboost I am getting an error that - no applicable method of predict was found for class "xgb.booster"

Below is the code I am using:
```
lrn <- makeLearner("classif.xgboost",predict.type = "response")
lrn$par.vals <- list( objective="binary:logistic", eval_metric="error", nrounds=100L, eta=0.1)

params <- makeParamSet( 
  makeDiscreteParam("booster",values = c("gbtree","gblinear")), 
  makeIntegerParam("max_depth",lower = 5L,upper = 8L), 
  makeNumericParam("min_child_weight",lower = 1L,upper = 10L), 
  makeNumericParam("subsample",lower = 0.5,upper = 1), 
  makeNumericParam("colsample_bytree",lower = 0.5,upper = 1))

rdesc <- makeResampleDesc("CV",stratify = T,iters=5L)

ctrl <- makeTuneControlRandom(maxit = 4L)

library(parallel)
library(parallelMap)
parallelStartSocket(cpus = detectCores())

mytune <- tuneParams(learner = lrn, 
                     task = traintask, 
                     resampling = rdesc, 
                     measures = acc, 
                     par.set = params, 
                     control = ctrl,
                     show.info = T)

```

I am getting the error while running the last piece of code i.e. 
```
mytune <- tuneParams(learner = lrn, 
                     task = traintask, 
                     resampling = rdesc, 
                     measures = acc, 
                     par.set = params, 
                     control = ctrl,
                     show.info = T)
```
For all the four iterations I am getting the same error, which is mentioned below:
![image](https://cloud.githubusercontent.com/assets/16971666/25189487/ef387676-2546-11e7-9806-0109d348a7fc.png)

Any help would be appreciated :)

**Comment by ja-thomas** [comment]
Did you update xgboost to the latest version?

**Comment by Ishant1589** [comment]
I have downloaded the version from cran

**Comment by Ishant1589** [comment]
Hi @ja-thomas, thanks for your help. After reinstalling both the packages the code is working fine.
Thanks again.

**Comment by Priyanka11g** [comment]
predict is working on local server but getting the error "Not able to find appropriate method of predict of class "xgb.booster" when published on web using shiny.io
