### ISSUE TITLE
Tasks can't accept logical predictor variables?

### ISSUE THREAD

**Issue by Prometheus77** [mlr-org/mlr#1786]
I'm new to MLR but already see the potential to the point where I want to rewrite my ensembling code to take advantage of all of its great features. The first time I went to create a binary classification task, it threw an error because some of the predictor columns were logical. Am I doing something wrong, or is MLR really unable to take logical variables? If so, shouldn't there be a default behavior to force to 1/0 numerical rather than stopping execution?

**Comment by Stevo15025** [comment]
> I'm new to MLR but already see the potential to the point where I want to rewrite my ensembling code to take advantage of all of its great features.

We are glad to have you!

> The first time I went to create a binary classification task, it threw an error because some of the predictor columns were logical. 

What was the error?

>Am I doing something wrong, or is MLR really unable to take logical variables?

Looking through `train` and `makeClassifTask` I don't see anything that explicitly stops you from using a logical. It's most likely that the underlying package does not accept logicals.

> If so, shouldn't there be a default behavior to force to 1/0 numerical rather than stopping execution?

I suppose we could do something similar to [fixup.data](https://github.com/mlr-org/mlr/blob/master/R/ClassifTask.R#L14) in `ClassifTask` but for every variable.

**Comment by larskotthoff** [comment]
Can you provide a complete example that allows to reproduce the problem please?

**Comment by Prometheus77** [comment]
My bad. Here is the code to reproduce:
> df <- data.frame(x1=(runif(5)>0.5),x2=runif(5),y=as.factor(sample(c(1,2),size=5,replace=TRUE)))
> cltask <- makeClassifTask(data=df,target="y")
Error in (function (cn, x)  : 
  Unsupported feature type (logical) in column 'x1'.
>

**Comment by larskotthoff** [comment]
Right, logical features aren't allowed by the `checkTaskData` function. I suspect like @Stevo15025 that some of the learners have problems with that (maybe @berndbischl or @mllg can clarify).

The problem with doing an implicit conversion is that we might create something that the user doesn't expect -- it's only a single line of code to do this conversion explicitly yourself.

I agree that we could offer an option for this though.

**Comment by Prometheus77** [comment]
Makes sense. If it's not optimal to auto-convert, some other ideas would be:
1) Warn the user that some classifiers can't use logical (can even build a property of learners that can be accessed by listLearners that states whether it can accept logical inputs)
2) Offer a parameter that converts logical to numeric or factor, even if the default is to turn it off

It just feels like throwing an error here is not in keeping with the idea of mlr being able to do a lot of the preprocessing for you. I can easily get around it, but my guess is that I'm not the only user that will hit this roadblock.

Thanks for all you do, looking forward to diving deeper into this awesome package.

-P

**Comment by Prometheus77** [comment]
FYI, let me know what the dev team decides to do on this (e.g. nothing, warnings, auto-conversion option, etc.). If nothing, I'll go ahead and close the issue.

**Comment by jakob-r** [comment]
I am a bit undecided if we want some auto conversion. On the upside: Having a logical target would directly translate to a positive value for the task description and to correct calculation of some measures like the TPR etc.
