### ISSUE TITLE
setHyperPars doesn't set the cutoff of randomForest

### ISSUE THREAD

**Issue by tobiaswagner** [mlr-org/mlr#1798]
I execute the following code:

```
lrn = makeLearner("classif.randomForest", predict.type = "prob")
lrn = makeOversampleWrapper(lrn)
lrn = setHyperPars(lrn, cutoff=c(0.1, 1-0.9))
rdesc = makeResampleDesc("CV", iters = sum(DB$FailureClass=="Verkleben"), stratify = TRUE)
res = resample(learner = lrn, task = task, resampling = rdesc, measures = list(fpr,tpr), show.info = F)
print(res.pred)
```

I get the following output:

```
Resampled Prediction for:
Resample description: cross-validation with 9 iterations.
Predict: test
Stratification: TRUE
predict.type: prob
threshold: NoFailure=0.50,Failure=0.50
```

My question: Why are the cutoff values not transferred to the validation?

**Comment by larskotthoff** [comment]
The hyperparameter you're setting for the random forest is different to the threshold. The hyperparameters of the learner are not shown when you print the resample predictions. The threshold you see in this output is completely independent and separate from the learner hyperparameters -- see [the tutorial](https://mlr-org.github.io/mlr-tutorial/devel/html/predict/index.html#classification-adjusting-the-decision-threshold) for information about that.

**Comment by berndbischl** [comment]
a few comments:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
1) it is good that you are trying to post minimal reproducible code.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
you succeeded in "minimal" but not 100% in "reproducible".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
pls try to use public data fot stuff like this, when ever possible, so we can reproduce.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 eg the mlr toy tasks ike iris.task, sonar.task are perfect for this.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 2) "you are doing it wrong":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 yes, you should be able to set the "cutoff" param of the rf.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 but please note that mlr has a better (ie generic) mechanism for this.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
 use setThreshold and tuneThreshold. and note the tune.threshold flag in every TuneControl.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 3) it is also clear now that your print output looks "weird", I mean this                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 >>>>threshold: NoFailure=0.50,Failure=0.50#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
this is technically correct, as the mlr threshold you have not changed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
you have changed the rf "cutoff".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 now what happens.:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 the rf prduces its output, you have requested "prob"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 the rf WOULD convert them into classes (if you would have requested predict.type = "response"), 
but mlr does this, with mlr's generic threshold.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 (which you are not using, see 2))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 effectively this means "cutoff" is never used in your code                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
4) also note that you are even using weird values for "cutoff".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 you use 0.1 for both classes this is basically the same as leaving the cutoff out,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 as this means to weight both classes equally when converting probs to classes.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 (i have changed that in my code below)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
5) what are your options:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             a) use setThreshold                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
```                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 task = sonar.task                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 lrn1 = makeLearner("classif.randomForest", predict.type = "prob")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 lrn2 = makeOversampleWrapper(lrn1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 r = resample(learner = lrn2, task = task, resampling = hout, measures = list(fpr,tpr), show.info = F)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 print(r$pred)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
print(calculateConfusionMatrix(r$pred))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 pred2 = setThreshold(r$pred, 0.99)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 print(pred2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 print(calculateConfusionMatrix(pred2))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
```                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
b) (less good IMHO): use cutoff, but do not request "probs" in makeLearner                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
```                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 task = sonar.task                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 lrn1 = makeLearner("classif.randomForest")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 lrn2 = makeOversampleWrapper(lrn1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 r1 = resample(learner = lrn2, task = task, resampling = hout, measures = list(fpr,tpr), show.info = F)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 print(r1$pred)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 print(calculateConfusionMatrix(r1$pred))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 lrn2 = setHyperPars(lrn2, cutoff = c(0.1, 0.9))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 r2 = resample(learner = lrn2, task = task, resampling = hout, measures = list(fpr,tpr), show.info = F)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 print(r2$pred)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
print(calculateConfusionMatrix(r2$pred))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
```                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
6) what should we learn from this:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 it is a bit confusing, i have to admit.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
 the easiest fix would be to remove "cutoff" from the randomForest, and document why, so only option                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  a) remains.

**Comment by berndbischl** [comment]
we should address 6. or at least document it properly
