### ISSUE TITLE
mlr with h2o : Unexpected CURL error: Empty reply from server

### ISSUE THREAD

**Issue by caprone** [mlr-org/mlr#1799]
sometimes when try to tuning parameters, with resampling and grid search + h2o models, this error occurs:
"Error in .h2o.doSafeREST(h2oRestApiVersion = h2oRestApiVersion, urlSuffix = urlSuffix,  : 
                           Unexpected CURL error: Empty reply from server"

first I tried to increase java memory before start mlr package, but nothing...Even if the memory was not saturated.
second: i tried to start h2o before mlr and set memory size, but nothing...Even if the memory was not saturated.

win 7 - Rstudio - packages and R interpreter --> all updated
thanks

**Comment by larskotthoff** [comment]
This sounds like a bug in the h2o package. Unfortunately, there's nothing we can do about this in mlr.

**Comment by caprone** [comment]
ok, thanks

**Comment by berndbischl** [comment]
get back to us if you have more concrete info or think you can "demonstrate" that there is a problem on our side

**Comment by caprone** [comment]
ok! thanks, but almost certainly it's a h2o package 's problem. it gives me same errors also when i run h2o algorithms outside mlr. 
h2o seems very unstable, at least on my Win workstation....
