### ISSUE TITLE
a way to check correlations among trained models 

### ISSUE THREAD

**Issue by caprone** [mlr-org/mlr#1811]
HI
ther's a method to check  correllations among different models? (like modelCor in caret?)
ps. have You planned to include also the LightGBM in mlr's learners?

**Comment by jakob-r** [comment]
Hi,

1) You mean something like this?
```r
learners = makeLearners(c("classif.svm", "classif.randomForest"), predict.type = "prob")
ms = lapply(learners, function(lrn) train(learner = lrn, task = sonar.task))
ps = lapply(ms, function(m) predict(m, task = sonar.task))
ps = lapply(ps, getPredictionProbabilities)
cor(do.call(cbind, ps))
```
As we don't have a specific object for a list containing multiple models I think some custom code here is fine. Especially as this gives you full control over which correlation function you want to use and all the special cases (multiclass, no probabilites but just class predictions and so on...)

2) Regarding LightGBM - I will put it on our list of future learners. You are also welcome to make a PR if you are interested.

For the future, please open separate issues for unrelated topics.

**Comment by caprone** [comment]
Hi Jakob,
ah, ok, I thought there was a dedicated method in mlr, but of course this custom code works fine  
and is more flexible, thanks!

Sorry, the next time i'll open separate issues.
thanks again

**Comment by jakob-r** [comment]
So I will close. Feel free to reopen if something is still unclear.
