### ISSUE TITLE
predict type == response for anomaly detection with h2o Autoencoder

### ISSUE THREAD

**Issue by MinhAnhL** [mlr-org/mlr#1820]
Mini-Example
```
# prepare data for one class classification ####
set.seed(1235)
data(iris)
iris$SpeciesClass[iris$Species == "versicolor"] = "TRUE"
iris$SpeciesClass[iris$Species! = "versicolor"] = "FALSE"
iris$SpeciesClass = as.factor(iris$SpeciesClass)
iris$Species = NULL
inTrain = createDataPartition(1:nrow(iris), p = 0.6, list = FALSE)
train = iris[inTrain, ]
test = iris[setdiff(1:nrow(iris), inTrain),  ]
data = iris
```
Training the Autoencoder-model with `h2o.predict` would return predicted numeric values for the columns `Sepal.Length, Sepal.Width, Petal.Length, Petal.Width` (the reconstruction of the input, which is technically predict.type == "response", but not interesting for anomaly detection). 
```
library(h2o)
localH2O = h2o.init()
train.hex <- as.h2o(train[, -5],  destination_frame = "train.hex")

train.dl = h2o.deeplearning(x = names(train.hex), training_frame = train.hex,
  autoencoder = TRUE,
  reproducible = T,
  seed = 1234,
  hidden = c(6,5,6), epochs = 50)
h2o.autoencoder.pred = h2o.predict(train.dl, train.hex) # response
```

For Anomaly detection we can use `h2o.anomaly` instead of `h2o.predict`, which return anomaly scores.
```
h2o.autoencoder.pred.score = h2o.anomaly(train.dl, train.hex, per_feature = FALSE)
```

The only way to get TRUE/FALSE (Normal/Anomaly) is to set a threshold for the scores. There is no way to extract directly from the h2o package a binary response which indicates normal/anomaly classes.

Problem:
1. In mlr the response for  **classification** values differs if you set `predict.type == response` or `predict.type == prob` in the learner.
In the first case mlr usually **extract response** directly from the original package. 
In the second case mlr **extract the probabilities**  from the original package and construct a response from the probabilities using a default threshold (1/k) or a set threshold ` predict.threshold`, when constructing the learner. 
In the second case mlr returns probabilities **and** response

2. As seen above autoencoder for h2o **only** return **anomaly scores**, which is neither `prob` nor `response`
-> solution: create scores-> extract prob from scores with Platts method (to get predict.type = "prob") -> set threshold (to get predict.type = "response")

3. But `setThreshold()` only works for `predict.type == "prob"`. So I need to find a workaround to use `setThreshold()`-fkt,  even if `predict.type = "response`" 
-> or easy solution would be only allows `predict.type == prob` (as in this case type response will always be constructed from prob)

**Comment by berndbischl** [comment]
isnt the solution simply to do the scaling? so then we support predict.type = "prob"?

**Comment by MinhAnhL** [comment]
And how do you get predit.type = "response"? Only with an default threshold?
for the response values with flexibel threshold we need the prob values and the setThreshold-fkt (which currently only work for predict.type ="prob")
