### ISSUE TITLE
should mlr enable predict.type ="scores"

### ISSUE THREAD

**Issue by MinhAnhL** [mlr-org/mlr#1821]
In Anomaly detection most algorithm return scores instead of probabilities or binary response variables. E.g. the autoencoder from h2o package (see issue #1820).
We can turn the scores into probabilities with Platt's method.

Bernd and I already discuss a little bit about these two questions:
1. Do we need to keep the scores in case users prefer scores instead of probabilities?
2. If yes, any ideas how to do it?

**Comment by berndbischl** [comment]
this is a larger change to the core package and i would rather not do this now

**Comment by MinhAnhL** [comment]
For the Area under the Mass Volume Curve (AMV), we would need the scores.
Need to find out if probability scores with Platt scaling would still work for AMV.
https://drive.google.com/file/d/0B8Dg3PBX90KNUTg5NGNOVnFPX0hDNmJsSTcybzZMSHNPYkd3/view
