### ISSUE TITLE
add tests for the case of only having one class in prediction or truth

### ISSUE THREAD

**Issue by MinhAnhL** [mlr-org/mlr#1822]
Exspecially in oneclass classification/anomaly detection there is often the case that we only have one class in the truth column or that we only predict one class.
Usually anomaly detection is unsupervised, however there are no established measurement yet, therefore we need to use supervised measures for evaluation.

Currently supervised measures in mlr can't handle the one class case (also see Issue #1812  #1813)
-> add unit tests and enhance measurements

**Comment by berndbischl** [comment]
and why do you assign me here?

**Comment by MinhAnhL** [comment]
sorry :) , because it was in our problem.txt file. I thought I should assign you :)
