### ISSUE TITLE
thresholding for oneclass

### ISSUE THREAD

**Issue by MinhAnhL** [mlr-org/mlr#1823]
Add tests for thresholding in oneclass.
How should we set the default of the prediction threshold?

**Comment by berndbischl** [comment]
why am is assigned? i would suggest to set the treshold to a "high" value, or and document this.
do they mention something in the papers about this that introduce the calibration for onecass?

**Comment by MinhAnhL** [comment]
I thought I supposed to assign you :)
The paper suggest threshold selection using Bayesian risk model, which minimizes the overall risk associated with some cost function.
In the case of a zero-one loss function, they declare any observation whose estimated posterior prob exceeds 0.5 as an outlier.

**Comment by MinhAnhL** [comment]
One suggestion would be to do a quantile-threshold on the scores. 5% of all observations are anomalies.
