### ISSUE TITLE
mapping of cv iterations to blocking factor?

### ISSUE THREAD

**Issue by Tazinho** [mlr-org/mlr#1824]
I used 

```r
task = makeClassifTask(id = "blocking_cv",
                       data = df_model,
                       blocking = blocking_factor,
                       target = "target",
                       positive = "1")

makeResampleDesc("CV",
               iters = length(levels(blocking_factor)),
               predict = "both")

r = resample(learner = lrn, # parms = list(),
             task = task,
             resampling = rdesc,
             measures = list(mmce, auc),
             models = FALSE)
```

How can I (easily) map back the results on the chunks (`r$measures.test`, for example) to the levels of the supplied `blocking_factor`.

I assumed that the order of the iterations would be the same as the levels the blocking factor, but surprisingly the order seems to differ arbitrarily. Seems like I am missing sth. is there really no intended order?

**Comment by Tazinho** [comment]
Is the position within the blocking factor equivalent to the `id` column of `r$pred` !?

**Comment by berndbischl** [comment]
i dont precisley understand your question. can you please provide a simple fully reproducible example so we can discuss this issue by concretely looking at that?

**Comment by berndbischl** [comment]
and i am unsure whether you are maybe not "abusing" the blocking feature a bit here. 
are you simply creating your own CV folds with index sets? 
you do know that you could also directly overwrite the indices in the CV splits? and then fully know how the test set looks in each fold?
