### ISSUE TITLE
While running train() function it is showing "Error: Please use column names for `x`", what does it mean?

### ISSUE THREAD

**Issue by ParasSipani** [mlr-org/mlr#1825]
I am working on titanic dataset and for initial testing I have ignored variables with NA values and some unimportant values. I am trying to use mlr pacakge and I am not able to understand to find the problem.

`library(mlr)
library(rpart)
library(caret)
library(caTools)
library(data.table)
library(datasets)
library(mlr)``
#reading the dataset
tr<-read.csv("Titanic.csv",header = T,stringsAsFactors = F)
tr$X<-NULL
tr$Name<-NULL
tr$PClass<-as.factor(tr$PClass)
tr$Sex<-NULL
tr$SexCode<-as.factor(tr$SexCode)
tr$Age<-NULL

spl=sample.split(tr$Survived,0.7)

train<-subset(tr,spl==T)
test<-subset(tr,spl==F)

regr<-makeClassifTask(data=train,target ="Survived")

classif.lrn = makeLearner("classif.randomForest", predict.type = "prob", fix.factors.prediction = TRUE)

mod<-train(classif.lrn,regr)

#Output showing  "Error: Please use column names for `x`"

**Comment by larskotthoff** [comment]
Can you post a complete, reproducible example please (with data)?

**Comment by mb706** [comment]
Does it make a difference if you call `mlr::train(classif.lrn, regr)`? Both `caret` and `mlr` seem to have a function `train`, and in fact, when I load the libraries in the order you did, I get the message
```
The following object is masked from ‘package:mlr’:

    train
```

**Comment by hpoorbagher** [comment]
Hi there,
I had the same problem with logistic regression and the following code (x was  par, y was class):

lrFull <- train(mydata$par, mydata$class,
 			data = mydata, 
			method = "glm",
			metric = "ROC",	
			family = binomial,
 			trControl = ctrl) 
ctrl <- trainControl(method = "LGOCV",
summaryFunction = twoClassSummary,
classProbs = TRUE,
savePredictions = TRUE)

I tried various changes to the code such but **none worked**, for example:
train(x = par, y =  class, ....
Or  train(par, mydata$class, ...

**solution:**
1) I changed the "class" variable from 0, 1  to "no", "yes"
2) I changed the code as : 
train(class ~ par, ...      Note that I did not use mydata$class or mydata$par etc)

**Comment by larskotthoff** [comment]
I can't reproduce this. Please post a *complete* example that allows to reproduce the problem.

**Comment by hpoorbagher** [comment]
Here, I have put an example. The dataset is called example. The number of data is low and we may not get a good result but some warnings from R. Anyway, I just wanted to show how to solve the problem with the error "Please use column names for x"

  R>      example

     par class
1  33.28    no
2  33.60    no
3  33.48    no
4  32.43    no
5  33.32    no
6  29.35   yes
7  32.53   yes
8  33.06   yes
9  29.28   yes
10 29.61   yes

### THE CODE IS HERE

lrFull <- train(class ~ par,
      data = example,
     method = "glm",
     metric = "ROC",
     family = binomial,
     trControl = ctrl)

ctrl <- trainControl(method = "LGOCV",
    summaryFunction = twoClassSummary,
    classProbs = TRUE,
    savePredictions = TRUE)

### RESULTS ARE HERE

R> lrFull
Generalized Linear Model 

10 samples
 1 predictor
 2 classes: 'no', 'yes' 

No pre-processing
Resampling: Repeated Train/Test Splits Estimated (25 reps, 75%) 
Summary of sample sizes: 8, 8, 8, 8, 8, 8, ... 
Resampling results:

  ROC   Sens  Spec
  0.94  0.88  0.72

**Comment by larskotthoff** [comment]
The following code works fine for me:

```
library(mlr)

df = data.frame(par = c(33.28, 33.60, 33.48, 32.43, 33.32, 29.35, 32.53, 33.06, 29.28, 29.61),
    class = factor(c(0, 0, 0, 0, 0, 1, 1, 1, 1, 1)))
tsk = makeClassifTask(id = "foo", data = df, target = "class")
mod = train(makeLearner("classif.randomForest"), tsk)
```

I'm closing this. If you have a complete example that demonstrates a problem with mlr, please reopen.

**Comment by jzzcutler** [comment]
I had this same problem.  The fix was to use mlr::train

**Comment by sanjayssane** [comment]
You might have also loaded package caret, due to which the caret::train() is getting called. On replacing the function call to AMORE::train() [or in your context yourpackagename::train() ] my code got executed.

**Comment by louis-vines** [comment]
Just to wade in here: I was having the same issue and it was definitely due to a name clash with `caret::train()`, either call `mlr::train()` or, probably better, if using mlr make sure to load it after caret so that mlr functions take precedent.

**Comment by mb706** [comment]
The problem of `caret` shadowing `mlr`'s `train` seems to be quite common, and although the `mlr::train` workaround exists, this is probably putting some burden on users who are not that familiar with `R`.

The `caret` people were nice enough to have `train` be an S3 method. I suggest to also turn `mlr`'s `train` into an S3 method and implement `train.character` and `train.learner`.

Alternatively, some trickery with `onAttach` hooks:
```R
setHook(packageEvent("caret", "attach"), function(...) {
    detach("ackage:mlr")
    attachNamespace("mlr")
  })
```
will prevent `caret` from shadowing `mlr`. (This is obviously good for nothing except showcasing cleverness; S3 is the way to go imho).
