### ISSUE TITLE
Partial depend. plots with plotHyperParsEffect: x-axis does not show used parameter values

### ISSUE THREAD

**Issue by VGalata** [mlr-org/mlr#1830]
Hello!

I am not sure whether this is a bug or is intended to be this way but `plotHyperParsEffect` does not use/plot the correct parameter values for the partial dependency plots if these were not created using `seq(min, max, length.out)` or in an analogous manner. If I am not mistaken the "problem" is `generateFeatureGrid` in `generatePartialDependenceData` called by `plotHyperParsEffect`.

Minimal example (modified example from the [tutorial](http://mlr-org.github.io/mlr-tutorial/release/html/hyperpar_tuning_effects/index.html#visualizing-the-effects-of-more-than-2-hyperparameters))
```
ps = makeParamSet(
  makeDiscreteParam("C", values=2^c(-10,-5,-1,0,1,5,10)),
  makeNumericParam("sigma", lower = -5, upper = 5, trafo = function(x) 2^x),
  makeDiscreteParam("degree", values = 2:5)
)
ctrl = makeTuneControlRandom(maxit = 100L)
rdesc = makeResampleDesc("Holdout", predict = "both")
learn = makeLearner("classif.ksvm", par.vals = list(kernel = "besseldot"))
res = tuneParams(learn, task = pid.task, control = ctrl,
  measures = list(acc, setAggregation(acc, train.mean)), resampling = rdesc,
  par.set = ps, show.info = FALSE
)
data = generateHyperParsEffectData(res, partial.dep = TRUE)
tmp <- plotHyperParsEffect(
  data, x='C', y="acc.test.mean",
  plot.type="scatter", partial.dep.learn = "regr.randomForest"
)
```

The parameter values of `C` in the plot are then 
```
> tmp$data$C
[1] 9.765625e-04 1.706675e+02 3.413340e+02 5.120005e+02 6.826670e+02
[6] 8.533335e+02 1.024000e+03
```
instead of the used values for the parameter tuning.

Used version `mlr_2.11` in `R version 3.3.2 (2016-10-31)`.

Thank you in advance!

**Comment by MasonGallo** [comment]
Thanks for reporting this. I will not have time to look into this until next week at the earliest, so feel free to make a suggestion if you have a potential solution.

**Comment by VGalata** [comment]
Ok... As far as I could understand the code the problem is the call of `generatePartialDependenceData` in `generateHyperParsEffect.R` for the case `(length(x) == 1) && (length(y) == 1) && !(z.flag)`. At least for my example. In the [current version of generatePartialDependenceData](https://github.com/mlr-org/mlr/blob/ad24bff4e694f22807cb06ea66aca79f986d1bcb/R/generatePartialDependence.R) `generateFeatureGrid` is called in `generatePartialDependenceData` if the parameter `range` is not set, i.e. one could avoid the problem by setting this parameter:

```
if ((length(x) == 1) && (length(y) == 1) && !(z.flag)) {
    d = generatePartialDependenceData(partial.fit, partial.task, x, range=sort(unique(d$[,x])))$data
}
```

I think an analogous solution is required in the `(length(x) == 1) && (length(y) == 1) && (z.flag)` case where `generatePartialDependenceData` is also called.

However, I did not test it as in my version, `mlr_2.11`, `generateFeatureGrid` is called independently of the `range` parameter and I had no time to install and run the development version.
