### ISSUE TITLE
train: store warnings in WrappedModel 

### ISSUE THREAD

**Issue by Tazinho** [mlr-org/mlr#1835]
Is there any way to get the warnings from a resampling object?
I would like to catch every warning that occurs within an iteration step and relate it to the this specific step afterwards.

I tried `options("warn" = 2)`, but then the resampling always stops (any idea on this?).

The closest I could get so far was

```r
rdesc = makeResampleDesc("CV", iters = n,
                           predict = "test")
  r = withCallingHandlers(resample(learner = lrn, # parms = list(),
               task = task,
               resampling = rdesc,
               measures = list(mmce),
               models = FALSE),
  warning = function(c) warn <<- c)
```

In this scenario I catch the first warning. Maybe I could also catch all warnings via allocating `warn` as a list
and setting `warning = function(c) warn[length(warn) + 1] <<- c`.
However I don't see a chance to connect it then to the iteration number.

Any ideas?

**Comment by berndbischl** [comment]
so, if i do a 10fold CV, and in folds 2 and 7 there is a warning, you want that collected in the result object? and know in which iters which warnings did occur?

**Comment by berndbischl** [comment]
> I tried options("warn" = 2), but then the resampling always stops (any idea on this?).

this is normal in R. this escalates warnings to errors. so you stop.

**Comment by berndbischl** [comment]
this is example that can be used for reproduction:

```

load_all()

makeRLearner.classif.mock = function() {
  makeRLearnerClassif(
    cl = "classif.mock", package = character(0L), par.set = makeParamSet(),
    properties = c("twoclass", "multiclass", "missings", "numerics", "factors")
  )
}

trainLearner.classif.mock = function(.learner, .task, .subset, .weights = NULL,  ...) {
  if (1 %in% .subset)
    warning("foo")
  list()
}

# produce fake preds
predictLearner.classif.mock = function(.learner, .model, .newdata, ...) {
  iris$Species[1:nrow(.newdata)]
}

registerS3method("makeRLearner", "classif.__mlrmocklearners__1", makeRLearner.classif.mock)
registerS3method("trainLearner", "classif.__mlrmocklearners__1", trainLearner.classif.mock)
registerS3method("predictLearner", "classif.__mlrmocklearners__1", predictLearner.classif.mock)

configureMlr(show.info = TRUE)
options(warn = 1)

lrn = makeLearner("classif.mock")
r = resample(lrn, iris.task, cv2)
```

this also includes your first solution. with warn = 1, you can see from the logging output which warning  occurs in which CV fold. this helps you to see that on the console, but it is not collected in result object "r".

**Comment by berndbischl** [comment]
and another option i dont see (yet)

?configureMlr allows you to escalate warnings to error, with on.learner.warning 
this will only escalate learner warnings AND collect the messages in the model. 
and you can have them in the result object.
BUT: the model will be a FailureModel and the predictions NA.

if you simply need this in debugging this might be the best solution? 

if you need also the predictions, i currently dont know.

please explain yout context better

**Comment by Tazinho** [comment]
> so, if i do a 10fold CV, and in folds 2 and 7 there is a warning, you want that collected in the result object? and know in which iters which warnings did occur?

Exactly.

> >    I tried options("warn" = 2), but then the resampling always stops (any idea on this?).

> this is normal in R. this escalates warnings to errors. so you stop.
EDIT: just read ?options

`ResampleResult` has the attributes `err.msgs` & `err.dumps` so `options("warn" = 2)` was my first idea to trigger these. I thought you do sth like this internally. (I admit, that this might not be obvious from my question ;-)

```r
> a <- list(2)
> options("warn" = 2)
> for (i in 1:2){
+ a[i] <- try(warning("mlAir", i))
+ }
Error in try(warning("mlAir", i)) : (converted from warning) mlAir1
Error in try(warning("mlAir", i)) : (converted from warning) mlAir2
> a
[[1]]
[1] "Error in try(warning(\"mlAir\", i)) : (converted from warning) mlAir1\n"

[[2]]
[1] "Error in try(warning(\"mlAir\", i)) : (converted from warning) mlAir2\n"
```

> ... . this also includes your first solution. with warn = 1, you can see from the logging output which warning occurs in which CV fold. this helps you to see that on the console, but it is not collected in result object "r".

Hmm I definitely need this in the result, since I don't think it makes sense to invent a parser for this.

> ?configureMlr allows you to escalate warnings to error, with on.learner.warning
this will only escalate learner warnings AND collect the messages in the model.
and you can have them in the result object.
BUT: the model will be a FailureModel and the predictions NA.
if you simply need this in debugging this might be the best solution?
if you need also the predictions, i currently dont know.
please explain yout context better

It would be nice to have both (if I can't have this, I would prefer `NA`'s...for only those specific "leave one out models" that really gave a warning (so I will look into this, maybe it suffices). I think predicting twice might also be ok, once for the prediction, once for the possible condition (err, warn, msg) like in the following example (it just lacks the case of two or more warnings for the same prediction, which is not so important for my usecase. I am also relatively sure that this can be done within one step, just don't remember...).

```r
> df <- data.frame(target = factor(0:1),
+ var1 = 0:1,
+ var2 = 0:1)
> options("warn" = 0)
> n = nrow(df)
> mods <- list(n)
> preds <- double(n)
> warns <- list(n)
> for(i in 1:2){
+ mods[[i]] <- glm(target ~ ., data = df[-i, ], family = binomial)
+ preds[[i]] <- predict(mods[[i]], df[i, ])
+ tryCatch(predict(mods[[i]], df[i, ]), warning = function(w) warns[[i]] <<- w)
+ }
Warning messages:
1: In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
  prediction from a rank-deficient fit may be misleading
2: In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
  prediction from a rank-deficient fit may be misleading
> preds
[1] -22.56607 -22.56607
> warns
[[1]]
<simpleWarning in predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==     "link", "response", type), terms = terms, na.action = na.action): prediction from a rank-deficient fit may be misleading>

[[2]]
<simpleWarning in predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==     "link", "response", type), terms = terms, na.action = na.action): prediction from a rank-deficient fit may be misleading>
```

I hope this case is clear now(?). I'll try your recommended approach with the `NA`s. I will explain my general usecase a bit more in the other (more related) issues. Thank you! And sry for my ambigouos formulations in my previous posts.

**Comment by mb706** [comment]
This is probably something that should be implemented in mlr `resample`. Currently I can only think of two ways to get what you want, neither of them very elegant.

(1) You could turn warnings into errors (internally in R) using `warn = 2`, then make mlr ignore these errors. `on.learner.error = "warn"` would only turn the errors into warnings, end they in turn would be turned into errors again by R, so you have to do `on.learner.error = "quiet"`. Optionally, you can set `on.error.dump = TRUE` which would give you the option to inspect error dumps. It uses a mechanism similar to `options(error=dump.frames)`.
```R
> options(warn = 2)
> configureMlr(on.learner.error = "quiet", on.error.dump = TRUE)
> # using the `lrn` of @berndbischl above
> r = resample(lrn, iris.task, cv2)
[Resample] cross-validation iter 1: mmce.test.mean= 0.6
[Resample] cross-validation iter 2: mmce.test.mean=  NA
[Resample] Aggr. Result: mmce.test.mean=  NA
> # some resampling iters are NA, no way around this with this method
> r$err.msg  # ugly, but shows error messages
[...]
```
if you have 'on.error.dump = TRUE' above, you can do
```R
> getRRDump(r)  # one list entry for each resampling iter
[[1]]
[[1]]$train
<debug dump>


[[2]]
list()

> getRRDump(r)[[1]]$train  # or $predict, depending on when the error occurred
<debug dump>
> debugger(getRRDump(r)[[1]]$train)
Message:  (converted from warning) fooAvailable environments had calls:
1: resample(lrn, iris.task, cv2)
2: parallelMap(doResampleIteration, seq_len(rin$desc$iters), level = "mlr.resa
3: mapply(fun2, ..., MoreArgs = more.args, SIMPLIFY = FALSE, USE.NAMES = FALSE
4: (function (learner, task, rin, i, measures, weights, model, extract, show.i
[...]
```

(2) If you want to have warnings *and* a proper resampling result, you can also create a custom learner that "wraps around" your learner, as [described in the tutorial](https://mlr-org.github.io/mlr-tutorial/devel/html/create_learner/index.html). Sorry if that is more than what you think you should have to go through for this kind of feature.

**Comment by berndbischl** [comment]
> ResampleResult has the attributes err.msgs & err.dumps so options("warn" = 2) was my first idea to trigger these. I thought you do sth like this internally. (I admit, that this might not be obvious from my question ;-)

yes. @mb706 added these 2 slots to the RR. they were intended for debugging. on you CAN use them with  the warnings. 
- you can escalate warnings to errors with options(warn = 2). or use configureMlr(on.learner.warning = "error")
- then set configureMlr(on.learner.error = "warn" or "quiet")
this will produce "FailureModels" for iters where warnings occured. So you lose the preds, they are NA. but you get the warning in the model, actually the model is just the string of the message. And you have the dumps in there.
--> not a perfect solution, but this is what is currently possible.

**Comment by berndbischl** [comment]
and: what @mb706  said before me. he outlined exactly what is possible today

**Comment by berndbischl** [comment]
the best solution would be: always capture the warning in training, then put it into a well defined slot of the model.

**Comment by Tazinho** [comment]
The proposed

```r
> options(warn = 2)
> configureMlr(on.learner.error = "quiet", on.error.dump = TRUE)
> resample(...)
> r$pred
> r$err.msgs
```

works for now. Depending on my supervisor's opinion, I might dig deeper and go with the tutorial for the wrapper. Anyway I appreciate that you included this feature into your todolist.
