### ISSUE TITLE
possibility for Dependency inversion in mlr

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#1843]
In mlr, we have a lot of statements like the following 
in `setThreshold`
`if (ttype == "classif" || ttype == "fdaclassif")`
in `zzz.R`
`mlr$measure.properties = c("classif", "classif.multi", "multilabel", "regr", "surv", "cluster", "costsens", "req.pred", "req.truth", "req.task", "req.feats", "req.model", "req.prob", "fdaregr", "fdaclassif")`
in `measures.R`

```
acc = makeMeasure(id = "acc", minimize = FALSE, best = 1, worst = 0, 
properties = c("classif", "classif.multi", "fdaclassif", "req.pred", "req.truth" ...                                               
```                                             
in FDATask, we have
`new.td$type = "fdaclassif" `

All these strings are no different as writing a number like 1L or 1245L, which is makes different parts of the software strongly coupled. For example, if we want to make a new task type like FDATask or OneclassTask, we could have to change all those if statements which compares those strings, which is actually error prone since we might forget to change some of them which makes the software inconsistent (Of course one could use ACK to search all the "classif" and replace them with "classif", '"fdaclassif", but this is also not a genuine way to solve it).

Is it possible to have some dependency inversion? For example

```
acc = makeMeasure(id = "acc", minimize = FALSE, best = 1, worst = 0, 
properties =  getAccProperties(conf)...  # a function for lazy loading which is only executed when used                                             
```   
and
```         
getAccProperties = function(conf){
function(){   # returns a function for lazy loading
list.fun = getInit(conf)
unique(unlist(lapply(list.fun, function(x) do.call(x)["ACC"])))
}}

list.fun.FDATASK = function(){
  return(list(ACC="fdaclassif", ....))
}

```
In this way, the old features(measures) do not depend on the new features(for example, a new Task type like FDA or OneClass) any more (which is currently the case and once has to edit all the old features to accmodate the new features,   MeasureACC which is old depends on  FDA which is new),  and the developer of the new features are responsible for writing those list.fun.FDATASK functions to tell mlr to call them so now it becomes FDA which is new depends on MeasureACC which is old. 
and we only need to maintain a global list of features for the software which could be stored in a configuration file.

**Comment by berndbischl** [comment]
> All these strings are no different as writing a number like 1L or 1245L, which is makes different parts of the software strongly coupled.

well, a usual solution to this would be using constants? but R doesnt support those.

**Comment by berndbischl** [comment]
> t (Of course one could use ACK to search all the "classif" and replace them with "classif", '"fdaclassif", but this is also not a genuine way to solve it).

i get your point, but unit testing will figure out these mistakes in 99.9% of cases

**Comment by berndbischl** [comment]
for the remainder of your post: i currently dont yet understand what your constructive suggestion is?

**Comment by mb706** [comment]
The suggestion is (in effect, and as I understand it) to not (as currently done) annotate each measure with a list of supported task types, but to instead annotate each task type with the list of supported measures. That would make adding new task types which are similar to old task types relatively easier, since the number of measures (~70) is so much greater than the number of task types (~5).

I'm not sure it makes MeasureACC less "dependent" on FDA, since MeasureACC would still depend on FDA making predictions in a form that make sense to MeasureACC. Maybe if FDA predictions are so similar to classif predictions, one could make some kind of prediction type hierarchy.

**Comment by smilesun** [comment]
@mb706  I agree with the first paragraph.  Note that the hard coded string problem does not only exist for measures, actually it is in the core of mlr everywhere.

@berndbischl  The idea is to use design pattern to decouple the system, which makes the software more stable since it reduces the complexity of the software and easy to maintain. For example, the imputeWraper Michel has written is a form of "**Strategy design pattern**" where different imputation method could be passed as strategy which could avoid  the long "switch" statement since one do not want to maintain a switch statement with 1000 lines.

My idea is similar to **visitor pattern**. Suppose the mlr is like a car assembly line, and we have several sectors like makePrediction,  subsetTask(resample) etc. Now comes a car part, and in each sector, we have those if statement to make an exact match if certain procedure should be conducted, if we have a new car part, those if statement has to be changed again which is a heavy burden for software development(it is not a matter that unit test could ensure there is no problem, but it is a matter that how much time you need to spend to let those unit test pass), since the principle is to make the software conservative(to change), if someone change or implement a feature, it should not affect other people or as least as possible, but this is not currently the case.

My suggestion is, when the car part come to a sector of the assembly line, instead of checking in the current sector itself, we instead let the current sector to ask another department of the factory, in case of this kind of car part, what should I do? and I really do not care why, just tell me what to do. In this way,  the part of code for the core does not need to change at all. 

In detail implementation, instead of **hard coding** the properties for the measure , ACC for example.

**Comment by berndbischl** [comment]
> The suggestion is (in effect, and as I understand it) to not (as currently done) annotate each measure with a list of supported task types, but to instead annotate each task type with the list of supported measures. That would make adding new task types which are similar to old task types relatively easier, since the number of measures (~70) is so much greater than the number of task types (~5).

OTOH i find this pretty "unatural". 
i also dont really see where there is a problem of annotating measures with task types. thats just properties of objects. 

what I can understand is that in some places there is not-so-good if-then-else code. but thats a different thing. and then we need concrete proposals how to fix this. which we could probably not do here, but in the newer version of mlr. thats also one reason why i would like R6. s3 really is not made for these things.
it really isnt "OO enough".
(of course mlr still has enough places which are probable suboptimal design, in such a large code base, written in that way over many years, that always happens)

**Comment by berndbischl** [comment]
> @berndbischl The idea is to use design pattern to decouple the system, which makes the software more stable since it reduces the complexity of the software and easy to maintain. For example, the imputeWraper Michel has written is a form of "Strategy design pattern" where different imputation method could be passed as strategy which could avoid the long "switch" statement since one do not want to maintain a switch statement with 1000 lines.

sure i agree. this was good and well done by @mllg

**Comment by berndbischl** [comment]
> My idea is similar to visitor pattern. Suppose the mlr is like a car assembly line, and we have several sectors like makePrediction, subsetTask(resample) etc. Now comes a car part, and in each sector, we have those if statement to make an exact match if certain procedure should be conducted, if we have a new car part, those if statement has to be changed again which is a heavy burden for software development(it is not a matter that unit test could ensure there is no problem, but it is a matter that how much time you need to spend to let those unit test pass), since the principle is to make the software conservative(to change), if someone change or implement a feature, it should not affect other people or as least as possible, but this is not currently the case.
> 
> My suggestion is, when the car part come to a sector of the assembly line, instead of checking in the current sector itself, we instead let the current sector to ask another department of the factory, in case of this kind of car part, what should I do? and I really do not care why, just tell me what to do. In this way, the part of code for the core does not need to change at a

i have like 15 years of background in java and OO (I am beginning to forget some of it), I know this, I have also read all those books, eg. the gang-of-four stuff ;-)

lets get more concrete please.

**Comment by berndbischl** [comment]
> setThreshold
> getPredictionProbabilities
> checkLearnerBeforeTrain

i do agree that these place show suboptimal code.
but 
a) i have no idea what this has to do with properties of a measure
b) the fix seems to be - like we discussed on monday - to have a better data type for FDA data. then we dont need to add this bad if statements. 

regarding the rest: i am not sure i understand your concrete solution. lets discuss this in our office, orally, so i can ask some questions, ok?

**Comment by smilesun** [comment]
OK, before the discussion, just give the Java version of the solution.
```
public interface MlrPipeline
{
public int accept(Visitor4Task visitor);
}
CheckLearnerBeforeTrain implements MlrPipeline
{
public int accpet(Visitor4Task2 visitor)
{visitor.visit(this)}

}
getPredictionProbabilities implements MlrPipeline
setThreshold implements MlrPipeline
```

public interface Visitor4Task
{
public int visit(MlrPipeline hh)
}
visitor4checkLearnerBeforeTrain.task1 implements Vistor4Task
{
@Override
	public int visit(CheckLearnerBeforeTrain hh) {
		return(!(td$type == "fdaclassif" 
})  # these fields should be got from the object hh.
	}
}
visitor4checkLearnerBeforeTrain.task2 implements Vistor4Task
{
@Override
	public int visit(CheckLearnerBeforeTrain hh) {
		return(!learner$type == "classif") && !(td$type == "fdaregr" && learner$type == "regr")
})  # these fields should be got from the object hh.
	}

}



visitor4setThreshold implements Vistor4Task
{

}


in checkLearnerBeforeTrain.java
int main()
{
tasks = Array(visitor4checkLearnerBeforeTrain.task1, visitor4checkLearnerBeforeTrain.task2 )
cbt = new CheckLearnerBeforeTrain()
for(task : tasks){
			if cbt.accept(visitor)
                            print( stopf("Task '%s' is '%s', but learner '%s' is for '%s'!", td$id, td$type, learner$id, learner$type) )
		}
}

**Comment by smilesun** [comment]
"a) i have no idea what this has to do with properties of a measure"
My solution for measure is written in the first floor. In short words, it is the responsibility for the task to register itself to a measure, instead of having the measure to depend on the task (what we are doing now is to list the "classif" "regr" which is the task description type in measures).

Instead, the task should register itself to a measure for example mmce, the measure should be a property for the task, like what we are doing to the learner.
