### ISSUE TITLE
reenable lintr

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1844]
```

# FIXME: disabled because it took more than 10min without output and broke travis
# library(testthat)
# test_check("mlr", filter = "lint")

```

**Comment by mb706** [comment]
[this](https://github.com/mlr-org/mlr/pull/1827/commits/2fc31078e14b8dbf6ae593611ec65688ba1b4dd1) is the solution, though the number should be greater (100 is working well for me).

**Comment by berndbischl** [comment]
but please then do and indivual PR for the master
