### ISSUE TITLE
add adaboostm1 learner from rweka

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1845]

**Comment by berndbischl** [comment]
reason: there is no good classic adaboost in R (that i know?).

ada in package ada is EXTREMELY slow

**Comment by giuseppec** [comment]
There is https://cran.r-project.org/web/packages/fastAdaboost/fastAdaboost.pdf which implements Adaboost based on C++ backend code. 
Not sure if this is better than the RWeka learner, at least they have unit tests in their repo https://github.com/souravc83/fastAdaboost

**Comment by alona-sydorova** [comment]
we'll check it out

**Comment by giuseppec** [comment]
Cool. Just do a mini benchmark first and share your results. We can then decide wether you can implement fastAdaboost or the rweka adaboost. (Btw. installing the rweka package can be horrible due to rjava dependency, so if you encounter any problem just ask.)

**Comment by alona-sydorova** [comment]
we have found out that fastAdaboost is implemented only for binary classification while RWeka adaboost can work with multilabel classification tasks. should we still compare their performance or is it more important for you to have the possibility of having more than 2 classes in the task?

**Comment by giuseppec** [comment]
Hm, as the currently used [adaboost learner](https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_ada.R) is also only able to do binary classification, I would say that a mini benchmark will still help in making a decision.

**Comment by alona-sydorova** [comment]
so, we did some micro benchmarking, with 3 different datasets and 50 to 200 iterations as well as different classifiers for RWeka and found out that RWeka still performs significately better than fastAdaboost

**Comment by giuseppec** [comment]
Do you have the code for this benchmark, so that I could reproduce this on my machine?
But it sounds like you can already implement the RWeka adaboost. Just do a PR for this!

**Comment by alona-sydorova** [comment]
I've sent you the script in Slack
