### ISSUE TITLE
changeData ignores weights for multiclass task

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1850]
because of a bug in changeData. This probably has other ramifications as well.

**Comment by berndbischl** [comment]
can you post an example with current master that demos this, first?

**Comment by mb706** [comment]
Apparently the tests weren't catching, they are now.

With the multilabel.task from tests/testthat/helper_objects.R:
```R
> t = multilabel.task
> ws = seq_len(getTaskDesc(t)$size)
> getTaskDesc(changeData(t, weights = ws))$has.weights
[1] FALSE
```
Vs. expected behaviour:
```R
> t = regr.task
> ws = seq_len(getTaskDesc(t)$size)
> getTaskDesc(changeData(t, weights = ws))$has.weights
[1] TRUE
```

**Comment by berndbischl** [comment]
ok, it is very good that you are repairing this. 
is it also possible to trigger that bug from the outside? changeData is not exported code

**Comment by mb706** [comment]
With subsetTask
```R
> t = multilabel.task
> ws = seq_len(getTaskDesc(t)$size)
> wtask = changeData(t, weights = ws)
> wtask$task.desc$has.weights = TRUE  # cheating, I know, but if one builds a multilabel task with weights he should get the same kind of object
> getTaskDesc(wtask)$has.weights
[1] TRUE
> getTaskDesc(subsetTask(wtask, 1:10))$has.weights
[1] FALSE
```

**Comment by mb706** [comment]
also since we're there: what would you think about exporting changeData? Maybe sometimes a user wants to do something to his data independent of what task type he happens to have. He currently needs to write a switch statement with different `makeXXXTask` calls.
