### ISSUE TITLE
How to add tunable hyperparamater to wrapped filter feature selection?

### ISSUE THREAD

**Issue by andrewjohnlowe** [mlr-org/mlr#1854]
Hello,

I've developed an unusual feature selection algorithm that I would like to fuse to a learner --- perhaps using makeFilterWrapper --- and the results depend on a tunable parameter. Unlike standard filter-based methods, I don't want to select the top X features after ranking, or the top Y%. The method finds subsets of features that are minimally redundant, but are not ranked*. The hyperparameter controls the size of the feature subsets, but in a somewhat complex way. I'd like to tune this hyperparameter as part of CV. How do I add this parameter to a feature filter wrapper? Alternatively, if this is not possible, how can this be done in a preprocessing wrapper?

* To be more clear: say I have a handful of features A, B, C, D, E that have been ranked in that order by information gain. Choosing the best three features would select A, B, C. But B doesn't contain more information than A; it is redundant. A better feature set might be A, D, E. Tuning the hyperparameter that indirectly controls the number of feature selection might also give A, D or B, C, D, E. My points is: simply tuning to select the top ranked features does not apply for this method.

**Comment by jakob-r** [comment]
It's a bit hard to answer a technical question without any code but I will give it a try.
Can you incorporate your future selection into a preprocessing wrapper? If so you can give it parameters that you can also tune on. You just have to write two functions `train` and `predict`. `train` will do the hard work and return the filtered data and a control object that contains the selected columns. `predict` will just read what columns were selected in `train` from the `control` argument and subset the data. Check the help for the preprocessingWrapper for further details.

**Comment by andrewjohnlowe** [comment]
Should I assume then that makeFilterWrapper is unsuitable for what I want to do? In that case, I'll not pursue this route further and instead focus on making this work in a preprocessing wrapper. If this works, I'm happy to contribute the method to mlr.

**Comment by jakob-r** [comment]
Alternatively you can fork mlr and implement your own `make?FilterWrapper` based on what you find in `makeFilterWrapper.R`. That's the way I would chose as it gives the most freedom.
