### ISSUE TITLE
Flexible creation of custom wrapper of feature method

### ISSUE THREAD

**Issue by jyk** [mlr-org/mlr#1863]
Hi!

I have a question (sorry, maybe it is more related to using R functions at all...) - how is it possible to make possible to evaluate parameters in 'fun' function of mlr::makeFilter (in my case: estimator = ...) ?
Currently I am creating custom filter in next way:

VarSelFilterStat <- 'InfGain' # can be other value

        CoreLearnFSWrapper <- mlr::makeFilter(
                                              name = "CoreLearnFSWrapper",
                                              desc = paste0("Feature selection as a wrapper from package 'CoreLearn' using estimator = ",VarSelFilterStat),
                                              pkg  = "CORElearn",
                                              supported.tasks = c("classif", "regr"),
                                              supported.features = c("numerics", "factors"),
                                              fun <- function(task, nselect, ...) {
                                                              CORElearn::attrEval(
                                                                                  getTaskFormula(task),
                                                                                  data = getTaskData(task),
                                                                                  estimator = base::get(VarSelFilterStat),
                                                                                  ...
                                                              )
                                              }
        )
Problem is that R gives me error: 
Error in CORElearn::attrEval(getTaskFormula(task), data = getTaskData(task),  : 
  Invalid estimator parameter

as.list(mlr:::.FilterRegister)$CoreLearnFSWrapper$fun gives me:
function(task, nselect, ...) {
                                                              CORElearn::attrEval(
                                                                                  getTaskFormula(task),
                                                                                  data = getTaskData(task),
                                                                                  estimator = base::get(VarSelFilterStat),
                                                                                  ...
                                                              )
                                              }
<environment: 0xcd4a0c0>
It seems like value for estimator for CORElearn::attrEval will not be evaluated (i.e. user can give VarSelFilterStat = 'InfGain')

Briefly i would like to have custom filter where user can give method for estimator parameter of CORElearn::attrEval function ('InfGain', 'Relief' etc)

**Comment by mb706** [comment]
Two things:
1. I think you are not using `base::get` correctly. In your example, `base::get` is trying to get a variable with the *name* 'InfGain' (which is not what you want here, *I think*)
2. You can have `fun` have more parameters. Then when you call `filterFeatures` or `generateFilterValuesData`, you can give these additional arguments to the `...` part of these functions and they will be delivered to your filtering function. In your case, that might be
```R
[...]
fun <- function(task, nselect, VarSelFilterStat) {
[...]
```
and then you would call `filterFeatures(task = task, ....., VarSelFilterStat = 'InfGain')`. (And don't use `base::get` because again, I think you're not using it the way you should use it)

**Comment by jyk** [comment]
Thank You very much! You can close.
