### ISSUE TITLE
Issuing a complexe numeric vector with MakeNumericVectoParm

### ISSUE THREAD

**Issue by aminevsaziz** [mlr-org/mlr#1866]
Is there a way to make a complex numeric vector with multiple upper /lower boundries for example: c (0.9,0.2)  where the first part limits are [0:0.9] and second part limits are [0.1,0.5].

**Comment by mb706** [comment]
I think what you want is
```R
> makeNumericVectorParam("x", len = 2, lower = c(0, 0.1), upper = c(0.9, 0.5))
           Type len Def           Constr Req Tunable Trafo
1 numericvector   2   - 0,0.1 to 0.9,0.5   -    TRUE     -
```
The `lower` and `upper` parameters can be vectors, where the entries give the lower / upper bounds for each dimension.

I don't know how well the tuners are able to work with these, however.

**Comment by aminevsaziz** [comment]
@mb706  thanks for your help it work..i think mlr should include this tidbit either in documentions or tutorials .
