### ISSUE TITLE
Creating Preprocessing Wrapper

### ISSUE THREAD

**Issue by MelvinWoodley** [mlr-org/mlr#1875]
I am trying to create a simple preprocessing wrapper for a regression task that can be used in the tuning process. The job of this preprocessing wrapper is very simple: It would take the input data and two numerical arguments 'lower1' and 'upper1' and then it would filter out the data points that are not between lower1 and upper1. So that the training would be done on only data that falls between these boundaries. It basically removes the outliers from the data that have a target value outside of the limits lower1 and upper1.

The goal is to pass the parameters lower1 and lower2 through the tuning process to identify the optimal cutoff points. I have to use a wrapper in order to get honest estimates of the performance when the preprocessing is applied. 

I think I have implemented the wrapper correctly but I am getting an error when I try to do the tuning. I am wondering if the returned data from the preprocessing wrapper is expected to be the same size as the input data that was passed to the wrapper.

Here is what I did and a reproducible example:

```R
library(mlr)
library(mlrMBO)
library(plyr)

trainfun = function(data, target, args = list(lower1, upper1)) {
  out<-data.frame(target=data[,target])
  out<-rename(out, replace = c("target" = target))
  x<-data[data[,target]<=args$upper1 & data[,target] >= args$lower1,]
  control<-list(lower1=args$lower1,upper1=args$upper1)
  data <-data.frame(x)
  return(list(data = data, control = list(lower1=args$lower1,upper1=args$upper1,out=out)))
}

predictfun = function(data, target, args, control) {
  data<-cbind(data,control$out)
  x<-data[data[,target]<=args$upper1 & data[,target] >= args$lower1,]
  x<-x[,setdiff(names(x),target)]
  data <-data.frame(x)
  return(data)
}

lrn = makeLearner("regr.xgboost")
lrn = makePreprocWrapper(lrn, train = trainfun, predict = predictfun,
                         par.set = makeParamSet(
                           makeNumericLearnerParam(id = "lower1", lower = 6, upper = 10),
                           makeNumericLearnerParam(id = "upper1", lower = 22, upper = 40))
                         ,par.vals = list(lower1 = 6,upper1 = 22))
lrn

paramsxgb <- makeParamSet(
  makeNumericParam("lower1",lower=5,upper=17),
  makeNumericParam("upper1",lower=21,upper=25),
  makeNumericParam("eta",lower=0.001,upper=1),
  makeIntegerParam("nrounds", lower=10,upper=200),
  makeIntegerParam("max_depth",lower=1,upper=10),
  makeNumericParam("min_child_weight",lower=1,upper=100),
  makeNumericParam("subsample",lower=0.1,upper=1),
  makeNumericParam("colsample_bytree",lower =0.3, upper=1)
)

iters = 10
ctrl = makeMBOControl()
ctrl = setMBOControlTermination(ctrl, iters = iters)
tune.ctrl = makeTuneControlMBO(mbo.control = ctrl)

data(BostonHousing, package = "mlbench")
data1<-subset(BostonHousing,select=-c(chas))
tsk = makeRegrTask(data = data1, target = "medv")
inner = makeResampleDesc("CV", iters=3,predict = "both")
set.seed(41)
result = tuneParams(lrn, tsk,measures=mae,resampling =inner, par.set = paramsxgb, control = tune.ctrl,show.info = FALSE)

---Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
---arguments imply differing number of rows: 337, 204
```
(mb706 edit: formatting)

**Comment by mb706** [comment]
Removing rows from the prediction data is not in the scope of PreprocWrapper, and shouldn't happen in `predictfun`. I think what you really want is `predictfun` to just be `return(data)`.

Remember that, usually, a learner model predicts data that is *not* the training data, so `cbind`-ing the training data target column to the test data really makes no sense in general.


P.S.: I think instead of
```R
out<-data.frame(target=data[,target])
out<-rename(out, replace = c("target" = target))
```
you could just do
```R
out <- data[target]
```

**Comment by MelvinWoodley** [comment]
I am not trying to remove rows from the prediction data. I am trying to remove rows from the **training** data before the training is done. 

The change that you suggested does make sense based on what I was trying to do, however it doesn't seem to solve the general problem that I am having. Are you saying that removing rows from the training data cannot be done with a PreprocWrapper?

**Comment by MelvinWoodley** [comment]
I think I understand the problem a little better based on what you have said. I really should not be modifying the data in the predictfun function. I should really just return the original data set that was passed. The following is perhaps a little closer to correct but I am now getting a different error.


trainfun = function(data, target, args = list(lower1, upper1)) {
  x<-data[data[,target]<=args$upper1 & data[,target] >= args$lower1,]
  control<-list(lower1=args$lower1,upper1=args$upper1)
  data <-data.frame(x)
  return(list(data = data, control = list(lower1=args$lower1,upper1=args$upper1)))
}

predictfun = function(data, target, args, control) {
  data <-data.frame(data)
  return(data)
}

**Comment by mb706** [comment]
I think you're getting an error because your tuning `ParamSet` contains bad lower / upper bounds for `"lower1"` and `"upper1"`. When I run your code with
```R
paramsxgb <- makeParamSet(
  makeNumericParam("lower1",lower=6,upper=10),  # !!!
  makeNumericParam("upper1",lower=22,upper=25),  # !!!
  makeNumericParam("eta",lower=0.001,upper=1),
  makeIntegerParam("nrounds", lower=10,upper=200),
  makeIntegerParam("max_depth",lower=1,upper=10),
  makeNumericParam("min_child_weight",lower=1,upper=100),
  makeNumericParam("subsample",lower=0.1,upper=1),
  makeNumericParam("colsample_bytree",lower =0.3, upper=1)
)
```
it appears to work.

The error message that comes is unhelpful, and I will open an issue about that.

**Comment by mb706** [comment]
(i.e. compare your lower / upper bounds in the `paramxgb` ParamSet, and the lower / upper bounds you give in your `makePreprocWrapper` call)

**Comment by MelvinWoodley** [comment]
I think this is what I wanted. Thank you so much.

**Comment by MelvinWoodley** [comment]
I was actually able to accomplish the same thing using another strategy. I basically created a new "learner" and passed those two bounds as parameters. Both ways seem to achieve the same goal. I just wanted to ability to tune these two bounds using the tuning tools.
