### ISSUE TITLE
MBO tuning gives unhelpful error message when parameter not feasible and show.info = FALSE

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1876]
One might argue that the user forfeits his right for a helpful message when he sets `show.info = FALSE`, but I think one may still want to know why an optimization run fails without wanting to see the `x` / `y` values for every design point.

This example sets `tol` between -1 and 1, even though only positive values are feasible. The error message is misleading.
```R
> iters = 10
> ctrl = makeMBOControl()
> ctrl = setMBOControlTermination(ctrl, iters = iters)
> tune.ctrl = makeTuneControlMBO(mbo.control = ctrl)
> tuneParams("regr.lm", bh.task, resampling = cv5,
+  par.set = makeParamSet(makeNumericParam("tol", -1, 1)),
+  control = tune.ctrl, show.info = FALSE)
Error in evalTargetFun.OptState(opt.state, xs, extras) :
  Objective function output must be a numeric of length 1, but we got: Inf
```

I don't know if this is an issue in `mlr` or `mlrMBO`, since I don't know tuneMBO's internal workings.

**Comment by jakob-r** [comment]
Okay. Negative values for `tol` are not feasible and generate predictions that somehow down the line got converted to an performance of Inf?

So wee need two things

- [ ] check that the par.set lays within the par.set of the learner.  
- [ ] check why we get a Inf value and fix that
