### ISSUE TITLE
NA handling of Aggr. result

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#1887]
Given an `resample` output of 

```
resa_ec$measures.test
   iter       auc
1     1 0.9250000
2     2        NA
3     3 0.9737336
4     4 0.9827586
5     5 0.9728261
6     6 0.9919218
7     7 0.9972586
8     8 1.0000000
9     9 0.9852941
10   10 0.9937255
```

Currently, the following is printed to the console:

`[Resample] Aggr. Result: auc.test.mean=  NA`

Wouldn't it be good if the aggregation function would do a `na.rm` for convenience? 

I could not find an option in the docs or in `setAggregation()`.

**Comment by larskotthoff** [comment]
Yeah, having that as an option would be useful. Pull requests welcome :)

**Comment by pat-s** [comment]
I would prefer to hardcode it - I see no advantage in a `NA` result of any aggregation function? 

`NA`s are not lost - they are still stored in the `measures` output.

**Comment by larskotthoff** [comment]
Then the user always has to check very carefully. It's better to keep them and give an option to omit to avoid mistakes.
