### ISSUE TITLE
cannot use measures=auc in tuneParams 

### ISSUE THREAD

**Issue by papinisan** [mlr-org/mlr#1888]
```r
tuneParams(learner = lrn, task = traintask, resampling = rdesc, measures = auc, par.set = params, control = ctrl, show.info = T)
```

yields this error:
```
Error in tuneParams(learner = lrn, task = traintask, resampling = rdesc,  : 
  Assertion on 'measures' failed: Must be of type 'list', not 'closure'.
```

Other measures that I've tried (acc, bac, logloss) work fine.

One option is to include eval_metric="auc" in par.vals, and measure=acc in tuneParams which will run, but it's not clear to me whether the paramaters are being chosen on the basis of auc or acc. I'd like to maximize auc in tuning since I have an unbalanced dataset.

**Comment by larskotthoff** [comment]
Can you post the full code please? mlr's `auc` could be shadowed by `auc` from another package.

**Comment by papinisan** [comment]
Thanks! You are right, the issue was another package (pROC). That being solved, is it redundant to have both eval_metric="auc" in par.vals and measure=auc in tuneParams?

**Comment by jakob-r** [comment]
I don't know which `learner` you are using but if it has the param `eval_metric` it has nothing to do how `mlr` evaluates the `auc`. You have to look up in the manpage of the learner to see if this setting changes anything but my guess would be that `eval_metric="auc"` is superfluous.

**Comment by papinisan** [comment]
Thanks, I will look at the manpage for xgboost.
