### ISSUE TITLE
We shoud add a ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#1889]
https://github.com/blog/2111-issue-and-pull-request-templates

IMHO we should encourage people 

- to use stack-overflow for things that are not feature-requests or error-messages
- to format their questions with triple ticks ` for source code
- to provide a MWE?
- to read the tutorial(?)
- etc.
- add an obligatory motivational concluding sentence

**Comment by berndbischl** [comment]
very good idea!

**Comment by jakob-r** [comment]
I will make a PR then where we can all edit.

**Comment by jakob-r** [comment]
https://github.com/mlr-org/mlr/pull/1893
