### ISSUE TITLE
Can printHead be removed?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1892]
`mlr` defines the function `printHead` in `R/utils.R`, but this is also exported by `BBmisc`. The output of both is subtly different; if this difference is enough to legitimize duplicating this function, I suggest renaming `mlr`'s version, since I get warnings when loading packages that import `mlr` when using `devtools::load_all`.

**Comment by larskotthoff** [comment]
I don't see a problem with renaming it as it's only used internally and not exported.

**Comment by mb706** [comment]
For reference, the function in `BBmisc` is [here](https://github.com/berndbischl/BBmisc/blob/master/R/printHead.R#L15-L23), the one in `mlr` is [this one](https://github.com/mlr-org/mlr/blob/master/R/utils.R#L17-L21).
