### ISSUE TITLE
Automatic threshold for feature selection with randomForestSRC.var.select 

### ISSUE THREAD

**Issue by mingrisch** [mlr-org/mlr#1894]
Right now, feature selection with `randomForestSRC.var.select` requires to pass the threshold, percentage or number of features to keep. However, minimal depth variable selection supports an automated threshold for the top variables. (see e.g. https://rdrr.io/cran/randomForestSRC/man/var.select.html)

I think it should be possible to support this threshold within the randomForestSRC.var.select filter (or, respectively, in filterFeatures, like `filtered.task = filterFeatures(task, randomForest.var.select, auto)`

I am not much of a R developer, but I'd be happy to assist (and learn).

**Comment by larskotthoff** [comment]
Well, if a user selects this type of automated variable selection, they can simply set the percentage to 100 to get all that the method thinks are important.
