### ISSUE TITLE
move BBMisc from imports to depends?

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#1896]
Every time one wants to run single tests using `devtools::test(filter = "something")`, `mlr` and dependencies are loaded. However, currently `BBMisc` is not listed as one and therefore all `test()` calls fail which depend on helper functions such as `requirePackages()` because they are not found/sourced. To avoid manual loading the package and sourcing the helper functions every time ->

Can we move `BBMisc` from `imports` to `depends`?

**Comment by larskotthoff** [comment]
This works fine for me. Can you post a complete example where this fails please?

**Comment by mb706** [comment]
I can reproduce this and support the suggestion. Possibly try to run `R --vanilla`, maybe something in your `.Rprofile` or `.RData` causes `BBmisc` to be loaded.
```R
> devtools::test("mlr", filter = "cluster_kmeans")
Loading mlr
Loading required package: testthat
Loading required package: ParamHelpers
Testing mlr
cluster_kmeans: 1

Failed -------------------------------------------------------------------------
1. Error: cluster_kmeans (@test_cluster_kmeans.R#4) ----------------------------
could not find function "requirePackages"
```

**Comment by pat-s** [comment]
```r
devtools::test(filter = "classif_lda")
Loading mlr
Loading required package: testthat
Loading required package: ParamHelpers
Welcome to rex, the friendly regular expression helper!
Use 'rex_mode()' to toggle code completion for rex shortcuts and functions.
Testing mlr
classif_lda: 1

Failed --------------------------------------------------------------------------------------------------------------------------------------------------------------
1. Error: classif_lda (@test_classif_lda.R#4) -----------------------------------------------------------------------------------------------------------------------
could not find function "requirePackages"

DONE ================================================================================================================================================================
```

with `BBMisc` in Depends

```r
devtools::test(filter = "classif_lda")
Loading mlr
Loading required package: testthat
Loading required package: ParamHelpers
Loading required package: BBmisc
Testing mlr
classif_lda: ....

DONE ================================================================================================================================================================
```

**Comment by larskotthoff** [comment]
I still can't get this to break. Removed my `.Rprofile` and started with `--vanilla`:

```
$ /usr/bin/R --vanilla

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> devtools::test("mlr", filter = "cluster_kmeans")
Loading mlr
Loading required package: testthat
Loading required package: ParamHelpers
Testing mlr
cluster_kmeans: .....

DONE ===========================================================================
```

**Comment by mb706** [comment]
Possibly the devtools version? I'm using 1.13.2, are you using the one from github? Is `BBmisc` in your sessionInfo()?

**Comment by larskotthoff** [comment]
I have version 1.12.0. BBmisc is not in my session info when I start the session, but shown as "loaded via namespace (and not attached)" after running the command.

**Comment by pat-s** [comment]
So its loaded by some other call/package for you - quite fiddly task to track by which one. 

Would it be any harm to add this to depends? Its needed for a lot of stuff in `mlr` anyway, right?

**Comment by mb706** [comment]
The issue seems to go away when I install the CRAN version of `testthat`. For some reason I had "version testthat_1.0.2.9000" -- the github version -- installed. I don't know if this behaviour is a bug in the new `testthat`, or a fix of incorrect behaviour of the current CRAN `testthat`.

**Comment by pat-s** [comment]
> The issue seems to go away when I install the CRAN version of testthat. 

Confirmed here!

So to prevent a bug when the new `testthat` version is released to CRAN, should we simply add `BBMisc` to depends? Any concerns?

**Comment by mb706** [comment]
Ok, the difference seems to be the line
```R
    if (packageVersion("testthat") > "1.0.2") {
        testthat_args <- c(testthat_args, load_helpers = FALSE, 
            encoding = pkg$encoding %||% "unknown")
    }
```
in (my version of) `devtools::test` (but [also on the github version](https://github.com/hadley/devtools/blob/master/R/test.r#L59)). Devtools anticipates the new argument `load_helpers` introduced by the github, as of yet unpublished, new version of `testthat`. With the old `testthat` version, `helper_*.R` files were loaded in the namespace of the package to test (`mlr`, which imports `BBmisc`), but with the new version they are sourced (by `devtools::load_all`) in the "package:mlr" environment.

[In my opinion this is a bug in `devtools`](https://github.com/hadley/devtools/issues/1540).

A downside of putting `BBmisc` into `depends` is that it pollutes the user's namespace when he loads mlr. As a workaround, I suggest `require`-ing `BBmisc` inside the relevant functions in `helper_helpers.R` instead.

**Comment by berndbischl** [comment]
hi,

please note 

1) if @pat-s has problems running his unit tests, we will help you to figure this out. 

2) but: whatever the outcome of this thread, I dont think we should BBmisc to DEPENDS. The argumentation here in the thread goes into a wrong direction. Let's think about this:
What goes into DEPENDS: Stuff that the user needs in the global env when he wants to use mlr.  Thats ParamHelpers, maybe ggplot2. Certainly NOT an internal helper package which is only called inside of mlr but never by the user. 

3) I personally have BBmisc in my R profile. And have 0 problems here. If you have a suggestion how to make the unit test scrips better, lets here it.

**Comment by berndbischl** [comment]
> Would it be any harm to add this to depends? Its needed for a lot of stuff in mlr anyway, right?

@pat-s Please really read my point 2) and understand the difference between IMPORTS and DEPENDS
Of course BBmis is "needed" by mlr. But if it is needed on the inside only, it goes into IMPORTS. Actually that is probably true for 95% of dependencies. They should go into DEPENDS. That package authors use IMPORTS less often is a mistake (!) on their part.

**Comment by berndbischl** [comment]
just to make sure i just did:

1) updated testthat and devtools from CRAN

2) ran 
test --filter=cluster_kmeans (with rt)
and
test(filter="cluster_kmeans") (from R)

I see 0 problems?

**Comment by berndbischl** [comment]
and now i removed my .Rprofile, which loaded BBmisc.

it STILL works?

**Comment by pat-s** [comment]
> updated testthat and devtools from CRAN

the issue appears when using `testthat` Github version

> What goes into DEPENDS: Stuff that the user needs in the global env when he wants to use mlr. Thats ParamHelpers, maybe ggplot2. Certainly NOT an internal helper package which is only called inside of mlr but never by the user.

Okay 👍 

> I personally have BBmisc in my R profile. And have 0 problems here. If you have a suggestion how to make the unit test scrips better, lets here it.

Sure that would be an easy fix. But think about new users/developers who do not know this. They will be frustrated once the new `testthat` version from Github moves to CRAN. So we should take care of this internally. 

> I suggest require-ing BBmisc inside the relevant functions in helper_helpers.R instead.

This might be a solution. I do not want to force a move into depends, I just want `devtools::test(filter = "something")` to work.

**Comment by berndbischl** [comment]
> the issue appears when using testthat Github version

thx. I guess i overlooked that. but then stop using the GH version? why did you even take it from there in the first place? I would also say that if that behavior stays in testthat, that seems like a bug. what we are discussing now (and what does work for me, with the CRAN version) SHOULD really work.
And I hope  they dont screw this up at testthat :)

> I suggest require-ing BBmisc inside the relevant functions in helper_helpers.R instead.

thats also kinda'bad, if i understand this correctly. this would not only concern BBmisc, but also EVERYTHING we have in imports. and now we want to call of those in multiple functions.

I see it like this:

a) this does not concern users, right? it only concerns developers.

b) it is not even on CRAN. do we know that they will keep this behavior in testthat? have you guys even asked there? at testthat?

c) there seems to be an extremely easy fix for everyone now? install testthat from CRAN?
which is not really a fix, but what one should do in the first place?

sorry, I dont want to sound unhelpful or angry :) 
I just dont want to create work or worsen our structure if we dont have to. the package should surely be easily usable for users and devs!

**Comment by pat-s** [comment]
> thx. I guess i overlooked that. but then stop using the GH version? why did you even take it from there in the first place? I would also say that if that behavior stays in testthat, that seems like a bug. what we are discussing now (and what does work for me, with the CRAN version) SHOULD really work.
> And I hope they dont screw this up at testthat :)

Living on the edge ;) 
Let's hope that they change it again - I'll open an issue to get deeper insights why they do this. 

> a) this does not concern users, right? it only concerns developers.

yes. for now everythings fine using CRAN `testthat`. I'll talk to them and see what comes out. 

> b) it is not even on CRAN. do we know that they will keep this behavior in testthat? have you guys even asked there? at testthat?

See a)

> c) there seems to be an extremely easy fix for everyone now? install testthat from CRAN?
> which is not really a fix, but what one should do in the first place?

yes 👍 

> sorry, I dont want to sound unhelpful or angry :)
> I just dont want to create work or worsen our structure if we dont have to. the package should surely be easily usable for users and devs!

sure, no worries 👍

**Comment by berndbischl** [comment]
> Living on the edge ;)

![here-be-dragons1](https://user-images.githubusercontent.com/1225974/28240103-2ffaa242-697b-11e7-8e53-5232f2943129.jpg)


> Let's hope that they change it again - I'll open an issue to get deeper insights why they do this

great thx

**Comment by mb706** [comment]
> I'll open an issue to get deeper insights why they do this.

This is explained in [testthat PR #505](https://github.com/hadley/testthat/pull/505): `devtools::load_all` already sources the `helper_` files, why should `testthat` do it again. The problem is that `devtools::load_all` sources them in a different context. See the [issue I opened about that over at devtools](https://github.com/hadley/devtools/issues/1540).

Right now it seems obvious that this is the direction `testthat` / `devtools` want to go in the future. The problem is not that `devtools::test` doesn't source the `helper_` files correctly, it is that *`devtools::load_all` doesn't source them correctly*.

**Comment by mb706** [comment]
A possible workaround that is more general than requiring BBmisc would be to prefix all the test files with
```R
source_test_helpers(".", env = environment())
```

**Comment by berndbischl** [comment]
> A possible workaround that is more general than requiring BBmisc would be to prefix all the test_ files with
> 
> source_test_helpers(".", env = environment())

which is horrible if one has ~100 test files. 

cant we do do something in very fex places?

**Comment by mb706** [comment]
Possibly put something like
```R
context = function(...) {
  source_helpers(".", env = parent.frame())
  testthat::context(...)
}
```
in one of the `helper_` files, but this is obviously a hack and I'm not 100% sure this doesn't break things in a different place.

**Comment by pat-s** [comment]
@mb706 not sure if we will get an answer in the devtools issue

could you try to see if your proposed workaround works?

**Comment by mb706** [comment]
@berndbischl is that something we want, or should the solution be "put BBmisc in your .Rprofile / load it when loading mlr"?

**Comment by berndbischl** [comment]
> is that something we want, or should the solution be "put BBmisc in your .Rprofile /

if thats all it takes i would doc it in the developer wiki. and keep it like it is.
that no big problem right?

but lets doc it

**Comment by mb706** [comment]
Note the relevant `devtools` issue was moved to [pkgload](https://github.com/r-lib/pkgload/issues/40), which apparently handles the relevant backend stuff.

**Comment by pat-s** [comment]
@mb706 solved? haven't tested yet

**Comment by mb706** [comment]
Works with the current github versions of `r-lib/pkgload` and `hadley/devtools`, as well as with the current CRAN version of `"devtools"`. r-lib/pkgload#40 apparently fixed this.
