### ISSUE TITLE
tuneParams should allow "tuning" with an empty ParamSet

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1900]
For consistency. This is especially useful when the `ParamSet` to tune over is generated automatically by some function.
```R
> tuneParams("classif.logreg", pid.task, cv5, par.set = makeParamSet(),
+   control = makeTuneControlGrid())
Error in checkTunerParset(learner, par.set, measures, control) : 
  No parameters were passed!
```

**Comment by berndbischl** [comment]
not sure if we should allow that.

what would you put in x,y in the OptResult?

**Comment by berndbischl** [comment]
and OptPath of length 0 we can construct

**Comment by mb706** [comment]
The consistent thing would be to evaluate the learner once (with makeTuneControlGrid) or as many times as the user chooses (with makeTuneControlRandom, or possibly other optimizers?); x would be a data.frame with 0 columns, y would be the result as usual.

**Comment by berndbischl** [comment]
well i dont know. this is exactly why this is not implemented.
why should i eval the learner more than once? 
and why does it matter with which tunecontrol?

evaluating it ONCE i can MAYBE see.

**Comment by mb706** [comment]
Should a learner with one "logical" parameter be evaluated no more than twice?
Dependence on the control because different controls have different ways of specifying the number of iterations. If a user has some function that generates his `ParamSet` and he expects the tuner to run 100 evaluations with it, he might be happy about consistency. On the other hand, this is obviously so much of an edge case that few people will care; doing anything except throwing an error would be nice.

**Comment by berndbischl** [comment]
ok, so your point is: 

i should eval the learner as often as specified in the tune control? but with its defaults? 
i dunno:
a) that then still will not run the real tuner (so it is a bit inconsisten here)
b) who wants that? it drastically wastes computation time.

now i can see the idea of evaluating it once. maybe. but this is then inconsitent with the tunectrol "budget" setting :)

hence maybe throwing an error is not so bad? if it is hard to write down any behavior that seems reasonable and consistent?

what do you think?

can we maybe talk more about your use case? why do you "hate" the exception here?

my guess is: 
you are wrapping many learner with the tunewrappers. but some have an empty paramset. so you now have a couple of special cases where you need to avoid the tunewrapping with an extra if-case? is that it?

**Comment by berndbischl** [comment]
well. lets look at it like this. my 2cents after thinking:

this is nested resampling. if we have an empty param set, we dont tune. so in the outer loop we should simply do normal model fitting. and tuning is not even started. thats the most resonable thing.
agreed?

so now we need to determine what we technically return.

tuneParams could 
a) return NULL object
b) or a tuneresult object contains NULL slots
and in any case we issue a warning.

i like a) better. what do you think?
