### ISSUE TITLE
Nested crossvalidation with xgboost

### ISSUE THREAD

**Issue by papinisan** [mlr-org/mlr#1904]
I am using resampling wrappers to perform nested crossvalidation with xgboost. Is it possible to access the xgb.Booster objects so that I can use some of xgboost's plotting functions like xgb.plot.tree and xgb.plot.importance?

Here's my code:

```R
dtrain=xgb.DMatrix(data =as.matrix(train[,X_train]), label=y_train)
dtest=xgb.DMatrix(data =as.matrix(test[,X_test]), label=y_test)

traintask=makeClassifTask (data = train,target = "Y_dicho", positive="1")
testtask=makeClassifTask (data = test,target = "Y_dicho", positive="1")

params=makeParamSet(
  makeDiscreteParam("booster",values = "gbtree", tunable=FALSE), 
  makeDiscreteParam("max_depth", values= c(2,3,4,5)),
  makeDiscreteParam("min_child_weight",values=c(2,3,4,5)), 
  makeDiscreteParam("subsample",values=c(.5, .6, .7)), 
)

ctrl=makeTuneControlRandom(maxit = 100L, tune.threshold=FALSE)

inner=makeResampleDesc("CV", iters=3, stratify = TRUE)
outer=makeResampleDesc("RepCV",stratify = TRUE, reps=10, folds=3, predict="both") 

lrn=makeLearner("classif.xgboost", objective="binary:logistic",predict.type = "prob")
lrn=makeTuneWrapper(lrn, measures=auc, par.set=params, control=ctrl, resampling=inner)

parallelStartSocket(cpus = detectCores())

r=resample(lrn, task=traintask, resampling=outer, measures=auc,extract=getTuneResult, show.info = TRUE, models=TRUE)
```

**Comment by larskotthoff** [comment]
You can access the "raw" model with the `getLearnerModel()` function.

**Comment by papinisan** [comment]
Thanks, tried this:

> x1=getLearnerModel(r$models[[1]], more.unwrap=TRUE)
> xgb.plot.tree(feature_names=df_features, model=x1, n_first_tree=1)
Error in xgb.plot.tree(feature_names = df_features, model = x1, n_first_tree = 1) : 
  model: Has to be an object of class xgb.Booster model generated by the xgb.train function.

So does an xgb.Booster object get generated by mlr, or do I have to rerun the model with xgb.train() in order to use xgboost's graphing functions? I'm also happy to use something else that works well with mlr to make tree, feature importance, and partial dependence plots.

**Comment by larskotthoff** [comment]
The learner model is the return value of a call to `xgb.train()`, so everything you get usually should be there as well. mlr only wraps the learner, it doesn't replicate any of its functionality.

**Comment by berndbischl** [comment]
this does what you want:

```


library(mlr)

params=makeParamSet(
  makeDiscreteParam("booster",values = "gbtree", tunable=FALSE), 
  makeDiscreteParam("max_depth", values= c(2,3,4,5)),
  makeDiscreteParam("min_child_weight",values=c(2,3,4,5)), 
  makeDiscreteParam("subsample",values=c(.5, .6, .7)) 
)

ctrl=makeTuneControlRandom(maxit = 2L)

lrn=makeLearner("classif.xgboost")
lrn=makeTuneWrapper(lrn, par.set=params, control=ctrl, resampling=hout)

# r=resample(lrn, task=iris.task, resampling=cv2, extract=getTuneResult, 
  # show.info = TRUE, models=TRUE)


# get mlr models
print(r$models)

# get the first xgboost model
getLearnerModel(r$models[[1]], more.unwrap = TRUE)

# now do whatever you want with the xgboost model

```

**Comment by berndbischl** [comment]
sorry, that you need to do the more unwrap here, the wrappers unfortunately create onion likes layers of wrapping.....

**Comment by papinisan** [comment]
Yes, but what that yields is a description of the parameters used, not an actual xgb.Booster object:

getLearnerModel(r$models[[1]], more.unwrap = TRUE)
Model for learner.id=classif.xgboost; learner.class=classif.xgboost
Trained on: task.id = train; obs = 361; features = 27
Hyperparameters: nrounds=50,verbose=0,objective=binary:logistic,booster=gbtree,max_depth=4,min_child_weight=5,subsample=0.6,colsample_bytree=1,eta=0.05

As far as I can tell, there is no xgb.Booster object:

> xgb1=getLearnerModel(r$models[[1]], more.unwrap = TRUE)
> class(xgb1)
[1] "OversampleModel" "ChainModel"      "WrappedModel"   

Which is why I can't use some of xgboost's plotting functions:

> xgb.plot.tree(feature_names=df_features, model=xgb1, n_first_tree=1)
Error in xgb.plot.tree(feature_names = df_features, model = xgb1, n_first_tree = 1) : 
  model: Has to be an object of class xgb.Booster model generaged by the xgb.train function.

Is the suggestion here that I take those hyperparameters and rerun a model using xgb.train()? So that I can get an xgb.Booster object and use some of xgboost's plotting function? This wouldn't exactly be the same model that's produced by resample(), even if the hyperparameters are the same.

If an xgb.Booster object does not get created or saved within the mlr framework then I will try to do the plots using the tools available with mlr.

**Comment by larskotthoff** [comment]
Can you post the exact call to `xgb.train()` that creates this object and how to access it please? As I've said, mlr doesn't do anything special with the result of `xgb.train()`, so if this object gets created normally it should get created in mlr as well. There's no need for mlr to explicitly create this object as far as I can see.

**Comment by berndbischl** [comment]
@papinisan 
you havent posted an "honest" reproducible example :)
i can see from your output that you are not simply suing a TuneWrapper, but also an OversampleWrapper, correct?

**Comment by berndbischl** [comment]
i guess this is what you really are doing

```
library(mlr)

params=makeParamSet(
  makeNumericParam("osw.rate", lower = 1, upper = 5), 
  makeDiscreteParam("booster",values = "gbtree", tunable=FALSE), 
  makeDiscreteParam("max_depth", values= c(2,3,4,5)),
  makeDiscreteParam("min_child_weight",values=c(2,3,4,5)), 
  makeDiscreteParam("subsample",values=c(.5, .6, .7)) 
)

ctrl=makeTuneControlRandom(maxit = 2L)
lrn=makeLearner("classif.xgboost")
lrn = makeOversampleWrapper(lrn)
lrn=makeTuneWrapper(lrn, par.set=params, control=ctrl, resampling=hout)

r=resample(lrn, task=sonar.task, resampling=cv2, extract=getTuneResult, 
  show.info = TRUE, models=TRUE)

# get mlr models
# print(r$models)

mm1 = r$models[[1]]
print(class(mm1))

# you can unwrap manually like this, just call go down
# $learner$next.model until you can go no further
# (yes this is somewhat "bullshit" and tedious)
mm1a = mm1$learner.model$next.model$learner.model$next.model$learner.model
print(class(mm1a))
# this is better, but getLeafModel is currently unexported
mm1b = getLearnerModel(mlr:::getLeafModel(mm1))
print(class(mm1b))

```

**Comment by berndbischl** [comment]
PS:
mm1a and mm1b are of class XGBooster

**Comment by papinisan** [comment]
@berndbischl Oh no, so sorry about that, you are absolutely right! Thanks for your help, now I can find the xgb.Booster object whether or not I use oversampling wrapper. Thanks!

**Comment by berndbischl** [comment]
ok, on our side we have 2 todos:

1) this needs to go into an FAQ

2) we need a better "getter"
