### ISSUE TITLE
What is the reason for the "variance" feature filter not handling NAs?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#1906]
Many other filters seem to handle NAs, but the variance filter explicitly says [`na.rm = FALSE`](https://github.com/mlr-org/mlr/blob/master/R/Filter.R#L574), so I assume there is some reason for that?

**Comment by berndbischl** [comment]
@mllg can you please respond? you implemented that.

**Comment by mllg** [comment]
Hm, I can't recall, probably just a mistake. Should be safe to set to `na.rm = TRUE`.
