### ISSUE TITLE
Any function to add jitter on the data like in WEKA?

### ISSUE THREAD

**Issue by heoa** [mlr-org/mlr#1909]
By jitter, I mean like adding some random noise on the data values like in WEKA. In comparison to WEKA visualisation, you can change the percentage of the jitter making groups of points more apparent. 

I could not find this functionality of the current MLR.

**Is there any such jitter function or perhaps some sort of noising functions?**

**Comment by larskotthoff** [comment]
Not in mlr, no.

**Comment by ja-thomas** [comment]
might be useful to add as a CPO in the future

**Comment by berndbischl** [comment]
@heoa 
can you post some specific use cases so the quesion becomes clearer?

**Comment by berndbischl** [comment]
and yes, currently the answer is "no"
