### ISSUE TITLE
use purrr::map instead of apply* functions

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#1913]
Reason: Type-safeness

For those who do not know `purrr`: 

`purrr::map` solves the return-type problem of `sapply` and makes the code more readable.

#### Examples:

`map_int`, `map_chr`, `map_lgl` (always return a vector of the respective type) -> `sapply` does not

`map` (always returns a list) -> lapply (equal)

Syntax of both approaches are identical with `purrr` providing some shortcuts and the so called 'formula' notation to do things. See these [slides](https://github.com/Cascadia-R/purrr-tutorial/blob/master/slides.pdf) for more details.

**Comment by berndbischl** [comment]
we NEVER use sapply, but BBmisc:v*apply
solves the same problem

purr is a really heacy dependency

**Comment by berndbischl** [comment]
reopen if you have further comments

**Comment by pat-s** [comment]
thanks for the info!
