### ISSUE TITLE
set param in dependency to resampling

### ISSUE THREAD

**Issue by mcschmitz** [mlr-org/mlr#1914]
I'm trying to tune a learner with a smote wrapper with an unstratified cv due to blocking. As I'm not sure what is the best range for the nearest neighbor parameter of the smote wrapper, I want to tune it over the whole possible parameterspace. 
Since the cv is unstratified the maximum size of nearest neighbors can not simply be calculated and varies over the iterations, what sometimes results in an error, because the parameter is higher than the amout of data in the train set of the cv. 
Setting on.par.out.of.bounds and on.learner.error to "warn" did not fix it. I think this is because of the error handling in the smote function.
So the question is simply: Is there any possibility to set the upper value of sw.nn to a relative value that is the amount of data in the train set of the current cv iteration. 

Thanks.

Ps. Is it even necessary to tune over such a high range or is there any rule of thumb to predict the nn value?

**Comment by berndbischl** [comment]
can you somehow post a reproducible example (on a public simple data set) so we can easier talk about the problem?

**Comment by mcschmitz** [comment]
```
require(mlr) #CRAN 2.10
require(mlbench)

configureMlr(on.learner.error = "warn", on.par.out.of.bounds = "warn")

set.seed(10)
dat = as.data.frame(mlbench.2dnormals(100, cl = 2))
block = sample(x = as.factor(1:5), size = 100, replace = TRUE, 
               prob = c(0.2, 0.5, 0.2, 0.05, 0.05))
# Since my problem is unbalanced I tried to simulate an unbalanced task by 
# setting half of the observations to one fixed Class
dat$classes[sample(1:100, 50)] = 1
task = makeClassifTask(data = dat,target = "classes", blocking = block, 
                       positive = "2")
lrn = makeLearner("classif.svm", kernel = "radial")
lrn = makeSMOTEWrapper(lrn)
rdesc = makeResampleDesc("CV", iters = 5)
ps = makeParamSet(
  makeNumericParam("cost", lower = -8, upper = 4, trafo = function(x) 10^x),
  makeNumericParam("gamma", lower = -8, upper = 4, trafo = function(x) 10^x),
  makeNumericParam("sw.rate", lower = 1, upper = 4),
  makeIntegerParam("sw.nn", lower = 1, upper = 20)
)
ctrl = makeTuneControlRandom(maxit = 100)
res = tuneParams(lrn, task = task, resampling = rdesc,
                 par.set = ps, control = ctrl)

```
If I could do a stratified cv a sw.nn parameter of size 20 would be no problem, since I'm doing a 5 fold cv with 25 positive observations. But because of the blocking by a - again - unbalanced factor the tuning results in the following error. 
```
[Tune] Started tuning learner classif.svm.smoted for parameter set:
           Type len Def  Constr Req Tunable Trafo
cost    numeric   -   - -8 to 4   -    TRUE     Y
gamma   numeric   -   - -8 to 4   -    TRUE     Y
sw.rate numeric   -   -  1 to 4   -    TRUE     -
sw.nn   integer   -   - 1 to 20   -    TRUE     -
With control class: TuneControlRandom
Imputation value: 1
[Tune-x] 1: cost=2.57e-07; gamma=1.48e-06; sw.rate=2.02; sw.nn=7
[Tune-y] 1: mmce.test.mean=0.205; time: 0.0 min; memory: 113Mb use, 180Mb max
[Tune-x] 2: cost=5e-08; gamma=2.76e-08; sw.rate=2.17; sw.nn=19
Warning in train(learner, task, subset = train.i, weights = weights[train.i]) :
  Could not train learner classif.svm.smoted: Error in smote(.task, rate = sw.rate, nn = sw.nn, standardize = sw.standardize,  : 
  You cannot set nn = 19, when the minimal class has size 14!

Error: $ operator is invalid for atomic vectors
```
The error message is right makes totally sense to me, but it occurs as I want to tune the parameter across a space which is not covered by any possibile train set in the cv.

**Comment by berndbischl** [comment]
that seems like a bug in the SMOTE. 
some comments:

1) on.par.without.bounds you should not need. all values are in the bounds.

2) on.learner.error is the correct option. that should ensure that the learner will be a FailureModel in case of such a problem, which only predicts NAs. the hyperparam config that produced such a model would then be treated as "very bad" during tuning. Also have a look at TuneControl::impute.val.

3) the last error message should not appear. it seems the failure model is not constructed correctly.

**Comment by berndbischl** [comment]
this is a minimal example to produce the same bug

```
configureMlr(on.learner.error = "warn")

task = subsetTask(sonar.task, 1:100)
lrn = makeLearner("classif.rpart")
lrn = makeSMOTEWrapper(lrn, sw.nn = 10)
m = train(lrn, task)
p = predict(m, task = task)
```

this produces the same error message, but should predict NAs instead

**Comment by berndbischl** [comment]
problem is here:

> isFailureModel(m)                                                                                                                                                                                         
Error in model$learner.model$next.model :
  $ operator is invalid for atomic vectors

**Comment by berndbischl** [comment]
we should also unit test the preproc wrapper for these types of problems, to make sure

**Comment by mcschmitz** [comment]
Alright. So for now I just have to settle with a smaller search space. 
But Thanks for your time and the awesome package anyway.

**Comment by berndbischl** [comment]
well, i wanted to fix this but it is a pretty annoying thing - to fix in general.
would it help in these cases, if we output a warning and cap the k for the NN to the largest POSSIBLE value given the data at hand, instead of an error.

so if you set k = 20, but the data only has 15 instances, we set it to 15?

**Comment by mcschmitz** [comment]
> would it help in these cases, if we output a warning and cap the k for the NN to the largest POSSIBLE value given the data at hand, instead of an error.

yes this would be great.  this is what i meant initially. The other option would be an error modell and an output of "TuneControl::impute.val" for this tuning iteration right?
