### ISSUE TITLE
Document functions in tests/testthat/helper_helpers.R

### ISSUE THREAD

**Issue by ck37** [mlr-org/mlr#1917]
It would be helpful to add some function documentation to tests/testthat/helper_helpers.R. There are no function descriptions and almost no code comments in that file, which contributes to the challenge of creating new wrappers with test coverage.

Thanks,
Chris

**Comment by berndbischl** [comment]
chris, you are definitely correct here. we have focussed on making the docs good for the exported / user level stuff. but problems like these slow down helpful PRs from the outside.

argh neeed more time

**Comment by pat-s** [comment]
Since we are hardly expecting any contributions in the future from external people and only very few of those should have to touch `helper_helpers.R`, invest/return does not apply here.
