### ISSUE TITLE
FDA: getFunctionalData problems

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1924]
getFunctionalFeatures: seems not perfect.
so i did not export this.
@pfistfl can we fix this quickly? 

1) funct.cols = which(vcapply(object, function(x) class(x)[1L]) == "matrix")
? is.matrix?

2) this seems weird? why?
#' The parameters \dQuote{subset}, \dQuote{features}, and \dQuote{recode.target}
#' are ignored for the data.frame method.

3) you have not docced what happens when there are no func features, what is returned then?
is this consistent for both cases? and an error is usually bad here

**Comment by pfistfl** [comment]
1. Yeah
2. The task method calls getTaskData and hands the params on. 
The data.frame method assumes you already have the required data.frame. 

3.   
We throw an error. In both cases, as the data.frame method is called in the Task method. 
```
if (length(funct.cols) == 0L)
    stop("No functional features in the **data")**
```


Shall I change or will you?

**Comment by pfistfl** [comment]
I can create a PR on top of #1890, What do you want me to do for 2 and 3?

**Comment by berndbischl** [comment]
you are too fast :)
i will merge into master now, in the next couple of hours
brnach from the master then pls

**Comment by berndbischl** [comment]
first of all:

all arguments: gubset = NULL, features, recode.target = "no"
seem to be quite useless, also for tasks? 
i mean the target is not used anymway, and subsetting cols and features I can do manually?

I think the whole method should be removed / completely changed.
getFunctionalFeatures could return a char vector just of the functional feature names.

also note: in many cases in the learner algos you dont NEED to call that function?
I mean if a learner can ONLY handle functional data, you KNOW that in the task and in data there will be ONLY functional data?
