### ISSUE TITLE
FDA: reiterate unit test file test_base_fda_extractFDAFeatures

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1926]
1) I had to change a few rows because I removed extractFDA MinMax, Mean, Median

So we have some inactive test lines like this now:

```
+  # expect_subset(colnames(df), c("UVVIS.mean", "NIR.min", "NIR.max", "heatan", "h20"))
+  # expect_true(ncol(df) == 6L)
```

These should be reenabled / changed to something similar.

2) I found when looking at the code that many lines are weird and bad. The whole file should be reread and improved

**Comment by pfistfl** [comment]
Should be fixed for now.
