### ISSUE TITLE
FDA: multiresolution feature extraction is not documented properly

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#1929]
the english is bad and the method is not explained clearly

**Comment by berndbischl** [comment]
i also do not see any asserts for the args of the constructer.
pls fix

**Comment by pfistfl** [comment]
The code quality is also not good (for-loops etc.)

I think this does not matter, as we are going to change to the C Version soon? 

Added asserts and tried to explain more concisely. Maybe you can iterate afterwards, because you understand the function better.
