### ISSUE TITLE
Cubist learner integrated in mlr?

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr#1931]
Hello,

Just a question: Do you have already integrated the "Cubist" learner from R-package "Cubist" into mlr? It could be quite useful. Cubist is similar to Random Forest, but uses some optimization inside. 

Here you may find the vignette: 
[https://cran.r-project.org/web/packages/Cubist/vignettes/cubist.pdf](url)

Just an idea....

Best regards,
Markus

**Comment by berndbischl** [comment]
Why not simply read NEWS:

Or check the tutorial?

regr.cubist is already included

**Comment by mareichhoff** [comment]
Bernd, I can't read.

No, I checked something else: listLearners() . The output is not so user friendly. Just the first 6 lines are shown. I used 

data <- as.data.frame(listLearners()) and then
data[, -5L] 

to print without the "note" column that is quite disturbing (in this case!). 

Thank you anyway for your answer.

**Comment by PhilippPro** [comment]
I remember I had same problems at the beginning ;)
