### ISSUE TITLE
Feature selection for learners from the same family

### ISSUE THREAD

**Issue by ir1979** [mlr-org/mlr#1945]
How can I use different learners of the same model but with different (hyper-)parameters. For instance, I want to find the best value of minsplit in "regr.rpart" (to the best of my knowledge I cannot embed feature selection wrapper within a tune wrapper). I have to do it manually as following:

```
library('mlr')

ctrl = makeFeatSelControlSequential(method = "sfbs")

visc = read.csv("ds.csv")
regr.task = makeRegrTask(id = "ds.regr.task", data = visc, target = "target")

learnersList = list()

for (i  in 2:20)
{
  lrn = makeLearner("regr.rpart", minsplit=i)
  
  lrnFeatSel = makeFeatSelWrapper(learner = lrn, resampling = cv2, control = ctrl, show.info = FALSE)

  # make unique ids
  lrnFeatSel$id = sprintf("%s.%d", lrnFeatSel$id, i)

  # add the new learner  
  learnersList[[length(learnersList)+1]] = lrnFeatSel
  
}

res = benchmark(tasks = regr.task, learners = learnersList, resampling = cv3, show.info = TRUE)

```

Is there any better way to do this?

**Comment by larskotthoff** [comment]
You can actually nest tune and feature selection wrappers now -- this was merged in #1871. This change isn't on CRAN yet, so use the github version.

**Comment by ir1979** [comment]
Should I use devtools::install_github("mlr-org/mlr") ?

**Comment by berndbischl** [comment]
can you please state more clearly what you want?

**Comment by berndbischl** [comment]
is it really parameter tuning and feature selection combined?

**Comment by ir1979** [comment]
Yes, I want to find the best mse (with feature selection) for any setting of rpart. Is it incorrect?

**Comment by ir1979** [comment]
By the way, the final mse is important for me, not the number of features nor the setting of the tree.

**Comment by ir1979** [comment]
after using devtools::install_github("mlr-org/mlr") and restarting rstudio, it shows me "Error in makeBaseWrapper(id, learner$type, learner, learner.subclass = c(learner.subclass,  : 
  Cannot wrap a tuning wrapper around another optimization wrapper!"

**Comment by larskotthoff** [comment]
Ah sorry, the change allows the other way round, i.e. a tuning wrapper inside a feature selection wrapper. This should work for what you want as well though.

**Comment by ir1979** [comment]
I changed the place of feature selection wrapper and tune wrapper (Tune wrapper is now embedded in Feature selector). It works now! But the reverse shows the above error! It seems I have to do my job manually :(

**Comment by larskotthoff** [comment]
If all you're interested in is the final MSE, it shouldn't matter which way you layer it.

**Comment by ir1979** [comment]
Why I cannot do the reverse?

**Comment by ir1979** [comment]
In fact, I don't want a tuner (as an optimization engine), but an iterator over a number of hyperparameters of a learner. In other words, I want to make a list of learners with some slightly different hyper parameters and of course with different unique Ids.

**Comment by larskotthoff** [comment]
Hmm, I guess in principle there's no reason to forbid this. In general, nesting optimization wrappers can lead to problems though and this is what the current code checks. The end result should be the same either way though.

**Comment by larskotthoff** [comment]
Can you describe what you want to do with it in the end? Are you looking for some kind of bagging?

**Comment by ir1979** [comment]
No, I want to find the best model with any setting that minimizes mse.

**Comment by larskotthoff** [comment]
That sounds to me like you definitely want the optimization wrapper. Why do you think you don't want that?

**Comment by ir1979** [comment]
Yes, finally i will choose the best one. But in the paper, I should report the trend also.

**Comment by larskotthoff** [comment]
Why? What do you want to show in your paper? You can get the optimization path from a tune wrapper, e.g. (from the tutorial)

```
print(head(as.data.frame(res$opt.path)))
#>            C     kernel     sigma degree mmce.test.mean dob eol
#> 1 -2.8894525    polydot        NA      4           0.06   1  NA
#> 2 -2.6793542 vanilladot        NA     NA           0.04   1  NA
#> 3 -0.7855061     rbfdot 11.049783     NA           0.68   1  NA
#> 4  1.7678978    polydot        NA      5           0.14   1  NA
#> 5  9.7729840 vanilladot        NA     NA           0.04   1  NA
#> 6 -2.7930352     rbfdot -7.198476     NA           0.36   1  NA
#>   error.message exec.time
#> 1          <NA>     0.028
#> 2          <NA>     0.023
#> 3          <NA>     0.025
#> 4          <NA>     0.023
#> 5          <NA>     0.023
#> 6          <NA>     0.026
```

**Comment by ir1979** [comment]
Do these optimizers interact with each other? In what way the layering may affect the result?

**Comment by larskotthoff** [comment]
The outer optimizer calls the inner one as a black box, i.e. there's no interaction beyond the outer feature selection wrapper asking the tuning wrapper to get the best parameter settings for a given set of features. If layered the other way, the feature selection wrapper would get the best feature set for a given parameterisation. If given enough time, both ways of layering should get the same result.

**Comment by ir1979** [comment]
Thank you for your help. 

As a side note from the computer science community from wikipedia: In computer programming, "orthogonality in a programming language means that a relatively small set of primitive constructs can be combined in a relatively small number of ways to build the control and data structures of the language" (Sebesta, Robert. Concepts of Programming Languages.). 

Therefore, any wrapper as a learner may be embedded within another learner. I cannot imagine the fail situation.

**Comment by ir1979** [comment]
In this case, if the performance in terms of execution time is the same?

**Comment by larskotthoff** [comment]
Well, optimisation wrappers are by no means primitive constructs. One thing to take into account is the size of the respective optimisation spaces. If you have only a few features and a large parameter space and put the feature selection wrapper on the outside, each evaluation of a feature set will take a very long time if you want to explore the large parameter space adequately. In this case it's probably a better idea to layer the other way round.

For the execution time, you set the limit yourself by restricting the number of evaluations.

**Comment by ir1979** [comment]
What do mean by "you set the limit yourself by restricting the number of evaluations."! 
I did not set any limitation there?

**Comment by larskotthoff** [comment]
How exactly you set it depends on the wrapper you use, for example for the sequential feature selection wrapper it's the `maxit` argument. The default is to search the space exhaustively in this case.

**Comment by ir1979** [comment]
Thank you really. Hope to see a complete book on mlr like the caret package.

**Comment by larskotthoff** [comment]
We currently have no plans for this, but the tutorial is quite comprehensive.

**Comment by ir1979** [comment]
I checked it (not sure the last version). But I could not find some issues like the mystery of next.learner after benchmark, parallel computing based on batch job, devtools for installing the package from github. By the way, the tutorial is really well written.

**Comment by larskotthoff** [comment]
Thanks.

The tutorial has a [section on parallelization](https://mlr-org.github.io/mlr-tutorial/devel/html/parallelization/index.html). How to install the package from Github is on our github front page. Not sure what you mean by the mystery of next.learner.

**Comment by ir1979** [comment]
When I use tune wrapper or feature selection wrapper, the model constructed based on the best result of inner resampling is saved in the next.model. I could not find some related documentation about this in the PDF, but two unrelated ones.

**Comment by larskotthoff** [comment]
Right, we don't really have documentation on nested wrappers yet.

**Comment by ir1979** [comment]
Thank you again for your help. mlr is really interesting.
