### ISSUE TITLE
ROC analysis for a regressor built with FeatSelWrapper

### ISSUE THREAD

**Issue by vrgaliano** [mlr-org/mlr#1946]
I am trying to apply a ROC analysis from a learner of class FeatSelWrapper:

rdesc = makeResampleDesc("Bootstrap", iters = 100, predict = "both")
b632plus.mse = setAggregation(mse, b632plus)
lrn.rf = makeLearner("regr.randomForest", ntree = 2500)
ctrl = makeFeatSelControlSequential(method = "sfs", alpha = 0.001)
lrn = makeFeatSelWrapper(lrn.rf, resampling = rdesc, measures = b632plus.mse, control = ctrl, show.info = TRUE)
rpart.sfs = train(lrn, task = regr.task)
df = generateThreshVsPerfData(rpart.sfs, measures = list(fpr, tpr, mmce))

**Comment by larskotthoff** [comment]
What is your question?

**Comment by vrgaliano** [comment]
I get the following error message:

Error in UseMethod("generateThreshVsPerfData") : no applicable method for 'generateThreshVsPerfData' applied to an object of class "c('FeatSelModel', 'BaseWrapperModel', 'WrappedModel')"

How could I perfom a ROC analysys with a learner obtained by feature selection wrapper?

**Comment by larskotthoff** [comment]
You can plot ROC curves from the predictions of the model. See [the tutorial](https://mlr-org.github.io/mlr-tutorial/devel/html/roc_analysis/index.html).

**Comment by vrgaliano** [comment]
Dear Lars, thanks for your reply.
It seems that it is not supported for regression:

> rdesc = makeResampleDesc("CV", iters = 10)
> pred_rf.sbs = predict(rf.sbs, task = regr.task, resampling = rdesc)
> df = generateThreshVsPerfData(pred_rf.sbs, measures = list(fpr, tpr,
mmce))


Error in checkPrediction(obj, task.type = "classif", binary = TRUE,
predict.type = "prob") :
  Prediction must be one of 'classif', but is: 'regr'

2017-07-26 19:02 GMT+02:00 Lars Kotthoff <notifications@github.com>:

**Comment by berndbischl** [comment]
> Prediction must be one of 'classif', but is: 'regr'

well, of, course you cannot do ROC for regression? thats a technique for binary classification?

**Comment by vrgaliano** [comment]
Well, it is not exactly regression either. I have a variable (nitrates
concentration) and I am interested in those instances that are higher than
a certain value (37.5). I rescaled the variable into 0s (<37.5) and 1s
(instances >37.5) values. This way I am predicting values between the range
of 0 to 1, which is somehow a probability. Perhaps this approach is not
correct using mlr library, but I did something similar using e1071 library.
Any suggestion on how to improve my analysis in mlr?.
Thanks

Victor

2017-07-26 19:56 GMT+02:00 Bernd Bischl <notifications@github.com>:

**Comment by larskotthoff** [comment]
What are you actually investigating?

**Comment by larskotthoff** [comment]
You can predict probabilities in mlr for classification. It sounds like this is what you should do.

**Comment by berndbischl** [comment]
i think we answered here
