### ISSUE TITLE
get prediction from a featureSelectionWrapper 

### ISSUE THREAD

**Issue by vrgaliano** [mlr-org/mlr#1948]
Hi,
I would like to calculate the ROC curve from the predictions of the test obtained by a featureslection wrapper. I have no idea on how to access to the prediction of that test.

ctrl = makeFeatSelControlSequential(method = "sfs", alpha = 0.001)
rdesc = makeResampleDesc("Bootstrap", iters = 100)
mmceB632plus = setAggregation(mmce, b632plus)
lrn.rf = makeLearner("classif.randomForest",  ntree = 2500, predict.type = "prob")
lrn = makeFeatSelWrapper(lrn.rf, resampling = rdesc, measures = mmceB632plus, control = ctrl, show.info = TRUE)
mod.rf.sfs = train(lrn, task = class.task)

**Comment by larskotthoff** [comment]
The same way you get predictions from any other model: `predict(mod.rf.sfs, test)`. Please read the documentation and tutorial.

**Comment by vrgaliano** [comment]
I am afraid that I cannot access that model using predict... However, I can access the features using getFeatSelResult.

predict(mod.rf.sfs, test)
Error in predict(mod.rf.sfs, test) : object 'mod.rf.sfs' not found

**Comment by larskotthoff** [comment]
You didn't even mention that you wanted to get the features. I've taken the name `mod.rf.sfs` from YOUR code. Please post COMPLETE and REPRODUCIBLE examples if you want help.

**Comment by vrgaliano** [comment]
Sorry, it was at the end of the script and I thought it was irrelevant. I
have rewritten the code using the iris dataset.

classif.task = makeClassifTask(data = iris, target = "Species")
ctrl = makeFeatSelControlSequential(method = "sfs", alpha = 0.001)
rdesc = makeResampleDesc("Bootstrap", iters = 100, predict = "test")
mmceB632plus = setAggregation(mmce, b632plus)
lrn.rf = makeLearner("classif.randomForest",  ntree = 2500, predict.type =
"prob")
lrn = makeFeatSelWrapper(lrn.rf, resampling = rdesc, measures =
mmceB632plus,
                         control = ctrl, show.info = TRUE)
mod.rf.sfs = train(lrn, task = classif.task)
pred.rf.sfs = predict(mod.rf.sfs, test)

sfeats.sfs = getFeatSelResult(mod.rf.sfs)
sfeats.sfs$x
analyzeFeatSelResult(sfeats.sfs)

2017-07-27 1:02 GMT+02:00 Lars Kotthoff <notifications@github.com>:

**Comment by larskotthoff** [comment]
Your example doesn't work for me, I'm getting

```
> mod.rf.sfs = train(lrn, task = classif.task)
[FeatSel] Started selecting features for learner 'classif.randomForest'
With control class: FeatSelControlSequential
Imputation value: Inf
[FeatSel-x] 1: 0000 (0 bits)
Error in FUN(X[[i]], ...) : 
  Aggregation 'b632plus' not compatible with resampling! You have to set arg 'predict' to 'both' in your resample object, instead it is 'test'!
```

**Comment by vrgaliano** [comment]
The "predict" parameter in "makeResampleDesd" can be change from "test" to
"both".Although it does not work either. I get the errror message:
Error in checkClass(x, classes, ordered) : object 'test' not found

library(mlr)
classif.task = makeClassifTask(data = iris, target = "Species")
ctrl = makeFeatSelControlSequential(method = "sfs", alpha = 0.001)
rdesc = makeResampleDesc("Bootstrap", iters = 100, predict = "both")
mmceB632plus = setAggregation(mmce, b632plus)
lrn.rf = makeLearner("classif.randomForest",  ntree = 2500, predict.type =
"prob")
lrn = makeFeatSelWrapper(lrn.rf, resampling = rdesc, measures =
mmceB632plus,
                         control = ctrl, show.info = TRUE)
mod.rf.sfs = train(lrn, task = classif.task)
pred.rf.sfs = predict(mod.rf.sfs, test)

sfeats.sfs = getFeatSelResult(mod.rf.sfs)
sfeats.sfs$x
analyzeFeatSelResult(sfeats.sfs)

2017-07-27 2:23 GMT+02:00 Lars Kotthoff <notifications@github.com>:

**Comment by larskotthoff** [comment]
This is a problem with your code, nothing to do with mlr. Please fix your code before asking for help.
