### ISSUE TITLE
Error in SMOTEing constant Features

### ISSUE THREAD

**Issue by mcschmitz** [mlr-org/mlr#1951]
I am still not sure if this is a bug or if I just misunderstood the smote function. 
Please take a look at the following snippet

```
Class = c(rep("1", 150), rep("2", 50))
x = c(rep("No", 125), rep("Yes", 75))
data = data.frame("Class" = Class, "X" = x)
task = makeClassifTask(data = data, target = "Class", positive = "2")

table("Class" = data$Class, "X" = data$X)

     X
Class  No Yes
    1 125  25
    2   0  50

taskOvr = smote(task, rate = 3)
dataOvr = getTaskData(taskOvr)
table("Class" = dataOvr$Class, "X" = dataOvr$X)

     X
Class  No Yes
    1 125  25
    2 100  50
```

So my tasks consists of 1/4 positive observations of class "2" and 3/4 negative observations of class "1". 
After applying the smote function the task is balanced but here's the point. I've always thought the oversampling is only happening in the space of the positve points. And since all the positive points have a X value of "Yes", all the synthetic points of class "2" should have the value "Yes" as well?
Am I wron or should the data structure after Smote look like this?
```
     X
Class  No Yes
    1 125  25
    2   0  150
```

**Comment by mcschmitz** [comment]
As the title suggests I had this issue only with features that are constant in the positve class.
Though I'm still not sure if this is a bug I managed to the output the way it seems right via  replacing the lines 136 - 138
```
if (!is.num[i]) 
        res[, i] = as.factor(as.integer(res[, i])) 
      levels(res[, i]) = levels(x[, i]) 
```
with
```
if (!is.num[i]){
        res[, i] = as.factor(as.integer(res[, i]))
        if(length(unique(res[, i])) != length(levels(x[, i]))){
          res[, i] = levels(x[, i])[as.numeric(as.character(res[, i]))]
        }
        else{
          levels(res[, i]) = levels(x[, i])
        }
      }
```

**Comment by AlexEngelhardt** [comment]
This does not happen for numeric features:

```
>   d = data.frame(
+     x = c(rep(2, 50), rep(4, 50)),
+     y = c(rep("1", 80), rep("2", 20))
+   )
>   task = makeClassifTask(data = d, target = "y")
>   task2 = smote(task, rate = 4, nn = 2L)
Warning in cluster::daisy(x.min, stand = standardize) :
  ‘x’ has constant columns 1; these are standardized to 0
> table(getTaskData(task2))
   y
x    1  2
  2 50  0
  4 30 80
```
