### ISSUE TITLE
no getOptPath()?

### ISSUE THREAD

**Issue by Prometheus77** [mlr-org/mlr#1953]
Given that so many mlr classes and objects have getters, it feels inconsistent to have to do as.data.frame(tr$opt.path) instead of just using a getOptPath. Should also include an as.data.frame=TRUE/FALSE option.

**Comment by larskotthoff** [comment]
`getOptPath` is a ParamHelpers function, please open the issue [there](https://github.com/berndbischl/ParamHelpers).

**Comment by berndbischl** [comment]
he has a point here, he means that we usually provide getters for objects.

**Comment by berndbischl** [comment]
also getOptPath just simply does not exist as a function?

**Comment by giuseppec** [comment]
@berndbischl do you want to introduce, e.g., a `getOptPath(obj, as.df = TRUE)` function for `TuneResult` objects?

**Comment by scholbeck** [comment]
Working on it.
