### ISSUE TITLE
Significance test models tunes using resample in mlr

### ISSUE THREAD

**Issue by aminevsaziz** [mlr-org/mlr#1954]
As the title suggest is there away to perform a ranking or significance test like friendman or wilcoxon on models tuned using resample in mlr.

**Comment by larskotthoff** [comment]
There's a section on that ("Comparing learners using hypothesis tests") in the [benchmark section of the tutorial](https://mlr-org.github.io/mlr-tutorial/devel/html/benchmark_experiments/index.html).

**Comment by aminevsaziz** [comment]
But thats for benchmark class & need more that 1 task to perform the ranking.

**Comment by larskotthoff** [comment]
You can use an arbitrary number of tasks in benchmark experiments. It sounds like this is what you want here. If not, please describe in detail.

**Comment by aminevsaziz** [comment]
Well simply i made an 3 objective function of 3 different learner than tune each function using mbo the best opt parameters was used to train the model on the whole data & evaluate its performance on unseen data.
All i want is to performe a ranking or even better a significance test on auc acc and kappa results obtained in each model same as caret package do.

**Comment by larskotthoff** [comment]
So you want to compare the best parameterisations of the 3 learners? Or the best and default configuration? In either case, construct a benchmark experiment with the learners and tasks you want to investigate.

**Comment by berndbischl** [comment]
his question is i think the following:

he runs multiple learners on 1 task. mlr only supports the Demsar way of testing when you have run on multiple data sets. 

Is that the question ?

**Comment by berndbischl** [comment]
which statistical test do you think would be approrriate?

**Comment by aminevsaziz** [comment]
@berndbischl sorry being late.. and yes my question is like what suggested.
I iaming at friendman or wilconxon tests to test out if there is a statitistical significance /difference between auc and acc scores in each learner so that way i can say learner B is ranked first somehow similar to what caret so when you want to compare learners to each others...

**Comment by ja-thomas** [comment]
@aminevsaziz is the question resolved? Either in #1973 or here?

**Comment by aminevsaziz** [comment]
@ja-thomas nothing change really, i tried my best yet no way to perform those significance tests on the final auc/kappa results 😂 😂, so i abandoned performing the test, because theres no clue how to perfome it properly on mlr. 😖😖😫
