### ISSUE TITLE
mlr 2.12 is not compatible with tasks created in older versions

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1960]
Just stumbled upon this. With the addition of the functional features, tasks that were created prior to that cannot be used anymore.

```
> train(lrn, mnist.task)
Error in if (functionals.as == "dfcols" && hasFunctionalFeatures(task)) { :
  missing value where TRUE/FALSE needed
```

This is not that bad since you normally just keep the data and you still can grab the data from the environment of the task and create a new task.

Maybe add a note to NEWS.

**Comment by mb706** [comment]
>you still can grab the data from the environment of the task and create a new task.

Does `getTaskData` work, or does the user need to know about `task$env$data`?

**Comment by ja-thomas** [comment]
`getTaskData` doesn't work, you need to directly grab the data from `task$env$data`

**Comment by mb706** [comment]
Maybe this is a bad thing if the user cannot rescue his data without actually knowing the task's internals? Possible solution would be to change `checkTask` to make old tasks compatible.

**Comment by berndbischl** [comment]
i am going to close this.

reason we always had this problem, and it will never go away. this will always happen, when we change the internal structure of objects. and to the best of my knowledge
- every other R package faces the same problem
- i dont know any (reasonable) way in R to prevent this

either tell me a simple solution or users have to live with this
