### ISSUE TITLE
mlr & lightgbm & grid-search & multiclass

### ISSUE THREAD

**Issue by suyi19890508** [mlr-org/mlr#1964]
I wan't optimize the params of lightgbm throught the mlr pacakge, which can gird-search. So I make my Learner with R language, but I got error "Error in checkPredictLearnerOutput(.learner, .model, p) : 
  predictLearner for classif.lgb has returned a class numeric instead of a matrix!"
My computer: win10, Microsoft R Server9.1.0, 2cores. The code could download here:
[makemylearner.txt](https://github.com/mlr-org/mlr/files/1202279/makemylearner.txt
[tuneparams.txt](https://github.com/mlr-org/mlr/files/1202280/tuneparams.txt)
)
Thank you very much!

**Comment by larskotthoff** [comment]
The error message tells you what's wrong: you're returning a numeric vector, and mlr expects a matrix. You need to postprocess what the learner returns. Have a look at the other learners for examples.
