### ISSUE TITLE
Integer parameter ignored in TuneControlGrid

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#1965]
Every time I start this build `mtry=6` is simply not used as an option for `mtry`. 
I have no clue why. Did this happen before to anyone?

```
[Tune] Started tuning learner classif.ranger for parameter set:
              Type len Def            Constr Req Tunable Trafo
mtry       integer   -   -           1 to 11   -    TRUE     -
num.trees discrete   -   - 10,50,100,300,700   -    TRUE     -

With control class: TuneControlGrid

[Tune-x] 1: mtry=1; num.trees=10
[Tune-x] 4: mtry=4; num.trees=10
[Tune-x] 2: mtry=2; num.trees=10
[Tune-x] 3: mtry=3; num.trees=10
[Tune-x] 6: mtry=7; num.trees=10
[Tune-x] 9: mtry=10; num.trees=10
[Tune-x] 5: mtry=5; num.trees=10
[Tune-x] 8: mtry=9; num.trees=10
[Tune-x] 7: mtry=8; num.trees=10
[Tune-x] 10: mtry=11; num.trees=10

[Tune-x] 11: mtry=1; num.trees=50
```

**Comment by berndbischl** [comment]
if you dont post reproducible code, we cannot help you ;-)

**Comment by berndbischl** [comment]
you need to post the ParamSet and which tuning method you chose

**Comment by jakob-r** [comment]
From what I can see it's the equivalent of
```r
> library(ParamHelpers)
> ps = makeParamSet(makeIntegerParam('mtry', 1, 11), makeDiscreteParam('num.trees', c(10,50,100,300,700)))
> generateGridDesign(ps, resolution=10)
   mtry num.trees
1     1        10
2     2        10
3     3        10
4     4        10
5     5        10
6     7        10
7     8        10
8     9        10
9    10        10
10   11        10
11    1        50
...
```
The reason for `mtry==6` not beeing generated is simply the following
```r
> round(seq(from=1, to=11, length.out=10))
 [1]  1  2  3  4  5  7  8  9 10 11
```

You might want to use a random design. Tuning over a grid gives you always a fixed set of hyper-parameters.

Reopen if you still see a bug.

**Comment by berndbischl** [comment]
> From what I can see it's the equivalent of

thats exactly what i guessed as well :)

**Comment by pat-s** [comment]
@jakob-r thanks! did not know that there is a "hidden" resolution behind Integer Params 

In this case I want to use a grid tuning on purpose. 

So the simple solution here would be to set `resolution = 11` in `makeTuneControlGrid`. 

@berndbischl I know, next time with reprex. Was a quick issue before some unexpected longer offline time..

**Comment by berndbischl** [comment]
1) please also note that you can always discretize params yourself with makeDiscreteParams

so like
makeDiscreteParams("myint", values = 1:11)

2) about the warning: i dont know. it is well-documented, correct? 
the whole point is for a setup like this:
makeIntegerParam("k", lower = 1, upper = 1000)
i dont want to iterate 1000 values. 
so maybe i set resolution = 50.
why should i now by hassled with a warning? when i am doing something very normal and reasoanable?

**Comment by jakob-r** [comment]
I agree with @berndbischl. Also the argument `resolution` is not really hidden. It's right there as soon as you type `makeTuneControlGrid`. We can argue that we a) might not want to have a default? or b) that we call it `grid.solution` in mlr to make it more obvious. Both solutions are annoying because they change the API.
