### ISSUE TITLE
how to perform significance difference between results in mlr

### ISSUE THREAD

**Issue by aminevsaziz** [mlr-org/mlr#1973]
I'm struggling to perform a Friedman and Wilcoxon signed-rank test on mmce and kappa scores of couple learners with just a single dataset task & using resmaple instead of benchmark experiment like  the example below :
```
library(mlr)
library(mlrMBO)

rdesc = makeResampleDesc("Subsample", iters = 5)

r = resample("classif.rpart", iris.task, rdesc, measures = list(mmce,kappa))
r2 = resample("classif.lda", iris.task, rdesc, measures = list(mmce,kappa))
r3 = resample("classif.randomForest", iris.task, rdesc, measures = list(mmce,kappa))
```
p.s: i asked same question in #1954  but clear answer.

**Comment by jakob-r** [comment]
Please try to avoid duplicated issues.

Do you just want to do this
```r
> wilcox.test(r$measures.test$mmce, r2$measures.test$mmce)

        Wilcoxon rank sum test with continuity correction

data:  r$measures.test$mmce and r2$measures.test$mmce
W = 24, p-value = 0.01812
alternative hypothesis: true location shift is not equal to 0

Warning message:
In wilcox.test.default(r$measures.test$mmce, r2$measures.test$mmce) :
  cannot compute exact p-value with ties
```

**Comment by aminevsaziz** [comment]
Thank you @jakob-r  ...thats very helpful and i think Friedman goes same way as the example above just changing "wilcox.test" to "friedman.test" right @jakob-r ?

**Comment by jakob-r** [comment]
Yes. But best read the help pages of each function. Also make sure to call
```r
rdesc = makeResampleInstance(rdesc, task = iris.task)
```
So that all resamplings are done on exactly the same train/test-splits so you can set `paired = TRUE` and get higher power of your test.
