### ISSUE TITLE
getHyperPars not working with character name

### ISSUE THREAD

**Issue by FlorianPargent** [mlr-org/mlr#1979]
getHyperPars only works with learner object not with the character name as claimed in the documentation

```r
getHyperPars("classif.randomForest")
```
Fehler in getHyperPars("classif.randomForest") : 
  Assertion on 'learner' failed: Must have class 'Learner', but has class 'character'.

**Comment by larskotthoff** [comment]
Ah, this is because we used the learner template in the documentation, which everywhere else can be a string as well as a learner. I guess in this particular case a string doesn't really make sense as it would only get the default values, so we could just change the documentation.

Thoughts?

**Comment by berndbischl** [comment]
we can simply change it to be consistent.

but as lars pointed out: not very usefel

getParamSet("classif.rpart") is much more useful
