### ISSUE TITLE
adjrsq: wrong keyword in 'implemented performance measures'

### ISSUE THREAD

**Issue by jeonghyunwoo** [mlr-org/mlr#1982]
'measures = list(adjrsq)' occurs error.
'adjrsq' is wrong keyword. 'arsq' is correct

**Comment by ja-thomas** [comment]
Can you give context? 

`adhrsq` is not a valid measure in mlr so the first line will obv. give you an error? But that line is not in the code of mlr.

**Comment by jakob-r** [comment]
I will close until further details are given.
