### ISSUE TITLE
plotLearnerPredictions does not accept "none" keyword for err.mark

### ISSUE THREAD

**Issue by Greforb** [mlr-org/mlr#1983]
```r
lrn = makeLearner("classif.rpart")
my.task = binaryclass.task
plotLearnerPrediction(learner = lrn, task = my.task, err.mark = "none")
```
Will give the error "Error in !data$.err : invalid argument type"
Untill fixed this can be handled by setting err.col="black" and err.size = 0.5

**Comment by ja-thomas** [comment]
Thanks for reporting, should be fixed with #1996
