### ISSUE TITLE
Predict probs for surv.randomForestSRC"

### ISSUE THREAD

**Issue by edvbb** [mlr-org/mlr#1986]
In 
`makeLearner("surv.randomForestSRC",  predict.type = "prob")`
`Error in setPredictType.Learner(learner = wl, predict.type = predict.type) : 
  Trying to predict probs, but surv.randomForestSRC does not support that!`
and we get the model with responses

Can we predict risks or survival function with individual prob of survival?
thanks!

**Comment by berndbischl** [comment]
@mllg

**Comment by PhilippPro** [comment]
Probably you can get the probabilities like in the ibrier measure: 
```

targets = getTaskTargets(task)
    tn = getTaskTargetNames(task)
    f = as.formula(sprintf("Surv(%s, %s) ~ 1", tn[1L], tn[2L]))
    newdata = getTaskData(task)[model$subset, ]
    max.time = extra.args$max.time %??% max(newdata[[tn[1L]]])
    grid = seq(0, max.time, length.out = extra.args$resolution)

    probs = predictSurvProb(getLearnerModel(model, more.unwrap = TRUE), newdata = newdata, times = grid)
```
Does it solve your problem?
