### ISSUE TITLE
Revert PR #1980

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1991]
#1980 breaks mlr and we didn't realize this as travis is not running tests at the moment.

See #1934 

We have 4 commits after the broken PR (maybe these are broken too, we don't really know).

**Comment by ja-thomas** [comment]
Instead we can also try to fix it directly, might be easier. Also it seems that travis is doing something again as tests in PR #1989 are failing.

**Comment by larskotthoff** [comment]
I've reverted this. I'm also not going to merge anything before we are *sure* that Travis is doing what it's supposed to do. Hopefully Jenkins will be back in the next few weeks as well.

**Comment by pat-s** [comment]
ahh sorry, did not see that tests are not running on travis. just checked the sign whether it passed or not.

I'll update the PR and ensure that tests are running and passing. 
sorry for the inconvenience!
