### ISSUE TITLE
tuneWrapper bug: threshold tuning does not work for binary classification using mbo 

### ISSUE THREAD

**Issue by Coorsaa** [mlr-org/mlr#2002]
when using a tuneWrapper for tuning binary classification with mbo, enabling threshold tuning throws an error. See example below: 

```r
lrn = makeLearner("classif.randomForest", predict.type = "prob")
ps = makeParamSet(
  makeIntegerParam("ntree", lower = 20L, upper = 50L)
)
ctrl = makeTuneControlMBO(budget = 10L, tune.threshold = TRUE)
rdesc = makeResampleDesc("Holdout")
lrn = makeTuneWrapper(lrn, rdesc, mmce, ps, ctrl, show.info = TRUE)
mod = train(lrn, sonar.task)
```

throws the following error:
```r
Error in train(lrn, sonar.task) : 
  Assertion on 'predict.threshold' failed: Must be of type 'numeric', not 'NULL'.
```
However, tuning with ````tune.threshold = FALSE```` or tuning without the wrapper via ````tuneParams```` is working.

this is related to issue #1675

**Comment by berndbischl** [comment]
i am nearly finsihed here. @Coorsaa thx for the report. there was even a FIXME in the mlr code about this

**Comment by Coorsaa** [comment]
that's great news @berndbischl . Let me know if you need any support here.
