### ISSUE TITLE
makePreprocWrapper should allow for modification of learner properties

### ISSUE THREAD

**Issue by notiv** [mlr-org/mlr#2003]
When creating a preproc wrapper, there is no possibility to change the properties of the learner that is being wrapped (right?). I believe that would be a useful feature.

Here my use case: I would like to use xgboost for classification. As xgboost works only with numeric features, any categorical variables need to be "dummy-fied". Assuming we have a categorical variable with hundreds of levels, an out-of-the-box dummy-fication would create a large dataframe. Instead of reducing the number of levels using mergeSmallFactorLevels, I wrote a custom Wrapper that takes as input the final number of levels (which I also want to optimize) and then wrote another one that performs the dummy-fication (I could have used the createDummyFeatures, but I'm doing some further preprocessing in this function).  Now when I try to train the model I get the following error: 
"Error in checkLearnerBeforeTrain(task, learner, weights) :  Task ... has factor inputs in ... but learner 'classif.xgboost.preproc.imputed.preproc.preproc' does not support that". I believe the last two "preprocs" are the wrappers I mentioned. 

I don't think this can be done without creating a new learner (I read the documentation and [this comment](https://github.com/mlr-org/mlr/issues/1853#issuecomment-308357166) from @jakob-r, I hope I am not missing something). Any feedback would be much appreciated!

**Comment by jakob-r** [comment]
Okay. Your wrapped learner seems to be really wrapped. What you can do is make use of S3:
```r
library(mlr)
lrn = makeLearner("classif.xgboost")
lrn = makeImputeWrapper(lrn)
getLearnerProperties(lrn)

class(lrn) = c("MyCustomWrapper", class(lrn))
getLearnerProperties.MyCustomWrapper = function(learner) {
  class(learner) = tail(class(learner), -1)
  c("factors", getLearnerProperties(learner))
}

getLearnerProperties(lrn)
```

A little less hacky would be to add a new class in the function where you create the wrapper.

e.g.:

```r
makeCustomWrapper = function(learner, ...) {
  #...
  BBmisc::addClasses(learner, "CustomWrapper")
}

getLearnerProperties.CustomWrapper = function(learner) {
  union(getLearnerProperties(learner$next.learner), "factors")
}
```

**Comment by jakob-r** [comment]
In conclustion:
The modification is possible but should be better documented.

**Comment by berndbischl** [comment]
thanks @jakob-r for answering this.

also please note that very soon a much better system will be in place for this. 

have a look here
https://github.com/mlr-org/mlrCPO

we are currently working quite hard to finalize this

**Comment by berndbischl** [comment]
@mb706

**Comment by notiv** [comment]
Thanks @jakob-r for the quick response!
@berndbischl Really looking forward to mlrCPO!

In case anyone is interested in a more complete example of the solution proposed [above](https://github.com/mlr-org/mlr/issues/2003#issuecomment-327104011), [here](https://github.com/mlr-org/mlr/blob/bb32eb8f6e7cbcd3a653440325a28632843de9f6/R/DummyFeaturesWrapper.R) some code from the DummyFeaturesWrapper wrapper in mlr.

**Comment by berndbischl** [comment]
Very cool that you posted a worked out solution, thanks!

The current plan is to finish CPO as much as possibe, then migrate everything wrt preprocessing into that separate package.
