### ISSUE TITLE
bartMachine parameter tuning

### ISSUE THREAD

**Issue by sreepunith** [mlr-org/mlr#2006]
I have been having issues with tuning hyper parameters for bartMachine.
```
Error in .jcall(java_bart_machine, "V", "setNU", nu) : 
  method setNU with signature (I)V not found

num_ps = makeParamSet(
  makeIntegerParam("num_trees", lower=50L, upper=200L),
  makeNumericParam("k", lower= 2, upper=5),
  makeNumericParam("q", lower=0.75, upper=1),
  makeIntegerParam("nu", lower= 2L, upper=10L) 
 )
```
I don't know what is causing the error.

**Comment by PhilippPro** [comment]
Post a reproducible example. It also looks more like an error that is caused by the bartMachine package, so you should write it on their github page.

**Comment by sreepunith** [comment]
Here is a simple example

library(mlr)
library(mlrMBO)
n = 200
p = 5
X = data.frame(matrix(runif(n * p), ncol = p))
y = 10 * sin(pi* X[ ,1] * X[,2]) +20 * (X[,3] -.5)^2 + 10 * X[ ,4] + 5 * X[,5] + rnorm(n)
data=as.data.frame(cbind(X,y))

regr.task = makeRegrTask(data = data, target = "y")

num_ps = makeParamSet(
  
  makeIntegerParam("num_trees", lower=50L, upper=200L),
  makeNumericParam("k", lower= 3, upper=20),
  makeIntegerParam("nu", lower=1L, upper=10L),
  makeNumericParam("q", lower=0.75, upper=1)
  
 )

lrn<-makeLearner("regr.bartMachine",verbose=F)




ctrl = makeMBOControl(propose.points = 4L)
ctrl = setMBOControlTermination(ctrl, iters = 3L)
ctrl = setMBOControlInfill(ctrl, crit = crit.ei)
ctrl = setMBOControlMultiPoint(ctrl, method = "cl", cl.lie = min)
tune.ctrl = makeTuneControlMBO(mbo.control = ctrl)
res = tuneParams(lrn, regr.task, cv5, par.set = num_ps, control = tune.ctrl, measures=mae,show.info = TRUE)

The error message is:

[Tune-x] 1: num_trees=96; k=3.37; nu=6; q=0.881
Warning in train(learner, task, subset = train.i, weights = weights[train.i]) :
  Could not train learner regr.bartMachine: Error in .jcall(java_bart_machine, "V", "setNU", nu) : 
  method setNU with signature (I)V not found

I figured out the soulution. If I define the parameter 'nu' as discrete. It works fine.

makeDiscreteParam("nu", values = c(1, 2, 3,4, 5,6,7,8,9,10)).

However the par.set for bartMachine says that nu is an Integer. 

nu                                           integer    -                 3    1 to Inf   -    TRUE     -

**Comment by jakob-r** [comment]
It's a bug in bartMachine. They somehow don't accept Integers even though nu is an integer-valued parameter. I wrote an email to the maintainer.

**Comment by sreepunith** [comment]
Thank you.
