### ISSUE TITLE
makeStackedLearner error

### ISSUE THREAD

**Issue by sreepunith** [mlr-org/mlr#2014]
I have been trying to used the "compress" method for stacking and I keep getting an error saying that "cannot allocate memory for vector of size 64GB". My data has 25000 rows and 75 features. 
I have the code below:
```
library(mlr)
task <- makeRegrTask(data = data, target = "y")
base.learners <- list(makeLearner("regr.ranger",num.trees=100,min.node.size=500), 
                      makeLearner("regr.gbm",n.trees = 200,interaction.depth = 6),
                     makeLearner("regr.xgboost",nrounds = 500,max_depth=4),
                      makeLearner("regr.cvglmnet"))

ff<-makeStackedLearner(base.learners,predict.type = "response", method="compress",parset = list(measures=mae,show.info=TRUE))
library(parallelMap)
parallelStartSocket(5) 
tmp<-train(ff,task)
```

The output looks something like this:
```
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 5; elements = 5.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 5; elements = 5.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 5; elements = 5.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 5; elements = 5.
Error: cannot allocate vector of size 60.7 Gb
```
Am I doing something wrong ? Or is the dataset too big?

**Comment by jakob-r** [comment]
There are multiple correct answers.

1) For what you are doing the dataset is too big
2) For what you are doing your memory is too small
3) Maybe running it sequentially would help as not so much memory will be allocated at the same time

**Comment by sreepunith** [comment]
Thank you! Some more info; I am running the code on a 64 bit R. I have a 64 GB RAM. I have tried running serially. I get the same error. I also tried memory.limit() to no avail.

**Comment by ja-thomas** [comment]
For debugging purposes, reduce the number of base.learners, and increase one by one until the error occurs. Maybe one of the used learners is especially memory hungry.

**Comment by sreepunith** [comment]
I tried adding 1 learner at a time. I still get the same error. Although, hill_climb, average and super_learner works fine.
