### ISSUE TITLE
tuning Only Super Learner ?

### ISSUE THREAD

**Issue by caprone** [mlr-org/mlr#2016]
it's possible tuning only the Super Learner in a StackedLearner 's ensemble?
i found this approach:  [https://github.com/SteveBronder/mlr#ensembles-of-forecasts], but seem that is required also tuning base learners..(what I do not care about)...
thanks

**Comment by larskotthoff** [comment]
Yes, there's n rule about which parameters you need to expose. You could tune just one parameter of one learner in an ensemble.

**Comment by SteveBronder** [comment]
I believe you can also tune the super learner by putting it in a `makeTuneWrapper()` right?

**Comment by caprone** [comment]
ok, but for example, when I call tuneParams method  on a makeStackedLearner, (that's a required parametr), it  will tune only the base learner parameters..
How i can specify to tuning only "par.set" of my  makeTuneWrapper(.."super learner")?

ps. Yes I want ONLY tune super Learner'S parameters  (putting it in a makeTuneWrapper)
thanks again

**Comment by larskotthoff** [comment]
In the example you've linked to, if you passed `super.ps` to `tuneParams`, you'd be tuning only the super learner.

**Comment by caprone** [comment]
HI and thanks for support, but that doesn't work..
if I pass super.ps to tuneParams, the method try to tune that parameters for base learners (that are different learner, with  different parameters )..indeed raise that issue:
"Error in checkTunerParset(learner, par.set, measures, control) : 
  Can only tune parameters for which learner parameters exist: nrounds

**Comment by SteveBronder** [comment]
Hi! Thanks for checking out the forecasting work. Can you post a small reproducible example of what you are attempting to do?

I'm happy to answer it here, though this may be a better question to post on stackoverflow

**Comment by sreepunith** [comment]
I had the same issue. In order for it to work you have to specify mod$super.learner as the learner, where mod is the makeStackedLearner object. It worked fine for me.

**Comment by caprone** [comment]
ok, thanks to Steve and sreepunith ;)
ok, this is a asmall reproducible example:

`
# resampling methods
inner = makeResampleDesc("Subsample", iters = 5, split = 2/3, stratify = TRUE)
outer = makeResampleDesc("CV", iters = 5, stratify = TRUE)

# parameters to tuning for super lrn
sl_par = makeParamSet(
  makeDiscreteParam('eta', values = c(.1, .01, .001))
)

base_lrn <- list(
  makeLearner("classif.gbm",  id = "gbm",  predict.type = "prob"),
  makeLearner("classif.ksvm", id = "ksvm", predict.type = "prob")
)

# super learner
sp_lrn <- makeTuneWrapper(makeLearner("classif.xgboost", id = "xgboost", predict.type = "prob"),
                          resampling = inner,
                          par.set = sl_par, 
                          control = makeTuneControlGrid())
# staked learner
stk_lrn <- makeStackedLearner(base_lrn, 
                              sp_lrn, 
                              predict.type = "prob",
                              method = 'stack.cv',
                              use.feat = TRUE, 
                              resampling = outer) 
                        
# data
df <- data.frame(replicate(10, sample(0:1, 50, rep=TRUE)))
df <- mutate(df, X10=as.factor(X10)) %>% mutate_if(is.integer, as.numeric)

# make task
task_   <- makeClassifTask(id = "Example", data = df, target = "X10")

# tuning super learner in this way raise issue...
res = tuneParams(stk_lrn,         
                 task = task_, 
                 resampling = outer,
                 par.set = sl_par, 
                 measures = logloss, 
                 control = makeTuneControlGrid()
                 )

# works fine passing directly TuneWrapper istance! thanks to sreepunith !!
res = tuneParams(stk_lrn$super.learner,        
                 task = task_, 
                 resampling = outer,
                 par.set = sl_par, 
                 measures = logloss, 
                 control = makeTuneControlGrid()
)
`

thanks to sreepunith ! the problem is that tuneParams for that purpose needs a TuneWrapper's class object .
thanks !!

**Comment by caprone** [comment]
ops...SORRY NO NO..THIS IS ERROR!
it works only because tuneParams works only on super learner, but staked learner not!
then tuneParams tune directly on task and not on base learners output!!  :(((
nothing done!! issue remain the same
