### ISSUE TITLE
ImputeWrapper: tune the methods

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#202]
It would be nice if one could easily tune the impute wrapper.
Like which methods was selected for imputing. 

Currently  this seems to be possible mainly by creating a preproc wrapper manually which then calls impute.

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
