### ISSUE TITLE
Question: for glm model, is there a way to extract from the fitted model, not just the coefficients, but also the p-values?

### ISSUE THREAD

**Issue by drorberel** [mlr-org/mlr#2021]
data(BostonHousing)
task.regr = makeRegrTask(data = BostonHousing, target = "lstat")

## glm
lrn.regr = makeLearner("regr.glm")
n = nrow(iris)
train.set = sample(n, size = 2/3*n)
test.set = setdiff(1:n, train.set)
model.regr = train(lrn.regr, task.regr, subset = train.set)

model.regr$learner.model$coefficients

p.values?

**Comment by larskotthoff** [comment]
Not directly, but you can extract them from the model: https://stackoverflow.com/questions/23838937/extract-pvalue-from-glm
