### ISSUE TITLE
saving optpath during parallelization in mlrMBO 

### ISSUE THREAD

**Issue by sreepunith** [mlr-org/mlr#2024]
Is there a way to save parameter tuning history is mlrMBO when using parallelmap when creating a custom resample measure? I am able to save the opt path during serial runs, but not when running in parallel.

**Comment by jakob-r** [comment]
On which level do you parallelize?

**Comment by sreepunith** [comment]
I tried both levels "resample" and "tuneparams". If i did that it would run parallel at all. If I run them without any level then print(opdf)would return "data frame with 0 columns and 0 rows"

library(parallelMap)
library(mlr)
library(mlrMBO)
set.seed(11, "L'Ecuyer")
parallelLibrary("mlr")
configureMlr(on.learner.error = "warn")
parallelSource("myresample1.R")
idx1 = seq(1, 150, 2)
idx2 = seq(2, 150, 2)
d1 = iris[idx1,]
d2 = iris[idx2,]
# task on indices idx1
task = makeClassifTask(data = d1, target = "Species")
# stupid param set
lrn = makeLearner("classif.ksvm")
ps = makeParamSet(
  makeNumericParam("C", lower = -10, upper = 10, trafo = function(x) 2^x)
)
# stupid tuning


########### HERE THE MAGIC STARTS ##################
m1 = mmce
# we create 2nd dummy measure to login to
m2 = mmce; m2$id = "extra"
ms = list(m1, m2)

# we now overwrite the resample function in  tuning
myresample = function(learner, task, resampling, measures, show.info) {
  # we generate the normal resample call
  r = resample(learner, task, resampling, measures, show.info = show.info)
  # and now we train on the complete task, predict extra holdout
  mod = train(learner, task)
  pred = predict(mod, newdata = d2)
  # and overwrite our dummy measure in the optpath
  p = performance(pred, measures = mmce)
  r$aggr[2] = p
  return(r)
}
# stupid param set
# stupid tuning

########### HERE THE MAGIC STARTS ##################
parallelStartMulticore(4L,level ="mlr.resample")
ctrl = makeMBOControl(propose.points = 4L)
ctrl = setMBOControlInfill(ctrl, crit = crit.ei)
ctrl = setMBOControlMultiPoint(ctrl, method = "cl", cl.lie = min)
tune.ctrl = makeTuneControlMBO(mbo.control = ctrl,same.resampling.instance = TRUE,mbo.keep.result = TRUE)
tr<-tuneParams(lrn, task, cv5, par.set = ps, control = tune.ctrl,  measure=ms,resample.fun=myresample,show.info = TRUE)
opdf<-as.data.frame(tr[[1]]$op)
print(opdf)

**Comment by ja-thomas** [comment]
your example works when I get the opt path with`as.data.frame(tr$opt.path)` does this solve your problem?
