### ISSUE TITLE
Batchmark and h2o does not work

### ISSUE THREAD

**Issue by MinhAnhL** [mlr-org/mlr#2027]
Hi, 
I'm currently working with batchmark, but h2o and batchmark seems to be not compatible. 
I tried it with my learner (h2o.autoencoder for oneclass, but also classif.h2o.deeplearning for classification)
The error is
> class water.fvec.Frame d is already in use.  Unable to use it now.  Consider using a different destination name.

### See Mini-example:

```
library(batchtools)
library(parallelMap)
library(BBmisc)
library(mlr)
library(h2o)

regdir = "/Users/Minh/Documents/TestData/BatchMark/BatchMarkJobH2o"

if (FALSE) {
  unlink(regdir, recursive = TRUE, force = TRUE)
  reg1 = makeExperimentRegistry(file.dir = regdir,
    packages = c("farff", "parallelMap", "kernlab", "e1071", "h2o"),
    seed = 17734)
}

#Lade registry
reg1 = loadRegistry(regdir)
#Windows:
#reg1$cluster.functions = makeClusterFunctionsMulticore(6L)
#Mac / Linux:
reg1$cluster.functions = makeClusterFunctionsSocket(4L)


#Setup
ps = makeParamSet(
  makeDiscreteParam("activation", values = c("Rectifier", "Tanh")))
ctrl = makeTuneControlRandom(maxit = 5L, tune.threshold = FALSE)
lrn = makeLearner("classif.h2o.deeplearning", predict.type = "prob")
lrn = makeTuneWrapper(lrn, resampling = cv2, par.set = ps, measures = list(auc),
  control = ctrl, show.info = TRUE)

batchmark(lrn, sonar.task, cv2, auc, reg = reg1)
submitJobs()

getJobTable()
```
Does anyone know a solution to that problem and can help me out?
Best Minh

**Comment by ja-thomas** [comment]
You cant run H2O learner distributed on one machine (i.e. Multicore or Socket backend) since you are not allowed to use parallel computations with the free version of H2O. Running it on SLURM or a similar system should work.

**Comment by ledell** [comment]
@ja-thomas What do you mean the "free version" of H2O?  There's only one version of H2O and it's Apache 2.0 licensed.

**Comment by ledell** [comment]
@MinhAnhL Can you tell me how to get this file, so I can try to reproduce this?
```
regdir = "/Users/Minh/Documents/TestData/BatchMark/BatchMarkJobH2o"
source = "/Users/Minh/Documents/TestData/BatchMark/setup_Data_Task_CV.R"
```

**Comment by MinhAnhL** [comment]
@ledell Thank you very much.
I updated the script above, you actually don't need the source file, as I only used sonar.task, which is already implemented in mlr. 
With `regdir`, you can set the path where the file "BatchMarkJobH2o" will be created to save your results in.

**Comment by ja-thomas** [comment]
> @ja-thomas What do you mean the "free version" of H2O? There's only one version of H2O and it's Apache 2.0 licensed.

Sorry you're right. But if I remember correctly there was some kind of restriction in the past on parallel processing in h2o.

I guess the problem is in the way we initialize h2o. Did you check if it works with parallelMap and parallel resampling or does this only not work with batchmark?

**Comment by ledell** [comment]
> Sorry you're right. But if I remember correctly there was some kind of restriction in the past on parallel processing in h2o.

Nope, there's never been a restriction.  H2O has always had multi-core & multi-node parallelism since the start of the project.  I think sometimes people make the assumption that there is an "enterprise" version because it's backed by a company, but that's not the case.  (Though H2O.ai sells "enterprise support" for H2O.)

**Comment by MinhAnhL** [comment]
@ja-thomas I had this problem before (I think with parallel resampling) but batchmark is working after switching of parallel computing. Thank you :)
I will try a larger computation on the server and let you know if it still works.

**Comment by ja-thomas** [comment]
@MinhAnhL Still relevant? Otherwise I'll close
