### ISSUE TITLE
Extension to a base learner

### ISSUE THREAD

**Issue by Jorimat** [mlr-org/mlr#2036]
I am trying to make an adaptation to a standard classifier from the kknn package.  The example below is a simplified version of what I want to do:
- Training is pretty normal.
- Classification depends on the Sepal.Width:
    - If the Sepal.Width is above 3.5, the prediction becomes "Unspecified".
    - Else, the normal kknn classification is done, using the training that was done before.

How can I build a learner that is compatible with mlr for this?  I want to use other functionality of mlr (parameter tuning, resampling,...).  I think I should make a wrapped learner, but the example in the tutorial (https://mlr-org.github.io/mlr-tutorial/release/html/wrapper/index.html) is not explanatory enough for my basic programming skills.

```r
library(mlr)

# Training
n = nrow(iris)
iris.train = iris[seq(1,150,2),]
iris.test = iris[seq(2,150,2),]
task = makeClassifTask(data = iris.train, target = "Species")
lrn = makeLearner("classif.kknn", predict.type = "prob")
mod = train(lrn, task)

# Classification
newdata.pred = rep(NA, nrow(iris.test))
for (i in 1:nrow(iris.test)){
	if (iris.test$Sepal.Width [i] > 3.5){
		newdata.pred[i] = "Unspecified"
	} else {
		prob = getPredictionProbabilities(predict(mod, newdata = iris.test[i,]))
		newdata.pred[i] <- names(prob[which(prob == max(prob))])	
	}
}
```

**Comment by larskotthoff** [comment]
It sounds like you want a custom learner implementation. Have a look at the kknn implementation for a start. Note that this would be an incredibly specific learner though.

**Comment by ja-thomas** [comment]
@Jorimat is you question answered? If so we can close here

**Comment by Jorimat** [comment]
Yes, the answer is pretty clear.

**Comment by ja-thomas** [comment]
thanks, closing
