### ISSUE TITLE
Replacing previous import ‘BBmisc::isFALSE’ by ‘backports::isFALSE’ when loading ‘mlr’ 

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#2037]
@mllg, @berndbischl importing BBmisc and backports seems to cause at least a warning when loading mlr (not sure if this can cause RStudio to crash as reported in https://github.com/openml/openml-r/issues/398).

```
library(mlr)
Warning:
1: replacing previous import ‘BBmisc::isFALSE’ by ‘backports::isFALSE’ when loading ‘mlr’ 
```

**Comment by mllg** [comment]
`isFALSE()` will be a base function in R-3.5.0, therefore BBmisc will soon always raise a warning if its namespace gets attached.
The import mechanism in backports has changed to circumvent these warnings, but the CRAN release is still using the old way to import functions. Everything should be fine after a new release :stuck_out_tongue:

**Comment by mllg** [comment]
Closing as this is already fixed in master.
