### ISSUE TITLE
calculateConfusionMatrix should have a parameter to specify which set to use

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#2046]
E.g. `set = "train" | "test" | "both"`.

**Comment by christophM** [comment]
The examples in the doc show that you can do this by giving the calculateConfusionMatrix a prediction object that is already subsetted:

```r
allinds = 1:150
train = sample(allinds, 75)
test = setdiff(allinds, train)
mod = train("classif.lda", iris.task, subset = train)
pred = predict(mod, iris.task, subset = test)
print(calculateConfusionMatrix(pred))
print(calculateConfusionMatrix(pred, sums = TRUE))
print(calculateConfusionMatrix(pred, relative = TRUE))
#
```

Does that solve your issue?

**Comment by larskotthoff** [comment]
Not unless it is implemented this way everywhere that produces predictions, e.g. resampling.

**Comment by AlexEngelhardt** [comment]
Hi,

could you confirm I understood correctly?

This argument would only make sense if the `pred` parameter comes from a resampling strategy. In the following, for `pred2`, it would not make sense (and the parameter should be ignored?)

```r
mod = train("classif.lda", iris.task)
pred1 = crossval("classif.rpart", iris.task)$pred
pred2 = predict(mod, iris.task)
rdesc = makeResampleDesc("CV", iters=10, predict="both")
pred3 = resample("classif.rpart", iris.task, rdesc)$pred  # here, you have set=train and set=test in pred3$data

class(pred1)  # "ResamplePrediction"
head(pred1$data)  # contains column "set", but all are "test" here
calculateConfusionMatrix(pred1)

class(pred2)  # "Prediction"
head(pred2$data)  # no column "set" => argument set="train" would *not* make sense

class(pred2)  # "ResamplePrediction"
head(pred2$data)  # has column "set" and it contains both "train" and "test" => argument set="train" would make sense
```

If yes, I would:
- add the argument, defaulting to "both" (for backwards compatibility)
- if it's unequal to "both", first assertClass(pred, classes = "ResamplePrediction"), to make sure the column `pred$data$set` exists
- then subset the data using this column

**Comment by larskotthoff** [comment]
Yes, that's correct.
