### ISSUE TITLE
Proposal: removeRedundantFeatures (and associated wrapper)

### ISSUE THREAD

**Issue by Prometheus77** [mlr-org/mlr#2052]
I'm thinking of coding up a preprocessing function and wrapper that will remove any redundant features from a task or dataset before training. Current line of thought is that it would offer the following options:
const: constant (zero-variance) features
const.thresh: minimum proportion of observations equal to the mode that will be eliminated. Default 1.
dupl: remove features that are exact duplicates of other features (keep only 1 of each)
corr: remove features that are highly correlated with other features (keep only 1 of each)
corr.thresh: minimum to remove, default 1.
corr.abs: use the absolute value of correlation?
crv: remove factors that have a high Cramer's V (analogous to r-squared) with other factors (keep only 1 of each).
crv.thresh: minimum to remove, default 1
uniq: remove factors where a high proportion is unique
uniq.thresh: minimum to remove, default 1

Any thoughts or suggestions as I start coding this up?

**Comment by jakob-r** [comment]
Most of what you mention is feature selection. Some things you mentioned are already covered by the FilterWrappers: http://mlr-org.github.io/mlr-tutorial/devel/html/feature_selection/index.html#filter-methods
We also have `removeConstantFeatures` which is not available as a Wrapper though, but filtering can eliminate those as well. 
Please check `listFilterMethods()` to check which ones are actually missing from your side.
