### ISSUE TITLE
Have a look at `classif.neuralnet`

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#2053]
The code looks pretty ugly. Maybe someone can clean it up and check whether everything works as supposed.

**Comment by ja-thomas** [comment]
Just delete it / ignore it as long as it isn't broken ? 

We have already nnet as a simple neural network and H2o and (soon) mxnet as better performing ones. I really see no use in investing time here.

Feel free to convince me otherwise.

**Comment by jakob-r** [comment]
* nnet does not have multiple hidden layers. 
* h2o is quite "big". 
* mxnet: I am looking forward for it
* neuralnet seems to be quite popular, has plots, multiple hidden layers...

Apart from that I don't have any strong personal opinions about any implementation.

**Comment by sycoforbidden** [comment]
i'm trying to integrate regr.neuralnet into mlr, however it fits the models poorly and gives a constant output.
I think it's because of the resampling, since calling the function with the task outside mlr still works.
