### ISSUE TITLE
makeModelMultiplexerParamSet

### ISSUE THREAD

**Issue by alentzos** [mlr-org/mlr#2055]
Hello all,

Currently I'm reading mlr tutorial at http://mlr-org.github.io/mlr-tutorial/devel/html/index.html and I have a question about makeModelMultiplexerParamSet function : 

I want to tune hyperparameters for ksvm & random forest   using the following r code:

``` 
library(mlr)
library("parallelMap")
parallelStartSocket(2)

 base.learners = list(
  makeLearner("classif.ksvm"),
  makeLearner("classif.randomForest")
)
lrn = makeModelMultiplexer(base.learners)

ps = makeModelMultiplexerParamSet(lrn,
classif.ksvm = makeParamSet(
makeNumericParam("sigma", lower = -10, upper = 10, trafo = function(x) 2^x),
makeNumericParam("C", lower = -12, upper = 12, trafo = function(x) 2^x),
makeIntegerParam("degree", lower = 2L, upper = 5L)
),
classif.randomForest = makeParamSet(
makeIntegerParam("ntree", lower = 1L, upper = 500L)
)
)

rdesc = makeResampleDesc("CV", iters = 2L)
ctrl = makeTuneControlIrace(maxExperiments = 200L)
res = tuneParams(lrn, iris.task, rdesc, par.set = ps, control = ctrl)

```

but i'm getting the following error:

--- [Tune] Started tuning learner ModelMultiplexer for parameter set:
                               Type len Def                            Constr Req Tunable Trafo
selected.learner           discrete   -   - classif.ksvm,classif.randomForest   -    TRUE     -
classif.ksvm.sigma          numeric   -   -                         -10 to 10   Y    TRUE     Y
classif.ksvm.C              numeric   -   -                         -12 to 12   Y    TRUE     Y
classif.ksvm.degree         integer   -   -                            2 to 5   Y    TRUE     -
classif.randomForest.ntree  integer   -   -                          1 to 500   Y    TRUE     -
With control class: TuneControlIrace
Imputation value: 1
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 2; elements = 8.
Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) : 
  Errors occurred in 5 slave jobs, displaying at most 10 of them:

00002: Error in rbfdot(degree = 4L, sigma = 11.6562054982094) : 
  unused argument (degree = 4)

00004: Error in rbfdot(degree = 4L, sigma = 0.0160552867943918) : 
  unused argument (degree = 4)

00005: Error in rbfdot(degree = 5L, sigma = 11.5156498356797) : 
  unused argument (degree = 5)

00006: Error in rbfdot(degree = 3L, sigma = 0.113005853832147) : 
  unused argument (degree = 3)

00008: Error in rbfdot(degree = 5L, sigma = 0.048755295835522) : 
  unused argument (degree = 5)

----

Can you please help  me to overcome these errors?

Thanks in advance

Lentzos Thanos

**Comment by jakob-r** [comment]
You are tuning the svm with the default kernel which is the radial basis function (rbfdot). Only the polynomial kernel accepts the degree parameter. You would have to add the kernel parameter to the parameter set. See here http://jakob-r.de/mlrHyperopt/articles/working_with_parconfigs_and_paramsets.html#creating-a-paramset-with-dependent-hierarchical-parameters for more details on how to do so.

**Comment by alentzos** [comment]
thanks u!
