### ISSUE TITLE
Problem with monotone_constraints in classif.xgboost learner

### ISSUE THREAD

**Issue by ItamarKanter** [mlr-org/mlr#2056]
Hi,
 I tried to make _xgboost_ learner with _monotone_constraints_.
While with the native xgboost package I was able to set monotone_constraints, when I try to use the _makeLearner_ function it raise an error

```r
sessionInfo()
```
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mlr_2.11          ParamHelpers_1.10

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13      magrittr_1.5      splines_3.4.2     munsell_0.4.3     colorspace_1.3-2  lattice_0.20-35  
 [7] rlang_0.1.1       plyr_1.8.4        tools_3.4.2       parallel_3.4.2    grid_3.4.2        checkmate_1.8.5  
[13] data.table_1.10.4 gtable_0.2.0      yaml_2.1.14       survival_2.41-3   xgboost_0.6-4     lazyeval_0.2.0   
[19] tibble_1.3.3      Matrix_1.2-11     ggplot2_2.2.1     parallelMap_1.3   stringi_1.1.5     compiler_3.4.2   
[25] BBmisc_1.11       scales_0.4.1      backports_1.1.1  

minimal reproducible example
```r
lrn = makeLearner("classif.xgboost", monotone_constraints = rep(0,60))
```

```r
Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  classif.xgboost: Setting parameter monotone_constraints without available description object!
Did you mean one of these hyperparameters instead: objective booster min_child_weight
You can switch off this check by using configureMlr!
```

While with xgboost it's work fine

```r
require("xgboost")
data = as.matrix(getTaskData(sonar.task)[,1:60])
target = ifelse(getTaskData(sonar.task)$Class=="M",1,0)
res = xgboost(data = data,label=target, nrounds=100, monotone_constraints = rep(0,60))
```

**Comment by larskotthoff** [comment]
We haven't included the `monotone_constraints` parameter in mlr yet.

**Comment by ItamarKanter** [comment]
Thanks,
If you
​would
 guide me
​(as I never contribute to an R package) ​
I'll happy to contribute
​ ​
to the package and add this parameter to the package.
It may be a good starting point to contribute to an open source project.
Itamar

בתאריך 8 בנוב׳ 2017 6:57 אחה״צ,‏ "Lars Kotthoff" <notifications@github.com>
כתב:

We haven't included the monotone_constraints parameter in mlr yet.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mlr-org/mlr/issues/2056#issuecomment-342882189>, or mute
the thread

**Comment by larskotthoff** [comment]
Have a look at the existing implementation -- it should be fairly straightforward to see how to add another parameter.

**Comment by ptl93** [comment]
I'm working on this

**Comment by scholbeck** [comment]
This issue seems to be solved. 
I cannot reproduce the error anymore by typing the following:
```lrn = makeLearner("classif.xgboost", monotone_constraints = rep(0,60))```

After taking a look into ```Rlearner_classif_xgboost.R``` and ```Rlearner_regr_xgboost.R``` respectively, it seems the parameter was added already:
```makeIntegerVectorLearnerParam(id = "monotone_constraints", default = 0, lower = -1, upper = 1),```

**Comment by ptl93** [comment]
@scholbeck  two days ago when I tried reproducing this error with the code you mentioned I got the error: `Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  classif.xgboost: Setting parameter monotone_constraints without available description object!
Did you mean one of these hyperparameters instead: objective booster min_child_weight
You can switch off this check by using configureMlr!`
I remember downloading **mlr** on CRAN via install.packages() . After reinstalling the github version of the package which covers the hyperparameter "montone_constraints" it was fine. So @ItamarKanter  you should use the github version in order to use the hyperparameter.

**Comment by ItamarKanter** [comment]
Great!
I'll take a look

2017-11-25 17:16 GMT+02:00 Christian Scholbeck <notifications@github.com>:

**Comment by christophM** [comment]
Works with the current mlr version on github.
