### ISSUE TITLE
generateHyperParsEffectData will format Numeric into Integer

### ISSUE THREAD

**Issue by chaoqing** [mlr-org/mlr#2065]
I do not know whether this is a bug or not, but it indeed introduce inconsistency when tuning a model and retrieving the tuning result.

Say I want to tuning a model's hyper-parameter which should have log scale but I do not want it to be  infinite precision, because tuning between `1000` and `1000.2` is meaningless. I want a numeric parameter but on some grid, so I create a parameter like `makeIntegerParam("C", lower = -4, upper = 4, default = 0, trafo = function(x) 10^x)`. When tuning the hyper-parameter `C`, 0.001/0.01/0.1/1/10/100/1000 will be passed to the algorithm, but when retrieving the tuning result with `generateHyperParsEffectData(res, trafo = TRUE)` the hyper-parameter `C` will all be formatted into integer like 0/1/10/100. 

This is actually because the [ParamHelpers](https://github.com/berndbischl/ParamHelpers/blob/9d374430701d94639cc78db84f91a0c595927189/R/OptPathDF_setter.R#L54) package will format the numeric into integer when `addOptPathEl`. 

I know maybe `makeDiscreteParam` is a good choice when I want discrete numeric values or I can do the transformation myself. Just a tip here about the inconsistency when tuning a model and retrieving the tuning result which maybe confusing to new users.

**Comment by jakob-r** [comment]
Are you using `generateHyperParsEffectData(..., trafo = FALSE)`?

Can you give a reproducible example?

I would say it's not a bug but it might be better documented, that an `integerParam` will be treated as an integer also after the `trafo`. We could also throw a warning/error if we detect a non integerish value after trasnformation. Toughts @berndbischl?

What you actually want is not an integer Parameter because as you stated yourself you are interested in fractions. So why not use `makeNumericParam("C", lower = -4, upper = 4, default = 0, trafo = function(x) 10^x)` and rely on `makeTuneControlGrid()`. 

> I do not want it to be infinite precision, because tuning between 1000 and 1000.2 is meaningless. I want a numeric parameter but on some grid [...]
But in your case for example -4 equals 0.001 and -3 0.01. The chance that the best performance is obtained with a setting between those two exact values is not necessarily negligible. So the grid is not always the best option. However of course the trafo makes sure that the difference between 1000 and 1000.2 is not as important as the difference between 0.21 and 0.01.

**Comment by chaoqing** [comment]
Hi, here is an reproducible example. As you can see the xgboost algorithm get `eta` an an decimals but the `opt_path` give zero. It better be sending an warning when this situation appears because it really confused me a lot when I first encounter it.

```
library(mlr)
library(mlrMBO)

set.seed(1024)

iris <- iris[iris$Species!="virginica",]
task = makeClassifTask(id = "iris", iris, target = "Species")
lrn = makeLearner("classif.xgboost", eval_metric = "auc", predict.type = "prob")

ps = makeParamSet(
  makeIntegerParam("eta", lower = -7, upper = -5, default = -6, 
                   trafo = function(x) 2^x)
)


ctrl = makeTuneControlRandom(maxit = 2)

res.mbo = tuneParams(lrn, task, cv10, par.set = ps, control = ctrl, 
                    show.info = TRUE, measures = auc)

#[Tune] Started tuning learner classif.xgboost for parameter set:
#       Type len Def   Constr Req Tunable Trafo
#eta integer   -  -6 -7 to -5   -    TRUE     Y
#With control class: TuneControlRandom
#Imputation value: -0
#[Tune-x] 1: eta=0.0156
#[Tune-y] 1: auc.test.mean=1.0000000; time: 0.0 min
#[Tune-x] 2: eta=0.00781
#[Tune-y] 2: auc.test.mean=1.0000000; time: 0.0 min
#[Tune] Result: eta=0.0156 : auc.test.mean=1.0000000

opt_path <- generateHyperParsEffectData(res.mbo, trafo = FALSE)$data
print(opt_path)

#  eta auc.test.mean iteration exec.time
#1   0             1         1     0.215
#2   0             1         2     0.207
```

**Comment by jakob-r** [comment]
In this case I strongly suggest to use `makeNumericalParam`.

**Comment by chaoqing** [comment]
OK. The things is I want something between integer and float numerical, decimals but on some grid (discrete). I can do the transformation myself by first using `generateHyperParsEffectData(res.mbo, trafo = FALSE)` and then apply the `trafo` function.

You can close this issue but I strongly suggest add a warning when the user use `makeIntegerParam` but actually return a numerical value.

**Comment by jakob-r** [comment]
If you really insist on having a discretized search space you could do
```r
ps = makeParamSet(
  makeNumericParam("eta", lower = -7.5, upper = -5.5, default = -6, 
                   trafo = function(round(x)) 2^x)
)
```

or simply
```r
ps = makeParamSet(
  makeIntegerParam("eta", lower = -7, upper = -5, default = -6, 
                   trafo = function(x) 2^x)
)
des = generateGridDesign(ps, ...)
[...]
ctrl = makeTuneControlDesign(design = design, ...)
```

And if the grid design is too big you can subset it to random rows.
