### ISSUE TITLE
makeXXXTask gives a warning when "x" or "y" columns are in the data

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#2087]
```R
> makeClusterTask(data=data.frame(x = 1))
Warning in makeTask(type, data, weights, blocking, fixup.data = fixup.data,  :
  We detected that you have columns named 'x' and 'y' in your data.
If you have spatial data and want to use spatial cross-validation as resampling 
method, please set 'spatial = TRUE' during task creation (default = FALSE).
If not, you can safely ignore this warning.
```
1. This is wrong, the warning comes when only an `x` **or** `y` column is present
2. This is making a bit too much of a fuzz about spatial data. Somehow `mlr` made it through more than four years without supporting it, I don't think most users want to be *warned* about it now.

I hope `mlr` doesn't aspire to be MS Clippy.

**Comment by larskotthoff** [comment]
Agreed. Removed in #2090.
