### ISSUE TITLE
extract information from resampling object

### ISSUE THREAD

**Issue by etbei** [mlr-org/mlr#2088]
Dear mlR creaters and users, 
first of all, thank you very much for the amazing package!
I wondered how to extract variable importance measures (from a randomForest) and also how to create partial dependence plots from the models of a(n outer) resampling object. 
I was able to get the filtered features using sapply(rx$models, getFilteredFeatures) - rx is the list from the ResampleResult - but this approach does not seem to work for variable importance (I tried sapply(rx$models, getFeatureImportance)). 
I am Sorry if this is not the right place for asking these questions. Is there maybe an example in the tutorial or here which I've maybe missed?
Thank you very much!

**Comment by larskotthoff** [comment]
You can pass the `models = TRUE` flag to `resample` to keep the models:

```
library(mlr)
lrn = makeLearner("regr.randomForest")
rdesc = makeResampleDesc("CV", iters = 10)

res = resample(lrn, bh.task, rdesc, models = TRUE)

# get first one...
getFeatureImportance(res$models[[1]])
# ...or all of them
lapply(res$models, getFeatureImportance)

pd.regr = generatePartialDependenceData(res$models[[1]], bh.task, "lstat", fun = median)
plotPartialDependence(pd.regr)
```

**Comment by Prometheus77** [comment]
I think the way I'd handle this would be to:

1. create a custom preprocessing wrapper that keeps only the features that you want for each iteration
2. wrap up your learner with this to create multiple learners
3. create a resample *instance* rather than a resample *description* to ensure that the same observations are in the same folds across all resampling results
4. use the benchmark() function to evaluate

Here's a code snippet you can try:
```
library(mlr)

my_df <- data.frame(x1 = runif(100),
                    x2 = runif(100),
                    x3 = runif(100),
                    x4 = runif(100),
                    y = sample(c("A", "B"), 100, replace = TRUE))

my_task <- makeClassifTask(data = my_df, target = "y")

# create custom preprocessing wrapper
# see https://mlr-org.github.io/mlr-tutorial/devel/html/preproc/index.html#writing-a-custom-preprocessing-wrapper

trainfun = function(data, target, args = list(keep_x)) {
  control <- list(keep_cols = c(args$keep_x, target))
  data <- data[names(data) %in% control$keep_cols]
  return(list(data = data, control = control))
}

predictfun = function(data, target, args, control) {
  return(data[names(data) %in% control$keep_cols])
}

makeKeepWrapper <- function(lrn, keep_x) {
  makePreprocWrapper(lrn, train = trainfun, predict = predictfun,
                     par.vals = list(keep_x = keep_x))
}

# now create my learner
my_lrn <- makeLearner("classif.randomForest")

# and create wrapped versions with each of the predictor subsets you want
lrn1 <- makeKeepWrapper(my_lrn, c("x1", "x2", "x3"))
lrn2 <- makeKeepWrapper(my_lrn, c("x1", "x3", "x4"))
lrn3 <- makeKeepWrapper(my_lrn, c("x2", "x3", "x4"))
lrn4 <- makeKeepWrapper(my_lrn, c("x1", "x2"))
# etc

# mlr benchmark requires that each learner have a separate learner id, so we will do that here
add_learner_suffix <- function(lrn, suffix) {
  setLearnerId(lrn, paste0(getLearnerId(lrn), suffix))
}

lrn1 <- add_learner_suffix(lrn1, 1)
lrn2 <- add_learner_suffix(lrn1, 2)
lrn3 <- add_learner_suffix(lrn1, 3)
lrn4 <- add_learner_suffix(lrn1, 4)
# etc

my_learners <- list(my_lrn, lrn1, lrn2, lrn3, lrn4)

# now we create a fixed resample instance (8-fold CV) where each subset of predictors is trained on the same 8 folds
my_rin <- makeResampleInstance("CV", iters = 8, task = my_task)

# and now we run the benchmark command
my_bmr <- benchmark(my_learners, my_task, my_rin)

# and finally view the result
plotBMRSummary(my_bmr)
```

**Comment by jakob-r** [comment]
Thanks Lars, I guess this answers the question. So I will close. Feel free to re-open if things remain unclear.

**Comment by etbei** [comment]
Thanks a lot! Your answers helped me a lot!
One last question: When I want to extract only the feature importance of the test sets or generate partial dependence plots using the test sets, how do I know which number I have to indicate within the double brackets using res$models[[...]], for example if the inner resampling loop contains 10 cross-validations and the outer one 3?
Thanks a lot!

**Comment by larskotthoff** [comment]
The number determines the iteration, nothing to do with train/test sets.

**Comment by etbei** [comment]
Thanks! I see, that would be res$extract[[1]]$x, for example, for the results of the first outer resampling loop...
