### ISSUE TITLE
Extract learner, task and resampledescription from ResampleResult object

### ISSUE THREAD

**Issue by Toekan** [mlr-org/mlr#2091]
Hi,

I'm quite new to mlr (which is amazing btw!), but after a reasonably extensive search, I still have no answer to the following question:

I want to extract the learner, the task and the resampledescription that were used as inputs of the resample function from the resulting ResampleResult object. Is this possible at all?

The reason I want this, is because I want to write a function that trains exactly the same model with the same resampledescription, but on a chosen subset of the predictors. So if I can access the three basic building bloks, I can reassign less columns to the data of the task and run a new resample.

Thanks!

**Comment by larskotthoff** [comment]
The short answer is "not really". You can get the learner if you save the models trained during the resampling:

```
library(mlr)
lrn = makeLearner("classif.randomForest")
rdesc = makeResampleDesc("CV", iters = 10)

res = resample(lrn, iris.task, rdesc, models = TRUE)
res$models[[1]]$learner
```

But the task and resample description are not saved (doing so would consume too much memory).

I would simply pass learner, task, and resample description to the function that does the resampling.

**Comment by Prometheus77** [comment]
I think the way I'd handle this would be to:

1. create a custom preprocessing wrapper that keeps only the features that you want for each iteration
2. wrap up your learner with this to create multiple learners
3. create a resample *instance* rather than a resample *description* to ensure that the same observations are in the same folds across all resampling results
4. use the benchmark() function to evaluate

Here's a code snippet you can try:
```
library(mlr)

my_df <- data.frame(x1 = runif(100),
                    x2 = runif(100),
                    x3 = runif(100),
                    x4 = runif(100),
                    y = sample(c("A", "B"), 100, replace = TRUE))

my_task <- makeClassifTask(data = my_df, target = "y")

# create custom preprocessing wrapper
# see https://mlr-org.github.io/mlr-tutorial/devel/html/preproc/index.html#writing-a-custom-preprocessing-wrapper

trainfun = function(data, target, args = list(keep_x)) {
  control <- list(keep_cols = c(args$keep_x, target))
  data <- data[names(data) %in% control$keep_cols]
  return(list(data = data, control = control))
}

predictfun = function(data, target, args, control) {
  return(data[names(data) %in% control$keep_cols])
}

makeKeepWrapper <- function(lrn, keep_x) {
  makePreprocWrapper(lrn, train = trainfun, predict = predictfun,
                     par.vals = list(keep_x = keep_x))
}

# now create my learner
my_lrn <- makeLearner("classif.randomForest")

# and create wrapped versions with each of the predictor subsets you want
lrn1 <- makeKeepWrapper(my_lrn, c("x1", "x2", "x3"))
lrn2 <- makeKeepWrapper(my_lrn, c("x1", "x3", "x4"))
lrn3 <- makeKeepWrapper(my_lrn, c("x2", "x3", "x4"))
lrn4 <- makeKeepWrapper(my_lrn, c("x1", "x2"))
# etc

# mlr benchmark requires that each learner have a separate learner id, so we will do that here
add_learner_suffix <- function(lrn, suffix) {
  setLearnerId(lrn, paste0(getLearnerId(lrn), suffix))
}

lrn1 <- add_learner_suffix(lrn1, 1)
lrn2 <- add_learner_suffix(lrn2, 2)
lrn3 <- add_learner_suffix(lrn3, 3)
lrn4 <- add_learner_suffix(lrn4, 4)
# etc

my_learners <- list(my_lrn, lrn1, lrn2, lrn3, lrn4)

# now we create a fixed resample instance (8-fold CV) where each subset of predictors is trained on the same 8 folds
my_rin <- makeResampleInstance("CV", iters = 8, task = my_task)

# and now we run the benchmark command
my_bmr <- benchmark(my_learners, my_task, my_rin)

# and finally view the result
plotBMRBoxplots(my_bmr)
```

**Comment by Toekan** [comment]
Thanks for these answers! I indeed ended up writing a function that takes the learner, task and resample description as inputs. 

Didn't know the benchmark functionality, will definitely look into it. Unfortunately in my case, I only know which features I want to select after I've run the model before it. I guess there is no way to do that in benchmark.

**Comment by jakob-r** [comment]
> I only know which features I want to select after I've run the model before it

Can you elaborate? It sound's like you want to do a FeatureSelection wrapper

**Comment by Toekan** [comment]
Each model is run on the x most important features of the model before it,
decided by ranking getFeatureImportance. Haven’t read about
featureselection wrappers yet!

**Comment by Toekan** [comment]
Hi jakob-r, it seems like a FeatureSelection wrapper is almost what I need. Unfortunately, because of the large number of features, training many models to figure out which feature is the most/least important isn't feasible for me. Guess there's no way to implement a variable importance measure in the selection criteria instead?

**Comment by jakob-r** [comment]
Okay. So I guess you want to write something like what we have in `FilterWrapper.R` but instead of using a method that is already available there you want to use your own by calling "getFeatureImportance" on the specific learner. You can do so by writing your own filter like the ones in `Filter.R` for the specific learner (see: http://mlr-org.github.io/mlr-tutorial/devel/html/create_filter/index.html#integrating-another-filter-method) . That is not the most universal method but otherwise you would have to dig deeper into the wrapper stuff inside mlr.

**Comment by Toekan** [comment]
Thanks for all the help! I'll have a look at it.

At the moment I have solution that kind of works, I pass extract=getFeatureImportance into resample and after training the model I rank the the values in $extract, take the n most important features and pass those to the new resample. 

The problem is that this doesn't work for nested resampling, I get the following error:

```
Error in UseMethod("getFeatureImportanceLearner") : 
  no applicable method for 'getFeatureImportanceLearner' applied to an object of class "c('TuneWrapper', 'OptWrapper', 'BaseWrapper', 'Learner')"
```

I understand that I now pass a TuneWrapper into the resample function instead of a Learner, but I'm a bit confused why this shouldn't work on a conceptual level. The inner resampling method tunes the parameters, finds the optimal ones, passes them to the outer resampling part, which is now an identical situation to non-nested resampling?
