### ISSUE TITLE
subset parameter works differently in subsetTask and train

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#2098]
```R
getTaskSize(subsetTask(pid.task, c(TRUE, FALSE)))
[1] 384
```
This is what I expect: R recycles the logical vector and gives only the odd rows of the task.
```R
train("classif.logreg", pid.task, subset = c(TRUE, FALSE))$subset
[1] 1
```
Even though this is plausible, this is *not* what I expect given the usual behaviour of R and even `subsetTask`. One of the first lines in `train` sets `subset = which(subset)`, the rest of the training happens on only this one line.

If this discrepancy is intentional, it should be documented more clearly.

**Comment by larskotthoff** [comment]
Sounds like a bug.

**Comment by mllg** [comment]
Discrepancy is clearly not intended here. And I do not like the vector recycling here. Maybe we should just assert that the length of the logical vector matches `getTaskSize(task)`?
