### ISSUE TITLE
Tuning individual learners inside a multilabel wrapper

### ISSUE THREAD

**Issue by nikoltoll** [mlr-org/mlr#2111]
Not really a bug but a feature.
As far as I can see, there is no possibility of tuning the individual learners in a multilabel wrapper procedure. Wrapping a tunewrapper model inside a multilabel wrapper will result in an error:

multilabel.textclassif.task <- makeMultilabelTask("textclassif", traindat, target = c("O1", "O2", "O3", "O4", "O5", "O6", "O7", "O8"))
Ada <- makeLearner("classif.ada")
rdesc <- makeResampleDesc(method = "CV", stratify = TRUE, iters = 5)
ps <-  makeParamSet(makeIntegerParam("iter", lower = 100, upper =  1000)) ctrl <- makeTuneControlGrid(resolution = 10L)
tune.Ada <- makeTuneWrapper(learner = Ada, resampling = rdesc, control = ctrl, par.set = ps)
CC.tune.Ada <- makeMultilabelClassifierChainsWrapper(learner = tune.Ada) 

##   Cannot wrap an optimization wrapper with something else!

This seriously limits the use of problem transformation methods for multilabel data and results in a overall suboptimal model. 

Is it possible to make this feature available in the current framework?

**Comment by ThomasWolf0701** [comment]
Yes this would make it much more useful. Especially in the case of imbalanced Label classes this would be a huge help.

**Comment by larskotthoff** [comment]
Could you do the wrapping the other way round? The fundamental problem with wrapping an optimization wrapper is that results may become misleading unless you optimize exhaustively.
