### ISSUE TITLE
One-Class Classifier

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr#2114]
Hello Bernd,

Are one-class classifier already supported? I saw different "project-oneclass" - threads here, i.a. concearning resampling for one-class classifiers, but I don't find any method that is able to work as a one-class classifier. 

When I look here
[http://mlr-org.github.io/mlr-tutorial/devel/html/integrated_learners/index.html](url),
there is no learner with "Prop" -> oneclass as described in the section above on the site.

I wonder, because there exist the one-class SVM.

`R> getLearnerProperties(learner="classif.svm")

[1] **"twoclass"**      "multiclass"    "numerics"      "factors"       "prob"          "class.weights"
`
There is not "oneclass".

When I look into ?svm, there is the option type="one-classification". Does it mean something else? I read there "novelty detection". It seems to be what I am looking for. But so I wonder. type="one-classification" is not implemented for classif.svm:

`R> getLearnerParamSet("classif.svm")`
'->                        Type  len              Def                             Constr                    Req Tunable Trafo
type               discrete    -     C-classification      C-classification,nu-classification   -    TRUE       -'

type="one-classification" is not implemented. 

Thank you!

Best regards,
Markus

**Comment by MinhAnhL** [comment]
Hi Mareichoff, I'm currently working on it in my thesis. 
It's not ready for merge yet, but hopefully soon :)

**Comment by drdebian** [comment]
> Hi Mareichoff, I'm currently working on it in my thesis.
> It's not ready for merge yet, but hopefully soon :)

any news on this? would be a great addition to mlr!

**Comment by mareichhoff** [comment]
Hello Albert,

 

that's interesting. We are working in the field of radiation therapy and mostly it's like this: From 1000 radiation plans used for irradiation with a linear accelerator, only 1 will fail (ca.). One the one hand it cost time to irradiate all the 1000 plans in a kind of pre-treatment irradiation. It would make sense to use some kind of anomaly detection in this case. That's why I am interested.

 

Best regards,

Markus

 

Gesendet: Donnerstag, 07. März 2019 um 08:52 Uhr
Von: "Albert Ulmer" <notifications@github.com>
An: mlr-org/mlr <mlr@noreply.github.com>
Cc: "Markus Eichhoff" <e_markus@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [mlr-org/mlr] One-Class Classifier (#2114)



Hi Mareichoff, I'm currently working on it in my thesis.
It's not ready for merge yet, but hopefully soon :)


any news on this? would be a great addition to mlr!

**Comment by MinhAnhL** [comment]
Hi,
I finished my thesis, which you can find here: https://epub.ub.uni-muenchen.de/58320/
Chapter 7 gives you an intro how to apply Anomaly detection based on this branch.

Best,
Minh

> > Hi Mareichoff, I'm currently working on it in my thesis.
> > It's not ready for merge yet, but hopefully soon :)
> 
> any news on this? would be a great addition to mlr!

**Comment by drdebian** [comment]
> I finished my thesis, which you can find here: https://epub.ub.uni-muenchen.de/58320/
> Chapter 7 gives you an intro how to apply Anomaly detection based on this branch.

Thanks, I'll go check it out!

**Comment by berndbischl** [comment]
> any news on this? would be a great addition to mlr!

it is not really merged into the main project, and we will feature-freeze mlr version 2, 
as we are currently working on mlr3.

at some point, this might be an interesting addition to mlr3.
if you want experiment with what @MinhAnhL you are welcome to do that.

**Comment by mareichhoff** [comment]
Yes, that's a good idea. I saw the repos of mlrng or mlr3. Great! 
Am 08.03.19, 05:08, Bernd Bischl <notifications@github.com> schrieb:

any news on this? would be a great addition to mlr!

it is not really merged into the main project, and we will feature-freeze mlr version 2,
as we are currently working on mlr3.
at some point, this might be an interesting addition to mlr3.
if you want experiment with what @MinhAnhL you are welcome to do that.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mlr-org/mlr","title":"mlr-org/mlr","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mlr-org/mlr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@berndbischl in #2114: \u003e any news on this? would be a great addition to mlr!\r\n\r\nit is not really merged into the main project, and we will feature-freeze mlr version 2, \r\nas we are currently working on mlr3.\r\n\r\nat some point, this might be an interesting addition to mlr3.\r\nif you want experiment with what @MinhAnhL you are welcome to do that.\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/mlr-org/mlr/issues/2114#issuecomment-470798116"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mlr-org/mlr/issues/2114#issuecomment-470798116",
"url": "https://github.com/mlr-org/mlr/issues/2114#issuecomment-470798116",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
