### ISSUE TITLE
Nested SpCV broken

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2125]
It works with the [commit](https://github.com/mlr-org/mlr/commit/e865e491dc2062b14ebeb9d5314cec2532c1bc2a) it was introduced but some recent commit broke it.
It seems to only affect nested SpCV and not normal SpCV.

I'll investigate and provide a fix. 

``` r
# install_github("mlr-org/mlr@e865e491dc2062b14ebeb9d5314cec2532c1bc2a")
remotes::install_github("mlr-org/mlr")

library(mlr)
#> Loading required package: ParamHelpers

data("bc.task.spatial")

lrn_knn <- makeLearner("classif.kknn",
                       predict.type = "prob")
#> Loading required package: kknn

## Tuning in inner resampling loop
ps <- makeParamSet(makeIntegerParam("k", lower = 10, upper = 400),
                   makeIntegerParam("distance", lower = 1, upper = 100),
                   makeDiscreteParam("kernel",
                                     values = c("triangular", "epanechnikov",
                                                "biweight", "triweight", "cos",
                                                "inv", "gaussian", "optimal")))

ctrl <- makeTuneControlRandom(maxit = 5)
inner <- makeResampleDesc("SpCV", iters = 5)

wrapper_knn <- makeTuneWrapper(lrn_knn, resampling = inner, par.set = ps,
                               control = ctrl, show.info = F, measures = list(auc))

outer <- makeResampleDesc("SpRepCV", folds = 5, reps = 2)

library(parallelMap)
parallelStart(mode = "multicore", level = "mlr.tuneParams", cpus = 1)
#> Starting parallelization in mode=multicore with cpus=1.

set.seed(12345)
resa_knn_spatial <- mlr::resample(wrapper_knn, bc.task.spatial,
                                  resampling = outer, extract = getTuneResult,
                                  show.info = TRUE, measures = list(auc))
#> Resampling: repeated spatial cross-validation
#> Measures:             auc
#> Error in data.frame(task$env$data$x, task$env$data$y): arguments imply differing number of rows: 0, 788
```

Created on 2018-01-07 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by mb706** [comment]
FYI the first one is a dead link.

**Comment by mb706** [comment]
So there is [this hack](https://github.com/mlr-org/mlr/blob/7541988ca65c4198907ce63fab7a46d2676449fb/R/Task_operators.R#L344-L349) that really shouldn't be there. Don't make functions behave differently under these kind of very specific conditions unless there is a **very** good reason for that.
1. Why should `getTaskData` not return spatial coordinate features?
2. If it actually shouldn't, then `getTaskData` would probably need a parameter `include.coordinates` so that it can safely be used in `subsetTask`. *I am against this.*

Why did the bug not occur earlier? Because the hack cited above checks for `subsetTask(.task, .subset)` being called, but since #2100 the subsetting doesn't happen in the learners any more, it happens in `train()`. There the call is `subsetTask(task, subset)`, so the hack doesn't catch this any more.

**Comment by pat-s** [comment]
> FYI the first one is a dead link.

Thanks, fixed it.

I'll take a detailed look later or tomorrow. 
As far as I see you already might have tracked down the problem, thanks so far @mb706!

**Comment by pat-s** [comment]
Now addressing this problem.

> Why should getTaskData not return spatial coordinate features?

Because they should not be used for model fitting but need to be used for partitioning, so they need to be removed somewhere between these two steps.

> If it actually shouldn't, then getTaskData would probably need a parameter include.coordinates so that it can safely be used in subsetTask. I am against this.

Why are you against a possible parameter `include.coordinates`?

> Why did the bug not occur earlier? 

Because there is no test checking a nested resampling with spcv - I'll add one.

**Comment by pat-s** [comment]
Currently debugging at `tuneParams()` l.97 where `makeResampleInstance()` tries to create a SpCV partitioning but is missing coordinates `x` and `y` in the task because they have been removed previously by [this hack](https://github.com/mlr-org/mlr/blob/7541988ca65c4198907ce63fab7a46d2676449fb/R/Task_operators.R#L344-L349).

I removed the hack and got the "nested cv with hyperparamter tuning" working again.
I now do 

```
  if (isTRUE(task$task.desc$is.spatial)) {
    task$env$data$x = NULL
    task$env$data$y = NULL
  }
```
in l.123 of `tuneParams()`. Possibly an adjusted `getTaskData` call would be better?

Will now also check for single CV for performance estimation

**Comment by pat-s** [comment]
So I removed the hack but now I face again the following problem that the hack solved:

When arriving in `train()` at around l.80 in a `SpCV` call (without tuning), I need to remove `x` and `y` there because there the models gets trained right [afterwards](https://github.com/mlr-org/mlr/blob/7541988ca65c4198907ce63fab7a46d2676449fb/R/train.R#L96). 

While this works fine in `SpRepCV` because the partitioning is already done at this point, it does not work in a nested setting with `tuneParams()`. 
There, the partitioning is done after I arrive at `train()` l.80 and if my code removes the coordinates there, they are not available when the resampling instance is created later on.

So I somehow have to check whether we are in a `SpRepCV` with tuning or `SpRepCV` without tuning. 

I now do so by checking in the `pars` object existing at [`train` l.72](https://github.com/mlr-org/mlr/blob/7541988ca65c4198907ce63fab7a46d2676449fb/R/train.R#L72) whether the `.learner$id` has "tuned" in its name, e.g. `classif.ksvm.tuned`.
This is only the case if we are in a nested cv setting with tuning.
Subsequently, I make the removal of the coordinates in `train()` conditional on this property.

We are arriving at this "removal point" (`train()` l.80) several times (basically for every model that is fitted, no matter if for tuning or performance estimation) and the `if` part is entered every time and coordinates are removed although they are not existent anymore. 
However, we need to do it at least once (on the first arrival of every outer fold) as then the task arrives at `train()` l.80 with coordinates.
