### ISSUE TITLE
Error in setNames(fiv, imp$Feature) : attempt to set an attribute on NULL

### ISSUE THREAD

**Issue by edvbb** [mlr-org/mlr#2126]
I'm doing a standard algorithm
`rf <- makeLearner("classif.xgboost",  predict.type = "prob")`
```
rf_param <- makeParamSet(
  makeDiscreteParam("booster",  values = c( 'gbtree','gblinear')),
  makeNumericParam("eta", lower = 0.0001, upper = 1) ,
  makeIntegerParam("nrounds",lower = 5, upper = 1000),
  makeIntegerParam("max_depth", lower = 1, upper = 15),
  makeNumericParam("subsample", lower = 0.1, upper = 1) ,
  makeNumericParam("colsample_bytree", lower = 0.1, upper = 1) ,
  makeNumericParam("lambda", lower = 0.1, upper = 1) ,
  makeNumericParam("alpha", lower = 0.1, upper = 1) ,
  makeNumericParam("rate_drop", lower = 0.1, upper = 1) 
  )
```

```
rancontrol <- makeTuneControlRandom(maxit = 50L) # мы ограничимся 5 итерациями, вы пробуйте больше от 50  
set_cv <- makeResampleDesc("RepCV", folds = 10L, reps = 5L)  
rf_tune <- tuneParams(learner = rf, resampling = set_cv, task = trainTask, 
                      par.set = rf_param, control = rancontrol, measures = mlr::auc

rf.tree <- setHyperPars(rf, par.vals = rf_tune$x)
rforest <- mlr::train(rf.tree, trainTask) 
getLearnerModel(rforest)
rfmodel <- predict(rforest, testTask) # testTask task.over
mlr::performance(rfmodel, measures = mlr::auc)
```

and error
`getFeatureImportance(rforest)`
`Error in setNames(fiv, imp$Feature) : attempt to set an attribute on NULL`

Do I understand correctly that the problem is that I received the parameter `rf_tune$x` `"gblinear"`, and this parameter does not allow me to show FeatureImportance? And we can see FeatureImportance  just with  `'gbtree'`? Or is the reason of the erroe for the other?

**Comment by mb706** [comment]
This is correct, if you set `rf_tune$x$booster = "gbtree"` after tuning, the rest of the code works.

`mlr` should probably give a more sensible error message, since `help(xgb.importance)` mentions that xgboost only offers the importance measure ("`Gain`") for tree-based models.
