### ISSUE TITLE
customized new feature filter with p-values as a score

### ISSUE THREAD

**Issue by drorberel** [mlr-org/mlr#2128]
I am trying to create the following customize feature filter based on p-value from glm. 
I am not sure how I should address the automatic internal ordering that is used with filterFeatures()
'perc' and 'abs', which return the top HIGH values. 
with p-values, I wish the lowest values to be returned.
I can do this by adding a minus, but was wondering if there is a better way.
I also noticed that none of the other filter 'scores' is using the p.value, and was wondering why.

 makeFilter(
      name = "glm.p.value.filter",
      desc = "Calculates scores according to glm order of features",
      pkg = "Rfast",
      supported.tasks = c("classif"),
      supported.features = c("numerics", "regr"),
      fun = function(task, nselect,  ...) {
        d = getTaskData(task, target.extra = TRUE)
        y = as.numeric(as.character(d$target))
        x = as.matrix(d$data)
        if(task$type=='classif') glm.out = Rfast::univglms(y, x, oiko='binomial')
        if(task$type=='regr') glm.out = Rfast::univglms(y, x, oiko='normal')
       
        setNames(glm.out[, "pvalue"], getTaskFeatureNames(task))
      }
    )

**Comment by larskotthoff** [comment]
Negating the value sounds like the way to go. All filters use a defined method, and that happens to not include any p values. Is that your second question?

**Comment by drorberel** [comment]
Thanks.
