### ISSUE TITLE
can't figure out error concerning getTaskClassLevels

### ISSUE THREAD

**Issue by etbei** [mlr-org/mlr#2136]
Dear all,

Thanks for the great opportunity to ask questions here!
I might have a stupid one (I am Sorry if so!), but I can't figure out what the problem is. 
I created a costs matrix for cost-sensitive classification and wanted to name the rows and columns according to the two factor levels of my target, which are "0" and "1". 
I tried ...

> costs = matrix(c(0, 2, 1, -2), 2)
> costs.measure = makeCostMeasure(name="costs", costs=costs)
> colnames(costs) = rownames(costs) = getTaskClassLevels(task) 
Just to check: 
> costs
  0  1
0 0  1
1 2 -2

... And I also tried ...

> colnames(costs) = rownames(costs) = c("0", "1")

... and ...

> colnames(costs) = rownames(costs) = c(0, 1)

... and I get the output for the class levels as ...

> getTaskClassLevels(task)
[1] "0" "1"
> colnames(costs)
[1] "0" "1"

But when I want to run the resampling using the cost measure within the list of measures, I get the error message

> rx = resample(lrnfinal, task, resampling = outer, extract = getTuneResult,
>              show.info = TRUE, models=TRUE, measures=list(mmce, tpr, costs.measure))

"Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) : 
  Errors occurred in 30 slave jobs, displaying at most 10 of them:

00001: Error in measure$fun(task, model, pred, feats, m$extra.args) : 
  Row and column names of cost matrix have to equal class levels!"

The other 9 errors are the same as the first one.
What am I missing here?
Thanks a lot!

**Comment by larskotthoff** [comment]
`0` and `1` are not valid R names (see https://stat.ethz.ch/R-manual/R-devel/library/base/html/make.names.html). Try renaming to something like `level0` and `level1`.

**Comment by etbei** [comment]
oh i am sorry *face-palm*. thanks very much!

**Comment by etbei** [comment]
Hi there,
I am Sorry to ask again. Can't figure out where my error is so that after renaming the class levels, I still get the error message after running "resample" for outer resampling ...
"Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) : 
  Errors occurred in 30 slave jobs, displaying at most 10 of them:
00001: Error in measure$fun(task, model, pred, feats, m$extra.args) : 
  Row and column names of cost matrix have to equal class levels!"
My code is...
finaldata$fake[finaldata$fake=="1"] <- "positive" 
finaldata$fake[finaldata$fake=="0"] <- "negative"
finaldata$fake <- factor(finaldata$fake)
task = makeClassifTask(data=finaldata, target="fake", positive="positive")
... where "positive" is the second and positive factor level and "negative" the first factor level. 
costs = matrix(c(0, 5, 1, 0), 2)
costs.measure = makeCostMeasure(name="costs", costs=costs, best = 0, worst = 5)
colnames(costs) = rownames(costs) = getTaskDesc(task)$class.levels
[.....]
rx = resample(lrnfinal, task, resampling = outer, extract = getTuneResult,
              show.info = TRUE, models=TRUE, measures=list(costs.measure, mmce))
Thank you very much!!!

**Comment by larskotthoff** [comment]
Could you post a complete example (with data) that allows to reproduce the error please?

**Comment by etbei** [comment]
Hi, see below. Thank you very much!

# create data
set.seed(12345)
x1 = rnorm(100)
x2 = rnorm(100)
x3 = rnorm(100)
y = rnorm(100)

# make classification target
y_target = c()
y_target = ifelse(y > 0.9, y_target <- "level1", y_target <- "level0")
y_target = factor(y_target)

# data frame for classification
data = data.frame(x1, x2, x3, y_target)

# create task
library(mlr)
task = makeClassifTask(data = data, target = "y_target", positive = "level1")

# create basic learner for random forest
library(randomForest)
lrn = makeLearner("classif.randomForest", predict.type="prob") 

# wrapper for imbalancy correction
lrn = makeSMOTEWrapper(lrn, sw.rate=4, sw.nn = 5, sw.standardize=FALSE, sw.alt.logic=FALSE) 

# parameter tuning
lrn$par.vals <- (list(importance=T))
rfparam <- makeParamSet(
  makeIntegerParam("ntree", lower=25, upper=500), 
  makeIntegerParam("mtry", lower=3, upper=10), 
  makeIntegerParam("nodesize", lower=5, upper=50))
ctrl <- makeTuneControlGrid(tune.threshold = TRUE)

# make cost matrix for cost-sensitive classification
costs = matrix(c(0, 5, 1, 0), 2)
costs.measure = makeCostMeasure(name="costs", costs=costs, best = 0, worst = 5)
colnames(costs) = rownames(costs) = getTaskDesc(task)$class.levels

# inner resampling
inner = makeResampleDesc("CV", iters= 3, stratify=T) 
lrnfinal = makeTuneWrapper(lrn, resampling = inner, par.set = rfparam, control = ctrl, show.info = TRUE, measures = list(costs.measure, mmce)) 
# outer resampling
outer = makeResampleDesc("RepCV", folds = 3, stratify=T) 
library(parallel)
library(parallelMap)
parallelStartMulticore(detectCores(), level = "mlr.resample")
rx = resample(lrnfinal, task, resampling = outer, extract = getTuneResult,
              show.info = TRUE, models=TRUE, measures=list(costs.measure, mmce))
parallelStop()

**Comment by larskotthoff** [comment]
You're making the measure before you're setting the names. The line

```
colnames(costs) = rownames(costs) = getTaskDesc(task)$class.levels
```

needs to come before

```
costs.measure = makeCostMeasure(name="costs", costs=costs, best = 0, worst = 5)
```

**Comment by etbei** [comment]
oooh i see, I am Sorry, thank you very much!!!
