### ISSUE TITLE
Default config in makeLearner can fail

### ISSUE THREAD

**Issue by zkurtz** [mlr-org/mlr#2141]
Upfront: this is not a reproducible example, as it's based on a pretty complicated context.

The problem creates causes `mlrMBO::mbo` to crash with a cryptic error:
```
Error in opts$show.learner.output || inherits(learner, "OptWrapper") :
  invalid 'x' type in 'x || y'
```

Here is sudo-code of what I'm doing:
```r
    objective = smoof::makeSingleObjectiveFunction(
        name = "my fun",
        fn = objective,
        par.set = [my custom space],
        minimize = FALSE)
    des = [my messy design]
    ctrl = [my messy FUN]
    lrn = mlr::makeLearner("regr.km", predict.type = "se",
                           covtype = "matern3_2",
                           control = list(trace = FALSE))
    run = mlrMBO::mbo(objective,
                      design = des,
                      learner = lrn,
                      control = ctrl,
                      show.info = FALSE)
```

On a hunch, I found that inserting the argument `config = list(show.learner.output = FALSE)` in the `makeLearner` call made the issue go away. Should there be a check far higher in the call stack to prevent triggering the low-level error above?

**Comment by larskotthoff** [comment]
Hmm, sounds like you're using some sort of parallelizations and the options don't get exported everywhere.

**Comment by zkurtz** [comment]
I'm not doing any parallelization explicitly. However, my objective function involves `xgboost` internally, so maybe I need to try setting it to use only one thread?

**Comment by larskotthoff** [comment]
Anything you can do to narrow down when this happens would help.

**Comment by mb706** [comment]
The problem is that zkurtz did not `library("mlr")` and instead just uses `mlr::`. mlr calls [`configureMlr`](https://github.com/mlr-org/mlr/blob/06fb95e4a56af73d6910ace2e0cab8bd89c3270d/R/zzz.R#L19) in `.onAttach` for some reason, but this does not get called when the namespace never gets attached.

I'm not sure whether this is a bug, or if it is on purpose to avoid problems with `configureMlr()` overwriting settings when doing parallelization in some modes.

MWE (in a fresh R environment, possibly `R --vanilla`):
```R
> mlr::train(mlr::makeLearner("classif.logreg"), mlr::pid.task)
Error in opts$show.learner.output || inherits(learner, "OptWrapper") :
  invalid 'x' type in 'x || y'
```

**Comment by zkurtz** [comment]
The code I showed above was actually a subsection of a function within an R package I was building.  `mlr` was available without `library(mlr)` because I included `mlr` in the DESCRIPTION file as an "Imports". Now I get the impression that including it as a "Depends" might be another way to solve the problem, [although that can potentially introduce other complications](https://stackoverflow.com/questions/8637993/better-explanation-of-when-to-use-imports-depends).

**Comment by mb706** [comment]
A workaround would probably be to call `mlr::configureMlr()` manually somewhere in your own code before `mlr` gets called.

**Comment by bryanhanson** [comment]
Had the exact same problem, so glad to find the suggestions here!

**Comment by pat-s** [comment]
I'd say the workaround provided is sufficient enough to solve this niche use case.
