### ISSUE TITLE
MLR Parallelization. When elements exceed cpus all elements attempt to be scheduled. Any way to stagger element runs? [type-question]

### ISSUE THREAD

**Issue by mlearner-jl** [mlr-org/mlr#2142]
When attempting to have something run in parallel with MLR and parallelStartSocket, the parallelisation level can be specified, e.g. mlr.benchmark, mlr.resample, mlr.selectFeatures, mlr.tuneParams, mlr.ensemble, 

Quite often, obviously, one might want to parallelise say the tuneParams runs. There are usually many more tuneParam runs than there are cores or thread, for example say 12 cpus and 50-100 tuneParam runs. Is there anyway to run 12 tuneParam runs at a time and stagger this?

**Comment by jakob-r** [comment]
This will be done automatically. No more jobs will be started then what you specified in `parallelStartSocket(k)` whereas k should be replaced with the number of CPUs you have.
