### ISSUE TITLE
can mmpf please be moved to suggests?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#2144]
we seem to import it now, but the basic mlr functionality surely does not depend on it?

@zmjones @larskotthoff

**Comment by zmjones** [comment]
yes it can. i had it that way initially but lars suggested we import it. can change it now if you like.

**Comment by berndbischl** [comment]
> i had it that way initially but lars suggested we import it.

@larskotthoff why?

**Comment by larskotthoff** [comment]
To avoid needing `mmpf::` all over the place. Fine with moving it.
