### ISSUE TITLE
makeImputeWrapper - Question about force.dummies

### ISSUE THREAD

**Issue by mlearner-jl** [mlr-org/mlr#2147]
From the documentation for makeImputeWrapper, force.dummies has the following comment:

> "Force dummy creation even if the respective data column does not contain any NAs. **Note that (a) most learners will complain about constant columns created this way but (b) your feature set might be stochastic if you turn this off.** Default is FALSE."

Obviously this is true.

Can I clarify something however.

Clearly a lot of algorithms _will_ complain if constant columns are passed, but of course without this the feature set is potentially stochastic.

Can I ask how this affects a trained model?

Let's say we have a trained model, and we _haven't_ used force.dummies (which we would struggle to do with a lot of algorithms anyway). If we now send some new_data to be predicted on, and a column that in the training data was never missing now has a missing value, will the prediction fail because the imputation will cause a new column to appear that it wasn't trained on (namely the dummy column)?

**Comment by jakob-r** [comment]
Yes. I don't know of any learner that can handle new columns in the data set. In case you have no missings in the training data but missings in the test data you can only impute normally without the creation of dummy columns.

See the following example:
```r
library(mlr)
iris2 = iris
iris2[150,1] = NA
ind.train = sample(149, 100)
ind.test = setdiff(1:150, ind.train)
tsk = makeClassifTask(data = iris2, target = "Species")
lrn = makeLearner("classif.svm")
lrn = makeImputeWrapper(lrn, list(numeric = imputeMean()), dummy.classes = "numeric")
m = train(lrn, tsk, subset = ind.train)
m$learner.model$next.model$learner.model$terms
p = predict(m, task = tsk, subset = ind.test)
```

**Comment by mlearner-jl** [comment]
Thanks @jakob-r.

So, to be clear, if I create a wrapped learning with an ImputeWrapper, in the predict call MLR is clever enough to not create a dummy column, only impute, if no dummy column was created in the training data?

This is reassuring if so.

Thanks

**Comment by jakob-r** [comment]
It will not create a dummy column if no imputation was done on training
If NAs are inte the test data they will be imputed but also no dummy column will be used.
