### ISSUE TITLE
Question concearning selectFeatures - Output

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr#2150]
Hello,

as the code below shows I am doing a regression and use a forward selection. measures=list(mse, rmse). It's clear that the optimization is carried out for mse. But shouldn't it be "rmse.test.mean" as the second output? Here I see "rmse.test.rmse".

```[FeatSel] Started selecting features for learner 'regr.randomForestSRC'
With control class: FeatSelControlSequential
Imputation value: InfImputation value: Inf
[FeatSel-x] 1: 0000000000 (0 bits)
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 5.
[FeatSel-y] 1: **mse.test.mean**=0.0000,**rmse.test.rmse**=0.0016; time: 0.1 min
```

I use version 2.12 of mlr.

Best regards,
Markus

**Comment by mareichhoff** [comment]
I wanted to write it in bold letters (didn't work), so you see "**" there in the output above: 
**mse.test.mean** and **rmse.test.rmse**.

**Comment by larskotthoff** [comment]
Sounds like a bug.

**Comment by schiffner** [comment]
Hi,

it's not a bug. `test.rmse` is the default aggregation scheme for performance measure `rmse`. See `mlr::rmse$note`or http://mlr-org.github.io/mlr-tutorial/devel/html/resample/index.html#aggregating-performance-values and http://mlr-org.github.io/mlr-tutorial/devel/html/measures/index.html#regression.

**Comment by mareichhoff** [comment]
Hallo Julia,

but it's difficult to understand "rmse.test.rmse". I mean if I say: measures <- list(mae, rmse), then both should be carried out over my CV, or not? And there the mean will be calculated over all iterations.

But thank you for your answer.

Best regards,
Markus

**Comment by schiffner** [comment]
Hi,

It's by no means a law that performance measures from single CV iterations have to be aggregated 
by the mean. It just makes sense for the overwhelming majority of measures.

To explain a bit why `test.rmse` is the default aggregation for `rmse`:
When doing K-fold CV you get predictions y*_k from every iteration and, given their corresponding true values y_k,  calculate a performance measure M_k = M(y*_k, y_k).
These are then aggregated to get an overall performance A(M_1, ..., M_K).
Imagine now you collect all predictions into a vector y* = (y*_1, ..., y*_K) with corresponding
true values y = (y_1, ..., y_K). Of course, you could also calculate the performance measure
M(y*, y) based on these vectors.
Often, the aggregation scheme is chosen such that aggregating the individual M_k gives appr.
the same result as calculating the measure directly on y* and y, i.e., M(y*, y) ~ A(M_1, ..., M_K).
For the MSE this can be achieved by the mean - with exact equality if all folds have the same size.
For the RMSE, however, if one aims at the equality above, it makes sense to first square the single results M_k, then take the mean and finally again calculate the square root, which is what the `test.rmse` aggregation does (see mlr::test.rmse$fun).
If you prefer the mean, you can change the aggregation scheme via `setAggregation`.

Hope that clarifies it a bit. :)

**Comment by jakob-r** [comment]
Thanks @schiffner for clearing this up. To sum things up: No bug and we can close this issue?

**Comment by mb706** [comment]
Does this also make sense for RepCV?

**Comment by jakob-r** [comment]
The aggregation function is independent from the resampling method. So yes.
