### ISSUE TITLE
Strange result for forward selection

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr#2151]
Hello all together,

Perhaps I am wrong, but if I do a regression, the MAE (for example) is a measure that should be minimized, correct? But if you see this output here, then the algorithm should decide to take feature no. 5 where we have "mae.test.mean=0.0005" and then go on with feature no.5 + another one instead of the empty model. If he would maximize the measure MAE, then I could understand that he chooses the empty model (less features, maximal MAE). Or is there an error, that MAE is set to "maximize"? I don't know how to check it. Do you know why he chooses the empty model? The optimization should be carried out on "MAE" again, 5-CV. I put measures <- list(mae, rmse).

```
feat.result <- selectFeatures(learner=lrn.rf, task=regr.task.featsel, resampling=rdesc.inner, measures=measures, control=select.ctrl)
[FeatSel] Started selecting features for learner 'regr.randomForestSRC'
With control class: FeatSelControlSequential
Imputation value: InfImputation value: Inf
[FeatSel-x] 1: 0000000000 (0 bits)
[FeatSel-y] 1: mae.test.mean=0.0011,rmse.test.rmse=0.0016; time: 0.0 min
[FeatSel-x] 2: 1000000000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0011,rmse.test.rmse=0.0016; time: 30.4 min
[FeatSel-x] 2: 0100000000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0011,rmse.test.rmse=0.0016; time: 27.5 min
[FeatSel-x] 2: 0010000000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0008,rmse.test.rmse=0.0014; time: 29.9 min
[FeatSel-x] 2: 0001000000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0007,rmse.test.rmse=0.0016; time: 37.0 min
[FeatSel-x] 2: 0000100000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0005,rmse.test.rmse=0.0007; time: 29.5 min
[FeatSel-x] 2: 0000010000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0010,rmse.test.rmse=0.0016; time: 26.0 min
[FeatSel-x] 2: 0000001000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0010,rmse.test.rmse=0.0015; time: 25.5 min
[FeatSel-x] 2: 0000000100 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0010,rmse.test.rmse=0.0015; time: 30.1 min
[FeatSel-x] 2: 0000000010 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0011,rmse.test.rmse=0.0016; time: 27.0 min
[FeatSel-x] 2: 0000000001 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0011,rmse.test.rmse=0.0016; time: 33.6 min
[FeatSel] Result:  (0 bits)
parallelStop()
Stopped parallelization. All cleaned up.

feat.result
FeatSel result:
Features (0): 
mae.test.mean=0.0011,rmse.test.rmse=0.0016
```
Thank you very much for your help!

Best regards,
Markus

**Comment by larskotthoff** [comment]
MAE is defined correctly to be minimized -- can you give a complete example that allows to reproduce the issue please?

**Comment by mareichhoff** [comment]
Something strange happened: See below. No real selection takes place. What happened? I wonder... Where is the problem? I wanted to give you a minimal example, but here comes no output. So I couldn't test whether the minimization of MAE works or not. What can we do? 

parallelStartSocket(cpus=3L, level="mlr.selectFeatures")

lrn.rf<- makeLearner("regr.kknn")
rdesc.inner <- makeResampleDesc("CV", iters = 5L)
select.ctrl <- makeFeatSelControlSequential(method = "sfs")
feat.result <- selectFeatures(learner=lrn.rf, task=bh.task, resampling=rdesc.inner, measures=list(mae, rmse), control=select.ctrl)
parallelStop()


Output:

[FeatSel] Started selecting features for learner 'regr.kknn'
With control class: FeatSelControlSequential
Imputation value: InfImputation value: Inf
[FeatSel-x] 1: 0000000000000 (0 bits)
[FeatSel-y] 1: mae.test.mean=6.6559,rmse.test.rmse=9.2034; time: 0.0 min
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 13.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 12.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 11.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 10.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 9.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 8.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 7.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 6.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 5.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 4.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 3.
[FeatSel] Result: crimindusnoxrmagedisradtaxb... (10 bits)

R> feat.result
FeatSel result:
Features (10): crim, indus, nox, rm, age, dis, rad, tax, b, lstat
mae.test.mean=2.2264,rmse.test.rmse=3.4476

**Comment by mareichhoff** [comment]
Here is my sessionInfo():

R> sessionInfo() R version 3.4.3 (2017-11-30) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 7 x64 (build 7601) Service Pack 1  Matrix products: default  locale: [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] kknn_1.3.1        mlr_2.12          ParamHelpers_1.10 parallelMap_1.3    loaded via a namespace (and not attached):  [1] igraph_1.1.2        Rcpp_0.12.15        magrittr_1.5        splines_3.4.3       munsell_0.4.3       lattice_0.20-35     colorspace_1.3-2    rlang_0.1.6          [9] stringr_1.2.0       plyr_1.8.4          tools_3.4.3         parallel_3.4.3      grid_3.4.3          checkmate_1.8.5     data.table_1.10.4-3 gtable_0.2.0        [17] yaml_2.1.16         survival_2.41-3     lazyeval_0.2.1      tibble_1.4.2        Matrix_1.2-12       ggplot2_2.2.1       stringi_1.1.6       compiler_3.4.3      [25] pillar_1.1.0        installr_0.19.0     BBmisc_1.11         scales_0.5.0        backports_1.1.2     XML_3.98-1.9        pkgconfig_2.0.1
--
 
R> | R>
R>

**Comment by mareichhoff** [comment]
The other example task also shows no output. Normally one sees "[FeatSel-x]...., [FeatSel-y]...." And not only "Mapping in parallel: .... " and "Exporting objects....." Why doesn't he shos the other "bits" such as 010, 001 (depending on the number of variables, I am not sure how many we have here, not important). For bh.task we have 13 features, but nothing is visible (see posting above). The other problem stays: Why didn'T he minimized MAE. In these examples I even can't see the MAE or rmse. I am really confused now...

R> lrn.rf<- makeLearner("regr.kknn")
R> rdesc.inner <- makeResampleDesc("CV", iters = 5L)
R> select.ctrl <- makeFeatSelControlSequential(method = "sfs")
R> feat.result <- selectFeatures(learner=lrn.rf, task=fuelsubset.task, resampling=rdesc.inner, measures=list(mae, rmse), control=select.ctrl)
[FeatSel] Started selecting features for learner 'regr.kknn'
With control class: FeatSelControlSequential
Imputation value: InfImputation value: Inf
[FeatSel-x] 1: 000 (0 bits)
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 5.
[FeatSel-y] 1: mae.test.mean=4.4312,rmse.test.rmse=5.8289; time: 0.1 min
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 3.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 2.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 1.
[FeatSel] Result: h20NIR (2 bits)
R> parallelStop()
Stopped parallelization. All cleaned up.
R> feat.result
FeatSel result:
Features (2): h20, NIR
mae.test.mean=1.8184,rmse.test.rmse=2.5801

**Comment by mareichhoff** [comment]
I just see: I wrote  select.ctrl <- makeFeatSelControlSequential(method = "sfs")
Could there be the problem? That this error is not catched? It should be "makeFeatSelControlSequential()" or ...(alpha=...., beta=...)

**Comment by larskotthoff** [comment]
Incomplete code snippets without data don't really help us to figure out what's going on...

**Comment by mareichhoff** [comment]
What is incomplete here? Above you see the example code. You can run that on your machine. What is missing? I even gave you my sessionInfo(). And here is no error, so I can't give you traceback().

**Comment by mareichhoff** [comment]
bh.task and the other task are example tasks of the mlr package.

**Comment by mareichhoff** [comment]
As you see above in my sessionInfo, I use mlr, Version mlr_2.12.

**Comment by larskotthoff** [comment]
Oh that example. You posted several. The one with `bh.task` works perfectly fine as far as I can see. You're not seeing the output because you're parallelizing it if that's what you mean.

**Comment by mareichhoff** [comment]
And why do I see the output in my original code? (above, first posting). There I see all the bits that are tested (even there I work in parallel! Cpus=3):

[FeatSel-x] 1: 0000000000 (0 bits)
[FeatSel-y] 1: mae.test.mean=0.0011,rmse.test.rmse=0.0016; time: 0.0 min
[FeatSel-x] 2: 1000000000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0011,rmse.test.rmse=0.0016; time: 30.4 min
[FeatSel-x] 2: 0100000000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0011,rmse.test.rmse=0.0016; time: 27.5 min
[FeatSel-x] 2: 0010000000 (1 bits)
[FeatSel-y] 2: mae.test.mean=0.0008,rmse.test.rmse=0.0014; time: 29.9 min
[FeatSel-x] 2: 0001000000 (1 bits)
etc.

**Comment by mareichhoff** [comment]
1. So two things: Why don't I see all the tested bits, e.g. for bh.task with more than 10 features, but in my original example (I can't give you the code), I see everything (all bits that are tested with its measure result).

2. Why is mae.test.mean not minimized. Or at least a result is given that is wrong (the algorithm stopped although it should go on with feature no. 5 (0000100000).

-> For the last I searched for reproducible code, but as you see, I even see a complete output for bh.task and the other one fuel... Everything had been calculated in parallel! I liked to use the same settings as in my original process. 5-CV as resampling etc. measure = list(mae, rmse) as you can see.

**Comment by larskotthoff** [comment]
Have you looked at the tutorial (https://mlr-org.github.io/mlr-tutorial/devel/html/feature_selection/index.html#wrapper-methods) or documentation (https://www.rdocumentation.org/packages/mlr/versions/2.10/topics/FeatSelControl):

> The search is stopped if the improvement is smaller than alpha = 0.02.

That's also the reason you're not getting the *exact* minimum. You can adjust `alpha` to 0 if you prefer that.

**Comment by mareichhoff** [comment]
In my original case!? Yes! You are right! Thank you! That makes me understand the first point (two posts before). I have to adjust it. I know what alpha and beta are. But I didn't configure them yet because I didn't know the outcome of mae. Now I can do it in a second step.

But point 2.? Why do I see in the original output for each 5-CV evaluation for each single variable the exact output of mae.test.mean.... blabla... and also bit 00010000 etc. and for the minimal examples nothing? Just the parallel output?

**Comment by mareichhoff** [comment]
`[FeatSel-x] 1: 0000000000000 (0 bits)
[FeatSel-y] 1: mae.test.mean=6.6559,rmse.test.rmse=9.2034; time: 0.0 min
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 13.
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 3; elements = 12.
Exporting objects to slaves for mode socket: .mlr.slave.options
........`

Just at the beginning I see what happens, but then..... nothing? Just the number of jobs and cpus... But in my original code above I see every detail (measure etc.).

**Comment by larskotthoff** [comment]
Stuff running in parallel doesn't always get the same output stream and you wouldn't see the messages. However, you can log to a file, check the documentation of `parallelStartSocket()`.

**Comment by mareichhoff** [comment]
Yes, yes, I know. logging = T, storage.dir =.... I used it years ago. 

The other thing you mentioned is new. I thought the output is always the same. O.k. Thank you very much for your help!!
