### ISSUE TITLE
parallelGetRegisteredLevels() doesn't work for feature selection

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr#2152]
Hello,

here is some warning. Perhaps it would belong to the parallelMap github, I am not sure. After I loaded "mlr" with "library", he knows "mlr.selectFeatures" that I like to use for the feature selection, but some warning appears. It's not an error yet, but why is it not registered? It is well known for mlr (see below):

R> parallelGetRegisteredLevels()
mlr: mlr.benchmark, mlr.resample, **mlr.selectFeatures,** mlr.tuneParams, mlr.ensemble

R> parallelStartSocket(cpus=3L, **level=" mlr.selectFeatures"**)
Warning in parallelStart(mode = MODE_SOCKET, cpus = cpus, socket.hosts = socket.hosts,  :
  Selected level=' mlr.selectFeatures' not registered! This is likely an error! Note that you can also
      register custom levels yourself to get rid of this warning, see ?parallelRegisterLevels.R
Starting parallelization in mode=socket with cpus=3.

**Comment by larskotthoff** [comment]
Works for me. There's a space before mlr in your call to `parallelStartSocket()`, maybe that's the problem?

**Comment by mareichhoff** [comment]
Yes! Sorry! There you are right. That can be closed then. Thank you!
