### ISSUE TITLE
randomForestSRC parallelization

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#2155]
When `randomForestSRC` is built with OpenMP support (and I have no idea what this depends on, but it is the case on my machine) it tends to make parallel threads automatically, unless specifically told not to do so. The decision is made by the `randomForestSRC:::get.rf.cores()` function and depends on the `rf.cores` option: if it is not set, the value `-1` is returned, which defaults internally to the number of threads as reported by `omp_get_max_threads` (typically number of cores). This [used to be documented in the package itself](https://www.rdocumentation.org/packages/randomForestSRC/versions/2.4.1/topics/randomForestSRC-package) but apparently [isn't any more](https://www.rdocumentation.org/packages/randomForestSRC/versions/2.5.1/topics/randomForestSRC-package), though [the author's webpage still mentions it](http://www.ccs.miami.edu/~hishwaran/rfsrc.html) (and looking in the source will confirm the behaviour is still present). 

This behaviour is a bit at odds with `mlr`'s explicit parallelization since it leads to oversubscribing of cores and possibly additional memory usage. It would probably be useful to introduce an explicit hyperparameter that controls the setting of the `rf.cores` option. Maybe that parameter should be set to 1 by default, or at least if `parallelMap` is used at any stage

**Comment by SteveBronder** [comment]
^+1 same goes for data.table as well

**Comment by pat-s** [comment]
Good catch, are you working on a PR?

From a practical point of view, most users will hopefully use either the default `randomForest` or `ranger` package when they use RF. 
This may explain why nobody reported the issue so far?

**Comment by mb706** [comment]
I'm not working on this, feel free to open a PR if you're interested. I noticed this only when the LRZ cluster scheduler reported out-of-memory errors which were, as it turned out, caused by the process forks in randomForestSRC (exacerbated by the fact that on this cluster the forked processes were apparently not killed for whatever reason, and that the memory accounting system double-counts COW memory of forked processes). Most people working with more generously calculated memory limits or fewer bugs in their working environment might not feel the slight inefficiency caused by this, that's why I think this is not really high priority.
