### ISSUE TITLE
Release mlr 2.12 to CRAN 

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#2158]
It has been already nearly a year since our last CRAN release. It's about time. 
The NEWS File is long enough to justify a new release.

**Comment by pat-s** [comment]
Good idea Jakob! 
Beforehand we should make sure to have a `mlr-tutorial` that is up-to-date. 
There was also the issue of timeouts in `mlr-tutorial` with the PR of https://github.com/mlr-org/mlr-tutorial/pull/125. This would be solved by the `pkgdown` integration.

So I would propose to push finishing the `pkgdown` transition after the build passes and then integrate the important PR's so that the tutorial matches the CRAN release.

What do you think?

**Comment by jakob-r** [comment]
To have a tutorial matching perfectly to a cran version is nice but we have to differentiate between

1. The tutorial properly uses the current mlr version and "api" without any errors/warnings
2. The tutorial covers all features of the current mlr version

1. is a must but 2. is optional and probably we have never even achieved that?

**Comment by SteveBronder** [comment]
For (2) should we make a list of the missing features?

Off the top of my head (feel free to edit comment to add things)
- [ ] Functional Data
- [ ] growing and fixed window CV
- [ ] New way to do spatial CV (?)

I very much like the idea of using the pkgdown version of the tutorial / website, though the search function still not working upstream is problematic.

**Comment by jakob-r** [comment]
As I said, I think (2) should not stop us from a release.

**Comment by PhilippPro** [comment]
Looking forward for the new mlr release so I can upload my new package to CRAN. ;)

**Comment by berndbischl** [comment]
release date is scheduled for march 2nd. 
if you want to help, be online that day.
the following guys will be there: me + @ja-thomas + @mllg 
@jakob-r do you have time too?
who also want to help? at the end we could discuss how to make the project management better

**Comment by pat-s** [comment]
I would be happy to help :smile:

**Comment by jakob-r** [comment]
@berndbischl I have time until 3PM. But maybe this is not the perfect place to discuss those matters.

**Comment by pat-s** [comment]
Writing down my thoughts of possible improvements here so I do not loose them (tbc):

* Quarterly/half-yearly fixed release dates (enough content will be there anyways)
* Stricter handling/closing of issues PR that are inactive -> More focus on active ones. re-opening always possible. Maybe even a fixed "inactivity timeout". 
* More people in charge that are allowed to merge PRs; apparently Bernd has not much time and Lars can't do everything alone. In this regard a list of people to request a review from for certain projects (e.g. FDA, spatial, plotting, core, tutorial). New contributors are lost which guys are in charge or should review stuff before it can be merged

**Comment by PhilippPro** [comment]
When will be the mlr-release?

**Comment by ja-thomas** [comment]
check the slack channel for updates :)

**Comment by berndbischl** [comment]
it is allowed to ask here.
i already released (twice) i am waiting for an answer from cran

**Comment by berndbischl** [comment]
done
