### ISSUE TITLE
Suspected: 'mldr' package update broke Travis tests

### ISSUE THREAD

**Issue by AlexEngelhardt** [mlr-org/mlr#2159]
For the two pull requests #2140 and #2154, Travis fails with the same error:

    ── 1. Error: check measure calculations (@test_base_measures.R#657)  ───────────
    object 'mldr_HL' not found
    1: expect_equal(mldr:::mldr_HL(multi.y, multi.p), measureMultilabelHamloss(multi.y, 
           multi.p)) at testthat/test_base_measures.R:657
    2: quasi_label(enquo(object), label)
    3: eval_bare(get_expr(quo), get_env(quo))
    4: mldr:::mldr_HL
    5: get(name, envir = asNamespace(pkg), inherits = FALSE)

I suspect that the new mldr package version dropped the mldr_HL function.

Can someone confirm? If yes, I can try and fix it.

**Comment by jakob-r** [comment]
I guess you are right. It's now exported and called `hamming_loss` I guess.

https://github.com/fcharte/mldr/blob/70f206182e4263e612496d789b9ae1894bedc6db/R/evaluate.R#L131

https://github.com/fcharte/mldr/blob/d0e3912ae5e7a3d83ffe57da6a3b6266d7abbc0c/R/evmetrics_ml.R#L44
