### ISSUE TITLE
Functions for multilabel measures capitalized inconsistently

### ISSUE THREAD

**Issue by AlexEngelhardt** [mlr-org/mlr#2160]
The 'L' in `measureMultiLabelF1` is capitalized, but it's not in all the other multilabel measures:

    measureMultiLabelF1
    measureMultilabelACC
    measureMultilabelHamloss
    measureMultilabelPPV
    measureMultilabelSubset01
    measureMultilabelTPR

See also here:

https://github.com/mlr-org/mlr/blob/9865ceacea0eec2a4acbb65c82f42624566dbb71/R/measures.R#L1270

Is that intended? If no, can it simply be adapted in the implementation and respective tests without breaking anything else in the process?

**Comment by jakob-r** [comment]
That has to be a typo. Clearly we should go `measureMultilabel*`
