### ISSUE TITLE
Match the F-measure and recall measures' behavior to mldr's 

### ISSUE THREAD

**Issue by AlexEngelhardt** [mlr-org/mlr#2167]
This issue arose in the bottom part of the comments of #2161.

The respective issue, #2159 , was fixed, but a few things remained open:

- The F-measure is inconsistent with the mldr implementation. For example, it's not clear what happens in the edge case when TP + FP + FN == 0. See also the disussion in the [mldr issue](https://github.com/fcharte/mldr/issues/45)
- These lines in [tests/testthat/test_base_measures.R](https://github.com/mlr-org/mlr/blob/master/tests/testthat/test_base_measures.R) are sill a bit hacky:

```r
# compare with mldr: copy-pasted older mldr version
# mldr had a bug when RealPositives or PredictedPositives are 0 (see https://github.com/fcharte/mldr/issues/36)
mldr.precision = counters[-3, ]$TruePositives / counters[-3, ]$PredictedPositives
mldr.recall = counters[-3, ]$TruePositives / counters[-3, ]$RealPositives
mldr.fmeasure = mean(mldr.precision * mldr.recall * 2 / (mldr.precision + mldr.recall), na.rm = TRUE)
expect_equal(mldr.fmeasure, measureMultiLabelF1(multi.y[-3, ], multi.p[-3, ]))
```

They should be changed if/when the mldr implementation of `fmeasure` has been changed (it sounds like they are planning to do so).

**Comment by pat-s** [comment]
Hi @AlexEngelhardt, 

what do you mean by the tag [Waiting]? Please try to use labels instead of tags in the title :+1:

**Comment by AlexEngelhardt** [comment]
I can't assign labels I'm afraid.

It means we can't work on this issue right now but are waiting for external action - in this case the promised package update by the mldr authors.  I took this idea from [GTD](https://en.wikipedia.org/wiki/Getting_Things_Done), I like it because it keeps an open topic from regularly requesting my attention when the next step is not dependent on me.

Shall I remove it? If so, the respective label would be nice...

**Comment by pat-s** [comment]
Someone with status "owner" should add you the mlr-org: https://github.com/orgs/mlr-org/people?page=1
Then you are allowed to use labels.

Not sure if there is a need for label "waiting" and if "waiting" is the best label; if so I would use something like "status: waiting for upstream change".

**Comment by larskotthoff** [comment]
@AlexEngelhardt I've invited you as a collaborator. I think that should give you the necessary permissions.

**Comment by AlexEngelhardt** [comment]
Yes, I now see edit gears next to the labels. Thanks for the upgrade!
