### ISSUE TITLE
"sort" makes sense in plotFilterValues()?

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr#2168]
Hello,

does the "sort" parameter in "plotFilterValues()" make sense? I plotted seven filter methods, 3 rows, 3 columns (standard). I used the standard sort = "dec". But this refers to the first method, that is being plotted in the upper left corner. The other methods are not sorted then. So I don't see the sense of this sorting. 
The problem is ggplot. We have one order of features for all the plots above. I don't know how one could handle it.
I tried "facet.wrap.nrow=1", but even then I had the order from the first method.

Best regards,
Markus

**Comment by larskotthoff** [comment]
Not sure what you mean. Have you read the documentation? The sorting refers to the features.

**Comment by mareichhoff** [comment]
Yes, of course! But the sorting refers to the importance value for each method, right? Ordering referring to the filter output. If so, then it doesn't work in my eyes as I described it above in detail.

**Comment by larskotthoff** [comment]
Can you post a complete example that demonstrates the problem please?

**Comment by mareichhoff** [comment]
Right now not. But because the order is not identical for all methods... How would you plot it with ggplot? In case of 7 methods I got such a plot result:

X X X
X X X
X

One X = one "histogram" of one filter method. Under each column I have ONE feature order. One for all plots=methods. The method (1. row, 1st from left) was ordered. This order has been taken for all other "X". Then the 1st X is ordered, but the other not. 

How can one sort over multiple methods, if each method gas its own order?

**Comment by larskotthoff** [comment]
Well what you describe sounds like a bug, but we really need a reproducible example.
