### ISSUE TITLE
Annoying warning for data.table

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#2170]
Hi, is there a special reason why we use `class(newdata)[1] != "data.frame"` instead of `!inherits(newdata, "data.frame")` here:
https://github.com/mlr-org/mlr/blob/ef52d414878d968f15df7ad22e6739d248e0bf7f/R/predict.R#L55

I am getting annoying warings when I use data.table. With `!inherits(newdata, "data.frame")` I wouldn't get them...

**Comment by giuseppec** [comment]
I mean I can see that we still have to convert the data.table to a data.frame here but I would like to get rid of the warning if `newdata` already inherits from a `data.frame`.

**Comment by jakob-r** [comment]
The problem is that a `data.table` inherits from `data.frame` but we don't want a `data.table` because it behaves differently.
```
> inherits(data.table(), "data.frame")
[1] TRUE
```
What is the annoying warning you get?

**Comment by giuseppec** [comment]
Yes, I think we could remove the warning in case of `data.table` as converting `data.table` to `data.frame` should not cause problems.
Well, I don't care anymore as I fixed my issue by always converting a `data.table` to a `data.frame` before I pass it to `predict` which should not make any differance as it would have been converted to a `data.frame` anyway. This way I can at least get rid of the annoying warnings...
