### ISSUE TITLE
FDA tests broken by update of fda.usc

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#2173]
`test_base_fda.R` works fine locally with v1.3.0, update v1.4.0 (live on CRAN) seems to have breaking changes.

**Comment by pfistfl** [comment]
I am on it.

**Comment by pfistfl** [comment]
So, I wrote to the maintainers, as this seems to be a fda.usc internal issue. 

The package (for now) no longer seems to support non-numeric factor levels. 


(Housekeeping):
The problem are lines 127-132 of 
https://github.com/cran/fda.usc/blob/d6ec91f4b148c860169f0ffdd1498a3341c86874/R/classif.np.r

**Comment by pfistfl** [comment]
@mllg 
So I did not get an answer until now.
Should I comment the offending tests and write workarounds or wait until the issue is fixed?

**Comment by mllg** [comment]
It would be great if you could nevertheless disable the test for the current CRAN release so that we get Travis working again.

**Comment by pfistfl** [comment]
Closing, fixed in 2178
