### ISSUE TITLE
Question: How to trim GLM model?

### ISSUE THREAD

**Issue by Cervus1983** [mlr-org/mlr#2179]
When I train a glm model using caret, it's fairly straightforward to trim some "fat" in order to make the resulting object lighter:

```r
caret::train(
	...,
	trControl = trainControl(
		returnData = FALSE,
		returnResamp = "none",
		trim = TRUE
	)
)
```

How can I do something similar when using mlr?

**Comment by larskotthoff** [comment]
No. (And does this actually make a difference in practice?)

Note that most operations in mlr (e.g. tuning) don't save the individual models at all though.

**Comment by Cervus1983** [comment]
Yes, it does make a difference, e.g. when you want to save a model and use it in another script. An "untrimmed" model trained on a large data set will take longer to save/load, and may be simply too large to be loaded on a less endowed machine (e.g. free AWS instance).

I'm looking for some way to save just the model, excluding bits which are unnecessary for making predictions.

**Comment by larskotthoff** [comment]
I'm afraid that mlr doesn't ofer anything for that.

**Comment by Cervus1983** [comment]
I guess I could try and extract the model (coefficients) manually. I just hoped there might be a more elegant solution.

**Comment by SteveBronder** [comment]
Lars, looking at caret's definition of the [trim argument](https://www.rdocumentation.org/packages/caret/versions/6.0-78/topics/trainControl)

> a logical. If TRUE the final model in object\$finalModel may have some components of the object removed so reduce the size of the saved object. The predict method will still work, but some other features of the model may not work. triming will occur only for models where this feature has been implemented.

I believe R's `glm()` returns a copy of the data in the final model (among other things) and `caret` rips out that data and anything else you don't need for bare bones prediction. This is actually pretty useful for production models (I actually ended up doing this at work with an mlr model by hand)

Cervus, we don't have anything like that atm and it's not on our to do list. Though idt it would be that bad.

To do this we would have to write new funcs for each method looking at what we can destroy that would still allow us to use the model for `predict()`. Then we add _another function_ [here](https://github.com/mlr-org/mlr/blob/master/R/train.R#L96) in `train()` to check if it needs to trim the model. IE

```R
trim.randomForest = function(trained_model, ...) {
    rip out stuff
    return(smaller model)
}
```

```R
time.train = measureTime(fun1({learner.model = ripStuff(fun2(fun3(do.call(trainLearner, pars)))})))
```

I do think this is a good idea to implement, but I don't have the bandwidth to do this atm. If you would like to try to add this feel free to make a fork and PR!
