### ISSUE TITLE
QUESTION: Constructing randomForests algorithm with makingBaggingWrapper - TRUE?

### ISSUE THREAD

**Issue by BDillinger** [mlr-org/mlr#2180]
Hi MLR folks,

I have a question regarding creating a random forest using makkingBaggingWrapper:

you state here: [https://mlr-org.github.io/mlr-tutorial/release/html/bagging/index.html](url) that ...

One reason why random forests perform so well is that they are using bagging as a technique to gain more stability. But why do you want to limit yourself to the classifiers already implemented in well known random forests when it is really easy to build your own with mlr?

my question is:

Is this really true since random forests (as invented by Breiman 2001) perform random feature selection at each split during tree growth in order to de-correlate trees, while, as far as I understand, rpart::rpart is not working like this?

In case no, is there any tree method available in R that performs feature selection as described by Breiman (2001)?
Any insight would be highly appreciated.

Thanks for your time!

**Comment by larskotthoff** [comment]
I'm not sure what you're asking. There's `classif.randomForest` which implements Breiman's approach, so there's no need to use the bagging wrapper. If you use `makeBaggingWrapper` with another learner, it probably won't do exactly the same.

**Comment by BDillinger** [comment]
Thanks for your answer.
I'm aware that there is 'classif.randomforest'.

My point is that the link above might maybe a bit misleading since it sugests ()for the quick reader) that rpart::rpart plus bagging plus CV is the same as a Breiman's randomForests, which - if I understood you correctly (?) - is not the case?

**Comment by larskotthoff** [comment]
Sorry, that's not my reading at all. The text doesn't suggest at all that something with the bagging wrapper would be the same as random forests; it explicitly states that the bagging is *one* reason why random forests perform so well.

The bagging wrapper samples both observations and features for the different iterations, regardless of the underlying learner.

**Comment by BDillinger** [comment]
I see, sorry for the misunderstanding!

Any suggestions on my remaining questions?

**Comment by larskotthoff** [comment]
What questions do you still have? You can use `makeBaggingWrapper` to construct bagged trees with different feature subsets.

**Comment by BDillinger** [comment]
Ok, thanks anyway.

**Comment by SteveBronder** [comment]
> In case no, is there any tree method available in R that performs feature selection as described by Breiman (2001)?

RandomForestSRC ?
https://cran.r-project.org/web/packages/randomForestSRC/index.html

I believe the model in the `randomForest` package is the closest implementation of Breiman (2001). 

Note that `mlr` is a meta level wrapper for already existing machine learning models available in R. So you can call a `makeLearner("classif.randomForest")` or `makeLearner("classif.randomForestSRC")` to call the model from either of those packages
