### ISSUE TITLE
In multilabel classification there is not way to set class weights seperately for each label

### ISSUE THREAD

**Issue by ThomasWolf0701** [mlr-org/mlr#2181]
While the multilabel implementation works great, Setting class weights seperately for each Label
does not work. This seems to be possible for multiclass classifiers but not for multilabel ones.
Is there any way to do this ?

If I use tune.threshold with a multilabel classifier i get the following,
even though the base classifier was set to predict.type = "prob"

Error in checkTunerParset(learner, par.set, measures, control) : 
  Using 'tune.threshold' requires a classif learner with predict.type = 'prob'!

If  i pass a weight vector of the correct length to the  makeMultilabelTask,
during cross Validation I get the following error:

Task: dMulti, Learner: binaryRf
[Resample] cross-validation iter 1: [Tune] Started tuning learner multilabel.classif.randomForestSRC for parameter set:
              Type len       Def    Constr Req Tunable Trafo
mtry      discrete   -         -    3,6,12   -    TRUE     -
nodesize  discrete   -         -     1,3,6   -    TRUE     -
na.action discrete   - na.impute na.impute   -   FALSE     -
ntree     discrete   -         -      1000   -    TRUE     -
With control class: TuneControlGrid
Imputation value: -0
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 8; elements = 9.
[Tune] Result: mtry=6; nodesize=3; na.action=na.impute; ntree=1000 : prCurve.test.mean=0.72
Error in mlr::benchmark(modelListMulti, task.Multi, rdesc, measuresMulti) : 
  Assertion on 'weights' failed: Must have length 1260, but has length 1492.

I can use 

makeLearner("classif.xgboost",predict.type = "prob") %>% makeWeightedClassesWrapper(wcw.weight = 0.71) %>% makeMultilabelBinaryRelevanceWrapper() 

But then the weighting would be the same for each label

Thanks for your time.

**Comment by lumatt** [comment]
Hi,

I wanted to ask similar question. Training ranger models packed in makeMultilabelBinaryRelevanceWrapper with tune control:

tune_control <- mlr::makeTuneControlRandom(maxit = 100, tune.threshold=T)

doesn't seem to work.:

"Error in checkTunerParset(learner, par.set, measures, control) : 
  Using 'tune.threshold' requires a classif learner with predict.type = 'prob'!"

In the tuneThreshold documentation I saw: "Optimizes the threshold of predictions based on probabilities. Works for classification and multilabel tasks. Uses BBmisc::optimizeSubInts for normal binary class problems and GenSA::GenSA for multiclass and multilabel problems." What's the reason behind such strange behaviour?

**Comment by pat-s** [comment]
Hi, have you created a learner with `predict.type = "prob"` as the error message indicates?

In any case, please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

**Comment by pat-s** [comment]
Closing due to lack of response.
