### ISSUE TITLE
Error in spatial cross-validation when stratify = TRUE is set

### ISSUE THREAD

**Issue by raff-k** [mlr-org/mlr#2182]
Due to the imbalanced class problem in my spatial data, I would like to perform stratified resampling by setting `stratify = TRUE`. However, I get the following error message:

> Resampling: repeated spatial cross-validation
> Measures:             auc       
> ERROR in resample(learner = learner.rf, task = spatial.task, resampling = resampling,  : 
>   Assertion on 'subset' failed: Contains missing values.

With the mlr-`spatial.task`-data I can reproduce the issue:

```r
# devtools::install_github("mlr-org/mlr") # using developer version of mlr
library("mlr")
data("spatial.task")

# Spatial Cross-Validation
learner.rf = makeLearner("classif.ranger", predict.type = "prob")

resampling = makeResampleDesc("SpRepCV", fold = 5, reps = 3, stratify = TRUE)

set.seed(123)
out = resample(learner = learner.rf, task = spatial.task,
               resampling = resampling, measures = list(auc))
````

However, using `"RepCV"`  instead of `"SpRepCV"` is working.

**Comment by pat-s** [comment]
Haven't tested it with `stratify = TRUE`. Idk when I find time in the next days to look into it - debugging should get you closer to the problematic part. 

Call `debug(resample)` and then execute the code step by step until you have found the error source.

**Comment by raff-k** [comment]
It seems that the training set contains `NA` values causing the error...

Following the nested functions to the end starting with `resample()`:

> parallelMap()
> res = mapply(fun2, ..., MoreArgs = more.args, SIMPLIFY = FALSE, 
>       USE.NAMES = FALSE)
> calculateResampleIterationResult() in fun2
> train()
> subsetTask()
> getTaskData() in changeData(...)
> checkTaskSubset()
> asInteger(subset, min.len = 1L, any.missing = FALSE, lower = 1L, upper = size) # here the error occured

However, checking `more.args$rin$train.inds` in the `mapply` call, there are already `NA`s.
So the bug must be before(?)... I have not found the code yet, where the stratification is done :-/

**Comment by raff-k** [comment]
... in the `makeResampleInstance()` the `NAs` appear in the line
```r 
train.inds[[i]] = lapply(inst$train.inds, function(j) ci[j])
 ```
so, maybe in the line above something goes wrong:
`inst = instantiateResampleInstance(desc, length(ci), task)`

... so far for now ;-)

**Comment by pat-s** [comment]
Won't fix as all effort is going into _mlr3_ and this is really an edge-case.
