### ISSUE TITLE
update the example in "create custom filters" tutorial section

### ISSUE THREAD

**Issue by pczhang** [mlr-org/mlr#2183]
suggest to update the nonsense.filter example in the tutorial.
change 'pkg = ""' to 'pkg = character(0)'
currently generateFilterValuesData(task, "nonsense.filter") is ok,
but makeFilterWrapper will lead to error. It is confusing for newbies like me who are trying to create custom filters.

```r
makeFilter(
  name = "nonsense.filter",
  desc = "Calculates scores according to alphabetical order of features",
  pkg = "",
  supported.tasks = c("classif", "regr", "surv"),
  supported.features = c("numerics", "factors", "ordered"),
  fun = function(task, nselect, decreasing = TRUE, ...) {
    feats = getTaskFeatureNames(task)
    imp = order(feats, decreasing = decreasing)
    names(imp) = feats
    imp
  }
)
task = makeClassifTask(data = iris, target = "Species")
lrn = makeLearner("classif.lda")
lrn = makeFilterWrapper(lrn, fw.method = "nonsense.filter", fw.abs = 2)
mod = train(lrn, task)
```

**Comment by jakob-r** [comment]
Thanks for reporting that issue.

1. We have to allow no package in `makeFilter`. I started a fix in the branch [fix2183_allow_no_learner](https://github.com/mlr-org/mlr/compare/fix2183_allow_no_learner?expand=1)
2. We have to change the tutorial. But this is currently in a transition phase.
