### ISSUE TITLE
Feature importance multi-label classification

### ISSUE THREAD

**Issue by maxiepad37** [mlr-org/mlr#2185]
Hi,

I have conducted a multi-label classification by means of a randomForestSRC method-adaption. I would like to have some insights in the feature importance for predicting specific labels. I have tried generating partial dependence data, but i am guessing this is not possible for multi-label data. 

Is there any way I adapt the partial dependence plots for multi-label classification? And if not, are there any other methods available? (Aside from the permutation importance)  

```r
#code
task = makeMultilabelTask(data=df,target="labels")

lrn.rfsrc = makeLearner("multilabel.randomForestSRC", predict.type = "prob")

mod.rf=mlr::train(lrn.rfsrc,task,subset=train.set)

pd = generatePartialDependenceData(mod.rf,df.train)

"Error in `[.data.frame`(out, , c("Class", "Probability", features, colnames(out)[!colnames(out) %in%  : 
  undefined columns selected"
```

**Comment by haseebmahmud** [comment]
Asking the same/similar question. generatePartialDependenceData produces an error. The example code,
```

library(mlr)
library(mmpf)

yeast <-  getTaskData(yeast.task)
labels <- colnames(yeast)[1:14]
yeast.task <- makeMultilabelTask(id = "multi", data = yeast, target = labels)

lrn.br <- makeLearner("classif.rpart", predict.type = "prob")
lrn.br <- makeMultilabelBinaryRelevanceWrapper(lrn.br)

mod <- mlr::train(lrn.br, yeast.task, subset = 1:1500, weights = rep(1/1500, 1500))
pred <- predict(mod, newdata = yeast[1501:1600,])

performance(pred, measures = list(multilabel.subset01, multilabel.hamloss, multilabel.acc,
                                   multilabel.f1, timepredict))

rdesc <- makeResampleDesc(method = "CV", stratify = FALSE, iters = 3)
r <- resample(learner = lrn.br, task = yeast.task, resampling = rdesc, show.info = FALSE)

getMultilabelBinaryPerformances(pred, measures = list(acc, mmce, auc))
getMultilabelBinaryPerformances(r$pred, measures = list(acc, mmce))

getLearnerModel(mod)

pd <- generatePartialDependenceData(mod, yeast.task)
plotPartialDependence(pd)

```
The line before the last gives me an error message, 
```
> pd <- generatePartialDependenceData(mod, yeast.task)
Error in data.table(preds, design[, vars, drop = FALSE], key = vars) : 
  column or argument 1 is NULL
```
Is there any way out to generate and plot partial dependence plot for multilabel classification problem?

**Comment by edvbb** [comment]
I have a similar problem
`getFeatureImportance(mrforest)
Error in checkLearner(object$learner, props = "featimp") : 
  Learner 'multilabel.randomForestSRC' must support properties 'featimp', but does not support 'featimp'.`
