### ISSUE TITLE
imputation with makePreprocWrapperCaret

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#220]
We need to add property `missings` to the learner if we wrap it with `makePreprocWrapperCaret` and any of the arguments `ppc.knnImpute`, `ppc.bagImpute`, and `ppc.mediaImpute` is TRUE.

**Comment by jakob-r** [comment]
It is <s>difficult</s>some work to change that dynamically with the usage of `setHyperPars()` so I changed it to support missings by default.

**Comment by berndbischl** [comment]
@studerus 
Does that solve your problem?

**Comment by studerus** [comment]
Why is it much work? Can't we just put the following if statement before `addProperties(learner, "missings")`:
```{r}
if (any(unlist(par.vals[grep("Impute", names(par.vals))])))
```

**Comment by berndbischl** [comment]
You need to consider that you can call setHyperPars later.....

**Comment by studerus** [comment]
Ah ok, then I don't know how to best do this. @berndbischl Its probably better if you assign jakob-r or someone else for this task. The solution is ok for now but I don't think we should leaf it like that.

**Comment by berndbischl** [comment]
Well I mainly assigned you to give feedback / test it.

What we can do, that is our only choice I guess:
Have setHyperPars later change the properties of the learner.

Can that be bad in any way? Maybe this is totally OK?

**Comment by studerus** [comment]
I think its ok, but you know the internals much better than me.

**Comment by berndbischl** [comment]
@jakob-r 
Can you please try to ovveride setHyperPars and make a proposal?

**Comment by berndbischl** [comment]
@jakob-r 
What is the status here?

**Comment by berndbischl** [comment]
another ping....

**Comment by jakob-r** [comment]
The only solution which sounds nice to me, is to have a S3 `getLearnerProperties` which for a normal learner will just return `lrn$properties` and for special cases (like wrappers) there is a `getLearnerProperties.PreprocWrapperCaret()` and if a normal learner has some strange behaviour we can just write a `getLearnerProperties.classif.gbm`.

We already have the foundation for that but the PreprocWrapperCaret has to get his own class and we have to make sure to use the getter everywhere. Maybe I oversaw something but with this approach it doesn't seem so difficult anymore.

So do you @berndbischl give green light?

**Comment by berndbischl** [comment]
Adding getLearnerProperties is needed anyway. And yes we can specialize / overwrite it for sublcasses.
Do a PR.

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
