### ISSUE TITLE
Adding multinomial support to classif.h2o.glm

### ISSUE THREAD

**Issue by kdpsingh** [mlr-org/mlr#2207]
According to the latest h2o documentation, h2o's glm function now supports multiclass classification (and I think that support dates back a couple of versions now).

I would suggest changing the default family from `binomial` to `multinomial` and adding `multiclass` to the list of learner properties.

@ledell, any issues that you would anticipate with this?

**Comment by ledell** [comment]
@kdpsingh H2O GLM has had support for multinomial for a long time, but it was not working with one of the solvers and that has recently been fixed.  I think it would be good to add `multiclass` to the list of learner properties.  I'm not sure about what would be the best default for family -- whatever makes the most sense on your end.  In H2O, the default GLM family is `gaussian`.

**Comment by kdpsingh** [comment]
Great, thanks for the input. Yes, mlr's "regr.h2o.glm" also has `gaussian` as the default family (when it wraps the function call).

However, the default family for classification problems ("classif.h2o.glm") using mlr is `binomial` rather than `multinomial`. I'm pretty sure that the `multinomial` family can handle situations with only 2 classes, so I think it would make more sense for the `multinomial` family to be the default within mlr's "classif.h2o.glm" learner and for the properties to be updated to include `multiclass` support.

**Comment by ledell** [comment]
@kdpsingh If you pass in "multinomial" to a 2-class response, it will give an error in H2O:

```
library(h2o)
h2o.init()

train <- h2o.importFile("https://s3.amazonaws.com/erin-data/higgs/higgs_train_10k.csv")
y <- "response"
x <- setdiff(names(train), y)
train[,y] <- as.factor(train[,y])

fit <- h2o.glm(x = x, y = y, training_frame = train, family = "multinomial")
```

Error:
```
Illegal argument(s) for GLM model: GLM_model_R_1519845896884_91.  Details: ERRR on field: _family: Multinomial requires a categorical response with at least 3 levels (for 2 class problem use family=binomial.
```

So maybe it makes sense to keep the default family for classification `"binomial"` which is also consistent with the rest of the mlr classification wrappers?

**Comment by kdpsingh** [comment]
@ledell Thank you for catching that! I didn’t realize that sending a 2-class problem to the “multinomial” family results in an error. That would definitely preclude changing the default family for this learner in mlr.

Personally, I feel like ideal behavior would be for mlr to check the number of classes and to set the argument for *family* to “binomial” if 2 classes and “multinomial” if 3+ classes. This would effectively make the “classif.h2o.glm” learner work “automatically” for both 2-class and multiclass problems. This approach wouldn’t break anyone’s code and would make this learner more consistent with other learners that support both 2-class and multiclass problems.

However, that’s a design decision that mlr devs can weigh in on. It would be fairly easy to implement.

**Comment by ledell** [comment]
@kdpsingh 
> Personally, I feel like ideal behavior would be for mlr to check the number of classes and to set the argument for family to “binomial” if 2 classes and “multinomial” if 3+ classes.

This sounds good to me as part of the mlr wrapper code, but as you mentioned, mlr devs can weigh in on this.  My objection is only relevant if you were going to pass `family = "multinomial"` directly down to `h2o.glm()` which it sounds like you're not planning on doing (so please disregard).
