### ISSUE TITLE
important CRAN issue, violates cran policy

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#2216]
From Kurt:

Dear Bernd,

Sorry for bothering you again: apparently checking the new version
leaves behind files like

  RtmpR3AGA0 test.svg

in the tempdir, rather than *inside* the session dir, apparently from

  ./mlr/tests/testthat/test_base_generateFilterValuesData.R:
     path = paste(tempdir(), "test.svg")

As this violates the CRAN Policy, it should be fixed as quickly as
possible: perhaps you can simply change paste to file.path and resubmit?

Best
-k

**Comment by berndbischl** [comment]
@larskotthoff @mllg @jakob-r

**Comment by berndbischl** [comment]
@jakob-r you fix doesnt work, using filepath is better programming, but you are still in the main TEMP folder not in the session folder!

**Comment by jakob-r** [comment]
And i think the backslash forwardslash issue on windows / unix system.

The fix is just what was in the mail. Now we write in the correct session temp dir which will get deleted.
