### ISSUE TITLE
DLL problems on CRAN with mlr 2.12

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#2220]
we still break on CRAN with mlr 2.12

see here
https://cran.r-project.org/web/packages/mlr/index.html

this is really bad and we need to fix this. i also dont understand why this happens

**Comment by berndbischl** [comment]
@larskotthoff @mllg

**Comment by mllg** [comment]
r-oldrel + r-release on linux/mac os/solaris do not have the environment variable set, thus the DLL limit is 100 on these systems.

**Comment by berndbischl** [comment]
but that does not really clear this up. why are we now loading so many of these? in the "base" suite?
that seems strange?

**Comment by berndbischl** [comment]
so my main question (also see my mail to thomas just now):
how do we see what happens and who loads which DLLs in our tests?

**Comment by berndbischl** [comment]
i got this from thomas kalibera


> It seems you can use
> .Internal(getLoadedDLLs())
> that gives also the path names
> .Internal(getLoadedDLLs())
                                                Filename Dynamic.Lookup
base                                                base          FALSE
methods       /usr/lib/R/library/methods/libs/methods.so          FALSE
utils             /usr/lib/R/library/utils/libs/utils.so          FALSE
grDevices /usr/lib/R/library/grDevices/libs/grDevices.so          FALSE
graphics    /usr/lib/R/library/graphics/libs/graphics.so          FALSE
stats             /usr/lib/R/library/stats/libs/stats.so          FALSE

**Comment by pat-s** [comment]
As far as I understand it, the mass of packages that are loaded in the tests sum up and exceed the DLL number. As the DLL number is only increased in r-devel and still limited to 100 as @mllg pointed out, we are running into troubles.

Not sure if one package only loads one DLL as indicated in the `getLoadedDLLs()` funciton.. I think we discussed about this on the relase day with Rcpp packages linking to more DLLs. 

Disabling tests for r-oldrelease and r-release is of course convenient but you have to ask if CRAN is ok with it.
However, either CRAN increases the DLL limit for r-relase and r-oldrelease or we need to disable the tests. I think there is no other solution. Why should we bother with reducing the tests for these two versions if r-devel is fine? R v3.5 should anyway be released somehow soon so I think there should be a "good solution for everyone" if you just ask.

**Comment by pat-s** [comment]
Whats the status here Bernd?

**Comment by berndbischl** [comment]
That my schedule sucks

**Comment by pat-s** [comment]
AFAIR the limit was increased in R v3.5 and the issue does not apply anymore therefore.
