### ISSUE TITLE
Issue with imputeLearner while imputing

### ISSUE THREAD

**Issue by AdityaIyer** [mlr-org/mlr#2226]
I am trying to run the following code but it still hangs.

rpart_imp <- impute(train, target = "Loan_Status",
classes = list(numeric = imputeLearner(makeLearner("regr.rpart")),
factor = imputeLearner(makeLearner("classif.rpart"))),
dummy.classes = c("numeric","factor"),
dummy.type = "numeric")

i am aware that the imputeLearner had issues but is the problem fixed or is there anyway i can achieve similar results using rpart package or learn since makeLearner seem to have no trouble. Thanks

**Comment by larskotthoff** [comment]
Please don't cross-post.

Please provide a complete example that allows to reproduce the problem. What do you mean by "it just hangs"?

**Comment by AdityaIyer** [comment]
Ohh, My apologies. This is my first time & i did try to search for similar issues to mine. What i meant was that i have a model of multi-caterogorical data with character & numerical values for a loan prediction problem. In the data zip folder, there is a training & testing set with following dimensions 
dim(train)
[1] 614  13
> dim(test)
[1] 367  12

 > head(train)
   Loan_ID Gender Married Dependents    Education Self_Employed ApplicantIncome CoapplicantIncome LoanAmount Loan_Amount_Term
1 LP001002   Male      No          0     Graduate            No            5849                 0         NA              360
2 LP001003   Male     Yes          1     Graduate            No            4583              1508        128              360
3 LP001005   Male     Yes          0     Graduate           Yes            3000                 0         66              360
4 LP001006   Male     Yes          0 Not Graduate            No            2583              2358        120              360
5 LP001008   Male      No          0     Graduate            No            6000                 0        141              360
6 LP001011   Male     Yes          2     Graduate           Yes            5417              4196        267              360
  Credit_History Property_Area Loan_Status
1              1         Urban           Y
2              1         Rural           N
3              1         Urban           Y
4              1         Urban           Y
5              1         Urban           Y
6              1         Urban           Y
> head(test)
   Loan_ID Gender Married Dependents    Education Self_Employed ApplicantIncome CoapplicantIncome LoanAmount Loan_Amount_Term
1 LP001015   Male     Yes          0     Graduate            No            5720                 0        110              360
2 LP001022   Male     Yes          1     Graduate            No            3076              1500        126              360
3 LP001031   Male     Yes          2     Graduate            No            5000              1800        208              360
4 LP001035   Male     Yes          2     Graduate            No            2340              2546        100              360
5 LP001051   Male      No          0 Not Graduate            No            3276                 0         78              360
6 LP001054   Male     Yes          0 Not Graduate           Yes            2165              3422        152              360
  Credit_History Property_Area
1              1         Urban
2              1         Urban
3              1         Urban
4           <NA>         Urban
5              1         Urban
6              1         Urban

I had earlier built a rpart model which worked just fine with the data & was able to impute the missing values. This time, i was learning to use MLR package, thus was trying to rebuild my previous rpart based model with MLR functions & was able to make the builder for class.if & regrss.if yet while using imputeLearner in following commands.

# Missing Value Imputation

imp <- impute(train, classes = list(factor = imputeNormal(), integer = imputeMean()), dummy.classes = c("integer","factor"), dummy.type = "numeric")
imp1 <- impute(test, classes = list(factor = imputeNormal(), integer = imputeMean()), dummy.classes = c("integer","factor"), dummy.type = "numeric")

rf_imp <- impute(train, target = "Loan_Status",
                    classes = list(numeric = imputeLearner(makeLearner("regr.rpart",predict.type = "response")),
                                   factor = imputeLearner(makeLearner("classif.rpart",predict.type = "response"))),
                    dummy.classes = c("numeric","factor"),
                    dummy.type = "numeric")

The command impute with imputeLearner sends my R console into almost an infinite loop which then i have to forcibly stop while impute with other functions run just fine. I did read up that imputeLearner had prior issues thus, i wanted to know if this is still an ongoing issue/feature. 

[data.zip](https://github.com/mlr-org/mlr/files/1826622/data.zip)
