### ISSUE TITLE
using xgboost early_stopping_rounds parameter in cross-validation

### ISSUE THREAD

**Issue by Toekan** [mlr-org/mlr#2227]
Hi,

From going through the issues on xgboost's early_stopping_rounds I understand that the implementation for it in mlr is by passing the train and test data also through the watchlist parameter.  So to get it to work with a holdout resampling description, I did the following:

```r
# Create the mlr task, learner and resampling object
task <- makeClassifTask(data = df, target = 'OUTCOME', positive = 1)
lrn <- makeLearner("classif.xgboost", predict.type = "prob")
rdesc <- makeResampleDesc("Holdout")
rin <- makeResampleInstance(rdesc, task)

# Making a copy of the data in xgb Dmatrix format
df_train <- df[rin$train.inds[[1]],]
df_train$OUTCOME <- as.numeric(as.character(df_train$OUTCOME))
mat_train <- as.matrix(df_train)
dmat_train <- xgb.DMatrix(mat_train[,-1], label=mat_train[,'OUTCOME'])

df_test <- df[rin$test.inds[[1]],]
df_test$OUTCOME <- as.numeric(as.character(df_test$OUTCOME))
mat_test <- as.matrix(df_test)
dmat_test <- xgb.DMatrix(mat_test[,-1], label=mat_test[,'OUTCOME'])

# Pass watchlist as one of the parameters
watchlist <- list(train=dmat_train, test=dmat_test)

lrn$par.vals = list(
  watchlist = watchlist,
  early_stopping_rounds = 20,
  nrounds = 500
)

# Train the model
res <- resample(lrn, task, rin)
```

Two questions:
- Is there a more elegant way to do this so that I don't have to copy my data just to send it twice to resample? (once through task, once through the watchlist parameter)
- More importantly: How do I use early_stopping_rounds in cross-validation? I know xgboost has a cv function, but the mlr implementation only seems to call xgb.train. 

Thanks!

**Comment by danielhomola** [comment]
HI good people of mlr! 

Has anyone looked into this maybe?  This is one of the best features of xgboost and helps a ton with hyper-parameter tuning.. If this is low priority, can someone provide some pointers how would one go about adding this to the xgboost learner of mlr?

Many thanks!

**Comment by ja-thomas** [comment]
Hi, have a look here:

https://github.com/ja-thomas/autoxgboost/blob/master/R/RLearner_classif_xgboost.earlystop.R
