### ISSUE TITLE
parallel tuning h2o.randomForest with parallelMap

### ISSUE THREAD

**Issue by fgreschner** [mlr-org/mlr#2237]
Parallel tuning of h2o learners (e.g. h2o.randomForest) is not possitble with parallelMap::parallelStartSocket() since h2o.init() cannot be called more than one time 

```r
library(mlr)
library(parallelMap)

learner <- makeLearner("classif.h2o.randomForest")

ps <- makeParamSet(
  makeNumericParam("sample_rate", lower = 0.01, upper = 1),
  makeIntegerParam("ntrees", lower = 10, upper = 500),
  makeIntegerParam("max_depth", lower = 3, upper = 10),
  makeIntegerParam("nbins", lower = 2, upper = 20),
  makeIntegerParam("min_rows", lower = 5, upper = 50),
  makeIntegerParam("nbins_cats", lower = 100, upper = 2000)
)
ctrl <- makeTuneControlRandom(maxit = 10)
rdesc <- makeResampleDesc("CV", iters = 3L)
parallelStartSocket(10)
res <- tuneParams(
  learner = learner,
  task = iris.task, resampling = rdesc,
  par.set = ps, control = ctrl
)
parallelStop()
```

**Comment by larskotthoff** [comment]
Is parallel tuning something that should be possible in general with h2o?

**Comment by fgreschner** [comment]
that would be best

**Comment by larskotthoff** [comment]
What I mean is, does it work on the h2o side? As everything is communicating with the server, I'm not sure whether it's possible in general.

**Comment by fgreschner** [comment]
Don't know, maybe that's the issue....

**Comment by j-hartshorn** [comment]
The H2O instance / cluster works across multiple cores by default. It doesn't make sense to do the R parts in parallel because the most computationally difficult work, the model training, is done in parallel already.
