### ISSUE TITLE
Hypothesis testing for benchmark experiments

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr#2238]
My work in regards to hypothesis testing for benchmark experiment will require some overhaul in the next weeks, as one of the packages it depends on will no longer be maintained (see #2198).

In the mean time, some papers have come out, that at least partially question how this should be conducted. [1](http://ieeexplore.ieee.org/document/8259793/), [2](https://arxiv.org/abs/1606.04316).

Additionally, one new idea I found interesting that involves confidence curves has been proposed [3](https://link.springer.com/article/10.1007/s10994-016-5612-6) [github](https://github.com/dberrar/ConfidenceCurve)

I wanted to clarify a few things before I move forward.

1. Is there even demand in fixing hypothesis testing? I do not have any idea how widely used this is, if at all.

2. Should we think about adding more functionalities, such as the confidence curves, and maybe even different methods?

@giuseppec Should we maybe talk to the [benchmarkVis](https://github.com/collinleiber/benchmarkVis) people?

**Comment by giuseppec** [comment]
Talking to people is always a good idea. You can listen to their presentation of benchmarkVis on Friday, 13th. Just talk to me if you want to get in touch with them.
