### ISSUE TITLE
Question: parametric tests for benchmark experiement?

### ISSUE THREAD

**Issue by XPeriment2** [mlr-org/mlr#2248]
Asking here as I was yelled at on Stackflow.
Can I compare performance of the learners using parametric tests in the mlr package? (not just the Friendmand test) let's say accuracy and AUC - using ANOVA or t-test? c

thanks

**Comment by pfistfl** [comment]
Parametric tests on benchmark results are not necessarily valid,
as in many cases the assumptions they require are not met for benchmark experiments.
See: 
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.141.3142&rep=rep1&type=pdf

If you really want to do it, you can always extract the auc etc. and use it for parametric tests.

Another great source:
http://www.jmlr.org/papers/volume18/16-305/16-305.pdf

**Comment by jakob-r** [comment]
There is no hypothesis testing on performance measures in mlr for the mentioned reasons.

**Comment by berndbischl** [comment]
not saying that i doesnt make sense, in all cases, to use parametric tests.
but currently this is not implemented in mlr.

but it is very easy to compute the results with mlr, get yourself the data.frame with the scores, then test yourself in R with any test you deem appropriate?
