### ISSUE TITLE
regr.nnet : some output layer params should likely be removed?

### ISSUE THREAD

**Issue by sycoforbidden** [mlr-org/mlr#2257]
When calling getParamSet("regr.nnet"), we get:

                Type  len  Def Constr Req Tunable Trafo
    linout   logical   -  FALSE    -   Y    TRUE     -

However, upon inspection of the mlr:::trainLearner.regr.nnet() function, one gets

> function (.learner, .task, .subset, .weights = NULL, ...) 
> {
>   if (is.null(.weights)) {
>     f = getTaskFormula(.task)
>     nnet::nnet(f, data = getTaskData(.task, .subset), **linout = TRUE**, 
>       ...)
>   }
>   else {
>     f = getTaskFormula(.task)
>     nnet::nnet(f, data = getTaskData(.task, .subset), **linout = TRUE**, 
>       weights = .weights, ...)
>   }
> }
> 

So when making a learner regr.nnet by default, which instance of linout is used?

**Comment by sycoforbidden** [comment]
Alright then, thank you for the quick response.

**Comment by berndbischl** [comment]
@mb706 gblame says you added these some time ago.


```
      makeLogicalLearnerParam(id = "linout", default = FALSE, requires = quote(entropy == FALSE && softmax == FALSE && censored == FALSE)),
      makeLogicalLearnerParam(id = "entropy", default = FALSE, requires = quote(linout == FALSE && softmax == FALSE && censored == FALSE)),
      makeLogicalLearnerParam(id = "softmax", default = FALSE, requires = quote(entropy == FALSE && linout == FALSE && censored == FALSE)),
      makeLogicalLearnerParam(id = "censored", default = FALSE, requires = quote(linout == FALSE && softmax == FALSE && entropy == FALSE)),
```

any reason?

**Comment by sycoforbidden** [comment]
Maybe he added those since they are the default parameters of nnet:::nnet.default() ? Even though what you're applying here should be nnet:::nnet.formula() ?

**Comment by berndbischl** [comment]
the latter 3 only make sense for classification. they should really be removed

**Comment by mb706** [comment]
I think git only blames me for changing the formatting of these lines, the lines were added to `regr.nnet` [long before my time](https://github.com/mlr-org/mlr/commit/30ba2c14331d4aa8627339eb740ca28198d85d1b). Similar parameters (although commented out) are in `classif.nnet` since [recorded history](https://github.com/mlr-org/mlr/blob/311668c3a096b5b0fdf6bd5d431008d2e4040fc1/mlr/skel/R/RLearner_classif_nnet.R).
