### ISSUE TITLE
Resampling: Add "blocking" resample description to work within nested resampling

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2266]
Related: https://github.com/mlr-org/mlr/issues/1498

#### Problem

- While the `blocking` argument in `make*Task()` works in a normal resample situation, it does not work in nested situations. 

- This is because the `blocking` information is stored in the task and is not independent from the chosen Resample instances in the outer and inner level. 

- Furthermore it is confusing if one sets `blocking` and then specifies one of the Resampling Descriptions (E.g. CV) although no CV is performed in fact. `blocking` should only be usable in a specific Resample description, e.g. `makeResampleDesc("Blocking")`. 

#### Example
For example: I want to have a "blocking" resampling in the outer level for performance estimation but a CV based hyperparameter tuning in the inner level.
I get an error because the inner resampling instance tries to use the blocked indices but the sample is only a subset of the initial sample at that stage. Subsequently, the function errors.

#### Motivation & Solution

- It should be possible to have two independent resampling strategies. With the current implementation of `blocking` this is not possible.

- I vote for the implementation of a Resample description named "blocking" that accepts a factor variable with length(obs) and returns one repetition of `n` folds `n(= length(levels))`. 

- The `blocking` argument in `make*Task()` can stay and behave similar to `coordinates` which is also only used if either `SpCV` or `SpRepCV` is specified.

Of course this is only an additional resample option and does not solve the possibility of user-defined resampling splits as proposed in #1498

**Comment by pat-s** [comment]
Inspecting object `p` in https://github.com/mlr-org/mlr/blob/de21b5c749caf3d98173f27947e78564ff01aa7f/tests/testthat/test_base_blocking.R#L28

I am a bit confused: I assumed that the `test.inds` should only contain groups of "blocked" indices. Since we have groups of five in the task, I expected only sequences of 5, e.g. 1,2,3,4,5 or 26,27,28,29,30

Instead, the test indices look random:

```
sort(p$instance$test.inds[[1]])
 [1]   5   7  10  13  17  18  21  22  25  28  35  37  40  43  47  48  51  52  55  58  65  67  70  73  77  78  81  82  85  88  95  97 100 103 107
[36] 108 111 112 115 118 125 127 130 133 137 138 141 142 145 148
```

Did I miss something here or is the `blocking` feature broken? 
@jakob-r @larskotthoff

**Comment by larskotthoff** [comment]
Thanks for looking into this! I'm not sure if this is the way to go though -- it feels to me like we should simply stop with an error message if the user tries to do something like that. Combining blocking with nested resampling sounds like it would lead to unexpected results in at least some cases.

**Comment by pat-s** [comment]
> Combining blocking with nested resampling sounds like it would lead to unexpected results in at least some cases.

I think it should be possible to use "blocking" in a nested resampling. Users that want to use this know anyways what they want to do. Why should it not be possible to tune hyperpars when using "blocking"? Thats the main problem for me. 

What makes you thinking that prohibiting this feature from the user would be better?

**Comment by larskotthoff** [comment]
Depending on what the blocking is, it may not be possible to have enough nested folds to support it. I guess as long as there's an error message in that case I'd be fine with it.

**Comment by pat-s** [comment]
> Depending on what the blocking is, it may not be possible to have enough nested folds to support it. I guess as long as there's an error message in that case I'd be fine with it.

Nested folds will always be `length(levels)` - 1 with the current implementation. In the future we could think of allowing custom levels for the inner and outer levels. In the PR there is no check yet that the blocking levels should be >= 3 in a nested setting (to have at least 2 folds in the inner, otherwise it makes no sense). But I can add that :)

**Comment by jakob-r** [comment]
I am a bit confused. I guess there are different interpretations of "blocking"

1) I want to completely control how the re-sampling looks --> use fixed resample instances --> only for outer resampling
2) I use blocking to keep specific observation pairs together but i have enough of those small blocks so that nested re-sampling is still possible and usefull --> throw an error if splits can not be created

What you proposed in your PR goes more into the direction of 2 am I right? Did you encounter any bugs regarding this case?

If you want to solve 1) I don't know if using the names and means of 2) is the right way to go.

**Comment by pat-s** [comment]
> I want to completely control how the re-sampling looks --> use fixed resample instances --> only for outer resampling

That's more what the PR is about. Having fixed instances for only one repetition. 
The new thing is that you can also do it during tuning then, using k-1 folds/levels from the outer loop. 

Currently, I want to leave "blocking" as it is and extend the "fixed resample instances" to also work during tuning.
