### ISSUE TITLE
Slack Workspace

### ISSUE THREAD

**Issue by pokyah** [mlr-org/mlr#2271]
Hi,

Sorry, it might not be the best place where to ask this but how can I join the [[slack group](https://mlr-org.slack.com/)]. Slack tells me that I need to ask the admin to invite me but I can't find a link for this purpose.

Thanks for your help.

**Comment by berndbischl** [comment]
could you post some context please?`and this is the correct place :)

**Comment by pokyah** [comment]
Hi @berndbischl ,

On the mlr doc [homepage](https://mlr-org.github.io/mlr/), there is a link button to the mlr salck group. I thought I could join the mlr-slack-workspace to exchange know-how, ask questions, etc ...

I know that i could ask my questions on SO and submit improvments through github but for small hints and suggestions, I thought the slack group could be the best place (unless it is reserved for main contributors ?). 

BTW, I plan to use mlr for spatial data prediction.

Thanks !

**Comment by berndbischl** [comment]
currently it is more used for devels. we could open this in general, but then we should make a coordinated decision.

just ask here or on SO

**Comment by jakob-r** [comment]
@pokyah Did you write me an email? It states in the README:
> We are on Slack (Request invitation: code{at}jakob-r.de)

**Comment by pokyah** [comment]
Hi @jakob-r, Hi @berndbischl 

OK. I did not notice that the information to apply for joining the slack group was in the readme file.

At the moment I'm beginning to use mlr package for spatial interpolation purposes. I'll ask my questions through SO. And if later I've improvements to discuss/suggest, I'll go through pull request and/or slack ! 

Thanks for your feddbacks
