### ISSUE TITLE
could not find function “generateFunctionalANOVAData”

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#2294]
We still have `generateFunctionalANOVAData` this in [vignette & tutorial](https://github.com/mlr-org/mlr/search?q=generateFunctionalANOVAData&unscoped_q=generateFunctionalANOVAData) but it seems that we removed it from `mlr` (see here https://stackoverflow.com/questions/50828653/could-not-find-function-generatefunctionalanovadata).
Maybe @zmjones can say something about this. Shall we refer to https://github.com/zmjones/fanova ?

**Comment by zmjones** [comment]
nah we should delete those references until fanova works better. right now it still blows up on even moderately sized tasks and i've been working on other things, so its improvement isn't imminent.

**Comment by zmjones** [comment]
sorry i meant to have removed all of them but apparently missed some
