### ISSUE TITLE
the the quickstart page really sucks. should we change it?

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2322]
_From @berndbischl on August 27, 2016 12:44_

lets collect some ideas here.

_Copied from original issue: mlr-org/mlr-tutorial#56_

**Comment by pat-s** [comment]
_From @MasonGallo on August 27, 2016 16:40_

I would propose a quick start for various common "tasks" that basically become quick scripts for users to adapt:
- classification with resampling and hyperparam tuning
- regression with resampling and hyperparam tuning
- benchmarking
- clustering
- etc

sklearn sorta does this where if you go on the documentation for a learner, they have "examples" at the bottom of each page [example](http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#examples-using-sklearn-neighbors-kneighborsclassifier)

**Comment by pat-s** [comment]
_From @jakob-r on August 27, 2016 18:18_

Why does it suck?
My proposal: We could have a Quickstart section for every chapter.

**Comment by pat-s** [comment]
_From @larskotthoff on August 27, 2016 19:20_

I like the idea of having a quickstart for every chapter.

**Comment by pat-s** [comment]
_From @berndbischl on August 27, 2016 22:9_

> Why does it suck?

because it is much too short and does not really help you to get into the package.
and some people dont want to spend hours reading our lengthy chapters

> I like the idea of having a quickstart for every chapter.

i dont. and we already had this in the past! turned out it was unmaintenable because it resulted in having each chapter kinda "twice". it also seems to go overboard / is not what the quickstart should be (IMHO).

I like what Mason posted. Some sweet, cool worked out use cases. We don't need a million.
I think eg posting a solution to this would not be bad

https://www.kaggle.com/c/titanic

**Comment by pat-s** [comment]
_From @ja-thomas on August 28, 2016 11:1_

> I think eg posting a solution to this would not be bad
> 
> https://www.kaggle.com/c/titanic

We wanted to do this anyways and post it on the kaggle scripts right?

**Comment by pat-s** [comment]
_From @berndbischl on August 28, 2016 12:17_

> We wanted to do this anyways and post it on the kaggle scripts right?

yes we could do this too, good idea

**Comment by pat-s** [comment]
_From @jakob-r on August 29, 2016 11:31_

So what you want is not a quickstart but a guided use case? IMO The quickstart is intended to give a copy pasta example without statistical / machine learning background. Because when you already have that background you can understand a simple code snippet easily.

But you are right that we had it already kind of like this. But maybe we did it wrong and we are able to do it better now.

**Comment by pat-s** [comment]
_From @jakob-r on August 29, 2016 11:34_

And [bug] is clearly an overstatement.

**Comment by pat-s** [comment]
_From @berndbischl on August 29, 2016 15:47_

> So what you want is not a quickstart but a guided use case? IMO The quickstart is intended to give a copy pasta example without statistical / machine learning background. Because when you already have that background you can understand a simple code snippet easily.
> 
> But you are right that we had it already kind of like this. But maybe we did it wrong and we are able to do it better now.

the quickstart is supposed to give a quick, hands on introduction to get into the package. 
usecases seem to be best for this. 

i really dont want a quickstart for each chapter.
who is going to write this? the tutorial does not even cover the complete list of of topic for now. 

and mixing a few different things together in a nice usecase quickstart is really what we are missing.  
"here is a fully worked out example. we will not talk about every option and detail. for thta, pls look at the tutorial and the API docs"

**Comment by pat-s** [comment]
_From @schiffner on March 10, 2017 20:21_

The quick start section on the index page has been updated. (#85)
Other quick start pages are in progress. (#90, #86 )

**Comment by pat-s** [comment]
_From @SteveBronder on March 11, 2017 1:58_

> i really dont want a quickstart for each chapter.

I think a good compromise is, take all the code for the tutorial section and place it at the bottom. That way people can copy-paste and see how the whole thing works together.

**Comment by pat-s** [comment]
_From @SteveBronder on March 11, 2017 2:2_

> and mixing a few different things together in a nice usecase quickstart is really what we are missing.
"here is a fully worked out example. we will not talk about every option and detail. for thta, pls look at the tutorial and the API docs"

Bernd would this be sort of what you are looking for? I would have to add the code directly into the analysis and remove a few things that were relevant for that specific project.

It does imputation, tuning, stacking, and makes some pretty graphs for the output 

https://github.com/Stevo15025/hedgeable_ads

**Comment by pat-s** [comment]
_From @berndbischl on March 11, 2017 21:49_

> I think a good compromise is, take all the code for the tutorial section and place it at the bottom. That way people can copy-paste and see how the whole thing works together.

good idea. open issue for this?

**Comment by pat-s** [comment]
_From @berndbischl on March 12, 2017 2:44_

> Bernd would this be sort of what you are looking for? I would have to add the code directly into the analysis and remove a few things that were relevant for that specific project

that's a tad more complex than what i thought of, and i also think we should have simpler use cases. but yes, this is definitely cool. if included there should also be a at least a teaser blog post linking to it, or you put it in the tutorial and also the blog.

**Comment by pat-s** [comment]
_From @SteveBronder on March 12, 2017 3:32_

The blog is a much better place for something more compicated like that. I'll do this on Monday

**Comment by pat-s** [comment]
_From @berndbischl on March 12, 2017 3:36_

> the blog is a much better place for something more compicated like that. I'll do this on Monday

well the use cases should be in the tutorial too.
shall we just have a "use case page" in the tutorial with titles and then links to the blog posts?

**Comment by pat-s** [comment]
_From @SteveBronder on March 12, 2017 4:0_

> shall we just have a "use case page" in the tutorial with titles and then links to the blog posts?

Once we have quite a few serious use cases we should do this

**Comment by GegznaV** [comment]
For a "Quickstart", it would be nice if each function, in addition, to a description also had at least one example. Several examples would be even better.

**Comment by AlexEngelhardt** [comment]
What's your current status on the "Get Started" page?

I really like the "Quick Start" section. Maybe it makes sense to keep it, just to show an easy five-liner in mlr and whet people's appetite. I think it might be good to add a section "Use cases" between "Quick Start" and "Detailed Tutorials", they'd be a nice middle ground between these two sections. The use cases could then live on the blog or in separate Vignettes.

If you can use it, I'd gladly contribute [my mlr case study](http://www.alpha-epsilon.de/r/2018/07/13/a-data-science-case-study-with-r-and-mlr/). It's very basic from a technical side, but a bit more elaborate than the quickstart section. 

Would that make sense?

**Comment by jakob-r** [comment]
@AlexEngelhardt Nice write-up. I would probably introduce re-sample a bit earlier (e.g. `mlr::holdout()`). Because the manual example already let people assume you have to do it manually. IMHO: For a real quick start it's a bit too detailed.

For the rest of the status: I think we are still conflicted because they are so many approaches. So we have to live with not having a perfect for everybody quick start - I guess.

**Comment by AlexEngelhardt** [comment]
> So we have to live with not having a perfect for everybody quick start - I guess.

Probably, yes. But to me it sounded like some improvement is better than leaving it like it is now.

From your opinion, would it make more sense to expand the current quickstart section, or to add a more detailed case study below it? If the latter, I can shorten my article and add a `holdout()` to it. If the former, I can try expanding the existing quickstart.

**Comment by pat-s** [comment]
We won't put time into polishing the mlr-tutorial anymore, please have a look at {mlr3} and the [mlr3book](https://mlr3book.mlr-org.com).
