### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by mareichhoff** [mlr-org/mlr#2333]
Hello,

I tried several times to install the development version of mlr, but it always fails. Below you find the output of the installation process. Perhaps there is a package problem? 

```
> R> devtools::install_github("mlr-org/mlr")
> Downloading GitHub repo mlr-org/mlr@master
> from URL https://api.github.com/repos/mlr-org/mlr/zipball/master
> Installing mlr
> "C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef4364c5a77/mlr-org-mlr-d3b9c39" --library="C:/Program Files/R/R-3.5.0/library" --install-tests 
> 
> * installing *source* package 'mlr' ...
> ** libs
> 
> *** arch - i386
> c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
> c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c smote.c -o smote.o
> c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o mlr.dll tmp.def init.o smote.o -LC:/PROGRA~1/R/R-35~1.0/bin/i386 -lR
> installing to C:/Program Files/R/R-3.5.0/library/mlr/libs/i386
> 
> *** arch - x64
> c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
> c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c smote.c -o smote.o
> c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o mlr.dll tmp.def init.o smote.o -LC:/PROGRA~1/R/R-35~1.0/bin/x64 -lR
> installing to C:/Program Files/R/R-3.5.0/library/mlr/libs/x64
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** inst
> ** tests
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
>   converting help for package 'mlr'
>     finding HTML links ... fertig
>     Aggregation                             html  
>     BenchmarkResult                         html  
>     ConfusionMatrix                         html  
>     FailureModel                            html  
>     FeatSelControl                          html  
>     FeatSelResult                           html  
>     LearnerProperties                       html  
>     MeasureProperties                       html  
>     Prediction                              html  
>     RLearner                                html  
> Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef4364c5a77/mlr-org-mlr-d3b9c39/man/RLearner.Rd:58: file link 'ParamSet' in package 'ParamHelpers' does not exist and so has been treated as a topic
>     ResamplePrediction                      html  
>     ResampleResult                          html  
>     Task                                    html  
>     TaskDesc                                html  
>     TuneControl                             html  
>     finding level-2 HTML links ...
> Fehler: unbekanntes Eingabeformat
> * removing 'C:/Program Files/R/R-3.5.0/library/mlr'
> * restoring previous 'C:/Program Files/R/R-3.5.0/library/mlr'
> In R CMD INSTALL
> Installation failed: Command failed (1)
```

Session Info:

```
R> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.3.0     dplyr_0.7.5       purrr_0.2.5       readr_1.1.1       tidyr_0.8.1       tibble_1.4.2      ggplot2_2.2.1     tidyverse_1.2.1   data.table_1.11.4
[10] httr_1.3.1        stringr_1.3.1    

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.4 reshape2_1.4.3   haven_1.1.1      lattice_0.20-35  colorspace_1.3-2 rlang_0.2.1      pillar_1.2.3     foreign_0.8-70   glue_1.2.0       withr_2.1.2     
[11] modelr_0.1.2     readxl_1.1.0     bindrcpp_0.2.2   bindr_0.1.1      plyr_1.8.4       munsell_0.5.0    gtable_0.2.0     cellranger_1.1.0 rvest_0.3.2      devtools_1.13.5 
[21] psych_1.8.4      memoise_1.1.0    knitr_1.20       parallel_3.5.0   curl_3.2         broom_0.4.4      Rcpp_0.12.17     scales_0.5.0     jsonlite_1.5     mime_0.5        
[31] mnormt_1.5-5     hms_0.4.2        digest_0.6.15    stringi_1.2.3    grid_3.5.0       cli_1.0.0        tools_3.5.0      magrittr_1.5     lazyeval_0.2.1   crayon_1.3.4    
[41] pkgconfig_2.0.1  xml2_1.2.0       lubridate_1.7.4  assertthat_0.2.0 rstudioapi_0.7   R6_2.2.2         nlme_3.1-137     compiler_3.5.0   git2r_0.21.0    
```

**Comment by mareichhoff** [comment]
Just now I installed all github-development versions of BBmisc, Paramhelpers, parallelMap and tried again to install mlr via devtools::....., but I still got an error. 

`R> devtools::install_github("mlr-org/mlr")
Downloading GitHub repo mlr-org/mlr@master
from URL https://api.github.com/repos/mlr-org/mlr/zipball/master
Installing mlr
Downloading GitHub repo berndbischl/BBmisc@master
from URL https://api.github.com/repos/berndbischl/BBmisc/zipball/master
Installing BBmisc
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45" --library="C:/Program Files/R/R-3.5.0/library" --install-tests 

* installing *source* package 'BBmisc' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c getMaxColRowIndex.c -o getMaxColRowIndex.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c getMaxIndex.c -o getMaxIndex.o
In file included from getMaxIndex.c:2:0:
getMaxIndex.c: In function 'c_getMaxIndex':
getMaxIndex.c:73:32: warning: unused variable 'len_w' [-Wunused-variable]
     UNPACK_REAL_VECTOR(s_w, w, len_w);
                                ^
macros.h:10:19: note: in definition of macro 'UNPACK_REAL_VECTOR'
     const R_len_t N = length(S);
                   ^
getMaxIndex.c:68:27: warning: unused variable 'w' [-Wunused-variable]
   UNPACK_REAL_VECTOR(s_w, w, len_w);
                           ^
macros.h:9:13: note: in definition of macro 'UNPACK_REAL_VECTOR'
     double *D = REAL(S); \
             ^
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c itostr.c -o itostr.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c which_first.c -o which_first.o
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o BBmisc.dll tmp.def getMaxColRowIndex.o getMaxIndex.o init.o itostr.o which_first.o -LC:/PROGRA~1/R/R-35~1.0/bin/i386 -lR
installing to C:/Program Files/R/R-3.5.0/library/BBmisc/libs/i386

*** arch - x64
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c getMaxColRowIndex.c -o getMaxColRowIndex.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c getMaxIndex.c -o getMaxIndex.o
In file included from getMaxIndex.c:2:0:
getMaxIndex.c: In function 'c_getMaxIndex':
getMaxIndex.c:73:32: warning: unused variable 'len_w' [-Wunused-variable]
     UNPACK_REAL_VECTOR(s_w, w, len_w);
                                ^
macros.h:10:19: note: in definition of macro 'UNPACK_REAL_VECTOR'
     const R_len_t N = length(S);
                   ^
getMaxIndex.c:68:27: warning: unused variable 'w' [-Wunused-variable]
   UNPACK_REAL_VECTOR(s_w, w, len_w);
                           ^
macros.h:9:13: note: in definition of macro 'UNPACK_REAL_VECTOR'
     double *D = REAL(S); \
             ^
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c itostr.c -o itostr.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c which_first.c -o which_first.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o BBmisc.dll tmp.def getMaxColRowIndex.o getMaxIndex.o init.o itostr.o which_first.o -LC:/PROGRA~1/R/R-35~1.0/bin/x64 -lR
installing to C:/Program Files/R/R-3.5.0/library/BBmisc/libs/x64
** R
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'BBmisc'
    finding HTML links ... fertig
    addClasses                              html  
    argsAsNamedList                         html  
    asMatrixCols                            html  
    asQuoted                                html  
    binPack                                 html  
    btwn                                    html  
    cFactor                                 html  
    capitalizeStrings                       html  
    catf                                    html  
    checkArg                                html  
    checkListElementClass                   html  
    chunk                                   html  
    clipString                              html  
    coalesce                                html  
    collapse                                html  
    collapsef                               html  
    computeMode                             html  
    convertDataFrameCols                    html  
    convertInteger                          html  
    convertIntegers                         html  
    convertListOfRowsToDataFrame            html  
    convertMatrixType                       html  
    convertRowsToList                       html  
    convertToShortString                    html  
    dapply                                  html  
    deprecated                              html  
    do.call2                                html  
    dropNamed                               html  
    ensureVector                            html  
    explode                                 html  
    extractSubList                          html  
    filterNull                              html  
    getAttributeNames                       html  
    getClass1                               html  
    getFirst                                html  
    getMaxIndex                             html  
    getMaxIndexOfRows                       html  
    getOperatingSystem                      html  
    getRelativePath                         html  
    getUnixTime                             html  
    getUsedFactorLevels                     html  
    hasAttributes                           html  
    insert                                  html  
    is.error                                html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/is.error.Rd:12: file link 'tryCatch' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/is.error.Rd:13: file link 'simpleError' in package 'base' does not exist and so has been treated as a topic
    isDirectory                             html  
    isEmptyDirectory                        html  
    isExpensiveExampleOk                    html  
    isFALSE                                 html  
    isProperlyNamed                         html  
    isScalarNA                              html  
    isScalarValue                           html  
    isSubset                                html  
    isSuperset                              html  
    isValidName                             html  
    itostr                                  html  
    lib                                     html  
    load2                                   html  
    lsort                                   html  
    makeDataFrame                           html  
    makeFileCache                           html  
    makeProgressBar                         html  
    makeS3Obj                               html  
    makeSimpleFileLogger                    html  
    mapValues                               html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/mapValues.Rd:24: file link 'gsub' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/mapValues.Rd:27: file link 'gsub' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/mapValues.Rd:30: file link 'gsub' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/mapValues.Rd:40: file link 'gsub' in package 'base' does not exist and so has been treated as a topic
    messagef                                html  
    namedList                               html  
    names2                                  html  
    nin                                     html  
    normalize                               html  
    optimizeSubInts                         html  
    pause                                   html  
    printHead                               html  
    printStrToChar                          html  
    printToChar                             html  
    rangeVal                                html  
    requirePackages                         html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/requirePackages.Rd:13: file link 'require' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/requirePackages.Rd:14: file link 'requireNamespace' in package 'base' does not exist and so has been treated as a topic
    rowLapply                               html  
    save2                                   html  
    seq_row                                 html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/seq_row.Rd:21: file link 'seq_len' in package 'base' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/seq_row.Rd:15: file link 'ncol' in package 'base' does not exist and so has been treated as a topic
    setAttribute                            html  
    setClasses                              html  
    setRowNames                             html  
    setValue                                html  
    sortByCol                               html  
    splitPath                               html  
    splitTime                               html  
    stopf                                   html  
    strrepeat                               html  
    suppressAll                             html  
    symdiff                                 html  
    system3                                 html  
    toRangeStr                              html  
    vlapply                                 html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef45472e3f/berndbischl-BBmisc-a5a4e45/man/vlapply.Rd:33: file link 'vapply' in package 'base' does not exist and so has been treated as a topic
    warningf                                html  
    which.first                             html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (BBmisc)
In R CMD INSTALL
Downloading GitHub repo berndbischl/parallelMap@master
from URL https://api.github.com/repos/berndbischl/parallelMap/zipball/master
Installing parallelMap
Downloading GitHub repo berndbischl/BBmisc@master
from URL https://api.github.com/repos/berndbischl/BBmisc/zipball/master
Skipping BBmisc, it is already being installed.
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef432228c/berndbischl-parallelMap-bda3a81" --library="C:/Program Files/R/R-3.5.0/library" --install-tests 

* installing *source* package 'parallelMap' ...
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'parallelMap'
    finding HTML links ... fertig
    parallelExport                          html  
    parallelGetOptions                      html  
    parallelGetRegisteredLevels             html  
    parallelLapply                          html  
    parallelLibrary                         html  
    parallelMap                             html  
    parallelRegisterLevels                  html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef432228c/berndbischl-parallelMap-bda3a81/man/parallelRegisterLevels.Rd:23: file link '.onLoad' in package 'base' does not exist and so has been treated as a topic
    parallelSource                          html  
    parallelStart                           html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef432228c/berndbischl-parallelMap-bda3a81/man/parallelStart.Rd:104: file link 'makePSOCKcluster' in package 'parallel' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef432228c/berndbischl-parallelMap-bda3a81/man/parallelStart.Rd:106: file link 'mcmapply' in package 'parallel' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef432228c/berndbischl-parallelMap-bda3a81/man/parallelStart.Rd:128: file link 'mclapply' in package 'parallel' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef432228c/berndbischl-parallelMap-bda3a81/man/parallelStart.Rd:129: file link 'clusterMap' in package 'parallel' does not exist and so has been treated as a topic
    parallelStop                            html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef432228c/berndbischl-parallelMap-bda3a81/man/parallelStop.Rd:16: file link 'stopCluster' in package 'parallel' does not exist and so has been treated as a topic
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (parallelMap)
In R CMD INSTALL
Downloading GitHub repo berndbischl/ParamHelpers@master
from URL https://api.github.com/repos/berndbischl/ParamHelpers/zipball/master
Installing ParamHelpers
Downloading GitHub repo berndbischl/BBmisc@master
from URL https://api.github.com/repos/berndbischl/BBmisc/zipball/master
Skipping BBmisc, it is already being installed.
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef4cd8641c/berndbischl-ParamHelpers-986c580" --library="C:/Program Files/R/R-3.5.0/library" --install-tests 

* installing *source* package 'ParamHelpers' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c c_dfRowsToList.c -o c_dfRowsToList.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c c_generateDesign.c -o c_generateDesign.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o ParamHelpers.dll tmp.def c_dfRowsToList.o c_generateDesign.o init.o -LC:/PROGRA~1/R/R-35~1.0/bin/i386 -lR
installing to C:/Program Files/R/R-3.5.0/library/ParamHelpers/libs/i386

*** arch - x64
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c c_dfRowsToList.c -o c_dfRowsToList.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c c_generateDesign.c -o c_generateDesign.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o ParamHelpers.dll tmp.def c_dfRowsToList.o c_generateDesign.o init.o -LC:/PROGRA~1/R/R-35~1.0/bin/x64 -lR
installing to C:/Program Files/R/R-3.5.0/library/ParamHelpers/libs/x64
** R
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'ParamHelpers'
    finding HTML links ... fertig
    LearnerParam                            html  
    OptPath                                 html  
    Param                                   html  
    addOptPathEl                            html  
    as.data.frame.OptPathDF                 html  
    checkParamSet                           html  
    convertParamSetToIrace                  html  
    dfRowsToList                            html  
    discreteNameToValue                     html  
    discreteValueToName                     html  
    dropParams                              html  
    evaluateParamExpressions                html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef4cd8641c/berndbischl-ParamHelpers-986c580/man/evaluateParamExpressions.Rd:10: file link 'ParamSet' in package 'ParamHelpers' does not exist and so has been treated as a topic
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef4cd8641c/berndbischl-ParamHelpers-986c580/man/evaluateParamExpressions.Rd:21: file link 'ParamSet' in package 'ParamHelpers' does not exist and so has been treated as a topic
    filterParams                            html  
    generateDesign                          html  
    generateDesignOfDefaults                html  
    generateGridDesign                      html  
    generateRandomDesign                    html  
    getDefaults                             html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef4cd8641c/berndbischl-ParamHelpers-986c580/man/getDefaults.Rd:10: file link 'ParamSet' in package 'ParamHelpers' does not exist and so has been treated as a topic
    getLower                                html  
    getOptPathBestIndex                     html  
    getOptPathCol                           html  
    getOptPathCols                          html  
    getOptPathDOB                           html  
    getOptPathEOL                           html  
    getOptPathEl                            html  
    getOptPathErrorMessages                 html  
    getOptPathExecTimes                     html  
    getOptPathLength                        html  
    getOptPathParetoFront                   html  
    getOptPathX                             html  
    getOptPathY                             html  
    getParamIds                             html  
    getParamLengths                         html  
    getParamNr                              html  
    getParamSet                             html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef4cd8641c/berndbischl-ParamHelpers-986c580/man/getParamSet.Rd:14: file link 'ParamSet' in package 'ParamHelpers' does not exist and so has been treated as a topic
    getParamTypeCounts                      html  
    getParamTypes                           html  
    getRequirements                         html  
    getTypeStrings                          html  
    hasExpression                           html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef4cd8641c/berndbischl-ParamHelpers-986c580/man/hasExpression.Rd:10: file link 'ParamSet' in package 'ParamHelpers' does not exist and so has been treated as a topic
    hasFiniteBoxConstraints                 html  
    hasForbidden                            html  
    hasRequires                             html  
    hasTrafo                                html  
    hasType                                 html  
    isEmpty                                 html  
    isFeasible                              html  
    isForbidden                             html  
    isRequiresOk                            html  
    isSpecialValue                          html  
    isType                                  html  
    isTypeString                            html  
    isVector                                html  
    makeParamSet                            html  
    paramValueToString                      html  
    plotEAF                                 html  
    plotOptPath                             html  
    plotYTraces                             html  
    removeMissingValues                     html  
    renderOptPathPlot                       html  
    renderYTraces                           html  
    repairPoint                             html  
    sampleValue                             html  
    sampleValues                            html  
    setOptPathElDOB                         html  
    setOptPathElEOL                         html  
    setValueCNames                          html  
    trafoOptPath                            html  
    trafoValue                              html  
    updateParVals                           html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (ParamHelpers)
In R CMD INSTALL
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef41c70275d/mlr-org-mlr-d3b9c39" --library="C:/Program Files/R/R-3.5.0/library" --install-tests 

* installing *source* package 'mlr' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O3 -Wall  -std=gnu99 -mtune=generic -c smote.c -o smote.o
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o mlr.dll tmp.def init.o smote.o -LC:/PROGRA~1/R/R-35~1.0/bin/i386 -lR
installing to C:/Program Files/R/R-3.5.0/library/mlr/libs/i386

*** arch - x64
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c smote.c -o smote.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o mlr.dll tmp.def init.o smote.o -LC:/PROGRA~1/R/R-35~1.0/bin/x64 -lR
installing to C:/Program Files/R/R-3.5.0/library/mlr/libs/x64
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'mlr'
    finding HTML links ... fertig
    Aggregation                             html  
    BenchmarkResult                         html  
    ConfusionMatrix                         html  
    FailureModel                            html  
    FeatSelControl                          html  
    FeatSelResult                           html  
    LearnerProperties                       html  
    MeasureProperties                       html  
    Prediction                              html  
    RLearner                                html  
Rd warning: C:/Users/meichho/AppData/Local/Temp/RtmpamtcXe/devtools2ef41c70275d/mlr-org-mlr-d3b9c39/man/RLearner.Rd:58: file link 'ParamSet' in package 'ParamHelpers' does not exist and so has been treated as a topic
    ResamplePrediction                      html  
    ResampleResult                          html  
    Task                                    html  
    TaskDesc                                html  
    TuneControl                             html  
    finding level-2 HTML links ...
Fehler: unbekanntes Eingabeformat
* removing 'C:/Program Files/R/R-3.5.0/library/mlr'
* restoring previous 'C:/Program Files/R/R-3.5.0/library/mlr'
In R CMD INSTALL
Installation failed: Command failed (1)`

**Comment by larskotthoff** [comment]
Maybe an encoding problem? Is your R and system set up to use UTF8?

**Comment by mareichhoff** [comment]
No, in R - studio I have set "UTF-8" as global settings. But as I see now on the site: "build: error". So it may has to do with my problem. Let's wait and see...

**Comment by berndbischl** [comment]
please do not install devel builds from github, but use CRAN releases
