### ISSUE TITLE
New favicon for tutorial (based on new logo)

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2347]
The favicon of the tutorial still has the old logo.

I created two versions (black and blue).
The coloring as it appears in the tutorial is not practical because most browsers have grey tabs by default. 
We really need a dark background color and a light font color.
The dots are almost not visible at this size. Should we remove them from the favicon and center "mlr"?
Please vote and comment!

![favicon-preview](https://user-images.githubusercontent.com/8430564/42118654-31ea61f8-7c05-11e8-855f-70606b1109de.png)

[![](https://api.gh-polls.com/poll/01CH6Y28TDXJJ8NF31MHJS295V/blue)](https://api.gh-polls.com/poll/01CH6Y28TDXJJ8NF31MHJS295V/blue/vote)
[![](https://api.gh-polls.com/poll/01CH6Y28TDXJJ8NF31MHJS295V/black)](https://api.gh-polls.com/poll/01CH6Y28TDXJJ8NF31MHJS295V/black/vote)
[![](https://api.gh-polls.com/poll/01CH6Y28TDXJJ8NF31MHJS295V/I%20do%20not%20like%20both)](https://api.gh-polls.com/poll/01CH6Y28TDXJJ8NF31MHJS295V/I%20do%20not%20like%20both/vote)

**Comment by berndbischl** [comment]
i am not good at this :)
i kinda like the black one better. pls choose and merge
