### ISSUE TITLE
control which class is over- or undersampled

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#235]
Currently, we can undersample the larger or oversample the smaller class.
This is fine as long as we aim to make the class frequencies more equal.
Sometimes, e.g., in cost-sensitive classification, one may want to make the classification problem more imbalanced.

**Comment by berndbischl** [comment]
@schiffner 
Julia, this is in master now.
Would you please check whether you think it is OK now? 
Then you can close please

**Comment by schiffner** [comment]
@florianfendt: Thank you very much for doing this.

I had a short look at code and docs. And I extended the examples on the tutorial page on cost-sensitive classification. Everything looks good and works fine, so I will close here.

**Comment by berndbischl** [comment]
perfect! thx
