### ISSUE TITLE
batchtools in docs

### ISSUE THREAD

**Issue by nick-youngblut** [mlr-org/mlr#2352]
This is a minor thing, but the [mlr parallelization docs](https://mlr-org.github.io/mlr-tutorial/release/html/parallelization/index.html?) state that BatchJobs can be used, but it appears that BatchTools, the successor to BatchJobs, is being used; at least, [for some of the code](https://github.com/mlr-org/mlr/blob/master/R/batchmark.R). I was a bit confused by this.

**Comment by jakob-r** [comment]
Well. both can be used but you are right. we probably should rewrite everything to only mention batchtools to not confuse people

**Comment by berndbischl** [comment]
agreed

**Comment by pat-s** [comment]
Hm, we should really redirect all sub-pages of the old tutorial, not just ./index.html. 
People still refer to the deprecated tutorial which is not good in the long run (updates etc). 

(In this case the page referred to in the issue is still the same as the current one.)

**Comment by pat-s** [comment]
FYI: I've now invalidated all old tutorial pages besides the main one. This still redirects to the new tutorial.
