### ISSUE TITLE
Test error after PR 2287

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2358]
The following test currently errors

https://github.com/mlr-org/mlr/blob/9254615d0e05f7729960daa9164815626572ef2b/tests/testthat/test_learners_all_classif.R#L64

```
Error in makeRegrTask("oneCol", data.frame(x = 1:10, y = as.factor(rep(c("a",  : 
  Assertion on 'y' failed: Must be of type 'numeric', not 'factor'.
```

@jakob-r Introduced by https://github.com/mlr-org/mlr/pull/2287

Factor response for a regr.task? I assume a typo; just make it a classif.task?

**Comment by jakob-r** [comment]
Will fix.
