### ISSUE TITLE
pass tuneWrapper an additional ResampleIsntance to detect overfitting

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#236]
When running the following example we will get two different end results. One is the best found performance on the inner cross validation and the other is the final performance on the outer cross validation.

``` r
ps = makeParamSet(
  makeNumericParam("C", lower = -5, upper = 2, trafo = function(x) 2^x),
  makeNumericParam("sigma", lower = -3, upper = 3, trafo = function(x) 2^x))
ctrl = makeTuneControlRandom(maxit = 30)
inner = makeResampleDesc("Holdout")
outer = makeResampleDesc("CV", iters = 2)
lrn = makeTuneWrapper("classif.ksvm", inner, par.set = ps, control = ctrl, show.info = FALSE)
r = resample(lrn, iris.task, resampling = outer, extract = getTuneResult, show.info = FALSE)

extractSubList(r$extract, "y")
r$measures.test
```

If you look at the `opt.path` you will also see always only the "inner performance". It would be nice if there was a way to calculate and add the outer performance reached in every tuning step to detect overfitting etc.
Is that too much or a nice idea?

**Comment by berndbischl** [comment]
So that is a question already about tuneParams?

For every point x, x is evaled on the (normal) test sets T1 (from normal resampling).
This is of course what is then fed back to the tuner, so it can optimize.

Now, you also want to eval it on extra, user defined test sets T2. This info is just for a trace and later analysis, and unused in the tuner?

This is some kind of a standard technique, yes, to look for oversearching / overfitting behavior. Se we could support it I guess.

**Comment by schiffner** [comment]
+1
It's odd that you can do nested resampling for feature selection and hyperparameter tuning combined with threshold tuning, respectively, but not for threshold tuning only (at least if you rule out strange solutions like using tuneParams with a ParamSet of size 1 and tune.threshold = TRUE in the TuneControl object).

**Comment by jakob-r** [comment]
@berndbischl This is exactly what I mean. I think it would be really handy!
@schiffner I don't see the connection to the issue so much. But I agree that the the momentary implementation of `tune.threshold` has it's drawbacks and we should do it as a wrapper if possible. I don't remember why we didn't. However, it's definitely a new issue.

**Comment by jakob-r** [comment]
Work on this topic is now in https://github.com/jakob-r/mlrOverfit
