### ISSUE TITLE
we need to reenable travis with irace 3.0

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#2376]
currently irace 3.0 is broken with mlr, it is a bug in irace
i am already talking to the maintainer of irace

hence @ja-thomas made sure that irace 2.4 is installed in our travis setup #2374 
this needs to be removed

**Comment by pat-s** [comment]
Does 5bd9e415cac2f6dbe0804a34b5e303ed757c9f54 and b8719ec64b4ce07c8c0df91266a1e78b13587d9e also work with `irace` 3.0, i.e. can we use the CRAN release again?

**Comment by berndbischl** [comment]
i think so

**Comment by pat-s** [comment]
Ok, I removed the version restriction in #2370 so it gets fixed once we merge it.
