### ISSUE TITLE
Wrong links in readme

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#2399]
Two links in the readme text (see below) do not work: 

Some parts of the package were created as part of other publications. If you use these parts, please cite the relevant work appropriately. An overview of all mlr related publications can be found here.

A list of publications that cite mlr can be found in the wiki.

**Comment by GegznaV** [comment]
It seems that in your message there should be some links, but they are missing.

**Comment by pat-s** [comment]
Solved in b224836ee1bb97392097cb9a875ad4dc68230087. Thanks!
