### ISSUE TITLE
Link to cheatsheat on mlr-org is broken - 404 page not found

### ISSUE THREAD

**Issue by harlecin** [mlr-org/mlr#2400]
On the mlr-homepage on the right hand side in the links-section the link for cheatsheets is broken:

See screenshot (highlighted in yellow):

![broken-link-homepage](https://user-images.githubusercontent.com/11078385/43190835-406579a8-8ffa-11e8-8385-84134d79bd39.PNG)

**Comment by pat-s** [comment]
Thanks! Solved in 3ec3950e69a82e586f8cd7e02daf8d34b1026e45.
