### ISSUE TITLE
generatePartialDependenceData does not work for xgboost

### ISSUE THREAD

**Issue by leoKampfer** [mlr-org/mlr#2408]
I tried to reproduce the example of @giuseppec posted here [https://github.com/dmlc/xgboost/issues/486](url):
```r
library(mlr)
library(xgboost)
# define learner
lrn = makeLearner("classif.xgboost", predict.type = "prob", nrounds = 100)

# train model on bh.task
fit = train(lrn, sonar.task)

# get importance
imp = xgb.importance(feature_names = fit$features, model = fit$learner.model)

# make partial dependence plot for most important feature
pd = generatePartialDependenceData(fit, sonar.task, imp$Feature[1])
plotPartialDependence(pd)
```

Unfortuantely, I received an error message after doing `generatePartialDependenceData()`:
```r
## > pd = generatePartialDependenceData(fit, sonar.task, imp$Feature[1])
## Error in predict.xgb.Booster(m, newdata = data.matrix(.newdata), ...) : 
##  Feature names stored in `object` and `newdata` are different!
```

Have anyone an idea how to solve this problem or how to work around?

**Comment by pat-s** [comment]
I recently faced the same error message with an `xgboost` learner but with a different function (can't remember right now). We should figure out what happens here.

**Comment by leoKampfer** [comment]
Thanks for the help. Unfortunately, I do not fully understand your proposed solution:
You suggest to transform the task into a dataframe with column names from the trained model? 

Furthermore, I checked if there is a discrepancy between the assigned column names or of their order - but I can't find any differences.

**Comment by pat-s** [comment]
> Thanks for the help. Unfortunately, I do not fully understand your proposed solution:
> You suggest to transform the task into a dataframe with column names from the trained model?

No, just to check if the order of `fit.features` is the same as the one in `fit.learner.model$feature.names` and in `task$env$data`.

If the order is exactly the same, there might be some shuffling going on in `generatePartialDependenceData()` maybe? Just a thought though. 

I am not completely sure if my fix also applies for your problem even though we have the same error message. The `xgboost` implementation is really bad here.
