### ISSUE TITLE
ROC plot() coercing type 'S4' to vector of type 'double'

### ISSUE THREAD

**Issue by balkon16** [mlr-org/mlr#2415]
Hello, 

I'm enjoying learning how the `mlr` package works. While trying to replicate an example from a [tutorial article](https://mlr-org.github.io/mlr/articles/roc_analysis.html) I experienced an error which reads as follows:

`Error in as.double(y) : cannot coerce type 'S4' to vector of type 'double'`

As I observed in my [stackoverflow post](https://stackoverflow.com/questions/51828525/r-oop-change-the-name-of-a-slot) the reason may be the incorrect name of the slot.

**Comment by pat-s** [comment]
Looks like your question was answered on SO.
