### ISSUE TITLE
Error when predicting new dataset with single factor values

### ISSUE THREAD

**Issue by mb1069** [mlr-org/mlr#2422]
Hi,
I'm having some issue predicting new values from unseen data; this data comes from a single source, and therefore many of the factor-type columns have a single value in this new dataset. However, the original dataset has no constant columns.

When running predict, I am getting the following error:
```R
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
```
A minimum example can be found with data here:
[min_example.tar.gz](https://github.com/mlr-org/mlr/files/2315420/min_example.tar.gz)

**Comment by larskotthoff** [comment]
It sounds to me like there isn't actually a bug here -- there's only so much you can do if there's only one factor level. What would you want to happen?

**Comment by mb1069** [comment]
there is a single factor in the new data, but i expect this to influence
the prediction relative to all the training data. why does the unseen data
need to vary in all variables?

**Comment by larskotthoff** [comment]
The problem isn't with the prediction, it's with the dummy features wrapper, which assumes that factors have at least 2 levels (otherwise a dummy encoding doesn't make sense).

**Comment by mb1069** [comment]
But why is it defining the dummy features based on test data, as this would create new input variables? Shouldn't it instead apply the transformations created from the training data?

**Comment by mb1069** [comment]
Would you have any suggestions for a workaround, pending a bugfix?

**Comment by larskotthoff** [comment]
You could create the dummy features in a separate step instead of in a wrapper, or make sure that all levels are always present.
