### ISSUE TITLE
Text Modelling question, and combination of models generally

### ISSUE THREAD

**Issue by mlearner-jl** [mlr-org/mlr#2427]
I would like to achieve the following:

- On a dataset containing multiple data types (numeric, categorical, text)
- I would like to take the text features, convert to n-grams or tf-idf say, and train this on a model
- Take the output of this model (models if multiple text features exist) and use that as input for the "main model" that is trained on the "main dataset"

e.g.
![untitled diagram](https://user-images.githubusercontent.com/32354881/45037341-a7947300-b056-11e8-9afa-e572adee7ea8.png)

Is this possible in mlr (obviously it could be done manually)?

More generally, is it possible to take a dataset, select subsets (potentially overlapping) of features, and train them on different models and combine them in various ways either with stacking (output of all models weighted), or with the outputs of some models becoming the inputs of others along with other input data etc.?

**Comment by larskotthoff** [comment]
Yes, this is possible -- parts of what you're describing sounds like a random forest, but you can also do that manually with ensembles and stacking.

**Comment by mlearner-jl** [comment]
Thank you.
So it is possible to replicate something like my diagram, including training/tuning or is this done after the fact?
What functions in MLR achieve this, is everything achievable with makeStackedLearner, I cannot see a function that relates to ensembles?

**Comment by larskotthoff** [comment]
You can create an ensemble with the bagging wrapper: https://mlr-org.github.io/mlr/articles/wrapper.html

**Comment by mb706** [comment]
>Take the output of this model (models if multiple text features exist) and use that as input for the "main model" that is trained on the "main dataset"

What kind of "output" does your text model produce that should be given to the main model? This sounds like preprocessing and therefore a good use case for [mlrCPO](/mlr-org/mlrCPO); you can try to create [custom CPOs](https://rawgit.com/mlr-org/mlrCPO/master/inst/doc/a_4_custom_CPOs.html) that do the steps you want. If you can be more specific about the operations you need to perform I can try to help you implementing this.

**Comment by berndbischl** [comment]
> Is this possible in mlr (obviously it could be done manually)?

it is not supported in an extremely simple manner. you could code what you just descibed, and build upon many of mlr's function. but it is not going to be 3 simple lines.

**Comment by berndbischl** [comment]
sorry, reopening this. we can try to help a bit here, like i said, there will not be a simple answer i guess, if you dont put in some of your own work

**Comment by SteveBronder** [comment]
I'm mlr you would have to have both data sources in one table no? Then you could

1. use a feature select CPO on the text learner train it on the text data.
2. Put that learner in a stacked learner that uses the underlying data. The stacked learner would also have a feature select cpo to choose all non text columns.

I think that would work? Though if your text model has a different target than the stacked learner idk if that would work. You'd want a custom cpo at that point
