### ISSUE TITLE
getFeatureImportance does not support h2o learners

### ISSUE THREAD

**Issue by markusdumke** [mlr-org/mlr#2433]
I can not extract features importances from h2o learners, e.g. `classif.h2o.randomForest` or `classif.h2o.glm` using `mlr::getFeatureImportance`. 

But h2o has the function `h2o.varimp`  for this. So I have to do `getLearnerModel(trained.learner) %>% h2o.varimp()`. Is it possible to include this into `getFeatureImportance` or is there any reason why it is not included?

**Comment by larskotthoff** [comment]
It sounds like this can certainly be included; the only reason it isn't is that nobody has implemented that yet :)

If you want to implement it and submit a pull request. I'm happy to have a look at it and help.

**Comment by markusdumke** [comment]
Ok. I will give it a try :)
