### ISSUE TITLE
Seeding is not respected in tutorial

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2435]
We get frequent commits to `master` changing digits in some tutorial sections.
This clutters the commit history. We should fix this ASAP.

We have a seed in the problematic files but it seems to get ignored by `pkgdown`.

**Comment by pat-s** [comment]
This is really annoying since one has to rebase the `docs/` from `master` all the time because they change in each branch deployment. Unfortunately I cannot figure out why the seeding is not respected :disappointed:

**Comment by pat-s** [comment]
So the problem persists. I currently see two solutions:

1. Go back serving the docs from `gh-pages` branch. Disadvantage: No PR preview of docs.
2. Don't push the docs on Travis. Always commit the changed files in `docs/` in the PR. 

Method 2) has the advantage that `master` is not cluttered anymore with Tutorial commits by Travis. Also usually only few (usually one) files within `docs/` need to be pushed to the current PR. 
We would still build the tutorial on Travis but disable the pushing temporary. 
Also Method 2) would only require to comment one line in the current CI setup.

**Comment by berndbischl** [comment]
this cannot be so hard.
cant you simply put a set.seed(123) in each tutorial page at the beginning?

**Comment by pat-s** [comment]
> cant you simply put a set.seed(123) in each tutorial page at the beginning?

We have this and I've tried multiple seed kinds as well. The pkgdown guys also don't know why we get different numbers in every run. Would be a workaround until the problem is solved.

**Comment by pat-s** [comment]
Also its not only about the changing numbers. Also all .png files are marked as changed after a complete `pkgdown::build_site()` run. So until this is solved I would really vote to use method 2) for now.

**Comment by berndbischl** [comment]
how can it be a workaround if it does not work?

**Comment by berndbischl** [comment]
so we HAVE a seed in the code part of a page. and that is not respected? i run it twice locally and get differents reults in the rendered out docs?

**Comment by pat-s** [comment]
Spoke to @jakob-r 

We agreed on the following for now:

- disable pushing the tutorial in all branches
- build the tutorial locally (only the parts that have changed) and push to the PR OR trigger a travis build with a custom commit message that also deploys the tutorial into the branch
- the tutorial is still build in every CI build, just no pushed

By doing so we avoid all the cluttering commits and still have PR previews of the tutorial. Once the PR gets merged, the tutorial is up-to-date.

@berndbischl 
Are you ok with this?

**Comment by berndbischl** [comment]
sounds good and thx also @jakob-r (and to you patrick, of course)

**Comment by pat-s** [comment]
If we commit files in `docs/` manually, we get merge conflicts on Github. Meh. 
These conflicts can only solved by hand in the Github editor currently. 
This sucks. Have to think about a different method to solve this in the long run if the seeding issue persists.

**Comment by jakob-r** [comment]
I don't understand. Where does a merge happen?

**Comment by pat-s** [comment]
1. I locally built the feature-sel page
1. I manually commited `docs/feature-sel.html` 
1. I got a merge conflict on Github between the master version and the PR version. Probably because there have been too many changes in the file
1. I needed to manually resolve the conflict in the Github editor

This is really annoying and we have to see if we can find a way around it. Even though we may only need to it once in every PR and it may only appear if the changes are major (whole sections for example). 

Let's see. We just do it like this for now and see what will happen.

**Comment by jakob-r** [comment]
but why has the master version of `docs/feature-sel.html` changed if we don't do any auto deployment anymore?

**Comment by pat-s** [comment]
It hasn't changed. I searched why this kind of problem appears in a simple PR file change and found that it can happen if there are too many changes in a single file.

**Comment by berndbischl** [comment]
isn the html a pure output file? so do conflicts even matter? just overwrite it?

**Comment by pat-s** [comment]
Yes. And I would like to do this. But there is no option to tell Github to do so. At least I searched for it and couldn't find one. 

You could do it locally via the "take always THEIRS" with THEIRS being the new file in case of conflicts. But this is not possible on GH.

**Comment by pat-s** [comment]
FYI: Talked to Bernd. We leave it in its current state, meaning no auto-deployment of travis to avoid cluttering commits and subsequently manual commits of changed tutorial files in PRs.

**Comment by pat-s** [comment]
I have a (robust) fix. Though I have to edit every file by hand. Will take some time. Stay tuned.

With that we can enable the auto-deployment again.

**Comment by pat-s** [comment]
Fixed in 0b121ccf9642bbc6d67858719cbb4d4eb93a5f2d.
