### ISSUE TITLE
mlr: Bigfix for generatePartialDependenceData

### ISSUE THREAD

**Issue by SebastianHapp** [mlr-org/mlr#2439]
Dear all,

I encountered the following issue using the generatePartialDependenceData.
It seems to me that classification problems work, whereas regression problems do not.

Pls find below the reproducible example generated from the iris dataset.

min example for the bug of generatePartialDependenceData
classification toy example with iris dataset
```r
lrn = makeLearner("classif.rpart", predict.type = "prob")
fit = train(lrn, iris.task)
pd = generatePartialDependenceData(fit, iris.task, "Petal.Width")
plotPartialDependence(pd, data = getTaskData(iris.task))
```
regression toy example with iris dataset
```r
t_data <- as.data.frame(as.data.table(lapply(iris, function(x){as.numeric(x)})))
tsk <- makeRegrTask(data = t_data, target = "Sepal.Length")
lrn <- makeLearner("regr.xgboost", predict.type = "response", eta = 0.1,
max_depth = 8, min_child_weight = 20,
subsample = 0.75, colsample_bytree = 0.75,
nrounds = 2, nthread = cl_n, objective = "reg:linear",
eval_metric = "rmse")
fit = train(lrn, tsk)
pd = generatePartialDependenceData(fit, tsk, "Petal.Width")
plotPartialDependence(pd, data = getTaskData(iris.task))
```
The problem is that in generatePartialDependenceData the function mmpf:::makeDesign reorders columns and hence xgboost fails to predict.

 
The solution for this issue is to do the following manipulation:

```r
library(R.utils)
makeDesign2 <- mmpf:::makeDesign;
mymakeDesign <- function(data, vars, n=n, uniform = TRUE, points, int.points) {makeDesign2(data, vars, n, uniform = uniform, points, int.points)[colnames(data)]};
reassignInPackage("makeDesign", pkgName="mmpf", mymakeDesign);
```
Pls implement this bugfix in mlr.

Thanks in advance,
Sebastian

**Comment by pat-s** [comment]
Hi @SebastianHapp,

thanks for contributing.

So the issue is caused by the fact that `xgboost` cannot handle reordered variable names (this is known and we cannot do anything about this) and `mmpf::makeDesign()` which is an external function that we do not control.

The latter probably functions rights for all algorithms besides `xgboost`? So the bug report should go to one of these packages. If the `mmpf` authors are nice they might account for the problem even though they might argue the same as I do just right now (that its an issue caused only by `xgboost`).

In the end, we are player 3 in the chain and its not effective to start accounting for it at level 3. 

PS: Next time, please spend 1 min more and format your post so its better readable. Thanks!

**Comment by berndbischl** [comment]
Why don't we simply depreciate and delegate to iml? We suggest to use that anyway?

**Comment by zmjones** [comment]
i know i sorta fell off the map but if i'd noticed this i'd have fixed it sooner. makeDesign now returns columns in the original order given to it. 

cran is apparently on vacation? anybody know what to do there?

**Comment by pat-s** [comment]
@zmjones 	@SebastianHapp 	is this issue now solved?

**Comment by GatesDupont** [comment]
I'm still having a problem with `generatePartialDependenceData()` for XGBoost and randomForest:

```
Error in setcolorder(out, c(names(out)[grepl(paste(target, "preds", sep = "|"),  : 
  neworder contains duplicates
```

I tried the solution by @SebastianHapp, but got this error:

```
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?
```
This seems like it's related to the same issue in this thread. Any ideas or updates? Thanks!

**Comment by pat-s** [comment]
I do not see a direct relation - the error message did not appear in this issue before.

Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

**Comment by pat-s** [comment]
Closing here due to inactivity and a upstream fix in _mmpf_ which possibly solves the problem.

**Comment by albersonmiranda** [comment]
Just tried in a few learners and got same colorder error

**Comment by pat-s** [comment]
Thanks.

**Comment by pat-s** [comment]
The code from the OP runs fine for me:

``` r
library(mlr)
#> Loading required package: ParamHelpers
#> Warning message: 'mlr' is in 'maintenance-only' mode since July 2019.
#> Future development will only happen in 'mlr3'
#> (<https://mlr3.mlr-org.com>). Due to the focus on 'mlr3' there might be
#> uncaught bugs meanwhile in {mlr} - please consider switching.
library(data.table)

t_data <- as.data.frame(as.data.table(lapply(iris, function(x) {
  as.numeric(x)
})))
tsk <- makeRegrTask(data = t_data, target = "Sepal.Length")
lrn <- makeLearner("regr.xgboost",
  predict.type = "response", eta = 0.1,
  max_depth = 8, min_child_weight = 20,
  subsample = 0.75, colsample_bytree = 0.75,
  nrounds = 2, nthread = 1, objective = "reg:squarederror",
  eval_metric = "rmse"
)
fit <- train(lrn, tsk)
pd <- generatePartialDependenceData(fit, tsk, "Petal.Width")
#> Loading required package: mmpf
plotPartialDependence(pd, data = getTaskData(iris.task))
```

![](https://i.imgur.com/hNlEhI1.png)

<sup>Created on 2021-02-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

It might be that the issues from other people posted in this thread might be triggered from other sources. We need reprexes to investigate further.
