### ISSUE TITLE
measures usage question

### ISSUE THREAD

**Issue by amueller** [mlr-org/mlr#2446]
Hey.
I'd like to use your multiclass auc methods to compare against.
Is there a way to call the measures if I already have the probabilities?

Also: do your measures require probabilities or do they also work on arbitrary continuous scores?

Thanks!
Andy

**Comment by ja-thomas** [comment]
Hi,

for most measures, e.g. `multiclass.au1p` is a function called `measureAU1P` which is called internally.
These function are called directly on probabilities and labels and don't need a `task` and `model` object.

They are not written to handle on scores, but by calling these function directly you're bypassing the checks, so some might work with scores nonetheless.

**Comment by PhilippPro** [comment]
Our minimum for this measures is 0.5, if it is lower (e.g. 0.3) we take the value 1-0.3. I am not completely happy with this, but take this in mind when you are testing.

**Comment by pat-s** [comment]
@amueller 	Closing here since the question seems to be answered.

**Comment by amueller** [comment]
sure, I didn't have time to follow up. I need to run it. I'll come back if I have issues :)

**Comment by berndbischl** [comment]
please do so. we are also working on making that even more open
