### ISSUE TITLE
parallelize xgboost after 'freading' large amount of data

### ISSUE THREAD

**Issue by lumatt** [mlr-org/mlr#2453]
Hello,

I have very weird problem. The code below works like a charm (meaning that it utilizes all 64 cores available on my machine)

```r
require(dplyr)
require(mlr)

# create upsampled version of iris data

set.seed(12345)

iris_edit <- do.call("cbind", lapply(1:598, function(i){
  iris %>% 
  dplyr::select(1:4) %>% 
  setNames(paste0("X", seq(4*i - 3, 4*i)))
})) %>% 
  tibble::as_tibble(.) %>% 
  dplyr::bind_cols(iris %>% dplyr::select(Species)) %>%
  dplyr::sample_n(114116, replace = TRUE) %>% 
  dplyr::filter(Species %in% c("setosa", "versicolor"))

# data.table::fwrite(iris_edit, "iris_edit.csv")
# rm(iris_edit)
# iris_edit <- data.table::fread("iris_edit.csv") %>% tibble::as_tibble(.)

# create tasks, learners, param set and cv strategy 

task.train <- makeClassifTask(data = iris_edit, 
                              target = "Species",
                              positive = "setosa")

xgboost_lrn <- makeLearner("classif.xgboost",
                           predict.type = "prob",
                           booster = "gbtree",
                           objective = "binary:logistic")

cv_strategy <- makeResampleDesc("CV", iters = 4, stratify = TRUE)

param_set = makeParamSet(makeNumericParam("eta", lower = 0.00001, upper = 0.4),
                         makeIntegerParam("nrounds", 10, 100))

# modelling part 

iter_num <- 60
tune_control = makeTuneControlRandom(maxit = iter_num)

parallelMap::parallelStart(mode = "multicore",
             cpus = 16,
             level = "mlr.tuneParams")

tune_xgboost_lrn <- tuneParams(learner = xgboost_lrn, 
                               task = task.train, 
                               resampling = cv_strategy, 
                               measures = auc, 
                               par.set = param_set, 
                               control = tune_control)

parallelMap::parallelStop()
```

Unfortunately, when I uncomment those 3 lines in the middle (with data:table::fwrite and fread) it utilizes only one core at the very end. I was wondering what happened in between that force the code not to parallelize underlying learner (maybe doing data.table::fread in parallel changes some setting implicitly, idk).

SessionInfo below:

```r
sessionInfo()
# R version 3.4.1 (--)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Ubuntu 16.04.4 LTS

# Matrix products: default
# BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.18.so

#  locale:
#  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
# [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] mlr_2.13          ParamHelpers_1.11 Rook_1.1-1        RJSONIO_1.3-0    
# [5] Cairo_1.5-6      
# 
# loaded via a namespace (and not attached):
#  [1] Rcpp_0.12.16      magrittr_1.5      bindr_0.1.1       splines_3.4.1    
#  [5] munsell_0.5.0     lattice_0.20-35   colorspace_1.3-2  R6_2.2.2         
#  [9] brew_1.0-6        rlang_0.2.0       fastmatch_1.1-0   plyr_1.8.4       
# [13] dplyr_0.7.4       tools_3.4.1       parallel_3.4.1    grid_3.4.1       
# [17] checkmate_1.8.5   data.table_1.11.4 gtable_0.2.0      survival_2.41-3  
# [21] lazyeval_0.2.1    assertthat_0.2.0  tibble_1.4.2      Matrix_1.2-10    
# [25] bindrcpp_0.2.2    ggplot2_3.0.0     codetools_0.2-15  glue_1.2.0       
# [29] parallelMap_1.3   stringi_1.2.2     compiler_3.4.1    pillar_1.2.2     
# [33] BBmisc_1.11       scales_0.5.0      backports_1.1.2   pkgconfig_2.0.1
```

**Comment by lumatt** [comment]
No, it's not. It has 128GB RAM, so should be enough for this task. Are you able to reproduce the issue?

**Comment by mb706** [comment]
This seems to be related to dmlc/xgboost#2094: xgboost's parallelization (OpenMP) does not work well together with parallelMap's "multicore" parallelization (`fork()`), and it is a surprise that this *does* work under some circumstances. Three possible solutions:
1. Do not use xgboost parallelization: Use `makeLearner("classif.xgboost", nthread = 1, ...)`
2. Do not use parallelMap "multicore" parallelization, but use e.g. `mode = "socket"` instead. This could be a bit less efficient because the large dataset is being copied inefficiently to worker threads.
3. Use both parallelMap multicore *and* xgboost parallelization, but be aware that you are on thin ice. For example, on my machine the script runs fine when `fwrite` only gets one thread: `data.table::fwrite(iris_edit, "iris_edit.csv", nThread = 1)`. I don't know why (there seems to be some interplay between both `fwrite` and `xgboost` using OpenMP), but again, the real question is why it does work sometimes.
---
The whole thing is a bit of a curiosity. The following script hangs if all is executed, *or* if only the part following `(3)` is executed, but if running everything from `(2)` the script works.
```r
# *** (1) ***
# run this whole script: R hangs
data.table::fwrite(iris[, sample(1:4, 10000, TRUE)], "iris.csv",
  nThread = 2, verbose = TRUE)  # output should show 'actual nth=2'

# *** (2) ***
# run everything from here: R does not hang
# (though note xgboost model handles are invalid)
library("mlr")
makeLearner("classif.xgboost")

# *** (3) ***
# run only the last bit: R hangs
data(agaricus.train, package='xgboost')
parallel::mclapply(1:4, function(x) {
  xgboost::xgboost(data = agaricus.train$data, label = agaricus.train$label,
    nthread = 2, nrounds = 2, objective = "binary:logistic")
  }, mc.cores = 4)
```
Apparently `makeLearner("classif.xgboost")` somehow protects xgboost from hanging in `parallel::mclapply`, but `data.table::fwrite` with more than one thread breaks things again.

**Comment by lumatt** [comment]
Thanks for feedback.

1. I didn't want to give exact number of threads to the xgboost, since I'm using parallelmap for tuning parameters. Having 64 cores and enabling user to do random search with maximum 16 guesses, it'd be ideal to running models using 4 cores not one.
2. Socket parallelization is unfeasible for me since the dataset I'm ingesting is huge :(
3. This is sth I also figured on my own (freading using one thread didn't stop the xgboost from using all the cores) - so probably it's not user- or machine-dependent.

Putting aside the fact that this is serious blocker for me, the whole thing is really interesting. Thanks for linking this thread to dmlc/xgboost#2094. Hopefully, someone can shed some more light on it.

**Comment by mb706** [comment]
According to http://bisqwit.iki.fi/story/howto/openmp/#OpenmpAndFork, this could be a compiler specific problem, so using clang or icc (if you have access, or maybe there are icc compiled binaries somewhere) could solve this issue for you.

Closing since this is not an issue with mlr. Good luck.
