### ISSUE TITLE
Info: Tutorial temp. unavailable while moving to new domain mlr-org.com

### ISSUE THREAD

**Issue by harlecin** [mlr-org/mlr#2454]
Hey there,

I believe the link to https://mlr-org.github.io/mlr/ is broken?

Best
Christoph

**Comment by pat-s** [comment]
Hi Christoph,

we are currently moving the tutorial to a new domain. Should be up soon. 
I'll keep you updated.

**Comment by pat-s** [comment]
It's up again. New URL: http://mlr.mlr-org.com

https hopefully soon.

**Comment by harlecin** [comment]
awesome:)

I saw that you are planning to refactor/upgrade mlr in v3?

Is there a todo list/sth similar where contributers can check if they can help with specific work items?

Best
Christoph


Sent from a mobile device. Sry for any typos!
________________________________
Von: Patrick Schratz <notifications@github.com>
Sent: Dienstag, Oktober 16, 2018 3:13 PM
An: mlr-org/mlr
Cc: Christoph Bodner; Author
Betreff: Re: [mlr-org/mlr] Weblink broken https://mlr-org.github.io/mlr/? (#2454)


It's up again. New URL: http://mlr.mlr-org.com

https hopefully soon.

**Comment by pat-s** [comment]
We still got some problems with the subdomains now, the tutorial is down again. I hope we have resolved the issues ASAP.

Yes, just check on the project mlr3 in our Github organization.

**Comment by harlecin** [comment]
Great:) I will take a look!

Thx a lot for all your work!

Sent from a mobile device. Sry for any typos!
________________________________

**Comment by pat-s** [comment]
Working now: mlr.mlr-org.com

Old URL mlr-org.github.io/mlr redirects to new url
