### ISSUE TITLE
Feature filtering for multi-label classifications not implemented?

### ISSUE THREAD

**Issue by krltrl** [mlr-org/mlr#2455]
I was trying to fuse a learner with a feature-filter method in a multi-label classification like this:

```r
lrn.br = makeLearner("classif.rpart", predict.type = "prob")
lrn.br = makeFilterWrapper(learner = lrn.br, fw.method = "information.gain", fw.abs = 2)
lrn.br = makeMultilabelBinaryRelevanceWrapper(lrn.br)
```

This does not throw an error, but when I train the model the features remain unfiltered:
```r
mod=train(lrn.br, yeast.task)

mod
mod$features
getFilteredFeatures(mod)
```

Would it be difficult to implement this? Or is it already on the list?

**Comment by krltrl** [comment]
That's perfect! 
`getLearnerModel()` was exactly what I needed. 
Thank you!

**Comment by krltrl** [comment]
By the way, is there an easy way to choose label-specific features manually?

I have enigneered one feature per label of which I expect it has explanatory power for this label only.

**Comment by mb706** [comment]
You can try [mlrCPO](/mlr-org/mlrCPO), which gives a lot of operations for features manipulation. You could write a [custom CPO](https://rawgit.com/mlr-org/mlrCPO/master/inst/doc/a_4_custom_CPOs.html#makecpo), but a [`cpoCase`](https://rawgit.com/mlr-org/mlrCPO/master/inst/doc/a_3_all_CPOs.html#cpocase) CPO would be a bit simpler:
    
```r
library("mlrCPO")
fselcpo <- cpoCase(dataformat = "task", cpo.build = function(data, target) {
  # The cpo.build function must return a "CPO" object that then gets applied
  # to the data. We can programmatically influence what kind of CPO gets
  # returned.
  # This returns a cpoFilterFeatures. Therefore, applying the "fselcpo" object we
  # construct here acts as if we apply a cpoFilterFeatures,
  # but with dynamic 'mandatory.feat' argument!

  mandatory.feat= getTaskFeatureNames(data)[nchar(target)]  # ... or whatever makes sense
  cpoFilterFeatures(method = "anova.test", abs = 3,
    filter.args = list(mandatory.feat = mandatory.feat))
})
lrn.br <- fselcpo %>>% makeLearner("classif.rpart", predict.type = "prob")
lrn.br <- makeMultilabelBinaryRelevanceWrapper(lrn.br)
mod <- train(lrn.br, yeast.task)
```
Here, just as with the FeatureFilter, the CPO acts *after* the MultilabelBinaryRelevanceWrapper, so the CPO runs for each of the target labels independently and only sees one label.

Note that you have to pry the selected features from the retrafo states:
```r
getFilteredFeatsFromCaseCPO <- function(model) {
  case.state <- getCPOTrainedState(retrafo(model))
  filter.state <- getCPOTrainedState(case.state$control)
  filtered.features <- filter.state$control
  filtered.features
}

sapply(getLearnerModel(mod), getFilteredFeatsFromCaseCPO)
```
If you run this example as-is you will see a matrix that indicates that features were selected: feature `x6` or `x7` depending on the name of the target column, as well as features selected by `"anova.test"`:
```r
     label1 label2 label3 label4 label5 label6 label7 label8 label9 label10
[1,] "x6"   "x6"   "x6"   "x6"   "x6"   "x6"   "x6"   "x6"   "x6"   "x7"   
[2,] "x88"  "x57"  "x58"  "x23"  "x62"  "x22"  "x23"  "x22"  "x47"  "x60"  
[3,] "x96"  "x61"  "x88"  "x61"  "x66"  "x23"  "x60"  "x23"  "x61"  "x61"  
     label11 label12 label13 label14
[1,] "x7"    "x7"    "x7"    "x7"   
[2,] "x60"   "x26"   "x26"   "x58"  
[3,] "x61"   "x27"   "x27"   "x91"  

```

**Comment by krltrl** [comment]
Thanks again, this seems like what I need!
