### ISSUE TITLE
Broken documentation link on mlr site

### ISSUE THREAD

**Issue by apeljohn** [mlr-org/mlr#2457]
I'm investigating the different measures available to mlr.  The relevant [documentation page](https://mlr.mlr-org.com/reference/measures.html) says:
> All supported measures can be found by listMeasures or as a table in the tutorial appendix: https://mlr-org.github.io/mlr/articles/measures.html.

However, following that link results in a redirection to https://mlr.mlr-org.com/articles/measures.html, which gives a 404 error.

I've confirmed the problem under Internet Explorer 11 on Windows 10 Enterprise (work laptop...), and on Chrome 69 on Android Marshmallow.

I am unable to locate the relevant page via site search (using the names of some measures from listMeasures() output) or on the Wayback Machine (web.archive.org).

**Comment by pat-s** [comment]
Thanks for the report. Will be fixed soon.

**Comment by apeljohn** [comment]
Thanks!
