### ISSUE TITLE
Getting help for libraries from mlr

### ISSUE THREAD

**Issue by mazgit82** [mlr-org/mlr#2460]
This is not a bug, just a suggestion. It would be interesting to be able to get help about libraries managed by mlr. For instance, if I wanted to know what "interaction.depth" is in "regr.gbm", I have to first: locate the library associated to "regr.gbm", second: locate the gbm training function, and third: do ?gbm. It would be useful to do something like help("regr.gbm").

**Comment by larskotthoff** [comment]
Thanks for the suggestion -- yes, that would be useful. That said, we have no plans for implementing it at the moment.

**Comment by larskotthoff** [comment]
Ah! We already have that! Thanks @mb706 :)

**Comment by mazgit82** [comment]
Thanks :-)
