### ISSUE TITLE
generateFilterValuesData() doesn't filter features

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2462]
`generateFilterValuesData()` has an argument `nselect` which is also passed down to all implemented Filter methods.

However, setting it has no effect as its neither applied in any filter nor in `generateFilterValuesData()` itself. The function always returns all filter values.

Subsetting is done in `filterFeatures()`: 

https://github.com/mlr-org/mlr/blob/c94ffcfee301f20627af8c8194a747806942a7f0/R/filterFeatures.R#L78-L81

While this is a little practical thing and does nothing "bad", it has a rather big effect when trying to memoise the call of `generateFilterValuesData()` while trying to speed up the filtering.

If `nselect` (which is usually tuned) would not be passed to `generateFilterValuesData()`, we can memoise the function if the `task` is the same in a tuning scenario (e.g. when tuning `fw.perc` on the same fold).

Specifically, the `fw.perc` value to be tuned is always passed to `generateFilterValuesData()` in `filterFeatures()`, triggering an argument change in which case no memoisation is applied.

Can anyone validate my finding of `nselect` being unncessary for `generateFilterValuesData()`? 

[hope that SO can follow. writing this as the last lines on a long day comes with the danger of completely seeing wrong things ;) ]

#1995

**Comment by pat-s** [comment]
In this regard: Why is `generateFilterValuesData()` exported at all? `filterFeatures()` with `perc = 1` does the same.

I think it just confuses to have two functions of which one is just a subset function of the other.

Is there anything I am overlooking or would it be ok to make `generateFilterValuesData()` internal only and just have `filterFeatures()`?

**Comment by berndbischl** [comment]
I don't think nselect is irrelevant for all filters itself. I am currently on my phone and would need to check later

**Comment by berndbischl** [comment]
Well. A. It should be irrelevant for most filters b. In the other cases it probably simply does not compute filter values for the remaining features. So in theses cases a greedy algorithm is run IIRC which is stopped after nselect iterations.

**Comment by pat-s** [comment]
> In the other cases it probably simply does not compute filter values for the remaining features. So in theses cases a greedy algorithm is run IIRC which is stopped after nselect iterations.

There is not one filter that uses `nselect` in its call as implemented right now.
I also do not see the advantage - we should always calculate all values ONCE and then subset.

### Why the removal of `nselect` in `generateFilterValuesData() would be good:

`nselect` set in `filterFeatures()` is always different in every tuning iteration. It is passed to `generateFilterValuesData()` without an effect because the actual subsetting happens later.
However, this causes that the arguments to `generateFilterValuesData()` change in every iteration (because of a varying `nselect`) which makes the caching of the results impossible.
(The caching is initiated if the function is called with the same arguments.)

So the unnecessary passing of `nselect` to `generateFilterValuesData()` prevents the successful caching of the generated filter values.

That's why I vote for

- making `generateFilterValuesData()` internal only
- remove `nselect` as an argument of `generateFilterValuesData()`

**Comment by mb706** [comment]
How is making generateFilterValuesData private related to this? (I'm slightly against this btw)

If `nselect` does not influence the relevant part of the result of `generateFilterValuesData` (and only affects runtime in some potential cases) you can also call it with `nselect = getTaskNFeats(task)` whenever caching is enabled, and keep the present behaviour when you are not caching. (The user should have a saying in whether caching is done or not, because some feature filters are nondeterministic)

**Comment by pat-s** [comment]
> How is making generateFilterValuesData private related to this? (I'm slightly against this btw)

Why do we need two functions which do the same of which one is only a subset of the other?

```r
# same
filterFeatures(task, method, perc = 1)
getFilterValuesData(task, method)
```

IMO this confuses the user -> "Why are there two functions? What is the difference? Why can't I just use `filterFeatures(task, method, perc = 1)` if I want all features (default) and `filterFeatures(task, method, perc = <xy>)` if I want a subset? Should I use `generateFilterValuesData()` for it or not?

> If nselect does not influence the relevant part of the result of generateFilterValuesData (and only affects runtime in some potential cases) you can also call it with nselect = getTaskNFeats(task) whenever caching is enabled, and keep the present behaviour when you are not caching. 

Why keep an argument to a function that is not used? (and will probably never be used in any filter because we want to return all values always and subset afterwards).

Using `nselect = getTaskNFeats(task)` would help, yes - but I would "simply" simplify the function by removing the argument?

> (The user should have a saying in whether caching is done or not, because some feature filters are nondeterministic)

Ok, I'll add a switch :) Which one is nondeterministic of the implemented ones?

**Comment by mb706** [comment]
How does the user get the filter value information (`"relief"` values, say) by calling `filterFeatures`?

**Comment by pat-s** [comment]
By attaching the internally computed filterValues as an object slot in the task?

- `generateFilterValuesData()` returns `task.desc` and a DF with the filter values.
- `filterFeatures()` returns a subsetted task. 

Other dependent functions like `plotFilterValues()` could also just work on `filterFeatures()` instead of only on `generateFilterValuesData()` once the filterValues DF exists there.

Both approaches have their adv/disadv here. Don't have a clear fav atm. Guess we need more opinions :)

**Comment by pat-s** [comment]
Ok, thinking about it again - I think its not worth making `generateFilterValuesData()` internal.

I see that it would even be unlogic to call `filterFeatures()` if we do not want to subset but just return all filter values. And all the additional effort changing things in `filterFeatures()`.

However, I still vote for the removal of `nselect` rather than doing the "`getTaskFeatures` workaround."
