### ISSUE TITLE
better name for getHyperParam

### ISSUE THREAD

**Issue by AtharKharal** [mlr-org/mlr#2465]
getHyperParam gets current parameter settings for a learner, and getParamSet gets a set of all possible parameter settings for a learner. It would be more consistent, I think, if getHyperParam is re-named as getParamVals.

**Comment by jakob-r** [comment]
I agree. As we are working at a completely new version of mlr we won't change the API of this mlr version anymore. Therefore I close this issue.

However we try to be more aware of consistent naming in the future version and therefore appreciate your input.
