### ISSUE TITLE
export `type` parameter for regr.gbm

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#2466]
`gbm::predict.gbm` has a `type` parameter that governs whether prediction is done on response or on link function scale. By default this is `"link"`, which is often not what one wants (because training data is on response scale). The user should have a choice here (and maybe it should be set to `"response"` by default?).

This came up [on Stackoverflow](https://stackoverflow.com/questions/53086410).

Example: Note the predicted "response" is in log scale.

```r
> counttask <- makeRegrTask("counttask", getTaskData(pid.task), target = "pregnant")
> predict(train(makeLearner("regr.gbm", distribution = "poisson"), counttask), counttask)
Prediction: 768 observations
predict.type: response
threshold:
time: 0.00
  id truth  response
1  1     6 2.0890591
2  2     1 1.2618966
3  3     8 1.5237790
4  4     1 0.5212248
5  5     0 1.0705697
6  6     5 1.3181337
... (#rows: 768, #cols: 3)
```

**Comment by berndbischl** [comment]
shouldnt the type param simply be changed? as the user probably never wants that? we can export it too,for more flexibility, but the default should be changed?

**Comment by mb706** [comment]
After checking a few learners it appears to me that it would be untypical for mlr to have a parameter that sets the prediction output to something nonstandard (and only `predict.type` influences the format of the predictions made at all), so I think `type = "response"` could also be hardcoded.

**Comment by berndbischl** [comment]
i guess i agree. do you wanna do that to close here?
