### ISSUE TITLE
Repo and site links to blog are dead

### ISSUE THREAD

**Issue by dshkol** [mlr-org/mlr#2471]
Minor issue, but the link to the blog in the readme for the Github repo and the corresponding pkgdown site uses this address: https://mlr-blog.netlify.com/ which appears to be dead. 

Google searches for "mlr + blog + r" find redirects to https://mlr-org.github.io/, which also appears to be dead. 

Is there a blog still?

**Comment by MartinKlm** [comment]
While the other links are dead, try to use this one:
https://mlr.mlr-org.com/

**Comment by pat-s** [comment]
Blog and main site: [https://mlr-org.com/](https://mlr-org.com/)
mlr-tutorial: [https://mlr.mlr-org.com/](https://mlr.mlr-org.com/)

Thanks for the report. We just recently changed all URLs to make them consistent across all of our pkgs. There may still be some leftovers.
