### ISSUE TITLE
resample does not accept argument 'predict.type' as extra argument

### ISSUE THREAD

**Issue by vrodriguezf** [mlr-org/mlr#2473]
This works:
```{r}
res = resample(
  learner = makeLearner("classif.rpart", predict.type = "prob"),
  task = iris.task,
  resampling = makeResampleDesc(method = "Holdout"),
  models = TRUE,
  minsplit = 25
)
```

But this does not work:
```{r}
res = resample(
  learner = makeLearner("classif.rpart"),
  task = iris.task,
  resampling = makeResampleDesc(method = "Holdout"),
  models = TRUE,
  minsplit = 25,
  predict.type = "prob"
)

 Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  classif.rpart: Setting parameter predict.type without available description object!
Did you mean one of these hyperparameters instead: surrogatestyle minbucket cp
You can switch off this check by using configureMlr!
```

Why is it possible to put any learner param as a resample argument except predict.type? Does it make sense?

Thanks!

**Comment by larskotthoff** [comment]
The parameters are something you want to change and tweak for a given learner (e.g. when tuning to get better performance), but the predict type is not. Once you've instantiated a learner, there's usually no reason to change the predict type. Does that make sense?

**Comment by berndbischl** [comment]
it does :)
another argument might be "this is how we chose to implement it" and it is documented.
... is passed down to par.vals / setHyperPars and that only accepst the individual hyperpars of the learner

**Comment by vrodriguezf** [comment]
Alright, thanks for your prompt response! ;)
