### ISSUE TITLE
PDF Tutorial margins

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#2476]
Would be good to have smaller margins in the pdf tutorial. So much space is wasted on the sides, at least in this version (Is it the newest? If not we should update it.): https://www.researchgate.net/profile/Julia_Schiffner2/publication/309321851_mlr_Tutorial/links/580f444d08aef2ef97afc00e/mlr-Tutorial.pdf

`geometry: margin=2cm` in the header should do it.

**Comment by pat-s** [comment]
Definitely not the latest version. 

Your right about the margins but we (i.e. Bernd) decided to not build a PDF tutorial anymore to make our life easier.
