### ISSUE TITLE
Making a feature selection wrapper before a tuning wrapper fails.

### ISSUE THREAD

**Issue by sycoforbidden** [mlr-org/mlr#2481]
When trying to make a filter wrapper with a tuning step afterwards, mlr gives an error.

The custom filter "BIA" is run once at the start since it is computationally expensive. 
It results in an BIAobject, from which features can be extracted. It should be passed down to filter since a cascade of filters is supposedly not possible in mlr, and it marks certain features as automatically not present in the final model.

```r

# BIA is a custom filter that optionally works with an external variable, the BIAobject.
# Given a task, a filter with an object that should be passed down to it, this happens:

BIAobject <- BIA.m(X = tmptaskdata$data,
                   Y = tmptaskdata$target)

learner <- makeTuneWrapper(learner = "regr.plsr",
                                 resampling = cv10,
                                 measures = rmse,
                                 par.set = LTuneParam,
                                 control = tc,
                                 show.info = FALSE)

subset <- 1:(taskindex$test[1] - 1)

# From here down

tmptasklist <- lapply(seq(from = 0.05, to = 1, by = 0.05), function(k) {
  tmp <- filterFeatures(task = task, method = "BIA", perc = k, BIAobject = BIAobject)
  r <- subsetTask(tmp, subset = subset)
  r$task.desc$id <- paste0(r$task.desc$id, "_feat_", k)
  r
})

mdl <- benchmark(learners = learner,
                 tasks = tmptasklist,
                 resamplings = cv10,
                 measures = rmse,
                 show.info = TRUE)

# ^ This works...

tmplrnlist <- lapply(seq(from = 0.05, to = 1, by = 0.05), function(k) {
  r <- makeFilterWrapper(learner, fw.method = "BIA", fw.perc = k, BIAobject = BIAobject)
  r$id <- paste0(r$id, "_feat_", k)
  r
})

tmptask <- subsetTask(task, subset = subset)

mdl <- benchmark(learners = tmplrnlist,
                 tasks = tmptask,
                 resamplings = cv10,
                 measures = rmse,
                 show.info = TRUE)

# ^ But his doesn't work, with or without passing BIAobject to makeFilterWrapper().

# Error message:
# 
# Task: TASK_4, Learner: regr.plsr.tuned.filtered_feat_0.05
# Resampling: cross-validation
# Measures:             rmse      
# Error in requireNamespace(pack, quietly = TRUE) : 
#   attempt to use zero-length variable name

```

**Comment by mb706** [comment]
I tried running this with a builtin filter ("variance") and could not reproduce the error. Are you sure this is not caused by a problem in your custom filter code?  Are you using parallelization? Does the problem go away if you are not using a `TuneWrapper`? If you could share the stack trace of the error (run `options(error=recover)` before running the benchmark) it may help finding the problem.

Be aware that the two calculations you are performing are *different*: In the first `benchmark` call you are doing feature filtering first, and then doing resampling with the reduced tasks--your filter method is called 20 times in total, each time with the whole task as input. In the second `benchmark` call you are doing resampling *first*, and within each CV10 resampling iteration you filter features. Your feature filter method is called 20x10 times (20 benchmarking instances i.e. `fw.perc` values, 10 cross validation instances each), each time with a 90% subset of the input task. Maybe your `"BIA"` method is assuming that the task used to create the `BIAobject` is the same task that is being filtered (and not a crossvalidation subset) and this is causing the error.

I hope you are aware of the problems of doing feature filtering "outside" of resampling (your first `benchmark` call; depending on how the `BIAobject` thing works maybe both?); if you want to assess the performance of a filtering method using resampling, the method should ideally not use any information from outside the training resampling subset.

**Comment by sycoforbidden** [comment]
> In the second `benchmark` call you are doing resampling _first_, and within each CV10 resampling iteration you filter features. Your feature filter method is called 20x10 times (20 benchmarking instances i.e. `fw.perc` values, 10 cross validation instances each), each time with a 90% subset of the input task. Maybe your `"BIA"` method is assuming that the task used to create the `BIAobject` is the same task that is being filtered (and not a crossvalidation subset) and this is causing the error.

What you said is true, it's supposed to be a filter that takes into account the correlation between features and the correlation between features and target, and that's why i supply a BIAobject with the result for the whole `data$data` and `data$target`. Its solution is dependent on a complete matrix given by BIAobject, so filtering within each resample may very well change the variables chosen for removal.

The result of BIAobject is the probability that each variable X_i is important to the model, ie
P(s_i = 1|y). If it's below 50%, it shouldn't be even considered in the final model. The ranking I provide is the average probability for a set of different lambda values, and of those over 50%. 

What i really wanted to try was an extension of the base "BIA" method, where it would search based on CV and on the ranking of variables which ones should definitely be in the model for better accuracy (I want to choose the n percent that have the highest probability). I would then use the selected features to find the best model while tuning the # of ncomp for PLSR.

**Comment by sycoforbidden** [comment]
> if you want to assess the performance of a filtering method using resampling, the method should ideally not use any information from outside the training resampling subset.

I can see why this is true, however I would have to do a cascading filter, since there's a hard limit for the features' probabilities and i want a percentage of those, Even though it's not possible to do so in MLR.

**Comment by mb706** [comment]
I am not exactly sure what you are trying to do, and why that is impossible in MLR. If you need a more powerful environment for preprocessing you can try [mlrCPO](https://github.com/mlr-org/mlrCPO) (in particular [custom CPOs](https://rawgit.com/mlr-org/mlrCPO/master/inst/doc/a_4_custom_CPOs.html)), which allows for custom functions to be applied on data as part of the `train()` and `predict()` pipeline. See e.g. the example of [`makeCPO`](https://rawgit.com/mlr-org/mlrCPO/master/inst/doc/a_4_custom_CPOs.html#makecpo) in the documentation.

**Comment by sycoforbidden** [comment]
> I am not exactly sure what you are trying to do, and why that is impossible in MLR. If you need a more powerful environment for preprocessing you can try mlrCPO (in particular custom CPOs), which allows for custom functions to be applied on data as part of the train() and predict() pipeline. See e.g. the example of makeCPO in the documentation.

I'm saying it's not implemented based on this open issue:
https://github.com/mlr-org/mlr/issues/1386

**Comment by mb706** [comment]
I was not aware of this issue; see [my comment](https://github.com/mlr-org/mlr/issues/1386#issuecomment-437864438) I just made there: It is possible to use the `cpoFilterFeatures` of mlrCPO to stack feature filters. The arguments are similar to `mlr::filterFeatures`. Please report back if this does not work, mlrCPO is relatively new and not well tested in the field yet.

**Comment by sycoforbidden** [comment]
Thank you, i will try it and report back asap.

**Comment by berndbischl** [comment]
> Thank you, i will try it and report back asap.

if you do so, please provide a complete and reproducible example.
