### ISSUE TITLE
Filter packages are not loaded automatically

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#2484]
Inspired by #2483

When calling `filterFeatures` or using filters in a similar way, the `pkg` argument given during `makeFilter` should make sure the package is loaded (tbh I'm not sure I know why). This happens [here](https://github.com/mlr-org/mlr/blob/f2817efb5d033adf2d090cd435852c974f1722d1/R/generateFilterValues.R#L41-L42). However, the if statement does not do what I assume it is supposed to do:
* The condition resolves to `TRUE` if and only if all `pkg` values are `NA` (learn your De Morgans Laws, guys)
* Filters that should not load any packages are (at least in some cases) indicated as `character(0)`. See e.g. `mlr:::.FilterRegister$variance$pkg`

**Comment by pat-s** [comment]
> Filters that should not load any packages are (at least in some cases) indicated as character(0). See e.g. mlr:::.FilterRegister$variance$pkg

This is bc of 

https://github.com/mlr-org/mlr/blob/f2817efb5d033adf2d090cd435852c974f1722d1/R/Filter.R#L33

Setting it as `character(0)` does the job for both checks. But I think it would be better if this slot could be `NA` or `NULL`? I [changed](https://github.com/mlr-org/mlr/pull/2483/commits/112af1363ea9a92bc0e1a4b5cd660a486088d93a) the `assert` function from `assertCharacter()` to `assert_choice(null.ok = TRUE)` in `makeFilter()`:

- filters requiring no pkg no come with a slot `pkg` which defaults to `NULL`
- choices of required filter pkgs are given in `makeFilter()`.

What do you think about this NS loading approach?

**Comment by pat-s** [comment]
AFAIR this was solved by referenced commit.
