### ISSUE TITLE
What to do with the purrr pkg?

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2489]
Bernd raised the question on Slack.
https://cran.r-project.org/web/packages/purrr/index.html
_purrr_ deps:

Imports: | magrittr (≥ 1.5), rlang (≥ 0.1), tibble
-- | --
Suggests: | covr, dplyr (≥ 0.7.5), knitr, rmarkdown, testthat

- Have _purrr_ staying in IMPORTS (which it is currently since some months)
- Move it to SUGGESTS
- A complete removal is not really possible since we rely on the `imap()` function in some code parts which is not available elsewhere.

**Comment by mllg** [comment]
The complete list of dependencies:
```r
 setdiff(package_dependencies("purrr", recursive=TRUE)[[1L]], getOption("defaultPackages"))
 [1] "magrittr"   "rlang"      "tibble"     "cli"        "crayon"    
 [6] "pillar"     "assertthat" "fansi"      "utf8"       "tools" 
```


Here is a simple replacement for `imap` (without the NSE for obvious reasons):
```r
imap = function(.x, .f) {
  Map(.f, .x = .x, .y = seq_along(.x))
}
```

**Comment by mllg** [comment]
For `map_xxx` we have the `v[ilnc]apply` alternatives in BBmisc.

I'm not saying that I generally don't like the purrr package, but I believe we should either use it everywhere or stick to the previously used apply functions.

**Comment by pat-s** [comment]
> Here is a simple replacement for imap (without the NSE for obvious reasons):

cool. 

> For map_xxx we have the v[ilnc]apply alternatives in BBmisc.
> 
> I'm not saying that I generally don't like the purrr package, but I believe we should either use it everywhere or stick to the previously used apply functions.

Yes. Let's see if I can get rid of them then. 

> The complete list of dependencies:

Meta questions: 
- Would you consider this amount as "many"? 
- The question is anyhow if these deps are so "heavy" bc a normal R user nowadays has all of these deps installed via other pkgs anyway?
- should we rely on _purrr_ in mlr3?

**Comment by mllg** [comment]
> Meta questions:
> 
> * Would you consider this amount as "many"?
> * The question is anyhow if these deps are so "heavy" bc a normal R user nowadays has all of these deps installed via other pkgs anyway?

I guess it is a tradeoff. You don't want to reinvent the wheel, but 
http://www.tinyverse.org/ also got some arguments.

For some wrappers around `lapply`, purrr looks quite heavy.


> * should we rely on _purrr_ in mlr3?

Are you suggesting to import purrr and replace all calls to lapply/vapply/mapply/... with their purrr counterparts? :wink:

**Comment by pat-s** [comment]
> http://www.tinyverse.org/ also got some arguments.

Nice reference.

> Are you suggesting to import purrr and replace all calls to lapply/vapply/mapply/... with their purrr counterparts? wink

I guess I do not need an answer for this anymore ;)

The point I had is that using pkgs that are widely known to the com make it way easier for people to contribute bc you do not have to tell them "have a look at our 999+ helper functions in pkg X that we wrote because base-R sucks and dependencies even more".
