### ISSUE TITLE
Lightgbm custom learner with hiperparameters tuning "unserialize(node$con) : error reading from connection"

### ISSUE THREAD

**Issue by matkalinowski** [mlr-org/mlr#2492]
**How I run this**
- open Rstudio;
- create script & paste code;
- add data from attachment;
- run whole script (for me it failed everytime, it runs about 1 minute);
- it turns down the session so i use new jobs feature in rstudio to see the output.

**Informations about the code:**
- First few methods are just overwriting of mlr methods due to error in makeRLearnerInternal, line: learner$fix.factors.prediction = F seems to be fixing the problem.
- lightgbm integration comes from https://github.com/MelvinWoodley/mlr-lightgbm-Extension/blob/master/mlr_lightgbm_starter.R

**Other informations:**
- Data is added as an attachment **([data.zip](https://github.com/mlr-org/mlr/files/2593137/data.zip))**.
- I haven't tried other parallelStart* options.
- lower values of maxit (like 4) in makeTuneControlRandom are working- optimization finishes (in this example You can run makeTuneControlRandom or makeTuneControlGrid).
- I still got a lot of RAM (4-5 GB) available while running this example.
- It doesn't matter how many cores I've set.
- sometimes traceback is not available;
- sometimes logs are scattered like in the given example;
- lightgbm library was installed using r package.
- It fails in two ways:
     - one is when i run it in parallel- then You can see traceback below (and whole output at the end)
     - second is when i run it with commented lines (and whole output at the end):
```r
library(parallelMap)
parallelStartSocket(cpus = 2)
parallelExport('trainLearner.regr.lightgbm', 'predictLearner.regr.lightgbm', 'lgb.Dataset')
```

**Traceback:**
> 14: unserialize(node$con)
> 13: recvData.SOCKnode(con)
> 12: recvData(con)
> 11: FUN(X[[i]], ...)
> 10: lapply(cl[1:jobs], recvResult)
> 9: staticClusterApply(cl, fun, vlen, argfun)
> 8: clusterMap(cl = NULL, slaveWrapper, ..., .i = iters, MoreArgs = more.args, 
>        SIMPLIFY = FALSE, USE.NAMES = FALSE)
> 7: parallelMap(evalOptimizationState, dobs, states, level = level, 
>        more.args = list(learner = learner, task = task, resampling = resampling, 
>            measures = measures, par.set = par.set, bits.to.features = bits.to.features, 
>            control = control, opt.path = opt.path, show.info = show.info, 
>            remove.nas = remove.nas, resample.fun = resample.fun))
> 6: evalOptimizationStates(learner, task, resampling, measures, par.set, 
>        NULL, control, opt.path, show.info, states, dobs, eols, remove.nas, 
>        resample.fun, "mlr.tuneParams")
> 5: evalOptimizationStatesTune(learner, task, resampling, measures, 
>        par.set, control, opt.path, show.info, xs, dobs = seq_along(xs), 
>        eols = NA_integer_, remove.nas = TRUE, resample.fun = resample.fun)
> 4: sel.func(learner, task, resampling, measures, par.set, control, 
>        opt.path, show.info, resample.fun)
> 3: tuneParams(learner = lgb_learner, task = trainTask, resampling = resample_desc, 
>        par.set = lgb_params_set, control = control, measures = rmse) at #3
> 2: tryCatchList(expr, classes, parentenv, handlers)
> 1: tryCatch({
>        lgb_params_tuning <- tuneParams(learner = lgb_learner, task = trainTask, 
>            resampling = resample_desc, par.set = lgb_params_set, 
>            control = control, measures = rmse)
>    }, finally = {
>        print("Traceback below:")
>        print(traceback())
>        print("Warnings below:")
>        print(warnings())
>    })
> 

**additional sources on this problem (sorted according to information gain):**
- https://github.com/stan-dev/rstan/issues/243
- https://github.com/HenrikBengtsson/future/issues/143
- https://github.com/kenkellner/jagsUI/issues/8
**about how to do parallel in r** (there is an information about this error stating: "as you can see below when we create an intermediate variable that takes up storage space:")
- http://gforge.se/2015/02/how-to-go-parallel-in-r-basics-tips/

**sessionInfo:**
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] **parallelMap_1.3**   bindrcpp_0.2.2    stringi_1.1.7     checkmate_1.8.5   BBmisc_1.11      
 [6] knitr_1.20        **lightgbm_2.2.3**    R6_2.3.0          forcats_0.3.0     stringr_1.3.1    
[11] dplyr_0.7.7       purrr_0.2.5       readr_1.1.1       tidyr_0.8.2       tibble_1.4.2     
[16] ggplot2_3.1.0     tidyverse_1.2.1   **mlr_2.13**          ParamHelpers_1.11 logging_0.7-103  

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5  splines_3.5.0     haven_1.1.2       lattice_0.20-35   colorspace_1.3-2 
 [6] survival_2.41-3   XML_3.98-1.16     rlang_0.3.0.1     pillar_1.2.2      withr_2.1.2      
[11] glue_1.3.0        modelr_0.1.2      readxl_1.1.0      bindr_0.1.1       plyr_1.8.4       
[16] munsell_0.4.3     gtable_0.2.0      cellranger_1.1.0  rvest_0.3.2       **parallel_3.5.0**   
[21] broom_0.5.0       Rcpp_0.12.17      scales_0.5.0      backports_1.1.2   jsonlite_1.5     
[26] fastmatch_1.1-0   hms_0.4.2         grid_3.5.0        cli_1.0.0         tools_3.5.0      
[31] magrittr_1.5      lazyeval_0.2.1    crayon_1.3.4      pkgconfig_2.0.2   Matrix_1.2-14    
[36] data.table_1.11.8 xml2_1.2.0        lubridate_1.7.4   assertthat_0.2.0  httr_1.3.1       
[41] rstudioapi_0.7    nlme_3.1-137      compiler_3.5.0  

**Code:**
```r
# loading libraries ----------------------------------------------------------------------------------------------
library(mlr)
configureMlr(on.learner.error = 'warn', on.error.dump = T)

library(tidyverse)
library(lightgbm)
library(knitr)

# fixing mlr method -----------------------------------------------------------------------------------------------
library(BBmisc)
library(checkmate)
library(stringi)

makeParamHelpList <- function(funs, pkgs, par.set) {
  help.list = list()
  par.ids = getParamIds(par.set)
  pkgs = stri_replace_all(pkgs, "", regex = "[+!_]")
  h = NULL
  for (f in rev(funs)) {
    for (pkg_ref in pkgs) {
      h = utils::help(f, package = (pkg_ref))
      if (length(h) > 0) {
        break
      }
    }
    if (length(h) == 0) {
      # catf("nothing found: %s", f)
      next
    }
    ghf = get(".getHelpFile", mode = "function", envir = getNamespace("utils"))
    html = capture.output(tools::Rd2HTML(ghf(h)))
    html = XML::htmlParse(html)
    # try to extract the 'R argblock' table
    tab = XML::getNodeSet(html, "//table[@summary='R argblock']")
    if (length(tab) < 1) {
      next
    }
    tbl = do.call(rbind, lapply(tab, function(t) {
      tbl = XML::readHTMLTable(t, header = FALSE, stringsAsFactors = FALSE)
      if (identical(ncol(tbl), 2L)) {
        tbl
      }
    }))
    # we also try to extract generally all lists that begin with a code string.
    # this gets appended to the front, so that the (more trustworthy) html table
    # extract will overwrite the <li>-extract if a param occurs in both.
    tbl = rbind(codeListToTable(html), tbl)
    if (is.null(tbl)) {
      next
    }
    for (row in seq_len(nrow(tbl))) {
      # the following loop handles occasions where multiple parameters are mentioned in
      # one row, separated by commas.
      for (par.name in stri_split(tbl[row, 1], regex = ", *")[[1]]) {
        if (par.name %in% par.ids) {
          help.list[[par.name]] = stri_join("Argument of: ",
                                            pkg_ref, "::", f, "\n\n", prepareString(tbl[row, 2]))
        } else {
          # catf("not interesting: %s par %s", f, par.name)
        }
      }
    }
  }
  return(help.list)
}


makeLearnerBaseConstructor <-  function(classes, id, type, package, properties, par.set, par.vals, predict.type) {
  if (length(par.vals) == 0L)
    names(par.vals) = character(0L)
  
  learner = makeS3Obj(c(classes, "Learner"),
                      id = id,
                      type = type,
                      package = package,
                      properties = unique(properties),
                      par.set = par.set,
                      par.vals = par.vals,
                      predict.type = predict.type
  )
  return(learner)
}

makeRLearnerInternal <-  function(id, type, package, par.set, par.vals, properties,
                                  name = id, short.name = id, note = "", callees) {
  
  # must do that before accessing par.set
  # one case where lazy eval is actually helpful...
  assertCharacter(package, any.missing = FALSE)
  requirePackages(package, why = stri_paste("learner", id, sep = " "), default.method = "load")
  
  assertString(id)
  assertChoice(type, choices = c("classif", "regr", "multilabel", "surv", "cluster", "costsens"))
  assertSubset(properties, listLearnerProperties(type))
  assertClass(par.set, classes = "ParamSet")
  checkListElementClass(par.set$pars, "LearnerParam")
  assertList(par.vals)
  if (!isProperlyNamed(par.vals))
    stop("Argument par.vals must be a properly named list!")
  assertString(name)
  assertString(short.name)
  assertString(note)
  assertCharacter(callees, any.missing = FALSE)
  learner = makeLearnerBaseConstructor("RLearner",
                                       id = id,
                                       type = type,
                                       package = package,
                                       properties = unique(properties),
                                       par.set = par.set,
                                       par.vals = par.vals,
                                       predict.type = "response"
  )
  learner$name = name
  learner$short.name = short.name
  learner$note = note
  learner$callees = callees
  learner$help.list = makeParamHelpList(callees, package, par.set)
  learner$fix.factors.prediction = F
  return(learner)
  
}



# preparing data --------------------------------------------------------------------------------------------------

prepare_data_for_ml_tasks <- function(train_orig, test_orig) {
  train <- train_orig %>%
    mutate(dataset = "train")
  
  test <- test_orig %>%
    mutate(dataset = "test")
  
  combined <- bind_rows(train, test)
  
  combined <- combined %>%
    mutate_at(
      .vars = vars("Product_ID", "Gender", "Age", "Occupation", "City_Category", "Stay_In_Current_City_Years", "Marital_Status", "Product_Category_1", "Product_Category_2", "Product_Category_3"),
      .funs = funs(as.factor(.))
    ) %>%
    select(-c(User_ID, Product_Category_2, Product_Category_3))
  
  train <- combined %>%
    filter(dataset == "train") %>%
    select(-dataset)
  
  test <- combined %>%
    filter(dataset == "test") %>%
    select(-dataset)
  
  train <- train %>%
    mutate_at(
      .vars = colnames(Filter(is.factor, train)),
      .funs = funs(as.integer(.))
    )
  return(list(
    train = train,
    test = test
  ))
}

train_orig <- read_csv("./data/train.csv")
test_orig <- read_csv("./data/test.csv")

data <- prepare_data_for_ml_tasks(train_orig, test_orig)

train <- data$train
test <- data$test

# creating mlr lightgbm integration -------------------------------------------------------------------------------

makeRLearnerRegr <-  function(cl, package, par.set, par.vals = list(), properties = character(0L), name = cl, short.name = cl, note = "", callees = character(0L)) {
  addClasses(
    makeRLearnerInternal(cl, "regr", package, par.set, par.vals, properties, name, short.name, note, callees),
    c(cl, "RLearnerRegr")
  )
}

makeRLearner.regr.lightgbm <-  function() {
  makeRLearnerRegr(
    cl = "regr.lightgbm",
    package = "lightgbm",
    par.set = makeParamSet(
      makeUntypedLearnerParam("early.stopping.data"),
      makeIntegerLearnerParam("nrounds", lower = 1, default = 100),
      makeDiscreteLearnerParam("metric", values = c("l1", "l2", "l2_root", "quantile", "mape", "huber", "fair")),
      makeDiscreteLearnerParam("obj", values = c("regression_l2", "regression_l1", "huber", "fair", "poisson", "quantile", "mape", "gamma", "tweedie", default = "regression_l2")),
      makeIntegerLearnerParam("verbose", lower = -1, upper = 2, tunable = FALSE, default = 2),
      makeLogicalLearnerParam("record", default = TRUE, tunable = FALSE),
      makeIntegerLearnerParam("eval_freq", lower = 1, tunable = FALSE, requires = quote(verbose > 0)),
      makeUntypedLearnerParam("init_model"),
      makeIntegerLearnerParam("early_stopping_rounds", lower = 1),
      makeDiscreteLearnerParam("boosting", values = c("gbdt", "dart", "rf"), default = "gbdt", requires = quote(boosting != "rf" || bagging_freq > 0 && bagging_fraction < 1 && feature_fraction < 1)),
      makeNumericLearnerParam("learning_rate", lower = 0, upper = 1, default = 0.1),
      makeIntegerLearnerParam("num_leaves", lower = 1, default = 31),
      makeDiscreteLearnerParam("tree_learner", values = c("serial", "feature", "data", "voting"), default = "serial"),
      makeIntegerLearnerParam("num_threads", lower = 1),
      makeDiscreteLearnerParam("device", values = c("cpu", "gpu"), default = "gpu"),
      makeIntegerLearnerParam("max_depth", lower = -1, default = -1),
      makeIntegerLearnerParam("min_data_in_leaf", lower = 1, default = 20),
      makeNumericLearnerParam("min_sum_hessian_in_leaf", lower = 0, default = 1e-3),
      makeNumericLearnerParam("feature_fraction", lower = 0, upper = 1, default = 1),
      makeNumericLearnerParam("bagging_fraction", lower = 0, upper = 1, default = 1),
      makeIntegerLearnerParam("bagging_freq", lower = 0, default = 0),
      makeNumericLearnerParam("lambda_l1", lower = 0, default = 0),
      makeNumericLearnerParam("lambda_l2", lower = 0, default = 0),
      makeNumericLearnerParam("min_split_gain", lower = 0, default = 0),
      makeNumericLearnerParam("drop_rate", lower = 0, upper = 1, default = 0.1, requires = quote(boosting == "dart")),
      makeNumericLearnerParam("skip_drop", lower = 0, upper = 1, default = 0.5, requires = quote(boosting == "dart")),
      makeIntegerLearnerParam("max_drop", lower = 0, default = 50, requires = quote(boosting == "dart")),
      makeLogicalLearnerParam("xgboost_dart_mode", default = FALSE),
      makeIntegerLearnerParam("min_data_per_group", lower = 1, default = 100),
      makeIntegerLearnerParam("max_cat_threshold", lower = 0, default = 32),
      makeNumericLearnerParam("cat_l2", lower = 0, default = 10),
      makeIntegerLearnerParam("max_cat_to_onehot", lower = 0, default = 4)
    ),
    properties = c("numerics", "weights", "featimp", "missings", "factors"),
    name = "Light Gradient Boosting Machine",
    short.name = "lightgbm",
    par.vals = list(obj = "regression_l2"),
    note = ""
  )
}

predictLearner.regr.lightgbm = function(.learner, .model, .newdata, ...) {
  predict(.model$learner.model, as.matrix(.newdata))
}

trainLearner.regr.lightgbm  <-  function(.learner, .task, .subset, .weights = NULL,  ...) {
  f = getTaskDesc(.task)
  data = getTaskData(.task, .subset,target.extra = TRUE)
  lgb.data = lgb.Dataset(as.matrix(data$data), label = data$target)
  lightgbm::lgb.train(
    data = lgb.data,
    objective = "regression",
    # verbosity = 1,
    verbose = 2,
    record = TRUE,
    # device = "gpu",
    ...
  )
}

registerS3method("makeRLearner", "regr.lightgbm", makeRLearner.regr.lightgbm)
registerS3method("trainLearner", "regr.lightgbm", trainLearner.regr.lightgbm)
registerS3method("predictLearner", "regr.lightgbm", predictLearner.regr.lightgbm)

# instantiating mlr -----------------------------------------------------------------------------------------------

library(parallelMap)
parallelStartSocket(cpus = 2)
parallelExport('trainLearner.regr.lightgbm', 'predictLearner.regr.lightgbm', 'lgb.Dataset')

rmse = makeMeasure(
  id = "rmse",
  minimize = TRUE,
  best = 0,
  worst = Inf,
  properties = c("regr", "req.pred", "req.truth"),
  name = "Root mean squared error",
  note = "The RMSE is aggregated as sqrt(mean(rmse.vals.on.test.sets^2)). If you don't want that, you could also use `test.mean`.",
  fun = function(task, model, pred, feats, extra.args) {
    measureRMSE(pred$data$truth, pred$data$response)
  },
  aggr = test.rmse
)

lgb_learner <- makeRLearner.regr.lightgbm()
trainTask <- makeRegrTask(data = data.frame(train), target = 'Purchase')

# control <- makeTuneControlRandom(maxit = 5)
control <- makeTuneControlGrid()
resample_desc <- makeResampleDesc("CV", iters = 4)
lgb_params_set <- makeParamSet(
  makeIntegerParam("nrounds", lower = 55, upper = 60)
)

tryCatch(
  {
    lgb_params_tuning <- tuneParams(
      learner = lgb_learner,
      task = trainTask,
      resampling = resample_desc,
      par.set = lgb_params_set,
      control = control,
      measures = rmse
    )
  },finally = {
    # parallelMap::parallelStop()
    print('Traceback below:')
    print(traceback())
    print('Warnings below:')
    print(warnings())
  }
)
```

**output for multicore (whole output in [this file](https://github.com/mlr-org/mlr/files/2594025/parallel_mode_output.txt)):**
Loading required package: ParamHelpers
-- Attaching packages ---------------------------------------------------------- tidyverse 1.2.1 --
<U+221A> ggplot2 3.1.0     <U+221A> purrr   0.2.5
<U+221A> tibble  1.4.2     <U+221A> dplyr   0.7.7
<U+221A> tidyr   0.8.2     <U+221A> stringr 1.3.1
<U+221A> readr   1.1.1     <U+221A> forcats 0.3.0
-- Conflicts ------------------------------------------------------------- tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
Loading required package: R6

Attaching package: 'lightgbm'

The following object is masked from 'package:dplyr':

    slice

Attaching package: 'BBmisc'

The following objects are masked from 'package:dplyr':

    coalesce, collapse

The following object is masked from 'package:base':

    isFALSE

Parsed with column specification:
cols(
  User_ID = col_integer(),
  Product_ID = col_character(),
  Gender = col_character(),
  Age = col_character(),
  Occupation = col_integer(),
  City_Category = col_character(),
  Stay_In_Current_City_Years = col_character(),
  Marital_Status = col_integer(),
  Product_Category_1 = col_integer(),
  Product_Category_2 = col_integer(),
  Product_Category_3 = col_integer(),
  Purchase = col_integer()
)
Parsed with column specification:
cols(
  User_ID = col_integer(),
  Product_ID = col_character(),
  Gender = col_character(),
  Age = col_character(),
  Occupation = col_integer(),
  City_Category = col_character(),
  Stay_In_Current_City_Years = col_character(),
  Marital_Status = col_integer(),
  Product_Category_1 = col_integer(),
  Product_Category_2 = col_integer(),
  Product_Category_3 = col_integer()
)
Starting parallelization in mode=socket with cpus=2.
Exporting objects to slaves for mode socket: trainLearner.regr.lightgbm,predictLearner.regr.lightgbm,lgb.Dataset
[Tune] Started tuning learner regr.lightgbm for parameter set:
           Type len Def   Constr Req Tunable Trafo
nrounds integer   -   - 55 to 60   -    TRUE     -
With control class: TuneControlGrid
Imputation value: Inf
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 2; elements = 6.
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9262.755429
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9262.170425
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9263.085131
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9262.755429
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9267.863867
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9262.170425
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9263.085131
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9267.863867
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 15
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9262.755429
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9262.170425
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9262.755429
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9262.170425
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 18
[1] "Traceback below:"
No traceback available 
NULL
[1] "Warnings below:"
Warning messages:
1: package 'mlr' was built under R version 3.5.1
2: package 'ParamHelpers' was built under R version 3.5.1
3: package 'tidyverse' was built under R version 3.5.1
4: package 'ggplot2' was built under R version 3.5.1[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8

5: package 'tidyr' was built under R version 3.5.1
6: package 'readr' was built under R version 3.5.1
7: package 'purrr' was built under R version 3.5.1
8: package 'dplyr' was built under R version 3.5.1
9: package 'forcats' was built under R version 3.5.1
10: package 'R6' was built under R version 3.5.1
11: package 'BBmisc' was built under R version 3.5.1
12: package 'bindrcpp' was built under R version 3.5.1
13: package 'parallelMap' was built under R version 3.5.1
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 13
B��d w poleceniu 'unserialize(node$con)':b��d czytania z po��czenia
Wywo�ania: sourceWithProgress ... FUN -> recvData -> recvData.SOCKnode -> unserialize
Dodatkowo: By�o 13 ostrze�enie (u�yj 'warnings()' aby je zobaczy�)
Wykonywanie wstrzymane
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 17
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12

**Output for commented lines (whole output in [this file](https://github.com/mlr-org/mlr/files/2594022/single_core_output.txt)):**
```r
library(parallelMap)
parallelStartSocket(cpus = 2)
parallelExport('trainLearner.regr.lightgbm', 'predictLearner.regr.lightgbm', 'lgb.Dataset')
```

Loading required package: ParamHelpers
-- Attaching packages ---------------------------------------------------------- tidyverse 1.2.1 --
<U+221A> ggplot2 3.1.0     <U+221A> purrr   0.2.5
<U+221A> tibble  1.4.2     <U+221A> dplyr   0.7.7
<U+221A> tidyr   0.8.2     <U+221A> stringr 1.3.1
<U+221A> readr   1.1.1     <U+221A> forcats 0.3.0
-- Conflicts ------------------------------------------------------------- tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
Loading required package: R6

Attaching package: 'lightgbm'

The following object is masked from 'package:dplyr':

    slice

Attaching package: 'BBmisc'

The following objects are masked from 'package:dplyr':

    coalesce, collapse

The following object is masked from 'package:base':

    isFALSE

Parsed with column specification:
cols(
  User_ID = col_integer(),
  Product_ID = col_character(),
  Gender = col_character(),
  Age = col_character(),
  Occupation = col_integer(),
  City_Category = col_character(),
  Stay_In_Current_City_Years = col_character(),
  Marital_Status = col_integer(),
  Product_Category_1 = col_integer(),
  Product_Category_2 = col_integer(),
  Product_Category_3 = col_integer(),
  Purchase = col_integer()
)
Parsed with column specification:
cols(
  User_ID = col_integer(),
  Product_ID = col_character(),
  Gender = col_character(),
  Age = col_character(),
  Occupation = col_integer(),
  City_Category = col_character(),
  Stay_In_Current_City_Years = col_character(),
  Marital_Status = col_integer(),
  Product_Category_1 = col_integer(),
  Product_Category_2 = col_integer(),
  Product_Category_3 = col_integer()
)
[Tune] Started tuning learner regr.lightgbm for parameter set:
           Type len Def   Constr Req Tunable Trafo
nrounds integer   -   - 55 to 60   -    TRUE     -
With control class: TuneControlGrid
Imputation value: Inf
[Tune-x] 1: nrounds=55
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9263.103679
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9272.597160
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[..]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Info] Total Bins 322
[LightGBM] [Info] Number of data: 412551, number of used features: 8
[LightGBM] [Info] Start training from score 9258.360421
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[...]
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 13

**Comment by larskotthoff** [comment]
Thanks for the report -- does the code work without parallelization?

**Comment by matkalinowski** [comment]
Sorry about that- I did not clarified.
It fails in two ways:
-one is when i run it in parallel- then You can see traceback below (and whole output at the end)
-second is when i run it with commented lines (and whole output at the end):

**Comment by matkalinowski** [comment]
So here is the traceback for the parallel case:

> 14: unserialize(node$con)
13: recvData.SOCKnode(con)
12: recvData(con)
11: FUN(X[[i]], ...)
10: lapply(cl[1:jobs], recvResult)
9: staticClusterApply(cl, fun, vlen, argfun)
8: clusterMap(cl = NULL, slaveWrapper, ..., .i = iters, MoreArgs = more.args,
SIMPLIFY = FALSE, USE.NAMES = FALSE)
7: parallelMap(evalOptimizationState, dobs, states, level = level,
more.args = list(learner = learner, task = task, resampling = resampling,
measures = measures, par.set = par.set, bits.to.features = bits.to.features,
control = control, opt.path = opt.path, show.info = show.info,
remove.nas = remove.nas, resample.fun = resample.fun))
6: evalOptimizationStates(learner, task, resampling, measures, par.set,
NULL, control, opt.path, show.info, states, dobs, eols, remove.nas,
resample.fun, "mlr.tuneParams")
5: evalOptimizationStatesTune(learner, task, resampling, measures,
par.set, control, opt.path, show.info, xs, dobs = seq_along(xs),
eols = NA_integer_, remove.nas = TRUE, resample.fun = resample.fun)
4: sel.func(learner, task, resampling, measures, par.set, control,
opt.path, show.info, resample.fun)
3: tuneParams(learner = lgb_learner, task = trainTask, resampling = resample_desc,
par.set = lgb_params_set, control = control, measures = rmse) at #3
2: tryCatchList(expr, classes, parentenv, handlers)
1: tryCatch({
lgb_params_tuning <- tuneParams(learner = lgb_learner, task = trainTask,
resampling = resample_desc, par.set = lgb_params_set,
control = control, measures = rmse)
}, finally = {
print("Traceback below:")
print(traceback())
print("Warnings below:")
print(warnings())
})

I couldn't get a traceback for the case where I comment those lines (basically turining off the parallelization as far as I would expect) but I wouldn't be suprised if it was the same error in two of those situations:
```r
library(parallelMap)
parallelStartSocket(cpus = 2)
parallelExport('trainLearner.regr.lightgbm', 'predictLearner.regr.lightgbm', 'lgb.Dataset')
```

For this data it fails everytime. Can you reproduce it? Do you need any other informations?

**Comment by matkalinowski** [comment]
Here are the most important thing from the logs and [all logs zip](https://github.com/mlr-org/mlr/files/2605722/parallelMap.zip). The values are changing with the log but the form stays the same.

> [Tune-y] 1: rmse.test.rmse=7344.3730013; time: 0.0 min
Error in addOptPathEl.OptPathDF(opt.path, x = x, y = res$y, dob = dob,  : 
  You have to add extras to opt path if the option is enabled.
          used (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 1795631 95.9    3420507 182.7  2631207 140.6
Vcells 3142028 24.0    8388608  64.0  5490144  41.9

**Comment by matkalinowski** [comment]
I have performed some more trials but the situation stays the same. There is no clear reason why this would fail, but I have seen that data size matters, also the picked control type in tuneParams and if I am performing computations on single core there is no error output in cluster logs.

@SteveBronder, @larskotthoff are there any solutions for the error above? Can I give you more informations or perform some more trials you would like to see?

@jakob-r I have seen that in issue #1335 you have mentioned about fixing this kind of error. Does it relates to the situation above?

**Comment by larskotthoff** [comment]
It seems like this is a technical issue that can't be fixed in mlr. What amounts of data are you transferring when you get the error?

**Comment by matkalinowski** [comment]
It failed even for the train size of 362,024 bytes (first 10k rows). While doing computations I still got ~6 GB of space left in RAM.
