### ISSUE TITLE
XgBoost and partial dependence does not work

### ISSUE THREAD

**Issue by XanderHorn** [mlr-org/mlr#2495]
Partial dependence with XgBoost as a learner does not work. See code below:

```r
lrn <- makeLearner("classif.xgboost", predict.type = "prob")

mod <- mlr::train(lrn,iris.task)

pd <- generatePartialDependenceData(mod, input = iris.task)

Error in predict.xgb.Booster(m, newdata = data.matrix(.newdata), ...) : 
  Feature names stored in `object` and `newdata` are different!
```
Any ideas why?

**Comment by pat-s** [comment]
Duplicate of https://github.com/mlr-org/mlr/issues/2408. Can you try the fix proposed there?

**Comment by XanderHorn** [comment]
I tired that solution already but with no luck, also double checked that the features are in the same order as what was described in that solution.
