### ISSUE TITLE
Is it possible to optimize a NumericVector?

### ISSUE THREAD

**Issue by vrodriguezf** [mlr-org/mlr#2499]
All the examples I see deal with unidimensional hyperparameters. I wonder if it is possible to optimize the values of a NumericVector.

Thanks for you great work here!

**Comment by mb706** [comment]
Should be no problem, just use `makeNumericVectorParam` (or other `make***VectorParam` for other types). Be careful that "grid search" for high dimensional search spaces may be very inefficient, so if you are tempted to use `makeTuneControlGrid`, consider using `makeTuneControlRandom/Irace/MBO` instead.

**Comment by berndbischl** [comment]
Correct. Try it out and tell us if you encounter problems.

**Comment by vrodriguezf** [comment]
Thank you! I will take a look at both of them more precisely to see which one is more suitable for me.
