### ISSUE TITLE
Getting error with getDefaultParConfig () with classif.lda

### ISSUE THREAD

**Issue by LGGom** [mlr-org/mlr#2501]
Sorry if it isn't the right place do asking for help!
I'm trying to use mlrHyperopt to tune a LDA model and getting the following error: 
"Error in getDefaultParConfig(learner) :   For the learner classif.lda no default is available."
Can you help about this issue?

**Comment by LGGom** [comment]
Additional information: Already tried other Integrated Learners, and all runs ok!

**Comment by larskotthoff** [comment]
Thanks for the report -- can you post a complete code example that allows to reproduce the problem please?

**Comment by berndbischl** [comment]
you are in the wrong repo

https://github.com/jakob-r/mlrHyperopt

@jakob-r
