### ISSUE TITLE
Cross-validation bug?

### ISSUE THREAD

**Issue by luca-scr** [mlr-org/mlr#2504]
I noticed what it looks like a bug in cross-validation. 
A small reproducible example is the following:

```r
library(mlr)
task <- makeClassifTask(data = iris, target = "Species")
lrn <- makeLearner("classif.knn", k = 3)
mod <- train(lrn, task)
cv <- makeResampleDesc(method = "CV", iters = 4)
```
Here I set `iters = 4` so to have folds with different sizes.
```r
set.seed(123)
resamp <- resample(learner = lrn, task = task, resampling = cv, measures = mmce)
# Resampling: cross-validation
# Measures:             mmce      
# [Resample] iter 1:    0.0789474 
# [Resample] iter 2:    0.0000000 
# [Resample] iter 3:    0.0526316 
# [Resample] iter 4:    0.0270270 
# 
# 
# Aggregated Result: mmce.test.mean=0.0396515
# 
# 
resamp$aggr
# mmce.test.mean 
#     0.03965149 
(err <- resamp$measures.test$mmce)
# [1] 0.07894737 0.00000000 0.05263158 0.02702703
(nfold <- nrow(resamp$measures.test))
# [1] 4
(folds.size <- table(resamp$pred$data$iter))
#  1  2  3  4 
# 38 37 38 37 
with(resamp$pred$data, sum(truth != response))  # number of errors
# [1] 6
with(resamp$pred$data, mean(truth != response)) # mmce = 6/150
# [1] 0.04
mean(err)
# [1] 0.03965149
```
So, mlr seems to compute as aggregated value the average of mmce values. If folds have the same size this is ok, but if folds have different sizes a weighted average with weights equal to folds size should be used.

I haven't checked but I suspect this behaviour is also present for other resampling schemes.

**Comment by berndbischl** [comment]
Thats not a bug, but documented behavior:

?Measure
Description
A measure object encapsulates a function to evaluate the performance of a prediction. [...]

A learner is trained on a training set d1, results in a model m and predicts another set d2 (which may be a different one or the training set) resulting in the prediction. The performance measure can now be defined using all of the information of the original task, the fitted model and the prediction.

?Aggregation 
?aggregation 
Defines who you aggregate these multiple numbers over resampling. Standard is to take the mean. 

-----------------

If you disllike this, it is changeable. 
?aggreagtions

test.join
Performance measure on joined test sets. This is especially useful for small sample sizes where unbalanced group sizes have a significant impact on the aggregation, especially for cross-validation test.join might make sense now. For the repeated CV, the performance is calculated on each repetition and then aggregated with the arithmetic mean.

See, even talks about your usecase / example :)

Simply set it in the aggregation of the meaure
mycv = setAggregation(cv10, test.join)
