### ISSUE TITLE
Cannot give an opt path for iteration 0 in makeFeatSelControlGA()

### ISSUE THREAD

**Issue by sycoforbidden** [mlr-org/mlr#2514]
Given a specific task with n feats, I want to use a custom bit matrix for iteration 0 of the genetic algorithm. Is there any way I can achieve this without using any third party function?

Is there any way you can add that feature if it isn't yet implemented?

I'm asking since I start from a dataset with 700 features, and the number of features (bits) for iteration 0 is always centered around the mean, while i actually want to use a reduced number of features from the get-go without having to externally split the task.

**Comment by larskotthoff** [comment]
This really sounds like something where you should just reduce the number of features in the task before starting the feature selection. Is there a specific reason you don't want to do that?

**Comment by sycoforbidden** [comment]
I want to test the GA algorithm as THE solution for feature selection. I know i could use some feature filtering, but i want to know how effective your GA is at converging to a solution. Right now, since the number of bits in iteration 0 is always centered around 350 features, the algorithm can't proceed to a much lower number of max features (eg. 50), as it just gets stuck indefinitely in iteration 1.

**Comment by larskotthoff** [comment]
It seems to me that a GA is not suitable for such a large number of features as you have because of the computational effort, as you've discovered. Therefore it's definitely not THE solution for feature selection.

**Comment by sycoforbidden** [comment]
What's the point of having max.features in the GA then? Shouldn't it at least apply max.features in iteration 0 so that the GA has a valid starting point?

**Comment by larskotthoff** [comment]
`max.features` really only limits the number of features returned at the end of the feature selection.

**Comment by sycoforbidden** [comment]
> `max.features` really only limits the number of features returned at the end of the feature selection.

hmm... Is there any way i can see the underlying GA code? Because that should be the reason as to why it hangs when setting the number of max.features too low.

**Comment by larskotthoff** [comment]
Sure, the code is here: https://github.com/mlr-org/mlr/blob/master/R/selectFeaturesGA.R

**Comment by sycoforbidden** [comment]
This should be the reason for the current problem:

```r 
# sample 2 random parents, CX, mutate --> 1 kid
# (repeat in a loop if max.features not satisfied)
generateKid = function(featmat, control) {
  parents = sample(seq_row(featmat), 2L, replace = TRUE)
  while (TRUE) {
    kid = crossover(featmat[parents[1L], ], featmat[parents[2L], ], control$extra.args$crossover.rate)
    kid = mutateBits(kid, control$extra.args$mutation.rate)
    if (is.na(control$max.features) || sum(kid) <= control$max.features)
      break
  }
  return(kid)
}
```

It will get stuck if there's a small number of max.features in iteration 0, since finding for eg. 50 features from a bunch of sets of 300+ features is like finding a needle in a hay stack.

**Comment by larskotthoff** [comment]
Clone the repo and edit away. You can find more information in the developer instructions: https://github.com/mlr-org/mlr/wiki/Developer-Instructions

**Comment by mb706** [comment]
> Clone the repo and edit away

If all you want to do is a few experiments it might be an option to just copy the content of https://github.com/mlr-org/mlr/blob/master/R/selectFeaturesGA.R into a file, put `mlr:::` in front of some of the functions (`evalOptimizationStatesFeatSel` and `makeFeatSelResultFromOptPath`), and `source()` the file.
