### ISSUE TITLE
no need to consder train in getting hyper-parameter in predict.WrappedModel?

### ISSUE THREAD

**Issue by smilesun** [mlr-org/mlr#2527]
https://github.com/mlr-org/mlr/blob/02a9969a538beeca84572f1ef17fb4be64eb3478/R/predict.R#L106
in the current implementation, 
`pars = c(pars, getHyperPars(learner, c("predict", "both")))`

`getHyperPars(learner, c("predict", "both"))` will return NULL if there is only "train" in learner.

**Comment by mb706** [comment]
I don't see the problem. There are parameters that are relevant during "train", some that are relevant during "predict", and some that are relevant during "both". This gets the ones that are relevant during "predict" and "both"; if there are none, getHyperPars returns NULL, but c(pars, NULL) is just pars, as it should be.
