### ISSUE TITLE
Self -made filtering method doesn't work with parallization in mlr

### ISSUE THREAD

**Issue by purod** [mlr-org/mlr#2528]
I made a new filtering method by myself and try work with multiple cores. It doesn't work even I export it to slaves before using. 

## my filter
```r
cutoff = makeFilter(
  name = "cutoff",
  desc = "determine the optical number of features included in the final model",
  pkg = character(0),
  supported.tasks = c("classif", "regr", "surv"),
  supported.features = c("numerics", "factors", "ordered"),
  fun = function(task, nselect, decreasing = TRUE, ...) {
    
    feature.name = getTaskFeatureNames(surv.task)
    feature.value = c(length(feature.name):1)
    names(feature.value) = feature.name
  
    feature.value
  }

)
```
## code I am trying to run with multiple cores
```r
parallelStartSocket(40)
parallelExport("cutoff")
lrn = makeFilterWrapper(makeLearner("surv.gbm"), fw.method = "cutoff")
lrn1 = makeTuneWrapper(lrn, 
                      #resampling = makeFixedHoldoutInstance(train.inds = 1:50, test.inds = 1:50, size = 50),
                      makeResampleDesc("RepCV",folds=3L,reps=20L),
                      par.set = makeParamSet(
                        makeDiscreteParam("n.trees", values = c(500,1000,1500)),
                        makeDiscreteParam("shrinkage", values = c(0.1,0.01)),
                        makeDiscreteParam("interaction.depth", values = c(1)),
                        makeDiscreteParam("n.minobsinnode", values = c(3,6)),
                        makeDiscreteParam("bag.fraction", values = c(0.7,0.8,0.9)),
                        makeDiscreteParam("fw.abs", values = c(8:12))
                      ), 
                      control = makeTuneControlGrid(), 
                      show.info = T)

r = resample(lrn1, surv.task, 
             resampling = makeResampleDesc("RepCV",folds=3L,reps=10L),
             #extract=getTuneResult, 
             models = T)
parallelStop()
```

**Comment by mb706** [comment]
The problem is that the `makeFilter` function registers the custom filter in the `mlr:::.FilterRegister` variable, which doesn't get exported to the worker threads; using `parallelExport` doesn't help here, because the `cutoff` variable is actually never used.

A workaround might be to put the `makeFilter()` call in a seperate file `filter.R` and then call `parallelSource("filter.R")` before running the resampling.

**Comment by purod** [comment]
@mb706  It works with parallelSource("filter.R"). One needs to load required libraries used in filter.R. For example, we need to load library("mlr"), or makeFilter would not be found. Another less skilled way is define r as a new function and use mclapply to repeat r for many times. mb706's suggestion is better.

**Comment by mb706** [comment]
> One needs to load required libraries used in filter.R.

Hadn't thought about that. `parallelLibrary("mlr")` etc. would probably work here, or just putting the `library()` call at the head of `filter.R`.

**Comment by purod** [comment]
parallelLibrary("mlr") also works.
