### ISSUE TITLE
Survival analysis with time-dependent variables

### ISSUE THREAD

**Issue by annette987** [mlr-org/mlr#2529]
I have posted on StackOverflow (https://stackoverflow.com/questions/54357172/mlr-survival-analysis-using-interval-censored-data) but not had a response, so thought I would ask my question here, even though it is a "How can this be done?".

Basically I would like to be able to use the Cox model with time-dependent variables in mlr. Reading the documentation it sounds like it might be possible:
`For interval censored data the two target columns must be specified in the "interval2"
format (see survival::Surv()).`

I have read the documentation for Surv() about the "interval2" format, which says that right-censored data can be represented as the interval (a, infinity). However,  I am not clear on how to use the "interval2" format with mlr, as makeSurvTask() only accepts a target with 2 columns. What do I pass as those 2 columns? Is there an example of this anywhere?

The documentation for Surv() also says: 
`Presently, the only methods allowing interval censored data are the parametric models computed by
survreg and survival curves computed by survfit; for both of these, the distinction between open
and closed intervals is unimportant. `
So does this mean that interval censored data cannot be used with function survival::coxph() after all?

**Comment by adibender** [comment]
First, I think, you need to be clear about what you are actually trying to do. Fitting an extended cox model with time-dependent covariates (using the start/stop extension of the data) has nothing to do with left or interval censoring.

**Comment by annette987** [comment]
Thanks for your advice. I have updated my SO question with code and error message. Can you help further?

**Comment by adibender** [comment]
Great. This type of model is currently not supported in MLR, which is also clearly stated in the help page of `makeSurvTask` (target must have length 2). 

In principle, there is no reason not to support it, but i think it would require some effort to fit it in the general framework. For example, multiple observations (rows) belong to the same individual/id, which has consequences for cross-validation, etc. 

You should post the code of your example from SO here and ask maintainers if they plan to include the possibility of start/stop notation. Essentially, this is a feature request.

**Comment by annette987** [comment]
Further to the comment above, do you plan at any stage to extend mlr to be able to use time-dependent variables with the Cox model? I would like to request this feature please. Below is an example of how this would be used, with 3 target variables being passed to makeSurvTask. 
(I used reprex for the first time, so I'm not sure if I was supposed to do more than cut and paste from the viewer in RStudio. Sorry I am fairly new to Github and SO!)
```

library(survival)
library(mlr)
data(pbc)

temp <- subset(pbc, id <= 312, select=c(id:sex, stage)) # baseline
pbc2 <- tmerge(temp, temp, id=id, death = event(time, status)) #set range
pbc2 <- tmerge(pbc2, pbcseq, id=id, ascites = tdc(day, ascites),
               bili = tdc(day, bili), albumin = tdc(day, albumin),
               protime = tdc(day, protime), alk.phos = tdc(day, alk.phos))

pbc.task <- makeSurvTask(data = pbc2, target = c("tstart", "tstop", "status"))
#> Error in makeSurvTask(data = pbc2, target = c("tstart", "tstop", "status")): Assertion on 'target' failed: Must have length 2, but has length 3.
cox.lrn <- makeLearner(cl="surv.coxph", predict.type="response")
mod = train(cox.lrn, pbc.task)
#> Error in checkClass(x, classes, ordered, null.ok): object 'pbc.task' not found
```
