### ISSUE TITLE
Multi criteria tuning as inner resampling

### ISSUE THREAD

**Issue by szapiszapo** [mlr-org/mlr#2539]
Hi All,

Am I correct in stating that mlr currently does not support multi criteria tuning as inner resampling loop in a nested resampling strategy?

I currently run the inner & outer resampling loops independently, i.e. tuneParamsMultiCrit on a given train set then resample each Pareto optimal solution with test set as fixed holdout instance then repeat the whole process n times for different train/test pairs.

I am just wondering firstly if I do things correctly and secondly if there is a more elegant way to do things, the way a "makeTuneMultiCritWrapper" object probably would.

Thanks a lot!

**Comment by jakob-r** [comment]
Please do not cross-post. [Here](https://stackoverflow.com/questions/54554701/multi-criteria-tuning-as-inner-resampling-loop) is the same question on stackoverflow. 

Also closing this issue because I don't see that this will be implemented in mlr. Especially as there is no standard procedure.
