### ISSUE TITLE
Platt scaling for Liblinear SVM classification

### ISSUE THREAD

**Issue by BTopcuoglu** [mlr-org/mlr#2540]
Would there be any interest in implementing Platt scaling to Liblinear SVM models to get predicted probabilities? 

I've been trying and failing to do this for ```RLearner_classif_LiblineaRL1L2SVC.R``` specifically.

**Comment by Prometheus77** [comment]
Generally, implementing Platt scaling in mlr is as simple as creating a stacked learner with a base learner that predicts probabilities and a logreg as a super learner. However, LiblineaR doesn't support probability prediction. Other SVMs (e.g. e1071) do. Here's a simple example of creating an SVM and applying Platt scaling via stacking:

```
svm <- makeLearner("classif.svm", predict.type = "prob")
svm_platt <- makeStackedLearner(base.learners = list(svm), 
                                super.learner = "classif.logreg", 
                                predict.type = "prob")
resample(svm, statlog.task, cv5, auc)
resample(svm_platt, statlog.task, cv5, auc)
```

**Comment by BTopcuoglu** [comment]
Thanks, @Prometheus77 for your explanation. That is a very neat way of creating a stacked model. Unfortunately, I can't use e1071 or kernlab packages.

e1071 and kernlab SVMs provide prob predictions however they don't support L1 Regularized Linear SVMs like LiblineaR does, which is why I wanted to use LiblineaR for my analyses. 

I tried to figure out a way to implement L1-reg to already existing kernlab/e1071 packages but failed :(.
