### ISSUE TITLE
How to find learner's parameters' documentation?

### ISSUE THREAD

**Issue by AlexEngelhardt** [mlr-org/mlr#2555]
Hi yall,

I have a question concerning explorative analyses.

I'd like to run an EM clustering algorithm on a data set. My first step is to call

```r
listLearners('cluster')

#                   class                                name    short.name    package    type
# 1        cluster.cmeans            Fuzzy C-Means Clustering        cmeans e1071,clue cluster
# 2        cluster.Cobweb         Cobweb Clustering Algorithm        cobweb      RWeka cluster
# 3        cluster.dbscan                   DBScan Clustering        dbscan        fpc cluster
# 4            cluster.EM Expectation-Maximization Clustering            em      RWeka cluster
# 5 cluster.FarthestFirst  FarthestFirst Clustering Algorithm farthestfirst      RWeka cluster
# 6       cluster.kkmeans                      Kernel K-Means       kkmeans    kernlab cluster
# ... (#rows: 9, #cols: 5)
```

This shows me a list of algorithms I could use. Now I decide to use `cluster.EM`, and need to find out which parameters I have to specify/tune:

```r
getLearnerParamSet('cluster.EM')

#                      Type len   Def       Constr Req Tunable Trafo
# I                 integer   -   100     1 to Inf   -    TRUE     -
# ll-cv             numeric   - 1e-06 1e-06 to Inf   -    TRUE     -
# ll-iter           numeric   - 1e-06 1e-06 to Inf   -    TRUE     -
# M                 numeric   - 1e-06 1e-06 to Inf   -    TRUE     -
# max               integer   -    -1    -1 to Inf   -    TRUE     -
# N                 integer   -    -1    -1 to Inf   -    TRUE     -
# num-slots         integer   -     1     1 to Inf   -    TRUE     -
# S                 integer   -   100     0 to Inf   -    TRUE     -
# X                 integer   -    10     1 to Inf   -    TRUE     -
# K                 integer   -    10     1 to Inf   -    TRUE     -
# V                 logical   - FALSE            -   -   FALSE     -
# output-debug-info logical   - FALSE            -   -   FALSE     -
```

Now, how/where do I find out what each of these parameters mean? The algorithm is not implemented in `mlr`, but how do I know which function in which package to read?

**Comment by larskotthoff** [comment]
The documentation of the learner usually gives you information on what the parameters mean (the names are the same as mlr uses) -- that's the documentation of the actual learner from the package shown in the output of `listLearner()`.

In some cases, there may be no/little documentation in the documentation of the learner. Then things may be documented in the comments in the implementation of the mlr wrapper for the learner, or the note for the learner in mlr.

**Comment by ja-thomas** [comment]
You can use `helpLearner()` and `helpLearnerParam()`

**Comment by berndbischl** [comment]
All correct. And then you need to read that help page to understand the semantics of the param.

Or get angry when they are not precisely explained
