### ISSUE TITLE
Error when imputing missing values in custom preprocessing wrapper

### ISSUE THREAD

**Issue by SLG1988** [mlr-org/mlr#2556]
I'm having trouble when imputing missing values in a custom preprocessing wrapper. Even after imputing, checkLearnerBeforeTrain still throws an error related to missing values and my learner not supporting those. My specific usecase is that I like makePreprocWrapperCaret, however I would also like to do some extra stuff when preprocessing (for example impute missing values for features of type factor).

When imputing with the Caret preprocessing wrapper I run into no trouble:

``` r

suppressPackageStartupMessages({
  library(mlr)
  library(tidyverse)
})

data(BostonHousing, package = "mlbench")

BostonHousing <- BostonHousing %>%
  dplyr::select_if(is.numeric)

BostonHousing[c(8, 43:146, 331), 'age'] = NA_real_

BostonHousing[c(8, 113:146, 331), 'dis'] = NA_real_

regr.task = makeRegrTask(data = BostonHousing, target = "medv")

lrn = makePreprocWrapperCaret("regr.cvglmnet", ppc.medianImpute = TRUE)

rdesc = makeResampleDesc(method = 'CV',
                         iters = 3)
result = resample(learner = lrn,
                  task = regr.task,
                  resampling = rdesc)
#> Resampling: cross-validation
#> Measures:             mse
#> [Resample] iter 1:    32.7820332
#> [Resample] iter 2:    32.2795288
#> [Resample] iter 3:    25.4448302
#> 
#> Aggregated Result: mse.test.mean=30.1687974
#> 
```

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

However, when trying to implement the same Caret imputation in a custom preprocessing wrapper an error is thrown:

``` r

suppressPackageStartupMessages({
  library(tidyverse)
  library(caret)
  library(mlr)
})

data(BostonHousing, package = "mlbench")

BostonHousing <- BostonHousing %>%
  dplyr::select_if(is.numeric)

BostonHousing[c(8, 43:146, 331), 'age'] = NA_real_

BostonHousing[c(8, 113:146, 331), 'dis'] = NA_real_

regr.task = makeRegrTask(data = BostonHousing, target = "medv")

trainfun = function(data, target, args = list(medianImpute)) {
  
  cns <- colnames(data)
  work.cols <- setdiff(cns, target)
  
  x = data[, work.cols, drop = FALSE]
  
  mod = caret::preProcess(x, method = c('medianImpute'))
  
  x = predict(mod, x)
  
  x = cbind.data.frame(x, data[, setdiff(cns, work.cols), drop = FALSE])
  
  control = list(caret_parms = mod)
  
  return(list(data = x, control = control))
}

predictfun = function(data, target, args, control) {
  
  data.frame(predict(control$caret_parms, data))
  
}

lrn = makePreprocWrapper('regr.cvglmnet', train = trainfun, predict = predictfun,
                         par.vals = list(medianImpute = TRUE))

rdesc = makeResampleDesc(method = 'CV',
                         iters = 3)

result = resample(learner = lrn,
                  task = regr.task,
                  resampling = rdesc)
#> Error in checkLearnerBeforeTrain(task, learner, weights): Task 'BostonHousing' has missing values in 'age, dis', but learner 'regr.cvglmnet.preproc' does not support that!
```

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

How can I fix this?

**Comment by larskotthoff** [comment]
`mlr` determines whether a learner supports missing values through the `missings` property. The caret preprocessing wrapper sets this property, see https://github.com/mlr-org/mlr/blob/master/R/PreprocWrapperCaret.R#L102 -- if you want to support missing values in a custom learner, you need to set this property as well.

For this, you'll probably need to create a custom learner, see [the tutorial](https://mlr.mlr-org.com/articles/tutorial/create_learner.html).

**Comment by pat-s** [comment]
I assume Lars answer solved your problem since there was no response in weeks. Closing here.
