### ISSUE TITLE
resampling with `on.learner.error = "warning"` fails for chained model under some cndtns

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#2557]
Many wrapper learners, e.g. `ImputeWrapper` or `CPO` learners, perform some processing on the data in the `trainLearner` function and then call `makeChainModel(train(...), ...)` to create a `ChainModel` object which will then be packaged inside a `BaseWrapperModel`. If the `train(...)` part inside the `trainLearner` function fails when `on.learner.error` is `"warning"` or `"quiet"`, then everything works correctly: `isFailureModel` on the resulting object reports `TRUE` because the model is a `BaseWrapperModel` that contains a `ChainModel` (`$learner.model`) that contains a `FailureModel` (`$next.model`). However, if the part before `makeChainModel` fails, then the resulting object is a `BaseWrapperModel` that does *not* contain a `ChainModel` but only a `character(1)` (i.e. the error message). `isFailureModel.BaseWrapperModel` then tries to get the `$next.model` slot of this atomic value and fails.

This can be triggered by using the `imputeHist()` function with only one data row in an `imputeWrapper` function: the `imputeHist()` part fails, and the resulting object triggers an error when `isFailureModel` is called, inside the `resample()` call here.

```r
> configureMlr(on.learner.error="warn")
> tsk <- makeClassifTask("t", data.frame(x = c("x", "y"), a = c(NA, 1)), "x")
> lrn <- makeImputeWrapper(makeLearner("classif.logreg"), classes = list(numeric = imputeHist()))
> resample(lrn, tsk, cv2)
Resampling: cross-validation
Measures:             mmce      
Warning in train(learner, task, subset = train.i, weights = weights[train.i]) :
  Could not train learner classif.logreg.imputed: Error in (function (data, target, col, breaks, use.mids)  : 
  All values missing. Unable to impute with Hist.

Error: $ operator is invalid for atomic vectors
```

**Comment by pat-s** [comment]
The description reads "somewhat" complicated :smile: 

Did you solve the issue in MBO already with the referenced commit? Or does it still apply?

**Comment by mb706** [comment]
It is a bug in mlr. The CPO commit is just a workaround, and e.g. ImputeWrapper (and probably other wrappers) are still affected.
