### ISSUE TITLE
surv.coxph: Error in names(name.vars) <- names(formula)[-1] 

### ISSUE THREAD

**Issue by edvbb** [mlr-org/mlr#2567]
For bug reports, please respect the following guidelines and check the boxes accordingly.
Please include your source code using tripple backticks ` like this:

I try to use surv.coxph. When I use `pec` to predict probs I get
```r
probs = pec::predictSurvProb(surva$learner.model, newdata =newdudes, times = timepoints)
Error in coxModelFrame.coxph(object) : invalid object 
set x=TRUE in the call to coxph 
```
Ok. I set x=TRUE
`surv_param <- makeParamSet(
  makeDiscreteParam("ties",  values = c('efron','breslow','exact')),
  makeIntegerParam("iter.max", lower = 1, upper = 150),
  makeIntegerParam("outer.max", lower = 1, upper = 50),
  makeLogicalParam('x')
)`

Then I try again 
```
probs = pec::predictSurvProb(surva$learner.model, newdata =newdudes, times = timepoints)

Error in names(name.vars) <- names(formula)[-1] : 
  'names' attribute [3] must be the same length as the vector [2]
```
I can use origin dataset instead newdudes but the result is the same
How to fix it, please

**Comment by larskotthoff** [comment]
Can you post a complete example that allows to reproduce the problem please?
