### ISSUE TITLE
mcp measure with negative value!

### ISSUE THREAD

**Issue by Doaa-MH** [mlr-org/mlr#2573]
Good day,
I am using mlr in my work and when I tried the following the mcp value was negative in the first iteration of the cross validation, what does it mean and is it acceptable?
```r
costsens.task = makeCostSensTask(id = "CS", data = df, cost = cost)
costsens.task
rdesc = makeResampleDesc("CV", iters = 2L)

lrn = makeLearner("classif.xgboost", predict.type = "prob")
lrn = makeCostSensClassifWrapper(lrn)
lrn
r = resample(lrn, costsens.task, resampling = rdesc)
r
``

The results of the resample function are:
Resampling: cross-validation
Measures:             mcp       
[Resample] iter 1:    -0.0005181
[Resample] iter 2:    0.0005209 

Aggregated Result: mcp.test.mean=0.0000014

PS: As the definition of the mcp
> 
Average difference between costs of oracle and model prediction
> 
and its minimize = TRUE so a negative value will affect its test.mean.

**Comment by larskotthoff** [comment]
Sounds like this might be a numerical accuracy issue. Can you post a complete example that allows to reproduce the problem please?

**Comment by Doaa-MH** [comment]
What is missing from previous post is the definition of df an cost, which are as follow:
``
df <- as.data.frame(fread("creditcard.csv"))

ca<- as.vector(matrix(5,nrow(df)))
cost <- cbind(df$Class*df$Amount,ca)

colnames(cost) = levels(as.factor(c("C0","C1")))
rownames(cost) = rownames(df)
``
I am using the credit card data set: [https://www.kaggle.com/mlg-ulb/creditcardfraud](url)

**Comment by pat-s** [comment]
Please provide a reprex that clearly shows the problem.
