### ISSUE TITLE
Bug in predictions due to recent change in data.table

### ISSUE THREAD

**Issue by danielhorn** [mlr-org/mlr#2578]
`data.table` changed its behaviour wrt. rbind by name/position. Recent version issue a message about this, e.g. if you run this code:
```r
set.seed(123)
lrn = makeLearner("classif.svm", predict.type = "prob")
task = iris.task
ctrl = makeTuneControlRandom(maxit = 2)
ps = makeParamSet(makeNumericParam("cost", lower = 0.01, upper = 0.1))
lrn = makeTuneWrapper(lrn, cv3, par.set = ps, control = ctrl)
resample(lrn, task, cv3)
```

This leads to errors down the analysis, where probabilites are not joint corretly together in prediction objects. I.e., probabiltites for the first class where rbinded to the column for the 2nd class, and vice versa. See https://github.com/mlr-org/mlr/blob/3b52b1213ee26fbe53ce9a6461510bf32f25b807/R/ResamplePrediction.R#L26.

To turn the message into an error, you can set the option `options(datatable.rbindlist.check="error")`.

**Comment by mllg** [comment]
Here is a snippet which demonstrates that the probabilities are incorrectly aggregated:

```r
set.seed(123)
lrn = makeLearner("classif.svm", predict.type = "prob")
task = sonar.task

rr = resample(lrn, task, cv3)

pred = rr$pred
calculateConfusionMatrix(pred)
pred = setThreshold(pred, 0.5)
calculateConfusionMatrix(pred)
```
