### ISSUE TITLE
broken tests due to R 3.6.0

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2580]
R 3.6.0 introduced (fixed) `sample()` behavior on large populations.

The old behavior can be restored by using `sample(sample.kind = "Rounding")`.

- [x] `@test_classif_mda.R#43` 
 -> Different outcomes due to RNG change
 - Here we test the outcome of a `mda` resample object against the tune performances of an `e1071::tune()` call? I do not really understand the purpose of this test.

- [x] `@test_base_benchmark.R#141`

  - `getBMRFeatSelResults()` -> `getBMROptResults()` -> `getBMRObjects()`
  - Here the test checks for an absolute row number which is now 4 less than before (57 <-> 61). I am not sure if we need to take any action here or if this check can simply be removed. The changes in `n` may depend on the new RNG Kind and affect the `fw.perc` argument of the FeatSel learners that are checked here. Changes are expected and checking for an absolute number of selected features does maybe not make sense here?

@berndbischl @mllg Could you have look here? This is urgent. 
Corresponding Travis build: https://travis-ci.org/mlr-org/mlr/builds/527324504

**Comment by mllg** [comment]
mda fixed via 9b72ab3.

**Comment by mllg** [comment]
benchmark fixed via 50833974e3b8c84f2117903cb9234d7f75aec0e8.

**Comment by pat-s** [comment]
remaining ones fixed by c13c2b0f704a32d00800b01d297c0bd195a0e1d2.
