### ISSUE TITLE
max.depth parameter in ranger

### ISSUE THREAD

**Issue by l47y** [mlr-org/mlr#2581]
First of all, thanks for this great package with all of the useful ML infrastructure. I am heavily using it in my work. 
I wondered what is the reason why the max.depth parameter in learners using the *ranger* package in the backend is missing. I do some survival analysis and want to compare my current results obtained by ranger itself with some other algorithms (for example randomForestSRC). I realized that I cant set the max.depth parameter of ranger learners via mlr. I am using:
- ranger_0.11.2     
- mlr_2.13.9000

Thanks for the help in advance!

**Comment by larskotthoff** [comment]
I think the reason is simply that this parameter wasn't there when we changed the implementation the last time. Pull request to add it welcome :)

**Comment by l47y** [comment]
Thanks for the fast answer :-) 
I will soon make a pull request!

**Comment by pat-s** [comment]
@l47y do you still want to contribute here?

**Comment by pat-s** [comment]
Closing due to no response, feel free to reply here if you still want to contribute.
