### ISSUE TITLE
regr.svm: constant df column warning is hidden, but it is very important

### ISSUE THREAD

**Issue by GabrieleBrambilla** [mlr-org/mlr#2582]
## Description

**e1071**
If I use a dataframe with some constant columns I get this warning message:

Warning message:
In svm.default(x = as.matrix(db[, -1]), y = db[, 1], type = "eps-regression",  :
  Variable(s) ‘july’ and ‘august’ and ‘september’ and ‘october’ and ‘november’ and ‘december’ and ‘Christmas_week’ and ‘ferragosto_week’ constant. Cannot scale data.

**mlr**
If I create a task and then train the model I don't get any warning. However, trying to use such model for predictions result in producing a constant value series!!!
It took a while to find out why this was happening....

Why are these warnings not returned from mlr?

**Comment by pat-s** [comment]
Can you please provide a reproducible example? Usually _mlr_ does not hide warnings by default.

**Comment by GabrieleBrambilla** [comment]
sorry, my bad. It shows up, IDK why I did not see it.
