### ISSUE TITLE
Specify dependencies between tuning parameters

### ISSUE THREAD

**Issue by lumatt** [mlr-org/mlr#2583]
Is it possible to create ParamSet with additional dependencies (apart from using 'require' which doesn't seem to help in this example)? I wanted to tune double-wrapped classifier: 
base_learner -> undersample -> weighted and was curious if one can specify range for weights that is dependent on usw.rate. 

For example: let's assume I have dataset with 1:10 imbalance ratio and want to make it more or less balanced (ratio between 1:1.05 and 1:0,95). If I have only one wrapper I can type either:

makeParamSet(makeIntegerParam("usw.rate", 
lower =  1.05 * minority_class_perc / (1- minority_class_perc), 
upper = 0.95 * minority_class_perc / (1- minority_class_perc)))

or

makeParamSet(makeIntegerParam("wcw.weight", 
lower =  0.95 * (1- minority_class_perc) / minority_class_perc, 
upper = 1.05 * (1- minority_class_perc) / minority_class_perc))

Is there a way to specify both ranges for double-wrapped learner to preserve effective balance ratio in a given range?

**Comment by berndbischl** [comment]
the question seems to be why you want to do that? weighting and sampling are nearly equivalent for this, and weighting seems to be preferable if it is possible for the learner? 

ok the undersampling might speed things up a bit, but thats about it? why do you want to do both?

i dont think you can currently make the one param (e.g. wcw.weight)  depend on the value of another (usw.rate), or vice versa.

not without touching mlr code. in mlr3 that should be possible, but not here, sorry.
