### ISSUE TITLE
Learners not working for one feature tasks

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#2592]
The following learners do not work for tasks with only one feature:

## classif
- [ ] classif.boosting Bug has to be removed in adabag
- [ ] classif.cforest + regr.cforest: fraction of 0.000000 is too small (only travis?)
- [ ] classif.cvglmnet + regr.cvglmnet:  Does not claim to work for 1d problems
- [ ] classif.dbnDNN
- [ ] classif.evtree + regr.evtree
- [ ] regr.frbs
- [ ] classif.geoDA
- [ ] regr.gbm: At least gives meaningfull error
- [ ] regr.glmnet
- [ ] regr.laGP
- [ ] classif.linDA
- [x] classif.lqa (solved, bc .not im mlr anymore)
- [ ] classif.lvq1
- [ ] classif.mda (maybe only subset error)
- [ ] regr.nodeHarvest: Error in ZRULES[[1]] : subscript out of bounds
- [ ] classif.pamr (maybe only subset error)
- [ ] classif.plsdaCaret (error still not fixed in caret)
- [ ] classif.quaDA: Bug has to be removed in DiscriMiner::quaDA
- [ ] classif.rknn: Bug has to be removed in rknn::rknn
- [ ] classif.rotationForest (gives some error, no one would use it for 1d anyway)
- [ ] classif.rrlda error eccours in the learner.
- [ ] regr.slim

(Related to PR #2378)

**Comment by larskotthoff** [comment]
Maybe the best solution here is to have a one-class wrapper that checks if only one class is present, if so always "predicts" it, otherwise runs the wrapped learner?

**Comment by jakob-r** [comment]
Are you confusing this Issue with [this](https://stackoverflow.com/questions/56341159/mlr-resampling-creates-oneclass-problems-for-multilabel-classification) SO question? Or am I confused? :)

These learners in this PR do not work on tasks with only one x column.

**Comment by larskotthoff** [comment]
Ah sorry, yes, confused by that.

**Comment by pat-s** [comment]
Good to have this as a reference here but we won't put time into this for {mlr} as this does not really have any influence in a real-world example.
