### ISSUE TITLE
Plotting MultiClass AUCs

### ISSUE THREAD

**Issue by abtresearch** [mlr-org/mlr#2596]
Apologies if this has already been established elsewhere, but I was curious if there was any way to plot the AUCs derived from multiclass models. 

Here's an example of one of the methods I've tried so far:

```r
test_predict <- predict(xg_multi_model, testtask)
test_perf <- performance(test_predict, measures = multiclass.au1p)

Pls_work <- generateThreshVsPerfData(test_perf, measures = list(fpr, tpr, mmce))
```

Edit: I managed to solve it myself using the package multiROC.

**Comment by YichaoCaiDBS** [comment]
Sorry to revive this issue. I am also trying to plot ROC curves for multi-class classification.

Could you share some testing codes about how you generate the plot using multiROC? It seems that multiROC does not support the au1p calculation. (https://github.com/WandeRum/multiROC)

Big thanks in advance!

**Comment by abtresearch** [comment]
I ended up solving it with the following code. Full disclosure though, it's likely not the most elegant solution and parts of my code could be better optimized. Hopefully it'll give you a good starting place in any case

`
#This code is project specific, but here I was predicting 4 binary classes with XGBoost. You'll need to adjust for your own number of classes.
#prediction.data is referring to the predict() function in mlr
#e.g. testpredict.xg <- predict(mlrmodel, testtask)

library("ggplot2")

MultiAUC <- function( prediction.data=NULL ){
  
  AUCframe = prediction.data$data
  
  names(AUCframe)[names(AUCframe) == "prob.0"] <- "S0_pred_XG"
  names(AUCframe)[names(AUCframe) == "prob.1"] <- "S1_pred_XG"
  names(AUCframe)[names(AUCframe) == "prob.2"] <- "S2_pred_XG"
  names(AUCframe)[names(AUCframe) == "prob.3"] <- "S3_pred_XG"
  
  AUCframe$truth = as.numeric(AUCframe$truth)
  
  AUCframe$S1_true = NA
  AUCframe$S1_true[AUCframe$truth == 1] <- 1
  AUCframe$S1_true[AUCframe$truth > 1] <- 0
  
  AUCframe$S2_true = NA
  AUCframe$S2_true[AUCframe$truth == 2] <- 1
  AUCframe$S2_true[AUCframe$truth > 2 ] <- 0
  AUCframe$S2_true[AUCframe$truth < 2 ] <- 0
  
  AUCframe$S3_true = NA
  AUCframe$S3_true[AUCframe$truth == 3] <- 1
  AUCframe$S3_true[AUCframe$truth > 3] <- 0
  AUCframe$S3_true[AUCframe$truth < 3] <- 0
  
  AUCframe$S4_true = NA
  AUCframe$S4_true[AUCframe$truth == 4] <- 1
  AUCframe$S4_true[AUCframe$truth < 4 ] <- 0
  
  AUCprob = AUCframe[c(3:6, 8:11)]
  
  #make a direct response one
  
  AUCresp = AUCframe[c(2,7:11)]
  AUCresp$response = as.numeric(AUCresp$response)
  
  AUCresp$S1_pred_XG = NA
  AUCresp$S1_pred_XG[AUCresp$response == 1] <- 1
  AUCresp$S1_pred_XG[AUCresp$response > 1] <- 0
  
  AUCresp$S2_pred_XG = NA
  AUCresp$S2_pred_XG[AUCresp$response == 2] <- 1
  AUCresp$S2_pred_XG[AUCresp$response > 2 ] <- 0
  AUCresp$S2_pred_XG[AUCresp$response < 2 ] <- 0
  
  AUCresp$S3_pred_XG = NA
  AUCresp$S3_pred_XG[AUCresp$response == 3] <- 1
  AUCresp$S3_pred_XG[AUCresp$response > 3] <- 0
  AUCresp$S3_pred_XG[AUCresp$response < 3] <- 0
  
  AUCresp$S4_pred_XG = NA
  AUCresp$S4_pred_XG[AUCresp$response == 4] <- 1
  AUCresp$S4_pred_XG[AUCresp$response < 4 ] <- 0
  
  AUCresp = AUCresp[c(3:10)]
  
  
  #create multiroc
  AUCres <- multiROC::multi_roc(AUCresp, force_diag=F)


###########################print results
  #print results 
  return(AUCres)
  
} 

###Plot the AUCS with MLR 


plotMultiAUC <- function(MultiAUCres=NULL ){

AUCres = MultiAUCres

n_method <- length(unique(AUCres$Methods))
n_group <- length(unique(AUCres$Groups))
res_df <- data.frame(Specificity= numeric(0), Sensitivity= numeric(0), Group = character(0), AUC = numeric(0), Method = character(0))
for (i in 1:n_method) {
  for (j in 1:n_group) {
    temp_data_1 <- data.frame(Specificity=AUCres$Specificity[[i]][j],
                              Sensitivity=AUCres$Sensitivity[[i]][j],
                              Group=unique(AUCres$Groups)[j],
                              AUC=AUCres$AUC[[i]][j],
                              Method = unique(AUCres$Methods)[i])
    colnames(temp_data_1) <- c("Specificity", "Sensitivity", "Group", "AUC", "Method")
    res_df <- rbind(res_df, temp_data_1)
    
  }
  temp_data_2 <- data.frame(Specificity=AUCres$Specificity[[i]][n_group+1],
                            Sensitivity=AUCres$Sensitivity[[i]][n_group+1],
                            Group= "Macro",
                            AUC=AUCres$AUC[[i]][n_group+1],
                            Method = unique(AUCres$Methods)[i])
  temp_data_3 <- data.frame(Specificity=AUCres$Specificity[[i]][n_group+2],
                            Sensitivity=AUCres$Sensitivity[[i]][n_group+2],
                            Group= "Micro",
                            AUC=AUCres$AUC[[i]][n_group+2],
                            Method = unique(AUCres$Methods)[i])
  colnames(temp_data_2) <- c("Specificity", "Sensitivity", "Group", "AUC", "Method")
  colnames(temp_data_3) <- c("Specificity", "Sensitivity", "Group", "AUC", "Method")
  res_df <- rbind(res_df, temp_data_2)
  res_df <- rbind(res_df, temp_data_3)
}

#plot in ggplot, Here you can edit the class labes & colors etc

plot = ggplot(res_df, aes(x = 1-Specificity, y=Sensitivity)) +
  geom_path(aes(color = Group)) +
  scale_color_manual(labels = c("Class 1", "Class 2", "Class 3", "Class 4", "macro AUC", "micro AUC"), 
                     values = c("#999999", "#E69F00", "#56B4E9", "#B22E86", "#239621", "#233a68")) + 
  geom_segment(aes(x = 0, y = 0, xend = 1, yend = 1), 
               colour='grey', linetype = 'dotdash') + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5), 
        legend.justification=c(1, 0), legend.position=c(.95, .05),
        legend.title=element_blank(), 
        legend.background = element_rect(fill=NULL, size=0.5, 
                                         linetype="solid", colour ="black"))

}


testpredict.xg <- predict(mlrmodel, testtask)
TestAUC = MultiAUC(testpredict.xg)
plotTestAUC = plotMultiAUC(testAUC)
plotTestAUC

`

Let me know if something is unclear. Good luck with your project!
