### ISSUE TITLE
How to predict all separate models fitted via makeStackedLearner?

### ISSUE THREAD

**Issue by thengl** [mlr-org/mlr#2597]
I would like to produce predictions by old stacked learners fitted through the 'train' function in combination with the 'makeStackedLearner' function.

I am comparing mlr to subsemble package. The [subsemble predict function](https://github.com/ledell/subsemble), for example, produced both the ensemble prediction and all individual predictions. This is a very useful feature as it allows for derivation of model error and visual comparison of models as shown in the animated gif on: https://github.com/Envirometrix/landmap

How to derive all individual predictions fitted using 'makeStackedLearner' function? Thanks in advance.

**Comment by larskotthoff** [comment]
You can use the [`getStackedBaseLearnerPredictions()`](https://www.rdocumentation.org/packages/mlr/versions/2.13/topics/getStackedBaseLearnerPredictions) function for that.
