### ISSUE TITLE
Reread Michel's new imputation code and add a section in tutorial

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#26]
- read code
- read roxygen help
- correct errors in both and extend docs a bit
- add section in tutorial to explain how it works

these are the files:
- Impute.R
- ImputeMethods.R
- PreprocImputeWrapper.R 

Also ImputeWrapper is probably a better and short name than PreprocImputeWrapper.

**Comment by larskotthoff** [comment]
Is this done and can be closed?

**Comment by berndbischl** [comment]
I guess I need to check this at some point, please leave it open

**Comment by berndbischl** [comment]
See #663 for maybe more breaking examples and tests

**Comment by schiffner** [comment]
Went over this and checked what still needs to be resolved:

- [ ] `impute` and `makeImputeWrapper` should have the same formal args.
- [ ] arg check for `learner` in `imputeLearner`
- [ ] Fix this:
```
impute(airquality, target = "Ozone", cols = list(Solar.R = imputeLearner(makeLearner("regr.rpart"), features = c("Wind", "Temp"))))
# Error in (function (data, target, col, learner, features)  : 
#   Target column used as feature for imputation: 'Ozone'
```
I suppose l. 279 in https://github.com/berndbischl/mlr/blob/master/R/ImputeMethods.R has to be changed to
``
not.ok = which.first(target %in% features)
``

- [ ] There should be (probably?) checks for the type of the learner vs. class of the variable to be imputed.
```
impute(airquality, target = "Ozone", cols = list(Solar.R = imputeLearner(makeLearner("classif.rpart"))))
```
