### ISSUE TITLE
Error: == irace == 'digits' (--digits) must be within [1,15] within MLR package

### ISSUE THREAD

**Issue by Mel1992** [mlr-org/mlr#2601]
I'm trying to run this code found in the MLR tutorial, and this is the error I get: Error: == irace == 'digits' (--digits) must be within [1,15]. I already tried the function: convertParamSetToIrace but it hasn't worked. The following is the code:

library(mlr)
data(iris)
task = makeClassifTask(id = "tutorial", data = iris, target = "Species")
base.learners = list(
  makeLearner("classif.ksvm"),
  makeLearner("classif.randomForest")
)
lrn = makeModelMultiplexer(base.learners)
rdesc = makeResampleDesc("CV", iters = 2L)
ctrl = makeTuneControlIrace(maxExperiments = 200L)
res = tuneParams(lrn, iris.task, rdesc, par.set = ps, control =
                   ctrl, show.info = FALSE)
print(head(as.data.frame(res$opt.path)))

**Comment by pat-s** [comment]
Hi,

thanks for posting your issue here.
Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

You can re-open the issue after you've done that.

**Comment by Mel1992** [comment]
Hi Patrick,

This is a reproducible example. It’s taken right out of the mlr tutorial.

Thank you,
Melika

Sent from my iPhone

On Jun 13, 2019, at 12:17 PM, Patrick Schratz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

thanks for posting your issue here.
Please provide a reproducible example<https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example>, preferably using the reprex<https://github.com/tidyverse/reprex> package.

You can re-open the issue after you've done that.

**Comment by larskotthoff** [comment]
You haven't defined `ps` in your code.
