### ISSUE TITLE
Progress bar for tuneParams()

### ISSUE THREAD

**Issue by oren0e** [mlr-org/mlr#2605]
Hi,

When I run the tuneParams() function I do not see any progress status at the console (I am using the default setting for `show.info`). It would be nice to have an optional progress bar that will show, either in console or in a separate window, the % done.

Thanks!

**Comment by pat-s** [comment]
An interesting idea in general, however we won't implement new things like that anymore into _mlr_.

Please file a feature request at [mlr3tuning](https://github.com/mlr-org/mlr3tuning).
