### ISSUE TITLE
classif.gbm multiclass

### ISSUE THREAD

**Issue by markseeto** [mlr-org/mlr#2612]
Thanks for the mlr package.

In case you don't already know, using `distribution = "multinomial"` in `gbm` is discouraged by at least one of the authors.

Examples of unexpected behaviour:
https://github.com/gbm-developers/gbm/issues/41
https://github.com/gbm-developers/gbm/issues/42

At the first link, Greg Ridgeway says:
> I would recommend switching to gbm3 posted on github. And I would not recommend using gbm's multinomial option...I don't think it was ever debugged and had a number of issues. We've actually removed it from gbm3.

**Comment by pat-s** [comment]
Thanks for the note @markseeto! Users encountering problems will find this issue here. Since this is an issue by the package itself, _mlr_ will not do anything about it.

**Comment by larskotthoff** [comment]
Hang on, but we can remove the "multinomial" value for the distribution parameter in mlr, can't we?

**Comment by pat-s** [comment]
Not sure if we should do this. Its still a valid option in the package and if they ever "fix" it we're missing the option here. 
I don't think that we should play the "package police" here?
We're not making single adjustments to package options by default, do we?

**Comment by berndbischl** [comment]
Why not leave the option and simply document the problem as it was communicated to us? As and informal warning in our docs in 2 lines?

**Comment by larskotthoff** [comment]
Sounds good, done that.
