### ISSUE TITLE
resample reproducibility on Windows

### ISSUE THREAD

**Issue by AleBitetto** [mlr-org/mlr#2613]
Hi,

probably this is an old question but I couldn't find any working answer. I'm trying to do outer+inner cross-validation using a `makeTuneWrapper` after defining the inner and outer resampling strategy by `makeResampleDesc`. Then I run the cross-validation with the `resample` function.

IMPORTANT: I'm on a Windows machine and not using any parallelization

I tried different `set.seed` strategy but I cannot get reproducible results.

Is it a Windows unfeasible task? Or is it a matter of wrapped resampling?

Thanks in advance

**Comment by pat-s** [comment]
Not aware of Windows specific seed problems. `mlr` does nothing to the seed, it just uses the seed provided by the user.

Can you post a reprex which shows the different samplings in each run?

**Comment by AleBitetto** [comment]
I fixed it, thanks anyway
