### ISSUE TITLE
Question: Adding a custom learner

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2614]
Received via mail:

> Hi Patrick good morning.
My name is Antonio Canepa, I'm a postdoc at the University of Burgos (ADMIRABLE group http://admirable-ubu.es/home/ )
I'm contacting you because I'm working in an old implementation (increase algorithm diversity by the rotation matrix) but now been applied to a multilabel classification problem. Thus, I have already implemented a "new" rFerns algorithm and I would like to use the "mlr" platform to make some comparisons.
Along with the mlr package, the two available algorithm adaptation methods are rFerns and randomForestSRC and I have tested the benchmark experiments section inside mlr package (which is great!)
Now, the question is how can I set a new algorithm to be used inside the "makeLearner" function to conduct some benchmark experiment using the rFern available in the mlr package and the modified version of the rFern that I have?
Patrick, many thanks for your time and any help you can provide me will be very nice.
All the best,
Antonio

To implement a custom algorithm you need to register it as a [new learner](https://mlr.mlr-org.com/articles/tutorial/create_learner.html).
Assuming you've already done that, you can make the learner available either by [registering](https://mlr.mlr-org.com/articles/tutorial/create_learner.html#registering-your-learner) it or by sourcing the source of your learner online. For example to source a learner from our [extralearners](https://github.com/mlr-org/mlr-extralearner) repo, you would do

```r
source("https://raw.githubusercontent.com/mlr-org/mlr-extralearner/master/R/RLearner_classif_mxff.R")
```

to make it available in your R session.

In your case, just name your custom rFern implementation something like `regr.rFern_custom` and use it as any other learner.

**Comment by ajcanepa** [comment]
Great!,
Many thanks for the answer.

**Comment by ajcanepa** [comment]
When you creates a new learner, through the `makeRLearner.` function, one option (argument package) declares the package where this new algorithm comes from. In the case, the new algorithm isn't in no already package but comes from your own work, which value for the package argument must to be declared?, a  NULL?  or an empty " " value?
Many Thanks again!

**Comment by pat-s** [comment]
We do not have our own learners, every learner comes from a package. If you mean the `rFerns` learner, it is from the `rFerns` package. 

I guess the easiest route for you would be to follow the "extralearner" way which I mentioned above.

**Comment by larskotthoff** [comment]
And if you have created a new learner, make a package for it first that mlr can then interface with.

**Comment by ajcanepa** [comment]
Sorry for coming back with the question, but I have reviewed all the *.R files in the "extralearner" as suggested by @pat-s and all of them had in the "package" argument the name of a package.
What about if the extralearner lives only in your *.R file what should I give to the "package" argument, a NULL? 
Or...
Maybe the case, that the creation of a package is "Mandatory" in order to upload a new learner as suggested by @larskotthoff ?
I can't find the obvious workflow to create a new learner, Should I create the package first and then use the "extralearner"?
Thanks!

**Comment by pat-s** [comment]
Based on your mail you want to implement a custom version of the `rFerns` learner, right? So in that case the learner requires the `rFerns` pkg and this should be put into the "package" slot. You can simply adapt the current `rFerns` learner and continue from there.

> What about if the extralearner lives only in your *.R file what should I give to the "package" argument, a NULL?

It does not matter where the .R file lives, the package which needs be installed/loaded for the learner is important.

Or did I get your question completely wrong? :sweat_smile:

**Comment by berndbischl** [comment]
?Learner
the docs are pretty clear here? 

#' @param package ([character])\cr
#'   Package(s) to load for the implementation of the learner.

Simply load what needs to be loaded for the underlying learner to work. 
Set it to character(0) if you dont need any

**Comment by ajcanepa** [comment]
Great!
Many thanks @pat-s and @berndbischl for your answer. 
Now, I have everything more clear. As @pat-s mentioned the idea is a custom version of a learner so I'll go for the *mlr-extralearners* and afterwards a PR to be included.
Thanks for all!
