### ISSUE TITLE
Feature: Make it possible to use BMRs with different filters but same task & learner

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2615]
This is currently not possible since the "BMR" IDs need to be unique. However, only task and learner are created in a unique fashion - if one uses multiple filters with the same task and learner, learner IDs will look like 

```
regr.xgboost.filtered.tuned
```

If one now tries to use `mergeBenchmarkResults()` with learners that used different filters, the function exits with:

```
The following task - learner combination(s) occur either multiple times or are missing: 
```

which is correct.

~~To not touch the API, we should provide the possibility of a passing a manual list of IDs to `mergeBenchmarkResults()` which~~

~~- serve as the learner ID~~
~~- are unique~~

~~These can then directly used by the subsequent plotting function to generate "pretty" labels.~~

**Comment by pat-s** [comment]
Ok, this is really annyoing if one wants to compare multiple filter methods (I guess nobody did so far, as otherwise this issue would have come up earlier).

Setting the IDs after creation of the BMR is a huge pain. 
I suggest we simply use unique filter names for autogenerating the BMR learner ids if a FilterWrapper is included in the last Wrapper.

Currently, task and learner names are created in a unique fashion but for filters we only append `[...].filtered`. Example: `regr.ksvm.filtered.tuned`.

So the auto-generated learner IDs for a BMR should look like 

```
<task.type>.<learnerID>.<filterID>.filtered.tuned
```

instead of 

```
<task.type>.<learnerID>.filtered.tuned
```

**Comment by berndbischl** [comment]
well your workaround is exactly what you should have done....
of course if you create different learners (here more: different "pipelines") they should have unique names.
so i guess the problem is simply in your client code? 

how could you even run the bechmark? mlr should have complained? 
ah your where running it individually and then tried to merge later?

**Comment by pat-s** [comment]
> well your workaround is exactly what you should have done....

Well yeah, just came across the problem after the models have been run - due to the individual execution.
In my previous project I did not use filters but only compared different resamplings and models and merged the results using the resample grouping.

> ah your where running it individually and then tried to merge later?

Yes because this way I can see which benchmarks fail on an individual base.

If its as simple as changing a chr from "filtered" to "filtered.<filter.name>", a change would make sense from my point of view. Will take a look later.

**Comment by berndbischl** [comment]
Not sure if Iike the ID change. Because you are now solving exactly your problem. But not the general one.

What if people want to compare different tuners? What if you want to compare different rf configurations? And so on

**Comment by berndbischl** [comment]
note that the last point in your OP issue (that the problem basically comes from merging) you didnt really explain well, which is the heart of the issue ;-)
you should have posted minimal code too :)

**Comment by pat-s** [comment]
> Not sure if Iike the ID change. Because you are now solving exactly your problem. But not the general one.

Right. Looking at it from this side you would have to include every component and then the auto-generated ID. Implementing this for mlr is not worth it anymore but maybe we can include a "smarter" auto-naming of IDs in mlr3.

The auto-naming would then contain all elements that you can possibly change in a benchmark setting:

- learner
- task
- tuner
- filter
- measure
- resampling

For _mlr_ the current behavior is as follows:

- `benchmark()` generates IDs based on the task/learner combination and stops early if some are not unique. 
- If one goes a different routes and does single benchmarks with the aim to combine them in the end, `benchmark()` does ofc not error but `mergeBenchmarkResult()` complains if IDs are not unique.
- Only Task and Learner are used because they are required for the benchmark and everything else is optional (tuner, filter). However, in that context it would make sense to also include the resample strategy in the auto-naming since it is also required (in contrast to tuning and filtering).

But yes, let's stick with the current behavior and do not just fix on part of the problem. 


> note that the last point in your OP issue (that the problem basically comes from merging) you didnt really explain well, which is the heart of the issue ;-)
> you should have posted minimal code too :)

Jup I should have and I was lazy at this point.

**Comment by berndbischl** [comment]
> mplementing this for mlr is not worth it anymore but maybe we can include a "smarter" auto-naming of IDs in mlr3.

sure, i can kinda see why you dislike what happened in your example...
