### ISSUE TITLE
Plotting training measure after benchmarking

### ISSUE THREAD

**Issue by FedericoConcas** [mlr-org/mlr#2616]
I want to access and plot both the training accuracy and the test accuracy after a benchmark experiment.
I am using accuracy as a metric.

If I set the aggregation of the accuracy to train.acc and create a list of both test.acc and train.acc, then the benchmark result cannot be plotted because there are two columns of class "acc" in the data frame, which are incidentally identical. However, I can see that the benchmark results contains the training accuracy even if the aggregation is not specified, as I have set the learners' predict.type to "both".

I thought of a workaround, which would be to extract the train.acc from the benchmark object and aggregate it and plot it myself.

How do I do that?
Is there a simpler way?

Thank you!

**Comment by berndbischl** [comment]
You havent presented a minimal code example. Please do that

**Comment by pat-s** [comment]
Please do not [cross-post](https://stackoverflow.com/questions/56877962/plotting-training-metric-after-benchmark-experiment).
