### ISSUE TITLE
Trouble with constructing custom measure which is dependent on a feature

### ISSUE THREAD

**Issue by oren0e** [mlr-org/mlr#2618]
I try to create my own measure for working with xgboost model. This measure will basically examine a sum of the `amount` feature where the **true** response equals to 1 and compare it to values where the **predicted** response equals to 1, and then will calculate a sort of absolute percentage error.

This is how I define it:
```
fp_amount_fun <- function(task, model, pred, feats, extra.args) {
  pred <- getPredictionResponse(pred)
  truth <- getPredictionTruth(pred)
  df <- cbind(feats, pred, truth)
  # predicted
  predicted_amount <- sum(df$amount[df$pred == 1])
  # real
  real_amount <- sum(df$amount[df$truth == 1])
  # error
  return((abs((real_amount - predicted_amount)) / real_amount))
}

# Generate the measure object
fp_amount <- makeMeasure(
  id = "fp_amount", name = "The Percentage of Error from the original value",
  properties = c("classif", "req.pred", "req.truth"),
  minimize = TRUE, best = 0, worst = 1,
  fun = fp_amount_fun
)
```

I don't think I am doing this right because I get an error (the top of the traceback):

```
Error: $ operator is invalid for atomic vectors 
7.
getPredictionTruth.default(pred) 
6.
getPredictionTruth(pred) 
``` 
I also not sure about if this measure is what I should use with the custom eval_metric for xgboost, because essentially they are both measuring the same thing. Help.

**Comment by berndbischl** [comment]
this is not a fully reproducible example. pls provide one

**Comment by berndbischl** [comment]
> I also not sure about if this measure is what I should use with the custom eval_metric for xgboost, because essentially they are both measuring the same thing. Help.

whether you want to use the custom_eval_metric on xgboost i dont know, but what happens there has nothing to do with what happens in mlr. you could of course pass there a (semnatically) equivalent function

**Comment by pat-s** [comment]
Closing here for now, feel free to re-open if you have further questions.
