### ISSUE TITLE
imbalanced classification problem with binary classification and nested spatial CV

### ISSUE THREAD

**Issue by joannapr** [mlr-org/mlr#2619]
Dear Contributors and Members,

I am currently working on a binary classification problem. My target variable is classified as 1 - affected and 0 - not affected. I am using a random forest algorithm within the ranger package. Thus, while constructing a learner in the mlr package, I specify it as "classif.ranger"). 

In order to account for spatial autocorrelation in my data in both hyperparameter tuning and predictive performance estimation (and to obtain unbiased estimates), I have decided to use a nested spatial cross-validation approach. 

For the outer resampling loop and performance evaluation, a 5-fold spatial partitioning was chosen (makeResampleDesc(method = "SpCV", iter= 5)). Whereas, for inner resampling loop and hyperparameter tuning, 4-fold cross-validation was selected (makeResampleDesc(method = "SpCV", iter= 4)). 

After running the whole script and analysing the results, I am encountering an issue. Even though my input data is relatively balanced, meaning the number of affected (1) and non-affected (0) records are roughly equal, I am coming across the issue of imbalanced classes. Which means that an imbalanced number of observations per class is assigned to each fold during spatial partitioning. This is due to the specific distribution of affected and non-affected records across different regions of my study area (in some places there are more 0's and other more 1's). 

According to my understanding, this imbalance in each fold leads to unsatisfactory results in regards to the predictions of new observations. 

I have been reading the tutorial for the mlr package, specifically the part that deals with imbalanced classification problems and cost- and sampling-based approaches. However, I am a bit confused about how these methods could be applied with a combination of nested spatial partitioning. I was looking at the option of undersampling or assigning the costs as my learner supports weights. 
I would like to know how these approaches would work in cases where each spatial fold contains a different class as a majority one (sometimes it will be 0's and sometimes 1's).
Moreover, is there an option to "modify" the spatial partitioning step so that more balanced observations per class are selected?

I would greatly appreciate any explanation or suggestions in this matter. 

With kind regards,
Joanna

**Comment by berndbischl** [comment]
i guess @pat-s has to answer this one

**Comment by pat-s** [comment]
Hi Joanna,

thanks for the extensive description of your problem.
To really help you, we need a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

- Because you used 5 (outer) and 4 (inner) -> the value for inner does not depend on the outer value
- You already used `mlr::makeUndersampleWrapper()`?

> Moreover, is there an option to "modify" the spatial partitioning step so that more balanced observations per class are selected?

This is handled by the wrapper mentioned above - spatial partitioning just takes the observations it gets passed to and clusters them in a certain way.

**Comment by joannapr** [comment]
Hi Patrick and Bernd,

Thank you very much for your fast response!
No, I didn't use the mentioned function yet, but I will try to apply it. I have tried to use the case.weights parameter. 

One of my concerns is how to select undersampling rate or class weights, if the number of observations per class (0's and 1's) changes in each spatially created fold. 

Please see below the reproducible example. To make it faster as an input data I applied some dataset from sp package. Please let me know if that is ok, or if some minimal dataset that I am using is needed.

Greetings,
Joanna

``` r
##### MLR PERFORMANCE ESTIMATION ########
library(sp)
#> Warning: Paket 'sp' wurde unter R Version 3.5.3 erstellt
library(sf)
#> Warning: Paket 'sf' wurde unter R Version 3.5.3 erstellt
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
library(raster)
#> Warning: Paket 'raster' wurde unter R Version 3.5.3 erstellt
library(dplyr)
#> Warning: Paket 'dplyr' wurde unter R Version 3.5.3 erstellt
#> 
#> Attache Paket: 'dplyr'
#> The following objects are masked from 'package:raster':
#> 
#>     intersect, select, union
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(mlr)
#> Warning: Paket 'mlr' wurde unter R Version 3.5.3 erstellt
#> Lade nötiges Paket: ParamHelpers
#> Warning: Paket 'ParamHelpers' wurde unter R Version 3.5.3 erstellt
#> 
#> Attache Paket: 'ParamHelpers'
#> The following object is masked from 'package:raster':
#> 
#>     getValues
#> 
#> Attache Paket: 'mlr'
#> The following object is masked from 'package:raster':
#> 
#>     resample
library(ranger)
#> Warning: Paket 'ranger' wurde unter R Version 3.5.3 erstellt

# data preparation 
data(meuse)
data = meuse
coords = data[,1:2]
data[,c(1,2,9,10,11,13,14)] = NULL
colnames(data)[7] = "target"
data$target = as.factor(data$target)

# create task, learner, outer and inner loop 
task = makeClassifTask(data = data, target = "target", coordinates = coords)

lrn_rf = makeLearner(cl = "classif.ranger", predict.type = "response")

outer = makeResampleDesc(method = "SpCV", iters = 5)

inner = makeResampleDesc(method = "SpCV", iters = 4)

ps = makeParamSet(
  makeDiscreteParam("mtry", values= c(3, 4)),
  makeDiscreteParam("sample.fraction", values= c(0.55, 0.632, 0.75)),
  makeDiscreteParam("min.node.size", values= c(1, 5, 10))
)

ctrl_grid = makeTuneControlGrid()

wrapped_lrn_rf = makeTuneWrapper(learner = lrn_rf,
                                 resampling = inner,
                                 par.set = ps,
                                 control = ctrl_grid,
                                 show.info = TRUE,
                                 measures = mlr::kappa)

configureMlr(on.learner.error = "warn", on.error.dump = TRUE)

library(parallelMap)
#> Warning: Paket 'parallelMap' wurde unter R Version 3.5.3 erstellt

if (Sys.info()["sysname"] == "Windows") {
  parallelStartSocket(level = "mlr.tuneParams",
                      cpus =  round(parallel::detectCores() / 1.1))
}
#> Starting parallelization in mode=socket with cpus=15.

set.seed(12345)
result = mlr::resample(learner = wrapped_lrn_rf,
                           task = task,
                           resampling = outer,
                           extract = getTuneResult,
                           show.info = TRUE,
                           measures = mlr::kappa) 
#> Resampling: spatial cross-validation
#> Measures:             kappa
#> [Tune] Started tuning learner classif.ranger for parameter set:
#>                     Type len Def          Constr Req Tunable Trafo
#> mtry            discrete   -   -             3,4   -    TRUE     -
#> sample.fraction discrete   -   - 0.55,0.632,0.75   -    TRUE     -
#> min.node.size   discrete   -   -          1,5,10   -    TRUE     -
#> With control class: TuneControlGrid
#> Imputation value: 1
#> Exporting objects to slaves for mode socket: .mlr.slave.options
#> Mapping in parallel: mode = socket; level = mlr.tuneParams; cpus = 15; elements = 18.
#> [Tune] Result: mtry=4; sample.fraction=0.632; min.node.size=10 : kappa.test.mean=0.6285691
#> [Resample] iter 1:    0.5692884
#> [Tune] Started tuning learner classif.ranger for parameter set:
#>                     Type len Def          Constr Req Tunable Trafo
#> mtry            discrete   -   -             3,4   -    TRUE     -
#> sample.fraction discrete   -   - 0.55,0.632,0.75   -    TRUE     -
#> min.node.size   discrete   -   -          1,5,10   -    TRUE     -
#> With control class: TuneControlGrid
#> Imputation value: 1
#> Exporting objects to slaves for mode socket: .mlr.slave.options
#> Mapping in parallel: mode = socket; level = mlr.tuneParams; cpus = 15; elements = 18.
#> [Tune] Result: mtry=4; sample.fraction=0.632; min.node.size=1 : kappa.test.mean=0.4897767
#> [Resample] iter 2:    0.8615385
#> [Tune] Started tuning learner classif.ranger for parameter set:
#>                     Type len Def          Constr Req Tunable Trafo
#> mtry            discrete   -   -             3,4   -    TRUE     -
#> sample.fraction discrete   -   - 0.55,0.632,0.75   -    TRUE     -
#> min.node.size   discrete   -   -          1,5,10   -    TRUE     -
#> With control class: TuneControlGrid
#> Imputation value: 1
#> Exporting objects to slaves for mode socket: .mlr.slave.options
#> Mapping in parallel: mode = socket; level = mlr.tuneParams; cpus = 15; elements = 18.
#> [Tune] Result: mtry=3; sample.fraction=0.55; min.node.size=5 : kappa.test.mean=0.6238186
#> [Resample] iter 3:    0.8888889
#> [Tune] Started tuning learner classif.ranger for parameter set:
#>                     Type len Def          Constr Req Tunable Trafo
#> mtry            discrete   -   -             3,4   -    TRUE     -
#> sample.fraction discrete   -   - 0.55,0.632,0.75   -    TRUE     -
#> min.node.size   discrete   -   -          1,5,10   -    TRUE     -
#> With control class: TuneControlGrid
#> Imputation value: 1
#> Exporting objects to slaves for mode socket: .mlr.slave.options
#> Mapping in parallel: mode = socket; level = mlr.tuneParams; cpus = 15; elements = 18.
#> [Tune] Result: mtry=3; sample.fraction=0.632; min.node.size=5 : kappa.test.mean=0.7815599
#> [Resample] iter 4:    0.3009709
#> [Tune] Started tuning learner classif.ranger for parameter set:
#>                     Type len Def          Constr Req Tunable Trafo
#> mtry            discrete   -   -             3,4   -    TRUE     -
#> sample.fraction discrete   -   - 0.55,0.632,0.75   -    TRUE     -
#> min.node.size   discrete   -   -          1,5,10   -    TRUE     -
#> With control class: TuneControlGrid
#> Imputation value: 1
#> Exporting objects to slaves for mode socket: .mlr.slave.options
#> Mapping in parallel: mode = socket; level = mlr.tuneParams; cpus = 15; elements = 18.
#> [Tune] Result: mtry=3; sample.fraction=0.75; min.node.size=1 : kappa.test.mean=0.6836122
#> [Resample] iter 5:    0.4545455
#> 
#> Aggregated Result: kappa.test.mean=0.6150464
#> 

parallelStop()
#> Stopped parallelization. All cleaned up.
```

<sup>Created on 2019-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pat-s** [comment]
Do you face the same error with the meuse dataset and your own one? You could also just use a subset of your original data.

I am not sure if using case.weights is the correct thing to do here.

> One of my concerns is how to select undersampling rate or class weights, if the number of observations per class (0's and 1's) changes in each spatially created fold.

This problem is not specific to spatial partitioning but applies to any resampling. I suggest you try out the undersampling wrapper first and inspect the indices using `getResamplingIndices(inner = TRUE)`. Then you can create a short reprex that we can discuss further :)

**Comment by joannapr** [comment]
Thank you very much for this suggestion. I will try it out and get back to you as soon as possible :)

**Comment by joannapr** [comment]
Hi,
I had tested the undersampling wrapper on a subset of my original data (random selection). Estimates/results of undersample approach and control one are very similar. Moreover, they are better from the results that I have obtained when using the whole original dataset, where imbalance of classes was more visible. Thus, it is difficult for me to understand the difference, maybe there is some explanation to that?

Because of some technical issue, I have to apply this approach once again, so I can come back with a short reprex. 

Greetings

**Comment by unnic** [comment]
I'm just diving into a similar problem. From my limited experience it seems like makeOversampleWrapper()  does not work with nested spatial CV. I was able to proceed a bit further using oversample() (or even better smote() ) on the task. The point generation seems to work when checked using getTaskData(). I'm about to check if the train/test seperation works during the spatial CV, but at this point I can't see why not.
please also see https://github.com/mlr-org/mlr/issues/2636

**Comment by unnic** [comment]
unfortunatley the new coordinates created by oversample() are not shown in oversample.task$coordinates

so sadly `nrow(getTaskData(task))!=nrow(task$coordinates)` which makes it impossible for me to check if the spatial CV worked.

Is there another way to get to the oversampled data including the coordinates?

**Comment by pat-s** [comment]
To be able to help you here, you need to come up with a reprex and specific questions. Too many single comments across several issues with only code chunks does not get us anywhere.

However, I can't promise anything here (neither time wise nor code wise).
We're not implementing new features in _mlr_ anymore and even though this is more likely a bug than a feature request, there are probably more shortcomings in the package related to spCV.

**Comment by pat-s** [comment]
@joannapr Have you been able to follow up on this approach?

I'll close here for now due to inactivity but happy to re-open if you're back at it.
