### ISSUE TITLE
accessing indices without running tuning in nested resampling with stratification

### ISSUE THREAD

**Issue by AleBitetto** [mlr-org/mlr#2623]
Hi,

I'm working on a nested tuning task with stratification based on regressor (with `stratify.cols`, creating the outer and inner `makeResampleDesc` and then using `makeTuneWrapper`). I need to test different learners but some of them require only numerical variables, so I need to create dummies. My problem is to get the (same) stratification also for the dummy dataset.

My solution is to provide the indices for both outer and inner folds by `blocking`. Assuming that this is the best way to achieve what I want, my question is how to create the indices. I have two possible answer:

1 - Using external package to evaluate the nested stratification
2 - Run a very basic learner (to minimize computation time) on the same task and get the indices from `resample` output.

I'd like to go for 2, so is there a way to get the indices without running the `resample` (so no need to define an additional basic learner), like doing `str(makeResampleInstance(...))`?

Thanks a lot

**Comment by pat-s** [comment]
The inner indices are created during the `resample()` call. So to get these I do not see another cheap way then calling `resample()` with a featureless learner.

You can then call `getResamplingIndices(inner = TRUE)` on the ResampleResult.
