### ISSUE TITLE
How can I use a feature to create blocks and then exclude it in the model

### ISSUE THREAD

**Issue by melonki** [mlr-org/mlr#2625]
Dear Contributors and Members,

In my study, I need to use the feature "year" to create blocks so that I can perform by-year cross validation. Meanwhile, I don't want this feature included in the model because it is meaningless. So I used the function "dropFeatures(task, features)", trying to drop the specific feature in my model. However, I could still find this feature in the results of feature importance. Did I use the function in correct way? Is there any alternative to achieve my goal? The code is as follows (tr1 is my dataframe):

```
tr1$year=as.factor(tr1$year)
tsk1 <- makeRegrTask (data = tr1,coordinates = tr1[,c("X_Lon","Y_Lat")],target = "o3_8h_24h")  #prepare and transfer traning data to traintask
ho=makeResampleInstance("Holdout",tsk1,split=0.8)
tsk1$blocking = tr1[,c("year")]
tsk1 <- createDummyFeatures (obj = tsk1,col = "year")
dropFeatures(tsk1,"X_Lon")
dropFeatures(tsk1,"Y_Lat")
dropFeatures(tsk1,"year.2013")
dropFeatures(tsk1,"year.2014")
dropFeatures(tsk1,"year.2015")
dropFeatures(tsk1,"year.2016")
```
I would greatly appreciate any explanation or suggestions in this matter.

With kind regards,
Melonki

**Comment by berndbischl** [comment]
Hi. A minimal reproducible example means you have to recreate an example with a dataset we can also access....

**Comment by berndbischl** [comment]
Also you do not even call feature importance in your code snippet. And why do you create dummy features then remove them? Please reopen with a full demonstration of the problem

**Comment by berndbischl** [comment]
Also you better should not overwrite the blocking field of the task but rather pass the arg into the constructor
