### ISSUE TITLE
multiple models parallel training

### ISSUE THREAD

**Issue by AleBitetto** [mlr-org/mlr#2629]
Hi,

is it possible to just train several models in parallel? I saw the multiplexer or the benchmark but they're used for tuning. I have a list of learners to be trained on the same task.

In my case I'm interested in evaluating the performance on the full dataset, after finding the best parameters with a nested CV tuning.

Thanks in advance.

**Comment by jakob-r** [comment]
If you are on a cluster you can use `batchmark()`. If you just want to use a multicore system you can use `benchmark()` and `parallelStartMulticore()` (Linux) or `parallelStartSockets()` (Windows). 
Also check this help page:
https://mlr.mlr-org.com/articles/tutorial/parallelization.html

**Comment by AleBitetto** [comment]
Actually I want to just train the model, not tune or benchmark. Is it enough to use a for loop with `parallelMap`?

**Comment by pat-s** [comment]
> In my case I'm interested in evaluating the performance on the full dataset, after finding the best parameters with a nested CV tuning.

Performance should be estimated in a CV.

> is it possible to just train several models in parallel? I saw the multiplexer or the benchmark but they're used for tuning. I have a list of learners to be trained on the same task.

it sounds like you need to familiarize yourself more with the concepts and the tutorial of _mlr_. Everything is explained there.
`benchmark()` is exactly for comparing models. 

> Is it enough to use a for loop with parallelMap?

I don't understand what you want to do but you will never need a for-loop. Please read the tutorial and try to understand it better before doing anything that is not correct (based on your last issues I assume that you're close to doing something the wrong way).

**Comment by pat-s** [comment]
In addition, please ask such usage/theory related questions on Stackoverflow in the future - they are better suited there and you might get quicker replies. Thanks.

**Comment by AleBitetto** [comment]
As explained before, I don't want to tune but just train the model after I tune the parameters elsewhere. And I want to train the models on the full set just to see how they perform on the whole set. So no CV is needed as I already have the cross-validated performance while tuning.

Anyway, apart from the theoretical matter (that I wasn't asking for), I was interested on simply TRAINING the models in parallel. Thus, reading the tutorial before asking, `benchkmark` or `multiplexer` seems not to do what I need. Reading the `parallelMap` tutorial I ended in this:

```
library(parallelMap)
parallelStartSocket(2)
parallelLibrary("MASS")
# subsample iris, fit an LDA model and return prediction error
f = function(i) {
  n = nrow(iris)
  train = sample(n, n/2)
  test = setdiff(1:n, train)
  model = lda(Species~., data=iris[train,])
  pred = predict(model, newdata=iris[test,])
  mean(pred$class != iris[test,]$Species)
}
y = parallelMap(f, 1:2)
parallelStop()
```
and I was wondering if there was a `mlr` wrapper also for this. Sorry for miscalling this as a "for-loop".

Moreover, I thought it was better to post here, marking as "questions", instead of Stackoverflow because you are the mantainers of the package. Next time I'll try there, no problem :)

Thanks for your patience.

**Comment by berndbischl** [comment]
do you want to parallelize the individual training of one model? 
--> mlr cannot do this. maybe the basic training algo has an option for that, and then you need to set it manually

or do you have 10 learners and want to train the 10 in parallel? thats simply a train to parallelMap, or actually any other parallel loop or lapply framework in R?

PS:
it would help in these cases to write down a minimal example. something that eg does what you want in a sequentail fashion. 
I have read you R code in the post above and still dont undertsand how it relates to you question...

**Comment by AleBitetto** [comment]
I managed in this way, define this function

```    
full_set_perf = function(i, task, learner, tuning_criterion, res_summ_best, param_set, par_names){
      # extract parameters
      params_full = learner$par.vals
      params_full[names(param_set$pars)] = as.list(res_summ_best[i, par_names])
      params_full_export = unlist(params_full[par_names])
      # remove missing params (some combination may contain unnecessary parameters)
      NA_params = which(unlist(lapply(params_full, is.na)))
      params_full[NA_params] = NULL
      
      learner_full = learner
      learner_full$par.vals = params_full
      learner_full$config = list(on.learner.error = 'quiet')

      model_full = train(learner_full, task)
      prediction_full = predict(model_full, task = task)
      performance_full = performance(prediction_full, eval(parse(text=tuning_criterion)))
      
      return(c(iter = i, params_full_export, performance_full))
}
```

and then run

```
      parallelStart(mode = "socket", cpus = detectCores(), show.info = F)
      parallel::clusterSetRNGStream(iseed = 1)
      parallelLibrary("mlr")
      perf_full = parallelMap(full_set_perf, 1:nrow(res_summ_best), more.args = list(task, learner, 
      tuning_criterion, res_summ_best, param_set, par_names))
      parallelStop()
```

where `res_summ_best` is the modified output of `getNestedTuneResultsOptPathDf`

**Comment by berndbischl** [comment]
so you are basically "benchmarking" always the same learner with different hyperpar settings (technically). thats a call into "benchmark" then.
simply set up the different learner objects as you do in your code, then run run benchmark on them (in parallel if you want)

**Comment by AleBitetto** [comment]
But in benchmark I need to define a resampling description and I don't want that. I just want to train the model on all data. Maybe using `subsample` with `spli = 1` is a good workaround?

**Comment by berndbischl** [comment]
you want a resample desciption. one where ALL indices are used in train AND predict.
(if i read your code example corretly)
use ?makeFixedHoldoutInstance and set up the indices yourself
its exactly made for such purposes
then call benchmark and use the normal paralleization options

HTH

**Comment by AleBitetto** [comment]
Thanks a lot, much appreciated.

**Comment by pat-s** [comment]
Just a small addition to that:

> Moreover, I thought it was better to post here, marking as "questions", instead of Stackoverflow because you are the mantainers of the package. 

We also look at the Stackoverflow questions. 
The thing is just that we would like to keep the repo tidy with issues about the package and its functionality (feature requests, bugs).
You have to see that way more people will see your question on SO and we are happy if other people can answer them instead of us, saving us some time.
This will probably not happen in the repo here ;)
However, we do not directly want to close any usage question here but instead kindly ask users to ask their questions on SO in the future.

**Comment by AleBitetto** [comment]
ok no problem!
