### ISSUE TITLE
Is it possible to use the learner classif.lgb for a two-class problem?

### ISSUE THREAD

**Issue by deepdalytics** [mlr-org/mlr#2631]
When using the lightgbm learner for my classification task, mlr outputs

"is a two-class-problem, but learner 'classif.lgb' does not support that"

So it seems that classif.lgb is only configured for multiclass-problems. Is this the case? If so, is there an alternative learner for the binary case? Thank you

**Comment by GegznaV** [comment]
The information on learners can be found [here](https://mlr.mlr-org.com/articles/tutorial/integrated_learners.html), but you classifier is not present in this list. 
Do you talk about one in **mlr-extralearner** package ([see here](https://github.com/mlr-org/mlr-extralearner/blob/75432ea7100a82382a1b5245acb2199fbe053e0c/R/RLearner_classif_lightgbm.R#L2))?

**Comment by deepdalytics** [comment]
@GegznaV Thank you very much for your reply. You're right, the classifier is not there. I switched to classif.lightgbm from the mlr-extralearner package and now it works like a char. Thank you very much for your help.
