### ISSUE TITLE
Current github version of data.table breaks mlr

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr#2632]
Just a quick heads up: 
I installed the current GitHub version from `Rdatatable/data.table`. 

This breaks `mlr` for me:

``` r
library(mlr)
#> Loading required package: ParamHelpers
#> Warning: replacing previous import 'BBmisc::coalesce' by
#> 'data.table::coalesce' when loading 'mlr'
makeLearner("classif.ranger", num.trees = 30L)
#> Error in coalesce(learner$config$on.par.without.desc, getMlrOption("on.par.without.desc")): Item 2 is type character but the first item is type NULL. Please coerce before coalescing.
```
<sup>Created on 2019-08-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

With the current CRAN version of `data.table` everything works fine.

**Comment by pat-s** [comment]
I just tried this and could not reproduce it. Probably fixed upstream meanwhile.
