### ISSUE TITLE
Oversampling and spatial repeated cross validation

### ISSUE THREAD

**Issue by unnic** [mlr-org/mlr#2636]
Hello,

I have an imbalanced class distribution in a spatial task. To account for this I would like to use [oversampling](https://mlr.mlr-org.com/articles/tutorial/over_and_undersampling.html) while accounting for the [spatial autocorrelation](https://mlr.mlr-org.com/articles/tutorial/handling_of_spatial_data.html) of the data by using _SpRepCV_ in makeResampleDesc().

can I use these techniques together? are the coordinates simply duplicated using oversample()? how about smote()? Does _SpRepCV_ pick up the artificial points correctly? How/where can I check this?

I can just assume from createSpatialResamplingPlots() that the spatial separation does not work:
![grafik](https://user-images.githubusercontent.com/17173808/65029448-0ebd5680-d93e-11e9-89ce-b28766fff2af.png)
There seems to be an orange (=testing) point overlayed on a blue (=training) point

**Comment by pat-s** [comment]
I've never used oversampling in a spatial analysis yet. So if you are facing issues, it will most likely not work.

You are welcome to look into the source code and come up with a PR :) 
However, adding support for this is not on my personal todo list.

**Comment by unnic** [comment]
I was using makeOversampleWrapper() which does work with SpRepCV. Using oversample() has an effect. But I'm not quite sure yet if it's doing what is intended....

**Comment by pat-s** [comment]
> Using oversample() has an effect. But I'm not quite sure yet if it's doing what is intended....

Chances are high that is is not, so you might want to inspect the results very carefully.

**Comment by unnic** [comment]
How can I access the created data points after using oversample() ? 
I can get the predictions in the "ResampleResult" object and would like to link the "id" to the data to see how the test set is distributed over the iterations.

**Comment by pat-s** [comment]
> How can I access the created data points after using oversample()?

I don`t know, I've never used `oversample()` personally yet. It should be stored somewhere in the resulting object?

**Comment by unnic** [comment]
Even without oversample()... You get a ResampleResult object from resample(). I am looking for a  way to get to the underlying data from that. Without oversample() i can link the ids from the "ResamplePrediction" object (within the ResampleResult) to the rows of the input data. I'm guessing there must be a more direct way as the data seems to be stored somewhere in the ResampleResult or the task itself. Do you happen to know where?

**Comment by unnic** [comment]
i think I got it:
getTaskData()

**Comment by pat-s** [comment]
I'll close here for now, everything seems to be clear currently. Feel free to re-open if not.
