### ISSUE TITLE
What should I do if I want to use different predefined indices in nested resampling?

### ISSUE THREAD

**Issue by melonki** [mlr-org/mlr#2641]
Dear Contributors and Members,
I really appreciate your efforts in developing the function of nested resampling and I have tried the combination of SpCV and grouping in tuning hyperparameters in my model by defining the inner and outer resample description. Now I wonder what should I do if I want to use other predefined indices in  inner and outer loop at the same time? It seems that I can't define two blockings in a single task.

I would greatly appreciate any explanation or suggestions in this matter.

With kind regards,
Melonki

**Comment by pat-s** [comment]
> Now I wonder what should I do if I want to use other predefined indices in inner and outer loop at the same time?

If you use "grouping" you cannot use more than one factor level at the same time as this one factor level sets fixed resampling indices.

What do you want to use this other factor level for?

**Comment by berndbischl** [comment]
predefined indices you can use in the outer level. 
have a look at ?makeFixedHoldoutInstance for the most common case

also, you can simply create a CV instance, and then simply overwrite the index sets for train and test sets in the instance. thats a little bit tedious / could be better supported through API, and in mlr3 this is supported in a better way. but also possible here.

fixed index sets we do not currently support on the inner level for nested resampling for various reasons. 

if this answers the question, pls close

**Comment by melonki** [comment]
> > Now I wonder what should I do if I want to use other predefined indices in inner and outer loop at the same time?
> 
> If you use "grouping" you cannot use more than one factor level at the same time as this one factor level sets fixed resampling indices.
> 
> What do you want to use this other factor level for?

In my case, I need to handle spatial datasets and assess my model performance with site-based CV, which is based on the ID of each monitoring site instead of a cluster of coordinates in spatial partitioning in mlr.

**Comment by pat-s** [comment]
> In my case, I need to handle spatial datasets and assess my model performance with site-based CV, which is based on the ID of each monitoring site instead of a cluster of coordinates in spatial partitioning in mlr.

Yes, then you are correct in using `grouping` to specify fixed indices corresponding to your sites. 

> fixed index sets we do not currently support on the inner level for nested resampling for various reasons.

We do, see [here](https://mlr.mlr-org.com/articles/tutorial/resample.html#grouping-cv-with-fixed-predefined-indices).

**Comment by melonki** [comment]
> > In my case, I need to handle spatial datasets and assess my model performance with site-based CV, which is based on the ID of each monitoring site instead of a cluster of coordinates in spatial partitioning in mlr.
> 
> Yes, then you are correct in using `grouping` to specify fixed indices corresponding to your sites.
> 
> > fixed index sets we do not currently support on the inner level for nested resampling for various reasons.
> 
> We do, see [here](https://mlr.mlr-org.com/articles/tutorial/resample.html#grouping-cv-with-fixed-predefined-indices).

Sorry, I forgot to mention that I also need to operate a by-year CV in the outer loop.

**Comment by melonki** [comment]
> predefined indices you can use in the outer level.
> have a look at ?makeFixedHoldoutInstance for the most common case
> 
> also, you can simply create a CV instance, and then simply overwrite the index sets for train and test sets in the instance. thats a little bit tedious / could be better supported through API, and in mlr3 this is supported in a better way. but also possible here.
> 
> fixed index sets we do not currently support on the inner level for nested resampling for various reasons.
> 
> if this answers the question, pls close

Thank you for your suggestions!

**Comment by pat-s** [comment]
> Sorry, I forgot to mention that I also need to operate a by-year CV in the outer loop.

Ah ok. This would be a spatio-temporal setting then which we do not support in _mlr_.
Support for this is planned in https://github.com/mlr-org/mlr3spatiotemporal but not finished yet. 

As a workaround you can try using the year level as the factor input since you are accounting for the spatial autocorrelation already by using spatial paritioning (i.e. `SpCV`). This is not perfect but takes into account both spatial and temporal parts.

**Comment by berndbischl** [comment]
> > fixed index sets we do not currently support on the inner level for nested resampling for various reasons.
> 
> We do, see [here](https://mlr.mlr-org.com/articles/tutorial/resample.html#grouping-cv-with-fixed-predefined-indices).

apparently i dont know my "own" software anymore. or lets say this perfectly shows the results of cool group effort :)
great if we can reuse the grouping concept for this.

**Comment by melonki** [comment]
> > Sorry, I forgot to mention that I also need to operate a by-year CV in the outer loop.
> 
> Ah ok. This would be a spatio-temporal setting then which we do not support in _mlr_.
> Support for this is planned in https://github.com/mlr-org/mlr3spatiotemporal but not finished yet.
> 
> As a workaround you can try using the year level as the factor input since you are accounting for the spatial autocorrelation already by using spatial paritioning (i.e. `SpCV`). This is not perfect but takes into account both spatial and temporal parts.

Thank you for your suggestions!
