### ISSUE TITLE
Consider dropping `...` in `generateFilterValuesData()` 

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2650]
and only allow specification of filter args via `more.args`.

Using `...` causes unwanted nameclashes when a filter method has a similar named argument than the ones used in `generateFilterValuesData()`.

Using `...` might be more convenient in the first place, but passing a named list is def. more safe.
Also I see no reason why we should support two ways of doing the same thing. The current implementation causes confusion as it is unclear if one should use `...` or `more.args`.

The issue came up in #2639.

**Comment by larskotthoff** [comment]
Hmm, this sounds like quite a big change. Not sure if we want to do that for a package that's maintenance only.

**Comment by pat-s** [comment]
Hm, yes. Might break backward compat. 

You're right, we should probably live with having to use `more.args` for filters that have nameclash problems with "method".
