### ISSUE TITLE
tuneParams() triggers data.table reshape2::melt warning via melt() in R/generateFilterValues.R

### ISSUE THREAD

**Issue by wzel** [mlr-org/mlr#2652]
I hope this can be investigated without a minimal working example. I'm getting warnings while invoking tuneParams():

> In melt(out, value.name = "value", measure.vars = method,  ... :
>
> The melt generic in data.table has been passed a data.frame and will attem
> pt to redirect to the relevant reshape2 method; please note that reshape2 is
> deprecated, and this redirection is now deprecated as well. To continue usi
> ng melt methods from reshape2 while both libraries are attached, e.g. melt.l
> ist, you can prepend the namespace like reshape2::melt(out). In the next ver
> sion, this warning will become an error.

The only line of code matching the pattern `melt(out, value.name = "value", measure.vars = method,` is in `R/generateFilterValues.R`. The warning itself comes from data.table. Data.table has been deprecating reshape2::melt since version v1.12.4 -- see NEWS.md, note 8 for that version.

My package versions: mlr 2.15.0, data.table 1.12.4, reshape2 1.4.3, R 3.6.1.

**Comment by pat-s** [comment]
Thanks, we are aware of the issue and will fix it with the next release.
