### ISSUE TITLE
h2o.deeplearning early stopping: stopping_rounds is missing?

### ISSUE THREAD

**Issue by albersonmiranda** [mlr-org/mlr#2658]
Doesn't seems to be `stopping_rounds` in `getParamSet("classif.h2o.deeplearning")`.
I'm aware of `classification_stop` but it's not the same.
Am i missing something here?

**Comment by pat-s** [comment]
Haven't checked right now but it could very well be that a param is missing for a learner. You are welcome to open a PR which adds it 👍

**Comment by jakob-r** [comment]
It suprises me, that it is present for `regr.h2o.deeplearning`. Was there any reason to not include it for `classif.h2o.deeplearning`? @Coorsaa 
This is also true for other parameters as `stopping_metric`, `max_runtime_secs` and `stopping_tolerance`.
Also does it make sense that `regression_stop` is defined for `classif.h2o.deeplearning`?

**Comment by albersonmiranda** [comment]
Added PR.
