### ISSUE TITLE
gbm multiclass classification predict throws an error with only one observation

### ISSUE THREAD

**Issue by maksymiuks** [mlr-org/mlr#2673]
Hi,

I would like to report a bug, that I have met today.
Execution of the following example 
```
library(DALEX)
library(mlr)
task <- makeClassifTask(data = HR, target = "status")
learner_gbm <- makeLearner("classif.gbm", predict.type = "prob", par.vals = list(n.trees=280, n.minobsinnode=10, shrinkage=0.00736))
model <- train(learner_gbm, task)
predict(model, newdata = HR[1,])
```
throws a following error
```
Error in checkPredictLearnerOutput(.learner, .model, p) : 
  predictLearner for classif.gbm has returned a class numeric instead of a matrix!
```
Have to say that it is quite problematic for me. Also I assume it is a bug since for randomForest predict with only one observation works without any problem
```
library(DALEX)
library(mlr)
task <- makeClassifTask(data = HR, target = "status")
learner_rf <- makeLearner("classif.randomForest", predict.type = "prob")
model <- train(learner_rf, task)
predict(model, newdata = HR[1,])
```

Best,
Szymon

**Comment by pat-s** [comment]
Thanks. It is a bug because returned predictions with only one row will have class `named numeric` instead of `matrix` and hence one of our assertions fails (which checks for a matrix).
