### ISSUE TITLE
Learner notes are inaccurate since help pages are gone.

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#2695]
Since the individual help-pages for each Learner are gone some Learner notes are inaccurate.

We have sentences like `See ?regr.randomForest for information about se estimation.` But this does not make sense anymore.

Options
1) Simply remove references to non existent help-pages
2) Retrieve lost information from the learner help-page and put it to the note
3) Restore individual help-pages
4) ?

**Comment by pat-s** [comment]
Thanks. The notes live in `?makeLearner` now. I'll update the links.

**Comment by pat-s** [comment]
I could only find two instances when searching for terms `regr.randomForest` and `regr.featureless`. Both are now living in `?makeLearner` instead of having their individual help pages.
