### ISSUE TITLE
Test "plotFilterValues" should be optimized

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2697]
https://github.com/mlr-org/mlr/blob/eb14d977f6e0e88dbdc14dcd09e0c5df614736b6/tests/testthat/test_base_generateFilterValuesData.R#L62-L89

- No need to use "permutation importance" as the filter
- "randomForestSRC_importance" also is quite slow and causes problems if called iteratively
- should use the _vdiffr_ approach for comparing visual outputs

**Comment by berndbischl** [comment]
hi, but we are in maintenance mode only? is this is a bug?

**Comment by pat-s** [comment]
Its not a bug but extends the test time substantially for no reason:
We call `generateFilterValuesData()` on all filters even though we want to check `plotFilterValues()` only.
This is not needed here and I am also unsure if the underlying approach of checking plots is really that safe.

I came across a bunch of issues while solving #2689 and decided to clean up in #2696. Besides getting rid of the unnecessary `generateFilterValuesData()` calls I also check the created plots with the canonical way of checking ggplot2 plots using the _vidffr_ package.

**Comment by berndbischl** [comment]
but how much time does that take?

**Comment by pat-s** [comment]
Time difference of 27.87076 secs

This is a value for which I would say it should be optimized, especially if we can have that test at no time cost (which is now already part of #2696).
