### ISSUE TITLE
generateFeatureImportanceData() number of Monte-Carlo iterations and meaning of performance values

### ISSUE THREAD

**Issue by FilippoCMC** [mlr-org/mlr#2706]
Regarding generateFeatureImportanceData(), 
1) is there any recommendation for the number of Monte-Carlo iterations to use? 
2) does the sum of absolute values of the performance metric for each feature add up to the overall performance of the tested learner?

**Comment by pat-s** [comment]
1. No

2. AFAIK no. Adding up does not really make sense as it always depends on the error measure you use. I assume you think of something like accuracy which ranges between [0, 1]? Once you think about regression measures for which the optimum is the lowest value, adding up to "the overall performance" does not make sense.

Please consider asking "usage"/"interpretation" questions on [Stackoverflow](https://stackoverflow.com/questions/tagged/mlr) (using the `#mlr` tag) or [Cross-validated](https://stats.stackexchange.com/) in the future. Thanks.
