### ISSUE TITLE
generateFilterValuesData returns error

### ISSUE THREAD

**Issue by zhangkd5** [mlr-org/mlr#2714]
I got an error when running generateFilterValuesData on a minimal sample, as below.
It seems to be related to recent fix in #2653 , where data.table() function may not take "row.names" argument versus data.frame().

```r
generateFilterValuesData(task=iris.task, method="variance")
#> Error in data.table(name = row.names(fval), type = types, fval, row.names = NULL,  :
#>   column or argument 4 is NULL
```

**Comment by larskotthoff** [comment]
Works with the latest master. What version of mlr are you using?

**Comment by zhangkd5** [comment]
The issue is found on mlr version 2.16.0 with an older version of data.table (1.10.4 in my case). 

The error is resolved in the v2.17.0 by requiring data.table version >= 1.12.4, as data.table() function now silently ignores NULL arguments instead of throwing an error. 

I would still recommend removing argument "row.names = NULL" as below to avoid this particular behavior dependency on data.table. 
```r
# generateFilterValuesData.R, line 147--148:
    out = data.table(name = row.names(fval),
#      type = types, fval, row.names = NULL, stringsAsFactors = FALSE)
      type = types, fval, stringsAsFactors = FALSE)
```

**Comment by larskotthoff** [comment]
Ok, that sounds reasonable. Could you make a PR for this please?

**Comment by pat-s** [comment]
AFAIR this is not the only case why the data.table minimal version was raised. This also had to do with the split of the `melt` function.

Happy to merge a PR which passes all tests, otherwise I'd say the prio is not high enough to take action.
