### ISSUE TITLE
Really surprising result in tuneThreshold with three classes

### ISSUE THREAD

**Issue by TobiSonne** [mlr-org/mlr#2731]
I have a classification task with three classes (`Higher`, `Lower`, `Stagnation`).
Roughly 2/3 of the data is in one class `Higher`. I initially wanted to set the thresholds to get the optimal balanced accuracy. The results where really bad (worse than without threshold tuning) so I tried to tune the threshold to get the best accuracy to have a look on the results. They were even more surprising and bad:

```
> Predictions.rf.test <- predict(Model.rf, 
+                                task = Classification.Task,
+                                subset = test.id)
> 
> mlr::performance(Predictions.rf.test, measure = list(bac,
+                                                      acc))
      bac       acc 
0.3338171 0.6508621 
> # acc is not a big surprise because 2/3 of the data is in one class (Higher)
> 
> # "Best" threshold for acc:
> Threshold.rf <- tuneThreshold(Predictions.rf, measure = list(acc))$th
> Threshold.rf
  Higher         Lower            Stagnation 
0.442058919 0.004732797 0.553208283 
> 
> Predictions.rf.test <- 
+   setThreshold(Predictions.rf.test, threshold = Threshold.rf)
> 
> mlr::performance(Predictions.rf.test, measure = list(bac,
+                                                      acc))
       bac        acc 
0.33542977 0.09482759 
``` 

I am quite confused. If I set the threshold of `Higher` very low I always get an accuracy of 2/3 because 2/3 of the data is with class `Higher`. Of course this is trivial but how can the optimal threshold for `Higher` that high (0.442)? With this threshold the performance of accuracy gets really, really bad as you can see.
Am I doing something wrong probably?
Thank you very much!

**Comment by pat-s** [comment]
Hi,

thanks for posting your issue here.
Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

**Comment by jakob-r** [comment]
Thank you for reporting this bug. I can confirm that in `tuneThreshold` we apparently are always minimizing the performance measure. If you use `mmce` (basically `1-acc`) instead of `acc` everything works like expected.

**Comment by TobiSonne** [comment]
> Thank you for reporting this bug. I can confirm that in `tuneThreshold` we apparently are always minimizing the performance measure. If you use `mmce` (basically `1-acc`) instead of `acc` everything works like expected.

Thank you very much, in fact, now it works, although with `ber` instead auf `bac`!
