### ISSUE TITLE
Test error after {checkmate} v2.0 update

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2733]
In

https://github.com/mlr-org/mlr/blob/1f00838d032e1270a3997f6c4a3c887e375a5ca9/tests/testthat/test_tune_tuneParamsMultiCrit.R#L10-L13

due to

https://github.com/mlr-org/mlr/blob/1f00838d032e1270a3997f6c4a3c887e375a5ca9/R/tuneParamsMultiCrit.R#L51-L51

See https://app.circleci.com/jobs/github/mlr-org/mlr/1838

In {checkmate} 2.0 the error message was changed and hence the check for the error message fails.

More explanation about the fix in the linked PR.

cc @mllg

**Comment by mllg** [comment]
Hm, looks like the reverse dependency check only ran the subset of tests that run on CRAN. Sorry!

**Comment by pat-s** [comment]
> Hm, looks like the reverse dependency check only ran the subset of tests that run on CRAN. Sorry!

{mlr} does not have any checks on CRAN atm so its not your fault.
I will turn them back on in the next release though (most of them at least).
