### ISSUE TITLE
Enable tests on CRAN again

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr#2735]
So we get revdepchecks from other packages.

We won't be able to enable all tests but it should be possible for at least 90%.
Tests are now much more stable than they were at the time when we turned them off on CRAN.

Testing in branch `cran-check`.

**Comment by berndbischl** [comment]
are you really really sure? there were multiple reasons to disable them, most of which you cannot simulate on github / travis

**Comment by pat-s** [comment]
Our test suite is much more stable now and having tests running on CRAN has its advantages.

Also remember the latest discussion here about revdeps - having tests on CRAN that break by revdepchecks from other packages is neat - and we won't have that on external CI systems.

**Comment by pat-s** [comment]
Giving up on it, mainly because of many limitations on CRANs side with spurious errors that are not traceable and time limitations.
