### ISSUE TITLE
ksvm fails for if task has (too) many factor variables.

### ISSUE THREAD

**Issue by bommert** [mlr-org/mlr#2771]
When I use the example code from makeModelMultiplexer and use my task instead of the iris task, tuning does not work. With the iris task, it does work. With my task without a model multiplexer (single learners), tuning works, too.
Can you please help me figure out what the problem is?

```
# download data into working directory
# http://www.salvirt.com/?smd_process_download=1&download_id=4128
# description of data set: http://www.salvirt.com/b2bdataset/

data = read.csv2("Salvirt_B2B_ML_dataset.csv", header = TRUE)
task = makeClassifTask(data = data, target = "Status")

# this code is taken from ?makeModelMultiplexer
# the only change is using "task" instead of "iris.task" in tuneParams
set.seed(123)
library(BBmisc)
bls = list(
  makeLearner("classif.ksvm"),
  makeLearner("classif.randomForest")
)
lrn = makeModelMultiplexer(bls)
ps = makeModelMultiplexerParamSet(lrn,
  makeNumericParam("sigma", lower = -10, upper = 10, trafo = function(x) 2^x),
  makeIntegerParam("ntree", lower = 1L, upper = 500L)
)
rdesc = makeResampleDesc("CV", iters = 2L)
ctrl = makeTuneControlRandom(maxit = 10L)
res = tuneParams(lrn, task, rdesc, par.set = ps, control = ctrl)
```
[Tune] Started tuning learner ModelMultiplexer for parameter set:
                               Type len Def                            Constr Req Tunable Trafo
selected.learner           discrete   -   - classif.ksvm,classif.randomForest   -    TRUE     -
classif.ksvm.sigma          numeric   -   -                         -10 to 10   Y    TRUE     Y
classif.randomForest.ntree  integer   -   -                          1 to 500   Y    TRUE     -
With control class: TuneControlRandom
Imputation value: 1
[Tune-x] 1: selected.learner=classif.rand...; ntree=152
[Tune-y] 1: mmce.test.mean=      NA; time: 0.0 min
[Tune-x] 2: selected.learner=classif.rand...; ntree=420
[Tune-y] 2: mmce.test.mean=      NA; time: 0.0 min
[Tune-x] 3: selected.learner=classif.rand...; ntree=244
[Tune-y] 3: mmce.test.mean=      NA; time: 0.0 min
[Tune-x] 4: selected.learner=classif.rand...; ntree=365
[Tune-y] 4: mmce.test.mean=      NA; time: 0.0 min
[Tune-x] 5: selected.learner=classif.rand...; ntree=69
[Tune-y] 5: mmce.test.mean=      NA; time: 0.0 min
[Tune-x] 6: selected.learner=classif.ksvm; sigma=0.00389
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 224, 218

```
# if I do not use a model multiplexer, tuning works fine
ps2 = makeParamSet(makeNumericParam("sigma", lower = -10, upper = 10, trafo = function(x) 2^x))
tuneParams("classif.ksvm", task, rdesc, par.set = ps2, control = ctrl)

ps3 = makeParamSet(makeIntegerParam("ntree", lower = 1L, upper = 500L))
tuneParams("classif.randomForest", task, rdesc, par.set = ps3, control = ctrl)
```

**Comment by jakob-r** [comment]
There seems to be a problem with tasks that contain (only?) factor columns: Here is a simpler example:
```r
data = mtcars[,c("cyl", "vs", "am", "gear", "carb")]
for (cn in colnames(data)) data[[cn]] = as.factor(data[[cn]])
task = makeClassifTask(data = data, target = "am")
bls = list(
  makeLearner("classif.ksvm"),
  makeLearner("classif.randomForest")
)
lrn = makeModelMultiplexer(bls)
rdesc = makeResampleDesc("CV", iters = 2L)
setHyperPars(lrn, selected.learner = "classif.randomForest")
resample(lrn, task, rdesc)
```

**Comment by jakob-r** [comment]
One problem is kernlabs ksvm predict method, which just silently drops columns that contain NAs :confused:

```r
library("kernlab")
data = mtcars[,c("cyl", "vs", "am", "gear", "carb")]
for (cn in colnames(data)) data[[cn]] = as.factor(data[[cn]])
mod = ksvm(carb~., data)
newdata = data
newdata[1:10,1] = NA
y = kernlab::predict(mod, newdata = newdata)
length(y)
nrow(newdata)
```

The second problem is: Why do we even create NAs?

**Comment by jakob-r** [comment]
Why do we create NAs? We have factor levels that are just present for training. And because `.learner$fix.factors.prediction` is `TRUE` for the ModelMultiplexer, these factor leves are set to NA. However, it is `FALSE` for the normal `Learner classif.ksvm`. That’s why just training ksvm works fine.

The only plausible solution would be to determine `fix.factors.prediction` dynamically, based on the active learner.

**Comment by bommert** [comment]
Thank you Jakob for looking into this so quickly! If I do
```
lrn$fix.factors.prediction = FALSE
```
my code seems to work. It's not only ksvm that has a problem. randomForest, ranger, nnet (and probably other learners) return NA for mmce.test.mean (see my code above).

**Comment by jakob-r** [comment]
The problem is that you have a task that only contains factors. That does not excuse that mlr fails without meaningful errors but it is no surprise that many algorithms do not cope well. You could have a look at the vtreat package to preprocess your data or try mlrCPO to do impact encoding. 

I will also check why NAs are returned.

**Comment by jakob-r** [comment]
The reason is simple. If `fix.factors.prediction` is `TRUE` the test data will contain `NAs` instead of unknown (to the training) factor levels. These NAs turn up as NAs for the predicted label. These NAs result in NAs for the aggregated meassure. You could write a measure that incorporates these NAs, by counting them as mismatches.

**Comment by pat-s** [comment]
@bommert @jakob-r Can we close here?

@jakob-r Do you want to add a meaningful message to the user when this case occurs? Maybe switching the title of this issue could also help.

**Comment by pat-s** [comment]
Jakobs PR is a good solution for this. Feel free to re-open if not.
