### ISSUE TITLE
Default feature importance of classif.randomForestSR is not FALSE

### ISSUE THREAD

**Issue by purod** [mlr-org/mlr#2772]
## Prework
Below is the code I used, "ano.cla.filter" is a filtering method defined by myself

set.seed(132541) # repeatable
lrn = makeFilterWrapper(learner = makeLearner( "classif.randomForestSRC", 
                                               predict.type = "prob", 
                                               ntree=100,
                                               importance="permute"), 
                        fw.method = "ano.cla.filter", 
                        fw.threshold = 0.5)
rdesc = makeResampleDesc("RepCV",folds=3L,reps=2L, stratify = TRUE,predict="both")

AllGenes_Model = resample(learner = lrn, 
                          task = cli.task, 
                          resampling=rdesc, 
                          show.info = F, 
                          models = TRUE,
                          measures = list(mlr::auc))

The default value for importance is FALSE when you check with getParamSet("classif.randomForestSRC")
However, I can still get values for feature importance when using getFeatureImportance. Then I assume that the importance I get could be the permute importance. However, when I set the importance as "permute", the features set I selected out totally changed. 

## Question

What is the default feature importance of classif.randomForestSR?
Why does the value of importance change the feature set selected out?
```

>

**Comment by pat-s** [comment]
Hi,

please try to format your issue a bit better next time. This makes it easier to read and understand.

> What is the default feature importance of classif.randomForestSR?

You can find this information in the learner.

> Why does the value of importance change the feature set selected out?

Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

**Comment by purod** [comment]
Thank you. I will create a reproducible example later.

**Comment by pat-s** [comment]
Closing due to no response.
