### ISSUE TITLE
Why is data not preprocessed in the Use case?

### ISSUE THREAD

**Issue by maozdd** [mlr-org/mlr#2774]
Hi, I'm new to mlr package and machine learning. I noticed that the BostonHousing dataset was not normalized in the Regression case. Why is that? In my understanding, normalization of feature vectors prior to feeding them to the SVM is very important.
Thank you.

**Comment by pat-s** [comment]
In ML you can do everything and nothing :) Our tutorials aim to be small examples to showcase particular problems.
They do not aim to make sense from a scientific or "best practice" point of view.

Also, normalization is not always required. It always depends on the use case.

If you are new, please consider using {mlr3} as mlr is deprecated for more than a year already.
