### ISSUE TITLE
OversampleWrapper with CV

### ISSUE THREAD

**Issue by Haridut** [mlr-org/mlr#2784]
If I set up a CV with a oversampling wrapper, would the oversampling be applied only to the training set (as it should be for an unbiased estimate) ? Thanks.

**Comment by pat-s** [comment]
The manual pages of the respective wrappers and the articles (https://mlr.mlr-org.com/articles/tutorial/over_and_undersampling.html#simple-over--and-undersampling) should give you answers to this question.

If the "estimate can be considered unbiased" is somewhat subjective here as "unbiased" can mean a lot of things.

**Comment by jakob-r** [comment]
The documentation might not be 100% precise

> Internally uses oversample or undersample before every model fit.

But as you can see here https://github.com/mlr-org/mlr/blob/master/R/OverUndersampleWrapper.R the oversampling is done directly before training and not before the CV.
