### ISSUE TITLE
Error in ibrier measure

### ISSUE THREAD

**Issue by bommert** [mlr-org/mlr#2789]
The code
```r
set.seed(1)
rin = makeResampleInstance(makeResampleDesc("CV", iters = 2), task = wpbc.task)
lrn = makeLearner("surv.coxph", x = TRUE)
resample(lrn, wpbc.task, resampling = rin, measures = list(ibrier))
```
throws the error:
```r
Error in `[.data.table`(newdata, , tn) : 
  j (the 2nd argument inside [...]) is a single symbol but column name 'tn' is not found. Perhaps you intended DT[, ..tn]. This difference to data.frame is deliberate and explained in FAQ 1.1.
```

I believe that this error can be fixed by adding *with = FALSE* in line 1373 in file measures.R such that the new line is
```r
perror = pec(probs, f, data = newdata[, tn, with = FALSE], times = grid, exact = FALSE, exactness = 99L,
      maxtime = max.time, verbose = FALSE, reference = FALSE)
```
Also, the result of *crps(perror, times = max.time)* is a crps object that can be coerced to numeric while
```r
crps(perror, times = max.time)[1L, ]
```
throws the error:
```r
Error in crps(perror, times = max.time)[1L, ] : 
  incorrect number of dimensions
```
Interestingly, when printing the crps object, then the score is put into a matrix.
Maybe you have a better idea than using as.numeric to access the number stored in the crps object.

**Comment by pat-s** [comment]
There were some other issues with survival datasets and ibrier in the past. Have you read #2426 (and friends)?

**Comment by bommert** [comment]
I understand that there have been more problems with the ibrier measure. I am only beginning to work on survival data sets, so I do not fully understand all issues yet. Maybe someone with more expertise on survival data can comment on how this bug can be fixed?
