### ISSUE TITLE
Error in hyperparameter tuning with scientific notation for lower/upper boundaries

### ISSUE THREAD

**Issue by tkuehn13** [mlr-org/mlr#279]
Within hyperparameter tuning I ran into several errors when using scientific notation for lower (or upper) tuning boundaries. Probably the error occurs because of a rounding error!?

example 1:
```R
library(mlr)
lrn = makeLearner("classif.gbm", predict.type = "prob")

ps = makeParamSet(makeNumericParam("shrinkage", lower = 1e-5, upper = 1e-4))
ctrl = makeTuneControlIrace(maxExperiments = 300L)
rdesc = makeResampleDesc(method = "Holdout")
lrn.tune = makeTuneWrapper(lrn, resampling = rdesc, par.set = ps, 
  control = ctrl, measure = list(mmce))

set.seed(123)
res = resample(lrn.tune, task = sonar.task, rdesc, measures = list(mmce))
```

throws error:
```R
Trying to add infeasible x values to opt path: shrinkage=0
```

---
example 2: 
```R
library(mlr)
lrn = makeLearner("classif.logreg")
lrn2 = makeUndersampleWrapper(lrn, usw.rate = 1)

ps = makeParamSet(makeNumericParam("usw.rate", lower = 2.91e-3, upper = 0.003))
ctrl = makeTuneControlIrace(maxExperiments = 100L)
rdesc = makeResampleDesc(method = "Holdout")
lrn.tune = makeTuneWrapper(lrn2, resampling = rdesc, par.set = ps, 
  control = ctrl, measure = list(mmce))

set.seed(123)
res = resample(lrn.tune, task = sonar.task, rdesc, measures = list(mmce))
```

throws error: 
```
Trying to add infeasible x values to opt path: usw.rate=0.0029
```

I'm currently using mlr version 2.3.

**Comment by larskotthoff** [comment]
mlr uses the ParamHelpers function `convertParamSetToIrace` internally, which requires the precision (`digits`) to be set. mlr doesn't expose this parameter and simply uses the default of 4.

One solution to this problem would be to expose it, but IMHO it would be nicer if the ParamHelpers function figured out the number of digits automatically. @berndbischl, what's your opinion on this?

**Comment by berndbischl** [comment]
Both things are already solved in PH on GH.
If this goes on CRAN (soon) I will simply add the two example here as unit tests
