### ISSUE TITLE
Warnings with xgboost post R 4.0 using pre 4.0 models

### ISSUE THREAD

**Issue by TylerGrantSmith** [mlr-org/mlr#2791]
I have a package that uses an mlr model built in R3.6 using `xgboost` which had been exported to an RDS.  This worked fine pre R4.0, but now when the model is loaded I am getting the following warnings:

```r
The model had been generated by XGBoost version 1.0.0 or earlier and was loaded from a RDS file. 
We strongly ADVISE AGAINST using saveRDS() function, to ensure that your model can be read in 
current and upcoming XGBoost releases. Please use xgb.save() instead to preserve models for the 
long term. For more details and explanation, see 
https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html
```

Is this avoidable?  Can I somehow resave the mlr model in a way to avoid this warning?

**Comment by pat-s** [comment]
This has nothing to do with {mlr}.
The error message is quite descriptive. I also do not think this has anything to do with the R version but only with the {xgboost} version.

Install the same version of {xgboost} in R4 as you had in R3 and things should work.
