### ISSUE TITLE
Figure missing in html-tutorial

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#2797]
In the HTML Version of the tutorial some figures are missing:
For example in
https://mlr.mlr-org.com/dev/articles/tutorial/nested_resampling.html
the figure is linked to
https://raw.githubusercontent.com/pat-s/mlr/master/vignettes/tutorial/devel/pdf/img/nested_resampling.png
but is actually here
https://raw.githubusercontent.com/mlr-org/mlr/master/vignettes/pdf/img/nested_resampling.png

**Comment by pat-s** [comment]
Thanks. Not sure how these urls ended up there and how long they have been missing unnoticed :/

**Comment by jakob-r** [comment]
thanks for the fix
