### ISSUE TITLE
RLearner_regr_gausspr.R

### ISSUE THREAD

**Issue by DrZhaoJie** [mlr-org/mlr#2802]
Dear Prof
      I really enjoy your R code: RLearner_regr_gausspr.R. I wonder how can I tune the hyperparameter (sigma)? Besides, do you have the demo to run R code in RLearner_regr_gausspr.R? Thank you very much!

**Comment by pat-s** [comment]
See our [tutorial on tuning](https://mlr.mlr-org.com/articles/tutorial/tune.html) for more information.

Also please consider using {mlr3} instead of {mlr} - if the learner is not yet available in {mlr3} please request it in [mlr3learners](https://github.com/mlr-org/mlr3learners).
