### ISSUE TITLE
selectFeatures error

### ISSUE THREAD

**Issue by DrZhaoJie** [mlr-org/mlr#2808]
Hi, I really enjoy your package, I run the code as following. As you say, I set the seed, but it still produced different outcomes every time. How can I reproduce my work and outcomes, then? Thank you very much!
`set.seed(3333)
oo <- selectFeatures(learner = "regr.gausspr", task = train.task0, 
                     resampling = makeResampleDesc("CV"), control = makeFeatSelControlExhaustive())`

**Comment by pat-s** [comment]
Hi,

thanks for posting your issue here.
Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

**Comment by pat-s** [comment]
Closing due to no response.
