### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by DrZhaoJie** [mlr-org/mlr#2809]
Dear professor,
     I really enjoy your package and learned a lot from it. I tried to use benchmark function to compare different models with different tasks or learners. But this function gave the performance without tuning the parameters, right? How can I get the performance of different models in the train and test dataset with the parameters tuned conveniently? Thank you very much!

**Comment by berndbischl** [comment]
hi this is not an issue but a basic user question @pat-s 

this is answered in the tutorial here

https://mlr.mlr-org.com/articles/tutorial/nested_resampling.html
eg see "Example 1: Two tasks, two learners, tuning" 
on that page
