### ISSUE TITLE
lrn = makeLearner("regr.gausspr", importance = c("permutation"))

### ISSUE THREAD

**Issue by DrZhaoJie** [mlr-org/mlr#2810]
Hi, I really enjoy your package. I had a problem. When I run this: 
`lrn = makeLearner("regr.gausspr", importance = c("permutation"))
`

it produced this error:Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  regr.gausspr: Setting parameter importance without available description object!
Did you mean one of these hyperparameters instead: kernel degree scale
You can switch off this check by using configureMlr!

How may I solve this bug?

**Comment by pat-s** [comment]
Hi,

thanks for posting your issue here.
Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.
