### ISSUE TITLE
Feature names stored in `object` and `newdata` are different! using mlr package

### ISSUE THREAD

**Issue by agneswattel** [mlr-org/mlr#2811]
## Prework
I have used search terms "mlr", "xgboost", and ''multilabel", but I could not find any hits on github.

## Description
I am trying to make a multilabel classification model for XGBoost. I have one that works for RF, but when I try this code below for XGBoost I get the error:

"Error in predict.xgb.Booster(m, newdata = data.matrix(.newdata), ...) : 
Feature names stored in 'object' and 'newdata' are different!

And as I did not assign it train data and test data or 'newdata' (this is done by the makeResampleDesc() ) I don't know how to fix this error.

## Reproducible example
Example data
```
library(mlr)
library(xgboost)
lab <- c("l1","l2","l3","l4","l5")
age <- c(round(rnorm(120,mean = 50,sd = 10)))
sex <- c(round(rnorm(120,mean = 0.5,sd = 0.2)))
l1 <- as.logical(c(round(rnorm(120,mean = 0.5,sd = 0.2))))
l2 <- as.logical(c(round(rnorm(120,mean = 0.5,sd = 0.2))))
l3 <- as.logical(c(round(rnorm(120,mean = 0.5,sd = 0.2))))
l4 <- as.logical(c(round(rnorm(120,mean = 0.5,sd = 0.2))))
l5 <- as.logical(c(round(rnorm(120,mean = 0.5,sd = 0.2))))
data <- as.data.frame(cbind(age,sex,l1,l2,l3,l4,l5))
data[,lab]<- lapply(data[,lab],FUN = as.logical)
```
Create learner
```
learner <- "classif.xgboost"
lrn <- makeLearner(learner, objective = "multi:softprob") 
lrn <- makeMultilabelClassifierChainsWrapper(lrn, order = NULL) 
lrn <- setPredictType(lrn,"prob")
```
Create grid
```
ps <- makeParamSet(
  makeDiscreteParam("max_depth", values = c(1,3,5)),
  makeDiscreteParam("eta",values = c(0.001,0.01,0.1))
)
```
Set up resampling method and tuning
```
ctrl <- makeTuneControlGrid()
rdesc <- makeResampleDesc(method = "CV",iters = 5L)
```
Initiate evaluation vector
```
v_f1 <- c()
v_max_depth <- c()
v_eta <- c()
```
Actual model training
```
task <- makeMultilabelTask(data = data, target = lab) 
   
res <- tuneParams(lrn,task = task,resampling = rdesc, par.set = ps,
       control = ctrl, measures = multilabel.f1)

v_f1 <- c(v_f1,as.vector(res$y[1]))
v_max_depth <- c(v_max_depth,as.vector(res$x[1]))
v_eta <- c(v_eta,as.vector(res$x[4]))
```

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(si = TRUE)`) and include the output.
(I don't understand this part)

## Expected output
Expected output would be no errors when I am running the script above.

**Comment by pat-s** [comment]
To my knowledge this Q should have been answered multiple times already on the web / other repos. 

Besides, I suggest using mlr3 instead of mlr.

**Comment by agneswattel** [comment]
Can you provide me a link? I cannot find it anywhere.
Further, the mlr3 that you suggested does not support multilabel classification yet. I already aswered a previous post from you about that here https://stackoverflow.com/questions/67387608/warning-unknown-or-uninitialised-column-ntree-when-trying-to-pass-hyperpar?noredirect=1#comment119132750_67387608

**Comment by pat-s** [comment]
I can't provide a link, sorry. I've seen this error in relation to XGBoost and ranger multiple times already and it usually came down to how variables were treated within the respective package.

I think it should be possible to find a solution in the web - I don't think this is a new issue. Not entirely sure though of course.

Thanks for your reprex. Next time, please include it as one block for easy c/p - preferably using the {reprex} package.

**Comment by pat-s** [comment]
@agneswattel Sorry I could not be of any help here. Did you manage to find a way around? 

[Here](https://github.com/dmlc/xgboost/issues?q=Feature+names+stored+in+object+and+newdata+are+different) is a link from the xgboost GH repo - though I am not sure if this is what I mean in my previous comment.

In mlr3 multilabel support does [not yet exist](https://mlr3book.mlr-org.com/special-tasks.html?q=multilabel#multilabel) as stated in the mlr3book - posting an issue in {mlr3multioutput} could help to lift the topic in priority :)
