### ISSUE TITLE
'surv.CoxBoost' and Integrated Learners 

### ISSUE THREAD

**Issue by emucaki** [mlr-org/mlr#2836]
I was attempting to implement some legacy code using 'mlr' and 'CoxBoost', and I received a "Couldn't find learner" error when trying to create a 'surv.CoxBoost' learner:
> learner= makeLearner("surv.CoxBoost")

I've seen code online that suggests this (and "surv.cv.CoxBoost") was once known to 'mlr', but it appears to be no longer listed as an [Integrated Learner](https://mlr.mlr-org.com/articles/tutorial/integrated_learners.html#survival-analysis-10-). 

I understand that 'mlr' is no longer supported, I was just hoping to understand why CoxBoost has (apparently) been excluded. And do you think installing an older release of 'mlr' would resolve the issue?

**Comment by pat-s** [comment]
Every once in a while we remove learners which upstream packages were removed from CRAN. I assume this also happened here.

You could ofc try to install an older version of {mlr} from the archives but I'd highly suggest moving forward and using `surv.coxboost` from {mlr3} - see https://mlr-org.com/learners.

**Comment by emucaki** [comment]
Thank you!
