### ISSUE TITLE
factor levels issues in R

### ISSUE THREAD

**Issue by sarkar453** [mlr-org/mlr#2863]
I have written a code on logistic regression in r language but it is showing factor level issue
# Load required libraries
library(titanic)
library(dplyr)
library(ggplot2)
library(caret)

# Load Titanic dataset
data("titanic_train")
titanic_data <- titanic_train

# Explore the dataset
str(titanic_data)
summary(titanic_data)

# Preprocess the data
# Remove unnecessary columns
titanic_data <- select(titanic_data, -c(PassengerId, Name, Ticket, Cabin))

# Impute missing values
titanic_data$Age[is.na(titanic_data$Age)] <- median(titanic_data$Age, na.rm = TRUE)
titanic_data$Embarked[is.na(titanic_data$Embarked)] <- "S"

# Convert categorical variables to factors
titanic_data$Survived <- factor(titanic_data$Survived)
titanic_data$Pclass <- factor(titanic_data$Pclass)
titanic_data$Sex <- factor(titanic_data$Sex)
titanic_data$Embarked <- factor(titanic_data$Embarked)
sum(is.na(titanic_data))
# Split the data into training and testing sets
set.seed(123)
train_index <- createDataPartition(titanic_data$Survived, p = 0.8, list = FALSE)
train_data <- titanic_data[train_index, ]
test_data <- titanic_data[-train_index, ]

# Build logistic regression model
log_model <- glm(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
                 data = train_data, family = "binomial")

# Summarize the model
summary(log_model)

str(titanic_data)

# Build logistic regression model
log_model <- glm(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
                 data = train_data, family = "binomial")
# Make predictions on the test set
predictions <- predict(log_model, newdata = test_data, type = "response")
predicted_classes <- ifelse(predictions > 0.5, 1, 0)

# Evaluate model performance
conf_matrix <- confusionMatrix(as.factor(predicted_classes), as.factor(test_data$Survived))
print(conf_matrix)

**Error in model.frame.default(Terms, newdata, na.action = na.action, xlev = object$xlevels) : 
  factor Embarked has new levels**

**Comment by larskotthoff** [comment]
What happens is that when you're splitting into training and test the factor levels are not consistent between the two. Use the [resample function](https://mlr.mlr-org.com/articles/tutorial/resample.html) instead of partitioning manually, which allows you to stratify to prevent that from happening.

In general, consider using the successor mlr3 instead of mlr, which is deprecated.
