### ISSUE TITLE
Use of makeDiscreteLearnerParam usefull for functions?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#293]
Some functions expect a function as a Parameter Setting.
As for now we use `makeDiscreteLearnerParam` although `ParamHelpers` offers `makeFunctionLearnerParam` (which is nowhere used).
The state now works fine for **mlr** itself but causes problems with OpenML as reported here: https://github.com/openml/r/issues/62 .

**Comment by berndbischl** [comment]
can you please reference 2 or 3 relevant examles?

**Comment by jakob-r** [comment]
* `RLearner_*_blackboost.R` L:7
* `RLearner_*_glmboost.R` L:7
* `RLearner_classif_mda.R` L:11
* `RLearner_regr_mob.R` L:13

**Comment by berndbischl** [comment]
Ok, thats what I thought. So here is the thing:

Option 1) We keep this as discrete params. The choices already there as values are likely sufficient for 99% of use cases. And you can now tune over these choices, which you cannot if we have an unstructured function param. And the bug in OML is simply a stupid bug, and not a real problem. We need to upload the name of the value to OML, which is a string. And not the value itself, which is an arbitrary R object. Exactly for this reason I invented the names of the values....

What is the only disadvanatge: Although the learner allows arbitary functions for these params, we do not allow to pass them. This restricts expert users. Although you could also use mlr's option "on.par.out.of.bounds" to disable such a check. So everything is kinda OK I guess for now..

Option 2) We change these params to FunctionParams. Then you cannot tune over these. And you have no value checks for the most common cases. Which I think is not so nice.

Hmm, is this actually true? I mean, in the learner we can set to "FunctionParam" but for tuning we can specifiy a "DiscreteParam"? Right? 

Option 3) We change to FunctionParam but also add a "values" field here for that class. Which specifies the "most common choices". So the learner knows these. 


Is Option 3 best? 

@mllg @kerschke You should also read this for GSOC I guess

**Comment by berndbischl** [comment]
Side remark: on.par.out.of.bound is a suboptimal name because it actually checks infeasibility which can be triggered by more than an out-of-bounds problem. as renaming is not user-friendly at least the doc should describe this.

**Comment by jakob-r** [comment]
I think Option 3 is the best to not run into trouble with `ParamHelpers::isFeasible`
In `mlr` we can set the hyperParams by the name attribute of the list but that is not *feasible*
```r
> ps = makeParamSet(
+ makeDiscreteParam("a", values = list(a = mean, b = median)),
+ makeDiscreteParam("b", values = 1:10))
> isFeasible(ps, list(a = mean, b = 1))
[1] TRUE
> isFeasible(ps, list(a = "a", b = 10))
[1] FALSE
```

**Comment by jakob-r** [comment]
We have talked about it. I thin everything is fine if you use `ParamHelpers::discreteNameToValue`. It just stays an issue in OpenML
