### ISSUE TITLE
Do we really need the special code in regr.randomForest for se estimation if we have that in BaggingWrapper?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#32]

**Comment by berndbischl** [comment]
We need to update the code and take that here into account

https://github.com/zmjones/edarf

**Comment by zmjones** [comment]
most of my code comes from [randomForestCI](https://github.com/swager/randomForestCI). their variance estimator requires as input a matrix of bootstrap weights and the tree predictions as well, which neither `rfsrc` nor `cforest` provide. There is code to do both of those things in [edarf](http://github.com/zmjones/edarf/). `randomForest` doesn't return a proper bootstrap weights matrix, only giving you an indicator of whether an observation was in the bootstrap sample for a tree, not the number of times it appears. Wager has also [fixed this](https://github.com/swager/randomForest) but I don't think it has been merged yet. I assume it will be at some point though.

**Comment by zmjones** [comment]
outdated/superseded by discussion in #595. will open an issue for the baggingwrapper se estimators when that is closed

**Comment by berndbischl** [comment]
ok

**Comment by berndbischl** [comment]
in general i would like to have the issues stay really open until they are solved, but what you say seems ok to me
