### ISSUE TITLE
tuneParams: Budget param needs to be reviewed. 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#336]
With @kerschke. Online.

Especially stuff like CMAES

**Comment by berndbischl** [comment]
For grid search we should set resolution in a smart way as a default, if only budget is given.

**Comment by berndbischl** [comment]
I can live with the warning in GENSA, if budget is exceeded, but better dont use FIXME_PK, but only FIXME.

**Comment by berndbischl** [comment]
try to test  that budget is truly respected, do it in a loop for all methods where possible.

**Comment by berndbischl** [comment]
we should have "budget" for multicrit as well then.

**Comment by kerschke** [comment]
> For grid search we should set resolution in a smart way as a default, if only budget is given.

That's kind of difficult as it depends on the type of parameter. Remember that the parameters are not passed to `makeTuneControlGrid`...

> I can live with the warning in GENSA, if budget is exceeded, but better dont use FIXME_PK, but only FIXME.

Ok, there's no problem in changing it. Just wanted to make sure, that I find *my* FIXMEs :-)

> try to test that budget is truly respected, do it in a loop for all methods where possible.

Ok. I'll add it to my to-do's.

> we should have "budget" for multicrit as well then.

Again, I'll add it to my to-do's.

> Especially stuff like CMAES

Let's talk about it, so it becomes more clear.

**Comment by berndbischl** [comment]
status here? ping
@kerschke
