### ISSUE TITLE
we should be able to tune randomForest just with the OOB estimator

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#338]
This is faster we do not need a CV here necesarrily. What other models provide that estimator?
Maybe we should generalize this.

@kerschke:  Relevant for gsoc.

**Comment by jakob-r** [comment]
I suppose you are talking about the `se.method` from `regr.randomForest` right? So we should ad a `oobStandardError`?
At this opportunity a closer look at the old StandardError functions would be nice as well.

**Comment by berndbischl** [comment]
> I suppose you are talking about the se.method

No, I am not, I am talking about evaluating the RF with its internal OOB estimator. This can be used for faster model selection

**Comment by jakob-r** [comment]
I am still not totally clear about the internal OOB estimator.
My naive way would be
```r
oobStandardError = function(.learner, .model, .newdata, ...) {
  rf.preds = predict(.model$learner.model, newdata = .newdata, predict.all = TRUE)
  mean.responses = rf.preds$aggregate
  sd.responses = apply(rf.preds$individual, 1, sd)
  return(cbind(mean.responses, sd.responses))
}
```

**Comment by zmjones** [comment]
you just mean that instead of doing further resampling on any learner which generates an OOB error estimate to just use that? i'd guess there are many methods other than rf that use resampling internally and can do this. that would indeed be much faster

**Comment by berndbischl** [comment]
Yes, while you are tuning your params, instead of doing a crossval for each point evaluation, you just train the model. Then access its OOB estimator, which is in the learner.model. You return this as the performance measure. 

Actually this can already be done, by simply using Holdout, with all data for training, and coding your own perfmeasure, which accesses the learner.model oob info and returns this. 

tuneParams would then work without any changes.

**Comment by berndbischl** [comment]
Here is some code that might help
```
library(mlr)

oobperf = makeMeasure("oobperf", minimize = TRUE, properties = c("classif", "classif.multi"),
  fun = function(task, model, pred, extra) {
  err = model$learner.model$err.rate
  err[nrow(err), "OOB"]
})

ps = makeParamSet(
  makeIntegerParam("ntree", lower = 1L, upper = 100L),
  makeIntegerParam("mtry", lower = 1L, upper = 4L)
)

ctrl = makeTuneControlGrid(resolution = 3)
lrn = makeTuneWrapper("classif.randomForest", par.set = ps, control = ctrl, measures = oobperf,
  resampling = makeResampleDesc("Holdout", split = 0.99))

z = crossval(lrn, iris.task, iters = 10L)

```

**Comment by zmjones** [comment]
`randomForest` returns the oob predictions as the `predicted` element of the return object. so you could feed this into whatever measure you like rather than using mce or mse which are your only choices when using the `err.rate` element. I haven't looked at it in detail but it may also be the case that `predict.randomForest` w/o the `newdata` arg (which I believe is always used by mlr) simply extracts this argument, though of course there is other overhead.

**Comment by berndbischl** [comment]
ok thx

**Comment by PhilippPro** [comment]
Remark: Maybe you want to tune a measure which is based on probability in the classification case, like AUC, logarithmic loss or brier score. Then you could be interested in the Probability-Prediction of the OOB. 
From my own implementation I know that these are provided at least for randomForest, ranger and randomForestSRC (in randomForest a new "predict" is necessary unfortunately)

rfsrc(Species ~ ., data=iris)$predicted.oob
ranger(Species ~ ., data=iris, probability = TRUE)$predictions
predict(randomForest(Species ~ ., data=iris), type = "prob")

**Comment by pat-s** [comment]
@mllg 	Is this a case we should consider for _mlr3_?
