### ISSUE TITLE
randomForest se.method = jackknife needs keep.inbag == TRUE

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#340]
I am not sure how to deal with it best. But now it just fails without any good message.
Maybe in regr.randomForest.R:11
```r
#...
makeDiscreteLearnerParam(id = "se.method", default = "bootstrap", 
  values = c("bootstrap", "jackknife", "noisy.bootstrap"), 
  requires = quote(se.method == "jackknife" || !keep.inbag)),
#...
```
?
Or setting it accordingly automatically?

**Comment by zmjones** [comment]
can we just put a condition in the predict method that stops if `se.method == "jackknife" & is.null(.model$learner.model$inbag)`? This could also go in the jackknife function.

**Comment by berndbischl** [comment]
zach, yes, please just add this as an arg check for now and stop with a meaningful err msg
