### ISSUE TITLE
Setting par.vals in makeRLearner is Horror

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#344]
Do we really want this?
I try to create a feasible learner like this

``` r
> lrn = makeLearner("classif.lqa", penalty = "adaptive.lasso", lambda1 = 0.1, lambda2 = 0.2)
Error in isRequiresOk(learner$par.set, learner$par.vals) : 
  The following parameter settings do not meet the requirements: lambda1=0.1 needs expression(penalty %in% c("enet", "fused.lasso", "icb", "licb", "weighted.fusion")), lambda2=0.2 needs expression(penalty %in% c("enet", "fused.lasso", "icb", "licb", "weighted.fusion"))
```

and it does not work. Because the predefined values in `par.vals` fu*\* everything up.
We have to deal with it in `makeLearner` or better in `makeRLearnerInternal` I guess. It's not easy for me to decide for now.

**Comment by berndbischl** [comment]
I thought we just discussed this?
And why is this a bug?

**Comment by berndbischl** [comment]
Options to resolve this:

a) Remove the predefined values. Then the learner is not creatable anymore without setting explicit values. But we can live with that.

b) Remove parameters whose requirements are not satisfied anymore in setHyperPars automatically and warn the user about this.

**Comment by jakob-r** [comment]
I wasn't totally aware of the fact that the learner is not creatable with a valid param setting. And it's simply a bug because in the tests we expect it to work - with reason and it doesn't. That's why it is a bug to me. Or a contradictory specification - if you prefer.
a) Is not an option because according to test files we have specified that each learner can be created "out of the box"
b) That would mean to reverse translate the `requirements` and modify the `par.vals` accordingly. I don't see myself doing that. 
Why not
c) If the learner is created with a list (or single arguments) of `par.vals` we ignore the defined predefined par.vals. Otherwise we use them as a fallback to be able to create the learner "out of the box"

**Comment by jakob-r** [comment]
c2) Ideas: `makeLearner(..., clean = TRUE)`, `makeLearner(..., clean = getMlrOptions("empty.pars"))` or similar.

**Comment by jakob-r** [comment]
Side note: We also have occurrences where defaults are put into the par.vals. Why?

* boosting
* glmboost
* maxdepth
* glmnet

**Comment by berndbischl** [comment]
should talk about this, maybe also with michel

**Comment by berndbischl** [comment]
> Side note: We also have occurrences where defaults are put into the par.vals. Why?

This might simply be inconsitent with what we want. I need to look at it in detail, but I also already told @kerschke  that we dont want that in general.

**Comment by jakob-r** [comment]
We agreed ion introducing an argument `reset = TRUE` which removes all par.vals.

**Comment by jakob-r** [comment]
We have a problem that in boosting `xval` should always stay 0

**Comment by jakob-r** [comment]
So - what's the plan on tackling this problem? Either one person is given the right to make major changes (also in ParamHelpers I guess) and in a week of hard thinking it should be done but might offense somebody or we (@berndbischl, @mllg, ...?) really work together on this focused and make up our minds on a smart solution having all requirements in the back of our head.
Without major changes (mostly internal) this can't be done - that I am pretty sure of. But I am also convinced that we should not keep that issue open so much longer until we forget everything again.

**Comment by berndbischl** [comment]
"reset" was a good idea, but it also does not work. It removes all settings of parameters we have defined in the constructor, too.

**Comment by berndbischl** [comment]
> We have a problem that in boosting xval should always stay 0

I guess you mean the same thing here? Please be more verbose when describing stuff.
Helps to close issues earlier....

**Comment by jakob-r** [comment]
You are right. We should list all problems detailed here so we don't forget about them.
One solution could be to have a separate par.vals slots
* par.vals -  to be set by setHyperPars
* par.vals.default - param values to use if nothing is given to make train work: not to be alternated by the user, **we** think they are useful
* par.vals.tec - param values that have to be set out of technical reasons but they don't influence the behaviour of the learner

**Comment by jakob-r** [comment]
We talked and agreed on:
* using the default in the ParamSet only for default values set by the developer of the method we use
* all derivations (because of performance reasons, or to simply have a value so we can call the function) will be stored in `mlr.default.vals` (proposals welcome)
* someone has to recheck because we misused the defaults according to point 1

**Comment by berndbischl** [comment]
why close?

**Comment by jakob-r** [comment]
because i clicked the wrong button

**Comment by jakob-r** [comment]
I am tackling this issue currently in branch: https://github.com/mlr-org/mlr/tree/fix_344_default_par_vals

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
