### ISSUE TITLE
we should support score output for classes

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#355]
some classifiers can only output scores for classes instead of probabilities.

**Comment by larskotthoff** [comment]
For example? What does the score tell us, and is it consistent (i.e. is higher always better)?

**Comment by IcedragonP** [comment]
Imho every score can be transformed to a probability by adding the lowest (possible) value and 
dividing through the range of the (possible) score values. 
Maybe there is a problem if range is infinity...

**Comment by larskotthoff** [comment]
That's at least assuming that the scores are always linear. Is that the case?

**Comment by berndbischl** [comment]
My 2 cents: Classifiers provide different kind of scores, this is why we dont have them so far. Eg an SVM can be trained with 1-vs-1 approach, then you get (k over 2) scores, for all class pairs. ksvm does this IIRC. We cannot support all of this.

What I would like to support is this:
A classifier outputs one score per class. The higher the score the more "confidence" we have in this class. The predicted class would be the one with the highest score. There are quite some learners, that do this. But there is no implemented, or obvious way, to transform the scores into probabilities.
So we say "That learner only supports predict.type = response".
Which means we cannot do ROC plots, and other stuff, that we could do with this scores, just a we do it with probabilities.

**Comment by g-rho** [comment]
I agree with Bernd. Scores are not necessarily always linear in posterior probs. But there should be monontony in what Bernd calls 'confidence' (or posteriors). There shouldn't even be a fixed sign of the monotony.

**Comment by berndbischl** [comment]
> Imho every score can be transformed to a probability by adding the lowest possible value and 
> dividing through the range of the possible score values. Maybe there is a problem if range is infinity...

The is the problem with a missing upper bound. And what the scores exactly mean. I dont want mlr to output probabilities, if the original authors did not envision that this is possible for their method. And I dont want to check every single paper / package for that. 
(Actually the much more standard way to transform to probs would be to push the scores into a sigmoidal function, like the logistic transfer. )

But OTOH: For nearly nothing that we currently do in mlr with probabilities in mlr we REALLY need that say are "true"  probs or from [0,1]. If i am not mistaken we could do nearly everything with arbitrary scores. Like:
- ROC plots
- threshold application and optimization
- and so on.

**Comment by berndbischl** [comment]
and @g-rho : 
Hi Gero.
