### ISSUE TITLE
how to label stuff in plots

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#366]
1) How do we "name" / label objects in plots.
Answer: This is why we have "id"s in objects. So if you show something related to a task, you use its id. Same for measures, there is also this function measureAggrName, that concats the aggregation method's name to the measure name. But that gets kinda long, and seems to be overspecific.  Just mentioning it for completeness sake.
For learners it is a bit complicated, because we have: id, name, and shortname. "shortname" is, well, short, and was exactly intended to be used in plots.
So please use it there, always a default.

**Comment by berndbischl** [comment]
Zach says:

I should add that although the measure ids have been the default labels for measures. I don't get why that is the case. Wouldn't the measure names be better if their length isn't a problem? Why would we prefer tpr to true positive rate. It would be much harder to misread the latter. The default in plotROCRCurves is to use this longer measure name (though it is a measure from ROCR::performance there). I was doing this for consistency and because I thought it made sense for the above reason.

**Comment by berndbischl** [comment]
@zmjones Lets move the discussion from emails here

**Comment by zmjones** [comment]
Hello I am here!

**Comment by zmjones** [comment]
So what do you want me to do on this?

**Comment by zmjones** [comment]
And I want to know precisely how I broke things so I can avoid it again. I guess I kind of knew `get` was bad but not any specific reasons, tests passed, etc.

**Comment by berndbischl** [comment]
So as always it seems to be a think one might want to configure. In cases where length is not a problem, take the longer name. Maybe also as a default. In cases where it is likely that long names are problematic, take the shorter ones. But make that choice changeable for the user I guess. Try to have something consistent across the plots.

**Comment by berndbischl** [comment]
For the get stuff, lets do this over emails. Please tell me what you want to achieve in the 3 lines of code there

**Comment by zmjones** [comment]
Ok well I put that in the email. You should just revert it though. That commit stands on its own, nothing else builds on it.

**Comment by zmjones** [comment]
It is in my first reply, the third little section.

**Comment by berndbischl** [comment]
I answered. Can you please simply repair as I suggested?

**Comment by berndbischl** [comment]
And tell me here whether you agree to what I said above about the plots. I mean if you already use a longer name where it is feasible, maybe you do not need to make this configurable. Just think about this for a second, I do not want to complicate things too much.

**Comment by berndbischl** [comment]
Maybe the best might be to have an argument: 
labels.learners, labels.measures, lables.task.
These have defaults. if you want to change them, just pass a different vector of strings.

**Comment by zmjones** [comment]
Working on the fix now. 

I don't think we need a switch. The ids are used in the container object and the names are (or will be) just looked up in the measure objects when they are plotted. 

I don't think we need to add label arguments. Like we talked about before it is trivial for the user to manipulate the object to do this after we return it.

**Comment by berndbischl** [comment]
OK, agreed

**Comment by zmjones** [comment]
Just issued the PR. Fixed at the source and the code in the plotting functions is a bit better now as well.

**Comment by zmjones** [comment]
Sorry for the mess...

**Comment by schiffner** [comment]
No worries, and thx for the fix.

**Comment by larskotthoff** [comment]
Ok, so the consensus for the actual issue here is to use shortname for the plot labels always?

**Comment by zmjones** [comment]
No I think we are keeping my change to the long name: just fixing my bad solution to this by adjusting `generateThreshVsPerfData` to return the measure objects and then using a nicer solution to the match/replace operation I was doing on the data part of the object that gets plotted by using `mapValues`.

**Comment by berndbischl** [comment]
Zach, can you somewhere in the wiki in the correct place define the labeling convention for the plots we discussed here? And then can we close this?

Also check that there is a hint in the docs / tutorials how users could chnange them if they want to

**Comment by rpinsler** [comment]
I found one issue which might be related to this when using generateLearningCurveData/plotLearningCurve. 
One common application for those functions is to compare the learning curves of one measure for training and test data. However, when I specify e.g. measures = (acc, setAggregation(acc, "train.mean")), then the resulting df has two columns named "acc". When I use this for plotting, only one of the columns is shown (the first one IIRC). When I manually rename the columns of <learningCurveData>$data it works as expected. Maybe you can also consider this.

**Comment by zmjones** [comment]
@rpinsler could you give a full example so I can reproduce it? also, are you using the latest github version? in the data container object the names should be the same but since i subbed in the measure names in place of the ids in the plots that shouldn't happen. prior to only using the ids the only way to distinguish them would have been if there was somehow a different default name for the aggregation measure.

**Comment by rpinsler** [comment]
```r
lcdata <- generateLearningCurveData(learners = "classif.rpart", 
                          task = sonar.task,
                          resampling = makeResampleDesc("Holdout", predict = "both"),
                          measures = list(acc, setAggregation(acc, train.mean)))
plotLearningCurve(lcdata)
```

```r
> lcdata

LearningCurveData:
Task: Sonar-example
Measures: Accuracy, Accuracy
        learner perc       acc       acc
1 classif.rpart  0.1 0.5285714 0.5362319
2 classif.rpart  0.2 0.5428571 0.6666667
3 classif.rpart  0.3 0.7714286 0.7173913
4 classif.rpart  0.4 0.7000000 0.7753623
5 classif.rpart  0.5 0.6285714 0.8260870
6 classif.rpart  0.6 0.5857143 0.7826087
```

current workaround:
```r
colnames(lcdata$data) <- c("learner", "perc", "acc.test", "acc.train")
plotLearningCurve(lcdata)
```

I haven't checked if it's resolved with the current dev version, tbh. It could very well be that it works now.

**Comment by zmjones** [comment]
It is still broken. The problem is that both measures have the same name and id. @berndbischl what do you think? 

My first inclination was to compare the two measures, and then append the difference to the plot label: e.g., Accuracy: Test Set, Accuracy: Train Set.

**Comment by zmjones** [comment]
Actually I am thinking now that this should be handled by `setAggregation`. We should just change the name accordingly. I also think this should be done for any function that creates a measure. For example `makeCostMeasure` should have an argument `name` (just like `id`) where the user can input something descriptive that will then get used in the plots.

**Comment by rpinsler** [comment]
Agreed. But maybe you don't even need the `name` argument if you just use list names. For example, my first approach to circumvent the issue was: 
```r
measures = list(acc = acc, acc.train = setAggregation(acc, train.mean))
```
Obviously, you'd still need some sensible defaults though.

**Comment by zmjones** [comment]
Yea that is a nice way to do it. Idk how we would encode defaults without changing the behavior of functions that create measures though. The problem is still that the default names and ids are the same.

**Comment by rpinsler** [comment]
You could also change the data generating functions using something along those lines:

```
name = measure$id
if(measure$aggr$id == "test.mean") name = paste(name, measure$aggr$id, sep = ".")
```

Of course, this also works when put into the measure functions.

**Comment by berndbischl** [comment]
Talked to Zach. We will, in the objects, always use <measureid>.<aggr>.
For plots, there will be a little converter that maps names to more readbale things and can be configured.

also note there is measureAggrName, that does what you posted above (internal function)

**Comment by zmjones** [comment]
Added guidelines to the [wiki](https://github.com/mlr-org/mlr/wiki/Visualization-development-guidelines)

**Comment by berndbischl** [comment]
OK thx
