### ISSUE TITLE
transfer mlr repo to mlr-org

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#370]
I would like to do this very soon.

I have started reading this. 

https://help.github.com/articles/transferring-a-repository/

But I really dont want to break things, URLs, etc

Can somebody pls help me to check this out?

**Comment by larskotthoff** [comment]
Looking at the page it sounds like everything should work fine and things should be redirected automatically. I'm happy to help with this -- let's make a list of things that need to be changed.

- Repo URL in CRAN package description
- Travis
- Travis configuration for tutorial
- Links in tutorial
- URL in mlr paper (hint hint)

Anything else?

**Comment by berndbischl** [comment]
Nothing comes to mind. We should simply go over the "main entry points" like CRAN, README, etc slowly after the transferal and check everything out. 

I need to upload mlr over the weekend and could update the URL then. Do you have a day, where you have some time to do this together?

**Comment by berndbischl** [comment]
Or we could do this tonite to get it done with. I would have time in about 4-5 hours.

**Comment by larskotthoff** [comment]
Well do you want to have the CRAN release you're preparing point to the new repo or not?

**Comment by berndbischl** [comment]
guess so, yes

**Comment by larskotthoff** [comment]
Then the move should happen after the new release. Do you have a preferred date/time for the move?

**Comment by berndbischl** [comment]
Sunday? Evening for me?

**Comment by larskotthoff** [comment]
Ok, let's coordinate then on hangouts.

**Comment by berndbischl** [comment]
But I dont know whether I can point towards a nonexsting URL in the DESCRIPTION. 
Maybe It does not matter and we leave the URL in the DESC for now and rely on autoforwarding until 2.6.

**Comment by larskotthoff** [comment]
Yes, that was my understanding -- URLs pointing to the old repo will be forwarded automatically, so it shouldn't be a problem. The only thing that won't be forwarded are github pages, and that only affects the tutorial which we've moved already.

**Comment by jakob-r** [comment]
I also would like to see this - why did nothing happen?

**Comment by berndbischl** [comment]
> I also would like to see this - why did nothing happen? 

Because my spine is broken again. 

> PS: Maybe we should abanond github.com/rdatsci in favour of mlr-org?

These are 2 very different things ?
