### ISSUE TITLE
compare measures against OpenML

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#372]
@giuseppec 

Can you please do me a favor. Take one or 2 binary classif, multiclass and regr tasks. Do a normal CV and calc every measure possible. With mlr and OpenML on the server. Report any differences you see.

OK?

**Comment by berndbischl** [comment]
@giuseppec 
Maybe do this when you have time to talk with Joaquin for a few minutes

**Comment by berndbischl** [comment]
@florianfendt 
Can you please do this when you have some time?

**Comment by florianfendt** [comment]
Happy to do it, I already started working on this a bit couple of weeks back anyway

**Comment by berndbischl** [comment]
florian, put your code under todo files, and then maybe close here. 
if you dont have to say anymore about this

**Comment by florianfendt** [comment]
Close here, the comparison we did can be found in to-do-files.
