### ISSUE TITLE
LiblineaR

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#373]
Currently, we have three learners `classif.LiblineaRMultiClass`, `classif.LiblineaRLogReg` and `classif.LiblineaRBinary`. However, all of them support multiclassification since one-vs-all is implemented in LiblineaR for LogReg and Binary SVMs. We should use one learner for each classification method that is implemented in LiblineaR:

type
0 – L2-regularized logistic regression (primal)
1 – L2-regularized L2-loss support vector classification (dual)
2 – L2-regularized L2-loss support vector classification (primal)
3 – L2-regularized L1-loss support vector classification (dual)
4 – support vector classification by Crammer and Singer
5 – L1-regularized L2-loss support vector classification
6 – L1-regularized logistic regression
7 – L2-regularized logistic regression (dual)

For example:
`classif.LiblineaRL2LogReg` (allowing primal and dual option)
`classif.LiblineaRL1LogReg`
`classif.LiblineaRL2SVC` (allowing primal and dual option)
`classif.LiblineaRL1L2SVC`
`classif.LiblineaRL2L1SVC`
`classif.LiblineaRMultiClassSVC`

**Comment by florianfendt** [comment]
I'll start working on this today!

**Comment by florianfendt** [comment]
While I'm on it, why not implement type 11, 12 ,13 (for regression) as well, right?

**Comment by berndbischl** [comment]
@florianfendt 
What is the status here?

You do the other "measure" units first or this? Version 2.6?

**Comment by florianfendt** [comment]
This can be closed. We already merged that about a week ago.

**Comment by berndbischl** [comment]
thx. you can close in these cases yourself. But asking also does not hurt

**Comment by florianfendt** [comment]
ok will keep that in mind thx
