### ISSUE TITLE
surv and docs

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#375]
Hi, @mllg 

Can you please do the following for "surv" learners:

0) See that the API is documented in the tutorial
1) add a check in checkPredictLearnerOutput 
2) doc in Prediction.R how the columns in the object look like

And think about whether I forgot something

**Comment by berndbischl** [comment]
Please also update code and docs for getPredictionTruth, getPredictionResponse, getPredictionProbabilities

**Comment by mllg** [comment]
> Please also update code and docs for getPredictionTruth, getPredictionResponse, getPredictionProbabilities

Did you forget to push some default methods / methods for clasif, regression, ... ?

**Comment by berndbischl** [comment]
Yes. Sorry. I saw that, this is in my multilabel TODO list.
I added the functions then. 
If you wanna do it now, would be great

**Comment by mllg** [comment]
Added for classif, regr, cluster and surv (3bfd3faa9ec4687747979faa66aac6d8bc2c4ef3). There are also some unit tests, except for multilabel where I was not sure how to test this properly.

**Comment by schiffner** [comment]
getPredictionTruth and getPredictionResponse are also mentioned in the tutorial now.

mlr-org/mlr-tutorial/d519d0fc04515412a66a0151e2573473df5ff59a

mlr-org/mlr-tutorial/c0c4cdf42eddedfd92a263e821aa61ae44292fd5

**Comment by berndbischl** [comment]
we added unit tests for multilabel
