### ISSUE TITLE
Learner.model not printed correctly after learning with MultilabelBinaryRelevanceWrapper

### ISSUE THREAD

**Issue by IcedragonP** [mlr-org/mlr#391]
lrn1 = makeLearner("classif.rpart")
  lrn2 = makeMultilabelBinaryRelevanceWrapper(lrn1)
  mod = train(lrn2, yeast.task)
  mod$learner.model

**Comment by larskotthoff** [comment]
Don't use `mod$learner.model` directly, use `getLearnerModel()` (which in this case returns `NULL`).

**Comment by berndbischl** [comment]
1) there is getHomogenousEnsembleModels. That return the list here

2) Phillip is right that this error is indeed confusing.

**Comment by larskotthoff** [comment]
Re 2) This is the same for all wrapped models. It's not clear to me whether this should be fixed in the wrappers (i.e. put everything that should be there in) or the print method (i.e. check whether something is there before printing).

**Comment by berndbischl** [comment]
> Re 2) This is the same for all wrapped models

This is actually why I am concerned a bit. Briefly checking now.

**Comment by berndbischl** [comment]
getHomogenousEnsembleModels works nicely here. Will at least fix docs.

**Comment by larskotthoff** [comment]
Why does `getLearnerModel()` not delegate to `getHomogenousEnsembleModels()` here?

**Comment by berndbischl** [comment]
I have done the following:
1) getHomGenEnsModels is deprecated. getLearnerModel works now for this
It has a documented arg more.unwrap.

2) In the example above and for all wrappers model$learner.model now prints. This I did by adding a printer for the (internal) ChainModel. Dont ask what that is.

@larskotthoff 
Can you please check? This should not be broken and is kinda difficult.

**Comment by larskotthoff** [comment]
Looks good. Closing.
