### ISSUE TITLE
Tuning Preprocessing wrapper with mlr?

### ISSUE THREAD

**Issue by davidwangz137** [mlr-org/mlr#392]
I read the tutorial on preprocessing and feature selection. The feature selectors are tunable by the tuneParams function called on a wrapped learner. I wish to do a PCA on my data before I pass it into the learner. I also want to tune the number of eigenvectors used, along with hyperparameters of the model itself.
One way to do this is to simply have a loop which which uses a different number of eigenvectors for the dataset in each iteration and calls tuneParams on the rest of the hyperparameters. This is a feasible substitute for grid and random search. However, if I want to tune the hyperparameters using something like Irace, then having an integrated handling of the hyperparameters would be needed.

I was thinking that maybe it is possible to make the preprocessing wrapper behave more like it has a par.set instead of passing in a par.vals each time. Then make it available to the tuneParams function.

**Comment by schiffner** [comment]
Hi,

if I understand what you want to do correctly, you just need to use the `par.set` argument of `makePreprocWrapper`. This way you can add all the preprocessing parameters you want to the parameter set of the underlying learner and then tune them jointly.

I hope that helps. If this doesn't answer your question, let me know.

Note to self: This should be probably mentioned in the tutorial.

**Comment by berndbischl** [comment]
sorry, for reopening. david i guess and hope that you have found a solution for you.

but your question is very good - and probably a common thing for many people. so we should grab the chance now to explain this in tje tutorial rather than here.

Julia do you have time to do this briefly?

i see 3 options here: 
1. construct a custom preproc wrapper, that selects pca components internally. the best ones by eigenvalue or a filter messure. to show how to tune this is instructive in ANY case.

2. we had a pcawrapper. i guess this is not exported. if not the burden should not be on julia to do this. maybe just check? but also see 3.

3. the easiest option is to tune the preprocwrappercaret. this is very flexible, imcludes pca, and should be shown to people.

your comments?

**Comment by schiffner** [comment]
> 1. construct a custom preproc wrapper, that selects pca components internally. the best ones by eigenvalue or a filter messure. to show how to tune this is instructive in ANY case.

Agreed. The tutorial shows an example preproc wrapper which scales the data (was the simplest thing I could think of). I can certainly show how to tune its parameters. It's not spectacularly impressive, but gets the point across, I guess.

> 2. we had a pcawrapper. i guess this is not exported. if not the burden should not be on julia to do this. maybe just check? but also see 3.

Yes, we had. I remember writing it with you (we also had a outlier removal wrapper). The last time I checked both were in todo-files.

> 3. the easiest option is to tune the preprocwrappercaret. this is very flexible, imcludes pca, and should be shown to people.

Yep. Can do this.

**Comment by berndbischl** [comment]
> I can certainly show how to tune its parameters. 
>It's not spectacularly impressive, but gets the point across, I guess.

I dont care what preproc op is shown. But one should see how to tune it jointly with the learner. This is what is cool about our package :)

Rest what you said: OK and Thx!
I guess we might not need the extra-warppers in todofiles because we support the caret monster. 
But note there might be an open issue wrt tuning this. To support you to close this i will try to fix this now.

**Comment by davidwangz137** [comment]
I closed the issue because I thought that par.set would simply solve the problem.

However, upon trying to obtain the parameters I passed to the par.set argument in makePreprocWrapper I couldn't find them at first. I tried walking up the environment tree and found them 1 parent frame up (stored in variable pvs). If the learner wasn't tuning, it wouldn't be included in the pvs variable. It would be nice to have the values of the variables in par.set included in the args or maybe another auxiliary variable, even if they are set to default values.

**Comment by schiffner** [comment]
I'm not sure if I'm getting the problem.

The best way to get an overview about the whole parameter set of a learner is `getParamSet`. Did you use this?

And did the tuning work?

**Comment by davidwangz137** [comment]
I omitted to check the args variable while tuning, only checking it while resampling. The variable is included whenever it is not its default value (I assumed that it wasn't there since it didn't appear when I tried resampling). That was why I couldn't find the variable. To remedy this I just need to set the default in the train function when it doesn't exist. Can you call getParamSet on the learner when you are inside the train function?

If not, then it isn't much of a hassle to hardcode the default (since the value found by tuning is what is desired anyways)
Thanks!

**Comment by berndbischl** [comment]
Can you please post your code here? And also check what Julia has in the tutorial.
I am guessing you are making a simple mistake.

**Comment by schiffner** [comment]
Would you mind copying the relevant code snippets, most importantly how you defined your prepress wrapper, here?
I got the feeling that things should not be that complicated and would like to have a look.
(And if it turns out that it's complicated we will know what to improve...)

**Comment by schiffner** [comment]
Ok, I put an example about joint tuning of learner and preprocessing parameters in the tutorial.
Provided I didn't break anything it should be [here](http://mlr-org.github.io/mlr-tutorial/devel/html/preproc/index.html) in about 30 min.

(mlr-org/mlr-tutorial/@11b6bcc5a9d4214bc82b2c467c63db583d7467d5)

**Comment by davidwangz137** [comment]
Here is my code. It works fine, except for the hardcoding of the default.

```R
tr.fun = function(data, target, args=list(center=TRUE,scale=TRUE)) {
  #Set the value of num.vectors. If it doesn't exist in the args, set it to the default value
  if("num.vectors" %in% args){
	num.vectors <- args$num.vectors
  }else{
	num.vectors <- 6
  }
  #Obtain the numeric features for PCA
  cns = colnames(data)
  nums = setdiff(cns[sapply(data, is.numeric)], target)
  #Set the number of eigenvectors to be at maximum the number of numeric parameters
  if(num.vectors > length(nums)) num.vectors <- length(nums)
  x = as.matrix(data[, nums, drop = FALSE])
  #Obtain the SVD
  y <- prcomp(x,scale=TRUE)
  
  data = data[, setdiff(cns, nums), drop = FALSE]
  data = cbind(data, as.data.frame(y$x[,1:num.vectors]))
  #The projection onto the eigenvectors is no longer needed
  y$x <- NULL
  return(list(data = data, control = y))
}

pr.fun = function(data, target, args, control) {
  #Set the value of num.vectors. If it doesn't exist in the args, set it to the default value
  if("num.vectors" %in% args){
	num.vectors <- args$num.vectors
  }else{
	num.vectors <- 6
  }
  #Obtain the numeric features for PCA
  cns = colnames(data)
  nums = setdiff(cns[sapply(data, is.numeric)], target)
  #Set the number of eigenvectors to be at maximum the number of numeric parameters
  if(num.vectors > length(nums)) num.vectors <- length(nums)
  
  x = as.matrix(data[, nums, drop = FALSE])
  x <- scale(x,center = control$center, scale = control$scale)
  #Obtain the SVD
  mat.proj <- control$rotation[,1:num.vectors]
  data.proj <- x %*% mat.proj
  #Combine the numeric and categorical data together
  data = data[, setdiff(cns, nums), drop = FALSE]
  data = cbind(data, as.data.frame(data.proj))
  return(data)
}

#Create the parameter set for the preprocessor
ps = makeParamSet(
        makeIntegerParam("num.vectors",lower=2,upper=12,default=6)
)
#Create the preprocessing learner
lrn = makeLearner("regr.nnet", trace = FALSE, decay = 1e-02)
lrn = makePreprocWrapper(lrn, train = tr.fun, predict = pr.fun,
  par.vals = list(center = TRUE, scale = TRUE),par.set=ps)

rdesc = makeResampleDesc("CV", iters = 10)
r = resample(lrn, bh.task, resampling = rdesc, show.info = FALSE)
r$aggr

#Set the hyperparameters to those found by tuning to see if there is any improvement in performance
lrn <- setHyperPars(lrn,par.vals=list(num.vectors=7,decay=0.01,size=16))
r = resample(lrn, bh.task, resampling = rdesc, show.info = FALSE)
r$aggr

#Tune the preprocessor
ctrl = makeTuneControlGrid(resolution=5L);

ps.tune = makeParamSet(
        makeIntegerParam("num.vectors",lower=2,upper=12),
        makeIntegerParam("size",lower=5,upper=20),
        makeNumericParam("decay",lower=-4,upper=0,trafo=function(x)10^x)
)

rdesc = makeResampleDesc("CV", iters = 10)
res.tuner = tuneParams(lrn, bh.task, rdesc, par.set = ps.tune, control = ctrl,show.info=T)
```R

**Comment by schiffner** [comment]
Thanks. I will take a look now.

**Comment by davidwangz137** [comment]
There is no "problem" as when tuning the "num.vectors" argument is always set. It would be nice if the value was always in the "args" variable since then you don't have to test for existence. Everything works on my side, you can close the issue whenever you want.

**Comment by schiffner** [comment]
I agree that `num.vectors` should be in `args`, therefore the solution is to simply put it there. I would do the following:

* Put `num.vectors` in the `args` in `tr.fun`, i.e., define:  
  `tr.fun = function(data, target, args=list(center=TRUE,scale=TRUE,num.vectors)) {`
* Within `tr.fun` I wouldn't extract `num.vectors` from the `args` (`num.vectors <- args$num.vectors`), but work directly with `args$num.vectors`. This spares you doing the same again in `pr.fun`.
* In `makePreprocWrapper` put your default for `num.vector` in the `par.vals` argument.

The result looks like this and worked for me as far as I checked:
```
tr.fun = function(data, target, args=list(center=TRUE,scale=TRUE,num.vectors)) {
  #Obtain the numeric features for PCA
  cns = colnames(data)
  nums = setdiff(cns[sapply(data, is.numeric)], target)
  #Set the number of eigenvectors to be at maximum the number of numeric parameters
  if(args$num.vectors > length(nums)) args$num.vectors <- length(nums)
  x = as.matrix(data[, nums, drop = FALSE])
  #Obtain the SVD
  y <- prcomp(x,scale=TRUE)

  data = data[, setdiff(cns, nums), drop = FALSE]
  data = cbind(data, as.data.frame(y$x[,1:args$num.vectors]))
  #The projection onto the eigenvectors is no longer needed
  y$x <- NULL
  return(list(data = data, control = y))
}

pr.fun = function(data, target, args, control) {
  #Obtain the numeric features for PCA
  cns = colnames(data)
  nums = setdiff(cns[sapply(data, is.numeric)], target)

  x = as.matrix(data[, nums, drop = FALSE])
  x <- scale(x,center = control$center, scale = control$scale)
  #Obtain the SVD
  mat.proj <- control$rotation[,1:args$num.vectors]
  data.proj <- x %*% mat.proj
  #Combine the numeric and categorical data together
  data = data[, setdiff(cns, nums), drop = FALSE]
  data = cbind(data, as.data.frame(data.proj))
  return(data)
}

#Create the parameter set for the preprocessor
ps = makeParamSet(
        makeIntegerParam("num.vectors",lower=2,upper=12,default=6)
)
#Create the preprocessing learner
lrn = makeLearner("regr.nnet", trace = FALSE, decay = 1e-02)
lrn = makePreprocWrapper(lrn, train = tr.fun, predict = pr.fun,
  par.vals = list(center = TRUE, scale = TRUE, num.vectors = 6),par.set=ps)

m = train(lrn, bh.task)
predict(m, task = bh.task)

rdesc = makeResampleDesc("CV", iters = 10)
r = resample(lrn, bh.task, resampling = rdesc, show.info = FALSE)
r$aggr

#Set the hyperparameters to those found by tuning to see if there is any improvement in performance
lrn <- setHyperPars(lrn,par.vals=list(num.vectors=7,decay=0.01,size=16))
r = resample(lrn, bh.task, resampling = rdesc, show.info = FALSE)
r$aggr

#Tune the preprocessor
ctrl = makeTuneControlGrid(resolution=5L);

ps.tune = makeParamSet(
        makeIntegerParam("num.vectors",lower=2,upper=12),
        makeIntegerParam("size",lower=5,upper=20),
        makeNumericParam("decay",lower=-4,upper=0,trafo=function(x)10^x)
)

rdesc = makeResampleDesc("CV", iters = 10)
res.tuner = tuneParams(lrn, bh.task, rdesc, par.set = ps.tune, control = ctrl,show.info=T)
```

**Comment by berndbischl** [comment]
What Julia just said!

This is kinda documented in makePreprocWrapper

par.vals	[list]
Named list of default values for params in args respectively par.set. Default is empty list.

Tell us if this is not enough!

@schiffner:
Can you check tuning for the PeprocCaret thing? It would be nice to have in in the tutorial once, because it is kinda powerful.

#

**Comment by schiffner** [comment]
@berndbischl: I'm looking at it now. We definitely have to improve the doc for `makePreprocWrapperCaret`. I had to look at the source code to find out how to do a pca.

**Comment by davidwangz137** [comment]
This seems like a good solution. It was due to my assumption that values in par.set should automatically be in args that I got confused. Thanks for everything!

**Comment by schiffner** [comment]
@davidwangz137 You are welcome!

@berndbischl : I checked tuning for the `ppc.thresh` and `ppc.pcaComp` params for pca preproc. Everything works so far.

**Comment by berndbischl** [comment]
Then I was mistaken. We just have issue with tuning the ImputeWrapper,

Then please doc it in the tutorial with a semi-reasonable example. If you can!

then close pls

**Comment by schiffner** [comment]
Yep. Will avoid `ppc.knnImpute`, `ppc.bagImput`e, and `ppc.mediaImpute` until #220 is solved.

**Comment by berndbischl** [comment]
@schiffner 

are we done here?

**Comment by berndbischl** [comment]
then close

**Comment by schiffner** [comment]
Almost. It took some time to find this "semi-reasonable example". Will push tutorial updates and close this issue tomorrow or Friday.

**Comment by schiffner** [comment]
Sorry for the delay. Just pushed the reworked preprocessing section.

mlr-org/mlr-tutorial/@e5dbf7ae73a8af4724a71ab257537846041e5733
