### ISSUE TITLE
MLBenchObjToTask "Id" Option

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr#401]
When using the ``benchmark()`` function on more then one tasks from
``convertMLBenchObjToTask()`` I get the following error:
``benchmark(lrns, tasks, rdesc, meas) : Tasks need unique ids!``,
which makes sense as the ``task.id`` for every task generated via ``convertMLBenchObjToTask()`` is "d".
Solution: Add some ``task.id = `` param to  ``convertMLBenchObjToTask()``.
It is pretty annoying to manually change the ``task.id`` for every task.

**Comment by berndbischl** [comment]
Please as well post minimal examples that demo the error in cases like this!

**Comment by pfistfl** [comment]
Example:
```
ion.task = convertMLBenchObjToTask("Ionosphere")
bc.task = convertMLBenchObjToTask("BreastCancer")
tasks = list(ion.task, bc.task)
lrns = list(makeLearner("classif.rpart"))
rdesc = makeResampleDesc("CV", iters = 5)
meas = list(mmce,ber,acc)
res = benchmark(lrns, tasks, rdesc,meas)
```

Produces: 
```
Error in benchmark(lrns, tasks, rdesc, meas) : Tasks need unique ids!
```

**Comment by berndbischl** [comment]
thx for the report

**Comment by berndbischl** [comment]
the id is now the name of th mlbench object
