### ISSUE TITLE
plotBechmarkResult bug?

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#406]
```{r}
cv10f = makeResampleDesc("CV", iters = 10)
measures = list(mlr::acc, mlr::auc)
learners = list(
  makeLearner("classif.randomForest", predict.type = "prob"),
  makeLearner("classif.rpart", predict.type = "prob")
)

res = benchmark(learners, sonar.task, cv10f, measures)

# this gives me an error:
plotBenchmarkResult(res, measure=auc) 
## Error in parse(text = x) : <text>:1:6: unexpected symbol
## 1: Area under
##         ^

# this works:
plotBenchmarkResult(res, measure=acc) 
```

**Comment by berndbischl** [comment]
huh?

**Comment by berndbischl** [comment]
this is weird, will check

**Comment by berndbischl** [comment]
are you using the GH package?

**Comment by giuseppec** [comment]
Yes, I always use the GH version of mlr

**Comment by berndbischl** [comment]
you can repair for now by setting pretty.names = F

**Comment by berndbischl** [comment]
does ggplot2 not allow whitespaces in aes varaible names?
@zmjones 
@pfistfl

**Comment by berndbischl** [comment]
I am unsure that what is currently done here is OK.
1) We still seem to have an error on travis
2) This issue here will concern other functions as well

I guess the correct solution is not to rename the columns in the data frame, but you tell ggplot how to set the axis labels explicitly.

**Comment by berndbischl** [comment]
So operators +xlab or +ylab should be used

**Comment by larskotthoff** [comment]
I'm trying to figure out why the travis build is not failing. I'm changing this to use `ylab` (which is the better solution anyway). I've had a brief look through the source and as far as I can see this shouldn't be an issue anywhere else.

**Comment by larskotthoff** [comment]
Ok, apparently the ggplot object isn't evaluated unless it's displayed. I've changed the test to save to a temporary file, which makes the test fail with the old implementation. I'll see if that upsets travis and if not change in similar tests as well.

**Comment by berndbischl** [comment]
Lars, thanks a lot. Dont wanna annoy you, I just want to doc here, why this is not a issue anywhere else.
How does Zach handle the same problem in his dozen plot functions? We discussed exactly the point here, so having more verbose axis names, at length, and he really wanted to do that.

**Comment by pfistfl** [comment]
Discovered the same bug earlier as well but did not get around to create an issue, wanted to create it today.
Sorry for the inconvenience!

I'll try to explain what I think the reason is, hope I got it right
This bug only appeared for  `pretty.names = TRUE` as those names (`measure$name`) might contain whitespace. I had only used `measure$id` before.
Guess the specific bug appeared because the  `y`-axis  was mapped via `mname` in the earlier commit. This led to ggplot2 searching for  colnames like **mean missclassification error** which is not allowed due to containing white space.

All other functions that I saw using `pretty.names` melt the performance measures into a `performance` column that is used as a `y` aesthetic. ( `generateThreshVsPerf ` and `generateLearningCurve`).

**Comment by berndbischl** [comment]
> I'll try to explain what I think the reason is, hope I got it right

What you say is correct. Here my 2cents: There is a difference between how you name stuff in objects (thats more a programmatic concept, like a variable name), and how you display stuff in plots. For the former often a severly restricted formal syntax can be applied. For the latter, arbitrary strings might be ok, that are more human readable. 
Often one should not mix and confuse the 2.

Your last sentence i dont get. Doesnt Zack display the name at all?

**Comment by schiffner** [comment]
> Your last sentence i dont get. Doesnt Zack display the name at all?

To explain this a little further:
There are 3 plots with `pretty.name` option (only those which plot performances):

1. plotBenchmark
2. plotLearningCurve
3. plotThreshVsPerf

1. was already discussed above / fixed.

In 2. and 3. we also have (if `pretty.names == TRUE`) the measure names as column names, but **only temporarily**. As @pfistfl pointed out,  `melt` is applied and we get a `data.frame` with a factor column called `measure` with the long names used as factor levels (which should be allowed).
See code snippet below.

If we want to circumvent column names with white space, we could change the factor levels after melting.

```
lrn = makeLearner("classif.lda", predict.type = "prob")
mod = train(lrn, task = sonar.task)
pred = predict(mod, task = sonar.task)
d = generateThreshVsPerfData(pred, measures = list(fpr, fnr, mmce))
p = plotThreshVsPerf(d)
head(p$data, 2)
     learner  threshold             measure performance
1 prediction 0.00000000 False positive rate   1.0000000
2 prediction 0.01010101 False positive rate   0.7422680
```

**Comment by pfistfl** [comment]
Was typing an answer as well, but see above.
In `generateThreshVsPerf` it is done via e.g `facet_wrap(~measure)`, where white space is allowed as element of the column but not as a colname.
I kind of like the idea of allowing different facetting, will have to think a little more if this is easily implemented.

**Comment by larskotthoff** [comment]
Thanks for clarifying. @berndbischl This isn't an issue anywhere else because as far as I can see the pretty name isn't used as a column name anywhere else.

**Comment by berndbischl** [comment]
Ok then I will close, thx for you help all
