### ISSUE TITLE
makePreprocWrapperCaret

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#408]
I encountered some problems with `makePreprocWrapperCaret`.
These are not difficult to solve. I'm opening this issue because I wanted your opinion and because I didn't
want to create any conflicts if @jakob-r is working on the wrapper (#220).
- `preProcess` works only for numeric features.
  At the moment this is not handled consistently:
  
  When I generate a wrapped learner it still has property `"factors"` (if it had this originally).
  
  When trying to `train` the wrapped learner on `bh.task` (which has numeric and factor columns)
  `preProcess`, of course, throws an error.
  
  My favorite solution would be to use only numeric columns as `work.cols` in `makePreprocWrapperCaret`.
  Any objections?
  
  Concrete example:

```
lrn = makePreprocWrapperCaret("regr.lm", ppc.pca = TRUE, ppc.thresh = 0.9)
lrn
# Learner regr.lm.preproc from package stats
# Type: regr
# Name: ; Short name: 
# Class: PreprocWrapper
# Properties: numerics,factors,missings,weights,se
# Predict-Type: response
# Hyperparameters: ppc.BoxCox=FALSE,ppc.YeoJohnson=FALSE,ppc.expoTrans=FALSE,ppc.center=FALSE,ppc.scale=FALSE,ppc.range=FALSE,ppc.knnImpute=FALSE,ppc.bagImpute=FALSE,ppc.medianImpute=FALSE,ppc.pca=TRUE,ppc.ica=FALSE,ppc.spatialSign=FALSE,ppc.thresh=0.9,ppc.na.remove=TRUE,ppc.k=5,ppc.fudge=0.2,ppc.numUnique=3

train(lrn, bh.task)
traceback()
#12: stop("all columns of x must be numeric")
#11: preProcess.default(x = list(crim = c(0.00632, 0.02731, 0.02729, 
#     0.03237, 0.06905, 0.02985, 0.08829, 0.14455, 0.21124, 0.17004, 
#10: (function (x, ...) 
#     UseMethod("preProcess"))(x = list(crim = c(0.00632, 0.02731, 
#     0.02729, 0.03237, 0.06905, 0.02985, 0.08829, 0.14455, 0.21124, 
#9: do.call(caret::preProcess, c(list(x = x), cargs))
#8: .learner$train(data = getTaskData(.task, .subset), target = getTaskTargetNames(.task), 
#        args = pvs)
#7: trainLearner.PreprocWrapper(.learner = list(id = "regr.lm.preproc", 
#        type = "regr", predict.type = "response", package = "stats", 
#6: (function (.learner, .task, .subset, .weights = NULL, ...) 
#    {
#        UseMethod("trainLearner")
#5: do.call(trainLearner, pars)
#4: fun2(do.call(trainLearner, pars))
#3: fun1(learner.model <- fun2(do.call(trainLearner, pars)))
#2: system.time(fun1(learner.model <- fun2(do.call(trainLearner, 
#        pars))), gcFirst = FALSE)
#1: train(lrn, bh.task)
```
- We have to add arguments of `fastICA` to the `par.set` in `makePreprocWrapperCaret`.
  These are not explicit arguments of `preProcess`, but passed to `fastICA` via `...`,
  but are really needed and something one would like to tune.
  For example `n.comp` has no default in `fastICA` and must be specified in `makePreprocWrapperCaret`.
  Otherwise:

```
lrn = makePreprocWrapperCaret("classif.lda", ppc.ica = TRUE)
lrn
train(lrn, sonar.task)
# Error in fastICA::fastICA(x, ...) : 
#   argument "n.comp" is missing, with no default
# Timing stopped at: 0.114 0.008 0.123 
```
- The documentation should mention the naming scheme for the arguments (i.e. argument names prefixed by `ppc.`,
  no `method` argument, but logical parameters).

**Comment by schiffner** [comment]
I looked into this and can do a PR to solve this issue.

* Do preprocessing only for the numeric columns (in fact this is what the next caret release will also do: https://github.com/topepo/caret/commit/399b973d4936523fb1429491421032eb52744028)
* Extend the docs.
* Add `fastICA` pars to the `par.set` (at least the ones that one might want to tune as there are 2 name clashes between `preProcess` and `fastICA`).

What I wrote above about `fastICA` was partly wrong / not the core of the problem, so just for the record:  
* The `fastICA` parameters are currently *not* in the `par.set` of `makePreprocWrapperCaret`.
* But they can be passed to `fastICA` via the `...` of `makePreprocWrapperCaret`. At the moment there is just a small bug in the `trainfun` that prevents that from happening, which I can fix. 
* Another thing to take care of: All arguments in `...` of `makePreprocWrapperCaret` are currently written into `par.vals`. The fact that they are in `par.vals`, but not in `par.set` causes problems when printing the learner (and also when printing the `WrappedModel` after training):

```
lrn = makePreprocWrapperCaret("classif.lda", ppc.ica = TRUE, n.comp = 2)
print(lrn)

Error in UseMethod("paramValueToString") : 
  no applicable method for 'paramValueToString' applied to an object of class "NULL"
traceback()
8: (function (par, x, show.missing.values = FALSE, num.format = "%.3g") 
   {
       assertFlag(show.missing.values)
       assertString(num.format)
       UseMethod("paramValueToString")
   })(dots[[1L]][[18L]], dots[[2L]][[18L]])
7: mapply(FUN = f, ..., SIMPLIFY = FALSE)
6: Map(paramValueToString, pars, hps)
5: getHyperParsString(x)
4: cat("Learner ", x$id, " from package ", collapse(cleanupPackageNames(x$package)), 
       "\n", "Type: ", x$type, "\n", "Name: ", x$name, "; Short name: ", 
       x$short.name, "\n", "Class: ", class(x)[1L], "\n", "Properties: ", 
       collapse(getLearnerProperties(x)), "\n", "Predict-Type: ", 
       x$predict.type, "\n", "Hyperparameters: ", getHyperParsString(x), 
       "\n\n", sep = "")
3: print.Learner(x)
2: print.BaseWrapper(lrn)
1: print(lrn)
```

**Comment by berndbischl** [comment]
Great. We can put this into 2.6 then.

**Comment by schiffner** [comment]
> I looked into this and can do a PR to solve this issue.

> * Do preprocessing only for the numeric columns (in fact this is what the next caret release will also do: topepo/caret@399b973)

This is now in caret version 6.0-57

**Comment by schiffner** [comment]
Just to remind myself:
The wrapper is also lacking a name and a short name

**Comment by pat-s** [comment]
This issue most likely does not apply anymore.
