### ISSUE TITLE
and makeLearner example fails

### ISSUE THREAD

**Issue by vjcitn** [mlr-org/mlr#413]
mkLrnr> makeLearner("classif.lda", predict.type = "prob")
Error in makeLogicalLearnerParam(id = "CV", default = FALSE, tunable = FALSE) : 
  unused argument (tunable = FALSE)

i assume i am taking devel branch at an inopportune moment.... but hope the info is useful anyway

**Comment by jakob-r** [comment]
like mentioned in #412
For now `devtools::install_github("berndbischl/ParamHelpers")` is the solution.
