### ISSUE TITLE
multilabel classification

### ISSUE THREAD

**Issue by zmjones** [mlr-org/mlr#416]
`cforest` can handle multilabel classification. I went to add it but I don't understand the way that the formula is set up for multilabel tasks. 

```{r}
> getTaskFormula(yeast.task)
label1 ~ .
> getTaskTargetNames(yeast.task)
 [1] "label1"  "label2"  "label3"  "label4"  "label5"  "label6"  "label7" 
 [8] "label8"  "label9"  "label10" "label11" "label12" "label13" "label14"
```

The formula for `cforest` should be `label1 + label2 ... ~ .`. In my experience most of the packages that have a function to predict multiple attributes that use the formula interface do so in this way (e.g. plotting in lattice). 

I thought maybe it was setup this way for use with the binary relevance wrapper but see no use of formulas there at all. 

So IMO this

```{r}
as.formula(paste(target, "~", paste(features, collapse = " + ")), env = env)
```

Should be

```{r}
as.formula(paste(paste(target, collapse = " + "), "~", paste(features, collapse = " + ")), env = env)
```

**Comment by zmjones** [comment]
I should also add that the multi-attribute prediction that `cforest` does is more general than multi-label classification, as it can handle mixed multi-attribute classification and regression tasks.

**Comment by zmjones** [comment]
I am also not sure why we've restricted the prediction output to just a logical matrix. Is that such a common restriction of the learners that this makes sense?

**Comment by berndbischl** [comment]
i fixed the getTaskFormula for multilabel as you described, which was indeed wrong and broken before. 
I also tried to go through all task operators to check them for multilabel.

**Comment by berndbischl** [comment]
for cforest / mixed output: true. this is called multitarget prediction. and i want to support it in mlr, too.
but multilabel is a specific subset here, also with sometimes specific algorithms. we need to take this slowly. so i would say: who cares (now) if cforest can do more.

**Comment by berndbischl** [comment]
regarding the predictions: 
well all labels are basically 0/1 coded columns. so a logical matrix seems natural. for type = "response",
we also support type = "prob" where it is num. matrix, and each col contains the P for the label.
do you thing this is somehow bad?

NB: we need to check that that API is documented.

**Comment by berndbischl** [comment]
@MariaErdmann 
can you please add cforest as a multilabel learner?

**Comment by berndbischl** [comment]
have a look this here:
https://github.com/mlr-org/mlr/blob/master/R/RLearner_multilabel_rFerns.R
and this PR https://github.com/mlr-org/mlr/pull/991

**Comment by berndbischl** [comment]
we have multilabel.cforest now. closing
