### ISSUE TITLE
Travis is broken

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#421]
Travis currently fails with

    Error in ._jobjRef_dollar(x[["jobj"]], name) : 
      no field, method or inner class called 'calls' 
    Calls: test_check ... expectation_error -> $ -> $.Throwable -> ._jobjRef_dollar
    Execution halted

I cannot reproduce this error, even on a fresh Ubuntu installation that should be configured in the same way as the Travis machine.

The message suggests that it's coming from some Java interface code, probably RWeka. I've tested all the learners we use from RWeka and they seem to be fine.

Any ideas anybody?

**Comment by jakob-r** [comment]
If we exclude everything which uses Rweka and thus Rjava it works again
https://travis-ci.org/mlr-org/mlr/branches

**Comment by larskotthoff** [comment]
Hmm, any idea what's causing this? Excluding everything that uses Java seems a bit over the top.

**Comment by larskotthoff** [comment]
Ok, I was able to reproduce the problem with the Oracle JDK. But in my case removing `bartMachine` (which also uses `rJava`) fixed it.

**Comment by larskotthoff** [comment]
Seems to be fixed now. Opened a new issue for the bartMachine stuff.

**Comment by jakob-r** [comment]
I am interested in how exactly did you spot the cause. So we might be smarter in the future. Could you give some hints?

**Comment by larskotthoff** [comment]
I created a virtual machine with a fresh Ubuntu install, then installed R, Java, etc. Then I ran the tests to see if I could reproduce, then only the test that failed. Then I printed the names of the learners as they were being tested; got the error just after `bartMachine`. So I tested just that, commenting out things until I'd narrowed it down to the test with missing values. So then I constructed a test case for this manually and got a different error, but this error message along with some playing around gave me the hint how to "fix" this.

In practice it wasn't quite as straightforward as I described it; for example the default Java version (openjdk) worked fine; the problem only occurs with the Oracle JVM.

**Comment by kapelner** [comment]
I just upgraded bartMachine to 1.2.1 please try it now.

**Comment by kindlychung** [comment]
@kapelner What went wrong and how did you solve the issue? I am also having this problem with one of my packages that depend on rJava. Thanks!

**Comment by kapelner** [comment]
Unsure... you'll have to wait for lars to rerun and see if what I did fixes it.

**Comment by larskotthoff** [comment]
Thanks for updating -- we're having some other issues with Travis now, but as soon as that's sorted out I'll have a look at this.
