### ISSUE TITLE
Check parameters for bartMachine

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#422]
This caused #421 .

bartMachine doesn't like missing values, even if `use_missing_data = TRUE`. In particular I got

    Error in .jcall(java_bart_machine, "V", "addTrainingDataRow", as.character(model_matrix_training_data[i,  :
     java.lang.NullPointerException

Setting `replace_missing_data_with_x_j_bar = TRUE` fixes this for some reason.

**Comment by kapelner** [comment]
Hello, see closed issue on bartMachine github page referenced above for the fix.

**Comment by larskotthoff** [comment]
Thanks @kapelner. We found this with the latest version of rJava and the error occurred reproducibly, so I'm not sure what the fix here is.

**Comment by kapelner** [comment]
That's ungood. Can you give me the dataset you're using and the code?

Using "replace_missing_data_with_x_j_bar = TRUE" is not a good fix because it bypasses our novel way of handling missing data so this actually has to be fixed.

**Comment by theodds** [comment]
Not sure if this helps, but I also had the newest version of rJava installed from CRAN, but it did not work until I installed it using `apt-get` in Ubuntu.

**Comment by larskotthoff** [comment]
Complete example (without mlr):

    library(bartMachine)
    data(Sonar, package = "mlbench")
    Sonar[1,1] = NA
    bartMachine(X = Sonar, y = Sonar$Class, use_missing_data = TRUE)

gives

    bartMachine initializing with 50 trees...
    Error in .jcall(java_bart_machine, "V", "addTrainingDataRow", as.character(model_matrix_training_data[i,  :
      java.lang.NullPointerException

If I use

    bartMachine(X = Sonar, y = Sonar$Class, replace_missing_data_with_x_j_bar = TRUE)

it works.

This only happens with the Oracle JDK, not with the default OpenJDK. rJava is installed through the Ubuntu repositories. Same problem if I install from CRAN.

**Comment by kapelner** [comment]
It seems that using apt-get is different that using install.packages in R.
See edit on first message here:

http://stackoverflow.com/questions/3311940/r-rjava-package-install-failing



On Wed, Aug 12, 2015 at 6:04 PM, theodds <notifications@github.com> wrote:

> Not sure if this helps, but I also had the newest version of rJava
> installed from CRAN, but it did not work until I installed it using
> apt-get in Ubuntu.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlr-org/mlr/issues/422#issuecomment-130461172>.
>



-- 
Adam Kapelner, Ph.D.
Assistant Professor of Mathematics
Queens College, City University of New York
65-30 Kissena Blvd., Kiely Hall Room 604
Flushing, NY, 11367 M: 516-435-6795
kapelner.com (scholar
<https://scholar.google.com/citations?user=TzgMmnoAAAAJ>|research gate
<http://www.researchgate.net/profile/Adam_Kapelner2>|publons
<https://publons.com/author/431881/adam-kapelner#profile>)

**Comment by larskotthoff** [comment]
Well both work in that the package is installed. Both break bartMachine in the same way.

**Comment by kapelner** [comment]
The bug is probably in passing that NA over to Java. Some combinations of
R-rJava-linux-Java seem to have it, others don't.

I just pushed a possible fix to the bartMachine repo. Can you clone, "ant"
and "R CMD INSTALL bartMachine" and restart R to see if that fixes it?

On Wed, Aug 12, 2015 at 6:14 PM, Lars Kotthoff <notifications@github.com>
wrote:

> Well both work in that the package is installed. Both break bartMachine in
> the same way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlr-org/mlr/issues/422#issuecomment-130462982>.
>



-- 
Adam Kapelner, Ph.D.
Assistant Professor of Mathematics
Queens College, City University of New York
65-30 Kissena Blvd., Kiely Hall Room 604
Flushing, NY, 11367 M: 516-435-6795
kapelner.com (scholar
<https://scholar.google.com/citations?user=TzgMmnoAAAAJ>|research gate
<http://www.researchgate.net/profile/Adam_Kapelner2>|publons
<https://publons.com/author/431881/adam-kapelner#profile>)

**Comment by larskotthoff** [comment]
That fixed it, thanks!

**Comment by kapelner** [comment]
Wow - totally weird.

This fix will come out in the next bartMachine release. Until then... let's
just hope people find this thread...

I want to reiterate that defaulting to replace_missing_data_with_x_j_bar =
TRUE is a very bad strategy if users care about their predictive accuracy.

On Wed, Aug 12, 2015 at 6:38 PM, Lars Kotthoff <notifications@github.com>
wrote:

> That fixed it, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlr-org/mlr/issues/422#issuecomment-130468444>.
>



-- 
Adam Kapelner, Ph.D.
Assistant Professor of Mathematics
Queens College, City University of New York
65-30 Kissena Blvd., Kiely Hall Room 604
Flushing, NY, 11367 M: 516-435-6795
kapelner.com (scholar
<https://scholar.google.com/citations?user=TzgMmnoAAAAJ>|research gate
<http://www.researchgate.net/profile/Adam_Kapelner2>|publons
<https://publons.com/author/431881/adam-kapelner#profile>)

**Comment by larskotthoff** [comment]
Great, thanks. It'd be great if you could ping us here when the next release is out so that we can revert the changes in the source we did to fix it. I'll close this issue.

**Comment by kapelner** [comment]
This is now fixed in v1.2.1. Please upgrade. Sorry for the delay on this...

**Comment by berndbischl** [comment]
reopening this. We need to look at this, whether we can readd bartmachine again

**Comment by berndbischl** [comment]
and then recheck this issue
