### ISSUE TITLE
The `subset` parameter in `train` doesn't work perfectly

### ISSUE THREAD

**Issue by hetong007** [mlr-org/mlr#426]
Since `xgboost` is on CRAN again, I am trying to add it as a learner in `mlr`. When I was writing the test, I found that the `subset` parameter in `testSimple -> train` doesn't work because `xgboost` itself doesn't have this parameter.

In this line: https://github.com/mlr-org/mlr/blob/master/R/train.R#L48, the subset parameter is meant to be passed to the modelling function, if the model doesn't have it, it will still train the model on the entire data set.

**Comment by mllg** [comment]
You need to pass the subset parameter to getTaskData() to get the training
data AS data.frame. See, e.g.,
https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_boosting.R
Am 04.08.2015 05:38 schrieb "Tong He" <notifications@github.com>:

**Comment by hetong007** [comment]
Oh I see. Thanks for pointing this out!
