### ISSUE TITLE
Examples load too many packages for check to succeed

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#429]
Travis currently gives:

    * checking examples ... ERROR
    Running examples in ‘mlr-Ex.R’ failed
    The error most likely occurred in:
    > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
    > ### Name: plotCalibration
    > ### Title: Plot calibration data using ggplot2.
    > ### Aliases: plotCalibration
    > 
    > ### ** Examples
    > 
    > lrns = list(makeLearner("classif.rpart", predict.type = "prob"),
    +             makeLearner("classif.nnet", predict.type = "prob"))
    > fit = lapply(lrns, train, task = iris.task)
    # weights:  27
    initial  value 203.863031 
    iter  10 value 112.181981
    iter  20 value 12.232541
    iter  30 value 6.085504
    iter  40 value 6.025532
    iter  50 value 5.988263
    iter  60 value 5.970419
    iter  70 value 5.953731
    iter  80 value 5.952943
    iter  90 value 5.946404
    iter 100 value 5.939855
    final  value 5.939855 
    stopped after 100 iterations
    > pred = lapply(fit, predict, task = iris.task)
    > names(pred) = c("rpart", "nnet")
    > out = generateCalibrationData(pred, groups = 3)
    Error in requirePackages("Hmisc", default.method = "load", why = "Equal width binning of probabilities.") : 
      For Equal width binning of probabilities. please install the following packages: Hmisc
    Calls: generateCalibrationData ... generateCalibrationData.list -> lapply -> FUN -> requirePackages -> stopf
    Execution halted

This is our old friend the "maximal number of DLLs reached" error again unless I'm very mistaken. I don't see a way of fixing this apart from reducing the number of packages loaded in the examples (and dealing with the same problem again in a few months).

**Comment by larskotthoff** [comment]
This is "fixed" for now. I'm leaving this open to see if we can find a more permanent solution.

**Comment by berndbischl** [comment]
I dont see a solution now and this keeps messing up the tracker. 
Open it, when you want to discuss this further or it gets annoying again.
