### ISSUE TITLE
Bug in performance calculation for a ResamplePrediction?

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#431]
Some functions like `tuneThreshold` or `generateThreshVsPerfData` call `performance` on a `ResamplePrediction`.
For example `tuneThreshold` and `generateThreshVsPerfData` both contain something like

```
performance(setThreshold(pred, ...))
```

where `pred` and thus `setThreshold(pred, ...)` are `Prediction`s (and therefore can also be `ResamplePrediction`s) to calculate performance values for different threshold settings.

`performance` seems to treat the `ResamplePrediction` as a `Prediction`, the aggregation functions in the `Measure`s are not taken into account, which can lead to totally wrong performance values, for example:

```
set.seed(123)
m = mmce
m = setAggregation(m, b632)

rdesc = makeResampleDesc("Bootstrap", iters = 5, predict = "both")
r1 = resample(makeLearner("classif.lda", predict.type = "prob"), sonar.task, rdesc, list(mmce, m))
r1$aggr
# mmce.test.mean      mmce.b632 
#     0.2695533      0.1898192 

d1 = generateThreshVsPerfData(r1, list(mmce, m))
plotThreshVsPerf(d1)

performance(r1$pred, list(mmce, m))
#     mmce     mmce 
#0.109375 0.109375
performance(setThreshold(r1$pred, 0.5), list(mmce, m))
    # mmce     mmce 
#0.109375 0.109375

set.seed(123)
rdesc = makeResampleDesc("Bootstrap", iters = 5)
r2 = resample(makeLearner("classif.lda", predict.type = "prob"), sonar.task, rdesc)
r2$aggr
# mmce.test.mean 
#      0.2695533 

d2 = generateThreshVsPerfData(r2)
plotThreshVsPerf(d2)

performance(r2$pred)
#      mmce 
#0.2690217 
performance(setThreshold(r2$pred, 0.5))
#      mmce 
#0.2690217
```

I hope I'm not doing something wrong.
In case of `tuneThreshold` I'm not sure if it was originally intended for `ResamplePrediction`s.

**Comment by jakob-r** [comment]
The problems are two:
* `predict = "both"` has not been taken into account in `performance.R`
* `performance.R` is not made for `ResamplePrediction` and it just works by chance

**Comment by jakob-r** [comment]
Well. Theoretically we have all the information we need in `r1$pred$data` to split the double occurrences back to train and test  as this information is in `pred$data$set`.
However I think this is rather clumsy. I can see why in `makeResamplePrediction` we put everything into one `data.frame` because it is handy for something like the `cv` where we don't have predictions for the training set. But other than that the information becomes really unhandy.
My proposal
* Store the prediction of each fold in a list like it is *natural* 
* adapt performance function to that
* getPrediction* can do the work of putting everything together where it makes sense

**cons**
* will be a lot of work to restructure everything - but seeing what we have now - it looks not so nice

**Comment by berndbischl** [comment]
@schiffner 
Do you remember wether we discussed a possible soultion here?

**Comment by schiffner** [comment]
I don't recall that we found a concrete solution. What I do remember is: We agreed that the `ResamplePrediction` should be composed of several `Predictions` as opposed to the current state, where it is derived/inherits from a `Prediction`.
I am very much willing to help/discuss more.

**Comment by larskotthoff** [comment]
Ok, I've had a look at this and made a PR that at least fixes `performance()` for `ResamplePrediction`s (#548).

`Prediction`s and `ResamplePrediction`s are used interchangeably all over the place in the source and examples in the documentation. Fixing this properly will require a large amount of refactoring (probably by S3'ing all of those functions that use them and specialising for each case). This will require checking a lot of unrelated code, as e.g. `plotROCCurves()` assumes that the names of measures in the generated data will be the same as the vanilla measure names, which they won't be with resampling.

I propose to postpone fixing this properly for a release after 2.5. It's not entirely clear to me what the best way of fixing it will be and it's too much work to be done soon.

**Comment by jakob-r** [comment]
Yeah. It's quite messy. What @schiffner said sounds plausible. S3`ing us out of the misery might be the solution. I would like to have it in 2.5 as it is a necessary fix in my eyes. I would like to have kind of a lock on mlr for one or two days and someone who is partly available at these days to make decisions together.

**Comment by berndbischl** [comment]
For 2.5 this is rather impossible. But we can surely find a date to make discuss this decision for 2.6 very soon.

**Comment by larskotthoff** [comment]
I agree with @berndbischl -- 2.5 has been pushed back too often already and doing a major thing like this will further delay it significantly.

**Comment by jakob-r** [comment]
A lot has happened to the named functions and the code provided by @schiffner now produces the expected result and I don't see any bugs anymore. So I don't see a reason anymore to tag it as [prio-severe].

Still, the internals are messy and I don't like them but to get this straight we would have to freeze most of the work on mlr to not run into conflicts. 

@berndbischl What is your suggestion?

**Comment by pat-s** [comment]
Based on Jakobs last comment this is not "cleaned" anytime soon.
