### ISSUE TITLE
Implement way to estimate overfitting of models

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#433]
There's an interesting way to estimate the relative overfitting of a model described in Improvements on Cross-Validation: The .632+ Bootstrap Method by Bradley Efron and Robert Tibshirani (page 552, equation 28). This would be useful to have in mlr.

I'm opening this issue primarily to discuss whether the way I've implemented it makes sense. The way it is described in the paper requires O(n^2) performance function evaluations where n is the size of the dataset -- this is quite slow in practice.

**Comment by larskotthoff** [comment]
Summary from call with Bernd about this:

- change implementation to allow ResampleDescription, ResamplePrediction, separate train/test predictions
- change implementation of b632+ aggregation to call this method
- clean up checks
- rename to something imperative

**Comment by larskotthoff** [comment]
#236 is related in some way (or so I'm told by Bernd).

**Comment by berndbischl** [comment]
it is a very different procedure, but tries to roughly reach the same goal. we could, but dont have to, discuss it jointly.

**Comment by pat-s** [comment]
Merged in #530.
