### ISSUE TITLE
Add support for ranger

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#438]
[ranger](https://cran.r-project.org/web/packages/ranger/index.html) provides random forests for classification, regression and survival.

**Comment by jakob-r** [comment]
The guys from ranger wanted to submit a pull request by themselves. I will write them an email.

**Comment by jakob-r** [comment]
Pull request is [here](https://github.com/mlr-org/mlr/pull/452) but travis fails. Why?

**Comment by mnwright** [comment]
Problem seems to be an ancient gcc version, ranger requires gcc >=4.7.

**Comment by larskotthoff** [comment]
Seems to be an open Travis issue: https://github.com/travis-ci/travis-ci/issues/1379

**Comment by giuseppec** [comment]
The travis issue is open since 2013... Should we wait until travis fixes this issue or can we merge or can avoid this issue somehow?
I looked through the ranger code and noticed:
1) mtry and min.node.size does not have a default value, any specific reason for this?
2) verbose, seed, save.memory and num.threads should have the `tunable = FALSE` option
rest seems okay

**Comment by mnwright** [comment]
1) Default values for mtry and min.node.size depend on the data: mtry = (sqrt(#independent vars)), min.node.size is 1 for classification, 5 for regression, 10 for probability forests and 3 for survival. Is it possible to include this in mlr or is it OK to have no defaults?
2) Added.

**Comment by berndbischl** [comment]
1) Data dep defaults are currently not possible to enter. But: 
a) @kerschke is working on this, so we can add expressions here.
b) it is for "bookkeeping" only, your defaults are used, as they are, we change nothing, if the user does not request it,
So: Simply leave out the defaults for these params for now. Please add a (verbose) FIXME in the code so we can improve it later.

2) thx.

**Comment by berndbischl** [comment]
if ranger really does not work now on travis, add a FIXME in the tests and disable them for now

**Comment by mllg** [comment]
We can use GCC 4.8 on travis. 
Example package with ranger: https://github.com/mllg/ttest
Successful build: https://travis-ci.org/mllg/ttest/builds/80257648

**Comment by mnwright** [comment]
Thanks, it's working now.

**Comment by mllg** [comment]
Great. I'll close this one and move the discussion to the PR.
