### ISSUE TITLE
makeLearner returns error in R 3.2.0

### ISSUE THREAD

**Issue by Eupraxis** [mlr-org/mlr#441]
Here's the code and ouput:

>makeLearner("classif.nnet")

>Error in substr(packs, 1L + (force.load | force.attach), nchar(packs)) : 
>  4 arguments passed to .Internal(nchar) which requires 3

**Comment by larskotthoff** [comment]
Works fine for me in R 3.2.1. We run Travis regularly and it worked fine on R 3.2.0 (see e.g. https://s3.amazonaws.com/archive.travis-ci.org/jobs/62885429/log.txt). Could you give us some more information?

**Comment by mllg** [comment]
This is a windows binary problem. R core decided to touch the signature of `nchar`, but the bytecode is still compiled against the old signature. By now Uwe should have built a new binary, therefore please re-install `BBmisc` and try again.

**Comment by berndbischl** [comment]
I will close this as like Michel sais this is a CRAN problem and should be solved.

I this is untrue please reopen and complain again.

**Comment by berndbischl** [comment]
Ok, the situation is more complex than I first.

And it REALLY sucks, although we have zero fault and also about zero control to change something here. Uwe Ligges, after my complaint, rebuild the package on Winbuilder. I guess that now means that BBmisc works with 3.2.2, but not anymore with R 3.2.0, due to the API change they did in 3.2.1. 

Can somebody with a Windows machine please confirm? 

And if I am right, I have no idea what to do about this. Well, I guess it means if you use mlr (or ANY of our packages, they all depend on BBmisc...) on Windows, CRAN now "broke" R 3.2.0 for you, forever?

**Comment by Eupraxis** [comment]
Bernd:

Thanks for following up. I was going to upgrade the latest R release
anyway, so I think it will work after I do that. However, it seemed weird
that I was getting an error from so deep within R when I ran it so i wanted
to bring it to your attention.

I will upgrade and then update all my packages and get back to everyone on
how my run goes.

**Comment by berndbischl** [comment]
Welcome + sorry :(
Hopefully this does not happen again....

**Comment by Eupraxis** [comment]
Ok, learners are initialized without errors now. I upgraded R to the
following:

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Platform: x86_64-w64-mingw32/x64 (64-bit)

Mike

**Comment by glivici** [comment]
Hi! I have the same problem. Please, can anyone give me a hint to solution? I have the same R version  3.2.0. Thank you!

**Comment by berndbischl** [comment]
hi. you did not post that much info....
have you read the thread? if you are under windows and use r 3.2.0 i am afraid that you have to upgrade R as I wrote above and @Eupraxis did...

**Comment by mllg** [comment]
You could also try this first:

```{r}
update.packages(checkBuilt=TRUE, ask=FALSE)
```

**Comment by mllg** [comment]
And to be sure that everything really gets updated, call `update.packages` again with a source install:

```{r}
update.packages(checkBuilt=TRUE, ask=FALSE, type="source")
```

Note that you might need to install [Rtools](https://cran.r-project.org/bin/windows/Rtools/) for a source install.
