### ISSUE TITLE
How to hande double meanings of parameters (svm)

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#442]
For the `e1071::svm` we have the `gamma` parameter which has different meanings depending on the kernel
>	0 -- linear: u'*v
>	1 -- polynomial: (gamma*u'*v + coef0)^degree
>	2 -- radial basis function: exp(-gamma*|u-v|^2)
>	3 -- sigmoid: tanh(gamma*u'*v + coef0)
~ https://www.csie.ntu.edu.tw/~cjlin/libsvm/

How can we define a ParamSet for tuning which meets those requirements? Or should we rename the parameter in *mlr*?

Following won't work (obviously) but might be what the user wants.
```r
ps = makeParamSet(
  makeNumericParam("gamma", lower = -15, upper = 15, trafo = function(x) 2^x, requires = expression(kernel == "radial")),
  makeNumericParam("gamma", lower = 0, upper = 1, requires = expression(kernel == "polynomial")),
  makeDiscreteParam("kernel", values = c("radial", "polynomial")),
)
```

**Comment by berndbischl** [comment]
I dont see a simple solution for this currently.
Create a modelmultiplexer?

**Comment by jakob-r** [comment]
I think that is a simple solution (for now)
