### ISSUE TITLE
benchmark should add an option keep.models

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#443]
this is very mem hungry, but some users might want this for convenience

**Comment by giuseppec** [comment]
In the `BenchmarkResult` Object, we have redundant info for the learner, which increases the object size:

```
task = makeClassifTask(data = iris, target = "Species")
rdesc = makeResampleDesc("CV", iters = 2)
b = benchmark(makeLearner("classif.qda"), task, rdesc)

all.equal(b$learners$classif.qda, b$results$iris$classif.qda$learner)
```

**Comment by jakob-r** [comment]
I think this "problem" we have multiple times. But what you mention is just the definition of the learner and and thus independent of the task size and usually pretty small as it's more or less just a basic list.
```r
object.size(b$learners$classif.qda)
# 11392 bytes
```

**Comment by berndbischl** [comment]
We dont care about the redundant learners at the moment.

But will add the models with an option.

I assigned @florianfendt

**Comment by berndbischl** [comment]
maybe also add a getter for the models in bmr_operators

**Comment by berndbischl** [comment]
this is done now
