### ISSUE TITLE
add a few standard ResampleDesc objects, to save some typing

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#447]
maybe cv3, cv5, cv10

**Comment by jakob-r** [comment]
Is that really necessary as we have `crossval(learner, task, iters = 10L)` ?

**Comment by berndbischl** [comment]
yes, because we also want to pass them to tuneParams and other stuff.

**Comment by jakob-r** [comment]
That on the other hand would mean that we can drop `crossval()`, no? Or am I to keen on removing things we have to maintain?

**Comment by berndbischl** [comment]
no, i dont want to drop that. it is just 2 very similar, but still slightly different things.
also: people already use crossval

**Comment by berndbischl** [comment]
done. thx
