### ISSUE TITLE
Question about listLearners

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#450]
I'm a little puzzled about the behavior of `listLearners`. Do I understand correctly that if I do something like `listLearners("classif")` the packages needed for the learners should not be loaded?

I played around with various examples/settings of `create`, `quiet`, `check.packages`, .... What I observe is that

* packages are always loaded (even if I set `create = FALSE` explicitly),
* I always see package startup messages (even if `quiet = TRUE`).

That's not intended, is it?

**Comment by larskotthoff** [comment]
No, that shouldn't happen (with the github master). How exactly are you calling it?

**Comment by berndbischl** [comment]
I can confirm the problem.

**Comment by berndbischl** [comment]
@larskotthoff 
Well, you broke it. Didnt you check this when you did this here?
https://github.com/mlr-org/mlr/commit/775e23b2c5ca0d05187b6ecf50a97bf65bbbf6e2

I mean also, if I look at the code, you have these if-branches with "!create".
You still eval(mb), which of course now constructs the learner.
This is exactly what I did not do before, when I changed listLearners....

**Comment by berndbischl** [comment]
To reproduce: Just run listLearners("classif")

**Comment by larskotthoff** [comment]
I did check this -- turns out that it's in fact the learner properties refactoring that broke it. I've fixed that and will try to come up with a test.

**Comment by schiffner** [comment]
@berndbischl, @larskotthoff: Thanks for fixing! (And sorry for not replying earlier!)
