### ISSUE TITLE
Give references where we have our own implementations.

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#451]
_mlr_ has become more than just an interface to other machine learning packages.
That's why I think it is important to give sources for the methodical parts of mlr in the documentation.
Such as:
- `bootstrapStandardError()` and `jackknifeStandardError()` in `RLearner_regr_randomForest.R`
- `BaggingWrapper.R`
- `CostSens*Wrapper.R`
- various filter methods
- `ImputeMethods.R`
- ...
  (please continue list)

Something unified would be perfect, so that when we use the methods of `mlr` in a scientific context we can easily quote the stuff.

**Comment by zmjones** [comment]
- `generatePartialPrediction.R`. I only reference the recent algorithm since the basic one is so well known (usual cite is Friedman 2001). The latter (Goldstein et. al. 2014) is mentioned in the docs.

The standard error estimators for RF I think are all described in Sexton and Laake (2009). 

The stuff that @ljudt added in `generateCritDifferences.R` needs cites.

**Comment by larskotthoff** [comment]
Why don't we make all of those @references in the documentation?

**Comment by zmjones** [comment]
Do you have an example of its use? I don't see it mentioned in the roxygen2 manual.

**Comment by larskotthoff** [comment]
See e.g. https://github.com/mlr-org/mlr/blob/master/R/plotBenchmarkResult.R https://github.com/mlr-org/mlr/blob/master/R/relativeOvertiffing.R https://github.com/mlr-org/mlr/blob/master/R/generateCritDifferences.R

**Comment by berndbischl** [comment]
> mlr has become more than just an interface to other machine learning packages.
> That's why I think it is important to give sources for the methodical parts of mlr in the documentation.

I heavily agree. And I have already told multiple people to do this for new stuff, and we should try to fix it for older, longer existing methods. What must be done are 2 things:
a)  The general procedure of an algorithm should be documented, normally, in the R docs. This is the correct place for this. So by reading the docs, I should get a precise idea of what happens. 
As good as this can be achieved in writing e.g. half a page of text.
b) If it exists, a more detailed paper should be referenced, that includes more and better info. 
The tutorial should introduce such methods in a simple way, so "beginners" get the rough idea. 

> Something unified would be perfect, so that when we use the methods of mlr

I dont know what this should mean. Like Lars said, normally one uses @references. I dont see what else we can do?

> The stuff that @ljudt added in generateCritDifferences.R needs cites.

Wasnt this added by @pfistfl?

**Comment by berndbischl** [comment]
@jakob-r 
Regarding the issue itself: I think it is a good idea that we discuss this now. But this will stay a problem in the future. We should simply agree on a "procedure" to ref / doc this and add it to the mlr developer hints in the wiki. OK?

**Comment by larskotthoff** [comment]
For algorithms in the literature, is it enough to reference a paper or should it be explained even if there are no modifications?

**Comment by berndbischl** [comment]
> For algorithms in the literature, is it enough to reference a paper or should it be explained even if there 
> are no modifications?

Well "it depends". 
I tried to explain this above. 

Compare these three options.

1) RDOCS: "Function f implements algo A. Please read (hard to read paper) P. (which is not freely available online)"

2) RDOCS: "Function f implements algo A, from paper P. Here is how it works <10 pages of text, basically a copy of the paper> .

3)  RDOCS: "Function f implements algo A, from paper P. Here is how it works roughly, 
<0.5 pages of text>. For more details please read P. 

I find 3) best, so in 95% of cases i dont need to open the ref. 

(Of course all deviations from papers should be documented pretty precisely)

**Comment by larskotthoff** [comment]
Ok, concrete example: Would you consider https://github.com/mlr-org/mlr/blob/master/R/relativeOvertiffing.R sufficient?

**Comment by berndbischl** [comment]
> Ok, concrete example: Would you consider https://github.com/mlr-
> org/mlr/blob/master/R/relativeOvertiffing.R sufficient?

That matches very closely what I meant above. Regarding the code itself: We discussed this on hangout.

**Comment by jakob-r** [comment]
>> Something unified would be perfect, so that when we use the methods of mlr

> I dont know what this should mean. Like Lars said, normally one uses @references. I dont see what else we can do?

That's exactly what I meant.

> We should simply agree on a "procedure" to ref / doc this and add it to the mlr developer hints in the wiki. OK?

I think this is fine. But I know for myself that I now checked the wiki for like the third time but we could mention it a bit more on top of README.md. I will edit the wiki now.

**Comment by jakob-r** [comment]
> The standard error estimators for RF I think are all described in Sexton and Laake (2009).

Or *Standard errors for bagged and random forest estimators* by Efron 1992

There we have the *it* 😌

**Comment by berndbischl** [comment]
@jakob-r 
Would you be so kind to do this, for the methods mentioned above?
IMHO we should close this issue then here, because it will not help.

Lars already documented this in wiki how to go about this in general.

**Comment by jakob-r** [comment]
How to do it when we have a Control object which determines which method is used?
* `makeFeatSelControl`

or similar the `method` of `filterFeatures()` or all the measures.

**Comment by berndbischl** [comment]
For feature selection all algos are documented under FeatSelControl. That seems the the best place to put lit refs.

For filterFeatures we could do the same. Just put a description there with the list of refs. If it is not complete, that does not matter. Put the refs there you currently seem to have in mind.

**Comment by berndbischl** [comment]
ping @jakob-r 
you wanted a issue, do this. it does not have to be 100% complete

**Comment by berndbischl** [comment]
@MariaErdmann 
Try to close this ASAP. Add refs where they are missing AND the method is already mentioned here.

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
