### ISSUE TITLE
plotPartialPrediction and other new plotters by zach

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#456]
Hi Zach,

could you please look a few minor things I noticed while trying out the plot?

1) You dont use the "standard" in mlr to document parameters. 
Eg the curly brackets around data types and the line breaks and so on.
Can you please look and an older mlr function to compare and adapt your roxygen code.

2) For some stuff we should use roxygen templates 
Eg we already have ret_ggplot2. We should also have that for ggvis.
Copypaste is always bad.

3) Does it make sense to doc all plot/generate functions for a specific plot on 1 page?
I would say "yes". Can we do that? 
With "@rdname".

Example code for now:

```
m = train("regr.randomForest", bh.task)
d = generatePartialPredictionData(m, data = getTaskData(bh.task), features = getTaskFeatureNames(bh.task))
plotPartialPredictionGGVIS(d)
```

4) Can we please pass the task the model was trained on into the function instead of the data.frame?
That seems much better. Then we can also set a default for the features. Eg.
all features if there are <= 10, or the first 10?

5) If you look at the x axis above for some features, numbers overlap and the axis looks bad. 
I know we said we do "default settings", but shall we not at least turn the labels by 45 degrees and doc this?

**Comment by berndbischl** [comment]
@zmjones

**Comment by berndbischl** [comment]
Shall we also talk about whether you would be up to contribute further to the project?

**Comment by zmjones** [comment]
I definitely plan on continuing, though of course now I have a bunch of other things to do as well; that is, if you all are still interested.

I will work on the documentation today.

Do you think it always makes sense to only use the training data as the data for computing partial predictions? If that is not always the case then relying on the task only would not work. That would be nice in producing a reasonable default. And changing the default orientation of the axes is a good idea as well.

I've had some trouble with it but a partial derivative estimator will make it into this function soon as well. Then I'd like to implement the functional anova decomposition as well.

**Comment by schiffner** [comment]
About the plot docs:

Re 3) I'm not sure, since there is not that much overlap in the function arguments. It's just my personal preference, but I usually hate it to scroll through a long list of mostly irrelevant arguments to find the ones that apply to the function I want to use.

Re 5) Would it make sense to cut decimal places instead/additionally?

6) I noticed that sometimes (e.g. `generateThreshVsPerfData`) the returned object is not mentioned. As it's an S3 object with a special class I think it should be.
In case of learning curves `LearningCurveData` has its own page with only little information. I guess that's not really needed.

About contributing: Big +1 :)

**Comment by zmjones** [comment]
Ah thanks @schiffner I will fix `generateThreshVsPerfData` as well then. 

We do have a page in the tutorial with all the plot/generate functions listed, but combining the documentation would be a bad idea I think. As Julia points out most of them have few arguments in common, and some have quite a number of arguments, so it would be quite messy.

**Comment by berndbischl** [comment]
> [contrib more] that is, if you all are still interested.

Please. We can also talk about this on Hangout. I would love you to join the team in anyway you like.

> I will work on the documentation today.

Awesome.

> Do you think it always makes sense to only use the training data as the data for computing partial
> predictions? 

Maybe you are right. Maybe rename "data", or even leave the name, but allow to pass the task as well?
IIRC you can also access the feature names from the model, as a default? The model contains a task.desc object. 

> Julia: Would it make sense to cut decimal places instead/additionally?

That is also an option, or maybe even mandatory. Although I never really saw a case where label turning did not help / hurt? Maybe do both?

**Comment by zmjones** [comment]
Ok I've fixed the docs and will issue a PR momentarily. I have to go caffeinate myself before class but will be back online in about 2 hours and will do the rounding/label rotation and can do a hangout as well if that is convenient. Also I think passing task and/or data should not be difficult.

**Comment by schiffner** [comment]
Thank you, Zach!

Forgot something: Just noticed that in the GGVIS plot (Bernd's example) the values on the x-axis are decreasing instead of increasing. It seems to take the values in the order as they are in the `$data`-slot...

**Comment by berndbischl** [comment]
> but combining the documentation would be a bad idea I think

OK, you can veto this. I hate combined doc pages in most cases, too. Very much. 
I just wondered whether it makes sense here.
But can we, somewhere in the devel docs, say where the examples go for plots? 
Always in the generate function? 
I guess most people would look at the plot* function first. But I want one defined place, without copy paste.

**Comment by zmjones** [comment]
Yea that makes sense for the examples especially. And by the devel docs do you mean in the wiki or also on the plot/generate page I mentioned?

Julia: I will fix that when I get back from class.
