### ISSUE TITLE
surv task predictions when newdata is a data.frame w/ one row

### ISSUE THREAD

**Issue by zmjones** [mlr-org/mlr#465]
```{r}
> fit = train(makeLearner("surv.rpart"), wpbc.task)
> predict(fit, newdata = getTaskData(wpbc.task)[1, ])
Error in truth[, 1L] (from Prediction.R#126) : incorrect number of dimensions
```

It appears that in `predict.wrappedModel` the line

```{r}
truth = newdata[, t.col, drop = TRUE]
```

results in (for survival tasks where the number of rows in `newdata = 1`)  two length one vectors with different names which when "dropped" results in a named list of two length one vectors instead of a `data.frame` with two columns and one row. Is that the desired behavior?

**Comment by zmjones** [comment]
cc @mllg

**Comment by berndbischl** [comment]
Michel can you take care of this pls?

**Comment by zmjones** [comment]
Can we have (in `predict.R`)?

```{r}
...
truth = newdata[, t.col, drop = TRUE]
if (is.list(truth))
  truth = data.frame(truth)
}
