### ISSUE TITLE
new irace causes build failing?

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#470]
Looking for `Error: tuneIrace` or `argument "candidate" is missing, with no default` in the [travis build 79704049](https://s3.amazonaws.com/archive.travis-ci.org/jobs/79704049/log.txt) log file, tells us that the new [irace](https://cran.r-project.org/web/packages/irace/index.html) on CRAN is causing the build failing. Running all checks locally with the old irace package worked for me.

**Comment by berndbischl** [comment]
The interface changed. I will do that

**Comment by giuseppec** [comment]
fixed in https://github.com/mlr-org/mlr/commit/93956c6ce60a4c13f048a9c4bd4c7b8fe42088fb
