### ISSUE TITLE
Allow sparse matrices in mlr?

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#471]
LiblineaR allows the use of sparse matrices from the `SparseM` package. We should think of allowing the user to choose sparse matrices to train the model (e.g. if we decide to store the sparse  in the task). Especially when there are many zeros in the data, this can make things faster (see also http://www.johnmyleswhite.com/notebook/2011/10/31/using-sparse-matrices-in-r/).  
The easierst way (which is currently done in xgboost https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_xgboost.R) would be to convert the data.frame in a sparse matrix directly in the trainLearner function, but this would be more time consuming for resampling methods because in each iteration we have to convert the sparse matrix from the data frame (I guess creating the full sparse matrix once, e.g. in the task object, and use appropriate indexing would be faster). 
So, the most efficient way to allow sparse matrices in mlr would  be to store them in the task, right? Of course all operation on tasks (for example indexing for resampling methods) must also be valid for the sparse matrix. Here a small dumb "study" to start the discussion:

```r
set.seed(1)
dat = sample(c(rep(0,5),1), 10000000, replace=TRUE)
dat = matrix(dat, ncol = 10000)
dat = data.frame(dat)

object.size(dat)
# 81040568 bytes
object.size(SparseM::as.matrix.csr(as.matrix(dat)))
# 20018728 bytes
dim(dat)
# [1]  1000 10000
dat$Y <- as.factor(sample(c(0,1), nrow(dat), replace=TRUE))
task = makeClassifTask(data=dat, target = "Y")

# dirty way to store the sparse data without response in task object
# this should be done when the task is created
task$env$sparse.data = SparseM::as.matrix.csr(as.matrix(subset(dat, select = -Y)))

# extractor for the sparse data
getTaskSparseData = function(task) return(task$env$sparse.data)
# modified train function from pull request in issue #373
trainLearner.classif.LiblineaRL2SVC = 
  function(.learner, .task, .subset, .weights = NULL, use.sparse = FALSE, ...) {
    d = getTaskData(.task, .subset, target.extra = TRUE)
    if (use.sparse) {
      LiblineaR::LiblineaR(data = getTaskSparseData(.task), target = d$target, type = 1L, ...)
    } else LiblineaR::LiblineaR(data = d$data, target = d$target, type = 1L, ...)
  }

bench = microbenchmark::microbenchmark(
  tr = trainLearner.classif.LiblineaRL2SVC(.task = task),
  tr.sparse = trainLearner.classif.LiblineaRL2SVC(.task = task, use.sparse = TRUE), 
  times = 10)
print(bench, unit="relative")
# Unit: relative
#      expr      min       lq     mean   median       uq      max neval cld
#        tr 1.441899 1.596678 1.542633 1.564515 1.447766 1.304471    10   b
# tr.sparse 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    10  a 
```

**Comment by berndbischl** [comment]
Sure, we can try to do this. But pls later. We have to clean up many other things now

**Comment by sanmai-NL** [comment]
@berndbischl 

To me as a practitioner and MSc thesis student facing only mild challenges and requirements in ML (and also `mlr`'s target audience, right?), this seems like a must-have feature that should be prioritized. The current design of `mlr` I think prevents a great many common applications. Take my largest of four design matrices within one task among a few text classification tasks:
```
#$> str(DESIGN_MAT_LST$body$SRF)
Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  ..@ i       : int [1:2829661] 0 6 7 9 16 19 23 24 25 27 ...
  ..@ p       : int [1:725113] 0 530 531 532 1709 1791 1867 2117 2118 2134 ...
  ..@ Dim     : int [1:2] 1338 725112
  ..@ Dimnames:List of 2
  .. ..$ : NULL
  .. ..$ : chr [1:725112] "\"" "\" gestelde" "\" gestelde eisen" "(" ...
  ..@ x       : num [1:2829661] 0.000925 0.002695 0.001164 0.00084 0.002151 ...
  ..@ factors : list()

#$> pryr::object_size(DESIGN_MAT_LST$body$SRF)
89.8 MB

#$> pryr::object_size(as.data.frame(as.matrix(DESIGN_MAT_LST$body$SRF)))
7.85 GB
```
Obviously, this means I will need access to a big machine whereas e.g. `glmnet` and other learners support sparse matrices fine.

I would that we all start implementing support for the official matrices, especially dgCMatrix, in the automatically loaded `Matrix` package. (I would like to help out with this, but I do not have time for that the coming two months.)

**Comment by berndbischl** [comment]
How do  we figure out wich learners support what format? Also you are very welcome to help later of you cannot do it now.

**Comment by sanmai-NL** [comment]
Yes, I can indeed help later.

If the packages for learners properly used S4 or even S3 generics, that would be easy:
```r
methods(class='dgCMatrix')
```
Two perhaps unrepresentative examples:
`glmnet::glmnet`:
```r
# ...
if (inherits(x, "sparseMatrix")) {
# ...
```

`xgboost:::xgb.get.DMatrix`:
```r
function(data, label = NULL, missing = NULL) {
  inClass <- class(data)
  if (inClass == "dgCMatrix" || inClass == "matrix") {
    if (is.null(label)) {
      stop("xgboost: need label when data is a matrix")
    }
# ...
```

So it is hard to know beforehand which training function will accept what classes of input data. One strategy I can see is to add automated tests that result in calling them with a `dgCMatrix` and see whether they signal an error. But then `mlr` should first be adapted to not reject `data` that does not inherit from a `data.frame`, e.g. in some experimental branch. I think the problems will mosty be there given the kind of behavior the package has given me so far (all kinds of argument validations that I am not sure are completely thought through), but I haven't studied your source code.

If you just want to get a quick impression of support for sparse matrices, the easiest thing may be to simply search the source code of all packages with learners suggested by `mlr` for strings like `dgCMatrix`, `sparseMatrix`. (But as for that question, perhaps importantly, there are also other classes such as the one(s) from `SparseM`.)

**Comment by berndbischl** [comment]
> Yes, I can indeed help later.

Ok.

> All kinds of argument validations that I am not sure are completely thought through)

If you see concrete problems, just discuss them. 

Conclusion: So we basically have to 
a) allow the matrices to be passed to the task
b) add properties to learners which matrices they can handle
c) add special code to train and predict of the learner, possibly
