### ISSUE TITLE
irace: should support parallel tuning

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#472]
use hookRunParallel for this

**Comment by larskotthoff** [comment]
Breaks tests, reverted. Please use PRs.

**Comment by berndbischl** [comment]
hmm, i tested this pretty intensly locally, even looked at it under top. I will do a PR.

do you have a proposal for a unit test to check that paralleliazation REALLY works?

**Comment by berndbischl** [comment]
(also: i was on the train)

**Comment by larskotthoff** [comment]
From my quick look it seemed that something unrelated was breaking (in particular the test that checks that irace allows to specify the number of digits). I don't know if this only happens if there's no parallelization, but I was able to reproduce this locally.

**Comment by berndbischl** [comment]
Argh, then you are perfectl right and I did NOT test this enough, sorry, my bad.

Still: Have an idea how to test that it indeed runs parallel?

**Comment by larskotthoff** [comment]
Wallclock time vs cpu time? That probably won't work on Travis though.

**Comment by berndbischl** [comment]
Which rules it then out.

**Comment by berndbischl** [comment]
we should REALLY check that this line is correct

 # the instance is always the same for all different param setting
 +    rin = experiment[[1]]$instance

**Comment by berndbischl** [comment]
fixed in PR #1001
