### ISSUE TITLE
ksvm has cache parameter

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#476]
I wasn't able exactly to spot out how it influences speed of the svm but for big matrixes you might want to increase this value above the default 40MB.
In the `kernlab` vignette I can only find the following:
> `cache` cache memory in MB (default 40)

**Comment by berndbischl** [comment]
how is this an issue? oh, or are you saying this param is missing from the param set?
Then please add it in a PR? It is just one line?

I can explain to you what the kernel cache does, but not here, too much typing.
Pls close soon.

**Comment by jakob-r** [comment]
See PR #480
