### ISSUE TITLE
provide a README for the mlr blog

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#488]
please describe briefly how the blog can be used to produce posts. either in the wiki or the readme of the blog repo.

**Comment by berndbischl** [comment]
@jakob-r did this nicely aready.
we should try it out with a few people and check it

**Comment by berndbischl** [comment]
Could some people pls comment? Is this done?
I read it and found it ok. 
@jakob-r @larskotthoff @zmjones

**Comment by larskotthoff** [comment]
Just fixed some typos -- looks ok to me. I haven't tried it though.

**Comment by berndbischl** [comment]
ok then we can open if problems occur
thx
