### ISSUE TITLE
Release 2.6 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#490]
I have already tagged quite a lot of stuff. Please do not add too many more things.

**Comment by berndbischl** [comment]
2.6 is defined from lars and my side. It is nearly too full already. If you want to REALLY add stuff, please discuss it here.

**Comment by zmjones** [comment]
is there a time frame for when this would be released?

**Comment by larskotthoff** [comment]
Yep, set it to November 6th for now, see https://github.com/mlr-org/mlr/milestones

**Comment by berndbischl** [comment]
I guess we dont need these threads
