### ISSUE TITLE
featingensemble 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#494]
must be reviewed, at least a bit
the test is in its own group, which probably means it is not even executed. 
it should be fast and in base
the whole algo should be benchmarked
(also this is not tobe done in this issue)

if it gets to complex, we must remove it and push it back to 2.6

**Comment by berndbischl** [comment]
it also does not use the new function makeLearnerBaseConstructor

**Comment by larskotthoff** [comment]
Unit tests run quite quickly, but don't check anything. The first one produces output that looks a bit fishy:

      truth     prob.M    prob.R response
    1     R 0.07386574 0.9261343        R
    2     R 0.09967064 0.9003294        R
    3     R 0.09520529 0.9047947        R
    4     R 0.06060965 0.9393904        R
    5     R 0.07972527 0.9202747        R
    6     R 0.03095329 0.9690467        R

I'm moving this into a `feating` branch and pushing back to 2.6.

**Comment by larskotthoff** [comment]
@aydindemircioglu Could you please check if the implementation conforms to what's described in the paper?

**Comment by aydindemircioglu** [comment]
oops, missed that one :(
but it'll take me some while to get to this.

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
