### ISSUE TITLE
disallow force for master branche

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#501]
Now that we become more experimental with our git workflow it might be a good idea to 
make the master a protected branch [here](https://github.com/mlr-org/mlr/settings/branches).

**Comment by larskotthoff** [comment]
Not sure if we need that. We're only merging into master through pull requests (except for a few cases), so this should never be an issue.

**Comment by jakob-r** [comment]
So it just gives us security and doesn't change our workflow. Sounds like a win :+1:

**Comment by larskotthoff** [comment]
Ok, done.
