### ISSUE TITLE
Is it necessary to have the man dir in the repository?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#505]

**Comment by larskotthoff** [comment]
Will devtools install from github generate the documentation or would that mean that a dev install wouldn't have documentation?

**Comment by jakob-r** [comment]
If we need them it would be a +1 for a release branch. just sayin' :airplane:

**Comment by zmjones** [comment]
What is the downside? Also, w/o a man directory we might catch errors in the roxygen docs more slowly since we would only be generating them at releases.

**Comment by larskotthoff** [comment]
Well the problem at the moment is that the documentation needs to be generated manually and people frequently forget this. Given that we're moving to pull requests only that will be checked, so it may not really be an issue.

**Comment by larskotthoff** [comment]
Closing here, see #508.
