### ISSUE TITLE
extract in resample, benchmark and convinience

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#507]
Discussion about how we want the extract to work.
Work is in branch [resample_extract](https://github.com/mlr-org/mlr/tree/resample_extract).

What we agreed on
- `extract = NULL | "default" | function`
- default is `"default"` and will trigger `getLearnerResampleExtractFunction`
- NULL will result in a list of NULLs, each NULL for one Resample Iteration
- the supplied `function` will generate a list entry called `custom`
- If something is extracted it will be in a named list (even if it's only one value)

**Comment by berndbischl** [comment]
This would be helpful:

Put some tests, for resample and and benchmark in your branch and link them here, that showcase the behavior.

**Comment by jakob-r** [comment]
Should I go for it again? I can't exactly remember what the reason was for PR #506

**Comment by berndbischl** [comment]
We can do it, but have to define it in a meeting. Remember how we screwed this up last time?

I can give you a dozen simpler issues if you simply wanna help clear up the tracker.

**Comment by berndbischl** [comment]
The reason for the reverted PR was that the system was broken, and the API that was implemented there was not optimal.

**Comment by pat-s** [comment]
Branch does not exist anymore. Also its more than 2 years ago, so the enhancement probably wasn't important enough.
