### ISSUE TITLE
Travis should generate and commit documentation

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#508]
We do this for the tutorial build already. Solves #505.

**Comment by berndbischl** [comment]
I like what you did here. 
But 2 comments:

1) We note to doc this in the contributor wiki so people know about this

2) Is there a way to "amend" the previous commit? So we have less commits in the history?

For 2) I might guess "no, not easy" but I still would like to ask

**Comment by larskotthoff** [comment]
1) Why? I don't think we need to mention automated stuff like this.

2) Technically very easy, but I wouldn't do it. It's rewriting history to some extent and asking for trouble in this context, e.g. somebody pushes a commit while the Travis build is running. We would have to worry about and handle these sorts of issues.

**Comment by berndbischl** [comment]
> 1) Why? I don't think we need to mention automated stuff like this.

Because it was a problem in the past? And isnt it now preferable NOT to commit the doc / auto files?

2) OK got your point

**Comment by larskotthoff** [comment]
Ok I guess I don't know what you're asking for 1 :) Do you mean adding something to the contributor page mentioning "Travis" as a contributor?
