### ISSUE TITLE
Integrate more GP Implementations?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#510]
We have already the approximate GP (laGP::aGP, called laGP in mlr) but it offers also a standard GP im laGP::newGP which has the nice option to run updateGP (which there is no way to implement it in mlr, yet)
But there is also the package mlePG.
It might also all be worth it because of the quirkiness of regr.km

**Comment by berndbischl** [comment]
Please note that for stuff like this we would like to have only one wiki page in the future to organize new learners. 

@florianfendt

**Comment by berndbischl** [comment]
@florianfendt 
Pls simply copy this to the list in the wiki

The model-update is a seperate issue, and we currently dont have a way to support it

**Comment by florianfendt** [comment]
updated the wiki page
