### ISSUE TITLE
Feature: Handling of Count Data, e.g. Poisson Regression

### ISSUE THREAD

**Issue by javdg** [mlr-org/mlr#515]
I intended to use mlr for a benchmark of Poisson Regression models but realized, that support for count data models hasn't actually been implemented yet.
While successfully working around these limitations in my specific use case, I talked to @berndbischl and this issue/feature request is supposed to track and coordinate any efforts towards a proper implementation.

As to specific performance measures, these StackExchange threads might be helpful:
- http://stats.stackexchange.com/questions/71720/error-metrics-for-cross-validating-poisson-models
- http://stats.stackexchange.com/questions/48811/cost-function-for-validating-poisson-regression-models

I also compiled a (likely incomplete) list of learners that might be considered (I'm personally not familiar with most of the more complex models, these might not be appropriate/a priority):

**Models for Count Data**
- glm() {stats}
- glm.nb() {MASS}
- glmnet() {glmnet}
- cv.glmnet() {glmnet}
- hurdle() {pscl}
- zeroinfl() {pscl}

**General Implementations** (including models for count data)
- gamlss() {gamlss}
- poissonff() {VGAM}

**Further Extensions** (to the classical glm, including count data models)
- finite mixture models {flexmix}
- generalized estimating equations {geepack}
- mixed-effects models {lme4, nlme}

**Apparently Outdated**
- zicounts() {zicounts - **orphaned**}
- fit.zigp() {ZIGP - **not on CRAN anymore**}

see also https://cran.r-project.org/web/packages/pscl/vignettes/countreg.pdf

Cheers,
Johannes

**Comment by bkomboz** [comment]
Hello,

two more boosting algorithms which can be used with count data:
- xgboost() {xgboost}
- gbm() {gbm}

Best
Basil

**Comment by zmjones** [comment]
i am a bit confused about why this is necessary. most (almost all?) regression methods for counts produce positive real-valued predictions. i don't see how this wouldn't work as a normal regression task. any count specific measures could be added without adding any other new structure. is there some other reason we should have count tasks that i've missed? If there is could it not be solved by adding additional structure to a regression task and maybe an additional property to regression learners (e.g., check/enforce non-negativity).

**Comment by javdg** [comment]
Hi,
this thread arose from encountering what has later been independently reported (and fixed in the meantime) as https://github.com/mlr-org/mlr/issues/559.
In my subsequent discussions with @berndbischl he suggested to tackle this issue in a systematic manner and to create this bug to track any developments in this regard.
I tend to agree, this doesn't necessarily require to create a completely new and separate count task - even though I think that's what Bernd had in mind originally, but he needed some more time to look into it.

**Comment by javdg** [comment]
As per our conversation from the weekend, this is to ping @berndbischl ...

**Comment by SimonCoulombe** [comment]
Hi, I was wondering if there is any way to do poisson regression?  If so, I am curious how to include the offset for exposure.
cheers

**Comment by j-hartshorn** [comment]
This would be a very useful addition, and I think it could be done with an addition of an `offset` argument to tasks not unlike the `weights` argument. From there, learners could use that for training and prediction.

Does anyone know why this might not be a good idea?

**Comment by pat-s** [comment]
If someone comes up with a PR for this, we are happy to review this. For now, I close here and advise future enhancements to be added to _mlr3_.
