### ISSUE TITLE
Using univariate filter in makeFilterWrapper() or filterFeature() results in checkLearner(perf.learner) error

### ISSUE THREAD

**Issue by enricoferrero** [mlr-org/mlr#516]
I get this error when using the `univariate` filter in `makeFilterWrapper()` or `filterFeature()`:
```{r}
Error in checkLearner(perf.learner) :
  argument "perf.learner" is missing, with no default
```

**Input:**
```{r}
library(mlr)
sessionInfo()
set.seed(16)

dat <- data.frame(replicate(2500, sample(0:1, 500, rep=TRUE)))
classif.task <- makeClassifTask(id="test", data=dat, target="X1")
lrn <- makeLearner("classif.svm")
lrn <- makeFilterWrapper(lrn, fw.method="univariate", fw.perc=0.1)
mod1 <- train(lrn, classif.task)
```

**Output:**
```{r}
$ R --vanilla

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source("mlr-test.R", echo=TRUE)

> library(mlr)
Loading required package: BBmisc
Loading required package: ggplot2
Need help? Try the ggplot2 mailing list: http://groups.google.com/group/ggplot2.
Loading required package: ParamHelpers

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.6 (Santiago)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=C
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=C
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] mlr_2.4          ParamHelpers_1.5 ggplot2_1.0.1    BBmisc_1.9

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1      digest_0.6.8     MASS_7.3-43      grid_3.2.2
 [5] plyr_1.8.3       gtable_0.1.2     magrittr_1.5     scales_0.3.0
 [9] stringi_0.5-5    reshape2_1.4.1   parallelMap_1.3  checkmate_1.6.2
[13] splines_3.2.2    proto_0.3-10     tools_3.2.2      stringr_1.0.0
[17] munsell_0.4.2    survival_2.38-3  parallel_3.2.2   colorspace_1.2-6

> set.seed(16)

> dat <- data.frame(replicate(2500, sample(0:1, 500, rep=TRUE)))

> classif.task <- makeClassifTask(id="test", data=dat, target="X1")

> lrn <- makeLearner("classif.svm")

> lrn <- makeFilterWrapper(lrn, fw.method="univariate", fw.perc=0.1)

> mod1 <- train(lrn, classif.task)
Error in checkLearner(perf.learner) :
  argument "perf.learner" is missing, with no default
Timing stopped at: 0.129 0 0.129
```

Thank you!

**Comment by berndbischl** [comment]
Thx. This has not been used too often I guess and we miss a unit test here. I will try to look at this later.

**Comment by berndbischl** [comment]
Sorry, I dont want to steal this thread. First of all, lets ping @mllg, as he implemented this.
Now:
1) Thx to Lars for taking this over.
2) I have to say, I really dislike the name "univariate" for this filter. It should also be slightly better explained what happens in the filter. 
3) I am not sure whether we should set the RF as a default. It is at least costly. Maybe rpart? 
(unsure here)

**Comment by enricoferrero** [comment]
I agree the discussion is very vague. Re the name, I thought it came from [here](http://scikit-learn.org/stable/modules/feature_selection.html#univariate-feature-selection)?

**Comment by berndbischl** [comment]
regarding the name:
I guess we have to ask Michel. But note that scikitlearn uses the name "univariate" feature selection, well, as an umbrella term for, surprise, univariate feature selection. 
We, OTOH, use it in the case here for fitting a learner to a single feature to and using its CV score as a score. I am not even sure in which papers this is used, I am pretty sure I havent seen it often
(Not saying it is bad, it is very nice and flexible)
But the name is IMHO very misleading.

**Comment by larskotthoff** [comment]
Happy to change name and/or default learner. Will also have to document this.

**Comment by berndbischl** [comment]
Pls
- use rpart as default
- document what the method does, including the default
- call it univariate.learner ?

deprecate the old "univariate" or hard rename?

**Comment by berndbischl** [comment]
i guess (???) we can live with a rename here as this was not used too ofteen, but it kinda is against our policy. 80% weight on rename from my side

**Comment by larskotthoff** [comment]
Not sure about the name. How about "learner.importance"?

**Comment by berndbischl** [comment]
no thats worse, that indicates the importance measure extracted from a learner. 

we SHOULD have that available as a filter, but it is something different than what we discuss here

**Comment by berndbischl** [comment]
univariate.model.score?
univariate.model.cvscore?
univariate.model.perf?

**Comment by larskotthoff** [comment]
I like "univariate.model.score".

**Comment by berndbischl** [comment]
ok. deprecate or rename?

**Comment by larskotthoff** [comment]
Deprecate for 2.6, remove in 2.7.

**Comment by berndbischl** [comment]
ok, then go

**Comment by larskotthoff** [comment]
Done, I've also changed `FilterWrapper` to pass the wrapped learner if not specified.
