### ISSUE TITLE
Question about getClassWeightParam

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#525]
I can do this:

```
getClassWeightParam("classif.ksvm")
           Type len Def   Constr Req Tunable Trafo
1 numericvector  NA   - 0 to Inf   -    TRUE     -
Used: train.
```

Is this also supposed to work?

```
lrn = makeWeightedClassesWrapper("classif.ksvm", wcw.weight = 5)
getClassWeightParam(lrn)
Error in learner$par.set$pars[[learner$class.weights.param]] : 
  attempt to select less than one element
```

**Comment by berndbischl** [comment]
1) The arg check in getClassWeightParam is crap.
@larskotthoff  @larskotthoff @zmjones @mllg 
Can we please somehow teach and agree upon how checkmate should be used and that it should NOT be abused.

2) I am unsure. Probably.

**Comment by berndbischl** [comment]
Your problem exists for any kind of wrapper, that I wrap around the base learner right?

**Comment by schiffner** [comment]
I would guess so, give me a moment to check.

Re 1) What would be the correct arg check here?

**Comment by schiffner** [comment]
> Your problem exists for any kind of wrapper, that I wrap around the base learner right?

Yep.

**Comment by berndbischl** [comment]
Sorry, I wrote too quickly and the text might have been confusing. I meant this line
  assertChoice("class.weights", getLearnerProperties(learner))

This is not an "arg check" as it does not check an argument. It is supposed to check whether "class.weights" is in element of the learner properties. 

There are 2 solutions. 
a) Just check extactly what I wrote, and if not generate a stopf message. This is the "bad" solution, although better than what the programmer did above.

b) Use your brain and understand that this simply checks whether a learner has a certain property. This is extremely conmon to do this right? So we would need a function? Guess what, we already have one, it is called checkLearner. So the good solution would have been to add an arg "properties" to checkLearner, so it can be checked whether a learner has a certain property. This is a), but generalizes this and encapsulates this at the correct place.

@kerschke

**Comment by berndbischl** [comment]
I just mentioned 1) because I saw this, now for the millionth  time. 
I does not cause the error here.

**Comment by berndbischl** [comment]
It should be easy to correct this bug here. It also does not look very critical as the class weighting itself works.

**Comment by schiffner** [comment]
I know that 1) does not cause the error, but I stumbled over this line of code earlier today (totally unrelated to my question above) and then forgot to ask about it... So you are answering my questions before I ask them. That's really cool. :)

**Comment by berndbischl** [comment]
Thats just me.

**Comment by larskotthoff** [comment]
How about finishing mlr releases before I ask..? :tongue:

**Comment by berndbischl** [comment]
The sentence does not parse?

**Comment by berndbischl** [comment]
Oh it does. But see, talking != programming....

**Comment by berndbischl** [comment]
We did quite a lot of work on PH this morning. And everybody else is also welcome to do PRs for milestone 2.5.....

**Comment by berndbischl** [comment]
this issue has to be seen in context
https://github.com/mlr-org/mlr/issues/862
