### ISSUE TITLE
travis is button is red, why?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#532]
Isnt the master branch building correctly? is the badge somehome wrong?
@larskotthoff

**Comment by jakob-r** [comment]
https://travis-ci.org/mlr-org/mlr.svg is green
https://travis-ci.org/mlr-org/mlr.svg?branch=master is red

**Comment by larskotthoff** [comment]
See #531.

**Comment by berndbischl** [comment]
actually, the real issue at hand seems to be that PR travis builds somehow are shown in the badge, when ONLY the status of the master branch should be displayed.
and we did not resolve this.

but i will leave this closed now.
