### ISSUE TITLE
Set seed in makeResampleInstance

### ISSUE THREAD

**Issue by federicou** [mlr-org/mlr#543]
I use a Cross Validation with 10 iterations for validating regression models.

Is it possible to set the seed when creating a resample instance in order to get always the same training and test indexes?

Thanks
Federico

**Comment by larskotthoff** [comment]
Yes, use e.g. `options(mlr.debug.seed = 123L)`.

**Comment by berndbischl** [comment]
longer answer: 
you can seed everything in mlr, normally. actually, AFAIK cran requires that this is possible.
(with the exception of code we dont control like in the learners)
but for the resample instance: it exists so you can store it away and reuse it later. you dont necesserily have to use set.seed. just store the instance in mem or disk and reuse it in later call to resample or benchmark.

maybe we need an FAQ? this was asked now multiple times...

**Comment by federicou** [comment]
Thanks guys. Actually I adopted the solution suggested by Bernd.
