### ISSUE TITLE
Unified logging

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#544]
Use one of the logging frameworks to make logging better (i.e. allow unified redirection, groups, etc).

**Comment by jakob-r** [comment]
Can you link something. I am not totally sure of what you are talking about.

**Comment by berndbischl** [comment]
yup will do soon

**Comment by berndbischl** [comment]
The point is that many languages define a standard for logging. 
This includes:
- levels: info, debug, warn, errror, custom ones, etc
- groups of messages
- loggers that mainly direct to the output to console or files
- formatters

This simply makes things configurable and customizable from the outside. 
log4j has become somewhat of a standard
https://en.wikipedia.org/wiki/Log4j

In R this is (as always) not really defined, and nobody really seems to care.
So there are now at least 3 packages

- logging
- futile.logger
- log4r

We need to figure out which one is best and stick to it as a standard.

I invested like 20 min for this. IMHO futile.logger seems to be good, simple and active.
Please comment.

**Comment by jakob-r** [comment]
:+1: for https://github.com/zatonovo/futile.logger

**Comment by berndbischl** [comment]
Ok, Jakob, that makes then 2 votes for "futile", lets collect some more.
