### ISSUE TITLE
`getPredictionProbabilities()` does not check properly whether predictions have probabilities

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#545]
Current check is

    if (pred$predict.type != "prob")
        stop("Probabilities not present in Prediction object!")

which will fail if `predict.type` is `both`, which would be valid as well.

**Comment by schiffner** [comment]
Is the `predict.type` not always exactly one of `se`, `prob` or `response`?
Please correct me if I'm on the wrong track here...

**Comment by larskotthoff** [comment]
Yes, you're right (which makes sense as `prob` includes the response). Now I'm really confused though -- where does "both" occur? @jakob-r says 'predict = "both" has not been taken into account in performance.R' in #431.

**Comment by schiffner** [comment]
Ah ok, he means the `predict` arg of e.g. `makeResampleDesc`.
(When `performance` is applied to a `ResamplePrediction` it does not take into account if the prediction was made on the training or the test set. At least the older version. I haven't checked out your fix, yet.)

**Comment by larskotthoff** [comment]
Ok, that should be fixed in my PR. I'm closing this though as it was just caused by my confusion :)

Thanks for pointing it out.

**Comment by berndbischl** [comment]
Yes, you are all correct.

For clarification: 
predict.type = response, prob, se 
is a property / setting of the learner, telling mlr whether you want "extended" predicteions.

predict = train / test / both
is a setting for the ResampleDesc, telling mlr whether you want to calc preds on train sets, test sets, or both.
