### ISSUE TITLE
Test contexts should have the same name as the files they're in

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#547]
If the names are different, it makes it unnecessarily hard to find the relevant file from the `testthat` output.  E.g. if I get a failure in context "tune" I have to look in file "test_base_tuning.R".

**Comment by berndbischl** [comment]
I agree. In very rare cases it might make sense to name a file after a concept that is tested, but usually we test functions.

But shouldnt we put this into the developer hints wiki instead of having a issue here?

**Comment by larskotthoff** [comment]
Sure, but this also involves fixing all the existing tests.

**Comment by berndbischl** [comment]
I am not sure this issue is useful. Keep it open until the next milestone?
I mean somebody has to volunteer here....

**Comment by berndbischl** [comment]
this was fixed in 
https://github.com/mlr-org/mlr/pull/694/files

@larskotthoff  @mllg @schiffner 
Correct people if they do this wrong now in new PRs
And feel free to improves names if you see something that still not matches this scheme
