### ISSUE TITLE
Naming convention for branches

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#550]
We need it.
Suggestion:

Do you fix something?
* fix_functionOrConceptYouAreFixing

Do you fix an issue
* fix_123_(If Issue has a good title, use this one, otherwise see above)

Do you want to add a Learner?
* RLearner_regr/classif/cluster/surv_name

Do you want to try something out?
* todo_conceptYouWantToTryOut

You Want to add a new Feature
* feature_nameOfFeature

Thoughts?

**Comment by berndbischl** [comment]
Do we really need this? This looks verly complicated, and is another thing one needs to remember?
At least reduce the number of cases.

IMHO 99% of things should have a associated issue.
So we only need

- issue_123_shorttitle
- learner_name
-<rare case of something else with custom name>

we can do this if more then 1 person really want this I would say :)
then it needs to be specified in the devel wiki

**Comment by zmjones** [comment]
Although this seems sensible I don't get why this is necessary since each branch is going to (usually) be associated with a PR and a description of what the addition is will show up as the title/description in the commit that gets merged.

**Comment by berndbischl** [comment]
One problem seems to be that we have now very many branches. Getting an overview over the existing ones is annoying. I think GH asks to delete a branch, when we a PR is merged. Shall we do this in the future? (I didn't, before)

**Comment by jakob-r** [comment]
After a successful PR the branch should be deleted to not generate a mess in my opinion.
Not every branch is automatically associated with a PR, e.g. when it is just a todo or an early implementation.
So I just want it to be easier to see which branch is targeting what piece of work and the relevance.

**Comment by berndbischl** [comment]
> After a successful PR the branch should be deleted to not generate a mess in my opinion.

Ok. I guess I agree. Does anybody know a downside to this?

> Not every branch is automatically associated with a PR, 

Sure. The PRs are the bulk currently, due to our "new gatekeeper system", but of course other branches exist and are normal and OK. If we always delete the "dealt with" ones a, only a few branches with good names might exist at any given time.

**Comment by larskotthoff** [comment]
I've been deleting branches that have been merged. I can't think of any disadvantages of doing that.

Don't really see the need for naming conventions either.

**Comment by zmjones** [comment]
The branche a PR is issued from will exist in the forked repository and/or locally anyway

**Comment by berndbischl** [comment]
apparanetly nobody wants this. should be discussed during mlr hangouts anyway, complain again when you think we need this
