### ISSUE TITLE
learners parameters reference guide

### ISSUE THREAD

**Issue by federicou** [mlr-org/mlr#551]
When using a specific learner is used through makeLearner function the parameters set may differ from the official learner arguments.

For example, adopting as learner "regr.lm" from package "stats" the parameters set recognized by MLR contains the following:
- tol
- nu 

The point is that I haven't found any reference to these parameters. Is that available somewhere?

**Comment by larskotthoff** [comment]
Hmm, looks like `nu` might not be an actual parameter. `tol` is a parameter for `lm.fit`, which is called internally by `lm` (as explained in its help page).

Can somebody else confirm please whether we can drop `nu` ( @mllg seems to have added this)?

**Comment by federicou** [comment]
You're right Lars. "tol" is actually an argument of lm.fit but still "nu" is yet obscure to me.

**Comment by berndbischl** [comment]
Actually, if anything really differs in mlr from the normal names / settings, there must / should a note in the mlr learner. I can be that you also have to look at stuff at lm.fit (the underlying doc point you to it).

But nu looks like an obvious mistake. It is neither in lm nor lm.fit.

**Comment by berndbischl** [comment]
Well, the "method" was also wrong. as it has only one setting in lm.fit, I remioed it too.
