### ISSUE TITLE
unsupervised rf

### ISSUE THREAD

**Issue by zmjones** [mlr-org/mlr#552]
So I started adding unsupervised rf a minute ago. This of course doesn't work without another clustering method on top, e.g., kmeans or something. I was thinking that the predict function would just have arguments that allow you to set the secondary clustering algorithm which operates on the rf distance matrix. Does anyone have a preferred default method?

**Comment by larskotthoff** [comment]
Hang on, give me some more context here. What do you mean when you say that it won't work with any other clustering method on top (i.e. why would you want to cluster twice)? The problem is that there's no `predict()` function for this, right?

**Comment by zmjones** [comment]
Correct. It can return a distance matrix which you then have to do something with.

**Comment by larskotthoff** [comment]
The `clue` package has a function [`cl_predict()`](http://www.inside-r.org/packages/cran/clue/docs/cl_predict) that allows to make predictions for cluster "objects". We already use this for the cluster learners that don't implement `predict()` themselves. Could you have a look whether this is easily extended (or maybe it already supports distance matrices) please?

**Comment by zmjones** [comment]
Yea sure. So you are advocating a single cluster method for this? What I thought would be better would be to have some way for the user to pick any clustering method that could operate on a distance matrix. Maybe that could be an attribute that cluster learners have?

**Comment by larskotthoff** [comment]
In general you're certainly right, but this would require a bit of refactoring of the current implementation. What I'm concerned about for the moment is that new clusterers behave consistent with what we already have. I'm not sure what `cl_predict()` does internally, but I don't think it uses another clustering method.

I think it makes sense to have a `predict()` implementations that just makes predictions without requiring an additional clusterer, especially as there may be non-obvious interactions if you combine two different clusterers. I would implement this as an additional argument to the `predict()` function -- if it's there, use the clusterer that it specifies, otherwise use the current way. It could even make sense to use a classifier or regression learner in this context to make the predictions.

**Comment by zmjones** [comment]
Certainly about the interactions. So we'll have a default method and an option to use a different clusterer. I don't understand what would require refactoring. 

All I'm suggesting is what you just said (have a default method and then an argument that allows you to select another clustering method), with the addition of a new attribute for cluster learners which says whether they can handle a distance matrix. Internally to the RF cluster learner I'd create a new cluster task with the RF distance matrix as the data and proceed normally.

I am also confused about how a regression or classification learner could be used here. Could you elaborate?

**Comment by larskotthoff** [comment]
What we currently implement (`cl_predict()`) simply assigns the closest cluster to new data in `predict()` -- for the sake of consistency, I would do the same thing here. Using a different clusterer do that means that this clusterer would behave differently from the rest and this could be confusing to the user.

Having an option to use a clusterer and being able to specify it would require implementing this for all the existing clusterers as well (again to keep things consistent). This shouldn't be a lot of work, but would require careful testing as the objects the different clusterers return are so different.

I don't think any of the clusters we have in `master` at the moment support clustering distance matrices.

You could use a classification or regression learner by using the distances (to each point in the training set or each cluster center) as features and the cluster ID as label resp. the probability of being member of a cluster for regression. Not sure if this would make sense, but technically it's possible :)

**Comment by berndbischl** [comment]
@zmjones 
are you still working on this? to be honest i dont really know what the thread is about. i dont even get the first post, what your "unsupervised rf" exactly does, and how that relates to clustering.

if you are still working on this, please reopen and try to explain again what your method would do.

**Comment by zmjones** [comment]
I am still working on it but I am doing it a bit differently and am just going to make it a package.
