### ISSUE TITLE
Family argument of glmnet in "regr.glmnet" learner

### ISSUE THREAD

**Issue by bkomboz** [mlr-org/mlr#559]
I am trying to use the `regr.glmnet` learner. `getParamSet("regr.glmnet")` does not list the `family` argument of the underlying `glmnet` function. Is there a specific reason for it? Why is it not possible to set the underlying distribution? 

Thanks! (Also for providing mlr and all the work behind it!!)

**Comment by javdg** [comment]
Hi Basil,

the family argument is currently "hardcoded" to "gaussian" by mlr (see https://github.com/mlr-org/mlr/blob/master/R/RLearner_regr_glmnet.R#L49).
I have been discussing this very same issue with @berndbischl in the context of poisson models, i.e. count data. The respective progress is being tracked here: https://github.com/mlr-org/mlr/issues/515
A (dirty) workaround is to modify the regr.glmnet learner locally.

Cheers,
Johannes

**Comment by bkomboz** [comment]
Hi Johannes,
thanks for your response!

The data I am working on is also count data. So it fits to the issue you opened. I will therefore close this issue here.

Best
Basil

**Comment by berndbischl** [comment]
Shall we just allow both poisson and gaussian for regression?
Any real argument / reason against this?

(not saying we should later properly add count data tasks)
