### ISSUE TITLE
Setting order of regression in regr.lm through formula editing

### ISSUE THREAD

**Issue by federicou** [mlr-org/mlr#564]
In many cases defining the formula to be used in a linear modeling is very important.
Is there a way to add also the formula as parameter of the regr.lm?

Many thanks for your help.
Federico

**Comment by berndbischl** [comment]
Hi, not really. The problem is mlr's sytem works a bit differently. 
But this is a larger issue, also for basis functions of boosting models.

But for now: 
what do you exactly want to do?

**Comment by berndbischl** [comment]
Due you just want a quadratic model or interaction effects? then you could also use regr.rsm

**Comment by federicou** [comment]
Actually a generic way to define the formula including the interaction
effects as used in the rsm would be ok.
Il giorno ven 13 nov 2015 alle 11:37 Bernd Bischl <notifications@github.com>
ha scritto:

**Comment by berndbischl** [comment]
So at least your problem here is solved for now?

**Comment by federicou** [comment]
Actually my idea is to be able to edit a formula in lm including quadratic
or cubic. The interaction effect is a form of curvature that may be applied
for regression models but it is not as generic as the formula applied in
lm. The formula of lm in principle may also contain any operator keeping
the linearity of the regressors.
Il giorno ven 13 nov 2015 alle 12:09 Bernd Bischl <notifications@github.com>
ha scritto:

**Comment by berndbischl** [comment]
So that means using RSM, which allows to use full interactions effects or full quadratic models, does NOT solve your problem?

you need to be able to specify a custom formula?

**Comment by federicou** [comment]
Yes. That's the point. That is also useful for exporting the model in a
usable format since it is a parametric formula with defined coefficients.
Otherwise using a weird Bayesian model or a kriging model not always may be
used easily outside R or a programming package.
Il giorno ven 13 nov 2015 alle 12:24 Bernd Bischl <notifications@github.com>
ha scritto:

**Comment by berndbischl** [comment]
Unfortunately we currently dont support this at the moment. But I do see the need, yes.
But we would need to discuss this API change among the developers. 

IIRC there was also another thread about this somewhere.

**Comment by kapelner** [comment]
But it's easily done using model matrices so you don't need to explicitly support it. For example:

```
X = read.csv("white_wine.csv")
form = as.formula(quality ~ .^2 +
           poly(fixed.acidity, 6) + 
           poly(volatile.acidity, 6) + 
           poly(citric.acid, 6) + 
           poly(residual.sugar, 6) + 
           poly(chlorides, 6) +
           poly(free.sulfur.dioxide, 6) + 
           poly(total.sulfur.dioxide, 6) +
           poly(density, 6) + 
           poly(pH, 6) + 
           poly(sulphates, 6) + 
           poly(alcohol, 6))
mod_matrix = model.matrix(form, X)
head(mod_matrix)

white_wine_learning_task = makeRegrTask(data = mod_matrix, target = "quality")
#make a 10-fold
rdesc = makeResampleDesc("CV", iters = 10)
r = resample("regr.lm", white_wine_learning_task, rdesc)
r
```

**Comment by federicou** [comment]
That's a great advice. I'll arrange the mar benchmark by changing the data accordingly to the poly degree. Thanks.

**Comment by tyleransom** [comment]
@kapelner This is super helpful. Thank you!
