### ISSUE TITLE
we need to teach travis to run-dontrun and run-donttest

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#568]

**Comment by berndbischl** [comment]
https://github.com/craigcitro/r-travis/issues/165

**Comment by larskotthoff** [comment]
Don't think that this will work -- it will take longer than 50 minutes to run all of this.

**Comment by berndbischl** [comment]
Huh? Why?

**Comment by larskotthoff** [comment]
Is it really that fast for you? Hasn't finished here yet and just the examples have been running for 40 minutes now.

**Comment by berndbischl** [comment]
For 2.5, I added "dontest" to ca. 5 example blocks. They each took about 10 secs. S this is like 1 miin of extra  runtime. 

Are you currently checking locally?

Ok I see we are both using dontrun and donttest now, which is probably not so good that we mix it.
But please tell me what happens if you run this locally.

**Comment by larskotthoff** [comment]
Hmm well at the moment it seems to hang when running the examples. At least it's not finished and doesn't seem to be doing anything.

**Comment by berndbischl** [comment]
are you running with both flags?
can you pls try only with run-donttest?

because this is what i added now, dontrun must be older stuff, maybe that took REALLY long

**Comment by larskotthoff** [comment]
With both flags on I left it running for 8 hours and it didn't finish or seem to do anything. Will try the other ones now.

**Comment by larskotthoff** [comment]
Well checking takes 5 minutes both with and without `--run-donttest`, so it doesn't seem to be doing what it should.

**Comment by berndbischl** [comment]
Like I said, the dontrun stuff is just a few seconds. But you need to set this envir variable, to get all UNIT tests to run on top of test_base.
That's a different thing, nevertheless you should still do it ;-)


```
if (identical(Sys.getenv("TRAVIS"), "true") || identical(Sys.getenv("R_EXPENSIVE_TEST_OK"), "true")) {
  test_check("mlr", "_classif_")
}
```

If you want to check whether run-dontrun works, simply go to one of the places where I added the dontrun and break the example. Only WITH the flag R CMD check should fail

**Comment by larskotthoff** [comment]
Can you clarify what exactly you want me to do please? I need to run `R CMD check --run-donttest mlr_2.6.tar.gz` and set `TRAVIS` to `true`? Anything else?

**Comment by berndbischl** [comment]
clarified on hangout, but i also have problem to use run-donttest?
if i break a test, and pass the flag, i still dont see an error in CMD check?

**Comment by larskotthoff** [comment]
Hey, I've already done this in our new CI system. Now I have to do it here as well? ;)

**Comment by berndbischl** [comment]
yup suck it up life is hard

**Comment by larskotthoff** [comment]
I'll get to it "immediately".

**Comment by berndbischl** [comment]
i sincerely hope so
