### ISSUE TITLE
plot* function should all be callable without doing gen*Data first

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#577]
this is simply convenience for the users and should not be hard to do

**Comment by larskotthoff** [comment]
You mean have a wrapper that calls both?

**Comment by zmjones** [comment]
That would be easy to do. Naming scheme though?

**Comment by berndbischl** [comment]
Why not keep the names? make the plotting methods S3. Either the now existing data objects goes in, or the original object the genData methods is now called on?

**Comment by zmjones** [comment]
ok so i'd have a plot method for the object from the gen function and another for a wrapped model object which then calls the gen function?

**Comment by berndbischl** [comment]
sure, because in many cases you want to be lazy, especially in interactive work and save that line of code.

maybe try to do this for 1-2 methods and then we can review?

**Comment by pfistfl** [comment]
Anything new in regards to this @zmjones ? 
I will / will not do this for the critDifferencesPlot im currently reworking.

**Comment by zmjones** [comment]
No I haven't done much on this yet. Been working on other stuff.
