### ISSUE TITLE
Implementation of Rsquared/adjusted Rsquared as an performance measure

### ISSUE THREAD

**Issue by competulix** [mlr-org/mlr#579]
It would be really cool to see Rsquared/adjusted Rsquared implemented as a possible choice for regression tasks.

**Comment by larskotthoff** [comment]
I'm guessing you want the [coefficient of determination](https://en.wikipedia.org/wiki/Coefficient_of_determination) as a performance measure?

**Comment by competulix** [comment]
Yes, precisely. :-)

**Comment by berndbischl** [comment]
@competulix is perfectly right, this is missing for far too long now.

**Comment by berndbischl** [comment]
@florianfendt Would you do this and add this to your todo list?

**Comment by florianfendt** [comment]
I implemented those measures in #659, which has been merged, therefore closing here.
