### ISSUE TITLE
Question about RLearnerMultilabel

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#586]
In https://github.com/mlr-org/mlr/blob/master/R/RLearner.R the return and aliases fields say that there exists a class `RLearnerMultilabel`. But `makeRLearnerMultilabel` returns an object of class `RLearnerClassif` which can also make sense, I guess.
```
class(makeLearner("multilabel.rFerns"))
#> [1] "multilabel.rFerns" "RLearnerClassif"   "RLearner"         
#> [4] "Learner"
```

So does class `RLearnerMultilabel` exist?

**Comment by berndbischl** [comment]
no, it does not, but it should exist. I need to look at this.

**Comment by berndbischl** [comment]
1) the base class uses the wrong class in classstring
2) rferns needs to call the correct constructor

then we are done
