### ISSUE TITLE
Multilabel-classification: sparse labels 

### ISSUE THREAD

**Issue by QuayAu** [mlr-org/mlr#587]
I have some data sets, where labels are very sparse (e.g. only one observation has that label). 
Using the binary relevance method, i get following error during resampling:

![medicaltask](https://cloud.githubusercontent.com/assets/15329438/11495586/aea09896-980c-11e5-8aab-ec05766a0845.png)

It would be nice, if the binary classifier would always predict "FALSE" for very sparse labels.

**Comment by berndbischl** [comment]
we need to discuss how to handle this. another option for now is to remove these cols from the data, as you already "know" what would happen to them during prediction. 

but we need a consistent way to handle this technically. either an option in the learner or a wrapper.

**Comment by berndbischl** [comment]
we now have makeConstantClassWrapper which should be able to handle this.
