### ISSUE TITLE
Fix Bug in critDiff plot

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#589]
Hi, why was that PR #555 closed and deleted?

I thought we would simply move this to a new PR because of rebasing problems?

Please answer soon, I would like to have this fixed in the new version!

**Comment by berndbischl** [comment]
@pfistfl

**Comment by pfistfl** [comment]
I deleted the branch, as you wanted a New clean branch with a Single
commit. This Seems to have deleted the PR. Gonna open New PR tonight After
work
Am 01.12.2015 3:41 nachm. schrieb "Bernd Bischl" <notifications@github.com>:

**Comment by pfistfl** [comment]
The plot does currently not use the pretty.names arg. 
Should I introduce this?

**Comment by berndbischl** [comment]
new PR: pls do so now, i got confused because you didnt reopen the new one at once. try to do these 2 things together, or at least write a msg in the the closed PR.

pretty.args: hmm, is what you write done for other plots already? if not leave it out here

**Comment by berndbischl** [comment]
and  dont touch other stuff except critdiff for now, i still need to finish the refactoring of the other plots
