### ISSUE TITLE
plots / pretty.names

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#592]
define here what this should mean. and add it where we need it.

**Comment by pfistfl** [comment]
Talked about it with Bernd yesterday,

```pretty.names``` for learners should mean we use short.name instead.

**Comment by larskotthoff** [comment]
Can this be closed now or does the issue entail other things?

**Comment by berndbischl** [comment]
i guess we are done here. we can open a separate issue if we need this more

**Comment by berndbischl** [comment]
was fixed in PR #822
