### ISSUE TITLE
review critdiff code with florian

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#593]
1) Please (!) stick to the style guide. I see camel case in some vars. And the class does start with a lower case letter.

2) The lines around 70ff need some comments. Otherwise one does not undertstand what happens

**Comment by berndbischl** [comment]
@pfistfl 
I guess it is best if we talk 10 min

**Comment by berndbischl** [comment]
Florian said:

The plot does currently not use the pretty.names arg. 
Should I introduce this?
Edit: In this case it would mean that I remove the "classif." / "regr". prefix for learner names.

**Comment by berndbischl** [comment]
the unit tests stochastically fails, sometimes. this was observed on jenkins.
reason: sometimes the friedman test rejects, sometimes not, for the constructed example.
we need to fix the unit test and make it better.

**Comment by pfistfl** [comment]
Will do. Thought it was constant via ``options(mlr.debug.seed = 123L)``.

I'll update my branch and adjust unit tests, as well as formulation.
Maybe we can talk about it then and I'll create a PR ?

2015-12-14 12:24 GMT+01:00 Bernd Bischl <notifications@github.com>:

**Comment by berndbischl** [comment]
> Thought it was constant via ``options(mlr.debug.seed = 123L)``.

That seed is only used in the learners before train and test steps, not for the rest of the unit tests.

**Comment by pfistfl** [comment]
Quick status update: 
1) done (I hope)
2) done (I hope not too much)

> the unit tests stochastically fails, sometimes. this was observed on jenkins
3)I could not reproduce this for critdifferences.Does it fail at unit tests for hypothesis tests?

Additionally:
4) Should the plotCritDifferences(obj = NULL) generate the data itself as you said in #584 ?
5) What about pretty.names arg ?

**Comment by berndbischl** [comment]
Lars said in the old PR for ggplot2:

Apparently ggplot doesn't support vjust in annotation anymore. I've removed this from generateCritDifferences to make the build pass again, but could you please check whether everything is still being shown correctly (and what to use instead of vjust)

**Comment by pfistfl** [comment]
Update regarding ```vjust```. 

As far as I understood, vjust was just a problem when used in ```annotate()```?
Then it is no problem, because it was only used as an optional input.

I completely removed it now for all ```annotate()```'s.

**Comment by pfistfl** [comment]
In regards to directly plotting from BenchmarkResults as suggested in #577, I will have to look through some of @zmjones 's code to get the hang I guess.

**Comment by pfistfl** [comment]
short Update.

I'm mostly done with my stuff. Problem for now is not getting R CMD check to work.
I'll create a PR when I'm done.

I created a new convenience function ```getBMRLearnerShortNames(bmr)``` For the pretty.names arg if that is ok.

**Comment by berndbischl** [comment]
Try to update the branch tonight please or at least tomorrow. 
If you cannot get R CMD ceck to work, post your insights here and I will try to fix

**Comment by pfistfl** [comment]
#643 should fix this.
Could you iterate again?

**Comment by berndbischl** [comment]
handled in PR 
https://github.com/mlr-org/mlr/pull/695
