### ISSUE TITLE
plotBMRSummary

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#594]
I'm currently playing around with the new function for the tutorial and noticed some things:

1) This line in `plotBMRSummary`:

```
    p = p + geom_point(size = pointsize, position = position_jitter(height = jitter))
```

You also introduce jitter in horizontal direction here. (The default width = NULL leads to jitter
of "40% of the resolution of the data").

Moreover, this makes turning off the jitter unnecessarily difficult as simply setting
 `jitter = 0` is not sufficient.

Maybe set `width = 0`?

2) If `trafo = "rank"` in `plotBMRSummary` shouldn't the x-axis label change?
Maybe something like "rank of meas.aggr"?

3) Is there any conceptual difference between `plotBMRSummary` with `trafo = "rank"`
and `plotBMRRanksAsBarChart`?

**Comment by berndbischl** [comment]
PR = #596 

1 + 2: done

3) no big diff. it just looks a bit different and i thought i would not hurt.

do you want to review the pr then close?

**Comment by schiffner** [comment]
Cool, thanks. Did review.
