### ISSUE TITLE
generateROCRCurves sometimes breaks

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#600]
I've traced the bug down to this line:
https://github.com/mlr-org/mlr/blob/master/R/generateROCRCurves.R#L116

If alpha is `c(Inf, [numeric])`, this obviously fails because `mean(numeric(0))` returns `NaN`. Unfortunately, I do not have a reproducible example.

**Comment by berndbischl** [comment]
Why no example?

**Comment by zmjones** [comment]
Is there a reason you can't use `generateThreshVsPerfData` and `plotROCCurves`?

**Comment by mllg** [comment]
> Why no example?

I cannot boil it down to something simple and deterministic.

> Is there a reason you can't use generateThreshVsPerfData and plotROCCurves?

I wanted to use it as an exercise for the students, and the tutorial does not cover that. Is ROCR deprecated?

**Comment by zmjones** [comment]
Not yet but I would like it to be eventually.

The procedure is very simple. Call `generateThreshVsPerfData` with the appropriate measures (e.g., tpr and fpr for a normal ROC curve), and then plug the returned objection into `plotROCCurves`.

**Comment by berndbischl** [comment]
> I cannot boil it down to something simple and deterministic.

Well, upload the complex code with a seed? otherwise we have 0 chance?

**Comment by berndbischl** [comment]
Not saying you not TRY to boil it down, but if is a student example it cannot be 100 pages of code?

**Comment by mllg** [comment]
> Well, upload the complex code with a seed? otherwise we have 0 chance?

I've narrowed the error down to a single line in my first post. I would fix it myself if I would understand the intention there. Whoever wants to resolve this can PM me, I can provide data and a short script. Can't publish it here because (a) the students might find it and (b) I probably do not have the rights to redistribute the data set.

OTOH, this might not be worth the effort if `plotROCRCurves` will be superseeded by `plotROCCurves` soon?

**Comment by berndbischl** [comment]
Send the data / script to me and Zach by mail. I guess we should keep this as bug free as possible.

**Comment by zmjones** [comment]
Agreed.

**Comment by berndbischl** [comment]
@mllg : We already asked for the script, please mail it.

**Comment by berndbischl** [comment]
@mllg 
you didnt reply to variuos requests for reproducible example, and plotROCR does not exist anymore.
will close.
