### ISSUE TITLE
BaggingWrapper parallelization

### ISSUE THREAD

**Issue by zmjones** [mlr-org/mlr#603]
is there a reason this has not been implemented? it could be a level no?

**Comment by berndbischl** [comment]
yes, you can do a PR

**Comment by berndbischl** [comment]
PS: If you want to do this there are a couple other wrappers where this might make sense, so we could discuss this here first and compile a list to define a wellnamed new "level"

**Comment by zmjones** [comment]
yes that sounds like a good idea

**Comment by berndbischl** [comment]
These guys basically fit simple homog. "ensembles"

R/OverBaggingWrapper.R
R/MulticlassWrapper.R
R/BaggingWrapper.R
R/CostSensRegrWrapper.R
R/MultilabelBinaryRelevanceWrapper.R
R/CostSensWeightedPairsWrapper.R

**Comment by zmjones** [comment]
do you think that this should just be restricted to training? i was just going to name the new level "ensembles"

**Comment by berndbischl** [comment]
not sure. is there a downside if we enable this for prediction?

**Comment by berndbischl** [comment]
stacking is probably also in this group

**Comment by zmjones** [comment]
no probably not. i will do that too then.

**Comment by zmjones** [comment]
is one pr and one commit per file ok? e.g., one commit for bagging, one for overbagging, etc. or should i squash them all together?

**Comment by berndbischl** [comment]
i can live with both options, but squashing them together in the end is preferred.

actually, while we are still reviewing the PR you can have as many commits as you want.
we can squash all stuff at the end with git rebase -i.

**Comment by zmjones** [comment]
in resample, there is `exportMlrOptions(level = "mlr.resample")`. That is setting the level to resample w/o user input right? since that is something that is by default parallelized if a parallel backend is registered? 

i can't think of a downside to doing this with this new level, but thought i would ask

**Comment by zmjones** [comment]
It occurs to me that in some cases at least parallelizing predictions may be annoying. My impression is that for almost all learners training takes vastly longer than prediction. if, for example, i have registered this new "mlr.ensemble" level, and I then I call any method which has a level which is by default registered, how would parallelMap handle that?

**Comment by PhilippPro** [comment]
I just was on the way on implementing parallelization for the MultilabelBinaryRelevanceWrapper, when I discovered this issue. (y)

I think parallelization can also be done for some of the new multilabel methods like Classifier Chains, Dependent Binary Relevance and Stacking. But maybe better wait for the approval of Quays PRs before implementing this.

**Comment by zmjones** [comment]
ah cool. yea i guess i need to rebase that PR. parallelize all the things!

**Comment by ja-thomas** [comment]
fixed in a49bf1f
