### ISSUE TITLE
params which trigger crossvals not tunable

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#605]
Is that a conscious decision, that i.e. `cross` for *.svm and `xval` for *.rpart are not set to `tunable = FALSE` ?
Both trigger internal cross validations which I gues should not be counted as a tunable param?

**Comment by berndbischl** [comment]
Of course, this is a feature and not a bug. 

Think about this, this option does not lead to a differently fitted model in the end.

**Comment by jakob-r** [comment]
So you say it should be `tunable = FALSE`. But this is not the case at the moment. So it should be changed?

**Comment by berndbischl** [comment]
I have to apologize. I completely MISREAD your first post. I misread the "not" in both sentences, I dont no why?

So, to be clear:
Params that simply control the internal crossval of models should be set to tunable = FALSE.

Can you pls change this and do a quick PR?

**Comment by berndbischl** [comment]
No response, as this is a mini fix I will do this now.
