### ISSUE TITLE
ModelMulitplexer Predict Type: Probability 

### ISSUE THREAD

**Issue by competulix** [mlr-org/mlr#609]
We ran into an issue with Multiplexer models in MLR. An error message is produced when we set the predict.type = "prob". 

```{r}
base.learners = list(
  makeLearner("classif.ksvm", predict.type = "prob"),
  makeLearner("classif.randomForest", predict.type = "prob")
)
learner = makeModelMultiplexer(base.learners)
rdesc = makeResampleDesc("Holdout")
ps = makeModelMultiplexerParamSet(learner, makeDiscreteParam("C", 2^(-1)),
                                  makeDiscreteParam("mtry", c(2,3))
)
ctrl = makeTuneControlGrid()
lrn2 = makeTuneWrapper(learner, resampling = rdesc, par.set = ps, control = ctrl)
r = resample(lrn2, iris.task, resampling = rdesc, measures = mmce)

[Resample] holdout iter: 1
[Tune] Started tuning learner ModelMultiplexer for parameter set:
                              Type len Def                            Constr Req Tunable Trafo
selected.learner          discrete   -   - classif.ksvm,classif.randomForest   -    TRUE     -
classif.ksvm.C            discrete   -   -                               0.5   Y    TRUE     -
classif.randomForest.mtry discrete   -   -                               2,3   Y    TRUE     -
With control class: TuneControlGrid
Imputation value: 1
[Tune-x] 1: selected.learner=classif.ksvm; C=0.5
Error in checkPredictLearnerOutput(.learner, .model, p) : 
  predictLearner for ModelMultiplexer has returned a class matrix instead of a factor!
```
Eventually we want to use it in order to tune the threshold in ctrl = makeTuneControlGrid(tune.threshold = TRUE)
Here is a code example showing the error message:

```{r}
base.learners = list(
  makeLearner("classif.ksvm", predict.type = "prob"),
  makeLearner("classif.randomForest", predict.type = "prob")
)
learner = makeModelMultiplexer(base.learners)
rdesc = makeResampleDesc("Holdout")
ps = makeModelMultiplexerParamSet(learner, makeDiscreteParam("C", 2^(-1)),
                                  makeDiscreteParam("mtry", c(2,3))
)
ctrl = makeTuneControlGrid(tune.threshold = TRUE)
lrn2 = makeTuneWrapper(learner, resampling = rdesc, par.set = ps, control = ctrl)

Error in checkTunerParset(learner, par.set, measures, control) : 
  Using 'tune.threshold' requires a classif learner with predict.type = 'prob'!

```
Your help is appreciated.

**Comment by berndbischl** [comment]
Actually, for the first chunk of code one can already see the problem when one prints the ModelMultiplexer learner. Its predict type is set to "response" and not correctly inherited from the base learners.

**Comment by berndbischl** [comment]
2nd observation, again for the first code chunk above:
I changed the measure to multiclass.auc in the TuneWrapper and resample calls, so predict.type = "prob" is really required to make it work. Then I removed the predict.type = "prob" from the base.learners. And called this on the ModelMultiplexer:
learner = setPredictType(learner, "prob")

This works. So this is for now a workaround. Although your report is of course valid and appreciated.

**Comment by berndbischl** [comment]
I have added now
- a check in BaseEnsemble, that the predict.type of all base.learners must be the same
- code in modelmultiplexer, to inherit the predict.type of the base learners
- unit tests that reflect our examples

I will do a PR now, I guess I am done
