### ISSUE TITLE
xgboost: feval-argument

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#613]
In xgboost the feval-argument is not available in mlr. Is there a specific reason? Wanted to optimize a different evaluation function (RMSPE), but it was not possible with xgboost in mlr.

**Comment by berndbischl** [comment]
it was probably just forgotten.

1) would you like to do a pull request?
2) Note that you can always use configureMlr to access params which we forgot like here.

**Comment by PhilippPro** [comment]
1) Ok.
2) I know, just wanted to comment here. ;)

**Comment by berndbischl** [comment]
Thx, was also trying to be complete :)

**Comment by berndbischl** [comment]
done, merged on the console
