### ISSUE TITLE
ROC-Curves for Multilabel Prediction

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#614]
Currently not implemented, I would like to do that. 

I need a Wrapper for generateROCRCurvesData, something like generateMultilabelROCRCurvesData, which for each label takes the relevant values/predictions out of the Multilabel Prediction and applies the generateROCRCurvesData function on this data. 

Furthermore a function called plotMultilabelROCRMultilabelCurves to plot the data of the Wrapper (or implement it in plotROCRCurves, but I think this is not good).

Any comments?

**Comment by zmjones** [comment]
Please do this with `generateThreshVsPerfData` and `plotROCCurves` as I would like to deprecate the functions that rely on `ROCR`.

**Comment by berndbischl** [comment]
Another "please" from my side.
Try to look at a couple of other mlr "plot" functions and try to stay consistent / similar to their API.

Otherwise just ask here or in a PR where we review your stuff.
