### ISSUE TITLE
Wrong class level names in MulticlassWrapper

### ISSUE THREAD

**Issue by rcprati** [mlr-org/mlr#620]
Hi,

I think that the buildCMatrix function in MulticlassWrapper.R has a bug in the line 111: 

levs = getTaskFactorLevels(.task)[[1]]

It assumes either that the class is the first feature or that only the class is a factor. If a dataset has more than one discrete feature, it crashes. 

I replaced by:

levs = .task$task.desc$class.levels

**Comment by larskotthoff** [comment]
Hmm, looks like it should be

    levs = getTaskDescription(.task)$class.levels

Does this cause a problem in practice? Can you post an example that triggers this issue please?

**Comment by rcprati** [comment]
Yes, if a data set have discrete features other than the class, it will not work, raising the error "Rownames of code matrix must be class levels!"

Here is my code (I am using the DNA dataset from mlbench package):

library(mlr)
library(mlbench)
data(DNA)

classif.task = makeClassifTask(id="DNA",data=DNA,target="Class")

base.lrn = makeLearner("classif.rpart")

w = makeMulticlassWrapper(base.lrn, mcw.method = "onevsrest")

rdesc = makeResampleDesc("CV", iters = 2L)

benchmark(w,classif.task,rdesc)

**Comment by larskotthoff** [comment]
Thanks. I've fixed this and added a test along the lines of your example in  #621.

**Comment by rcprati** [comment]
Thanks for the fix and for excellent package!

**Comment by larskotthoff** [comment]
Thanks, but let's leave this open until the pull request has been reviewed and merged. This will automatically close the issue.
