### ISSUE TITLE
ggplot2 2.0 problem

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#623]
Hi,

travis does not run at all.
We have problems due to ggplot2.

We have to fix this ASAP otherwise we cannot merge or fix anything,

Errors are also pasted here.

One can easily reproduce locally, but I had to download the ggplot2 2.0 targz manually from cran as it was not on my mirror yes. 

I have pasted some logs also here #622

**Comment by berndbischl** [comment]
@larskotthoff @zmjones

**Comment by larskotthoff** [comment]
See #538.

**Comment by berndbischl** [comment]
Does this mean we simply have to merge the other PR? Because if that is true, pls check and do that. 
Otherwise we inherit chaos.

**Comment by larskotthoff** [comment]
I have started Travis again on the PR to check.

**Comment by berndbischl** [comment]
Hi, Lars did a lot of work and nearly fixed every thing. But:

a) Lars said in the old PR: 
Apparently ggplot doesn't support vjust in annotation anymore. I've removed this from generateCritDifferences to make the build pass again, but could you please check whether everything is still being shown correctly (and what to use instead of vjust)?

This we will take care of in issue #593 with @pfistfl 

b) We currently dont run on rdevel, as can be seen on Jenkins.
@larskotthoff @zmjones 
This is REALLY important, as I othwerwise cannot submit to CRAN. I am very unsure that I can fix this myself, and we have resolved so many bugs in 2.8 that I would like to push to CRAN soon.

**Comment by larskotthoff** [comment]
They've changed the colour definitions again. This is a huge pain and I've commented all the tests that rely on it for now -- there's no way to make this work for R and R-devel without awkward additional checks.

Let's think about how to make this more robust and maybe reenable later.

**Comment by larskotthoff** [comment]
This should be fixed now -- can't really test as the R-devel build fails because ParamHelpers 1.7 isn't on CRAN yet.

**Comment by berndbischl** [comment]
First, i can live very well at the moment  without Tests for colours.

But can  we pls install PH from GH on jenkins?

**Comment by larskotthoff** [comment]
In a separate job? I don't want to do that by default because then it's easy to miss that you need the GH version of PH for everything to work.

**Comment by berndbischl** [comment]
How is it  possible to miss it? It is in the DESCRIPTION and R eben tells you.

**Comment by larskotthoff** [comment]
If we run tests *only* on installations with GH PH and never check whether it works with PH on CRAN, we may miss that it doesn't work with PH on CRAN.

**Comment by pfistfl** [comment]
Short question in regards to vjust / hjust.
Should I drop both from my code altogether? I removed it for the  `` annotation()```

Another (new?) thing that was added in ggplot2 is
```
#' @param nudge_x,nudge_y Horizontal and vertical adjustment to nudge labels by.
#'   Useful for offsetting text from points, particularly on discrete scales.
```

**Comment by larskotthoff** [comment]
If there's a better way of doing what you're doing with vjust/hjust at the moment, then please change. Otherwise I'm fine with keeping them where they are still supported.

**Comment by berndbischl** [comment]
Agreed with Lars.
