### ISSUE TITLE
tuning: Export a lightweight version of logFunTune

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#624]
When doing experiments with tuneParams() and fast learners / small datasets, the `gc()` calls made through `logFunTune` to report memory usage tend to make up >80% [1] of the runtime. Since I want to follow the optimization process but don't need the memory output, I ended up copying the logFunXX functions with the `gc()` calls removed. I can imagine this to be a common case, however, so I think giving an easier method for skipping memory reporting would be useful.

I propose
- exporting a lightweight version of `logFunTune` that does not report memory usage, or
- creating an `tune.report.memory` option by which the default log function behaviour can be changed

[1] According to `Rprof()`. Another call of `gc()` is implied by the `system.time()` call inside `evalOptimizationState()` (since it defaults to gcFist=TRUE). adding `gcFist=FALSE` here also improves runtime (seemingly with no downside besides inaccurate time reporting?)

**Comment by berndbischl** [comment]
Hi, first of all thanks a lot for dilligently looking into the details here.

We are all very busy now, so PRs would be extremely helpful. Starting a discussion FIRST and getting some feedback is absolutely correct and good.

1) Note that you can plugin your own tune.log.fun in TuneControl from the outside.

2) You are still right that we might change the default here. Do you want to add an option to TuneControl to disable the gc calls? We can then discuss the default.

**Comment by berndbischl** [comment]
We discussed on hangout:

An option to disable the gc call in TuneControl is good. Lets call it:
"log.fun.memreport "

I would vote for the default to be "FALSE" to speed up normal runs / tests etc. But this needs to be discussed in the PR with Lars and Michel.

For the system.time call in evalOptimizationState pls also set gcFirst = FALSE.

Can you also please check the FeatSelControl? We have to have this consistent, unfortunately.
