### ISSUE TITLE
PreprocWrapperCaret hyperparameters should reflect requirements / dependencies

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#626]
The relationship of hyperparameters of PreprocWrapperCaret are not reflected in its ParamSet. This includes:
- `pca` and `ica` are mutually exclusive (internally `ica` is preferred, warning is given)
- `knnImpute`, `bagImpute`, `medianImpute` are mutually exclusive (error thrown when more than one is given)
- if `range` is TRUE, none of `center`, `scale` or `BoxCox` may be TRUE (error thrown)
- if one of (`pca`, `ica`, `spatialSign`, `knnImpute`) is given and `range` is _not_ given, then both `scale` and `center` are implied (happens silently)

(see `caret:::pre_process_options` for reference)

**Comment by schiffner** [comment]
Thank you very much. Will take this into account when fixing #408.

**Comment by berndbischl** [comment]
@schiffner 
Please talk to me about this first, best on hangout or per mail, we might do a different approach here.
