### ISSUE TITLE
Deprecated filter methods

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#632]
Related to https://github.com/mlr-org/mlr-tutorial/issues/32

* `listFilterMethods` lists also deprecated filter methods.
* When trying to use `"univariate"`, the deprecated filter method, the warning message is a little messy. To me it seems that `.Deprecated` is not used correctly.

```
fv = generateFilterValuesData(iris.task, method = "univariate")
Warning message:
'function (...) 
{
    .Deprecated("Filter 'univariate' is deprecated, use 'univariate.model.score' instead.")
    .FilterRegister[["univariate.model.score"]]$fun(...)
}' is deprecated.
Use 'Filter 'univariate' is deprecated, use 'univariate.model.score' instead.' instead.
See help("Deprecated") 
```

**Comment by berndbischl** [comment]
Acually, as we might use listFilterMethods maybe also for arg checks, I guess it is really better if we just add (DEPRECATED) to the desc of the filter. Otherwise I am not sure if everything works, and adding a special case makes the code much uglier.

**Comment by berndbischl** [comment]
I have also fixed the deprecation warning text

**Comment by schiffner** [comment]
> Acually, as we might use listFilterMethods maybe also for arg checks, I guess it is really better if we just add (DEPRECATED) to the desc of the filter. Otherwise I am not sure if everything works, and adding a special case makes the code much uglier.

You are right. Thx for fixing this so quickly. PR looks good.

**Comment by berndbischl** [comment]
was  merged, closing
