### ISSUE TITLE
Ensemble of several learners

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#644]
Is there a possibility to make a combination of different learners in mlr?

For example in a regression task something like 0.6* randomForest + 0.2* svm + 0.2* lm ?

I could not find anything in the tutorial.

**Comment by larskotthoff** [comment]
There's nothing in `mlr` that allows you to combine predictions with explicit weights like this, but you can construct this quite easily yourself:

    bh.task.train = subsetTask(bh.task, 1:300)
    bh.task.test = subsetTask(bh.task, 301:506)

    model.rf = train(makeLearner("regr.randomForest"), bh.task.train)
    model.svm = train(makeLearner("regr.ksvm"), bh.task.train)
    model.lm = train(makeLearner("regr.lm"), bh.task.train)

    preds = 0.6 * getPredictionResponse(predict(model.rf, bh.task.test)) +
      0.2 * getPredictionResponse(predict(model.svm, bh.task.test)) +
     0.2 * getPredictionResponse(predict(model.lm, bh.task.test))

**Comment by berndbischl** [comment]
why do you explicitly want to set manual weights? have you looked into Stacking, which we provide?

**Comment by PhilippPro** [comment]
Ah ok, cool, thx, did not know, that this was available (did not find it in the tutorial).

**Comment by berndbischl** [comment]
@PhilippPro 

Can we close this then here? You could open up an issue in the tracker of the tutorial that we should explain stacking quickly.

**Comment by schiffner** [comment]
We already have this issue: https://github.com/mlr-org/mlr-tutorial/issues/11

But I haven't done it yet... :(

**Comment by berndbischl** [comment]
@PhilippPro 
Close here?

And please feel free to ask us about stacking or if you need other pointer to heterogenous ensemble combinations.

**Comment by PhilippPro** [comment]
yes.
