### ISSUE TITLE
Error in predict()

### ISSUE THREAD

**Issue by larry77** [mlr-org/mlr#646]
Dear All,
I must be misunderstanding something very basic about mlr.
Please have look at the code at the end of the post: essentially I use a randomForest with some simple tuning for a multiclass prediction exercise.
However, when I try to predict with the tuned learner, I get an error message

Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('classif.randomForest', 'RLearnerClassif', 'RLearner', 'Learner')"

What is my mistake?

########################################################
library(mlr)
## library(xgboost)
library(parallelMap)

n = nrow(iris)
train = iris[seq(1, n, by = 2), ]
test = iris[seq(2, n, by = 2), -5]

task = makeClassifTask(data = train, target = "Species")
lrn = makeLearner("classif.randomForest")

rdesc = makeResampleDesc("RepCV", folds =3, reps = 3, predict="both")

parallelStart("multicore", 10)
# Description of our parameter space we want to grid-search over
par.set = makeParamSet(
  makeIntegerParam("mtry",  lower = 1, upper = 20, trafo=NULL),
  makeIntegerParam("nodesize", lower = 1, upper = 15, trafo=NULL)## ,
  ## makeIntegerLearnerParam(id = "nthread", default = 10, lower = 1)
)

ctrl = makeTuneControlRandom(maxit = 30)

set.seed(123457)

res = tuneParams(lrn, task, rdesc, par.set = par.set, control = ctrl)

## update learner

lrn_up = setHyperPars(lrn, par.vals=res$x)

## now predict!
newdata.pred = predict(lrn_up, newdata = test)

**Comment by larskotthoff** [comment]
You need a model to predict, i.e. the result of having trained a learner on some data. You're giving it the learner itself. You need something like

    model = train(lrn_up, task)
    newdata.pred = predict(model, newdata = test)

See [the relevant part of the tutorial](https://mlr-org.github.io/mlr-tutorial/devel/html/train/index.html) for more information.
