### ISSUE TITLE
speedup removeConstantFeatures

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#652]
The `removeConstantFeatures` function is very slow for big data, this is because the `BBmisc::computeMode` function is very slow. I've written a `computeMode2` function that is faster:

``` r
computeMode2 = function (x, ties.method = "random", na.rm = TRUE) 
{
  assertAtomicVector(x)
  assertChoice(ties.method, c("first", "random", "last"))
  assertFlag(na.rm)
  tab = data.table::as.data.table(x)[, .N, by = list(x)]
  if(na.rm) tab = na.omit(tab)
  mod = tab$x[which.max(tab$N)]
  if (!is.factor(x)) 
    mode(mod) = mode(x)
  if (length(mod) > 1L) 
    switch(ties.method, first = mod[1L], random = sample(mod, 1L), last = mod[length(mod)])
  else mod
}
```

However, `computeMode` is still faster for factors with less then ~15000 entries. Here a short benchmark study:

``` r
library(BBmisc)
library(microbenchmark)
library(checkmate)
library(data.table)

bench = function(n, times = 25) {
  num = rnorm(n)
  fac = as.factor(round(num, digits = 2))
  bench = microbenchmark(computeMode2(num), computeMode(num), 
    computeMode2(fac), computeMode(fac), times = times) 
  return(invisible(bench))
}

n = ceiling(exp(seq(6, 12, length.out = 20)))
res = lapply(n, bench)
res2 = lapply(res, print, unit = "ms")
res3 = do.call("rbind", res2)
res3$nObs = rep(n, each = 4)
res3$featureClass = as.factor(gsub(".*\\(|\\)", "", res3$expr))
res3$fun = as.factor(gsub("[[:punct:]].*", "", res3$expr))

library(ggplot2)
p = ggplot(res3, aes(x = nObs, y = median))
p + geom_line(aes(colour = fun)) + 
  facet_wrap(~ featureClass, scales = "free_y") + 
  ylab("median-runtime in (ms)") 
```

Do we want to improve this in BBmisc (data.table dependency must be added) or just use `computeMode2` in mlr (we already depend on data.table)?

![rplot](https://cloud.githubusercontent.com/assets/4238748/12204685/fae31c6e-b635-11e5-99c4-8f38b68f3d8d.png)

**Comment by larskotthoff** [comment]
Should this be an issue in the [BBmisc repo](https://github.com/berndbischl/BBmisc)?

**Comment by berndbischl** [comment]
@giuseppec 
While I find this good what you are doing, this is kind of the "wrong" approach.

1) Adding the datatable dependency is really heavy for such a "little" function and the gain we get.

2) Why not directly coe the function in C?

**Comment by berndbischl** [comment]
I already have a version in C.
But we should move this to BBmisc

Also, @giuseppec your version does not work for me? I would like to compare to it. But I get:

```
> computeMode2(1:3)
Error in `[.data.frame`(x, i, j) : object '.N' not found
```

**Comment by berndbischl** [comment]
@giuseppec 
Disregard that, it is this non-standard evaluation crap i guess. I had the function computeMode2 already copied to BBmisc/R, then it does not work. 
(Note to myself OR Giuseppe: I need to get better at datatable)

I have now a version, which on integers > 0 is a lot faster, even than the datatable version. 
I have an (easy) way to make it run faster on everything, by converting stuff to a factor, but then I lose with a factor of 3 vs. datatable, on a vector with 100K entries.

Of course I am not going to admit defeat here, so I guess I now need to see how R in C converts to a factor....
