### ISSUE TITLE
Incorrect plots by `plotThreshVsPerf` and `plotROCRCurves`

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#654]
`plotThreshVsPerf` and `plotROCRCurves` show incorrect plots for `ResampleResult`s (and thus also for `list`s of `ResampleResult`s and `BenchmarkResult`s) if the curves are not aggregated. Instead of separate curves for the resampling iterations one very wiggly line is drawn.

```
library(mlr)

lrn = makeLearner("classif.lda", predict.type = "prob")
r = resample(lrn, sonar.task, cv3, measures = list(fpr, tpr, mmce))

d = generateThreshVsPerfData(r, measures = list(fpr, tpr, mmce), aggregate = FALSE)
plotThreshVsPerf(d) # not ok
plotROCCurves(d) # ok

d = generateROCRCurvesData(r, avg = "none")
plotROCRCurves(d) # not ok
```

**Comment by zmjones** [comment]
I will look into this on Monday.

**Comment by schiffner** [comment]
Thanks.

**Comment by zmjones** [comment]
Sorry this took so long. I've now fixed the bug in the plot via `plotThreshVsPerf`. It was a somewhat subtle problem with the generation function and also a more obvious problem with the plotting functions.

Maybe we should now remove the dependency on `ROCR` though. Thoughts? I think it is weird that we rely on external measures via `ROCR` and then have our own set in mlr.

**Comment by larskotthoff** [comment]
If we can remove the dependency easily, I'd be all for it.

**Comment by zmjones** [comment]
As far as I am aware nothing depends on `ROCR` other than `generateROCRCurves` and `plotROCRCurves`. I will check all of this and push the fix and the dependency removal in separate commits. Maybe separate PRs as well?

**Comment by larskotthoff** [comment]
Thanks, yes, separate PRs would be good if not too much hassle.

**Comment by zmjones** [comment]
What are your thoughts on actually importing ggvis and shiny. Both are listed as imports in the description but are not actually loaded when mlr is attached. ggvis has one namespace conflict with another function "resolution" and so I was going to use `importFrom` and just import what is currently being used.

**Comment by larskotthoff** [comment]
The latter sounds preferable (i.e. we only pull in what's necessary). Is that list still manageable or are we using so much stuff that it would become ridiculously long?

**Comment by zmjones** [comment]
no it is fine i think

**Comment by larskotthoff** [comment]
Ok cool then let's go for that.

**Comment by schiffner** [comment]
I'm sorry I didn't have time to review earlier.

I just installed mlr (with the merged PRs), tried the above example and found that it doesn't work.
Do I miss something?

```
library(mlr)
 
lrn = makeLearner("classif.lda", predict.type = "prob")
r = resample(lrn, sonar.task, cv3, measures = list(fpr, tpr, mmce))

d = generateThreshVsPerfData(r, measures = list(fpr, tpr, mmce), aggregate = FALSE)
plotThreshVsPerf(d)

Error in eval(expr, envir, enclos) : object 'int' not found
traceback()
10: eval(expr, envir, enclos)
9: FUN(X[[i]], ...)
8: lapply(aesthetics, eval, envir = data, enclos = plot$plot_env)
7: f(..., self = self)
6: l$compute_aesthetics(d, plot)
5: f(l = layers[[i]], d = data[[i]])
4: by_layer(function(l, d) l$compute_aesthetics(d, plot))
3: ggplot_build(x)
2: print.ggplot(x)
1: function (x, ...) 
   UseMethod("print")(x)
```

**Comment by larskotthoff** [comment]
Ah, this should be "iter" instead "int". I'll fix this and add a unit test.

**Comment by schiffner** [comment]
Thx.
I just also noted that the `learner` column of `$data` contains the string `"prediction"` instead of the learner name. It doesn't really hurt, but I don't think that this is intended.

```
str(d$data)
'data.frame':	300 obs. of  6 variables:
 $ learner  : Factor w/ 1 level "prediction": 1 1 1 1 1 1 1 1 1 1 ...
 $ fpr      : num  1 1 1 0.611 0.654 ...
 $ tpr      : num  1 1 1 1 0.86 ...
 $ mmce     : num  0.514 0.377 0.507 0.314 0.333 ...
 $ iter     : num  1 2 3 1 2 3 1 2 3 1 ...
 $ threshold: num  0 0 0 0.0101 0.0101 ...
```

**Comment by larskotthoff** [comment]
Ok, I'll have a look.

@zmjones Turns out that the plots aren't rendered with the ggsave(...) commented out. So any errors don't actually show up. I've commented them back in for this file in the PR.

**Comment by zmjones** [comment]
@larskotthoff Saving the plots doesn't make a difference if we aren't actually testing the svg though. You removed that for the new version of ggplot2 no? The plots are already being rendered.

@schiffner The only scenario I can envision this being a problem is when someone passes an unnamed list of resample predictions. This should only occur when the input is a single resample prediction, where we aren't plotting the name at all.

**Comment by larskotthoff** [comment]
@zmjones I've added the test case without aggregation that triggers the bug Julia found and it ran fine. Only when I commented ggsave back in did the test fail.

**Comment by zmjones** [comment]
hmmm that is odd. no idea why that would occur.

**Comment by larskotthoff** [comment]
Well the plot object is lazily constructed and evaluated. If you don't reference it explicitly, nothing happens because the tests run "headless".

On the "prediction" in the learner column, as far as I can see the information on what learner was run isn't available where this is constructed (in `generateThreshVsPerfData.Prediction`). Did I miss something and there's an easy way to get this information @zmjones?

**Comment by zmjones** [comment]
Correct, because ResamplePrediction doesn't have a field for this. Shouldn't it though?

**Comment by schiffner** [comment]
The `ResamplePrediction` has a `learner.id`slot, but a`Prediction` has no info on the learner.

**Comment by zmjones** [comment]
Ah yea that is what I meant.

**Comment by larskotthoff** [comment]
Can we pass that information along without it becoming too ugly? Otherwise the learner column is a bit pointless.

**Comment by zmjones** [comment]
Yea I think that was already done in a similar fashion with `task.id`. We just need to add that to the method signature, document it, and then have it be `NULL` in all cases but this one.

**Comment by schiffner** [comment]
If it's easier maybe we could just remove the learner column in case of only one learner.

**Comment by berndbischl** [comment]
Have we reached a conclusion here? I am can check the API change and comment, but can somebody please summarize precisely the concrete proposal?

**Comment by schiffner** [comment]
**Problem:**

In case of a single learner and if the `obj` arg of `generateThreshVsPerfData` is a `ResamplePrediction` or a `Prediction` the `learner` column in the `data` slot of the returned `ThreshVsPerfData` object shows the string `"prediction"` and not the learner name.

**Possible solution:**

In case of a `ResamplePrediction` the solution is simple, because it contains the `learner.id`.

The `Prediction` object has no info on the learner name, so the question is how to supply it.

Zach's proposal (I hope I understood correctly): Introduce a `learner.id` arg to `generateThreshVsPerfData` that defaults to `NULL`. Use this arg to pass the missing info on the learner name if `obj` is a `Prediction` object, otherwise ignore it.

**Comment by zmjones** [comment]
Yes I like @schiffner's solution better. I started to do it but didn't finish even though it is a short task. I just got to the office now and will have it done shortly.

**Comment by berndbischl** [comment]
OK, I guess you got this sorted then :)
Ask if you need further feedback from me

**Comment by zmjones** [comment]
Will do!

**Comment by berndbischl** [comment]
ok thx @zmjones for doing this and thx to @larskotthoff for the other fix.

I guess there was no chance to add a unit test for the real issue right? as one basically has to look at the plot to see it?

**Comment by zmjones** [comment]
yes that is correct. our svg testing could have caught this but it has been disabled post-ggplot2 update. i can look into getting it working again though.

**Comment by berndbischl** [comment]
Maybe open up an issue for that? I guess it is helpful right?

**Comment by zmjones** [comment]
Yea I think so. I will do that.
