### ISSUE TITLE
xgboost classification stops with the below error for CV = 4

### ISSUE THREAD

**Issue by myloginid** [mlr-org/mlr#672]
Hi,

Part of the code is as below. The below error is not documented in the code. Not sure where the problem is. Any help is helpful on this.

Thanks..

> res = tuneParams(lrn, task = trainTask, resampling = rdesc, par.set = ps, control = ctrl)
[Tune] Started tuning learner classif.xgboost.preproc for parameter set:
                    Type len Def     Constr Req Tunable Trafo
eta              numeric   -   - 0.1 to 0.3   -    TRUE     -
colsample_bytree numeric   -   -     1 to 2   -    TRUE     Y
subsample        numeric   -   -     1 to 2   -    TRUE     Y
With control class: TuneControlRandom
Imputation value: 1
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 4; elements = 10.
Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) : 
  Errors occurred in 10 slave jobs, displaying at most 10 of them:

00001: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

00002: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

00003: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

00004: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

00005: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

00006: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

00007: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

00008: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

00009: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

00010: Error in data.frame(id = c(1L, 2L, 3L, 6L, 17L, 18L, 20L, 22L, 24L, 25L,  : 
  arguments imply differing number of rows: 14845, 1855

**Comment by larskotthoff** [comment]
Thanks for the report. Could you give us some more information? What does your data look like and where does the error come from? Could you try running sequentially and when the error occurs run `traceback()` please? It would be ideal if you could provide a complete example that allows us to reproduce the problem so we can investigate.

**Comment by myloginid** [comment]
Hey... Unfortunately I overwrote the code that was giving the error. The background is using xgboost for training the Kaggle Prudential Data Set gave me this error. I understand that without the code and the traceback it actually impossible to debug this. I will make sure I dont overwrite the code subsequently. Closing the bug for now.

**Comment by berndbischl** [comment]
Thanks for the feedback!
