### ISSUE TITLE
 GBM - Incorrect number of dimensions

### ISSUE THREAD

**Issue by myloginid** [mlr-org/mlr#676]
Hi.. I got an Error with GBM as "incorrect number of dimensions". I didnt get anything the mlr code base for this and it dosent look like a GBM error. Can you have a look pls...

	trainTask = makeClassifTask(data = train, target = "Response")
	trainTask = createDummyFeatures(trainTask)
	lrn = makeLearner("classif.gbm")
	lrn$par.vals = list ( verbose = 1, distribution = "gaussian"	)
	parallelStartSocket(socs)
	ps = makeParamSet(
		makeIntegerParam(id = "n.trees", lower = 100 , upper= 500),
		makeDiscreteParam(id = "shrinkage", values = c ( 0.001, 0.01 ) )
	)
	rdesc = makeResampleDesc("CV", iters = 2)
	ctrl =  makeTuneControlRandom(maxit = 3)
	res = tuneParams(lrn, task = trainTask, resampling = rdesc, par.set = ps, control = ctrl)

Starting parallelization in mode=socket with cpus=2.
[Tune] Started tuning learner classif.gbm.preproc for parameter set:
              Type len Def     Constr Req Tunable Trafo
n.trees    integer   -   - 100 to 500   -    TRUE     -
shrinkage discrete   -   - 0.001,0.01   -    TRUE     -
With control class: TuneControlRandom
Imputation value: 1
Exporting objects to slaves for mode socket: .mlr.slave.options
Mapping in parallel: mode = socket; cpus = 2; elements = 3.
traceback()
Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) : 
  Errors occurred in 3 slave jobs, displaying at most 10 of them:
 
00001: Error in p[, , 1L] : incorrect number of dimensions
 
00002: Error in p[, , 1L] : incorrect number of dimensions
 
00003: Error in p[, , 1L] : incorrect number of dimensions
 
> traceback()
14: stop(obj)
13: stopf("Errors occurred in %i slave jobs, displaying at most 10 of them:\n\n%s\n%s", 
        n, collapse(msgs, sep = "\n"), extra.msg)
12: stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character))
11: checkResultsAndStopWithErrorsMessages(res)
10: parallelMap(evalOptimizationState, dobs, states, level = level, 
        more.args = list(learner = learner, task = task, resampling = resampling, 
            measures = measures, par.set = par.set, bits.to.features = bits.to.features, 
            control = control, opt.path = opt.path, show.info = show.info, 
            remove.nas = remove.nas))
9: evalOptimizationStates(learner, task, resampling, measures, par.set, 
       NULL, control, opt.path, show.info, states, dobs, eols, remove.nas, 
       "mlr.tuneParams")
8: evalOptimizationStatesTune(learner, task, resampling, measures, 
       par.set, control, opt.path, show.info, vals, dobs = seq_along(vals), 
       eols = NA_integer_, remove.nas = TRUE)
7: sel.func(learner, task, resampling, measures, par.set, control, 
       opt.path, show.info)
6: tuneParams(lrn, task = trainTask, resampling = rdesc, par.set = ps, 
       control = ctrl) at mlr_v66.r#121
5: mlr.gbm(train, train) at mlr_v66.r#170
4: eval(expr, envir, enclos)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("/home/manishm/prudes/mlr_v66.r")

**Comment by larskotthoff** [comment]
Thanks for your report. Could you post a complete example (including data) please so we can investigate?

**Comment by berndbischl** [comment]
I already figured out what is wrong

**Comment by berndbischl** [comment]
1) Please, like Lars said, if you do such reports: Try to send in a fully reproducible example that we can run. Also, in the above case parallelization has nothing to do with the problem. So it would be good to leave it out of a minimal example.

2)  
lrn$par.vals = list ( verbose = 1, distribution = "gaussian"    )

This line actually contains 3 mistakes at once. 
a) You should not manually change the lrn structure. Use ?setHyperPars
b) verbose is of the wrong type. It is a logical. That already came up in the last issue....
c) A "gaussian" distribution actually is only for gbm regression. You are doing classification. This a what causes your error.

3) Point 2c) is actually a small problem in the gbm wrapper of mlr. We allowed to many distribution setting in the gbm classif learner. I will fix this now.

**Comment by berndbischl** [comment]
commit is here
https://github.com/mlr-org/mlr/commit/8d8438f70c3ae9b5e3065dcfcf3e81f5c0570c21

**Comment by myloginid** [comment]
Thanks for the info. I will use setHyperPars. For the basic parameters setting them directly in the par.vals is handy though.

**Comment by berndbischl** [comment]
Please really use the appropriate setter. For convenience, please note that you can directly pass them to ?makeLearner. Even in 2 different ways: a) in the "dots" ... and b) as a list via "par.vals" (the arg of makeLearner)
