### ISSUE TITLE
Problem with stacked wrapped learners

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#687]
When I slightly modify the first example of `makeStackedLearner` by wrapping one of the base learners with a filter wrapper, I get the following error:

```r
tsk = makeClassifTask(data = iris, target = "Species")
base = c("classif.rpart", "classif.lda", "classif.svm")
lrns = lapply(base, makeLearner)
lrns = lapply(lrns, setPredictType, "prob")
lrns[[1]] <- makeFilterWrapper(lrns[[1]], fw.abs = 2)  #the line I added
m = makeStackedLearner(base.learners = lrns, 
  predict.type = "prob", method = "hill.climb")
tmp = train(m, tsk)
res = predict(tmp, tsk)
```

```r
Error in setPredictType.Learner(learner, predict.type) : 
  Trying to predict probs, but stack does not support that!
```

Does anybody know what's the problem here?

**Comment by larskotthoff** [comment]
Thanks for the report. The problem was that the properties for an ensemble were constructed using `extractSubList` and not the proper getter. I've opened a PR to fix this.

**Comment by studerus** [comment]
Thanks for the fast bug fix! It works.

**Comment by berndbischl** [comment]
@larskotthoff fixed this. thx.
