### ISSUE TITLE
svg testing for plots

### ISSUE THREAD

**Issue by zmjones** [mlr-org/mlr#692]
after the ggplot2 update this was disabled as some of the default colors changed. i need to look at the saved plots, pick out the new colors, and re-enable the relevant tests.

**Comment by larskotthoff** [comment]
Ideally, we'd have a way of automatically getting the colours (or some other way of identifying the elements we're interested in). I've had a brief look at this, but didn't see anything obvious.

**Comment by zmjones** [comment]
yea that would be nice. did you have any ideas for doing that? 

i think we could extract from the default theme the relevant information, but then we'd have to turn that into whatever color coding system is used in svg, which i guess is html color codes. this should be possible?

**Comment by larskotthoff** [comment]
In principle that should work, and the colour definitions must be somewhere, I just didn't find them. Ideally, we'd be able to identify the elements by something else, but nothing came to mind there.
