### ISSUE TITLE
plotROCCurves

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#699]
Here is some nitpicky stuff I noticed about `plotROCCurves`:

* The docs for `obj` are wrong. It's an object of class `ThreshVsPerfData`.

* The docs for `measures` are misleading.
   It gives the impression that passing one single `Measure` is ok, although this makes no sense.
   It should say that you can only plot `measures` that were passed to `generateThreshVsPerfData`.

* The arg check that `measures` is a `list` of length 2, gives a confusing error message:

```
n = getTaskSize(sonar.task)
train.set = sample(n, size = round(2/3 * n))
test.set = setdiff(seq_len(n), train.set)

lrn1 = makeLearner("classif.lda", predict.type = "prob")
mod1 = train(lrn1, sonar.task, subset = train.set)
pred1 = predict(mod1, task = sonar.task, subset = test.set)

d = generateThreshVsPerfData(pred1, measures = list(mmce, fpr, tpr))
plotROCCurves(d, measures = mmce)
# Error in plotROCCurves(d, measures = mmce) : 
#   Assertion on 'measures' failed: Must have length 2, but has length 10
```

**Comment by schiffner** [comment]
For threshold values exactly 0 or 1 some measure values will be `NA` / `NaN`.
At the moment `plotROCCurves` can't cope with that.

```
n = getTaskSize(sonar.task)
train.set = sample(n, size = round(2/3 * n))
test.set = setdiff(seq_len(n), train.set)

lrn1 = makeLearner("classif.lda", predict.type = "prob")
mod1 = train(lrn1, sonar.task, subset = train.set)
pred1 = predict(mod1, task = sonar.task, subset = test.set)
df = generateThreshVsPerfData(pred1, measures = list(ppv, tpr, tnr))
plotROCCurves(df)
# Error in if (diagonal & all(sapply(obj$data[, names(measures)], max) <=  : 
#   missing value where TRUE/FALSE needed

plotThreshVsPerf(df) # works

mlr:::measurePPV
# function (truth, response, positive) 
# {
#     measureTP(truth, response, positive)/sum(response == positive)
# }
```

**Comment by schiffner** [comment]
A related question: `generateROCRCurvesData` etc. have been completely removed, right? I'm not sure what we agreed on. Shouldn't they be deprecated first?

**Comment by zmjones** [comment]
Ok will fix the docs and will look into the other issue.

Maybe we should have deprecated the ROCR functions. Have we released to CRAN since they were removed? I definitely should have made it more of a discussion. If we bring them back they will need to be fixed a bit, since as you pointed out the ROCR generation/plot had some problems.

**Comment by schiffner** [comment]
> Ok will fix the docs and will look into the other issue.
Thx.

> Maybe we should have deprecated the ROCR functions. Have we released to CRAN since they were removed? I definitely should have made it more of a discussion. If we bring them back they will need to be fixed a bit, since as you pointed out the ROCR generation/plot had some problems.

I thinks that's not worth the effort.
@berndbischl: What's your opinion?

**Comment by schiffner** [comment]
Sorry, me again. Noticed another small thing.

When passing `measures` to `plotROCCurves` it seems to plot the correct curves, but the axis labels are off.

```
n = getTaskSize(sonar.task)
train.set = sample(n, size = round(2/3 * n))
test.set = setdiff(seq_len(n), train.set)

lrn1 = makeLearner("classif.lda", predict.type = "prob")
mod1 = train(lrn1, sonar.task, subset = train.set)
pred1 = predict(mod1, task = sonar.task, subset = test.set)

df = generateThreshVsPerfData(pred1, measures = list(fpr, tpr, mmce))

plotROCCurves(df, measures = list(mmce, fpr))
# x label: False positive rate, y label: True positive rate

plotROCCurves(df, measures = list(mmce, fpr), pretty.names = FALSE)
# x label: fpr, y label: tpr
```

**Comment by berndbischl** [comment]
@mllg @larskotthoff 

Regarding the deprecation thing: Let us please IN GENERAL try to deprecate stuff. And fade it out very slowly. Thats is much better for other people. This means we will not really fix and maintain the older stuff anymore. 

And I just talked to Zach. He says we should be fine by leaving ROCR out. So I will follow that.

Lets fix these soon and close this when we can

**Comment by schiffner** [comment]
Thanks Zach for fixing all this stuff so quickly.
