### ISSUE TITLE
plotThreshVsPerf

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#700]
Sorry, found another problem.

In the below plots there are separate lines drawn for each CV iteration, but the starting and end points are also connected, see example:

```
lrn1 = makeLearner("classif.lda", predict.type = "prob")
lrn2 = makeLearner("classif.ksvm", predict.type = "prob")
lrns = list(lrn1, lrn2)
rdesc = makeResampleDesc("CV", iters = 3)

## benchmark result
res = benchmark(lrns, tasks = sonar.task, resampling = rdesc, measures = list(mmce, auc), show.info = FALSE)
df = generateThreshVsPerfData(res, measures = list(fpr, tpr, mmce), aggregate = FALSE)
plotThreshVsPerf(df)

## list of resample results
r1 = resample(lrn1, sonar.task, rdesc, measures = ms, show.info = FALSE)
r2 = resample(lrn2, sonar.task, rdesc, measures = ms, show.info = FALSE)
df = generateThreshVsPerfData(list(r1, r2), measures = list(fpr, tpr, mmce), aggregate = FALSE)
plotThreshVsPerf(df)
```

@zmjones: Sorry, I'm playing around with the ROC tutorial page and thus found a number of issues at once. :(  Let me know if you want help here or for #699.

**Comment by zmjones** [comment]
what is the `ms` measure. mmce?

**Comment by zmjones** [comment]
well that looks weird. never seen that before.

**Comment by schiffner** [comment]
> what is the ms measure. mmce?

Oops. I used `ms = list(auc, mmce)`, but I guess it doesn't matter.
