### ISSUE TITLE
Update docs of crit differences plots

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#705]
In this is PR @schiffner said: 
https://github.com/mlr-org/mlr/pull/695

§The docs of friedman*TestBMR, generateCritDifferencesData, plotCritDifferences need some improvements. It's probably easiest if I just do a commit in this branch after you are done, Bernd."

**Comment by berndbischl** [comment]
I would be great if you 
1) could update the docs
2) if while you do that you see some easy clean ups in the code, go for it please
3) can you transform the detected problem in the PR thread into a unit test?

**Comment by schiffner** [comment]
> 3) can you transform the detected problem in the PR thread into a unit test?
I can try to come up with tests for the "changing the `baseline`" problem (#695) and the earlier bug (in #643).

A general question about any tests for this: I never fully understood why mlr was broken on CRAN.
Any advice so that I don't accidentally build in a similar problem again?

**Comment by berndbischl** [comment]
2 answers:

a) mlr was broken on cran because ggplo2 was API-changed. and @pfistfl simply created a unit test which with 1% probability failed, beacause it was stochastic and lets say sub-optimally designed. 
So this does not really concern you.

b) look at what @zmjones and @larskotthoff did to test correctness of plots and talk to them. because this seems to be the problem here, right?

**Comment by schiffner** [comment]
Can I rename the `p.value` arg?
I don't know why I missed that before, but you don't pass a p-value to a test, but a significance level.

**Comment by berndbischl** [comment]
> Can I rename the p.value arg?

yes do that

**Comment by schiffner** [comment]
Just noticed in the tutorial that the x-axis of the critical differences plot is now missing (?!).
This is just to remind me that I need to investigate this, too.
