### ISSUE TITLE
Automatically test learners' ParamSets by comparing default params to no params

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#711]
Some of the included learners seem to have parameters listed in their ParamSet that do not work for some reason (typo in parameter name, trainLearner.XXX goofs it up, ...) or may be set to the wrong default. An efficient way to prevent these bugs to some degree would be to test that each learner's behaviour when no hyperparameters are set is the same as the behaviour when the hyperparameters are set to their default values.

**Comment by MariaErdmann** [comment]
Refers to #1034 . Shall we close this issue then?
