### ISSUE TITLE
Featureless dummy learners

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#712]
For comparisons it is nice to have models which predict y, but dont use the features at all.

For classification, this is either a simple majority vote, or sampling from the prior distribution.
For regression it could be the simply the mean. 

Franz Kiraly  requested this.  I have started to work on it in this branch.
https://github.com/mlr-org/mlr/tree/create_featureless_dummy_models

scitkit learn has these as well:
http://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyClassifier.html
http://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyRegressor.html

**Comment by berndbischl** [comment]
@jklanger 
this would be extremely useful to have in mlr and should also be faily simple to code. please take a look at my branch. and talk to me about how to do this in detail here. 

the major problem might be to construct a dummy learner which is more or less "optimal" for a certain performance measure. but we also maybe dont have to go overboard for the first try?

**Comment by ja-thomas** [comment]
We already have `NoFeaturesModel`. This is quite related to this task I would say and we may should adapt it as well.

**Comment by larskotthoff** [comment]
This sounds related to the `ConstantClassWrapper` -- maybe some code can be used in both places?

**Comment by giuseppec** [comment]
By the way, here is a pull request for this issue here: https://github.com/mlr-org/mlr/pull/1063. 
@smilesun just mention always the issue in the pullrequest so that we know that there is already a pullrequest to solve this issue.

**Comment by berndbischl** [comment]
> his sounds related to the ConstantClassWrapper -- maybe some code can be used in both places?

where is this again?

**Comment by larskotthoff** [comment]
The `ConstantClassWrapper`.

**Comment by ja-thomas** [comment]
This is related, but we want to do this not only for classifcation, but also regression (and maybe survival in the future). So I'm not sure if we can (and want) to use the `ConstantClassWrapper`

**Comment by pat-s** [comment]
We have featureless learners in _mlr3_ now.
