### ISSUE TITLE
partialprediction with GGVIS, some smaller issues

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#713]
Hi,

Lets use this code as background for this thread:

```
library(mlr)
library(TH.data)
data(bodyfat)
bodyfat$agegroup = as.factor(bodyfat$age > 50) # create a categorical feature
bf_task = makeRegrTask(data = bodyfat, target = "DEXfat")
lrn = makeLearner("regr.randomForest", ntree = 3L, predict.type = "se")

fit_model = train(lrn, bf_task)
pd_model = generatePartialPredictionData(fit_model, bf_task, c("waistcirc", "agegroup"), 
  interaction = TRUE)
pl = plotPartialPredictionGGVIS(pd_model, interact = "agegroup")
print(pl)

```

a) So the above works nice. But if I forget to set "interaction = TRUE" I can still run  plotPartialPredictionGGVIS, with interact = "agegroup". The plot looks broken. We should instead just throw an error.  This should also be unit tested.

b) Now remove the ineraction = TRUE and also interact = "agegroup". The plot is broken as well. If the 2nd feature is not a factor but a numeric, it works. 

c) We should make sure that people see how nice the "interact" is. I have to recheck the tutorial, or maybe @schiffner can also do this, the "interact" concept should be explained there.

d) We should, in general, use https://www.shinyapps.io, to demo ggvis stuff. Just put small, commented code snippets there and link to them. 
Do this for plotPartialPredictionGGVIS.

**Comment by pat-s** [comment]
GGVIS functions are deprecated.
