### ISSUE TITLE
subsetTask and getTaskData should also allow integer indices for features

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#716]
it is much nicer if we dont have to do this always
getTaskFeatureNames(task)[1:3]

**Comment by berndbischl** [comment]
are there other functions to consider?

**Comment by florianfendt** [comment]
@berndbischl 
Should I get rid of this FIXME in ````getTaskData()````:
````
#FIXME: argument checks currently not done for speed
````

**Comment by berndbischl** [comment]
OK, do it.

**Comment by berndbischl** [comment]
PR is here #825
