### ISSUE TITLE
resample(..., extract = [defaultValue]) with Wrappers

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#73]
The usual case when using a wrapped learner like `makeFeatSelWrapper` is that you also want to access the used Features at the end. So why doesn't these wrappers tell `resample` directly what should be extracted in the default case? It's not that costly to  extract with `getFeatSelResult` by default, isn't it?

Suggestions:
* makeTuneWrapper : getTuneResult
* makeFeatSelWrapper : getFeatSelResult
* makeFilterWrapper : getFilteredFeatures
* Did I miss something?

When preforming the benchmark (Issue #40) for example it would be also more handy when the user doesn't have to take care of it. Or should it be implemented in the benchmark locally?

**Comment by jakob-r** [comment]
Pull request here: https://github.com/mlr-org/mlr/pull/419
Will auto merge in 3 days

**Comment by berndbischl** [comment]
Apparently we have this now
