### ISSUE TITLE
{classif,regr}.{gbm,bdk} parameter keep.data not used

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#731]
The `trainLearner` function of `classif.gbm`, `regr.gbm`, `classif.bdk` and `regr.bdk` all give the parameter `keep.data` explicily as `FALSE` to the learner call inside `trainLearner.XXX`, ignoring the parameter declared in their ParamSet.

When `keep.data` is given, the learner crashes:
```R
> train(makeLearner("regr.gbm", keep.data=FALSE), bh.task)
Error in gbm::gbm(f, data = getTaskData(.task, .subset), keep.data = FALSE,  :
  formal argument "keep.data" matched by multiple actual arguments
Timing stopped at: 0.005 0 0.01
```
```R
> train(makeLearner("classif.gbm", keep.data=FALSE), pid.task)
Error in gbm::gbm(f, data = d, keep.data = FALSE, ...) :
  formal argument "keep.data" matched by multiple actual arguments
Timing stopped at: 0.007 0 0.007
```
etc., similar for `*.bdk`.

Either `keep.data` should be removed from the ParamSet or the parameter should be considered when given.

**Comment by larskotthoff** [comment]
I didn't see a reason why `keep.data` isn't passed through so I've fixed this, but Bernd may know why it was implemented like this in the first place :)
