### ISSUE TITLE
Some parameters of classif.ada do not work.

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#732]
Because of something that might be a bug in `ada::ada`, it throws an error whenever there are extra args in the `...` that don't match `formals(rpart::rpart)`. That means `rpart.control` parameters can not be used, since they fall inside the `...` of `rpart::rpart`.

The parameters in question are
- minsplit
- minbucket
- cp
- maxcompete
- maxsurrogate
- usesurrogate
- surrogatestyle
- maxdepth
- xval

```R
> l = makeLearner("classif.ada", minsplit=20, minbucket=20, cp=0.01, maxcompete=4, maxs
urrogate=5, usesurrogate=2, surrogatestyle=0, maxdepth=30, xval=10)
> train(l, pid.task)
Error in ada.default(x, y, ..., na.action = na.action) :
  Error:  Argument minbucket not matchedError:  Argument maxcompete not matchedError:  Argument maxsurrogate not matchedError:  Argument usesurrogate not matchedError:  Argument surrogatestyle not matched
Timing stopped at: 0.009 0.001 0.013
```

One notices there is no error for some of the parameters I listed. This is because **additionally** there is a bug in `trainLearner.ada` where some of these parameters are collected in a list and given as unnamed parameter:
```R
#R/RLearner_classif_ada.R
  to.list = c("maxdepth", "cp", "minsplit", "xval")
  list = filterNull(dots[to.list])
  dots = dropNamed(dots, to.list)
  args = c(dots, list(list))
```
Maybe at some point in time this was a way to circumvent the ada bug, but as I see it now, ada assigns the list to the first parameter that is not given otherwise ("`test.x`").

If there is no way to give these parameters to `rpart::rpart.control` without hiccup from ada, then these parameters should be removed from the ParamSet.

**Comment by mb706** [comment]
The given code doesn't fix the issue. The error won't be thrown any more, but instead the given values are ignored by ada.

This is because `trainLearner.classif.ada` assigns all the values that I list above to a list and gives this list as an unnamed argument to `ada::ada`. Therefore, `ada` interprets this list as the first argument that is not otherwise named in the call, which happens to be `test.x`. As can be seen in `ada:::ada.default`, `test.x` [will be removed since `test.y` is `NULL`](https://github.com/cran/ada/blob/3c3917b4e3a53894d43752bcf5f28015fd6921fe/R/ada.default.R#L30-L41), hence the arguments are ignored.

Proof:
```R
# the following trace command will cause ada:::ada.default to print the value
# of all local variables as soon as it is called. This will be the value of all given
# function parameters.
trace(ada:::ada.default, quote(print(as.list(sys.frame(-4)))))

#make a small task that won't take up too much screen space when it will be printed.
smalltask <- subsetTask(pid.task, subset=c(1:3))

# the output of the following call includes the values of the parameters as
# ada:::ada.default sees them. Notice test.x$xxx are present.
> train(setHyperPars(makeLearner("classif.ada"), xval=10, minsplit=10, minbucket=100),
  smalltask)
Tracing ada.default(x, y, ..., na.action = na.action) on entry 
$x
  pregnant glucose pressure triceps insulin mass pedigree age
1        6     148       72      35       0 33.6    0.627  50
2        1      85       66      29       0 26.6    0.351  31
3        8     183       64       0       0 23.3    0.672  32

$y
[1] "pos" "neg" "pos"

$test.x
$test.x$minsplit
[1] 10

$test.x$xval
[1] 10

$test.x$minbucket
[1] 100


$test.y
NULL

$loss
[1] "exponential" "logistic"   

$type
[1] "discrete" "real"     "gentle"  

$iter
[1] 50

$nu
[1] 0.1

$bag.frac
[1] 0.5

$model.coef
[1] TRUE

$bag.shift
[1] FALSE

$max.iter
[1] 20

$delta
[1] 1e-10

$verbose
[1] FALSE

$na.action
function (x) 
{
    Terms <- attr(x, "terms")
    if (!is.null(Terms)) 
        yvar <- attr(Terms, "response")
    else yvar <- 0L
    if (yvar == 0L) {
        xmiss <- is.na(x)
        keep <- (xmiss %*% rep(1, ncol(xmiss))) < ncol(xmiss)
    }
    else {
        xmiss <- is.na(x[-yvar])
        ymiss <- is.na(x[[yvar]])
        keep <- if (is.matrix(ymiss)) 
            ((xmiss %*% rep(1, ncol(xmiss))) < ncol(xmiss)) & 
                ((ymiss %*% rep(1, ncol(ymiss))) == 0)
        else ((xmiss %*% rep(1, ncol(xmiss))) < ncol(xmiss)) & 
            !ymiss
    }
    if (all(keep)) 
        x
    else {
        temp <- seq(keep)[!keep]
        names(temp) <- row.names(x)[!keep]
        class(temp) <- c("na.rpart", "omit")
        structure(x[keep, , drop = FALSE], na.action = temp)
    }
}
<bytecode: 0x5583b80895e0>
<environment: namespace:rpart>

Model for learner.id=classif.ada; learner.class=classif.ada
Trained on: task.id = PimaIndiansDiabetes-example; obs = 3; features = 8
Hyperparameters: xval=10,minsplit=10,minbucket=100
> 
```

**Comment by berndbischl** [comment]
@jklanger 
this should be fairly simple. do you wanna take a look here?

**Comment by jklanger** [comment]
Working on issue #732 I found the following problem:
The rpart.control parameters were collected in an unnamed list, which is then given to the ada function. Like mentioned by @mb706 this unnamed list is recognized as the parameter 'test.x', which during the execution of ada is set to NULL iff the argument 'test.y' is NULL.
To fix this I put all rpart.control parameters in a list named 'control', which is then recognized by ada.

See changes in the above PR.

**Comment by berndbischl** [comment]
@florianfendt 
please check all here and report status

**Comment by florianfendt** [comment]
@berndbischl 
I checked and all seems well. @giuseppec wrote a small test for this in PR #1081, should we extend this a little?

**Comment by larskotthoff** [comment]
If the tests checks what has been reported here, it's fine. I'll close this issue.
