### ISSUE TITLE
classif.dcSVM: "kernel" parameter broken.

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#733]
The kernel parameter to `e1071::svm` differs from the kernel parameter for `SwarmSVM::dcSVM`: it must be one of "linear", "polynomial", "radial", "sigmoid" instead of 1, 2 or 3. Since `trainLearner.classif.dcSVM` sometimes uses `e1071::svm` instead of `SwarmSVM::dcSVM`, the parameter should be adapted in this case.

```R
> train(makeLearner("classif.dcSVM", kernel=1), pid.task)
Error in svm.default(x, y, scale = scale, ..., na.action = na.action) :
  wrong kernel specification!
Timing stopped at: 0.011 0.001 0.012
```
(note the error message comes from inside (`e1071::`)`svm.default`)

**Comment by larskotthoff** [comment]
Thanks for the report, this is fixed in #768.
