### ISSUE TITLE
classif.neuralnet parameter linear.output broken

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#736]
Similar to #731, `linear.output` is set explicitly in `trainLearner.classif.neuralnet` and therefore leads to a bug if also given as hyperparameter:
```R
> train(makeLearner("classif.neuralnet", linear.output=TRUE), pid.task)
Error in neuralnet::neuralnet(f, data = taskdat, linear.output = FALSE,  :
  formal argument "linear.output" matched by multiple actual arguments
Timing stopped at: 0.007 0 0.017
```

**Comment by berndbischl** [comment]
but for classif we never want linear output? 
so i guess we simply remove the hyperpar, and add a note

**Comment by larskotthoff** [comment]
Agreed. I've done that in the PR.
