### ISSUE TITLE
Use stringi internally

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr#744]
We should use stringi for all string operations. Grep for "substr", "grep", "regex".

**Comment by berndbischl** [comment]
Please note: if we ever clean this up, we might have to make a note the coding giudelines + check for it later.

**Comment by MasonGallo** [comment]
Just to confirm - any particular reason why "only" substr, grep, regex mentioned? What about any other string methods from base R?

**Comment by berndbischl** [comment]
> Just to confirm - any particular reason why "only" substr, grep, regex mentioned? What about any other string methods from base R?

i think these were the ones that @mllg could think of. if there are more, refactor those too
(i hope its not that many)

**Comment by MasonGallo** [comment]
That's what I figured. Thanks!

**Comment by berndbischl** [comment]
was solved in #904
