### ISSUE TITLE
Allow tuning with time budget

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#749]
Currently, `tune` and/or `tuneControl` seem to only allow control over the number of evaluations to perform when tuning, but giving a time budget would also be useful. A simple way to implement this would be to use `R.utils::withTimeout` at and keeping track of the elapsed walltime in some way.

This allows relatively fine-grained control over the runtime, even R-based learners that run for a long time can be interrupted like this. Only a learner based on C code that is also not interruptible by pressing Ctrl-C can not be interrupted like this.

**Comment by pat-s** [comment]
Termination by runtime is supported in _mlr3tuning_.
