### ISSUE TITLE
Make information about learners easily accessible.

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#751]
It would be nice if there were more information about the learners easily accessible, regarding
(**1**) the thing they actually do (e.g. `help(the_function_actually_called_inside_trainLearner)`). Right now one would need to use the appendix of the tutorial to get this information.
(**2**) maybe specific information about their workings within mlr or user experience.

**To (1):** It would be useful to add an `mlrHelp()` function that accepts a learner (or learner string) and calls help() for the actual function being called inside `trainLearner` or `predictLearner` (whichever is the more important one?). If the function being called depends on the parameters, or if both `trainLearner` and `predictLearner` call interesting functions (a function being 'interesting' if something in the ParamSet influences its behaviour), it should prompt the user to choose between different help pages. I would imagine the user interface to be something like:

```
> mlrHelp("classif.pamr")
pamr: ** Nearest shrunken centroid **
Choose help page:
1 : pamr::pamr.train
2 : pamr::pamr.predict
...:[user input]
```

Internally this would not be more than listing all the 'interesting' functions in a learner-object $property and having the `mlrHelp` function do the mentioned prompt and calling `help()`.

**To (2):** This seems to already exist in the form of `learner$notes`, but apparently, if someone has something to add to that, they would have to fork the repo and make a pull request? One could use the Github mlr Wiki (or something else that is publicly editable) to collect information about different learners; things that may be of interest to the user, maybe even have something about sensible parameter settings if a contributor has some expertise. During the build process, this information could be curl'd from the github wiki and included as data in the R package and made available also via `mlrHelp`.

**Comment by jakob-r** [comment]
This is a quite extensive suggestion. I also note that the different learners could be documented more detailed.
I don't like the idea of a command line help interface so much as it is really unhandy. I prefer a more detailed and automatically generated documentation in the mlr tutorial. Obviously this should be mentioned in the internal documentation to not leave the user clueless.
Information about what parameters are sensible might be included in the future from other sides. 
What might be a good idea is to have a link to the internal documentation of the desired learner, so that `mlrHelp("classif.lqa")` would link you to `?lqa::lqa.default`  But this is also a good amount of not so demanding work.

**Comment by mb706** [comment]
Something in the direction of
```R
# assuming learner$callees is a character vector containing the functions of
# package learner$package that are 'interesting'.
mlrHelp = function(learner, ...) {
  learner = checkLearner(learner, ...)
  if (is.null(learner$callees)) {
    catf("No information about learner %s found.", coalesce(learner$name, learner$shortname, learner$id))
    return(NULL)
  } 
  if (length(learner$callees) == 1) {
    return(help(learner$callees, package=learner$package[1]))
  }
  repeat {
    cat("Choose help page:\n")
    cat(paste0(seq_along(learner$callees), " : ", learner$package[1], "::", learner$callees, "\n", collapse=""))
    n <- readline("(Ctrl-C to cancel)\n...: ")
    n <- ifelse(grepl("\\D",n),-1,as.integer(n))
    if (n >= 1 && n <= length(learner$callees)) {
      catf("Invalid input. Enter a number between 1 and %d", length(learner$callees))
      break
    }
  }
  return(help(learner$callees[n], package=learner$package[1]))
}

**Comment by jakob-r** [comment]
Well yeah kind of. But the problem is obviously that we don't have the slot `$callees` :wink: . So somebody would have to do that for all learners. But before you put more time into it let's find a good solution so that you don't code in vain.

**Comment by berndbischl** [comment]
1) I agree that what Martin suggests in point 1) is extremely helpful and I would definitely use it. Note that even from the appendix page we dont directly link to the called training function, but only to the package. So it is not perfectly convenient to reach the help page. 
And thanks for the mlrHelp code. Sounds like a student assistent task, to add the meta info slot to the learners. 

2) I can also see the point about adding user info to the learners. First of all an explanation what "note" was supposed to be: Here we state whether mlr actually somehow "deviates" in its call of the learner from it default behavior. (Very seldomly we have to recode/rename params and so on). But already for the random forest you can see that we added info now that it sometimes crashes.

On a technical side it might probably best if we simply assign a Wiki page for this? Currently it would be  empty. So I would suggest to have one page for all learners for now. If it fills up we can have one page (autogenerated) for each learner?

@larskotthoff 
@mllg 

Opinions?

**Comment by larskotthoff** [comment]
Sounds good.
