### ISSUE TITLE
Add extra features to task after feature selection

### ISSUE THREAD

**Issue by enricoferrero** [mlr-org/mlr#753]
I have two sets of features for my observations, a large one (tens of thousands) and a small one (around ten). 

I would like these feature sets to be more or less balanced when training my model.

My strategy has been to create a task with the first feature set and perform an aggressive feature selection with mRMR. Now I would like to add the second set of features to my task.

What is the best way to do that?

Thanks!

**Comment by jakob-r** [comment]
Are you asking for technical help? If you have a filtered Task like in [this tutorial part](http://mlr-org.github.io/mlr-tutorial/devel/html/feature_selection/index.html#filter-methods) then you can get the filtered data.frame with `getTaskData(fitered.task)`, `cbind` it with your small feature set data.frame and create a new Task out of that.

**Comment by enricoferrero** [comment]
Thanks - that makes sense. I was just wondering if there was a specific method (similar to dropFeatures()) that should be used.

Is it better to ask this type of technical questions here or on StackOverflow with tag mlr?

**Comment by jakob-r** [comment]
1. `dropFeatures()` does more or less the same by returning you a task object but leaves you more choices on which feauters do you exactly want to drop. `filterFeatures()` is the more automatic approach.
2. Theoretically yes, but I have to sign up for email updates on those questions then ;) (I will do this now)

I will close. If you have questions left feel free to reopen.
