### ISSUE TITLE
Mark the logical parameters of Weka learners as default FALSE

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#755]
The RWeka learners usually take user arguments by initializing a `RWeka::Weka_control(...)` object, which will usually be passed to the Java class's `setOptions()` internally with the Weka_control objected _converted to character_. Looking into `RWeka:::as.character.Weka_control` one sees that a logical parameter, e.g. `S`, is converted to the string `"-S"` if the value is `TRUE` and is _discarded_ otherwise:
```R
> as.character(RWeka::Weka_control(A=TRUE, B=FALSE, C=1))
[1] "-A" "-C" "1" 
```
This might justify setting the 'default' value of all the logical parameters to Weka learners to `FALSE`. Grepping the source for Weka_control and checking for logical parameters, I find the following candidates:
- cluster.XMeans
- regr.IBk
- classif.PART*
- cluster.EM
- classif.J48*
- classif.IBk
- classif.JRip
- cluster.SimpleKMeans
- classif.OneR
- cluster.FarthestFirst

(*: already done in my PR #752 )

**Comment by jakob-r** [comment]
I would be very grateful if you just combine everything in your PR #752. I will try my best to get it merged fastly :wink: :+1:
