### ISSUE TITLE
classif.blackboost cannot use 'stump' argument properly

### ISSUE THREAD

**Issue by philippstats** [mlr-org/mlr#756]
Running 
`lrn = makeLearner("classif.blackboost", stump = TRUE)`
`train(lrn, task = pid.task)`
throws following error: 
`Error in mboost_fit(bl, response = response, ...) : 
  unused argument (stump = TRUE)`

Within `trainLearner.classif.blackboost` `stump = TRUE` should be passed to `ctree_control` which is not possible (no `stump` argument, no `...`)

**Comment by berndbischl** [comment]
Fixed in
https://github.com/mlr-org/mlr/commit/e73f63b9849b8c964b10291d45a309ac70d2f549

**Comment by berndbischl** [comment]
thx.
