### ISSUE TITLE
Passing ResampleInstance to tuneParams with control set to irace fails

### ISSUE THREAD

**Issue by tijoseymathew** [mlr-org/mlr#757]
A `ResampleInstance` does not work with `irace` although it is a valid argument for `tuneParams`. I understand this is to create the [multiple instances](https://github.com/mlr-org/mlr/blob/master/R/tuneIrace.R#L25).  But maybe we could, add a default resampling ('Subsample'?) on the train subset of task if a `ResampleInstance` is passed.

**Comment by jakob-r** [comment]
I could not reproduce what you mean. Can you post a minimal working example?

**Comment by tijoseymathew** [comment]
`ps = makeParamSet(
  makeNumericParam("C", lower = -12, upper = 12, trafo = function(x) 2^x),
  makeDiscreteParam("kernel", values = c("vanilladot", "polydot", "rbfdot")),
  makeNumericParam("sigma", lower = -12, upper = 12, trafo = function(x) 2^x,
                   requires = quote(kernel == "rbfdot")),
  makeIntegerParam("degree", lower = 2L, upper = 5L,
                   requires = quote(kernel == "polydot"))
)
ctrl = makeTuneControlIrace(maxExperiments = 200L)
rdesc = makeFixedHoldoutInstance(train.inds = 1:100, test.inds = 101:150, size = 150)
res = tuneParams("classif.ksvm", iris.task, rdesc, par.set = ps, control = ctrl, show.info = FALSE)`

**Comment by jakob-r** [comment]
Okay it was my mistake. We indeed prevent `ResampleInstance`s to be passed in `tuneParams`. Anyhow, what we do by default is `makeTuneControl*(same.resampling.instance = TRUE)` which leads to a fixed `ResampleInstance` used during tuning. This obviously doesn't give you full control over the train and test splits but in your example it also would not make much sense, as it splits all `virginica` to the test part. :wink:

**Comment by tijoseymathew** [comment]
> We indeed prevent ResampleInstances to be passed in tuneParams

I think `ResampleInstance` is a valid [parameter](https://github.com/mlr-org/mlr/blob/master/R/tuneParams.R#L16). At least it seems to work with `makeTuneControlGrid` 
>would not make much sense, as it splits all virginica to the test part. 

It was meant to be a MWE! I did not check the classes :-)

So what would you recommend if I needed to tune the parameters only on a subset of the task. Of course, I can create two separate task... 
Also is there a particular re-sampling strategy recommended for `itrace` I could't find any thing in the documentation.

**Comment by mb706** [comment]
The point of irace is to test the parameter configurations for the learner on _different_ problem instances (i.e. different `ResampleInstance`s) (read the [paper](http://iridia.ulb.ac.be/IridiaTrSeries/IridiaTr2011-004.pdf) if you want) to see which configurations perform best statistically; giving only one ResampleInstance would defeat this purpose. If you want to see which configuration performs best on a particular train / test split, you should use a different tuning algorithm.

**Comment by berndbischl** [comment]
@mb706 is correct. we should simply improve the docs and possibly the error msg
