### ISSUE TITLE
mlr fails R CMD check with dev ggplot2

### ISSUE THREAD

**Issue by hadley** [mlr-org/mlr#766]
Because ggsave now uses svglite for svg output, so you'll need to add `svglite` to your suggests file. Please fix and submit to CRAN ASAP.

**Comment by larskotthoff** [comment]
Thanks Hadley. We'll do that and make a new release ASAP (we're currently having some other issues that need to be fixed first).

**Comment by zmjones** [comment]
I'll look into it and see if I can fix it tomorrow.

**Comment by larskotthoff** [comment]
I've commented the failing tests for now -- the structure of the generated SVGs is completely different now and our xpaths don't match at all anymore.

**Comment by larskotthoff** [comment]
This issue is fixed in master and we'll make a release in the next few days. Closing.
