### ISSUE TITLE
tuneParams/IRace fails with requirements depending on non-character discrete params

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#777]
``` R
> ps = makeParamSet(makeLogicalParam("R"), makeNumericParam("C", lower=.1, upper=.9, requires=quote(!R)))
> ctrl = makeTuneControlIrace(maxExperiments = 40, nbIterations = 2, minNbSurvival = 1)
> rdesc = makeResampleDesc("Holdout")
> res = tuneParams("classif.J48", task = pid.task, resampling = rdesc, par.set = ps, control = ctrl, show.info=TRUE)
[Tune] Started tuning learner classif.J48 for parameter set:
     Type len Def     Constr Req Tunable Trafo
R logical   -   -          -   -    TRUE     -
C numeric   -   - 0.1 to 0.9   Y    TRUE     -
With control class: TuneControlIrace
Imputation value: 1
Error in !R : invalid argument type
```

Oh well. If we look into the debugger, we see this is because...

``` R
> debugger()
Message:  Error in !R : invalid argument type
Available environments had calls:
1: tuneParams("classif.J48", task = pid.task, resampling = rdesc, par.set = ps
2: sel.func(learner, task, resampling, measures, par.set, control, opt.path, s
3: g(or <- irace::irace(tunerConfig = tuner.config, parameters = parameters))
4: evalVis(expr)
5: withVisible(eval(expr, pf))
6: eval(expr, pf)
7: eval(expr, envir, enclos)
8: irace::irace(tunerConfig = tuner.config, parameters = parameters)
9: sampleUniform(parameters, nbNewCandidates, digits = tunerConfig$digits, for
10: conditionsSatisfied(parameters, candidate, currentParameter)
11: eval(condition, as.list(partialCandidate))
12: eval(expr, envir, enclos)

Enter an environment number, or 0 to exit  Selection: 12
Browsing in the environment with call:
   eval(expr, envir, enclos)
Called from: debugger.look(ind)
Browse[1]> R
[1] "FALSE"
Browse[1]> 
```

... irace sees R as a discrete (string) variable. This can be fixed by substituting all occurrences of logical parameters `x` in a requirement with `(x == "TRUE")`.
Or put it in the documentation somewhere and maybe message when `any(unlist(lapply([paramrequirements], all.vars)) %in% [logical param ids])`, so the user knows to use `== "TRUE"`.

**Comment by federicou** [comment]
Actually I'm having a similar problem 

library(mlr)
library(irace)
library(brnn)

options(mlr.debug.seed = 313L)
df <- read.csv("data4mlr.csv") #file is attached
lrn <- makeLearner("regr.brnn")
ps = makeParamSet(
  makeIntegerParam("neurons", lower = 2L, upper = 12L),
  makeNumericParam("mu",lower=0.0005,upper=0.01),
  makeLogicalParam("normalize"))

ctrl = makeTuneControlIrace()
rdesc = makeResampleDesc("CV",iter=10)
Task <- makeRegrTask(id = "OptiRSM",data = df,target = "O_1")
res = tuneParams(learner = lrn,task = Task,resampling = rdesc,par.set = ps,control = ctrl,measures = list(rmse))

[Tune] Started tuning learner regr.brnn for parameter set:
             Type len Def         Constr Req Tunable Trafo
neurons   integer   -   -        2 to 12   -    TRUE     -
mu        numeric   -   - 0.0005 to 0.01   -    TRUE     -
normalize logical   -   -              -   -    TRUE     -
With control class: TuneControlIrace
Imputation value: Inf
[Tune-x] 1: neurons=11; mu=0.00142; normalize=TRUE
[Tune-y] 1: rmse.test.rmse=0.617; time: 0.0 min; memory: 160Mb use, 261Mb max
[Tune-x] 2: neurons=10; mu=0.000587; normalize=FALSE
Error in if (C_new < C) { : missing value where TRUE/FALSE needed

[data4mlr.csv.zip](https://github.com/mlr-org/mlr/files/263511/data4mlr.csv.zip)

**Comment by mb706** [comment]
@federicou's bug is unrelated and stems from a (kind of) bug in `brnn` where too large input values give rise to `NaN`s. (In particular, C's `sech` for values greater than about 600, `NaN` is returned when a better value would be 0). The propensity for this to happen seems to be greater if `normalize == FALSE`.
