### ISSUE TITLE
Add argument fix.factors.prediction to makeRLearnerClassif

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#783]
... or make the `$fix.factors.prediction` slot default to something. Otherwise, the object resulting from `makeRLearnerClassif` is incomplete and one needs to set it manually after creating the learner -- or get an error when predicting:

``` R
> l = makeRLearnerClassif("myclas", character(0), makeParamSet(), properties=c("numerics", "twoclass"))
> trainLearner.myclas = function(.learner, .task, .subset, .weights=NULL, ...) NULL
> predictLearner.myclas = function(.learner, .model, .newdata, ...) factor("pos")
> predict(train(l, pid.task), pid.task)
Error in if (.learner$fix.factors.prediction) { (from predictLearner.R#51) : 
  argument is of length zero
Timing stopped at: 0.048 0 0.054 
```

**Comment by matkalinowski** [comment]
I have encountered the same problem when it comes to makeRLearnerRegr. Would you like some additional informations? If yes please tell me which.

**Comment by pat-s** [comment]
Even though there is no reference in this issue, this problem does not apply anymore in current master.
