### ISSUE TITLE
predict.WrappedModel gives warning when on.learner.error == "quiet"

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr#788]
(... if `on.learner.warning == "warn"`)
The culprit is [this](https://github.com/mlr-org/mlr/blob/1d2c1dfdf53e66d6c529880449775659291e68c8/R/predict.R#L117) line, it should be
```R
if (opts$on.learner.error == "warn")
```
(instead it is 'on.learner.**warning** == "warn"'.)

**Comment by berndbischl** [comment]
thx to both parties involved!
