### ISSUE TITLE
Choice of RandomForest algorithm

### ISSUE THREAD

**Issue by joaquinvanschoren** [mlr-org/mlr#806]
Hi, 

Maybe this is a silly question, but is there any guidance on which of the many RandomForest algorithms to use? For classification, I can find cforest, randomForest, and ranger. Ranger claims to be faster, randomForest seems to be Breiman's original implementation, and only cforest can handle missing values. Are there any more distinguishing features that are less apparent?

**Comment by berndbischl** [comment]
Hi,

it is OK to ask this here, but I might close this thread anyhow soon :)
It is also not a silly question. R and mlr now offer quite a lot of different packages for RFs.

I am not sure how we can handle this here, I guess the only chance is to write blog posts and scientific articles about this. And you will kinda have to read the relevant package docs and the articles behind those forests for now.

Maybe you already know these resources? The task view contains a section on forests:
https://cran.r-project.org/web/views/MachineLearning.html
And here is a summarizing blog post:
http://www.r-bloggers.com/a-brief-tour-of-the-trees-and-forests/

We can try to find people to write little giudance posts in the mlr tutorial / or blog, but this will take time.

I should also say that @PhilippPro works on exactly that topic what you are asking about.

**Comment by PhilippPro** [comment]
Hi,

I wrote something about exactly that in my blog:
http://philipppro.github.io/

I distinguised between packages that claim to be the "standard" random forest and some adaptations: http://philipppro.github.io/More_complete_list/

In my first post I also wrote something about different usage possibilities:
http://philipppro.github.io/Random_Forest_in_R/

Probably I still missed some packages/usages.

I am also making/want to make some benchmarking about speed and accuracy of the different implementations. I think the outcomes could be quite different as I also outlined here:
http://stats.stackexchange.com/questions/194560/difference-in-randomforestsrc-and-randomforest-package-increasing-oob-error-cu

**Comment by PhilippPro** [comment]
Some part of my blog posts could also be included in mlr blog/tutorial if you want it, Bernd.

**Comment by berndbischl** [comment]
i guess the question is answered here. 

i would like to extend the mlr pages at some point with standard benchmark results from OML for data based guidances. for the rest there are papers and blog posts and we cannot do this here currently.

@PhilippPro 
I see you do habe a lot of valuable info already linked above. I could keep this issue open, and as you suggested you could merge this in a tutorial post for mlr? Could you answer in the next days whether you wanna do that?

**Comment by zmjones** [comment]
I think this is way beyond our scope. I mean each one of these implementations has one or more papers written on the topic. The relevant citation is basically always found in the relevant package doc. I don't think this is different from asking why you'd want to use some other algorithm in place of rf either, and so we'd end up with an ML textbook.

**Comment by berndbischl** [comment]
@zmjones 
While I mainly agree with what you wrote: don't you think we could find a place for such "blog posts" as @PhilippPro in a separate section in the tutorial? i mean this will never be "exhaustive", but that does not mean its useless? honest question, somewhat undecided here.

**Comment by zmjones** [comment]
yea on the blog that would be ok, just not part of the tutorial. we still have the mlr-org blog running so why not use that? we ought to add that to r-bloggers if that is alright with you. what if we also got the domain mlr.org and used a CNAME to point mlr-org.github.io there?

**Comment by PhilippPro** [comment]
One bad thing about blog posts is, that they are not very good structured (in general), so the overview for readers is much worse than things that are written e.g. in the tutorial. 
But that could be resolved by having a good structure on our blog post page. 

I think my posts are not directly connected to mlr so probably it would be better to put it on "our" blog page and maybe link this site somehow from the tutorial and our mlr-org/mlr page.

I think in the tutorial there should only be things that really are connected to mlr.

**Comment by berndbischl** [comment]
i guess we are talking about mlr and blogging later anyhow and now we know that @PhilippPro's stuff exits. so i will close here.
