### ISSUE TITLE
allow to use BatchExperiments for benchmark exps

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#81]
See here

https://github.com/tudo-r/BatchExperimentsMlr/

**Comment by berndbischl** [comment]
Also see code here from Benni
https://github.com/benjaminschober/laufzeitanalyse_BA_Schober/tree/master/Code
batchmark_benni_testfile.R

**Comment by berndbischl** [comment]
And see here
https://github.com/mlr-org/mlr/blob/master/todo-files/batchmark.R

**Comment by ja-thomas** [comment]
As far as I understand we can now add suggests for github packages right? So we could add batchmark (which seem done and completely working as far as I tested it) and add it in the package?

**Comment by berndbischl** [comment]
> As far as I understand we can now add suggests for github packages right? So we could add batchmark (which seem done and completely working as far as I tested it) and add it in the package?

yes

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
