### ISSUE TITLE
normalizeFeatures and createDummyFeatures mini clean up

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#810]
1) normalizeFeatures is not S3 --> do this

2) check that checkTargetPreproc is used consistentlly everywhere

3) in capLargeVales and impute we positively specify "cols", here we have an "exlude" arg to exlude unwanted cols. Remove exlude and use "cols"

**Comment by berndbischl** [comment]
@florianfendt @Coorsaa 

Can you please talk about this, so we can close this ASAP? Who can do this first?

**Comment by florianfendt** [comment]
I'll do it

**Comment by berndbischl** [comment]
fixed in #868
