### ISSUE TITLE
rank.correlation filter should support factors but doesn't

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#815]
The rank.correlation filter throws an error when a task with factors is supplied
```
filterFeatures(bh.task, method = 'rank.correlation', abs = 2)
```

However, in the definition of this filter, it says that it supports factors
```
subset(listFilterMethods(features = T), id == 'rank.correlation')
````

**Comment by berndbischl** [comment]
The code in FSelector seems very clear. It only supports cont. features and our tag for method = 'rank.correlation' seems wrong. I will remove this now.
