### ISSUE TITLE
tuneThreshold: the multiclass version with cmaes should be checked

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#82]
We require at least multistarts.

Maybe we should consider genSA instead?

**Comment by berndbischl** [comment]
For TuneWrapper: to set further CMAES params in the threshold tuning.

**Comment by berndbischl** [comment]
actually cmaes seems to be maybe bad and slow. i used constrOptim instead. I started work in this branch. it is UNFINISHED. 

 tuneThreshold_multiclass_fix

**Comment by pat-s** [comment]
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.
