### ISSUE TITLE
Multi-class classification with imbalanced classes

### ISSUE THREAD

**Issue by enricoferrero** [mlr-org/mlr#821]
Is there any support for multi-class classification problems with imbalanced classes?
In particular I'd like to use `undersample()` with a `ClassifTask` with three classes which doesn't seem to be supported:

```
Error in checkTask(task, "ClassifTask", binary = TRUE) :
  Task 'dataset' must be binary classification!
```

Or is there any reason why imbalanced classes don't matter in multi-class problems?

Thanks,

**Comment by jakobbossek** [comment]
Dealing with imbalanced multi-class problems is a highly nontrivial research area. In fact, at the moment the under-/oversampling techniques as well as SMOTE in mlr can only deal with two-class problems. There are two approaches you could try instead:

- `OverBaggingWrapper`
- Apply cost-sensitive learning assigning higher class weights to minority class instances and lower weights for classes with more instances. For some learners, e.g., "classif.ksvm", "classif.randomForest", "classif.svm", you can pass class weights directly. Moreover you can use a `WeightedClassesWrapper` to add class weights to learners which support observation weights only.

**Comment by berndbischl** [comment]
+1 to what @jakobbossek  said.

more comments: 
- we spport measures for this case like balanced error rate,  cost measures and multiclass auc
- you can use threshold tuning, even for multiclass problems. but thisshould be improved a bit

it *is* an important topic and we should become better at it
