### ISSUE TITLE
variable importance information/plots?

### ISSUE THREAD

**Issue by andreashandel** [mlr-org/mlr#823]
Is it possible to pull out information on variable importance after tuning/training a model for which this information makes sense (e.g. a random forest or gbm model)? E.g. similar to varImp() in caret. Couldn't find anything on that topic in the tutorial. Thanks!
(this is obviously a question, I just can't figure out how to apply the 'question' label to it).

**Comment by zmjones** [comment]
Yes it is. I think we have a method for extraction when the learner automatically computes this, though I don't know off hand what this is. In any case the object returned by the learner contains the object returned by the function that actually trains the learner, and so you can extract that directly any way you like.

We also have [generateFilterValuesData](http://mlr-org.github.io/mlr-tutorial/devel/html/feature_selection/index.html) for which we have a large number of ways of computing feature importance as well as some visualization functions that work with the results.

**Comment by florianfendt** [comment]
I uploaded a PR (#667) on this couple of weeks back. I still need to review it with Bernd, hope we can merge it in soon though.

**Comment by andreashandel** [comment]
Thanks! 
@zmjones I've been digging around in the object that tuneParams returns, but I can't figure out how to pull out the original object returned by the underlying function (in this particular case it's glmnet, but knowing how to do that in general would be helpful). How can I retrieve the object returned by the underlying function?

**Comment by zmjones** [comment]
ah thanks @florianfendt that is what i was thinking of. definitely will be nice to have.

@andreashandel you wouldn't want to extract this from the `tuneParams` object but instead a `wrappedModel` which is what `train` returns. you would set the hyperparameters of your learners based on the what the `tuneParams` says is optimal. you can extract the underlying learner using `getLearnerModel`. I don't think there are any methods for `getLearnerModel` for classes other than `wrappedModel` but I could be wrong.

**Comment by berndbischl** [comment]
Andreas, can you please give a precise definition of what you want to do?
Best would be a concrete example, with some prelim code.

**Comment by andreashandel** [comment]
Thanks for all the replies and help so far!

Here is what I'm currently trying to do. Let's say I tune a random forest using e.g. repeated CV and run:
tuneres = tuneParams(...)
Ideally, what I'd like to do is something like:
varImp(tuneres)
which would give me the variable importance averaged over all samples for the optimal learner. 

I haven't quite been able to figure out how to do that. I can almost get it by using the optimal learner returned from the tuning process, send it through another resampling process using resample() and then use the extract = ... example from the tutorial to get variable importance for all samples. 
If I understand it correctly, with enough samples, this should be similar to the result from the original tuning process? But it would still be nice to not have to go through another sampling run and instead get variable importance for the optimal model directly from tuneParams(...). Is that possible? Thanks.

**Comment by berndbischl** [comment]
> Is it possible to pull out information on variable importance after tuning/training a model for which this information makes sense (e.g. a random forest or gbm model)?

this is currently been dealt with by @florianfendt, and handled in PR #667. So not done yet.

> Here is what I'm currently trying to do. Let's say I tune a random forest using e.g. repeated CV and run:
> tuneres = tuneParams(...)
> Ideally, what I'd like to do is something like:
> varImp(tuneres)
> which would give me the variable importance averaged over all samples for the optimal learner.
> 
> I haven't quite been able to figure out how to do that. I can almost get it by using the optimal learner returned from the tuning process, send it through another resampling process using resample() and then use the extract = ... example from the tutorial to get variable importance for all samples. 
> If I understand it correctly, with enough samples, this should be similar to the result from the original tuning process? But it would still be nice to not have to go through another sampling run and instead get variable importance for the optimal model directly from tuneParams(...). Is that possible? Thanks.


what you are asking here is really not supported at the moment. (and not really planned.) 
you have outlined a possible solution, which is to use the best found param by tuneParams, and then apply those manually.  
and that actually the only advice i good give to do that.
