### ISSUE TITLE
Question about glmnet in mlr

### ISSUE THREAD

**Issue by larry77** [mlr-org/mlr#824]
Dear All,
I am not sure this is an issue, but I am a bit puzzled.
Consider the following

`
> library(mlr)
> library(glmnet)
> lrn=lrn = makeLearner("regr.glmnet")
> lrn=makeLearner("regr.glmnet")
> lrn
Learner regr.glmnet from package glmnet
Type: regr
Name: GLM with Lasso or Elasticnet Regularization; Short name: glmnet
Class: regr.glmnet
Properties: numerics,factors,ordered,weights
Predict-Type: response
Hyperparameters: s=0.01

`
It looks to me that here I have only one model parameter I can tune -- s.
However, if I look at the vignette 

https://cran.r-project.org/web/packages/glmnet/vignettes/glmnet_beta.html#intro

it seems to me that there are 2 hyperparameters that play a role (lambda and alpha) and not only one.
For instance, in the caret model list

https://topepo.github.io/caret/modelList.html

I have 

Model	method Argument Value	Type	Packages	Tuning Parameters
glmnet	   glmnet	   Dual Use	             glmnet	        alpha, lambda

So I have two hyperparameters to tune.
I should say that I am now making my first baby steps with glmnet, so perhaps I am misunderstanding.
I have other questions (e.g. how to calculate the confidence interval of the glmnet predictions), but I will leave them for another post.
Now I have to make sure I get the fundamentals right.
Any clarification is appreciated.

**Comment by PhilippPro** [comment]
Dear Larry,

I think not all hyperparameters are shown if you look at the information of a learner, only these ones that where changed by the mlr-org community in comparison to the default values of glmnet. 
If you look at 
```
?predict.glmnet
```
you see, that ``s=NULL``as default, this was changed by the one who implemented glmnet. 

You can see all possible hyperparameter if you make 
```
lrn$par.set
```

It can happen, that a package changes and some hyperparameter is really missing, then you (or somebody else) can make a pull request to change the underlying function (https://github.com/mlr-org/mlr/blob/master/R/RLearner_regr_glmnet.R). 

(See here for how to create a custom learner: http://mlr-org.github.io/mlr-tutorial/devel/html/create_learner/index.html)

**Comment by larry77** [comment]
OK, now this is clear.

**Comment by berndbischl** [comment]
Short ps:
The best way to look at all available hyperparams for a learner is to call getParamSet on it. Pls use these getter functions. And for our team here: pls don't tell people otherwise. Directly accessing the member slots is less robust.

**Comment by berndbischl** [comment]
Short ps:
The best way to look at all available hyperparams for a learner is to call getParamSet on it. Pls use these getter functions. And for our team here: pls don't tell people otherwise. Directly accessing the member slots is less robust.

**Comment by larry77** [comment]
Hello,
Apologies for coming back on this topic.
If now I do the following

`library(mlr)`
`library(glmnet)`
`lrn = makeLearner("regr.glmnet")`
`getParamSet(lrn)`


I see that the "family" parameter is tunable, but it can only  take the values "gaussian" or "poisson", whereas in the original glmnet package more options are available (e.g. "mgaussian").
Am I misunderstanding or not all the options are available through mlr?
For completeness

> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid

locale:
 [1] LC_CTYPE=en_GB.utf8       LC_NUMERIC=C             
 [3] LC_TIME=en_GB.utf8        LC_COLLATE=en_GB.utf8    
 [5] LC_MONETARY=en_GB.utf8    LC_MESSAGES=en_GB.utf8   
 [7] LC_PAPER=en_GB.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_GB.utf8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmnet_2.0-5     foreach_1.4.3    Matrix_1.2-4     mlr_2.8         
[5] ParamHelpers_1.7 ggplot2_2.1.0    BBmisc_1.9      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3      magrittr_1.5     splines_3.2.4    munsell_0.4.2   
 [5] lattice_0.20-33  colorspace_1.2-6 xtable_1.8-0     R6_2.1.1        
 [9] dplyr_0.4.3      stringr_1.0.0    plyr_1.8.3       tools_3.2.4     
[13] parallel_3.2.4   grid_3.2.4       checkmate_1.7.3  gtable_0.2.0    
[17] DBI_0.3.1        iterators_1.0.8  htmltools_0.3    ggvis_0.4.2     
[21] survival_2.38-3  assertthat_0.1   digest_0.6.9     shiny_0.13.1    
[25] reshape2_1.4.1   codetools_0.2-14 mime_0.4         parallelMap_1.3 
[29] stringi_1.0-1    scales_0.4.0     backports_1.0.2  httpuv_1.3.3    
>

**Comment by PhilippPro** [comment]
Hi! `regr.glmnet` is a regression learner and all the other options of family are not for regression (mgaussian is for multivariate regression).

**Comment by berndbischl** [comment]
@PhilippPro 
answered this I guess. Closing.
