### ISSUE TITLE
subset argument in tuneParams() and benchmark()

### ISSUE THREAD

**Issue by enricoferrero** [mlr-org/mlr#836]
Would it be possible to have a subset argument in `tuneParams()` and `benchmark()` like there is in `train()` and `predict()`?

Essentially I'd like to tune and benchmark only on a subset of my task (the training set). What would be the best way?

Thanks.

**Comment by larskotthoff** [comment]
You can use `subsetTask()`.

**Comment by berndbischl** [comment]
> You can use subsetTask().

exactly. 

And: Do you want to do nested resampling, is that why you are asking? 
Because that you dont have to code yourself, you can use the TuneWrapper?

**Comment by enricoferrero** [comment]
Thanks both - `subsetTask()` does the job.
I'm not sure about the TuneWrapper suggestion: is there any practical advantage to use `makeTuneWrapper()` over something like this?
```
# decision tree
dt.lrn <- makeLearner("classif.rpart")
dt.ps <- makeParamSet(
                      makeDiscreteParam("cp", values = c(0.001, 0.0025, 0.005, 0.01, 0.025, 0.05))
                      )
dt.tun <- tuneParams(dt.lrn, classif.task, rdesc, par.set=dt.ps, control=ctrl)
saveRDS(dt.tun, file.path("../data/dt.tun.rds"))
dt.lrn <- makeLearner("classif.rpart", par.vals = list(cp=dt.tun$x$cp))
dt.lrn <- setPredictType(dt.lrn, predict.type="prob")
dt.lrn$id <- "Decision Tree"
```
Thanks
