### ISSUE TITLE
Question about downsampling / makeDownsampleWrapper()

### ISSUE THREAD

**Issue by bkomboz** [mlr-org/mlr#839]
When exactly does the downsampling in a (with `makeDownsampleWrapper()`) wrapped learner happen inside a cross-validation or during tuning? Is there a downsampling for every iteration of the cross-validation / tuning? Or only once at the beginning?

If it is only once, what is the recommended way to downsample / sample from a huge dataset during several cross-validation / tuning iterations?

*Edit*: I just discovered that `makeDownsampleWrapper()` is not working with a tuned learner.

**Comment by berndbischl** [comment]
the DownsampleWrapper simply downsamoles the data before each training call. 

What exactly are you trying to do? Can you explain that please?

**Comment by bkomboz** [comment]
Thanks for the fast reply (and the bugfix for issue #838). 

My situation is the following: I have a rather huge data set (> 4m observations) from which I want to (down)sample for each cross-validation iteration so that the cross-validation (I assume it is more like resampling in this case) uses a different (but smaller and probably overlapping) subset of the original data in each iteration. The reason why I want to do this is purely performance. As I have a nested cross-validation (with a inner tuning loop) it would also be cool, if I can take smaller subsamples/downsample the original data set in each tuning iteration but I am not sure how to do this.

At the moment I am downsampling initially to 2/3 of the data and then doing a 5-fold CV as outer loop and a holdout split in the inner tuning loop all based on the same single downsampled dataset. With this approach I basically lose some variability/have some bias as I only use a subset of the original data for everything. By downsampling in the outer or inner loop I hope to regain this information/variability.

**Comment by berndbischl** [comment]
Can you boild down your question to a mini example?  
Where simply the downsampling is missing? 
Then we can show you how to add this.

**Comment by bkomboz** [comment]
Sorry for the delay, here comes the mini-example (see comments in code):
```
library("mlr")
tsk <- sonar.task # task with all data
lrn <- makeLearner("classif.gbm")
desc <- makeResampleDesc("Subsample", iters = 10, split = 3/4, stratify = TRUE)

# Ideally, I would like to downsample for each resampling iteration to SAMPLE_FRAC percent of
# the original data and then do the resampling on this SAMPLE_FRAC percent of the data, i.e.,
# splitting it further into `split` and `1-split` parts. But this downsampling should happen for every
# iteration such that in the end there is the chance to have seen all available parts of the original data
# but each model is only fitted to a downsampled version (to speed up things)
r <- resample(learner = lrn, task = tsk, resampling = desc, measures = list(auc))
```

**Comment by berndbischl** [comment]
But this is exactly what the DownsampleWrapper does (if I get correctly what you want).
Before each training step (here, before each of the 10 training in the subsampling) the normal training data is randomly downsampled even further (so you basically randomly throw data point away before training).

Also the source code is in this case really simple to read. Why not check it yourself if you feel really unsure.

Reopen if questions remain.
