### ISSUE TITLE
Confidence Intervals in Prediction (bootstrap)

### ISSUE THREAD

**Issue by larry77** [mlr-org/mlr#843]
Dear All,
Once again, a question more than an issue (and perhaps a potential enhancement to mlr).
As you may have guessed from my other posts, I am fine tuning some predictive model based on glmnet for regression.
I am interested in estimating some confidence levels not for the estimated parameters, but rather for my predicted values.
glmnet does not return natively these confidence intervals (and this is not entirely without reason, see e.g. 

http://stackoverflow.com/questions/12937331/how-to-get-statistical-summary-information-from-glmnet-model
and
https://www.reddit.com/r/statistics/comments/1vg8k0/standard_errors_in_glmnet/
), but I nevertheless need to provide some quantitative estimate of the uncertainty in my prediction.
I found an online PhD theses which seems relevant 

https://air.unimi.it/retrieve/handle/2434/153099/133417/phd_unimi_R07738.pdf

(see sections 3.2 and 3.3). I wonder if any infrastructure to calculate by bootstrap the confidence levels of a prediction of a model exist in mlr (and if not, if there is any plan to introduce them any time soon).
Cheers

**Comment by zmjones** [comment]
Variance estimators for predictions have been implemented for some learners, and are accessed by using `predict.type = "se"`. Certainly it would be nice to have them for `glmnet`. I don't think we'll be implementing generic variance estimation methods for all predictions however.

**Comment by berndbischl** [comment]
> I don't think we'll be implementing generic variance estimation methods for all learners however.

I agree with Zach here, that we will not implement *method specific* se estimators. For that you should probably speak with the maintainer of glmnet.

But what about stuff which is more "generic" like the nonparam bootstrap? Are you asking about stuff like that (as well)?

**Comment by larry77** [comment]
Hello,
Maybe my post created some confusion. I am of course not dreaming to ask you to roll up your sleeves and write down a specific analytical estimator for the prediction uncertainty of a single specific model.
I am rather thinking about a generic bootstrap estimator which can be used with several models. I think this would be valuable for a whole class of models.
I am not at all a guru in bootstrap methods, but I think (seeing the quoted PhD thesis and 

http://www.stat.cmu.edu/~fienberg/Statistics36-756/Efron1979.pdf
and
http://www.ams.org/journals/proc/2010-138-12/S0002-9939-2010-10474-4/S0002-9939-2010-10474-4.pdf
) that these methods should have a wide range of applications.

**Comment by zmjones** [comment]
I meant that that is what we should not do. Mainly because I don't think it will work particularly well. There are some generic variance estimators for homogenous ensembles that have been studied and all have substantial monte carlo bias. When there is a variance estimation method that hasn't been implemented and that has been shown to work for a particular method or set thereof (like the abovementioned homogenous ensemble stuff) then I am all for having it in mlr.

**Comment by berndbischl** [comment]
I talked a bit to Zack on Hangout. 

We think it MIGHT be reasonable to support something like the nonparametric bootstrap for se estimation in mlr, through the BaggingWrapper. (case resampling)

@zmjones Does that basically already exitst in some PR?

**Comment by larry77** [comment]
Excellent and thanks a lot. Will I be notified through an update of this issue when and if this gets implemented in mlr?
Keep up the good work.

**Comment by berndbischl** [comment]
This issue would be updated. But we likely need some time for this.

**Comment by zmjones** [comment]
@berndbischl no not yet. i still have a lot of work to do on it. it probably will be done at the end of may though.

@larry77 i'll reference this issue when i issue the pull request

**Comment by larry77** [comment]
Hello,
Any progress on this issue? I finally implemented a residual resampling strategy as in 
http://www.statoo.com/en/publications/bootstrap_scgn_v131.pdf
but it would be really nice, I believe, to have it hard-coded in mlr.

**Comment by zmjones** [comment]
hey @larry77 no sorry i am behind on this. trying to finish a chapter of my dissertation by the end of the summer...

**Comment by berndbischl** [comment]
hi. i will close this here but have noted this as a possible extension in another catchall thread.

lets reopen this if someone is concretely working on this
