### ISSUE TITLE
getConfMatrix odd margins

### ISSUE THREAD

**Issue by waynefoltaERI** [mlr-org/mlr#845]
Not sure what the margins mean when you do a `getConfMatrix`. Is it supposed to be the number of misclassifications?

```
> pred
Prediction: 105 observations
predict.type: prob
threshold: FALSE=0.50,TRUE=0.50
::

> getConfMatrix(pred)
       predicted
true    FALSE TRUE -SUM-
  FALSE    43   22    22
  TRUE     20   20    20
  -SUM-    20   22    42
```

**Comment by berndbischl** [comment]
Thx for the hint. The docs could be improved here. Updated them like this now.

#' The marginal elements count the number of classification
#' errors for the respective row or column, i.e., the number of errors
#' when you condition on the corresponding true (rows) or predicted
#' (columns) class. The last element in the margin diagonal
#' displays the total amount of errors.
