### ISSUE TITLE
Question regarding multiclass and binary measures

### ISSUE THREAD

**Issue by catastrophic-failure** [mlr-org/mlr#855]
I've been using brier from packages `scoring` for some time in `mlr` and now I saw multiclass Brier score is being added in #854  as a multiclass measure and a question came to my mind.
Is there are reason why doesn't `mlr` unify every measure with separate multiclass and binary implementations? `makeMeasure` could include a conditional to call either `measureBinary` or `measureMulticlass`.
Pros: It would make it easier to compare results in benchmarks including multiclass and binary tasks.
Con: Some measure have different definitions in their multiclass interpretation, and might not be directly comparable.

**Comment by berndbischl** [comment]
I am not sure what you exactly mean by:

> Is there are reason why doesn't mlr unify every measure with separate multiclass and binary implementations?

you mean why we have 2 names / objects for 
brier and multiclass.brier
auc and multiclass.auc

instead of one object and internally dispatching to the correct case?

**Comment by catastrophic-failure** [comment]
Yes, exactly.

**Comment by berndbischl** [comment]
ok, i can see your point. we could try to unify this under one object.

i also already see the problem that sometimes different multiclass versions will exist. but i would guess that the 2class version is always unique.

so we could still have auc1 and auc2 as objects. they would results in the same binary AUC for 2 classes,   but offer different multiclass versions (of course they would be named better....)

a cleaner approach would be to have a configurable constructor, but that we cannot do as it would change the whole structure.

**Comment by berndbischl** [comment]
ok answer here is:

1) we have added multiclass.brier
2) as multiclass.brier is not the same as the normal brier for 2class problems we cannot unify this further. and two objects seem ok to me here.

reopen if further questions or comments remain
