### ISSUE TITLE
Observation weights are not passed to classif.logreg

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#857]
The following gives exactly the same performance although it shouldn't

    lrn <- makeLearner('classif.logreg', predict.type = 'prob')
    lrn.w <- makeWeightedClassesWrapper(lrn, wcw.weight = 2)
    benchmark(list(lrn, lrn.w), pid.task, cv10, list(bac, auc, tpr, tnr))

**Comment by studerus** [comment]
Observation weights are also not passed to the following learners
`classif.binomial, classif.ctree, classif.lqa, classif.probit`

**Comment by studerus** [comment]
`classif.binomial, classif.ctree, classif.probit` are easy to change. 
However, I don't know why this gives the same performance;
    
    lrn <- makeLearner('classif.lqa', predict.type = 'prob')
    lrn.w <- makeWeightedClassesWrapper(lrn, wcw.weight = 2)
    benchmark(list(lrn, lrn.w), pid.task, cv10, list(bac, auc, tpr, tnr))

The weights seem to be passed to the learner with the following lines:
 
    if (!is.null(.weights))
      args$weights = .weights
    do.call(lqa::lqa.default, args)

**Comment by berndbischl** [comment]
i have made EXACTLY the same observations as you, yesterday night. ;-)

i do have a general unit test for this. and fixed all learners where this was triggered (basically your list).
but lqa and plr where the only ones where i could not see an effect of the weights, although the seem to be passed down correctly. 

i  only need to solve this, then it will be done.

**Comment by studerus** [comment]
I already wrote an email to the maintainer of `lqa` but didn't get a response so far. I think we should remove the `weights` property from `classif.lqa` for the time being.

**Comment by berndbischl** [comment]
> I already wrote an email to the maintainer of lqa but didn't get a response so far. I think we should remove the weights property from classif.lqa for the time being.

thx for the email. and i do agree with your suggestion. will finish this NOW

**Comment by berndbischl** [comment]
just for reference sake, i tried this. it fails:
```
library(mlbench)
library(lqa)
d = Sonar[59:61]
d$Class = as.numeric(d$Class == "M")
w = rep(1, nrow(d))
w[1:100] = 10000
m1 = lqa(Class ~., data = d, family = binomial(), penalty = ridge(lambda = 0.1), control = lqa.control())
p1 = predict(m1, newdata = d)
m2 = lqa(Class ~., data = d, family = binomial(), penalty = ridge(lambda = 0.1), control = lqa.control())
p2 = predict(m2, newdata = d)
print(range(p1$mu.new - p2$mu.new))
```

it returns 0,0

**Comment by berndbischl** [comment]
classif.ada had the weights tag, but "weights" isnt even supported  in its API

**Comment by berndbischl** [comment]
see my pullrequest for this.
i added a generic unit test now, that should always detect this.

**Comment by berndbischl** [comment]
done
