### ISSUE TITLE
Make a weighted class wrapper of a model multiplexer

### ISSUE THREAD

**Issue by danielhorn** [mlr-org/mlr#862]
Hi,

I'm trying to fuse a model multiplexer with a weighted class wrapper. Since both of my base learner support class weights, this should be possible? Can this be done with mlr? The intuitive way does not work:

```
library(mlr)
bls = list(
  makeLearner("classif.randomForest"),
  makeLearner("classif.svm")
)
classif.lrn = makeModelMultiplexer(bls)
classif.lrn = makeWeightedClassesWrapper(classif.lrn)
Error in makeWeightedClassesWrapper(classif.lrn) : 
  Learner 'ModelMultiplexer' does not support observation weights. You have to set 'wcw.param' to the learner param which allows to set class weights! (which hopefully exists...)
```

The problem is: There is no single class weights param, but 2 different ones. One for each base learner.

**Comment by catastrophic-failure** [comment]
This should work instead:

```splus
library(mlr)
bls = list(
  makeWeightedClassesWrapper(makeLearner("classif.randomForest")),
  makeWeightedClassesWrapper(makeLearner("classif.svm"))
)
classif.lrn = makeModelMultiplexer(bls)

getParamSet(classif.lrn)
```

**Comment by danielhorn** [comment]
It does, but that's not 100% what I would like to have.
Now I get 2 parameters weightedclasses.classif.randomForest.wcw.weight and weightedclasses.classif.svm.wcw.weight. I would like to have a single parameter wcw.weight for my parameter tuning. Is this possible?

You can also convince me that it is a stupid idea to have a single wcw.weight parameter and I want to have one for each base learner. I think the tuning would benefit from a single parameter.

**Comment by catastrophic-failure** [comment]
You can make your own grid where both weights are the same in every evaluation point. Of course, that wouldn't work with other hyperparameter searching strategies, so I agree with you on that.

**Comment by berndbischl** [comment]
nearly solved. I have set up a branch here

https://github.com/mlr-org/mlr/tree/classweightparam_with_modelmultiplexer

**Comment by danielhorn** [comment]
I fear there is still an error:
```
library(mlr)
bls = list(
  makeLearner("classif.randomForest"),
  makeLearner("classif.svm")
)

classif.lrn = makeModelMultiplexer(bls)

classif.lrn = makeWeightedClassesWrapper(classif.lrn,
  wcw.param = c("classif.randomForest.classwt", "classif.svm.class.weights"))
resample(classif.lrn, sonar.task, resampling = makeResampleDesc("Holdout"))

[Resample] holdout iter: 1
Error in setHyperPars2.Learner(learner, par.vals = par.vals[i]) : 
  ModelMultiplexer: Setting parameter classwt without available description object!
You can switch off this check by using configureMlr!
```

After setting
`
configureMlr(on.par.without.desc = "quiet")
`
I get a (hopefully reasonable) result.

**Comment by danielhorn** [comment]
I looks like there is a new error in the above example:

```
library(mlr)
bls = list(
  makeLearner("classif.randomForest"),
  makeLearner("classif.svm")
)
classif.lrn = makeModelMultiplexer(bls)

classif.lrn = makeWeightedClassesWrapper(classif.lrn,
  wcw.param = c("classif.randomForest.classwt", "classif.svm.class.weights"))
resample(classif.lrn, sonar.task, resampling = makeResampleDesc("Holdout"))

[Resample] holdout iter 1: Error in setNames(list(wcw.weight), p) : 
  'names' attribute [2] must be the same length as the vector [1]
```
