### ISSUE TITLE
feature selection for multilabel rferns

### ISSUE THREAD

**Issue by me88** [mlr-org/mlr#866]
Hello, 

First thanks for the package mlr it's really great.

May I ask if it there is a feature selection implementation available in mlr regarding a multilabel algo using Rferns?

==============================================================================
Here is an example where I would like to add feature selection. 
# Libs
rm(list = ls()) #clear workspace
set.seed(1234)
library(mlr)

# Get data and set label
yeast = getTaskData(yeast.task)
labels = colnames(yeast)[1:14]

# Create a task
yeast.task = makeMultilabelTask(id = "multi", data = yeast, target = labels)
yeast.task

# Construct a learner : Algorithm adaptation method
multilabel.lrn2 = makeLearner("multilabel.rFerns")  
multilabel.lrn2

# Train
mod2 = train(multilabel.lrn2, yeast.task, subset = 1:100)
mod2

# Test
pred2 = predict(mod2, task = yeast.task)
names(as.data.frame(pred2))

# Perform
performance(pred2)

**Comment by larskotthoff** [comment]
If you do feature selection with a wrapper method (https://mlr-org.github.io/mlr-tutorial/devel/html/feature_selection/index.html#wrapper-methods), it should work.

**Comment by me88** [comment]
thanks it works
