### ISSUE TITLE
coefficients of makeFeatSelWrapper model

### ISSUE THREAD

**Issue by krz** [mlr-org/mlr#876]
Hi,

when I train a survival model like this:

```
library(survival)
data(ovarian)
surv.task <- makeSurvTask(data = ovarian, target = c("futime", "fustat"))
m1 <- train("surv.coxph", surv.task)
```

I can extract the parameter estimates of the cox model like this:
`coef(m1$learner.model)`

Now I want to perform feature selection before building the Cox model.
I do it like this, hope this is correct:

```
ctrl <- makeFeatSelControlRandom(maxit = 20L)
rdesc <- makeResampleDesc("CV", iters = 5L)
sfeats <- makeFeatSelWrapper(learner = "surv.coxph", resampling = rdesc, control = ctrl, show.info = FALSE)
m2 <- train(sfeats, surv.task)
```

but now I cannot extract the coefficients with
`coef(m2$learner.model)`

as it results in a NULL output.

I am doing something wrong?

**Comment by schiffner** [comment]
Hi,

it is generally better to use function `getLearnerModel` than to directly access the `$learner.model` slots.
For your example:

```
getLearnerModel(m2)

Model for learner.id=surv.coxph; learner.class=surv.coxph
Trained on: task.id = ovarian; obs = 26; features = 3
Hyperparameters: 

getLearnerModel(m2, more.unwrap = TRUE)
Call:
survival::coxph(formula = f, data = data)

            coef exp(coef) se(coef)     z      p
age       0.1285    1.1372   0.0473  2.72 0.0066
resid.ds  0.6964    2.0065   0.7585  0.92 0.3586
rx       -0.8489    0.4279   0.6392 -1.33 0.1842

Likelihood ratio test=16.8  on 3 df, p=0.000789
n= 26, number of events= 12 

getLearnerModel(m1)
Call:
survival::coxph(formula = f, data = data)

            coef exp(coef) se(coef)     z      p
age       0.1248    1.1329   0.0469  2.66 0.0078
resid.ds  0.8262    2.2846   0.7896  1.05 0.2954
rx       -0.9145    0.4007   0.6533 -1.40 0.1616
ecog.ps   0.3362    1.3996   0.6439  0.52 0.6016

Likelihood ratio test=17  on 4 df, p=0.0019
n= 26, number of events= 12 
```

Short explanation why `coef(m2$learner.model)` doesn't work:
A wrapped learner has a more complicated structure with several layers (in your case feature selection and Cox regression), and the output of `train` "mirrors" this structure.
In your case the output from `coxph` is in `m2$learner.model$next.model$learner.model`.
If you wrap your learner a second time you would need to add another `$next.model$learner.model` to access  the innermost model...
So `getLearnerModel` is much simpler (and also the more robust choice in case we decide to change something in the internal structure).

Cheers,
Julia

**Comment by krz** [comment]
thanks!

**Comment by schiffner** [comment]
Welcome! :)

I will close this here. If any more questions come up, feel free to reopen.
