### ISSUE TITLE
measures: Strictly proper scoring rules

### ISSUE THREAD

**Issue by catastrophic-failure** [mlr-org/mlr#880]
There are three famous strictly proper scoring rules: Quadratic, Logarithmic and Spherical.
I added the spherical scoring rule, but I also have coded the other two. There's a issue, the Quadratic scoring rule is simply an affine tranformation of `multiclass.brier` and the Logarithim scoring rule is simply `-1*logloss`. 

Are those two too trivial to be added? I would be fine with that, anyone would be able to calculate those _a posteriori_ with a simple linear transformation. ML begginers could be unaware though.

What do you think?

**Comment by PhilippPro** [comment]
I think it would be ok to have also the affine transformation versions. In fact we also have rmse and mse. 
Maybe in the tutorial we can cluster measures, that are closely related to each other instead of ordering them only alphabetically, for the better overview.

**Comment by catastrophic-failure** [comment]
All right. It's quite trivial, really, Brier Score and Logloss are strictly proper scoring rules, too.

Now, about the implementation itself, should I make new and self contained `measure.quadraticscore` and `measure.logarithmicscore` functions or could I point these to `measure.multiclassbrier` and `measure.logloss`, when these are merged, like it's done on RMSE?

**Comment by berndbischl** [comment]
a) i have no problem to add measures, which are trafos of each other. we also have mmce and acc = 1-mmce. 


b) 
> Now, about the implementation itself, should I make new and self contained measure.quadraticscore and measure.logarithmicscore functions or could I point these to measureMulticlassBrier and measureLogloss, when these are merged, like it's done on RMSE?

either ways is OK, but better style IMHO is to call into the existing measure function. they exist, so we can do exactly that.

repopen if you have more questions. otherwise do the PRs.

AND: THX A LOT FOR ACTIVELY CONTRIBUTING! MUCH APPRECIATED!
