### ISSUE TITLE
Class for heterogenous ensembles

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#882]
This is related to #525 for a new getClassWeightParam method.

We need to distinguish between ensembles in which all learners are the same (eg. Bagging wrapper) and ensembles containing multiple different models (eg. modelMultiplexer, stacking). 

Currently there are only two "heterogenous" ensembles (I think) so we could handle them directly but if there will be more in the future would it make sense to add an additional class to them?

**Comment by berndbischl** [comment]
yes, this makes sense. please refactor, then do a PR.

**Comment by ja-thomas** [comment]
Ok I'm stupid, they are already different classes.

ModelMultiplexer and stacking are of class `BaseEnsemble` while BaggingWrapper and stuff like that is already a `HomogeneousEnsemble`.
