### ISSUE TITLE
Travis: manpage generation fails

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#886]
One upon a time we had the idea that the Rd files can be generated automatically by Travis. @larskotthoff implemented it in the `.travis.yml` but it fails as roxygen2 is not loaded.
Question:
- [ ] Make it work again?
- [ ] Delete that part from `.travis.yml`

**Comment by berndbischl** [comment]
@larskotthoff 

my travis budget is depleted. can you please check this so we can close this?

**Comment by larskotthoff** [comment]
Done.
