### ISSUE TITLE
Why do the ranger-learners not support odered factors?

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#888]
Is there a specific reason, why the ranger learners do not have the `ordered` property set? It seems that the `ranger` random forest implentation correctly handles ordered factors the same way as numeric variables, as you can see in the following example:

    library(ranger)
    dat2 <- dat <- getTaskData(bc.task)
    i <- which(sapply(dat, is.ordered))
    dat2[,i] <- lapply(dat[,i], as.numeric)
   
    set.seed(1)
    p1 <- ranger(Class ~ ., dat)$predictions
    set.seed(1)
    p2 <- ranger(Class ~ ., dat2)$predictions
    all.equal(p1, p2)

**Comment by jakob-r** [comment]
From my point of view you can change it if you want to and include it in a unit test. Maybe wait for a secon opinion.

**Comment by berndbischl** [comment]
yup, we can do a simple PR here. i am pretty sure this was simply an oversight.
