### ISSUE TITLE
wrapper feature selection any book/manual to understand the algos

### ISSUE THREAD

**Issue by me88** [mlr-org/mlr#889]
Hello,

I checked the documentation regarding the following wrapper feature selection algos.

- Exhaustive search (makeFeatSelControlExhaustive),
- Genetic algorithm (makeFeatSelControlGA),
- Random search (makeFeatSelControlRandom),
- Deterministic forward or backward search (makeFeatSelControlSequential)

Documentation mentions parameters available for each of the wrapper feature algos. However, would anyone **recommend a book/manual/website** in order to understand better what does those algos do in details. Understanding them will help to correctely manipulate the params...

Thanks

**Comment by jakob-r** [comment]
Maybe this is of improtance in Thead #451

**Comment by berndbischl** [comment]
this is mentioned in FeatSelControl, all algos are explained here

```

#' @references [Ron Kohavi] and [George H. John],
#' [Wrappers for feature subset selection], Artificial Intelligence Volume 97, 1997, [273-324].
#' \url{http://ai.stanford.edu/~ronnyk/wrappersPrint.pdf}.\cr
```
