### ISSUE TITLE
Question About Accessing Standard Errors in Regression Tasks

### ISSUE THREAD

**Issue by larry77** [mlr-org/mlr#890]
Dear All,
This is a question, not a bug. I paste below a simple snippet in which I use random forest for a simple regression task. My question is, how do I  access the standard errors (se) in the prediction?
Probably i am not asking the model to predict the se and this is the root of my problems.
Any suggestion is appreciated!

#####################################################################
library(mlr)
library(randomForest)
library(parallelMap)

n_cores <- 3

data(BostonHousing, package = "mlbench")
task = makeRegrTask(id = "bh", data = BostonHousing, target = "medv")
removeConstantFeatures(task)

lrn = makeLearner("regr.randomForest") 

ps = makeParamSet(
    makeDiscreteParam("mtry", values = seq(2, 10, by=2)),
    makeDiscreteParam("nodesize", values = 1:5)
    
    )

ctrl = makeTuneControlGrid()

rdesc = makeResampleDesc("RepCV", folds =3, reps = 3, predict="test")

parallelStart("multicore", n_cores)
   

res = tuneParams(lrn, task = task, resampling = rdesc, par.set = ps,
  control = ctrl, show.info=F)

## at this point I update the learner by setting the values of the parameters determined before

lrn = setHyperPars(makeLearner("regr.randomForest"), par.vals = res$x)

## Now I can finally train the learner on the whole train dataset

mm4 = train(lrn, task)

**Comment by schiffner** [comment]
Hi,

as you already suspected you need to ask the model to predict the se.
You can do this by setting `predict.type = "se"` when creating the learner.

Here is a mini example (without tuning and parallelization):
```
lrn = makeLearner("regr.randomForest", predict.type = "se")
mm4 = train(lrn, bh.task)
p = predict(mm4, task = bh.task)
p
Prediction: 506 observations
predict.type: se
threshold: 
time: 2.54
  id truth response        se
1  1  24.0 26.53697 1.7223561
2  2  21.6 22.36886 0.7539356
3  3  34.7 35.14462 0.9498649
4  4  33.4 34.67890 1.2288798
5  5  36.2 34.71675 1.0899630
6  6  28.7 27.60681 0.9117782
```

There is also `getPredictionSE` that extracts the se column for you:
```
head(getPredictionSE(p))
[1] 1.7223561 0.7539356 0.9498649 1.2288798 1.0899630 0.9117782
```

Cheers,
Julia

**Comment by larry77** [comment]
Perfect,
and thanks a lot.
Last question (back to my example, where I also tune the learner): should I specify `predict.type="se"` , both when I invoke  `lrn = makeLearner(...)` to first create the learner before tuning the hyperparameters and after tuning when I set the learner's hyperparameters with `setHyperPars(makeLearner(...))` ?

**Comment by schiffner** [comment]
Hi,

I guess it depends. Here are some random thoughts:

* `tuneParams` doesn't store the predictions and I don't know of a performance measure that needs the se column, so whether se is predicted or not while tuning does not make a difference.
If predicting se is for some reasons computationally expensive it makes sense not to do it (I don't know of a learner where this is the case though).

* On the other hand it might make sense for practical reasons: When you set the hyper pars after tuning you **don't need to create a new learner**, but you can just **update** the learner you already generated before the tuning, like this:
```
lrn = makeLearner(..., predict.type = "se")
## tuning
lrn = setHyperPars(lrn, ...)
```
So setting the `predict.type` beforehand might save you some typing (especially if you want to set many fixed parameters) and might prevent errors (like changing settings for the learner before tuning and forgetting to do this for the second one ...).

**Comment by larry77** [comment]
Thanks a lot. This is the answer I was looking for.
