### ISSUE TITLE
Problem with impute learner

### ISSUE THREAD

**Issue by studerus** [mlr-org/mlr#893]
I experienced a problem using imputeLearner for cross-validation. Here's an example:

    dat = data.frame(y = rnorm(10), a = c(NA, rnorm(9)), b = rnorm(10))
    task = makeRegrTask(data = dat, target = "y")
    impLrn = imputeLearner(makeLearner("regr.rpart"))
    lrn = makeImputeWrapper(makeLearner("regr.lm"), cols = list(a = impLrn))

    #works
    train(lrn, tsk)

    #does not work
    holdout(lrn, task)

> [Resample] holdout iter: 1
> Error in holdout(lrn, task) : 
>   Assertion on 'newdata' failed: Must have at least 1 rows, but has 0 rows.

Does anybody know, what's the problem here? Someone else has also mentioned this problem on [stackoverflow](http://stackoverflow.com/questions/36811709/mlr-package-error-for-imputation)

**Comment by jakob-r** [comment]
Duplicate with #848
