### ISSUE TITLE
Is it possible to apply bagging only to one class?

### ISSUE THREAD

**Issue by enricoferrero** [mlr-org/mlr#894]
I'm working on a [PU learning](https://en.wikipedia.org/wiki/One-class_classification) problem.
I would like to apply bagging only to the unlabelled class, but not to the positive class, as described in [this paper](http://arxiv.org/abs/1402.3144), section 2.2.

Is this possible within the mlr framework? How?

Thank you,

**Comment by krz** [comment]
from my understanding, oversampling the minority class would achieve that:
https://mlr-org.github.io/mlr-tutorial/release/html/over_and_undersampling/index.html

**Comment by enricoferrero** [comment]
The problem I see with this is that in my case the class that I want to apply bagging to (the unlabelled cases) is the majority class. So i would need to apply oversampling to the majority class - I'm not entirely sure it makes sense to do that?

**Comment by berndbischl** [comment]
hi, @enricoferrero 

sorry, one-class classification is not really supported at this stage. so i guess the answer sadly is:
currently you cannot really do this. 

The only (hacky) solution I might point you to is the OverBaggingWrapper. Read what that does, maybe you can "abuse" it to achieve what you want.
