### ISSUE TITLE
Argument "requires" does not work properly in ModelMultiplexer

### ISSUE THREAD

**Issue by philippstats** [mlr-org/mlr#895]
Some parameters require other parameter settings, e.g. in SVM the argument "degree" is only useful if kernel "polynominal" is applied. This works fine when only one learner is used (returns NA at that position). In ModelMultiplexer the "requires" argument does not work as expected: 

```
tsk = subsetTask(pid.task, 1:200)
ctrl = makeTuneControlRandom(maxit = 2L)

# tuning of multiple learners using ModelMultiplexer
mm.lrns = list(
  makeLearner("classif.xgboost", predict.type = "prob"),
  makeLearner("classif.svm", predict.type = "prob"))
mm = makeModelMultiplexer(mm.lrns)

# "most secure" version for parameter set
mm.ps = makeModelMultiplexerParamSet(mm,
  classif.xgboost = makeParamSet(
    makeIntegerParam("nrounds", lower = 30L, upper = 120)),
  classif.svm = makeParamSet(
    makeDiscreteParam("kernel", values = c("linear", "polynomial")),
    makeNumericParam("cost", lower = 2^-12, upper = 2^12),
    makeIntegerParam("degree", lower = 2L, upper = 5L, requires = quote(kernel == "polynomial")))
)
# tuning
set.seed(124)
res.mm = tuneParams(mm, tsk, hout, par.set = mm.ps, control = ctrl)
head(as.data.frame(res.mm$opt.path)[, c(1, 3:5)])
```

This returns values (and not NA) for `classif.svm.degree` although kernel "linear" is used.

```
selected.learner classif.svm.kernel classif.svm.cost classif.svm.degree
1      classif.svm         polynomial         929.2399                  5
2      classif.svm             linear         620.9415                  5
```

**Comment by jakob-r** [comment]
We refactored the handling of requirements but it has not been pulled in yet in ParamHelpers but I coud imagine that this is fixed once we merged https://github.com/berndbischl/ParamHelpers/pull/73 and this branch: https://github.com/mlr-org/mlr/tree/fix_344_default_par_vals

**Comment by philippstats** [comment]
ok, nice! thanks

**Comment by berndbischl** [comment]
we need unit tests that prove that this works before closing. or link to a duplicate

**Comment by mb706** [comment]
(FYI: Possible duplicate of #598; see also #597 for something similar.)
