### ISSUE TITLE
add unit test that learners that claim to handle ordered factors really do this.

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#897]

**Comment by berndbischl** [comment]
solved in PR #959

**Comment by berndbischl** [comment]
@MariaErdmann 
Can you also please add tests for this?

**Comment by berndbischl** [comment]
(i think we currently test for factors but not for ordered)

**Comment by MariaErdmann** [comment]
Oh yes, that is true. I will add a test!

**Comment by berndbischl** [comment]
solved in PR #1003
