### ISSUE TITLE
Wrapper methods featureSelection customisation

### ISSUE THREAD

**Issue by me88** [mlr-org/mlr#903]
Hello, 

Is it possible to use wrapper methods by chosing only a certain amount of features in the search process. 

Imagine I have 90 features {x1 .. x90}. 
For some reasons I want to keep {x80 .. x90} because they are strong business oriented features. 

So how can I add this extra condition (forbid mlr to remove specific features) ? 

Thanks

**Comment by jakobbossek** [comment]
Yes. There is the `fw.mandatory.feat` argument in `makeFilterWrapper` respectively `mandatory.feat` in `filterFeatures`.

**Comment by ja-thomas** [comment]
This question seems answered, I'll close here
