### ISSUE TITLE
2d partial prediction plots

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#922]
Instead of plotting a graph for each value one could plot a ggplot with colors @zmjones.
Just as idea. 

Example code of @RaphaelCouronne: 
```

library(mlr)
library(ggplot2)
library(gridExtra)

## Datas

# Data
data(iris)
lrn.classif = makeLearner("classif.ksvm", predict.type = "prob")
fit.classif = train(lrn.classif, iris.task)

# Partial Dependance Plot
pd.int = generatePartialPredictionData(fit.classif, iris.task, c("Sepal.Width", "Petal.Length"), TRUE)
df=pd.int$data


## Plots 2D

# Virginica
df1=df[which(df=="virginica"),]
maxProba=max(df1$Probability)

ggplot(data = df1, aes(x=Sepal.Width, y=Petal.Length, fill=Probability)) + 
  geom_tile()+
  scale_fill_gradient2(low = "blue", high = "red",
                       midpoint = maxProba/2, limit = c(0,maxProba), space = "Lab",
                       name="Probability")+ ggtitle("virginica")

# Setosa
df2=df[which(df=="setosa"),]
maxProba=max(df2$Probability)

ggplot(data = df2, aes(x=Sepal.Width, y=Petal.Length, fill=Probability)) + 
  geom_tile()+
  scale_fill_gradient2(low = "blue", high = "red",
                       midpoint = maxProba/2, limit = c(0,maxProba), space = "Lab",
                       name="Probability")+ ggtitle("setosa")

# versicolor
df3=df[which(df=="versicolor"),]
maxProba=max(df3$Probability)

ggplot(data = df3, aes(x=Sepal.Width, y=Petal.Length, fill=Probability)) + 
  geom_tile()+
  scale_fill_gradient2(low = "blue", high = "red",
                       midpoint = maxProba/2, limit = c(0,maxProba), space = "Lab",
                       name="Probability")+ ggtitle("versicolor")


```

**Comment by zmjones** [comment]
Yea that is a good idea for plotting 2 feature interactions for multiclass tasks. I think we could do this with facetting no problem. I'll go ahead and implement this. Thanks for the idea!

**Comment by PhilippPro** [comment]
Why not for regression? As far as I see we also get discrete combinations of values for regression with generatePartialPredictionPlot. 

Maybe it would be nice not only to have discrete values but something like a continuos heatmap, but I do not know any R-package that supports this.

**Comment by MasonGallo** [comment]
+1 @zmjones keep me posted - I think we will cross paths as my GSoC work progresses

**Comment by zmjones** [comment]
This is already implemented with regression unless I've understood what you mean.

```{r}
library(mlr) ## github version
fit = train("regr.svm", bh.task)
pd = generatePartialDependenceData(fit, bh.task, c("crim", "age"), interaction = TRUE)
plotPartialDependence(fit, geom = "tile")
```

**Comment by zmjones** [comment]
@MasonGallo for sure. I have another PR incoming adding a data overplotting argument to this but otherwise I have no big changes to the static plots planned. You are writing the set of functions to visualize the hyperparameter optimization path right?

**Comment by MasonGallo** [comment]
Yup! This would also entail implementing partial dependence wrt hyperparameters rather than features, so we should definitely connect at some point in the future to make sure we're aligned.

**Comment by zmjones** [comment]
Ah right ok I remember look at your ipynb on this. That is a cool idea.

**Comment by PhilippPro** [comment]
Oh, very cool, I did not know this is already implemented. I also use it for visualisation of hyperparameter combinations in random forests, so I think I am not so far from MasonGallos work.

**Comment by zmjones** [comment]
Well you guys should check out [this](https://github.com/mlr-org/mlr/pull/917) PR then which adds a functional anova decomposition using partial dependence to estimate the different effects. If you have any advice for how to structure things to make your stuff work more easily let me know. Next thing I'm adding are some methods for  multivariate density estimation to weight pd/fanova. Maybe that would be useful for correlated parameters or with various search methods?

**Comment by MasonGallo** [comment]
Oh great, will do! @PhilippPro I'd love to learn more about your usecase. I'll follow up with you in the next few weeks.

**Comment by PhilippPro** [comment]
If you have time, contact me, so we can make an appointment on hangout.

**Comment by berndbischl** [comment]
hi guys.

can please schedule a call to talk about this topic? we have currently so much "function visualization" code, that this becomes somewhat confusing. how shall we go about this?

**Comment by MasonGallo** [comment]
I would like to join this call if possible to hear the discussion

**Comment by berndbischl** [comment]
> I would like to join this call if possible to hear the discussion

you were asked to join it anyway :)

can some please setup a doodle? possible not for next week but after that?

**Comment by PhilippPro** [comment]
http://doodle.com/poll/8r24evzg5b5qtq9z

Probably only in the evening, as you live in America?

**Comment by MasonGallo** [comment]
I believe @zmjones and I are -6 hours from you and @berndbischl 

My times are in the doodle

**Comment by berndbischl** [comment]
@PhilippPro 
ok the guy who set up the doodle missed inviting us to the best doodled date...
now its already in the past....

new try?

**Comment by zmjones** [comment]
did we just need the three of us in this thread? i am free most of the time! don't know what happened here...

**Comment by PhilippPro** [comment]
Sorry, but there was no date, where all 4 had time. Mainly because of time restrictions of Bernd and Lars. ;) Maybe you can look at the doodle @berndbischl if you have a timeslot somewhere next week.

**Comment by berndbischl** [comment]
lars and me are meeting with jason on 5th july, 19 CET. can you other guys join in 20 CET?

**Comment by PhilippPro** [comment]
yes, I can.

**Comment by PhilippPro** [comment]
yes, I can.

Am 30.06.2016 um 21:19 schrieb Bernd Bischl:

**Comment by berndbischl** [comment]
@zmjones can you quickly replay pls so we can fix this?

**Comment by PhilippPro** [comment]
grid.size is not applicable, when interaction = TRUE:

```
library(mlr) ## github version
fit = train("regr.svm", bh.task)
pd = generatePartialDependenceData(fit, bh.task, c("crim", "age"), interaction = TRUE, grid.size = 20)
plotPartialDependence(pd, geom = "tile")
```
Does the same as grid.size = 10.
