### ISSUE TITLE
fixDataForLearner is bad

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#926]
Look in fixDataForLearnner.R.

Status quo:
- this function is used to "enhance" learner capabilities. 
-  it can do 3 things: 
  -- restore.levels in features. so if factor levels are dropped from features during eg resampling this options restores. 
  verdict: this seems 100% superfluous as we have fix.factors.predictions in makeLearner?
  -- factors.to.dummies: can encode a factor with dummies, so a learner can work on factor features, as well. 
  verdict: this is in principle nice, but: it renders the "factors" property of a learner useless, as we could call this thing now in each base learner. and the latter sucks, you have to add this code in dozens of places. 
  -- ordered.to.int can encode an ordered  factor as int. 
  verdict: this is in principle nice, but see dummy.factors
- the whole code is undocumented 
- we mainly use this function in survival learners currently

**Comment by jakob-r** [comment]
?

**Comment by berndbischl** [comment]
my 2 cents:

- we should remove this now. it would not affect much of the codebase. and like i said, the design seems bad.

- after removal, we can talk about the functionality of  "factors.to.dummies" and "ordered.to.int". mlr should support this. but please in *one*  place. as added functionality for general base learners.
IMHO I would add these as options to makeLearner. as we already have "fix.factors.prediction" here. 
but @mllg seemed to prefer a wrapper. 

please help to make the design better here.

@larskotthoff @schiffner @mllg @jakob-r @giuseppec @ja-thomas

**Comment by larskotthoff** [comment]
I'm ok with removing that code.

A wrapper sounds like a good option for this.

**Comment by berndbischl** [comment]
> A wrapper sounds like a good option for this.

i new that you would say this :)  
i dunno, i am not going to force my opinion here and we could kinda "vote", but my opinion on this is:
- we already have fix.factors.predictions in makeLearner. adding more options to makeLearner here seems more consistent to me 
- for me this whole thing is more closer to the base learner and less about "adding more stuff on top of the learner" (yes, more a "feeling" like a proper argument)
- wrappers are kinda complicated and more verbose

**Comment by schiffner** [comment]
I also don't have totally valid reasons, but:
While "fix.factors.prediction" is, like the name says, a necessary fix, treatment/encoding of categorical features "feels" more like preprocessing to me. Usually, one has several possible options (e.g. treat ordered factors as factors and therefore use dummies vs. encode ordered factors as integers) and either has good reasons to use one option or just try out what works best.
Tuning would work with a wrapper, but we cannot tune over options of makeLearner, right?

**Comment by larskotthoff** [comment]
I guess there's a general question of how much stuff should be options (to makeLearner, or to specific learners) vs. how much stuff should be in wrappers. I think that wrappers are more flexible.

**Comment by berndbischl** [comment]
ok, i see your arguments. i might also lean more towards a wrapper now.

one point i see, about makeLearner: fix.factors.prediction. 
that more a technical thing. and i think mlr shouldnt really need this option. this is actually something we SHOULD fix with simple code in the base learner? because you never want to look up that stupid option?

**Comment by larskotthoff** [comment]
That sounds reasonable to me.

**Comment by catastrophic-failure** [comment]
Just a reference: [R Library: Contrast Coding Systems for categorical variables](http://www.ats.ucla.edu/stat/r/library/contrast_coding.htm) details 8 coding options. Perhaps a Wrapper could help bring all these functionalities? There's also details about the Orthogonal Polynomial Coding and Helmert Coding, which can be useful for ordered factors. There's also dummy coding for ordered factors.

**Comment by berndbischl** [comment]
@catastrophic-failure 

> Just a reference: R Library: Contrast Coding Systems for categorical variables details 8 c

thx! also you seem to follow the package quite closely? do you want better contact to us devels?

**Comment by catastrophic-failure** [comment]
Well, I don't know if I would be able to contribute much more (I have no experience with software development or management btw, I'm just a medical physicist), so I think it's not necessary for now, Git seems to suffice.

**Comment by berndbischl** [comment]
@jklanger 
this is not extremely simple but probably a nice training for code refactoring.

**Comment by jklanger** [comment]
The functions 'fixDataForLearner' and 'getFixDataInfo' are solely used in the 'trainLearner._' and 'predictLearner._' context (8 times), to prepare the data for the learner/predict functions of the packages 'glmnet', 'CoxBoost' and 'mboost'. It does not seem to add functionality, but to prepare the data for functions, which are not able to encode factors to dummies themselves, unlike e.g. lm etc. So far I would see it as a 'fix':

- it doesn't add functionality the user can control

- it can't be deleted from the 'trainLearner._'/'predictLearner._' context of the respective learners, because this would leave them helpless to handle factors. We could include a warning message, that for the usage of this learner, it was necessary to encode factors and ordered. This warning could also mention the possibility to choose a customer encoding, which we would have to add.

My conclusion would be: Leave the code there as a fix for the respective learners, which lack the functionality to encode factors and throw a warning if the encoding was necessary. Also add a possibility for the user to choose his/her own encoding scheme.

**Comment by mllg** [comment]
This is necessary to support r/o tasks. 
Auto-conversions (e.g., character to factor conversions for classif tasks) should be done by the user. fixDataForLearner should be a wrapper.

Blocks #1108 .
