### ISSUE TITLE
Additional/recoded learner params

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#929]
We need to talk about how to integrate additional or recoded learner params properly.
See also #927 and #928.

**Comment by berndbischl** [comment]
here is the answer: doing this is not allowed, in general.

we can make exceptions like here:
https://github.com/mlr-org/mlr/pull/919

but only, RARELY:
a) if there is REALLY no other reasonable way to achieve this
b) if is mentioned in "note" of the learner

for the mtry-stuff you really dont need this you can easily tune from [0,1] with a little extra effort
