### ISSUE TITLE
Truncated precision - recall plots

### ISSUE THREAD

**Issue by enricoferrero** [mlr-org/mlr#937]
Hello

I'd like to visualise the performance of my classifiers using a precision - recall plot.
The problem is that, for some classifiers, these plots appear to be truncated for high precision and low recall values.

Is this a an expected or unexpected behaviour?
If it is expected, how can I interpret these truncated precision - recall curves?

This is the code I'm using:

``` r
bmrk <- benchmark(lrns, subsetTask(classif.task, subset=train.set), rdesc, measures=list(mmce, acc, auc, tpr, tnr, ppv, f1))
pr <- generateThreshVsPerfData(bmrk, measures=list(tpr, ppv))
png(file.path("../data/BenchmarkPR.png"), height=10*300, width=10*300, res=300)
print(
      ggplot(data=pr$data, aes(x=tpr, y=ppv)) +
          geom_path(aes(colour=learner), size=1.5) +
          xlab("Recall") +
          ylab("Precision") +
          scale_colour_brewer(palette="Set1", name="Classifier") +
          theme_bw(base_size=14)
)
dev.off()
```

where `lrns` is a list of learners and `classif.task` is a classification task.

The call to ggplot generates this warning message:

``` r
Warning message:
Removed 6 rows containing missing values (geom_path).
```

And indeed I can see that some classifiers have `NaN` in the `ppv` column corresponding to zero or low values of `tpr`:

``` r
summary(pr$data)
                      learner         tpr              ppv           threshold
 Random Forest            :100   Min.   :0.0000   Min.   :0.5079   Min.   :0.00
 Neural Network           :100   1st Qu.:0.5503   1st Qu.:0.6800   1st Qu.:0.25
 Support Vector Machine   :100   Median :0.6443   Median :0.7306   Median :0.50
 Gradient Boosting Machine:100   Mean   :0.6180   Mean   :0.7311   Mean   :0.50
                                 3rd Qu.:0.7167   3rd Qu.:0.7821   3rd Qu.:0.75
                                 Max.   :1.0000   Max.   :0.9333   Max.   :1.00
                                                  NA's   :6
```

And finally, this is what the plot looks like, you can see that 3 of the 4 curves are truncated:
![benchmarkpr](https://cloud.githubusercontent.com/assets/4481814/16043363/3c520a70-3237-11e6-92c8-bad5da45d7a9.png)

Thank you,

**Comment by berndbischl** [comment]
hi, 

1) we cannot reproduce this.

2) but i guess the answer seems clear. PPV = TP / nr.of.pos.preds.
so if your threshold is so high that you have 0 pos. preds, i guess that NA follows.

@zmjones @schiffner 

what do you think? should we try to "continue" the last feasible value in the plot?

**Comment by berndbischl** [comment]
this is a reproducible example.
(please... really post these)

```
set.seed(1)
task = sonar.task
lrn = makeLearner("classif.rpart", predict.type = "prob")

r = holdout(lrn, task)
d = generateThreshVsPerfData(r, measures = list(tpr, ppv), gridsize = 5)
print(plotROCCurves(d))
```

d$ looks like this, this is exactly the effect i explained above and out plot also contains a truncated curve

```
     tpr    ppv threshold
1 1.0000 0.5429      0.00
2 0.7632 0.7632      0.25
3 0.7632 0.7632      0.50
4 0.6842 0.7647      0.75
5 0.0000    NaN      1.00
```

**Comment by schiffner** [comment]
Hi,

> what do you think? should we try to "continue" the last feasible value in the plot?

I'm too tired to figure this out now, but here is based on your example, Bernd, a comparison of the curves produced by mlr (for better comparability I used an ordinary plot instead of ggplot2) and by ROCR.
The ROCR curve is less truncated and apparently for a threshold/cutoff of 1 goes through (0.13,1). Might be worth a closer look.

```
pr = asROCRPrediction(r$pred)
perf = ROCR::performance(pr, "prec", "rec")
perf
# An object of class "performance"
# Slot "x.name":
# [1] "Recall"

# Slot "y.name":
# [1] "Precision"

# Slot "alpha.name":
# [1] "Cutoff"

# Slot "x.values":
# [[1]]
# [1] 0.0000000 0.1315789 0.6842105 0.7631579 0.8684211 1.0000000


# Slot "y.values":
# [[1]]
# [1]       NaN 1.0000000 0.7647059 0.7631579 0.7333333 0.5428571


# Slot "alpha.values":
# [[1]]
# [1]        Inf 1.00000000 0.89090909 0.68750000 0.13333333 0.08888889

par(mfrow = c(1,2))
plot(ppv ~ tpr, d$data, type = "l", ylim = c(0,1))
plot(perf, ylim = c(0,1))
```

**Comment by schiffner** [comment]
related to #1016
