### ISSUE TITLE
Filter mrmr and generateFilterValuesData

### ISSUE THREAD

**Issue by schiffner** [mlr-org/mlr#940]
* In "mrmr" `nselect` is misleading because one gets one score less than the supplied `nselect`.

* mrmr does not return scores in the original order of the features in the data set.
This is not taken into account when writing the results into the data.frame returned by `generateFilterValuesData` and therefore gives wrong results when more than one filter is used.

I guess it's easiest if mrmr returns the scores in the original order. But maybe this should also be checked in `generateFilterValuesData`.

```
generateFilterValuesData(iris.task, method = c("mrmr", "anova.test"), nselect = 3)
FilterValues:
Task: iris-example
          name    type       mrmr anova.test
1  Sepal.Width numeric 0.03281607  119.26450
2 Sepal.Length numeric         NA   49.16004
3  Petal.Width numeric 0.33922212 1180.16118
4 Petal.Length numeric         NA  960.00715

generateFilterValuesData(iris.task, method = "anova.test")
FilterValues:
Task: iris-example
          name    type anova.test
1 Sepal.Length numeric  119.26450
2  Sepal.Width numeric   49.16004
3 Petal.Length numeric 1180.16118
4  Petal.Width numeric  960.00715
```

**Comment by berndbischl** [comment]
hi @mllg can you please share your thoughts here?
mine so far:

a) 
the mrmr filter code does some very weird and undocumented (!) stuff 
```
    # some required conversions
    ind = vlapply(data, is.factor)
    data[ind] = lapply(data[ind], as.ordered)
    ind = which(vlapply(data, is.integer))
    data[ind] = lapply(data[ind], as.double)
    data = mRMRe::mRMR.data(data = data)
```

the int to double i can kinda understand, but we should not need it? as mlr would do this on task creation and never allows int features to exist anyway? 
but the conversion from factors to ordered? does mrmr recommend that?


b) and now this error, the NA that julia mentions might stem from the problems in a (?)

what i can say now is this

this works - mrmr on regr data, nselect = 2 

``` 
library(mRMRe)
d = iris[, 1:4]
fdata = mRMR.data(data = d)
f = mRMR.classic("mRMRe.Filter", data = fdata, target_indices = 4, feature_count = 2)
s = scores(f)
print(s)
```
output 
``` 
> source("test2.R")
$`4`
         [,1]
[1,]  1.30940
[2,] -0.02944
``` 

this already becomes weird - mrmr on binary classif (with weird as.ordered)

``` 
library(mRMRe)
d = droplevels(iris[1:100,])
d$Species = as.ordered(d$Species) # michel does this, dunno why?
fdata = mRMR.data(data = d)
f = mRMR.classic("mRMRe.Filter", data = fdata, target_indices = 4, feature_count = 2)
s = scores(f)
print(s)
```
output

```
$`4`
        [,1]
[1,]      NA
[2,] -0.1276
```

without the weird "as.ordered" hack mrmr says 
"  data columns must be either of numeric, ordered factor or Surv type"

**Comment by schiffner** [comment]
Re `as.ordered`: The help page on mRMRe.Data-class says:

data: is expected to be a data frame with samples and features respectively organized as rows and columns. The columns have to be of type :numeric, ordered factor, Surv and respectively interpreted as :continuous, discrete and survival variables.

**Comment by berndbischl** [comment]
@schiffner 
ok, but what you just said basically restates what my error message says. but does mrmr actually tell us to recode factor features and factor target variables to ordered ones? and the mrmr compuations still make sense?

**Comment by berndbischl** [comment]
to make my point clearer: by calling as.ordered we basically induce a very arbitrary order on our unordered factors. which i dont like. 

I then looked at the paper here
http://bioinformatics.oxfordjournals.org/content/29/18/2365.long

quote:
```
Correlation between continuous variables can be computed using either Pearson’s or Spearman’s estimators, whereas Cramer’s V is used for correlation between discrete variables and Somers’ Dxy index is used for correlation between continuous variables and survival data.
```

but:
https://en.wikipedia.org/wiki/Cram%C3%A9r%27s_V

is simply defined between nominal variables. it is basically a chi-squared statistics. so why do i have to convert my factors now....?

**Comment by schiffner** [comment]
I understand your point and also think that the "ordered factor thing" is weird.
(Was just hoping because they say that ordered factors are treated as discrete variables that something meaningful would happen.)
Found the same paper as you, hoped to find out what they do with a discrete response and a continuous predictor, but don't know yet, and hope that Michel does.

**Comment by schiffner** [comment]
It seems that the order makes a difference in this case
```
d1 = d2 = iris
d1$Species = as.ordered(d1$Species)
res1 = mRMR.classic(data = mRMR.data(d1), target_indices = 5, feature_count = 3)
scores(res1)
$`5`
           [,1]
[1,]         NA
[2,] 0.33922212
[3,] 0.03281607

d2$Species = factor(d2$Species, levels = levels(d2$Species)[3:1])
d2$Species = as.ordered(d2$Species)
res2 = mRMR.classic(data = mRMR.data(d2), target_indices = 5, feature_count = 3)
scores(res2)
$`5`
            [,1]
[1,]          NA
[2,]  0.74385851
[3,] -0.02789069
```

**Comment by berndbischl** [comment]
I might have it now. what is guessed is this: 

for factors they need the order, to be able to compare factors to continuous features. 
comparing factors to factors they use CRAMERS V and the dont need / use the order. 

you can see this kinda here:

```
runMRMR = function(d, y.i) {
  d[,y.i] = as.ordered(d[, y.i])
  fdata = mRMR.data(data = d)
  f = mRMR.classic("mRMRe.Filter", data = fdata, target_indices = y.i, feature_count = 4)
  scores(f)
}

mycompare = function(d, y.i) {
  print(runMRMR(d, y.i))
  d2 = d
  d2[, y.i]= factor(d2[,y.i], levels = levels(d2[,y.i])[3:1])
  print(runMRMR(d2, y.i))
}

mycompare(iris, 5)

allfacts = iris
for (i in 1:4)
  allfacts[,i] = as.ordered(sample(iris$Species))

mycompare(allfacts, 5)
```


```
# permuting y does have an effect as features are cont (and we get that weird NA???)
$`5`
        [,1]
[1,]      NA
[2,] 0.33922
[3,] 0.03282
[4,] 0.05022

$`5`
         [,1]
[1,]       NA
[2,]  0.74386
[3,] -0.02789
[4,]  0.14921

# permuting y does not have an effect as features and y are both factors

$`5`
         [,1]
[1,] 0.012351
[2,] 0.006068
[3,] 0.004741
[4,] 0.001135

$`5`
         [,1]
[1,] 0.012351
[2,] 0.006068
[3,] 0.004741
[4,] 0.001135
```

**Comment by berndbischl** [comment]
for me the conclusion is: 
i dont see how they support classification or learning with unordered factor features. so that leaves regr with num features only.

and i dont see this as my / our responsibility to figure this out. if somebody can tell us how to do this reliably i am happy to change the code. for now, i dont know what to do except for removing the properties from this learner.

**Comment by schiffner** [comment]
Re your code: Thx, that's what I thought, too.
And I agree with your conclusion.

This leaves the second bullet point about the ordering of the scores. I can look into that tomorrow.

**Comment by schiffner** [comment]
`generateFilterValuesData` actually takes care of ordering the filter values. There was just a mini mistake in the line doing this. PR is #1021 .

**Comment by berndbischl** [comment]
PR #1021 is merged, which looked at the ordering problem. the mrmr problem is still open and not merged.

**Comment by berndbischl** [comment]
@schiffner 
did you do a PR to change mrmr?

**Comment by schiffner** [comment]
> did you do a PR to change mrmr?

No, but I will.
