### ISSUE TITLE
Possible, speculative extensions for mlr

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#944]
This thread here lists possible points of extensions for mlr that we currently dont have time to work on. they are closed in the tracker, so the issue list becomes more readable. 

All of them have the tag "possible enhance later".

**Comment by berndbischl** [comment]
Making a super learner from base learners applied to different parts of the data
https://github.com/mlr-org/mlr/issues/153

**Comment by ja-thomas** [comment]
submodel approaches
#298

**Comment by berndbischl** [comment]
better imbalanced and costsensitive multiclass modelling, see #821

**Comment by zmjones** [comment]
generic interaction detection methods
 - functional anova cost-of-exclusion (the cost of excluding a particular fanova component in terms of approximation error)
 - joint feature importance with lower dimensional feature importances removed (e.g., I(x1, x2) - I(x1) - I(x2)

get interaction detection
 - randomForestSRC terminal node co-occurence matrix (unclear how to reduce to a single score for each possible interaction)
 - upcoming mentch/hooker package (hypothesis tests for interaction graphs), might have to implement this myself

plotting
 - undirected graph
 - bar chart

**Comment by ja-thomas** [comment]
We moved this information to the wiki:

https://github.com/mlr-org/mlr/wiki/List-of-Possible-Enhancements-to-mlr
