### ISSUE TITLE
Visual unit testing

### ISSUE THREAD

**Issue by MasonGallo** [mlr-org/mlr#948]
I noticed that ggplot2 uses [vtest](https://github.com/wch/vtest) for "visual testing".

Any thoughts/concerns on using it for mlr's plotting?

**Comment by zmjones** [comment]
that looks cool. 

for ggplot output we've been writing to to svg and then analyzing the svg files to check for the correct number of lines, points, colors, etc. they are disabled right now though because i haven't fixed them (default color change).

would vtest be able to do this sort of testing too? or would this be something additional.

**Comment by MasonGallo** [comment]
From what I understand of reading the source code for vtest::save_vtest, looks like vtest does that sort of testing using pdfs. 

The benefit here could be that since ggplot2 uses it, it will hopefully adjust to any ggplot changes (so you don't have to go back and edit the mlr tests every time ggplot changes something internally).

**Comment by larskotthoff** [comment]
How does it do the actual comparison? Does it rely on manually inspecting the plots?

**Comment by MasonGallo** [comment]
I haven't had time to test (no pun intended) it out since I just discovered it today. It's on my to do list. It appears to reference hash and imagemagick so I'm curious if it would work across all OS or only linux. 🎱

**Comment by larskotthoff** [comment]
Sounds like it should work on all unix-ish systems, which is what we care about for the automated testing. It doesn't really matter if not every user will be able to run the tests.

**Comment by berndbischl** [comment]
> Sounds like it should work on all unix-ish systems, which is what we care about for the automated testing. It doesn't really matter if not every user will be able to run the tests.

+1
