### ISSUE TITLE
Vignette knit fails with rcheck

### ISSUE THREAD

**Issue by MasonGallo** [mlr-org/mlr#951]
When I run `rcheck` on my Mac, I get the below error:

`It seems you should call rmarkdown::render() instead of knitr::knit2html() because mlr.Rmd appears to be an R Markdown v2 document.`

This is fixed locally by changing `knitr::rmarkdown` to `rmarkdown::rmarkdown` within the file.

Can this be changed in master or is there a reason to keep as is? 

If it can be changed, I'll do the quick PR for it.

**Comment by larskotthoff** [comment]
Hmm, this seems to be a configuration issue. Apparently your default vignette builder is rmarkdown when it should be knitr. It works fine for me (and also on our various build things) and I didn't configure anything, so I'm not sure what's happening. Any ideas anybody?

**Comment by jakob-r** [comment]
Are the code parts executed when you use `rmarkdown::rmarkdown` an an engine? Because that should be the difference.

**Comment by berndbischl** [comment]
@MasonGallo 
can you please update ALL of your packges? does that error still remain?

**Comment by MasonGallo** [comment]
@berndbischl 
the error remains after updating all packages

@jakob-r 
I'm not sure what you mean. Can you clarify please?

**Comment by MasonGallo** [comment]
Following up. Any ideas?

**Comment by berndbischl** [comment]
I just got exactly the same error msg:

```
* installing the package to build vignettes
* creating vignettes ... ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc is not available. Please install both.
Error: processing vignette 'checkmate.Rmd' failed with diagnostics:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because checkmate.Rmd appears to be an R Markdown v2 document.
```

But: Pls note the pandoc version problem before! Updating it as requested completely resolved this then....

**Comment by MasonGallo** [comment]
Thanks! I reinstalled pandoc and pandoc-citeproc on my dev mac with homebrew and I'm all set. 

I will go ahead and close. For anyone who runs into this issue in the future, make sure you have correct versions of pandoc and pandoc-citeproc installed. If you're on a mac, I recommend using homebrew.
