### ISSUE TITLE
generatePartialPredictionData test

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#952]
There is still some tests for `generatePartialPredictionData` in `test_parallel_all.R` which seems to be overseen with #912 

1. How can it be there and not fail?
2. Is `Sys.info()["sysname"] != "Windows"` really the way to go, when we have `testthat::skip_on_os("windows")`?
3. Should this test be kept and renamed or deleted?

**Comment by zmjones** [comment]
i will figure this out today. no idea why that isn't failing. i can just rename it though.

**Comment by zmjones** [comment]
the test didn't fail because it is disabled in `run-parallel.R` for travis. i am not sure it didn't fail locally when i pushed the change however.

**Comment by berndbischl** [comment]
what is the status here? can we please resolve this quickly? is my help needed?

**Comment by zmjones** [comment]
no it is fixed. there was a paramhelpers issue that made the test fail and then when i rebased it i accidentally pushed to master here rather than to my fork, but the build passed so i just left it and closed this.

**Comment by berndbischl** [comment]
so can this issue here be closed?

**Comment by zmjones** [comment]
yes
