### ISSUE TITLE
How to explicitly mention predictors (or by formula) in makeLearner/makeClassifTask?

### ISSUE THREAD

**Issue by ncdingari** [mlr-org/mlr#953]
I could not find an example on how to explicitly mention predictors such as

`makeClassifTask(formula=Y~X1+X2+X3, data=df,...)`

**Comment by jakob-r** [comment]
Just subset your task after creation or create it on a subset:

Solution A:
```r
tsk = makeClassifTask(data=df[, c("X1", "X2", "X3")], target = "Y", ...)
```
Solution B
```r
tsk = makeClassifTask(data=df, target = "Y", ...)
tsk = subsetTask(tsk, features = c("X1", "X2", "X3"))
```

We are not planning to implement a formula interface, but I hope I could help you.

----
note: We are in a discussion at the moment, whether we would prefer those questions on stackoverflow (Issue #947)

**Comment by berndbischl** [comment]
> We are not planning to implement a formula interface, but I hope I could help you.

lets say we are not sure about this. these issues here exist:

https://github.com/mlr-org/mlr/issues/266

https://github.com/mlr-org/mlr/issues/564

and the whole question has come up multiple times. but at least this is not going to be changed very soon.
