### ISSUE TITLE
surv.coxph and surv.ranger can't do probabilites

### ISSUE THREAD

**Issue by MariaErdmann** [mlr-org/mlr#966]
Hi,
surv.coxph and surv.ranger do have properties "prob" but they actually can't do probabilities (yet).
While surv.coxph is throwing an error when predicting that survival cannot do probabilities yet, surv.ranger throws an error when training that the predict type is unknown.
Should the property "prob" be removed from these two learners for now? Or is there something wrong in the example script?

````
# load_all()
# source("/tests/testthat/helper_objects.R")

listLearners("surv", properties = "prob")$class
lrn.coxph = makeLearner("surv.coxph", predict.type = "prob")
m.coxph = train(lrn.coxph, surv.task)
p.coxph = predict(m.coxph, surv.task)
# Error in checkPredictLearnerOutput(.learner, .model, p) : 
# Survival does not support prediction of probabilites yet.


lrn.ranger = makeLearner("surv.ranger", predict.type = "prob")
m.ranger = train(lrn.ranger, surv.task)
# Error in trainLearner.surv.ranger(.learner = list(id = "surv.ranger",  : 
# Unsupported predict type 

````

Cheers,
Maria

**Comment by intiveda** [comment]
Please, in case you remove property 'probs' from the package could you update the documentation?

Do not make people lose their time trying to debug code.

**Comment by larskotthoff** [comment]
Sorry, which documentation are you referring to?

**Comment by intiveda** [comment]
You could find the reference here: 

http://mlr-org.github.io/mlr-tutorial/release/html/integrated_learners/ 
at Survival analysis (13), 

> Additional learner properties:
prob: Probabilities can be predicted

Thank you in advance

**Comment by larskotthoff** [comment]
Ah, sorry about that -- the property got reintroduced accidentally! I've fixed that and you can find the updated tutorial at https://mlr-org.github.io/mlr-tutorial/devel/html/integrated_learners/ once it's been regenerated.
