### ISSUE TITLE
resample without information about fold number (in CV)

### ISSUE THREAD

**Issue by philippstats** [mlr-org/mlr#968]
Hi @berndbischl, 
as discussed I would need information about the fold number during training in cross validation to save models on disc. Thanks!

**Comment by philippstats** [comment]
Hi @berndbischl,
what should we do with this issue. Do it after my defence?

**Comment by jakob-r** [comment]
As the CV folds are independent from each other you can just save them on the disk with a random number and later decide which fold was which number from 1 to 10.

**Comment by philippstats** [comment]
Cool idea. Thanks!
