### ISSUE TITLE
randomforest: sampsize and strata

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr#972]
From the manpage:

> strata	
> A (factor) variable that is used for stratified sampling.

> sampsize	
> Size(s) of sample to draw. For classification, if sampsize is a vector of the length the number of strata, then sampling is stratified by strata, and the elements of sampsize indicate the numbers to be drawn from the strata.

Maybe check for further missing params.

**Comment by berndbischl** [comment]
@MariaErdmann 
can you please add these 2 params and check the help page for other missing params?

**Comment by berndbischl** [comment]
strata: add them to classif.rf and regr.rf. make it "untyped"

sampsize: i guess make it an intvec param then. for classif and regr.

**Comment by berndbischl** [comment]
see discussion in PR.
this needs to be closed ASAP so we dont forget what happened
