### ISSUE TITLE
strata for performance measures

### ISSUE THREAD

**Issue by zmjones** [mlr-org/mlr#975]
one of the issues with using learners with dependent data is that you can end up with overfitting by having performance estimates that are overly optimistic since they are estimated from data that is not independent of the training data. 

basically all of the resampling methods for dependent data that i am aware of (which i guess are the simple ones) work by somehow figuring out groups of the data that should be independent of one another, and resampling those rather than the individual observations. 

it occurs to me that if we simply added, to every performance measure, a strata argument which grouped the measure accordingly and then averaged across the strata, users could do any resampling method that relies on this block-independence. 

this seems like it would be relatively easy for us and rather useful. thoughts?

**Comment by larskotthoff** [comment]
I'm not sure if I understand what you're saying. What's the issue here? How would you group a measure?

**Comment by zmjones** [comment]
actually i think we can do this already using `stratify.cols`. 

what i really meant was computing measures on grouped data wherein the groups are independent.

**Comment by berndbischl** [comment]
ok :)
