### ISSUE TITLE
jenkins mails

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr#976]
I received today 5 jenkins mails, they are a bit annoying, can somebody stop it pls?

**Comment by berndbischl** [comment]
lol i get about a million mails just for mlr per day.
*and* i tend to read them all ;-)

but please directly talk to @larskotthoff to configure this.

**Comment by berndbischl** [comment]
(you do have his mail so i will close this here)

**Comment by larskotthoff** [comment]
Well, I can turn off emails to people who committed changes altogether (with just a static list of people to email). I don't think I can easily exclude specific people or specific builds.

If I turn this off, you won't get any notifications when things break and will have to check yourself. Is this what you want?

**Comment by PhilippPro** [comment]
Yes.

It is strange, because until today I never got such messages. (Maybe 
that was because of my email provider).

Am 29.06.2016 um 18:18 schrieb Lars Kotthoff:

**Comment by berndbischl** [comment]
whether jenkins run is maybe more an info for the core devels anyhow?

**Comment by larskotthoff** [comment]
Ok, I've turned this off for everyone for Bernd and me.

It is now your responsibility to check whether builds have succeeded.
