### ISSUE TITLE
setThreshold() on BenchmarkResults

### ISSUE THREAD

**Issue by enricoferrero** [mlr-org/mlr#985]
Is there a recommended way to change the probability threshold for objects of class `BenchmarkResult`? I'd like to consistently use a 0.75 probability for the positive class in all cross-validation and test instances.

I've tried something like this:

``` r
lapply(getBMRPredictions(bmrk)[[1]], setThreshold, 0.75)
```

but I'm not sure how to assign these values back to the original object so that all subsequent steps reflect the new probabilities. Is there a clean way to do this?

Thank you,

**Comment by berndbischl** [comment]
> Is there a recommended way to change the probability threshold for objects of class BenchmarkResult

not yet, really.

A BechmarkResult (BMR) mainly consists of a list of lists of ResampleResults (RR). This is doced here: ?BenchmarkResult.

So, you basically have to write 2 nested for loops, where for each element you call setThreshold on the RR, and assign this back to the list. Doing this will work and not hurt the integrity of the BMR, as all aggregated measures, and so on are extracted from the list of RRs. And these are adapted by our call to setTRhreshold.

**Comment by berndbischl** [comment]
note that if you do this posthoc, you are kinda "violating" a clean benchmark experiment setup, but that's your choice, we just give you the technology plus potential recommendations ;-)

**Comment by berndbischl** [comment]
i marked this for potential student assistent work.

if we do this, we should provide a simple way possibly, to specify different thresholds for different data sets and/or different learners.

actually: maybe we should simply doc what i outlined here? so we dont blow up the API anymore?

**Comment by berndbischl** [comment]
@florianfendt 
ok, i am not sure we want this, but do this, dont go overboard:

setBMRThreshold(bmr, task.ids, learners.ids).
Defaults for the latter are NULL which means all.
