### ISSUE TITLE
Arguments to predict of custom learner // Howto return more than a single value/vector from predict?

### ISSUE THREAD

**Issue by bkomboz** [mlr-org/mlr#988]
Let's assume we have the following custom learner which consists of two separate models:

    makeRLearner.regr.foo <- function () {
        makeRLearnerRegr(
            cl = "regr.foo",
            package = "stats",
            properties = c("numerics", "factors", "ordered"),
            name = "Foo Combined Model",
            par.set = makeParamSet(makeDiscreteLearnerParam(id = "family", default = "binomial", values = c("binomial"))),
            short.name = "foo"
        )
    }
    
    trainLearner.regr.foo <- function(.learner, .task, .subset, .weights = NULL, ...) {
    
        ## setup data
        data <- getTaskData(.task, .subset, target.extra = TRUE)
        dc <- df <- data$data
    
        ## setup targets
        df$tf <- as.integer(data$target < 10)
        dc$tc <- data$target
    
        ## models
        fm <- glm(as.formula("tf ~ ."), data = df, family = binomial())
        cm <- lm(as.formula("tc ~ ."), data = dc)
    
        ## return
        models <- list("cm" = cm, "fm" = fm)
        return(models)   
    }
    
    predictLearner.regr.foo <- function(.learner, .model, .newdata, ...) {
    
        ## extract individual models and data
        fm <- .model$learner.model$fm
        cm <- .model$learner.model$cm
    
        ## individual predictions
        fpred <- predict(fm, newdata = .newdata)
        cpred <- predict(cm, newdata = .newdata)
    
        ## return
        rv <- fpred * cpred 
        return(rv)
    }

Ideally, I would like `predict` to return a `list/data.frame/matrix` with `fpred` and `cpred` (and maybe also the product of the two). However, as far as I understand this is not possible because `predict` has to return a scalar/vector.

Therefore I tried to add an argument to `predict` to define what it returns, i.e., something like:

    predictLearner.regr.foo <- function(.learner, .model, .newdata, ...) {
    
        ## extract individual models and data
        fm <- .model$learner.model$fm
        cm <- .model$learner.model$cm
    
        ## type
        pars <- list(...)
        type <- if (is.null(pars$type)) "combined" else pars$type
    
        ## individual predictions
        fpred <- predict(fm, newdata = .newdata)
        cpred <- predict(cm, newdata = .newdata)
    
        ## return
        if (type == "probability") {
            rv <- fpred
        } else if (type == "value") {
            rv <- cpred
        } else {
            rv <- fpred * cpred
        }
        return(rv)
    
    }

Unfortunately, I was not successful. Either via `...` as shown above or via an explicit argument it did not work. Any suggestion how to do this is appreciated! Thanks!

**Comment by jakob-r** [comment]
Try
```r
attr(rv, "fpred") <- fpred
attr(rv, "cpred") <- cpred
```
or something along the lines of that. You should be able to access it later via `attr(getPredictionResponse(pred), "fpred")`

**Comment by bkomboz** [comment]
This works, thanks!

**Comment by berndbischl** [comment]
maybe even better option:

just write your predict function completely independent from mlr. 
create your API as you like i.

then in the mlr wrapper, call it, and extract and transform the stuff that is needed for mlr.

that seems to me "optimal" from a design standpoint
