### ISSUE TITLE
plotPartialDependence does not check (and doc) which models can be drawn

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#994]
hi,

this is really a mini issue, but

a) 

```
lrn = makeLearner("classif.rpart")
m = train(lrn, iris.task)
pd = generatePartialDependenceData(m, iris.task)
```

this leads to an uninformative error of 
function argument must return a numeric vector with length equal to the number of target class levels.

but i guess it should tell me that my learner did not predict probs.
you should simply check the passed wrapped model.

b)
the docs also seem to be quite generic. can we please add a few sentences to describe what is drawn? and for what models? like: estimated probs for positive class, what for multiclass, the we dont support it for bla....

**Comment by berndbischl** [comment]
@zmjones 
would you do that?

**Comment by zmjones** [comment]
Yep

**Comment by zmjones** [comment]
I added a more informative error message.

I was looking at the docs for the output and I am not sure what is vague. Under the 'data' part of "object members" it says that you get a columns for predictions, 1 for regression and survival, and a column with a predicted probability for each class. I guess  the only thing omitted is that for binary classification the predict method drops the negative class by default. But that is already documented there.
