### ISSUE TITLE
possibility to relabel objects in container objects for plots

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#999]
Very often you would like to be able to rename certain things like 
- tasks
- features
- classes
- learners
- measures

in container objects before you plot them. this issue came up twice now
https://github.com/mlr-org/mlr/issues/899
https://github.com/mlr-org/mlr/issues/993

it would be nice if we could have a function 

like:
relabelInContainer(object, task.ids=, features=, class.names=, ....) 

should be callable on 
- ResampleResult
- BMR
- all genPlotData containers
- opt.path

this would also allow us to get rid of this pretty.names option? at least this is potential "clash" where to approaches try to do similar things

**Comment by berndbischl** [comment]
yup. before we chaotically implement "something" lets define it first here. or create a prototype, which is criticized, thats also fine

**Comment by jakobbossek** [comment]
All plot functions return `ggplot` object, right? These can be modified in all aspects with the + operator, e.g., axis labels via `xlim(), ylim()`, facet labels via custom `labeller` functions etc. I do not consider adding a set of relabel functions meaningful.

**Comment by berndbischl** [comment]
@jakobbossek 
i am unsure about this. 

a) is it really so simple to relabel EVERYTHING in a ggplot object?

b) imagine you have the container. now you do 10 different plots and tables. where would you change the strings to get a consistent result? in the container....

**Comment by jakobbossek** [comment]
Can you define container? You mean if you glue together different ggplot objects, e.g., with grid.arrange? Yeah, in this case renaming is more difficult.
As far as I know you can change everything in a single ggplot object.

**Comment by berndbischl** [comment]
well maybe the checking is not so hard. we basically have to add examples below all roxygen section of the plots....

**Comment by berndbischl** [comment]
> Can you define container?

ah i see we are misunderstanding each other. sorry. with "container" i mean the nice s3 objects mlr defines, before plots are created. so basically everything that is output by generate*Data. The BMRResult object. and so on.
everything you push INTO a mlr plot* function()

**Comment by jakobbossek** [comment]
Ok. But if one generates a plot he HAS the nice mlr objects at hand and he can have a look at it and the structure of the plot object returned by the plot* functions as well. However, I agree, that this is not easy to understand in more complex cases. E.g. in facetting one needs to find out the names of the variables used for splitting.

**Comment by berndbischl** [comment]
i 100% agree with all what you are saying. 
a) the whole idea of the container objects was to enable something like this. and i sometimes already do this.
b) but we COULD have a bit more convenience here. 
e.g. we have all of these names, short.names, ids, so there could be short function calls to swap them.

**Comment by pat-s** [comment]
We won't implement such new convenience features in _mlr_ anymore. Might be a possible enhancement for _mlr3_ even though I am skeptical if we should add such viz convenience things at all.
